### ISSUE TITLE
我很喜欢这个一眼明了的配置，可是我在使用中，有个lua文件配置的问题，请帮助我，或者提供一下思路，谢谢大大

### ISSUE THREAD

**Issue by 1096015776** [ayamir/nvimdots#1]
我注意到我直接clone下了分支，然后确保了我安装了插件可是，似乎只有在plugin的lua文件的没有生效。
我不知道是我做错了什么吗，我去了galaxyline的官网，按照官网的示例，我将lua的文件设置生效了。但如果每一个都这么做似乎很麻烦，应该是我做错了什么。抱歉浪费你宝贵的时间，希望您能在空闲的时候，帮我看看。
这是直接clone下的coc分支效果图
![截屏2021-06-28 下午7 10 26](https://user-images.githubusercontent.com/40203327/123627367-81ae6d80-d844-11eb-9713-8db623d8829f.png)
这是我按照官网配置后，改变了文件目录的配置
![截屏2021-06-28 下午7 13 53](https://user-images.githubusercontent.com/40203327/123627865-1618d000-d845-11eb-99a1-8445c6ff5901.png)
我注意到似乎连文件名都不能命名为galaxyline只有命名为官网的evailine才会生效，我已尽可能在找我犯的错误，可是我没有找到，我确信我用的最新版本的neovim

**Comment by ayamir** [comment]
我自己clone仓库之后初始化一切都是正常的，可能是macos的问题？

**Comment by ayamir** [comment]
或者你可以把这些lua文件换成vim文件中嵌入lua代码的形式，这样应该不会出现问题

**Comment by 1096015776** [comment]
谢谢您提供的解决方案，我尝试了并且可行。
