### ISSUE TITLE
hi, i have some problem in nvim-tree,help me please

### ISSUE THREAD

**Issue by 1096015776** [ayamir/nvimdots#10]
I try to solve it, but i cannot,i find similiar issue in nvim-tree, i try it but not working,
here you are
https://github.com/kyazdani42/nvim-tree.lua/issues/443
i just want to edit open file don't change my project dir,
beacuse i always edit in projec
could you help me
my english is not ok.

**Comment by 1096015776** [comment]
![截屏2021-08-14 下午2 50 12](https://user-images.githubusercontent.com/40203327/129437871-713013ca-eaca-4850-a7b8-0fe34fa15383.png)
after i edit dir's file
![截屏2021-08-14 下午2 49 43](https://user-images.githubusercontent.com/40203327/129437888-ed8ec483-5a95-4a6a-920b-f60031ec75ab.png)
i try let g:nvim_tree_update_cwd = 0 not work

**Comment by 1096015776** [comment]
i find all setting nvim-tree not work
and someone ask
but i don't know it's same with me
https://github.com/kyazdani42/nvim-tree.lua/issues/562

**Comment by ayamir** [comment]
fixed at https://github.com/ayamir/nvimdots/commit/d4450edbd5de70e646c638288ebe856677e25533 , maybe.
