### ISSUE TITLE
efm linter 看起来没生效

### ISSUE THREAD

**Issue by cyniczhi** [ayamir/nvimdots#100]
用 efm 来进行 format 运行得很好，但是在配置里面看到的 linter 貌似没有生效？我在 c++ 项目下没有看到 clang-tidy 的相关信息。

是和原本的 lsp 冲突了还是需要额外更改 capability 的配置？

**Comment by ayamir** [comment]
如果没有要提示的信息就不会显示的呀

**Comment by cyniczhi** [comment]
如果用 clangd 的话内置的 clang-tidy 是有输出的，换成 ccls+efm 就没了
