### ISSUE TITLE
Installation script uses pnpm instead of npm

### ISSUE THREAD

**Issue by Rehtt** [ayamir/nvimdots#1000]
### Feature description

Installation script uses pnpm instead of npm

**Comment by CharlesChiuGit** [comment]
PR is appreciated  about adding a new option for npm, yarn, pnpm in install script both for sh and pwsh.

**Comment by Jint-lzxy** [comment]
And is there a good reason for using `pnpm` (usually an additional dependency) instead of just `npm` for everyone?

**Comment by CharlesChiuGit** [comment]
for example, some package manager will ship `pnpm` with `nodejs`, but some didn't, like `scoop` on Windows.

u need extra settings to get `pnpm` and `yarn` ready for every distros and OSs.

to avoid this kind of hustle, we tend to use just the standerd installer.

in fact, u can [only use pnpm](https://pnpm.io/only-allow-pnpm) on your own system.

**Comment by ayamir** [comment]
As @Jint-lzxy said, `pnpm` is an additional dependency. It looks better than `npm` but it's not the official tool and maybe not suit every user. So we won't support it.
