### ISSUE TITLE
[autocomplete] line break and autocomplete

### ISSUE THREAD

**Issue by jwangtobeno1** [ayamir/nvimdots#1002]
### Version confirmation

- [X] Confirm

### Following prerequisites

- [X] Confirm

### Neovim version

NVIM v0.9.2

### Branch info

main (Default/Latest)

### Minimal (user) folder structure required to reproduce the issue

```console
Null
```

### Minimal config with steps on how to reproduce the issue

As the picture shows:

![tmp](https://github.com/ayamir/nvimdots/assets/69038155/a7217928-0029-4ccf-ba13-1563c7c29904)

At this point I want to wrap the line, but if I press Enter it will automatically complete it by default.

At this time, I haven't selected the completion item. How can I set it to wrap the line by default instead of automatically completing it?

### Expected behavior

I want to wrap the line, but if I press Enter it will automatically complete it by default.

**Comment by CharlesChiuGit** [comment]
press `Ctrl + e` to close the cmp windows, them press enter.

**Comment by jwangtobeno1** [comment]
How can I set press Enter to auto wrap the line by default?

There is no need to press Ctrl+e to close the cmp window. When auto-comp is required, select it through TAB and press Enter to complete it.

![tmp](https://github.com/ayamir/nvimdots/assets/69038155/d1386727-c770-4eff-8a44-3eb607685b12)

**Comment by CharlesChiuGit** [comment]
check https://github.com/ayamir/nvimdots/blob/main/lua/modules/configs/completion/cmp.lua, https://github.com/ayamir/nvimdots/wiki/Usage#how-to-customize-according-to-your-preferences and https://github.com/hrsh7th/nvim-cmp

**Comment by jwangtobeno1** [comment]
I solved this problem by changing *true* to *false* in the image below

![tmp](https://github.com/ayamir/nvimdots/assets/69038155/9aae2047-6e99-4889-90c3-ef9ed7e86c65)
