### ISSUE TITLE
'autoindent'

### ISSUE THREAD

**Issue by qqphp** [ayamir/nvimdots#1004]
### Version confirmation

- [X] Confirm

### Following prerequisites

- [X] Confirm

### Not a user config issue

- [X] Confirm

### Neovim version

NVIM v0.9.1

### Operating system/version

Ubuntu20.4

### Terminal name/version

Tabby1.0.200

### $TERM environment variable

xterm-256color

### Branch info

main (Default/Latest)

### Fetch Preferences

SSH (use_ssh = true)

### How to reproduce the issue

In my configuration file, when 'autoindent' is set to true, the indentation when wrapping a new line cannot be the same as the previous line. You need to manually enter `:set autoindent`. I'm here to ask for advice, thank you.

### Expected behavior

It can be achieved that the indentation will automatically be consistent with the previous line when wrapping.

**Comment by qqphp** [comment]
In php code files, there is no automatic line wrapping.

**Comment by ayamir** [comment]
`:echo &autoindent` to check whether it's true or false.

**Comment by qqphp** [comment]
lua/modules/configs/editor/treesitter.lua
