### ISSUE TITLE
clang-format failed to use custom .clang-format file while formatting c source code 

### ISSUE THREAD

**Issue by csyJoy** [ayamir/nvimdots#1006]
### Version confirmation

- [X] Confirm

### Following prerequisites

- [X] Confirm

### Not a user config issue

- [X] Confirm

### Neovim version

NVIM v0.9.2

### Operating system/version

macOS 14.0

### Terminal name/version

alacritty 0.12.2 (9d9982d)

### Branch info

main (Default/Latest)

### Fetch Preferences

SSH (use_ssh = true)

### How to reproduce the issue

1. add `.clang-format` file in project root directory to disable `SortIncludes` 

### Expected behavior

clang-format read .clang-format configuration and stop sorting include files

### Actual behavior

include files are still sorted by clang-format

### Additional information

I' m not sure whether this is a bug or just a feature, after removing https://github.com/ayamir/nvimdots/blob/c7b12cacdd8bf1bcd354f07cbfc7dbf4cdc09570/lua/modules/configs/completion/null-ls.lua#L10
clang-format reads my custom .clang-format and acts correctly, It seems that this extra-args and custom .clang-format configuration files are incompatible.

I have already looked up the clang-format and null-ls.nvim documents, but I cann't find enough explanation about `extra-args` in null-ls.nvim, I find `-style` is used to set coding style like .clang-format files. I've try hard to make both of them work  but failed. Do I omit anything important? or `--extra-args` and `.clang-format` are actually incompatiable?

**Comment by Jint-lzxy** [comment]
Hmm Yes, this is _supposed_ to be a "feature" to avoid cases where `clang-format` formats code completely based on its defaults (which vary from version to version) when no "formatting specification" (e.g., `.clang-format`) is provided. Actually, similar issues have popped up many times (#581, #557, #470) and we strongly recommend u do a search on existing issues first (including closed ones) to avoid creating duplicates :D

**Comment by csyJoy** [comment]
oh, sorry for my oversight, these issues actually  answer my questions, I will  search the existing issue first next time, thanks : )
