### ISSUE TITLE
I can not install clang-format and vint with mason

### ISSUE THREAD

**Issue by muausees** [ayamir/nvimdots#1007]
### Version confirmation

- [X] Confirm

### Following prerequisites

- [X] Confirm

### Not a user config issue

- [X] Confirm

### Neovim version

NVIM v0.9.2

### Operating system/version

Windows 11

### Terminal name/version

Windows Terminal 1.17.12191.0

### Branch info

main (Default/Latest)

### Fetch Preferences

SSH (use_ssh = true)

### How to reproduce the issue

Every time I start nvim, it tells me which two packages are being installed, but when I check mason.log, I find that they cannot be installed due to the same issue every time

### Expected behavior

It said "Failed to create python3 virtual enviroment"
![image](https://github.com/ayamir/nvimdots/assets/66890281/1fa9f649-adb5-488b-bb29-f70e4331a029)

**Comment by Jint-lzxy** [comment]
Does `:checkhealth` report that u're using a legacy Python distribution? (similar to https://github.com/ayamir/nvimdots/issues/980#issuecomment-1704055076)

**Comment by muausees** [comment]
OK, I solved it
