### ISSUE TITLE
how to remove `f` find word

### ISSUE THREAD

**Issue by Penguin-SAMA** [ayamir/nvimdots#1008]
### Version confirmation

- [X] Confirm

### Following prerequisites

- [X] Confirm

### Neovim version

NVIM v0.10.0-dev-951+g5d8ab32f3-Homebrew

### Branch info

main (Default/Latest)

### Minimal (user) folder structure required to reproduce the issue

```console
plugins/custom.lua
```

### Minimal config with steps on how to reproduce the issue

```lua
custom["folke/flash.nvim"] = {
	lazy = true,
	event = "VeryLazy",
	opts = {},
	keys = {
		{
			"s",
			mode = { "n", "o", "x" },
			function()
				require("flash").jump()
			end,
			desc = "Flash",
		},
		{
			"S",
			mode = { "n", "o", "x" },
			function()
				require("flash").treesitter()
			end,
			desc = "Flash Treesitter",
		},
		{
			"r",
			mode = "o",
			function()
				require("flash").remote()
			end,
			desc = "Remote Flash",
		},
		{
			"R",
			mode = { "o", "x" },
			function()
				require("flash").treesitter_search()
			end,
			desc = "Treesitter Search",
		},
		{
			"<c-s>",
			mode = { "c" },
			function()
				require("flash").toggle()
			end,
			desc = "Toggle Flash Search",
		},
	},
}
```

### Expected behavior

I want to use flash.nvim.
how to modify the 'fx' keymap.

**Comment by CharlesChiuGit** [comment]
what do u mean? we didn't define `fx` in our default keymaps

**Comment by Penguin-SAMA** [comment]
<img width="742" alt="image" src="https://github.com/ayamir/nvimdots/assets/50973632/8fe32114-0e76-465a-8c71-57f4653ca4d1">
this

**Comment by CharlesChiuGit** [comment]
it's relate to plugin `clever-f`. u cant modify the keymaps from `user/` right now, u need to directly modify `/lua/keymaps/tool.lua`.

**Comment by Jint-lzxy** [comment]
> I want to use flash.nvim.
how to modify the 'fx' keymap.

One possible alternative is to disable `clever-f` and remove its associated mappings:
- append the following to `user/settings.lua`:
```lua
settings["disabled_plugins"] = { "rhysd/clever-f.vim" }
```
- Disable `n|;` and `n|,` in `lua/keymap/editor.lua`:
```lua
return {
	["n|;"] = false, -- or ""
	["n|,"] = false, -- or ""
}
```

**Comment by Penguin-SAMA** [comment]
> > I want to use flash.nvim.我想使用 flash.nvim。
> > how to modify the 'fx' keymap.如何修改“fx”键盘映射。
> 
> One possible alternative is to disable `clever-f` and remove its associated mappings:一种可能的替代方法是禁用 smart-f 并删除其关联的映射：
> 
> * Append the following to `user/settings.lua`:将以下内容附加到 user/settings.lua：
> 
> ```lua
> settings["disabled_plugins"] = { "rhysd/clever-f.vim" }
> ```
> 
> * Disable `n|;` and `n|,` in `user/keymap/editor.lua`:禁用n|；和 n|，在 user/keymap/editor.lua 中：
> 
> ```lua
> return {
> 	["n|;"] = false, -- or ""
> 	["n|,"] = false, -- or ""
> }
> ```

this didn't work

**Comment by Jint-lzxy** [comment]
> this didn't work

Have you registered `f` under `flash.nvim`?

**Comment by Penguin-SAMA** [comment]
> Have you registered f under flash.nvim?

I have not modified the configuration of flash.nvim
I think it's registered by default

**Comment by Jint-lzxy** [comment]
> I think it's registered by default

What do u observe when u press `f<char>` now? And what do u expect to see?

**Comment by Penguin-SAMA** [comment]
press `f` like this 
<img width="665" alt="image" src="https://github.com/ayamir/nvimdots/assets/50973632/e4d2172c-3047-4f0f-aeb6-aa825408aa2b">

i hope like this 
![image](https://github.com/ayamir/nvimdots/assets/50973632/fc0f2d3d-c7d8-496c-8562-cf558db8fd2f)

**Comment by ayamir** [comment]
The reason why your config and @Jint-lzxy 's advice doesn't work is your minimal config is wrong.
1. create `lua/user/plugins/editor.lua`
2. fill it with following content:
```lua
local custom = {}

custom["folke/flash.nvim"] = {
	lazy = true,
	event = "VeryLazy",
	opts = {},
	keys = {
		{
			"s",
			mode = { "n", "o", "x" },
			function()
				require("flash").jump()
			end,
			desc = "Flash",
		},
		{
			"S",
			mode = { "n", "o", "x" },
			function()
				require("flash").treesitter()
			end,
			desc = "Flash Treesitter",
		},
		{
			"r",
			mode = "o",
			function()
				require("flash").remote()
			end,
			desc = "Remote Flash",
		},
		{
			"R",
			mode = { "o", "x" },
			function()
				require("flash").treesitter_search()
			end,
			desc = "Treesitter Search",
		},
		{
			"<c-s>",
			mode = { "c" },
			function()
				require("flash").toggle()
			end,
			desc = "Toggle Flash Search",
		},
	},
}

return custom
```
3. Follow @Jint-lzxy advice.
Then this plugin works for me.

**Comment by Penguin-SAMA** [comment]
Sorry, when I created the file and filled in the content above, I got this error
<img width="1103" alt="image" src="https://github.com/ayamir/nvimdots/assets/50973632/86430ac8-22d2-45a1-8d6b-76dadad2ac53">

I don't know if there is something wrong with my file structure
<img width="2560" alt="image" src="https://github.com/ayamir/nvimdots/assets/50973632/9bf677b2-c534-4a85-9c7d-8a362d84645b">

**Comment by ayamir** [comment]
> Sorry, when I created the file and filled in the content above, I got this error <img alt="image" width="1103" src="https://user-images.githubusercontent.com/50973632/271782668-86430ac8-22d2-45a1-8d6b-76dadad2ac53.png">
> 
> I don't know if there is something wrong with my file structure <img alt="image" width="2000" src="https://user-images.githubusercontent.com/50973632/271782834-9bf677b2-c534-4a85-9c7d-8a362d84645b.png">

pull the latest repo config.

**Comment by Penguin-SAMA** [comment]
The flash.nvim is now working properly.
However, I still receive the same error message whenever I open any file.

> Sorry, when I created the file and filled in the content above, I got this error
![image](https://github.com/ayamir/nvimdots/assets/50973632/5a8225c8-d0a3-4d63-b88d-c42d07ca8b6b)

**Comment by CharlesChiuGit** [comment]
> The flash.nvim is now working properly. However, I still receive the same error message whenever I open any file.
> 
> > Sorry, when I created the file and filled in the content above, I got this error
> > ![image](https://user-images.githubusercontent.com/50973632/271828376-5a8225c8-d0a3-4d63-b88d-c42d07ca8b6b.png)

#1011

**Comment by Penguin-SAMA** [comment]
> @Penguin-SAMA #1011

I'm sorry, but I didn't understand. Could you please clarify which changes should be made in which file?

**Comment by vollowx** [comment]
It means, the latest conf doesn't has this problem as #1011 has been merged. You should `git pull` the conf again, and solve the probable conflicts.

If there're conflicts you still don't how to solve them, you can give the screenshot of `git pull`.

**Comment by Penguin-SAMA** [comment]
@vollowx 
Thank you very much, you are right. I apologize for asking a foolish question.
