### ISSUE TITLE
`telescope` cant load extension `fzf`

### ISSUE THREAD

**Issue by CharlesChiuGit** [ayamir/nvimdots#1009]
### Version confirmation

- [X] Confirm

### Following prerequisites

- [X] Confirm

### Not a user config issue

- [X] Confirm

### Neovim version

v0.10.0-dev-3387dc4

### Operating system/version

macOS 13.6 / arch

### Terminal name/version

wezterm

### Branch info

main (Default/Latest)

### Fetch Preferences

SSH (use_ssh = true)

### How to reproduce the issue

1. fresh install nvimdots. ( I have check related plugins had installed successfully.)
2. call `:Telescope fzf`
3. error log:
![image](https://github.com/ayamir/nvimdots/assets/32497323/079c27b4-41de-49eb-8f98-d94d545c40c9)

### Expected behavior

extension `fzf` load successfully.

### Additional information

I have tried reproduce it on both `macOS m2` and `arch`.

Other methods I had tried to solve this issue:
1. `cd ~/.local/share/nvim/site/lazy/telescope-fzf-native.nvim` and do `make clean && make`.
	- the build succeed, the `libfzf.so` is in `build/`.
2. Add `~/.local/share/nvim/site/lazy/telescope-fzf-native.nvim/build` to `$PATH`.
3. cp `libfzf.so` to `...//lazy/telescope-fzf-native.nvim/` as https://github.com/ayamir/nvimdots/issues/326#issuecomment-1326587295 suggested.
4. `:checkhealth` didn't seem to give any useful info too. Here's the [health log](https://github.com/ayamir/nvimdots/files/12735162/test.txt)

non of above seem to work, so i'm here for some wisdom. also i'm not sure if this is a upstream issue or not, but i didn't seem to find related issue in `telescope-fzf-native.nvim` and `telescope.nvim`'s issues.

**Comment by Jint-lzxy** [comment]
I remember this being mentioned somewhere before:

> `:Telescope fzf` is not a valid command. It replaces an internal function that handles the sorting. We should never use that directly.

b/c I can find this quote in one of my inbox snapshots, but I seem to have forgotten where it belongs :(

**Comment by CharlesChiuGit** [comment]
omg, i just never learned.🥲
tks for pointing it out! i'll try it again tomorrow!

**Comment by CharlesChiuGit** [comment]
can confirm, silly me lol
