### ISSUE TITLE
当我使用 Alt + Shift + Q 关闭窗口会报错

### ISSUE THREAD

**Issue by low-py** [ayamir/nvimdots#101]
![image](https://user-images.githubusercontent.com/29934976/161048908-174a0bb5-4fa9-4097-9d45-b937db0fcfc9.png)

如图，关闭右侧的window会报错，是不是我使用了zsh 的shell？

**Comment by ayamir** [comment]
https://github.com/ayamir/nvimdots/blob/16401b3adf95525c5037d9d4574bac0bc6f4faaf/lua/core/mapping.lua#L26
`<A-S-q>`执行的命令是`q!<CR>`，你想说的是不是`<A-q>`？

**Comment by low-py** [comment]
直接按 A-S-q 不能退出吗， 还有 move current buffer to right  这个命令<A-S-k> 不起作用

**Comment by ayamir** [comment]
> 直接按 A-S-q 不能退出吗， 还有 move current buffer to right 这个命令 不起作用

move current buffer to right是正常的啊，你是不是把buffer和分屏的搞混了

**Comment by ayamir** [comment]
> 还有一个小bug， 当我按F5在右侧新建了个窗口了，然后在右窗口使用 :q 退出了之后，主窗口的tab上还保留着这个窗口的tab ![image](https://user-images.githubusercontent.com/29934976/161096723-2fd18195-bd99-46e3-9882-eae55d861a6b.png) ![image](https://user-images.githubusercontent.com/29934976/161096783-75a2a747-02fd-42da-9520-53d081c3dad1.png)

右边的窗口就是你自己的终端，你应该用`<C-d>`这种退出正常shell的命令退出而不是vim的命令

**Comment by low-py** [comment]
作者大大建个微信交流群呗，有问题可以及时问你吗，我现在已安装了vim-go和GoInstallBinary，但是写代码的时候自动提示还是不够，比如fmt的自动提示就没出来，按g+d也没反应

**Comment by ayamir** [comment]
https://github.com/ayamir/nvimdots/issues/21#issuecomment-908051818
