### ISSUE TITLE
Font display problem

### ISSUE THREAD

**Issue by jwangtobeno1** [ayamir/nvimdots#1010]
### Version confirmation

- [X] Confirm

### Following prerequisites

- [X] Confirm

### Neovim version

NVIM v0.9.2

### Branch info

main (Default/Latest)

### Minimal (user) folder structure required to reproduce the issue

```console
No modified
```

### Minimal config with steps on how to reproduce the issue

I am running nvim on WSL, and the font is set to JetBrainsMono Nerd Font, but some fonts are not fully displayed in nvim, as shown in the figure below:

This is in Vim
![tmp1](https://github.com/ayamir/nvimdots/assets/69038155/26dfbc21-6d92-467d-bc32-368d0bd0ad55)

This is in Nvim:
![tmp](https://github.com/ayamir/nvimdots/assets/69038155/7998ab58-04a5-46e4-b088-8d113b73082c)

In nvim, there is a problem with the display of ‘0’

### Expected behavior

How to slove it?

**Comment by jwangtobeno1** [comment]
When I add `(abcd` at the end, the `0` can be displayed correctly, but there is another problem with `d`

![tmp](https://github.com/ayamir/nvimdots/assets/69038155/920b0682-cfe1-46a1-826e-4d8c3c0f4181)

**Comment by CharlesChiuGit** [comment]
it got nothing to do with nvim config, set your terminal font properly or use another terminal.

**Comment by jwangtobeno1** [comment]
Could you please tell me what font you used?

**Comment by CharlesChiuGit** [comment]
I use jetbrains-nerd-fonts with wezterm.
u can check my wezterm config: https://github.com/CharlesChiuGit/dotfiles/tree/main/terminals/wezterm

**Comment by CharlesChiuGit** [comment]
u can use this plugin in our nvim config to display those error messages.
https://github.com/folke/trouble.nvim#commands

**Comment by Jint-lzxy** [comment]
> The above problem is solved only if I use italic font........

Are u using a font collection (which usually contains multiple variants such as Normal, **Bold**, _Italic_, **_BoldItalic_**, etc.) as the preferred font for ur terminal? Because if u only use a specific variant, ur terminal could reasonably assume that the containing glyphs all fit in a specific scaled "box", and using italics here (possibly "simulated" by ur terminal) would then lead to the problem you mentioned above.

**Comment by jwangtobeno1** [comment]
> > The above problem is solved only if I use italic font........
> 
> Are u using a font collection (which usually contains multiple variants such as Normal, **Bold**, _Italic_, **_BoldItalic_**, etc.) as the preferred font for ur terminal? Because if u only use a specific variant, ur terminal could reasonably assume that the containing glyphs all fit in a specific scaled "box", and using italics here (possibly "simulated" by ur terminal) would then lead to the problem you mentioned above.

thank u very much!!  u say is right. I only have a specific variant of font installed.

**Comment by yinghaoyu** [comment]
I love `SauceCodePro Nerd Font Mono`, but some icons cannot be successfully displayed. It's so sad.
![无标题](https://github.com/ayamir/nvimdots/assets/42765754/c2be496f-d73b-4e30-96ad-43d0ba6ac214)

**Comment by CharlesChiuGit** [comment]
@yinghaoyu make sure your nerdfont is up-to-date, or u need https://github.com/loichyan/nerdfix
