### ISSUE TITLE
invalid require path with missing "user" when add a new plugin

### ISSUE THREAD

**Issue by double12gzh** [ayamir/nvimdots#1014]
### Version confirmation

- [X] Confirm

### Following prerequisites

- [X] Confirm

### Neovim version

NVIM v0.9.1

### Branch info

main (Default/Latest)

### Minimal (user) folder structure required to reproduce the issue

```console
follow https://github.com/ayamir/nvimdots/wiki/Usage#setps-to-add-a-new-plugin
```

### Minimal config with steps on how to reproduce the issue

follow the [user guide](https://github.com/ayamir/nvimdots/wiki/Usage#setps-to-add-a-new-plugin) to add a new plugin

### Expected behavior

-  issue
should replace "configs.editor.todo-comments"  with "user.configs.editor.todo-comments"  in [user guide](https://github.com/ayamir/nvimdots/wiki/Usage#setps-to-add-a-new-plugin)

```lua
local custom = {}

custom["folke/todo-comments.nvim"] = {
        lazy = true,
        event = "BufRead",
        config = require("user.configs.editor.todo-comments"), -- Require that config
}

return custom
```
- typo
shoudl replace "setps " with "steps" in [guide](https://github.com/ayamir/nvimdots/wiki/Usage#setps-to-add-a-new-plugin)

### Additional information

not any

**Comment by Jint-lzxy** [comment]
> should replace "configs.editor.todo-comments" with "user.configs.editor.todo-comments" in [user guide](https://github.com/ayamir/nvimdots/wiki/Usage#setps-to-add-a-new-plugin)

I remember this being documented somewhere:
> **Note:** `lua/user` is in the search path of `require`. So instead of requiring `user.configs.editor` you should use `configs.editor` instead.

See:
https://github.com/ayamir/nvimdots/blob/2b84dbb109eda37030104739841b067239222ca3/lua/core/pack.lua#L26-L34
