### ISSUE TITLE
How can I jump to `glance.nvim`'s floating window

### ISSUE THREAD

**Issue by fakeczg** [ayamir/nvimdots#1015]
### Feature description

比如我通过gd，调出定义，在1和2两个plane中的切换，有没有办法通过键盘，似乎现在我只能通过鼠标来切换；
![图片](https://github.com/ayamir/nvimdots/assets/54363314/c5bcf965-9a6f-4cad-87e2-59549bcc6063)

**Comment by ttbug** [comment]
Ctrl + w  上下左右键就可以切换了吧

**Comment by CharlesChiuGit** [comment]
https://github.com/ayamir/nvimdots/blob/2b84dbb109eda37030104739841b067239222ca3/lua/core/mapping.lua#L16-L19

**Comment by fakeczg** [comment]
> https://github.com/ayamir/nvimdots/blob/2b84dbb109eda37030104739841b067239222ca3/lua/core/mapping.lua#L16-L19

通过以前vim的，切出去是切不回去的，您试试；gd弹出框，然后c+k出去，c+j回不去；

**Comment by CharlesChiuGit** [comment]
dont we suppose to close the reference pane first and go back to coding?

also, it's called pane not code plane.

**Comment by ayamir** [comment]
You can use `<C-q>` to save the results to quickfix window and use `<C-k>` and `<C-j>` to switch.

**Comment by fakeczg** [comment]
> dont we suppose to close the reference pane first and go back to coding?
> 
> also, it's called pane not code plane.

对的，一般是这样的，但是我想试试有时候有这样的需求- -

**Comment by Jint-lzxy** [comment]
Agree with CharlesChiuGit, [glance.nvim](https://github.com/DNLHC/glance.nvim) is supposed to be used this way by design (the preview window is essentially a float). But u could use `<C-w><C-w>` to let Neovim try to jump into the previous floating window, this may or may not work but is worth a shot.

**Comment by fakeczg** [comment]
> Agree with CharlesChiuGit, [glance.nvim](https://github.com/DNLHC/glance.nvim) is supposed to be used this way by design (the preview window is essentially a float). But u could use `<C-w><C-w>` to let Neovim try to jump into the previous floating window, this may or may not work but is worth a shot.

ok.thanks!
