### ISSUE TITLE
indent-blankline conflict

### ISSUE THREAD

**Issue by jwangtobeno1** [ayamir/nvimdots#1018]
### Version confirmation

- [X] Confirm

### Following prerequisites

- [X] Confirm

### Not a user config issue

- [X] Confirm

### Neovim version

NVIM v0.9.2

### Operating system/version

Arch WSL2

### Terminal name/version

windows terminal

### Branch info

main (Default/Latest)

### Fetch Preferences

SSH (use_ssh = true)

### How to reproduce the issue

I update package today with `<Space>+pc`. But when I open the file with nvim, it's show:

" You are trying to call the setup function for indent-blankline version 2, but you already have version 3 installed. Check out the github wiki for instructions on how to migrate or revert to version 2 "

### Expected behavior

How to fix the Issue？

**Comment by CharlesChiuGit** [comment]
#1011

**Comment by jwangtobeno1** [comment]
Is this a new feature? 

![tmp](https://github.com/ayamir/nvimdots/assets/69038155/f1747d99-c37f-4ee7-9359-6f357e9dcf71)

**Comment by CharlesChiuGit** [comment]
just pull the latest config, i'm sure if it's your personal config.

**Comment by jwangtobeno1** [comment]
This situation still exists after I pull the latest config

**Comment by CharlesChiuGit** [comment]
1. u r not using our default colorscheme, so i dont know if it was caused by your colorscheme of choice.
2. check your user config again

**Comment by CharlesChiuGit** [comment]
> spawn: go failed with exit code - and signal -. go is not executable

it means u need to install golang

**Comment by jwangtobeno1** [comment]
If I don't need golang, how do I close this installation? Is it commenting out here?

`lua/core/setting.lua`

![IMG_20231012_164202.jpg](https://github.com/ayamir/nvimdots/assets/69038155/7fe4d917-4f36-41cf-9f0e-c491ec85bbf4)

**Comment by CharlesChiuGit** [comment]
https://github.com/ayamir/nvimdots/wiki/Usage#about-user-overrides-settings-options-events-etc

**Comment by jwangtobeno1** [comment]
doesn't work

user/settings.lua
![tmp](https://github.com/ayamir/nvimdots/assets/69038155/3e5293cb-bc06-4640-a226-749d0cbe5e85)

core/settings.lua
![tmp1](https://github.com/ayamir/nvimdots/assets/69038155/3afeebe4-1a5b-4587-8e92-41e0f2205a4a)

**Comment by jwangtobeno1** [comment]
> 1. u r not using our default colorscheme, so i dont know if it was caused by your colorscheme of choice.
> 2. check your user config again

what is our default colorscheme? 

> Is this a new feature?
> 
> ![tmp](https://user-images.githubusercontent.com/69038155/274497869-f1747d99-c37f-4ee7-9359-6f357e9dcf71.jpg)

Could this new feature be caused by my updating the package(`<space>+pc`) today?

**Comment by Jint-lzxy** [comment]
> Is this a new feature?

It's [nvim-treesitter-context](https://github.com/nvim-treesitter/nvim-treesitter-context). See https://github.com/ayamir/nvimdots/pull/707 for more information (this was merged quite a while ago).

**Comment by jwangtobeno1** [comment]
Looks like I haven't synced in a long time :)

**Comment by yinghaoyu** [comment]
Did you slove this problem?

**Comment by CharlesChiuGit** [comment]
@yinghaoyu 
just pull the latest commit.

**Comment by CharlesChiuGit** [comment]
@yinghaoyu he doesn't install golang, that's why he can't download those lsp, u guys have different issues.
