### ISSUE TITLE
Error occurs when entering '.'

### ISSUE THREAD

**Issue by Penguin-SAMA** [ayamir/nvimdots#1023]
### Version confirmation

- [X] Confirm

### Following prerequisites

- [X] Confirm

### Not a user config issue

- [X] Confirm

### Neovim version

NVIM v0.10.0-dev-951+g5d8ab32f3-Homebrew

### Operating system/version

macos 14

### Terminal name/version

iterm 2

### Branch info

main (Default/Latest)

### Fetch Preferences

SSH (use_ssh = true)

### How to reproduce the issue

Every time I type a character followed by '.', I encounter the following error. What could be causing this issue?
<img width="1512" alt="image" src="https://github.com/ayamir/nvimdots/assets/50973632/815aa72e-01a7-4f53-8124-896f686b756c">

### Expected behavior

No errors should occur.

**Comment by ayamir** [comment]
Try `Lazy sync` first.

**Comment by Penguin-SAMA** [comment]
I've already tried it, but it didn't work.

**Comment by CharlesChiuGit** [comment]
Cant reproduce on my mac mini m2 (macos 14)

**Comment by ayamir** [comment]
Are you using the latest config? We pinned its version in #1003 .

**Comment by Penguin-SAMA** [comment]
> Are you using the latest config? We pinned its version in #1003 .

Yes, I am using the latest version.

**Comment by Penguin-SAMA** [comment]
> Cant reproduce on my mac mini m2 (macos 14)

 I conducted the following experiment: I created a new test.cpp file and only entered the code below. When I typed world., there was no error. However, after copying the entire content of the original file into the new one, the error still occurred.
<img width="947" alt="image" src="https://github.com/ayamir/nvimdots/assets/50973632/e159de5e-b60f-4d9f-86be-b3d8ccef1373">

**Comment by Penguin-SAMA** [comment]
I believe I've pinpointed the trigger for the issue. In my project, I have both hittable_list and camera classes. The error occurs when I type world. after adding the camera class.
<img width="1512" alt="image" src="https://github.com/ayamir/nvimdots/assets/50973632/2204f9bc-fa47-45d1-be8c-f9747c65a7c0">
<img width="1512" alt="image" src="https://github.com/ayamir/nvimdots/assets/50973632/b05907da-c8a1-4406-a636-b504635a7cd1">

**Comment by Jint-lzxy** [comment]
I remember I was able to reproduce this sometime before. But roughly two months ago, one commit seemed to have (at least partially) fixed this issue. As a workaround, u can either enforce the missing status check by editing [these two lines](https://github.com/zbirenbaum/neodim/blob/9477da03b93f1984a81fee3b92e6ac7c6ada6aa4/lua/neodim/ts_override.lua#L48-L50):
```diff
-            local cur_hl = vim.api.nvim_get_hl(0, { id = hl, link = false })
+            local ok, cur_hl = pcall(vim.api.nvim_get_hl, 0, { id = hl, link = false })
 
-            if not hl_map[capture_name] and cur_hl and cur_hl.fg then
+            if not hl_map[capture_name] and ok and cur_hl and cur_hl.fg then
```
or open an issue upstream.

**Comment by Penguin-SAMA** [comment]
thx, it's work
