### ISSUE TITLE
pylsp delete all text when formatting

### ISSUE THREAD

**Issue by nkta3m** [ayamir/nvimdots#1025]
### Version confirmation

- [X] Confirm

### Following prerequisites

- [X] Confirm

### Not a user config issue

- [X] Confirm

### Neovim version

NVIM v0.9.4 Build type: Release LuaJIT 2.1.1692716794

### Operating system/version

Debian

### Terminal name/version

alacritty

### Branch info

main (Default/Latest)

### Fetch Preferences

HTTPS (use_ssh = false)

### Affected language servers

pylsp

### How to reproduce the issue

1. open python file
2. save

### Actual behavior

normal format 

### Support info

![2023-10-18 14_47_02-Window](https://github.com/ayamir/nvimdots/assets/13484700/aa299df6-926d-48c8-baf3-9cf91d3c6a08)
![2023-10-18 14_47_25-Window](https://github.com/ayamir/nvimdots/assets/13484700/d7a2f109-5eaa-453e-b798-b7f7e62530ce)

### Logs

```console
[ERROR][2023-10-18 14:41:56] .../vim/lsp/rpc.lua:734	"rpc"	"~/.local/share/nvim/mason/bin/pylsp"	"stderr"	"2023-10-18 14:41:56,891 CST - ERROR - pylsp_ruff.plugin - Error running ruff: error: unexpected argument '--format' found\n\n  tip: to pass '--format' as a value, use '-- --format'\n\nUsage: ruff check <--verbose|--quiet|--silent> [FILES]...\n\nFor more information, try '--help'.\n\n"
```

**Comment by CharlesChiuGit** [comment]
seems like an upstream error have u check their repo yet?

**Comment by nkta3m** [comment]
no, i don't know how to configure pylsp.

**Comment by ayamir** [comment]
In fact, `ruff` is not responsible for formatting, it just provides the code lint function. `black` is installed to do format. I have no idea about the error log.

![image](https://github.com/ayamir/nvimdots/assets/61657399/ae5e7f58-1083-4a85-8220-c91f26748c8e)

**Comment by nkta3m** [comment]
Is it possible to specify the version of pylsp?

**Comment by ayamir** [comment]
> Is it possible to specify the version of pylsp?

You reminded me. I upgraded the latest `pylsp`. This bug can be reproduced for `pylsp` (version==1.8.2)

**Comment by ayamir** [comment]
The workaround is to use `black` via `null-ls` and disable the format function from `pylsp`.
Add These lines to `lua/user/settings.lua`.
```lua
settings["server_formatting_block_list"] = {
	pylsp = true,
}

settings["null_ls_deps"] = {
	"black",
}
```

**Comment by nkta3m** [comment]
Great, thanks!

**Comment by nkta3m** [comment]
Upstream has been fixed, reinstalling the plugin will solve the problem
