### ISSUE TITLE
未输入前自动显示补全? 打开neovim后无法立刻执行NvimTreeToggle?

### ISSUE THREAD

**Issue by Ritzier** [ayamir/nvimdots#103]
![Screenshot 2022-04-20 225050](https://user-images.githubusercontent.com/85002404/164259073-3583d86a-45d4-4fb9-875a-1f3a6b69e14b.png)
你好, 怎么在还没输入前自动显示补全？
就像Visual Studio里的补全一样

https://user-images.githubusercontent.com/85002404/164266300-0ee35c62-c945-43b5-af51-e725915a7ad9.mp4

每次打开Neovim时马上执行NvimTreeToggle无效

----------------------------------------------------------------
![Screenshot 2022-04-20 232558](https://user-images.githubusercontent.com/85002404/164266613-a67274d5-79d5-47d6-a302-e7383c93d393.png)

建议在ui/plugin.lua里的'wfxr/minimap.vim' 添加:
do: ':!cargo install --locked code-minimap'

**Comment by ayamir** [comment]
1. 第一个问题应该暂时没办法解决。
2. 第二个问题已经修复。
3. 第三个问题因为这种方式还是会依赖rust工具链，因为需要的只是这个包，对于那些不写rust的用户来说我认为他们并没有必要绕圈子装cargo之后再编译安装，不如让根据他们自己的方式直接装code-minimap，比如arch系可以通过pacman、mac用户可以通过homebrew等

**Comment by Ritzier** [comment]
好吧，谢谢
