### ISSUE TITLE
Neorg mode issue

### ISSUE THREAD

**Issue by samos667** [ayamir/nvimdots#1034]
### Version confirmation

- [X] Confirm

### Following prerequisites

- [X] Confirm

### Neovim version

NVIM v0.9.4

### Branch info

main (Default/Latest)

### Minimal (user) folder structure required to reproduce the issue

```console
lua/user/configs/tools/neorg.lua
lua/user/plugins/tools.lua
```

### Minimal config with steps on how to reproduce the issue

my user/plugins/tools.lua
```lua
local custom = {}

custom["nvim-neorg/neorg"] = {
        lazy = true,
        build = ":Neorg sync-parsers",
        config = require("configs.tools.neorg"),
        dependencies = { "nvim-lua/plenary.nvim" },
        event = "VeryLazy",
}

return custom
```
my user/configs/tools/neorg.lua
```lua
return function()
        require("neorg").setup({
                load = {
                        ["core.defaults"] = {}, -- Loads default behaviour
                        ["core.concealer"] = {}, -- Adds pretty icons to your documents
                        ["core.keybinds"] = {}, -- Adds keybindings
                        ["core.journal"] = {}, -- Enables support for the journal modules
                        ["core.completion"] = {
                                config = {
                                        engine = "nvim-cmp",
                                },
                        },
                        ["core.dirman"] = { -- Manages Neorg workspaces
                                config = {
                                        workspaces = {
                                                notes = "~/notes",
                                        },
                                },
                        },
                },
        })
end
```

### Expected behavior

Keybind defined for neorg mode is not applied.
:neorg workspace notes
Put this command open my workspace notes and take me in neorg mode and should have this proper keybind. 
Example: 
```lua
{ leader .. "nn", "core.dirman.new.note", opts = { desc = "Create New Note" } },
```
Defined by default in https://github.com/nvim-neorg/neorg/blob/main/lua/neorg/modules/core/keybinds/keybinds.lua

But when I input expected keys nothing append and also telescope key maps show me only this 3 keybinds:
![image](https://github.com/ayamir/nvimdots/assets/50653464/00b8400e-4c9a-44aa-bfca-cff7ac568898)

### Additional information

Commit hash of my nvimdot repo: 647c23f9973fbb4a1228948afeb792e15b8c04a0

**Comment by ayamir** [comment]
We fixed the error mentioned in #1030 at 874b413a4450ab9557380659456587afde2d0418. You should correct the `config` option's value to `require("configs.tools.neorg")` first if you are using latest config.

**Comment by samos667** [comment]
It's just done but it's not resolve the problem. I've edited the issue with the modification that I have made.

**Comment by ayamir** [comment]
You lacked the line of `return custom` in `lua/user/plugins/tools.lua`.

**Comment by samos667** [comment]
Sorry... I have badly copy past the file to the issue. It's updated.
![image](https://github.com/ayamir/nvimdots/assets/50653464/a3f83f43-6757-40b9-8f46-ce13b1f7e5f0)

**Comment by ayamir** [comment]
I don't know how to use `neorg` but I think you should map the `<LocalLeader>` first as its wiki said.
![图片](https://github.com/ayamir/nvimdots/assets/61657399/0706c427-fd0c-431b-8ea1-83011f12bcff)

**Comment by samos667** [comment]
Thanks that was that the local leader key is "\" mb.
https://learnvimscriptthehardway.stevelosh.com/chapters/06.html
