### ISSUE TITLE
Unknow code In Command line

### ISSUE THREAD

**Issue by yinghaoyu** [ayamir/nvimdots#1036]
### Version confirmation

- [X] Confirm

### Following prerequisites

- [X] Confirm

### Not a user config issue

- [X] Confirm

### Neovim version

nvim v0.9.4

### Operating system/version

WSL2-Ubuntu20.04

### Terminal name/version

Windows Terminal

### Branch info

main (Default/Latest)

### Fetch Preferences

SSH (use_ssh = true)

### How to reproduce the issue

`Ctrl + z` to sleep nvim, then I had taken `fg` to weak up, It shows unknow code like `?61;6;7;22;23;24;28;32;42c` in  nvim command line.
![微信截图_20231025101206](https://github.com/ayamir/nvimdots/assets/42765754/3bd6005f-fd90-4512-b0d7-1f6648cf2b68)

### Expected behavior

It shouldn't happend.

**Comment by ayamir** [comment]
Can't repro.

https://github.com/ayamir/nvimdots/assets/61657399/17c36125-3721-4d99-86fe-73969ce8b115

**Comment by yinghaoyu** [comment]
I had reproduced it on two different hosts.

https://github.com/ayamir/nvimdots/assets/42765754/fa63e447-3d1b-4622-9c59-30c77a89c1f6

**Comment by Jint-lzxy** [comment]
Hmm, this might be related to your installed plugins (e.g., one of them mistakenly emitted ANSI color codes to colorize your prompt). Looks like you are using `zsh`, can you reproduce this with zsh's "factory defaults"?
```sh
env -u PS1 zsh --no-rcs --no-globalrcs --interactive
```

**Comment by yinghaoyu** [comment]
It also appears in `bash`.

**Comment by Jint-lzxy** [comment]
> It also appears in `bash`.

Do you mean you can reproduce this using both `zsh` and `bash` (with factory defaults)?

**Comment by yinghaoyu** [comment]
Yeah

**Comment by Jint-lzxy** [comment]
Hmm this is a bit weird since none of us can reproduce this, maybe u could try out a different emulator or just use Neovim's built-in terminal (via toggleterm)?

**Comment by yinghaoyu** [comment]
> Hmm this is a bit weird since none of us can reproduce this, maybe u could try out a different emulator or just use Neovim's built-in terminal (via toggleterm)?

We could't fix it, so avoid it. Hahahaha.

**Comment by CharlesChiuGit** [comment]
https://github.com/wez/wezterm/issues/4167

https://github.com/microsoft/terminal/issues/15693

https://stackoverflow.com/questions/77338019/tmux-starts-up-with-some-gibberish-in-the-prompt

seems like it happens in various places, but nobody knows why.

**Comment by yinghaoyu** [comment]
> [wez/wezterm#4167](https://github.com/wez/wezterm/issues/4167)
> 
> [microsoft/terminal#15693](https://github.com/microsoft/terminal/issues/15693) -> this explains why.
> 
> https://stackoverflow.com/questions/77338019/tmux-starts-up-with-some-gibberish-in-the-prompt
> 
> It's not a nvim config issue. I think the quickest solution for u is to roll-back to windows terminal v1.17.

orz

**Comment by CharlesChiuGit** [comment]
@yinghaoyu so is it good to close the issue?

**Comment by yinghaoyu** [comment]
Let it go.
