### ISSUE TITLE
Telescope.vim complains sqlite library not found

### ISSUE THREAD

**Issue by skywolf-dl** [ayamir/nvimdots#104]
**Describe the bug**
After cloning and automatically installing all plugins, seeing error message in command mode as shown in attachment.

**To Reproduce**
1. Follow guideline to install;
2. Open nvim and press ":" to go to command mode;

**Expected behavior**
No error message found.

**Screenshots**
See attachment.

**Environment (please complete the following information):**
 - OS: Ubuntu in VMWare Fusion on MacOS
 - Nvim version(output of `nvim --version`)
NVIM v0.6.1
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by team+vim@tracker.debian.org

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info

**Additional context**
I thought the issue was because missing sqlite libraries, hence I installed sqlite with "sudo apt install sqlite3 sqlite3doc" and confirmed  "sqlite3" is available as system command, but I did not find out libsqlite3.so in my system. I am not sure what does the nvim plugin expect to find the so file, will it install its own version by itself or not? Or maybe I should reinstall the plugin after installing sqlite3 in OS?

**Note: Any issue without any information will be closed directly, Please value our time.**
![Screen Shot 2022-04-22 at 11 13 09](https://user-images.githubusercontent.com/3191719/164591160-ed46d1b6-06ae-4afa-a2d8-18bcb62a593d.png)

**Comment by ayamir** [comment]
`sudo apt install libsqlite3-dev`

**Comment by skywolf-dl** [comment]
Great! Thanks a lot!
