### ISSUE TITLE
Alpha header display issue

### ISSUE THREAD

**Issue by HerveyB3B4** [ayamir/nvimdots#1043]
### Version confirmation

- [X] Confirm

### Following prerequisites

- [X] Confirm

### Not a user config issue

- [x] Confirm

### Neovim version

nvim v0.9.4

### Operating system/version

Arch Linux(Gnome Desktop)

### Terminal name/version

zsh in Console

### Branch info

main (Default/Latest)

### Fetch Preferences

SSH (use_ssh = true)

### How to reproduce the issue

When I modified the terminal font to `JetBrainsMono Nerd Font Mono` still shows anomalies.
Does it need to install additional fonts/software packages?
![Pasted image](https://github.com/ayamir/nvimdots/assets/145422807/34c4c294-6db1-458f-9094-1a2fe45b8e4e)
![Pasted image 1](https://github.com/ayamir/nvimdots/assets/145422807/6d7a2cce-9b07-4796-ba7f-a2b1e4c522e9)

### Expected behavior

Viewing `ui.lua` in github using browser also fails to display properly.
![Pasted image 2](https://github.com/ayamir/nvimdots/assets/145422807/410a9815-61ed-40e3-b814-5450b3fa19dd)

**Comment by CharlesChiuGit** [comment]
update your nerdfont pkg

**Comment by HerveyB3B4** [comment]
I tried `nerdfix` and my nerdfont is up-to-date.
But it's still not working...
![image](https://github.com/ayamir/nvimdots/assets/145422807/0ce687cd-e984-4365-92bc-1ddc8555f87e)
![image](https://github.com/ayamir/nvimdots/assets/145422807/3330fee7-eaaf-4cae-baf1-63d6b75b3929)

**Comment by Jint-lzxy** [comment]
Does ur terminal (and ur current `locale`) support full range UTF-8 characters? Can u reproduce this using a different terminal?

**Comment by yinghaoyu** [comment]
Just download nerd font at [Nerd Font](https://www.nerdfonts.com/), I had fixed the same problem.

**Comment by HerveyB3B4** [comment]
> Does ur terminal (and ur current `locale`) support full range UTF-8 characters? Can u reproduce this using a different terminal?

This is my  current`locale`:
![image](https://github.com/ayamir/nvimdots/assets/145422807/3971ee04-1968-41b0-82e6-f35746f57381)

When I use `Kitty` open `nvim`, it works.
![image](https://github.com/ayamir/nvimdots/assets/145422807/c0942c23-74aa-4664-aa6b-3c7fdbb571af)

 But when I use 'Console', it doesn't work.
![image](https://github.com/ayamir/nvimdots/assets/145422807/d3e906ea-c822-48f1-934c-470a8d91e80a)

Maybe it's `Console`'s problem.

**Comment by ayamir** [comment]
We highly recommend you use `kitty` or `wezterm` as your terminal emulator, both of them support GPU-accelerate.
