### ISSUE TITLE
`Lspsaga diagnose_jump_next` error with `'replacement string' item contains newlines` in rust-analyzer lsp

### ISSUE THREAD

**Issue by csyJoy** [ayamir/nvimdots#1064]
### Version confirmation

- [X] Confirm

### Following prerequisites

- [X] Confirm

### Not a user config issue

- [X] Confirm

### Neovim version

NVIM v0.9.4

### Operating system/version

macOS 14.0

### Terminal name/version

alacritty 0.12.3 (5efb069)

### Branch info

main (Default/Latest)

### Fetch Preferences

SSH (use_ssh = true)

### Affected language servers

rust-analyzer

### How to reproduce the issue

1. `cargo new foo`
2. nvim foo/src/main.rs
3. replace with the following code 
```rust
fn main() {
    let mut bt: BTreeMap<i32, i32> = BTreeMap::new();
}
```

4. save the file and current buffer will be like this:
<img width="1714" alt="image" src="https://github.com/ayamir/nvimdots/assets/58020450/ac182a56-97f2-4d8f-8949-96f3283a6881">

5. use `:Lspsaga diagnostic_jump_prev` in line 2 and you will get an error:
<img width="1645" alt="image" src="https://github.com/ayamir/nvimdots/assets/58020450/93879326-29af-4e7c-859f-04308d686b5c">
and the error window spawned remain blank:
<img width="1600" alt="image" src="https://github.com/ayamir/nvimdots/assets/58020450/d3f0749e-4e7a-4dee-ae01-b6ed45868069">

### Actual behavior

```
Error executing Lua callback: ...share/nvim/site/lazy/lspsaga.nvim/lua/lspsaga/window.lua:118: 'replacement string' item contains newlines
stack traceback:
        [C]: in function 'nvim_buf_set_lines'
        ...share/nvim/site/lazy/lspsaga.nvim/lua/lspsaga/window.lua:118: in function 'setlines'
        ...m/site/lazy/lspsaga.nvim/lua/lspsaga/diagnostic/init.lua:313: in function 'render_diagnostic_window'
        ...m/site/lazy/lspsaga.nvim/lua/lspsaga/diagnostic/init.lua:423: in function 'move_cursor'
        ...m/site/lazy/lspsaga.nvim/lua/lspsaga/diagnostic/init.lua:437: in function 'goto_next'
        ...hare/nvim/site/lazy/lspsaga.nvim/lua/lspsaga/command.lua:41: in function <...hare/nvim/site/lazy/lspsaga.nvim/lua/lspsaga/command.lua:40>
        ...hare/nvim/site/lazy/lspsaga.nvim/lua/lspsaga/command.lua:74: in function 'load_command'
        ...cal/share/nvim/site/lazy/lspsaga.nvim/plugin/lspsaga.lua:8: in function <...cal/share/nvim/site/lazy/lspsaga.nvim/plugin/lspsaga.lua:7>
```

### Expected behavior

Lspsaga spawn error window within error message and code action correctly

### Support info

Lspinfo:
<img width="882" alt="image" src="https://github.com/ayamir/nvimdots/assets/58020450/62cf5b5d-0279-4209-aa7d-205211fc93b1">

:Mason
<img width="1033" alt="image" src="https://github.com/ayamir/nvimdots/assets/58020450/cef7375d-0e13-47c8-895a-b5b0292c05e0">

### Additional information

I add `vim.print()` in `setlines` function in `Lspsaga`:
```lua
function obj:setlines(lines, row, erow)
  row = row or 0
  erow = erow or -1
  vim.print(lines)
  api.nvim_buf_set_lines(self.bufnr, row, erow, false, lines)
  return self
end
``` 
here is the result of the line information:
```
{ "cannot find type `BTreeMap` in this scope", "not found in this scope", "main.rs(1:0): consider importing this struct: `use std::collections::BTreeMap;\n\n`" }
```

PS: this time I've taken a look at existing issues including this repository as well as lspsaga.nvim but find nothing similar. Forgive me if there's something I've missed that I haven't picked up on, I didn't mean to do it : )

**Comment by vollowx** [comment]
consider reporting to lspsaga?

**Comment by csyJoy** [comment]
after reporting, lspsage fix this issue https://github.com/nvimdev/lspsaga.nvim/commit/87786212c30e36d37478f8a6c30c1d9a98db4751
