### ISSUE TITLE
关于自带nerd font的问题

### ISSUE THREAD

**Issue by JerryAllison** [ayamir/nvimdots#1069]
### Feature description

关于安装nvimdots碰到的问题：
经过测试，在Mac 和Linux桌面安装运行没有任何问题，非常好用，但是通过xshell或securCRT或Termius等客户端软件连接到远程服务器上就会出现字符显示的问题，因为远程桌面没有nerd font，所以安装nvimdots的安装是否可以自动安装一些nerd font，这样用户体验会非常好。

**Comment by ayamir** [comment]
It's because these ssh clients doesn't support nerd fonts. You can try [tabby](https://tabby.sh/) or [warp](https://www.warp.dev/).

**Comment by JerryAllison** [comment]
> 你的理解是错误的。
> 
> ```c++
> bool symbols_displayed_normally = nerd_font_installed_on_local_machine && ssh_client_support_nerd_fonts
> ```
> 
> 上面的 ssh 客户端根本不支持 nerd 字体。 You can try [tabby](https://tabby.sh/) or [warp](https://www.warp.dev/).

Thanks
