### ISSUE TITLE
使用非‘catppuccin’主题如'edge'等其它主题时 LSP diagnostic 没有下划线

### ISSUE THREAD

**Issue by liuyangzys** [ayamir/nvimdots#107]
# 问题描述
使用 ```edge```、```gruvbox```、```tokyonight``` 等主题时，```lsp diagnostic``` 无下划线显示效果。

# 操作步骤
1. 使用 branch main
2. 确保配置好 lsp server 等环境，使用默认配置编辑文件工程，可正常看到 lsp diagnostic 的下划线提示
3. 将主题切换为 tokyonight，重新启动 nvim 再次编辑，lsp diagnostic 、补全等都正常，唯一区别是 diagnostic 的下划线部分无了

# 输出结果
1. 使用 ```catputtin``` 结果如下，diagnostic 下划线正常
![image](https://user-images.githubusercontent.com/19203871/164883583-adc3d42c-96df-448d-b001-ac446eb0c88f.png)

2. 使用 ```tokyonight``` 或 ``edge``` 等其它主题，则没有下划线，单 diagnostic 信息是正常的
![image](https://user-images.githubusercontent.com/19203871/164884051-7259c643-ea77-4fbe-8892-f9d7449a3015.png)

# 操作环境
windows 11
nvim 0.7
lsp cpptools/su

**Comment by ayamir** [comment]
你现在的配置更新到仓库的最新状态了吗

**Comment by liuyangzys** [comment]
不是配置的原因，可能是 Windows Terminal 显示波浪线的问题，我使用 nvim-qt 就能显示了，但是在  Windows Terminal 中显示有问题。catppuccin 主题对 diagnostic 的提示是下划直线，所以没问题。
 
![image](https://user-images.githubusercontent.com/19203871/164887101-fe87df75-b242-4190-a31e-7cc7f17df1c6.png)
