### ISSUE TITLE
black background color of `fidget.nvim` when global setting `transparent_background` is true

### ISSUE THREAD

**Issue by csyJoy** [ayamir/nvimdots#1070]
### Version confirmation

- [X] Confirm

### Following prerequisites

- [X] Confirm

### Not a user config issue

- [X] Confirm

### Neovim version

NVIM v0.9.4

### Operating system/version

macOS 14.0

### Terminal name/version

alacritty 0.12.3 (5efb069)

### $TERM environment variable

xterm-256color

### Branch info

main (Default/Latest)

### Fetch Preferences

SSH (use_ssh = true)

### How to reproduce the issue

1. set `settings["transparent_background"] = true` in `lua/core/setting.lua`
2. open a file with lsp attached(to check `fidget.nvim` behavior)

### Expected behavior

the background of `fidget.nvim` notification should be transparency

### Actual behavior

black background color:
<img width="525" alt="image" src="https://github.com/ayamir/nvimdots/assets/58020450/bc2a7b0f-7ba9-4322-82b4-21d5f6f22366">

### Additional information

The only thing I change in `main` branch is the `transparent_background` setting. I also test this in `iTerm2` and get the same result.

I do a bisect in main branch and find commit #1068 causes this problem, is this a upstream issue or just a inconsistency configuration problem?

**Comment by Jint-lzxy** [comment]
Have you updated ur plugins via `:Lazy sync`? `fidget.nvim` has [undergone numerous modifications recently](https://github.com/j-hui/fidget.nvim/compare/legacy...main).

**Comment by csyJoy** [comment]
Stupid me! while switching to main branch to check, I discard the change of lock file, sorry for wasting your time and thank you for your help
