### ISSUE TITLE
close diagnostic virtual_text

### ISSUE THREAD

**Issue by fakeczg** [ayamir/nvimdots#1071]
### Feature description

lua vim.diagnostic.config({virtual_text = false})
Is this command invalid?

**Comment by CharlesChiuGit** [comment]
https://github.com/ayamir/nvimdots/blob/88e1b03e806d626801a8bf729e0b1ef9ad6b0697/lua/core/settings.lua#L39

**Comment by CharlesChiuGit** [comment]
dont use issue unless it's a bug. use discussions instead.

**Comment by fakeczg** [comment]
> dont use issue unless it's a bug. use discussions instead.

ok.thanks!
