### ISSUE TITLE
Error Message Appearing After Treesitter Update

### ISSUE THREAD

**Issue by Penguin-SAMA** [ayamir/nvimdots#1084]
### Version confirmation

- [X] Confirm

### Following prerequisites

- [X] Confirm

### Not a user config issue

- [X] Confirm

### Neovim version

NVIM v0.10.0-dev-951+g5d8ab32f3-Homebrew

### Operating system/version

macos 14

### Terminal name/version

iterm 2

### Branch info

main (Default/Latest)

### Fetch Preferences

SSH (use_ssh = true)

### How to reproduce the issue

such as 
<img width="1508" alt="image" src="https://github.com/ayamir/nvimdots/assets/50973632/831f0da3-ec0b-4582-84a3-ce20587c75c0">
<img width="1510" alt="image" src="https://github.com/ayamir/nvimdots/assets/50973632/a56b64b8-a76c-436f-8fc6-3c2ba11eab91">

### Expected behavior

How to Clear These Error Messages

**Comment by CharlesChiuGit** [comment]
it's fixed, update your config
