### ISSUE TITLE
What does `+prefix` mean in which-key's popup?

### ISSUE THREAD

**Issue by Winson-030** [ayamir/nvimdots#1086]
### Version confirmation

- [X] Confirm

### Following prerequisites

- [X] Confirm

### Neovim version

NVIM v0.9.4

### Branch info

main (Default/Latest)

### Minimal (user) folder structure required to reproduce the issue

```console
main 分支的原始配置，没有修改
```

### Minimal config with steps on how to reproduce the issue

main 分支的原始配置，没有修改

### Expected behavior

系统是macos，终端是iterm2，使用的字体是 jetbrainmono
问题已经在图片中圈出，prefix 文字丢失（这样表达是否准确？），nerd font 不显示。
请问我需要到哪个文件进行修改？

### Additional information

![neovim fix](https://github.com/ayamir/nvimdots/assets/100707097/7df2c760-ac73-468f-be18-227449f1082d)

**Comment by Jint-lzxy** [comment]
> IMO we can add some key-mappings like `<Leader>b` with label of `sub: Buffers` that binds to `<Ignore>` for better accessibility for new users.

But in this case, users wouldn't be able to trigger which-key's popup by typing `<leader>b`. Or maybe we could consider just [registering this mapping in which-key](https://github.com/folke/which-key.nvim?tab=readme-ov-file#%EF%B8%8F-mappings)?

**Comment by vollowx** [comment]
exactly what I mean :100:

**Comment by Cyberczy** [comment]
> IMO we can add some key-mappings like `<Leader>b` with label of `sub: Buffers` that binds to `<Ignore>` for better accessibility for new users.

like this?
![image](https://github.com/ayamir/nvimdots/assets/109653523/c5f9da44-1dd4-4fef-9c8b-5b2987258b4d)

**Comment by Cyberczy** [comment]
> > IMO，我们可以添加一些键映射，例如绑定`<Leader>b`的标签，以便新用户更好地访问。`sub: Buffers``<Ignore>`
> 
> 像这样？ ![图像](https://private-user-images.githubusercontent.com/109653523/293749055-c5f9da44-1dd4-4fef-9c8b-5b2987258b4d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQyMTcyMDgsIm5iZiI6MTcwNDIxNjkwOCwicGF0aCI6Ii8xMDk2NTM1MjMvMjkzNzQ5MDU1LWM1ZjlkYTQ0LTFkZDQtNGZlZi05YzhiLTViMjk4NzI1OGI0ZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEwMlQxNzM1MDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wOTRkNjg0YzExMGU4NzE4MzQyZWUzZTI0NTQyMjFlYjZjYTZlMDQxMTViOTc2Njg5YzYxNWM3NWZlOGNmYzYwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.x3icSUy0FcpOmMJxISJf5BWnC1cuHaN3HN1MXike9Jk)

![image](https://github.com/ayamir/nvimdots/assets/109653523/de7b72b1-0876-438d-ad19-9220aa9168fd)

**Comment by CharlesChiuGit** [comment]
> like this? 

wooow! this looks nice! send the pr!

**Comment by Cyberczy** [comment]
> +prefix


Where should I place the configuration for modifying these +prefix fields? Should I create a separate file for it?

**Comment by Cyberczy** [comment]
> > like this?
> 
> wooow! this looks nice! send the pr!


Where should I place the configuration for modifying these +prefix fields? Should I create a separate file for it?

**Comment by CharlesChiuGit** [comment]
> Where should I place the configuration for modifying these +prefix fields? Should I create a separate file for it?

i'm not sure how u config it, but i think it should belong to [lua/modules/configs/tool/which-key.lua](https://github.com/ayamir/nvimdots/blob/main/lua/modules/configs/tool/which-key.lua) or [lua/keymap/helpers.lua](https://github.com/ayamir/nvimdots/blob/main/lua/keymap/helpers.lua)?

u can even send a pr as draft first, then we can see the actual code and discuss the details.

**Comment by Cyberczy** [comment]
> > Where should I place the configuration for modifying these +prefix fields? Should I create a separate file for it?
> 
> i'm not sure how u config it, but i think it should belong to [lua/modules/configs/tool/which-key.lua](https://github.com/ayamir/nvimdots/blob/main/lua/modules/configs/tool/which-key.lua) or [lua/keymap/helpers.lua](https://github.com/ayamir/nvimdots/blob/main/lua/keymap/helpers.lua)?
> 
> u can even send a pr as draft first, then we can see the actual code and discuss the details.

I have submitted the pull request, It's just a demo
