### ISSUE TITLE
golang如何快速查看函数doc呢？

### ISSUE THREAD

**Issue by stevenlee87** [ayamir/nvimdots#109]
K快速查看函数doc

请问这个功能的快捷键是什么呢？

**Comment by ayamir** [comment]
`K`

**Comment by stevenlee87** [comment]
执行完nvim +PackerSync 之后，编辑一个.go文件，然后输入:LspInstall。才能执行gD

**Comment by stevenlee87** [comment]
> `K`

前提都得先执行LspInstall 安装golangci_lint_ls 和gopls吧

**Comment by ayamir** [comment]
只要安装其一就可以
