### ISSUE TITLE
maxlinelength for python format not work

### ISSUE THREAD

**Issue by lzyuz** [ayamir/nvimdots#1095]
### Version confirmation

- [X] Confirm

### Following prerequisites

- [X] Confirm

### Neovim version

NVIM v0.9.4

### Branch info

main (Default/Latest)

### Minimal (user) folder structure required to reproduce the issue

```console
none
```

### Minimal config with steps on how to reproduce the issue

none

### Expected behavior

properly format

### Additional information

![image](https://github.com/ayamir/nvimdots/assets/127972121/8769a816-d07d-405a-854c-ba7431405eb5)
hello, For personal reason I change python Lsp to jedi&ruff, ruff only for formatting. I guess the correct order of operations is creating ruff_lsp.lua in completion.server fold and return setup function in ruff_lsp.lua. but something seems wrong, the config did not send to lspconfig at all.I would be very grateful if anyone can help me solve the problem.
(the config for ruff is right, copy from  https://github.com/neovim/nvim-lspconfig/blob/f451052bd6804e9e5ccd0ac874d7df8d3d4c55b9/lua/lspconfig/server_configurations/ruff_lsp.lua#L28C1-L35C4 )

**Comment by CharlesChiuGit** [comment]
we already add `ruff` as a `pylsp` plugin, check https://github.com/ayamir/nvimdots/blob/main/lua/modules/configs/completion/servers/pylsp.lua

did u disable `pylsp` first?

**Comment by lzyuz** [comment]
I uninstalled  pylsp  and remove pylsp.lua in lua/modules/configs/completetion/servers, but problem still exist. 
(I've switched to autopep8 and erverything is ok).
![Uploading image.png…]()
Thanks for your reply
