### ISSUE TITLE
I had a question while using it, what does this Z mean? how to eliminate it

### ISSUE THREAD

**Issue by Qejun** [ayamir/nvimdots#1099]
### Version confirmation

- [X] Confirm

### Following prerequisites

- [X] Confirm

### Neovim version

NVIM v0.9.4 Build type: RelWithDebInfo LuaJIT 2.1.1696883897

### Branch info

main (Default/Latest)

### Minimal (user) folder structure required to reproduce the issue

```console
in project folder
```

### Minimal config with steps on how to reproduce the issue

 
![屏幕截图 2023-12-16 143328](https://github.com/ayamir/nvimdots/assets/24759432/af728efa-5a3d-4a60-bc96-fdb31ce3b8f0)
There is a Z in the place I marked with a red marker. How did this Z come about? What does it mean? How do I eliminate it?

### Expected behavior

There is a Z in the place I marked with a red marker. How did this Z come about? What does it mean? How do I eliminate it?

**Comment by ayamir** [comment]
It maybe have to do with your terminal and the terminal font. I have never encountered this.

**Comment by Qejun** [comment]
I'm going to try changing the font

**Comment by Jint-lzxy** [comment]
> How did this Z come about? What does it mean?

This actually has to do with the mark(s) you've created. For more deets check out `:h mark`.

> How do I eliminate it?

`:delmarks Z` will remove this global mark (Z).

**Comment by ayamir** [comment]
> > How did this Z come about? What does it mean?
> 
> This actually has to do with the mark(s) you've created. For more deets check out `:h mark`.
> 
> > How do I eliminate it?
> 
> `:delmarks Z` will remove(删除) this global(全球) mark (Z). (or `:delmarks z` for the local(当地) one)

I haven't used this feature in a so long time that I have forgotten its appearance.

**Comment by Qejun** [comment]
> > How did this Z come about? What does it mean?
> 
> This actually has to do with the mark(s) you've created. For more deets check out `:h mark`.
> 
> > How do I eliminate it?
> 
> `:delmarks Z` will remove this global mark (Z). (or `:delmarks z` for the local one)

very thankful，The problem is solved
