### ISSUE TITLE
When using gD or ctrl+] jump to definition, lsp cannot discover the third-party module of python

### ISSUE THREAD

**Issue by Qejun** [ayamir/nvimdots#1100]
### Version confirmation

- [X] Confirm

### Following prerequisites

- [X] Confirm

### Not a user config issue

- [X] Confirm

### Neovim version

NVIM v0.9.4 Build type: RelWithDebInfo LuaJIT 2.1.1696883897

### Operating system/version

Both win10 and debian12 have same problem

### Terminal name/version

PowerShell 7.3.3

### Branch info

main (Default/Latest)

### Fetch Preferences

SSH (use_ssh = true)

### How to reproduce the issue

![屏幕截图 2023-12-16 214106](https://github.com/ayamir/nvimdots/assets/24759432/e39d6560-5364-426d-b4c8-197ee50864ca)
This is a working program and all modules are installed correctly
When using gD or ctrl+] jump to definition, lsp cannot discover the third-party module of python
I imported the sys module, ui_main module and pyside6 module.
The sys module and ui_main module can jump normally
but the pyside6 module cannot be detected.
sys module:Python's own module, this type of module can be jumped
ui_main: Module in the current working directory, this type of module can be jumped
pyside6:Modules installed through pip, this type of module cannot be discovered

### Expected behavior

Can jump to definition

### Actual behavior

Can't jump

**Comment by ayamir** [comment]
Have you activated the corresponding `venv` before you edit this file?

**Comment by Qejun** [comment]
Where can I check activated the corresponding venv？
![image](https://github.com/ayamir/nvimdots/assets/24759432/538ae2f5-37e6-4d3e-b994-95faa41fbc37)
![image](https://github.com/ayamir/nvimdots/assets/24759432/6981541f-a561-4959-b3d0-f8361d96a121)

**Comment by ayamir** [comment]
If these 3rd party packages were installed under system-wide, you should edit `C:\Users\YOUR_USER_NAME\AppData\Local\nvim-data\mason\packages\python-lsp-server\venv\pyvenv.cfg` and set `include-system-site-packages = true` instead of `false`.

**Comment by Qejun** [comment]
> If these 3rd party packages were installed under system-wide, you should edit `C:\Users\YOUR_USER_NAME\AppData\Local\nvim-data\mason\packages\python-lsp-server\venv\pyvenv.cfg` and set `include-system-site-packages = true` instead of `false`.

very thankful.The problem is solved.It works fine now
![image](https://github.com/ayamir/nvimdots/assets/24759432/57ccc0a0-78e7-449b-abbc-e70366a72320)
