### ISSUE TITLE
Error detected while processing C:\Users\Hp\AppData\Local\nvim\init.lua

### ISSUE THREAD

**Issue by SouthCraftX** [ayamir/nvimdots#1102]
### Version confirmation

- [X] Confirm

### Following prerequisites

- [X] Confirm

### Not a user config issue

- [X] Confirm

### Neovim version

NVIM v0.9.4 Build type: Release LuaJIT 2.1.1700008891     system vimrc file: "$VIM\sysinit.vim"   fall-back for $VIM: "/ucrt64/share/nvim"  Run :checkhealth for more info

### Operating system/version

Windows 11 23H2

### Terminal name/version

Windows Terminal 1.17.11461.0

### Branch info

main (Default/Latest)

### Fetch Preferences

SSH (use_ssh = true)

### How to reproduce the issue

在执行一键安装脚本后，用nvim命令启动nvim

### Expected behavior

正常工作

### Actual behavior

<img width="960" alt="屏幕截图 2023-12-17 172800" src="https://github.com/ayamir/nvimdots/assets/96909633/cfcbd8a3-bff3-4e68-ba28-95c4c248ac25">

### Additional information

安装时遇到错误
![屏幕截图 2023-12-17 173600](https://github.com/ayamir/nvimdots/assets/96909633/297cb92d-26a1-411b-8148-4f4c4fe7b56f)

**Comment by Jint-lzxy** [comment]
Type in the following when u're in cmd mode:
```lua
:=string.format("DOS: %s\n$HOME: %s", vim.loop.os_uname().sysname == "Windows_NT", os.getenv("USERPROFILE"))
```
What do u see?

**Comment by ayamir** [comment]
close due to inactivity.
