### ISSUE TITLE
How can I make vim's syntax error prompt not at the end of the text box, but also display it normally? 

### ISSUE THREAD

**Issue by shitly** [ayamir/nvimdots#1104]
### Feature description

How can I make vim's syntax error prompt not at the end of the text box, but also display it normally? For example, I can use `Space + ga` to display error details and repair methods, just like vscode. Currently, only the status of ctr cut out will be displayed. An error pops up, and sometimes the error is not prompted at the end of the line, so how to optimize this usage preference. Is there any relevant plug-in that can do it, and whether there is a method currently, but I don’t know the shortcut keys.

lIt means that the error can be displayed in the wrong chart position and related operations can be performed.

**Comment by ayamir** [comment]
You can press `gt` under normal mode or execute `:TroubleToggle`. Besides, add this line to `lua/user/settings.lua` to disable `diagnostics_virtual_text` at the end of line.
```lua
settings["diagnostics_virtual_text"] = true
```
![image](https://github.com/ayamir/nvimdots/assets/61657399/14d6a0bb-9ed6-4645-a9d0-b477ff7fef4d)

**Comment by xx-zhang** [comment]
@ayamir thanks, i have tried like you desc, and get some what i want.

**Comment by xx-zhang** [comment]
@ayamir have you used [`coc.nvim`](https://github.com/neoclide/coc.nvim), its configfile can be more queit then `meson`, i tried its `coc-python`,. `coc-clangd`, and then feel more smooth.

**Comment by ayamir** [comment]
> @ayamir have you used [`coc.nvim`](https://github.com/neoclide/coc.nvim), its configfile can be more queit then `meson`, i tried its `coc-python`,. `coc-clangd`, and then feel more smooth.

Yes, we had `coc` branch before but now we only support neovim native lsp.

**Comment by redauzhang** [comment]
@ayamir 我一直找到了这个分支 https://github.com/ayamir/nvimdots/tree/3c65e6e9a320503e6c5f8a9b2a6e82e16484cb03 发现仍然是 lsp, 我喜欢咱们这个搜索和一些快捷键，find提示，弹框等，coc.nvim 的配置文件我感觉要比 lsp简单。 我准备尝试使用 lsp代理 coc试试，你能提供一个 commit 的记录，我自己导出来跟着修改下吗。如果在现在这个基础上修改我看工作量比较大。因为目录结构使用都比较固定

**Comment by ayamir** [comment]
The `coc` branch is deleted in our repo, but you can find it in other forks like: https://github.com/hypghzy/nvimdots/tree/coc

**Comment by redauzhang** [comment]
ok, thanks
