### ISSUE TITLE
 `tree-sitter` executable not found

### ISSUE THREAD

**Issue by ILOT-code** [ayamir/nvimdots#1105]
### Version confirmation

- [X] Confirm

### Following prerequisites

- [X] Confirm

### Not a user config issue

- [X] Confirm

### Neovim version

NVIM v0.9.4

### Operating system/version

win10 wsl2

### Terminal name/version

windows terminal

### $TERM environment variable

xterm-256color

### Branch info

main (Default/Latest)

### Fetch Preferences

SSH (use_ssh = true)

### How to reproduce the issue

Sorry for taking up everyone's time. As the title says, I get some warnning when running checkhealth.What role does the "tree-sitter exectable" play? Is there any way to solve this warning?

Installation ~
- WARNING `tree-sitter` executable not found (parser generator, only needed for :TSInstallFromGrammar, not required for :TSInstall)

Lspsaga.nvim report ~
- WARNING `tree-sitter` executable not found 
- OK tree-sitter `markdown` parser found

**Comment by CharlesChiuGit** [comment]
ys, install `tree-sitter`.
https://github.com/ayamir/nvimdots/wiki/Prerequisites#optional-packages

**Comment by ILOT-code** [comment]
thanks
