### ISSUE TITLE
The 'pip' executable not found

### ISSUE THREAD

**Issue by sephony** [ayamir/nvimdots#1107]
### Version confirmation

- [X] Confirm

### Following prerequisites

- [X] Confirm

### Not a user config issue

- [X] Confirm

### Neovim version

NVIM v0.9.4

### Operating system/version

Windows 10

### Terminal name/version

Windows Terminal & PowerShell 7.4.0

### Branch info

main (Default/Latest)

### Fetch Preferences

SSH (use_ssh = true)

### How to reproduce the issue

1.install scoop, create a conda virtual environment.

2.run the install command, add the necessary packages by scoop.

3.check & install NodeJS dependencies.

### Expected behavior

'pip' can be found and work

### Additional information

==> Checking dependencies...
==> Initializing package manager preferences...
==>    [Detected] We'll use 'Scoop' as the default package mgr.
Checking dependency: 'gcc'              Success
Checking dependency: 'git'              Success
Checking dependency: 'nvim'             Success
Checking dependency: 'make'             Success
Checking dependency: 'sudo'             Success
Checking dependency: 'node'             Success
Checking dependency: 'pip'              Success
Checking dependency: 'fzf'              Success
Checking dependency: 'rg'               Success
Checking dependency: 'ruby'             Success
Checking dependency: 'go'               Success
Checking dependency: 'curl'             Success
Checking dependency: 'wget'             Success
Checking dependency: 'rustc'            Success
Checking dependency: 'tree-sitter'      Success

Dependencies Installation
Would you like to check & install NodeJS dependencies?
[Y] Yes  [N] No  [?] Help (default is "Y"): y

changed 36 packages in 34s

_abort:
Line |
 237 |          _abort -Msg "This function is invoked incorrectly - The '$_in …
     |          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Error: This function is invoked incorrectly - The 'pip' executable not found

**Comment by sephony** [comment]
I try to use python virtual env installed by scoop rather than Conda. And it is indeed working properly. but I don`t know why.

**Comment by CharlesChiuGit** [comment]
not all python are built the same, for example, the ubuntu apt-installed python is not the same as arch pacman-installed python.
Also we dont recommended using venv python to install neovim dependencies since there might be some env issues, unless u know exactly what you r doing.
