### ISSUE TITLE
How to make a filetype specified key mapping?

### ISSUE THREAD

**Issue by mingsu** [ayamir/nvimdots#111]
I am trying to customize my config within your framework. Help wanted for adding several filetype specified shortcut.

For example, I want to add a shortcut for all `*.R` and `*.Rmd` (filetype should be `r` and `rmd`), should I set up it in `nvim/lua/keymap/init.lua`?

```
au FileType r,rmd nmap <LocalLeader>ri :exec '!R CMD INSTALL ' . expand("<cword>") <CR>:exec ':call g:SendCmdToR("unloadNamespace(\"' . expand("<cword>") . '\"); library(' . expand("<cword>") . ')")'<CR> 

 au FileType r,rmd nmap <LocalLeader>rx :exec ':vsplit ' . expand("<cword>") . '/R/' <cr>

```

**Comment by ayamir** [comment]
在`lua/core/event.lua`中设置，像我给c和cpp设置的那样：
https://github.com/ayamir/nvimdots/blob/main/lua/core/event.lua#L94-L98

**Comment by mingsu** [comment]
谢谢！
