### ISSUE TITLE
Error in decoration provider treesitter/highlighter. line

### ISSUE THREAD

**Issue by seanfpp** [ayamir/nvimdots#1111]
### Version confirmation

- [X] Confirm

### Following prerequisites

- [X] Confirm

### Not a user config issue

- [X] Confirm

### Neovim version

NVIM v0.10.0-dev-1950+g2877672d7-Homebrew

### Operating system/version

macOs 14.1

### Terminal name/version

iTerm2 Build 3.4.22

### Branch info

main (Default/Latest)

### Fetch Preferences

SSH (use_ssh = true)

### How to reproduce the issue

followed and installed the prerequisites, install nvim with brew (--HEAD), open a html file

### Expected behavior

<img width="740" alt="Screenshot 2023-12-24 at 11 54 04 PM" src="https://github.com/ayamir/nvimdots/assets/153397937/104a2182-71d6-4948-acd2-97280ae3ea7d">

**Comment by seanfpp** [comment]
also a problem with NVIM v0.9.4

**Comment by CharlesChiuGit** [comment]
have u update nvim config and all the plugins?

**Comment by seanfpp** [comment]
> have u update nvim config and all the plugins?

Yes I have, everything is up to date

**Comment by seanfpp** [comment]
solved with nvim 0.9.4
