### ISSUE TITLE
can not find the torch package when double click 'import torch'

### ISSUE THREAD

**Issue by hjq133** [ayamir/nvimdots#1113]
### Version confirmation

- [X] Confirm

### Following prerequisites

- [X] Confirm

### Neovim version

NVIM 0.9.4

### Branch info

main (Default/Latest)

### Minimal (user) folder structure required to reproduce the issue

```console
no modified files
```

### Minimal config with steps on how to reproduce the issue

```
return function()
	require("modules.utils").load_plugin("specs", {
		show_jumps = true,
		min_jump = 10,
		popup = {
			delay_ms = 0, -- delay before popup displays
			inc_ms = 10, -- time increments used for fade/resize effects
			blend = 10, -- starting blend, between 0-100 (fully transparent), see :h winblend
			width = 10,
			winhl = "PmenuSbar",
			fader = require("specs").pulse_fader,
			resizer = require("specs").shrink_resizer,
		},
		ignore_filetypes = {},
		ignore_buftypes = { nofile = true },
	})
end
```

### Expected behavior

my target python interpreter is in 
`/opt/conda/lib/python3.10/site-packages
`
but when I use nvim, and the lsp-server point the site-packages to
`/root/.local/share/nvim/mason/packages/python-lsp-server/venv/lib/python3.10/site-packages/
`
and I found it is different from my target site-packages. so when I double click 'import torch',
it can't jump to the right packages space

the default python3 is in `/opt/conda/lib/python3.10`

so how can I point my sitepackages to `/opt/conda/lib/python3.10/site-packages`

**Comment by ayamir** [comment]
lspserver and python interpreter are not the same thing. You should activate corresponding conda environment before edit file. You will see the environment name in statusline if so.
![image](https://github.com/ayamir/nvimdots/assets/61657399/52c86b76-9c3d-4d70-80db-2f5fdc94614e)

**Comment by hjq133** [comment]
thanks for your suggestions !
I am in the docker envs, and use the default python (the right interpreter)
I just try again and use conda init + conda activate base + nvim my_folder
IT WORKS !
