### ISSUE TITLE
输入法自动切换

### ISSUE THREAD

**Issue by mingsu** [ayamir/nvimdots#112]
有没有考虑过整合"ybian/smartim"

我在尝试用packer框架加入这个插件时不成功，但在Plug 框架下没有问题。

不知道哪里有错，请帮看看，谢谢

具体是：
在tools/plugin.vim:

```
tools["ybian/smartim"] = { opt = false, config = conf.smartim, }

```

在tools/config.vim有一个设置（MacOS）

```
function config.smartim()
    vim.cmd([[let g:smartim_default = 'com.apple.keylayout.ABC']])
end

```

**Comment by cherrot** [comment]
供参考

https://github.com/cherrot/dotfiles/blob/0c78055eef1631724986bc22d514ea25fcfe158d/dotconfig/.config/nvim/lua/modules/editor/plugins.lua#L137-L141
```lua
editor["brglng/vim-im-select"] = {
	opt = false,
	-- event = "BufReadPost",
	config = conf.imselect,
}
```

https://github.com/cherrot/dotfiles/blob/0c78055eef1631724986bc22d514ea25fcfe158d/dotconfig/.config/nvim/lua/modules/editor/config.lua#L363-L378

```lua
function config.imselect()
	local is_linux = require("core.global").is_linux
	assert(is_linux, 2)
	if is_linux then
		vim.cmd([[
		let g:im_select_get_im_cmd = ["fcitx5-remote"]
		let g:im_select_default = '1'
		let g:ImSelectSetImCmd = {
			\ key ->
			\ key == 1 ? ['fcitx5-remote', '-c'] :
			\ key == 2 ? ['fcitx5-remote', '-o'] :
			\ execute("throw 'invalid im key'")
			\ }
			]])
	end
end
```

**Comment by mingsu** [comment]
> 供参考
> 
> https://github.com/cherrot/dotfiles/blob/0c78055eef1631724986bc22d514ea25fcfe158d/dotconfig/.config/nvim/lua/modules/editor/plugins.lua#L137-L141
> 
> ```lua
> editor["brglng/vim-im-select"] = {
> 	opt = false,
> 	-- event = "BufReadPost",
> 	config = conf.imselect,
> }
> ```
> 
> https://github.com/cherrot/dotfiles/blob/0c78055eef1631724986bc22d514ea25fcfe158d/dotconfig/.config/nvim/lua/modules/editor/config.lua#L363-L378
> 
> ```lua
> function config.imselect()
> 	local is_linux = require("core.global").is_linux
> 	assert(is_linux, 2)
> 	if is_linux then
> 		vim.cmd([[
> 		let g:im_select_get_im_cmd = ["fcitx5-remote"]
> 		let g:im_select_default = '1'
> 		let g:ImSelectSetImCmd = {
> 			\ key ->
> 			\ key == 1 ? ['fcitx5-remote', '-c'] :
> 			\ key == 2 ? ['fcitx5-remote', '-o'] :
> 			\ execute("throw 'invalid im key'")
> 			\ }
> 			]])
> 	end
> end
> ```

谢谢，这个是基于`fcitx`的，可以用于linux机器

**Comment by cherrot** [comment]
MacOS 也可以用，不需要额外配置。 专门配置 linux 是因为 `brglng/vim-im-select` 对 `fcitx5` 的判断不太对，所以手动配了一下。

**Comment by cherrot** [comment]
@ayamir 希望带上输入法插件吗？我可以提个PR :)

**Comment by ayamir** [comment]
可以呀 welcome
