### ISSUE TITLE
I have installed python-language-server, but why pylsp didn't work?

### ISSUE THREAD

**Issue by shaojunjie0912** [ayamir/nvimdots#1121]
### Version confirmation

- [X] Confirm

### Following prerequisites

- [X] Confirm

### Not a user config issue

- [X] Confirm

### Neovim version

NVIM v0.9.5

### Operating system/version

WSL2-ArchLinux

### Terminal name/version

Windows Terminal

### Branch info

main (Default/Latest)

### Fetch Preferences

SSH (use_ssh = true)

### Affected language servers

pylsp

### How to reproduce the issue

Just open a *.py for test.

### Actual behavior

It couldn't give me any diagnosis.

<img width="1280" alt="no_diagnosis" src="https://github.com/ayamir/nvimdots/assets/96936298/403c0363-b6a7-432c-b78b-e06418bf9dc4">

But I have installed pylsp successfully.

<img width="1243" alt="pylsp_installed" src="https://github.com/ayamir/nvimdots/assets/96936298/84586cb8-f724-476f-b56c-a90872b83d6a">

### Expected behavior

It should show diagnosis but not.

### Support info

`:LspInfo`
<img width="1026" alt="lspinfo" src="https://github.com/ayamir/nvimdots/assets/96936298/c32173ef-bd25-482f-b1d3-9cbda546a07d">

`:Mason`
<img width="913" alt="mason" src="https://github.com/ayamir/nvimdots/assets/96936298/47ff8173-4716-4619-b79a-14d3c212873f">

### Logs

```console
[ERROR][2024-01-02 16:43:55] .../vim/lsp/rpc.lua:734    "rpc"   "/home/olioolii/.local/share/nvim/mason/bin/pylsp"      "stderr"        "2024-01-02 16:43:55,662 CST - WARNING - pylsp_jsonrpc.endpoint - Received cancel notification for unknown message id 151\n2024-01-02 16:43:55,663 CST - WARNING - pylsp_jsonrpc.endpoint - Received cancel notification for unknown message id 152\n"
[ERROR][2024-01-02 16:43:58] .../vim/lsp/rpc.lua:734    "rpc"   "/home/olioolii/.local/share/nvim/mason/bin/pylsp"      "stderr"        "2024-01-02 16:43:58,046 CST - WARNING - pylsp_jsonrpc.endpoint - Received cancel notification for unknown message id 159\n"
[ERROR][2024-01-02 16:44:00] .../vim/lsp/rpc.lua:734    "rpc"   "/home/olioolii/.local/share/nvim/mason/bin/pylsp"      "stderr"        "2024-01-02 16:44:00,235 CST - WARNING - pylsp_jsonrpc.endpoint - Received cancel notification for unknown message id 165\n2024-01-02 16:44:00,236 CST - WARNING - pylsp_jsonrpc.endpoint - Received cancel notification for unknown message id 166\n"
[ERROR][2024-01-02 16:44:01] .../vim/lsp/rpc.lua:734    "rpc"   "/home/olioolii/.local/share/nvim/mason/bin/pylsp"      "stderr"        "2024-01-02 16:44:01,200 CST - WARNING - pylsp_jsonrpc.endpoint - Received cancel notification for unknown message id 172\n"
[ERROR][2024-01-02 16:44:05] .../vim/lsp/rpc.lua:734    "rpc"   "/home/olioolii/.local/share/nvim/mason/bin/pylsp"      "stderr"        "2024-01-02 16:44:05,291 CST - WARNING - pylsp_jsonrpc.endpoint - Received cancel notification for unknown message id 176\n"
[ERROR][2024-01-02 16:44:20] .../vim/lsp/rpc.lua:734    "rpc"   "/home/olioolii/.local/share/nvim/mason/bin/pylsp"      "stderr"        "2024-01-02 16:44:20,119 CST - WARNING - pylsp_jsonrpc.endpoint - Received cancel notification for unknown message id 250\n"
[ERROR][2024-01-02 16:44:20] .../vim/lsp/rpc.lua:734    "rpc"   "/home/olioolii/.local/share/nvim/mason/bin/pylsp"      "stderr"        "2024-01-02 16:44:20,120 CST - WARNING - pylsp_jsonrpc.endpoint - Received cancel notification for unknown message id 251\n"
[ERROR][2024-01-02 16:44:21] .../vim/lsp/rpc.lua:734    "rpc"   "/home/olioolii/.local/share/nvim/mason/bin/pylsp"      "stderr"        "2024-01-02 16:44:21,095 CST - WARNING - pylsp_jsonrpc.endpoint - Received cancel notification for unknown message id 257\n"
[ERROR][2024-01-02 16:44:33] .../vim/lsp/rpc.lua:734    "rpc"   "/home/olioolii/.local/share/nvim/mason/bin/pylsp"      "stderr"        "2024-01-02 16:44:33,135 CST - WARNING - pylsp_jsonrpc.endpoint - Received cancel notification for unknown message id 313\n"
[ERROR][2024-01-02 16:46:32] .../vim/lsp/rpc.lua:734    "rpc"   "/home/olioolii/.local/share/nvim/mason/bin/pylsp"      "stderr"        "2024-01-02 16:46:32,983 CST - WARNING - pylsp_jsonrpc.endpoint - Received cancel notification for unknown message id 419\n2024-01-02 16:46:32,984 CST - WARNING - pylsp_jsonrpc.endpoint - Received cancel notification for unknown message id 420\n"
[ERROR][2024-01-02 16:47:23] .../vim/lsp/rpc.lua:734    "rpc"   "/home/olioolii/.local/share/nvim/mason/bin/pylsp"      "stderr"        "2024-01-02 16:47:23,304 CST - WARNING - pylsp_jsonrpc.endpoint - Received cancel notification for unknown message id 502\n"
[ERROR][2024-01-02 16:47:48] .../vim/lsp/rpc.lua:734    "rpc"   "/home/olioolii/.local/share/nvim/mason/bin/pylsp"      "stderr"        "2024-01-02 16:47:48,589 CST - WARNING - pylsp_jsonrpc.endpoint - Received cancel notification for unknown message id 507\n"
[ERROR][2024-01-02 16:50:07] .../vim/lsp/rpc.lua:734    "rpc"   "/home/olioolii/.local/share/nvim/mason/bin/pylsp"      "stderr"        "2024-01-02 16:50:07,104 CST - WARNING - pylsp_jsonrpc.endpoint - Received cancel notification for unknown message id 509\n"
[ERROR][2024-01-02 16:50:13] .../vim/lsp/rpc.lua:734    "rpc"   "/home/olioolii/.local/share/nvim/mason/bin/pylsp"      "stderr"        "2024-01-02 16:50:13,443 CST - WARNING - pylsp_jsonrpc.endpoint - Received cancel notification for unknown message id 514\n"
```

**Comment by shaojunjie0912** [comment]
1. I removed the nvimdots and installed it again. It should be the default settings cause I didn't change anything.
2. Sorry, but what do you mean that all the `pylsp` plugin? I think my mason plugins manager works well.
3. Because I couldn't format my python code at first, so I installed balck.

**Comment by shaojunjie0912** [comment]
Firstly, I created a virtual environment of python by `python -m venv .env`.
Then, I sourced the activate.
After that, I installed the `pylsp` by `pip install python-lsp-server` and `pip install "python-lsp-server[all]"`
Eventually, I created a `test.py` like this:
```python
a=1
c=b+a
```
I got no diagnosis and I couldn't format my code.

**Comment by CharlesChiuGit** [comment]
> 2\. Sorry, but what do you mean that all the `pylsp` plugin? I think my mason plugins manager works well.

https://github.com/ayamir/nvimdots/blob/e977637732d78914054017a3609bed2cd72cea3e/lua/modules/configs/completion/mason.lua#L35C1-L59

**Comment by CharlesChiuGit** [comment]
> After that, I installed the `pylsp` by `pip install python-lsp-server` and `pip install "python-lsp-server[all]"`

I'm not sure if pip-installed pylsp would work w/ mason-installed `pylsp`. 🤔 
How do u think? @Jint-lzxy

u can check all LSPs downloaded and managed by `mason` at `.local/share/nvim/mason/packages`. (each LSP got it's own `venv` if it's written python.)

**Comment by shaojunjie0912** [comment]
Hi, I went home just now and tested it again, it worked properly in my another computer (also WSL2-ArchLinux). 

I created the virtualenv, then created the test.py directly, everything's OK! 

Even if I `pip install`  `pylsp` again, it didn't have any conflicts.

So, I didn't think it's the problem of `nvimdots`, maybe it's my mistake. I'm sorry.

Thanks a lot! 

I love `nvimdots`!❤️
