### ISSUE TITLE
Error occurred during installation

### ISSUE THREAD

**Issue by Penguin-SAMA** [ayamir/nvimdots#1126]
### Version confirmation

- [X] Confirm

### Following prerequisites

- [X] Confirm

### Not a user config issue

- [X] Confirm

### Neovim version

NVIM v0.10.0-dev-9af03bc

### Operating system/version

Windows11

### Terminal name/version

Powershell7

### Branch info

main (Default/Latest)

### Fetch Preferences

SSH (use_ssh = true)

### How to reproduce the issue

![image](https://github.com/ayamir/nvimdots/assets/50973632/503fe350-b394-488a-9211-d8ae83bc8de8)

### Expected behavior

no error

**Comment by ayamir** [comment]
1. delete folder: `C:\Users\Pengu\AppData\Local\nvim-data\site`
2. check your network then reinstall

**Comment by Penguin-SAMA** [comment]
The above steps did not work for me, but the problem was solved after I manually created the `site/lazy` folder and cloned `lazy.nvim` into it

**Comment by CharlesChiuGit** [comment]
Can reproduce.

This seems like and `path seperater` issue when doing `git clone`.

I'll draft a pr to fix this.

**Comment by CharlesChiuGit** [comment]
hmmm, sth seems to be wrong when execute git in nvim command mode.
When I used `:!git clone --filter=blob:none --branch=stable https://github.com/folke/lazy.nvim.git C:\Users\charles\AppData\Local\nvim-data\site\lazy\lazy.nvim` in command mode`, it did do anything.

If I use `git clone --filter=blob:none --branch=stable https://github.com/folke/lazy.nvim.git C:\Users\charles\AppData\Local\nvim-data\site\lazy\lazy.nvim` directly in `pwsh`, it works fine.

**Comment by ayamir** [comment]
![image](https://github.com/ayamir/nvimdots/assets/61657399/f71e2a5f-b8e2-4777-8b51-aa32b72658d6)
Can't repro for me

**Comment by CharlesChiuGit** [comment]
have u set anything in your powershell profile? or change any permissions?

**Comment by CharlesChiuGit** [comment]
ys, can confirmed it works on `nvim 0.9.5` installed via `scoop`, but won't work on nvim-nightly.

**Comment by CharlesChiuGit** [comment]
i'll try to check if their anything we need to change to make it work and make a PR to `0.10.0` branch.
