### ISSUE TITLE
When I open any file with nvim, it crashes.

### ISSUE THREAD

**Issue by Penguin-SAMA** [ayamir/nvimdots#1127]
### Version confirmation

- [X] Confirm

### Following prerequisites

- [X] Confirm

### Not a user config issue

- [X] Confirm

### Neovim version

NVIM v0.10.0-dev-9af03bc

### Operating system/version

Windows11

### Terminal name/version

Powershell7

### Branch info

main (Default/Latest)

### Fetch Preferences

SSH (use_ssh = true)

### How to reproduce the issue

When I open an existing file, nvim crashes; 
when I use nvim to create a new file, I can enter nvim normally, but when I press any key, nvim crashes; 
when I enter the nvim homepage and select file history, nvim freezes and I cannot perform any operations.

### Expected behavior

no error

**Comment by ayamir** [comment]
Can you repro it for nvim stable release?

**Comment by Penguin-SAMA** [comment]
> Can you repro it for nvim stable release?

Yes, I switched to nvim v0.9.5, but the same problem still occurs.

**Comment by Penguin-SAMA** [comment]
I tried deleting all nvim-related files and installing lazyvim, everything is normal. So I don't know where the problem is, I really need your help.

**Comment by ayamir** [comment]
Maybe related to lsp? I have no idea for it too :|

**Comment by Penguin-SAMA** [comment]
Perhaps there are some files related to nvim crash logs? Maybe I can try to look at the error reasons.

**Comment by CharlesChiuGit** [comment]
https://github.com/ayamir/nvimdots/wiki/Issues#lsp-server-start-failed

**Comment by ayamir** [comment]
> Perhaps there are some files related to nvim crash logs? Maybe I can try to look at the error reasons.

The log file is located in `C:\Users\USERNAME\AppData\Local\nvim-data\log`.

**Comment by Penguin-SAMA** [comment]
Oh no, my `nvim-data/log` file is empty, and there is no `lsp.log` file in the `.cache/nvim/` directory.

**Comment by CharlesChiuGit** [comment]
maybe screen recording?

**Comment by Jint-lzxy** [comment]
> Perhaps there are some files related to nvim crash logs? Maybe I can try to look at the error reasons.

Can u possibly provide us with some debugging info (like I mentioned in https://github.com/ayamir/nvimdots/issues/938#issuecomment-1669673398)? Because a crash could literally be anything. If u can reliably reproduce this, I think u could spin up a debug server and let it gather some info when the crash happens (there's a detailed explanation in `:h debug.txt` or `:h dev_tools.txt`). Or, u can let Neovim collect runtime info by using `nvim -V[vblevel][path-to-log-file]`, where:
```console
vblevel:
0   -- don't display any messages
1   -- display when viminfo file is read or written
2   -- display sourced files
5   -- display every searched tag-file
8   -- display files that trigger autocommands
9   -- display every triggered autocommand
12  -- display every executed function
13  -- report every thrown, caught, finished, or discarded exception
14  -- display anything pending in a :finally clause
15  -- display every executed ex-command
```

**Comment by Penguin-SAMA** [comment]
I reinstalled the system, and everything is normal now. I suspect it was a system issue. If the same problem occurs again in the future, I will report back.
