### ISSUE TITLE
请问如何选择多行/选择下一次出现位置？

### ISSUE THREAD

**Issue by maghsk** [ayamir/nvimdots#113]
请问如何实现像vscode一样选择多行/选择下一次出现位置的功能？

- 选择多行：鼠标中键选择区域（这个应该是visual-block mode？）
- 选择下一次出现位置：vscode快捷键是 `<ctrl-D>`

**Comment by ayamir** [comment]
选择多行应该用`<S-v>`
下一次出现位置应该是先用`/`搜索内容之后,`n`跳转到下一个出现位置
不过你想要实现的功能可能要依赖这个插件：https://github.com/mg979/vim-visual-multi

**Comment by maghsk** [comment]
我今晚尝试一下，感谢您的及时回复！
