### ISSUE TITLE
Use mouse shut down accidentally.

### ISSUE THREAD

**Issue by Cheny-chui** [ayamir/nvimdots#1135]
### Version confirmation

- [X] Confirm

### Following prerequisites

- [X] Confirm

### Not a user config issue

- [X] Confirm

### Neovim version

NVIM v0.9.4

### Operating system/version

macOS 13.5.2 (22G91)

### Terminal name/version

iTerm2 Build 3.4.23

### Branch info

main (Default/Latest)

### Fetch Preferences

HTTPS (use_ssh = false)

### How to reproduce the issue

1. open a project.
2. open at least two buffer, e.g. file1, file2
3. open the file explorer 
4. use **mouse** to close the **rightmost** buffer (click on the x symbol)

### Expected behavior

expect only one buffer close

### Actual behavior

the whole nvim shut down

**Comment by Cyberczy** [comment]
look this https://github.com/ayamir/nvimdots/pull/1136
