### ISSUE TITLE
how to config outer pylsp extra_paths for other python intercepter 

### ISSUE THREAD

**Issue by xx-zhang** [ayamir/nvimdots#1137]
### Version confirmation

- [X] Confirm

### Following prerequisites

- [X] Confirm

### Not a user config issue

- [X] Confirm

### Neovim version

Nvim 0.9.5 

### Operating system/version

ArchL:inxu latest

### Terminal name/version

windows Terminal

### Branch info

main (Default/Latest)

### Fetch Preferences

HTTPS (use_ssh = false)

### Affected language servers

pylsp

### How to reproduce the issue

how to config outer pylsp extra_paths for python3.6 site-packeges  ;

i have trid like this and no use. what i wanted is using the conda-path `/soft/miniconda3` not the `venv` 

![image](https://github.com/ayamir/nvimdots/assets/47806549/caedf56d-a5d5-4271-b475-d20f0f8f1647)a

### Expected behavior

i can use the pkgs from the `extra_path` i have set 

### Support info

python:3.11.5 
all the latest, have updated the nvimdots as latest.

**Comment by ayamir** [comment]
Do you want to use self-installed `pylsp`?

**Comment by ayamir** [comment]
close due inactivity.
