### ISSUE TITLE
m1 mac 部分插件报错

### ISSUE THREAD

**Issue by toihrn** [ayamir/nvimdots#114]
**Describe the bug**
在m1芯片的mac中，nvim-treesitter和fzf等插件报错
mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64e')

**截图**

<img width="853" alt="image" src="https://user-images.githubusercontent.com/48119164/167355430-7e6c586e-6faa-435e-914a-b28cf9ab91ed.png">

**运行环境**

- 操作系统：m1 mac monterey 12.3.1
- `nvim`版本：0.7.0
- `nvim`安装方式：brew install 安装

**Comment by ayamir** [comment]
这个已经超出我能解决问题的范畴了，如果不需要lua的parser可以在配置里面删除

**Comment by tcstory** [comment]
报错的提示已经很明显了.  x86 和 arm 的架构兼容问题.. 这种只能你自己处理了

**Comment by ZhangHang** [comment]
可以参考 https://github.com/nvim-telescope/telescope-fzf-native.nvim/issues/23#issuecomment-860066581

**Comment by CharlesChiuGit** [comment]
for whom might be interested: https://github.com/nvim-telescope/telescope-fzf-native.nvim/issues/96
