### ISSUE TITLE
bug: <leader> doesn't work

### ISSUE THREAD

**Issue by Ahwxorg** [ayamir/nvimdots#1141]
### Version confirmation

- [X] Confirm

### Following prerequisites

- [X] Confirm

### Not a user config issue

- [X] Confirm

### Neovim version

NVIM v0.9.5 release

### Operating system/version

I am on Linux kernel 6.6.0, running Gentoo GNU/Linux aarch64 with glibc

### Terminal name/version

foot version: 1.16.2 -pgo +ime +graphemes -assertions

### $TERM environment variable

xterm-256color

### Branch info

main (Default/Latest)

### Fetch Preferences

HTTPS (use_ssh = false)

### How to reproduce the issue

1. Clone repo
2. Try <leader>
3. Leader does not work

### Expected behavior

Leader works

### Actual behavior

Leader does not work

**Comment by CharlesChiuGit** [comment]
It mostly b/c u haven't set those leader key in your terminal, i.e. your terminal doesn't pass the keybings to nvim.

**Comment by Ahwxorg** [comment]
Doesn't work with neither Kitty nor Foot, works on my old Neovim config...

**Comment by CharlesChiuGit** [comment]
have u clear the caches of the old nvim config? it might cause some issues.

**Comment by CharlesChiuGit** [comment]
u r using our default leader, right?

**Comment by Ahwxorg** [comment]
> have u clear the caches of the old nvim config? it might cause some issues.

Yes

**Comment by Ahwxorg** [comment]
> u r using our default leader, right?

Also yes, I did not change anything. Should be space.

**Comment by CharlesChiuGit** [comment]
u might what to describe more details of your situation; otherwise, it's pretty hard to help u, since it works for most of the ppl.

**Comment by Jint-lzxy** [comment]
> What do you need to know?

Can u include a short clip of pressing `<Space>` in normal mode? Since normally, there should be a `WhichKey` prompt showing up. Also, if u press `<Space>` in `showkey -a` what do u see?

**Comment by Ahwxorg** [comment]
![out](https://github.com/ayamir/nvimdots/assets/87855602/50d3fe9b-7f62-4345-bb8f-c2d53f776302)

**Comment by Ahwxorg** [comment]
Ignore the notifications lmao

**Comment by Ahwxorg** [comment]
![image](https://github.com/ayamir/nvimdots/assets/87855602/d3d2506b-07b4-4e7d-a196-021ab9708b54)
Running `:WhichKey` shows this ^^

**Comment by CharlesChiuGit** [comment]
guess u r using hyperland lol
nice settings btw lol

**Comment by Ahwxorg** [comment]
> can u tried map leader-key to , or other keys and give it another try?

How do I do that :full_moon_with_face:

> guess u r using hyperland lol
> nice config btw lol

Hyprland is sick indeed. Also runs flawlessly on my M2 MacBook, which anything using Xorg does not at all. Thanks :)

**Comment by Jint-lzxy** [comment]
Well TBH, I have _absolutely_ no idea why we mapped \<leader\> to \<Nop\>. But anyway, does removing the following two lines solve the problem?
https://github.com/ayamir/nvimdots/blob/f2cf03b254c21a69d3654c2c05014cd411ac14e2/lua/core/init.lua#L78-L79

**Comment by CharlesChiuGit** [comment]
> Well TBH, I have absolutely no idea why we mapped <leader> to <Nop>. But anyway, does removing the following two lines solve the problem?

I think we set those to <Nop> when we were using `,` as leader?

In my personal config, i set leader keys like this.
![image](https://github.com/ayamir/nvimdots/assets/32497323/dd1be33a-10bb-42b7-adce-eb4a7d0b952d)

**Comment by Jint-lzxy** [comment]
> I think we set those two lines to `<Nop>` when we were still using `,` as leader?

Aha, that makes sense lol I guess the original intention was to prevent advancing a character when pressing \<Space\>, but now it's obviously not necessary anymore XD

**Comment by ayamir** [comment]
Gentoo user too :) (with awesome wm and kitty), but never encounter this problem, it's weird.

**Comment by Ahwxorg** [comment]
> Well TBH, I have _absolutely_ no idea why we mapped <leader> to <Nop>. But anyway, does removing the following two lines solve the problem?
> 
> https://github.com/ayamir/nvimdots/blob/f2cf03b254c21a69d3654c2c05014cd411ac14e2/lua/core/init.lua#L78-L79

I removed those, set the leader to `,`, set it to ` ` again and now it works... Thanks!

**Comment by Ahwxorg** [comment]
Unrelated, is there an easy way to turn plugins on/off? I don't really want to use Codeium on every file, and I'd like to disable TabNine completely.

**Comment by Ahwxorg** [comment]
![image](https://github.com/ayamir/nvimdots/assets/87855602/b385fcba-295f-4edb-8e59-3570d880a4dc)
TabNine also kinda throws errors.

**Comment by Ahwxorg** [comment]
> Gentoo user too :) (with awesome wm and kitty), but never encounter this problem, it's weird.

I run Gentoo on everything except the Raspberry Pi's I own, since I don't like compiling on PoE fed devices :). Even homeserver/most VMs unless otherwise is needed. Gentoo is life :)

I use Foot though, I dislike Kitty, but keep it around since the colorscheme is perfect for kernel configurating lmao

**Comment by CharlesChiuGit** [comment]
> TabNine also kinda throws errors.

i think u need to make it executable?

**Comment by CharlesChiuGit** [comment]
> Unrelated, is there an easy way to turn plugins on/off? I don't really want to use Codeium on every file, and I'd like to disable TabNine completely.

check our wiki: https://github.com/ayamir/nvimdots/wiki/Usage

**Comment by Ahwxorg** [comment]
> check our wiki: https://github.com/ayamir/nvimdots/wiki/Usage

Oh, yeah, sorry. I should've done that earlier...
