### ISSUE TITLE
How to config language servers like `glsl-analyzer` which is not managed by `mason.nvim`?

### ISSUE THREAD

**Issue by Penguin-SAMA** [ayamir/nvimdots#1149]
### Version confirmation

- [X] Confirm

### Following prerequisites

- [X] Confirm

### Neovim version

NVIM v0.9.5

### Branch info

main (Default/Latest)

### Minimal (user) folder structure required to reproduce the issue

```console
user/configs/lsp-servers/glsl-analyzer.lua
user/configs/lsp-servers/glslls.lua
```

### Minimal config with steps on how to reproduce the issue

this the config on user/configs/lsp-servers/glsl-analyzer.lua
![image](https://github.com/ayamir/nvimdots/assets/50973632/ddae6a1b-4942-4bf5-bfb9-3b6e17c71102)

this the config on user/configs/lsp-servers/glslls.lua
![image](https://github.com/ayamir/nvimdots/assets/50973632/5b4b5138-378d-4126-8b26-fed68bfadfbe)

### Expected behavior

the config file seem not to be loaded

### Additional information

this is `:LspInfo` 
![image](https://github.com/ayamir/nvimdots/assets/50973632/c621a512-26ec-4721-b578-e433c9596e28)

**Comment by Penguin-SAMA** [comment]
and when i use `TSUninstall glsl`

![image](https://github.com/ayamir/nvimdots/assets/50973632/03b0689c-e47e-405f-b73e-ef2e91a9a42f)

**Comment by CharlesChiuGit** [comment]
bruh, `TSUninstall` is for treesitter parsers.
`glsl-analyzer` and `glslls` is language server.

did u state those LS in the config or install them manually yet?

**Comment by Penguin-SAMA** [comment]
> did u state those LS in the config or install them manually yet?

i only use `:TSInstall glsl`, and created the two files mentioned above. Is there anything else that needs to be stated?

**Comment by CharlesChiuGit** [comment]
i not familiar with `glslls` or `glsl-analyzer`, but i think `:TSInstall glsl` can only give u syntax highlighting, not the LS itself.
check this:
https://github.com/nvim-treesitter/nvim-treesitter#supported-languages
https://github.com/theHamsta/tree-sitter-glsl
> This is a extension of [tree-sitter-c](https://github.com/tree-sitter/tree-sitter-c) to support the syntax of GLSL (https://www.khronos.org/opengl/wiki/Core_Language_(GLSL)).

Since `Mason` doesn't have `glslls` or `glsl-analyzer` supported, u need to download/compile them by yourself and add them to your `PATH`.
https://github.com/nolanderc/glsl_analyzer#installation
https://github.com/svenstaro/glsl-language-server#compile

**Comment by CharlesChiuGit** [comment]
btw, i encourage u did some research on `tree-sitter parser` and `language server protocol` to give u a better idea about what your doing next time.

i never heard of `glsl` b/4 today, i just did some searching.

**Comment by Penguin-SAMA** [comment]
I found [this](https://github.com/nolanderc/glsl_analyzer?tab=readme-ov-file#usage) in the README of glsl_analyzer, but I don't know how to add it to nvimdots. I don't want to modify the default init.lua

**Comment by CharlesChiuGit** [comment]
Since `glsl_analyzer` is not in [mason-registry](https://github.com/mason-org/mason-registry), u dont need to add it to `[lsp_deps]`.

u also need to make a user_custom lspconfig entry for `glsl_analuzer` like this:
https://github.com/ayamir/nvimdots/blob/b0513aadaba9aead3cba940237a092538d2d2a26/lua/modules/configs/completion/lsp.lua#L9-L17

**Comment by Penguin-SAMA** [comment]
like this?
``` lua
if vim.fn.executable("glsl-analyzer") == 1 then
		local glsl_opts = {
			-- 在这里放置 glsl-analyzer 的特定配置选项
		}
		local final_glsl_opts = vim.tbl_deep_extend("keep", glsl_opts, opts)
		nvim_lsp.glsl_analyzer.setup(final_glsl_opts)
	end
```

**Comment by CharlesChiuGit** [comment]
yeap

**Comment by Penguin-SAMA** [comment]
But it still doesn't work, the .vert files don't have any language server functionality.
![image](https://github.com/ayamir/nvimdots/assets/50973632/9b041368-40c7-4e95-bcdb-9910a965daa3)
![image](https://github.com/ayamir/nvimdots/assets/50973632/d1d5e5d5-a79b-4203-a99c-855651e6de6a)

**Comment by CharlesChiuGit** [comment]
can u call glsl-analyzer from any path?

or can u show us your whole config?

**Comment by Penguin-SAMA** [comment]
Also, I found that glsl-analyzer seems to require the vim-glsl plugin, but even after installing the vim-glsl plugin, it's not effective.

**Comment by Penguin-SAMA** [comment]
Oh, I think I understand now. vim-glsl is written in Vimscript, and it requires running the following statement:[path](https://github.com/tikhomirov/vim-glsl/blob/master/ftdetect/glsl.vim)
``` vimscript
" Language: OpenGL Shading Language
" Maintainer: Sergii Tykhomyrov <sergii@tykhomyrov.net>

" Extensions supported by Khronos reference compiler (with one exception, ".glsl")
" https://github.com/KhronosGroup/glslang
autocmd! BufNewFile,BufRead *.vert,*.tesc,*.tese,*.glsl,*.geom,*.frag,*.comp,*.rgen,*.rmiss,*.rchit,*.rahit,*.rint,*.rcall set filetype=glsl

" vim:set sts=2 sw=2 :
```

And my `user/plugins/vim-glsl.lua` is as follows:
![image](https://github.com/ayamir/nvimdots/assets/50973632/e9eb19a7-292f-426b-8aa3-ee232a0a5c2d)
If I use `:set=glsl` in any file, both vim-glsl and glsl-analyzer work fine.

**Comment by ayamir** [comment]
1. Create `lua/user/configs/lsp.lua`:
```lua
local nvim_lsp = require("lspconfig")
local opts = {
	capabilities = require("cmp_nvim_lsp").default_capabilities(vim.lsp.protocol.make_client_capabilities()),
}
-- Setup lsps that are not supported by `mason.nvim` but supported by `nvim-lspconfig` here.
if vim.fn.executable("glsl_analyzer") == 1 then
	local ok, _opts = pcall(require, "user.configs.lsp-servers.glsl_analyzer")
	if ok then
		local final_opts = vim.tbl_deep_extend("keep", _opts, opts)
		nvim_lsp.glsl_analyzer.setup(final_opts)
	end
end
```
2. Create `lua/user/configs/lsp-servers/glsl_analyzer.lua`
```lua
return {
	default_config = {
		cmd = { "glsl_analyzer" },
		filetypes = { "glsl", "vert", "tesc", "tese", "frag", "geom", "comp" },
		single_file_support = true,
	},
	docs = {
		description = [[
https://github.com/nolanderc/glsl_analyzer

Language server for GLSL
    ]],
	},
}
```
3. Open a `glsl` file:
![image](https://github.com/ayamir/nvimdots/assets/61657399/b238642f-c996-4a15-a70d-83ae308d56da)

NOTE: find a bug that `nvim` will recognize `vert` file as `conf` wrongly, need to `set filetype=vert` manually then `glsl_analyzer` will works for it.

![image](https://github.com/ayamir/nvimdots/assets/61657399/5c966e9d-d76b-4e0b-82aa-71c1fabccfa8)

**Comment by CharlesChiuGit** [comment]
damn @ayamir that's what i'm doing lol.

**Comment by Penguin-SAMA** [comment]
This is so cool! Thank you for your help!
