### ISSUE TITLE
refactor: organized keymaps group

### ISSUE THREAD

**Issue by CharlesChiuGit** [ayamir/nvimdots#1153]
https://github.com/ayamir/nvimdots/pull/1134#issuecomment-1891995931

todo:

leader+g, for git operations
leader+p, for package management
leader+l, for lsp related keymaps

brain storm time!

**Comment by ayamir** [comment]
I committed just now with new keymap here: https://github.com/ayamir/nvimdots/pull/1134/commits/a9bdd12f08b20fa89bd313d993258c0b6a944345

**Comment by CharlesChiuGit** [comment]
@ayamir 
![image](https://github.com/ayamir/nvimdots/assets/32497323/9134b296-cebb-4b36-91b7-2176c99fe883)

which branch is this commit in?
