### ISSUE TITLE
How to turn off the black strip？

### ISSUE THREAD

**Issue by shaojunjie0912** [ayamir/nvimdots#1154]
Hi, how can I turn off the black strip like this:

<img width="1280" alt="Snipaste_2024-01-18_11-02-30" src="https://github.com/ayamir/nvimdots/assets/96936298/b1738546-d4ac-4b9a-8469-6ab6fa84e378">

Thanks a lot!

**Comment by ayamir** [comment]
`lua/user/options.lua`
```lua
local options = {
	cursorcolumn = false,
}

return options
```
