### ISSUE TITLE
[enhancement] Project specific LSP configurations

### ISSUE THREAD

**Issue by ClSlaid** [ayamir/nvimdots#1156]
### Feature description

As a former VS Code user, I've been missing its per-project configurations for a long time. 

For some projects, we would like to check with different LSP or linters. Like the rust compiler project, its layout differs from most rust projects, and thus confuses LSP servers. So painfully, you have to configure manually.

With VS Code, we could just leave an ".vscode" folder containing project specific configurations.

Thankfully, the rust project [recommends](https://rustc-dev-guide.rust-lang.org/building/suggested.html#neovim) a plugin named [neoconf.nvim](https://github.com/folke/neoconf.nvim/). 

![图片](https://github.com/ayamir/nvimdots/assets/44747719/e1afdf59-93be-472e-88a2-9536f39811f6)

After trying, I found it actually able to read from ".vscode" project configurations. And I'd like to integrate it into this distro.

**Comment by CharlesChiuGit** [comment]
seems nice to have.
