### ISSUE TITLE
Use SSH to download the Mason package

### ISSUE THREAD

**Issue by Cyberczy** [ayamir/nvimdots#1158]
### Feature description

We have already used SSH to download plugins and treesitter. Can we use SSH to download the Mason package?

### Additional information

![image](https://github.com/ayamir/nvimdots/assets/109653523/11b0fef7-6495-4fbc-828d-b906939789a4)

**Comment by CharlesChiuGit** [comment]
nice to have, it should be fairly easy. do u want to make the pr?

**Comment by Cyberczy** [comment]
Sorry, I'm in the process of moving recently and may not have much time.

**Comment by Cyberczy** [comment]
SSH seems unable to download files from the releases.
![image](https://github.com/ayamir/nvimdots/assets/109653523/1abc29ba-3b24-4f9a-8ee7-dd665dfb7880)

**Comment by CharlesChiuGit** [comment]
aha indeed, u can only use ssh clone for `git@github.comXXXXX.git`, releases are not git object.
maybe it's not doable.

**Comment by Cyberczy** [comment]
lol.
