### ISSUE TITLE
There is an error in the wiki.

### ISSUE THREAD

**Issue by pCandKa** [ayamir/nvimdots#1160]
There is an error in the wiki.
![image](https://github.com/ayamir/nvimdots/assets/69684715/8dadee8e-9dfa-4d96-bbed-6e48cdc73c9c)
It should be "configs"

**Comment by pCandKa** [comment]
I tried "config," but it doesn't work.

**Comment by Cyberczy** [comment]
Fixed in https://github.com/ayamir/nvimdots/wiki/_compare/ce55adbe80d4b5b80a531a3c3b35b3b8c0228c87

**Comment by pCandKa** [comment]
> 已修复https://github.com/ayamir/nvimdots/wiki/_compare/ce55adbe80d4b5b80a531a3c3b35b3b8c0228c87

棒棒
