### ISSUE TITLE
Sniprun unbale to start

### ISSUE THREAD

**Issue by It-is-Sean** [ayamir/nvimdots#1161]
### Version confirmation

- [X] Confirm

### Following prerequisites

- [X] Confirm

### Neovim version

NVIM v0.9.5

### Branch info

main (Default/Latest)

### Minimal (user) folder structure required to reproduce the issue

```console
├─core
├─keymap
├─modules
│  ├─configs
│  │  ├─completion
│  │  │  ├─formatters
│  │  │  └─servers
│  │  ├─editor
│  │  ├─lang
│  │  ├─tool
│  │  │  └─dap
│  │  │      └─clients
│  │  └─ui
│  ├─plugins
│  └─utils
├─user
│  ├─configs
│  │  ├─dap-clients
│  │  ├─formatters
│  │  └─lsp-servers
│  ├─keymap
│  └─plugins
└─user_template
    ├─configs
    │  ├─dap-clients
    │  ├─formatters
    │  └─lsp-servers
    ├─keymap
    └─plugins
```

### Minimal config with steps on how to reproduce the issue

<leader> r
Error detected while processing function SnipRunLauncher:
line    6:
E5108: Error executing lua Vim:E475: Invalid value for argument cmd: 'C:\Users\jiang\AppData\Local\nvim-data\site\lazy\sniprun/target/release/sniprun' is not executable
stack traceback:
        [C]: in function 'jobstart'
        ...ppData/Local/nvim-data/site/lazy/sniprun/lua/sniprun.lua:210: in function 'start'
        ...ppData/Local/nvim-data/site/lazy/sniprun/lua/sniprun.lua:214: in function 'notify'
        ...ppData/Local/nvim-data/site/lazy/sniprun/lua/sniprun.lua:226: in function 'run'
        [string ":lua"]:1: in main chunk

### Expected behavior

.

**Comment by ayamir** [comment]
Unfortunately, `sniprun` doesn't support windows: https://github.com/michaelb/sniprun?tab=readme-ov-file#known-limitations

**Comment by ayamir** [comment]
Maybe https://github.com/CRAG666/code_runner.nvim is a better choice for windows? Have not test it.

**Comment by It-is-Sean** [comment]
I’ve tried [https://github.com/Zeioth/Compiler.nvim](url) but it doesn’t work well either. Maybe using WSL is the best solution? I don’t know.

**Comment by ayamir** [comment]
> I’ve tried [https://github.com/Zeioth/Compiler.nvim](url) but it doesn’t work well either. Maybe using WSL is the best solution? I don’t know.

Maybe, I'm using WSL on windows now and everything works perfect.
