### ISSUE TITLE
Some questions about Neodim

### ISSUE THREAD

**Issue by Penguin-SAMA** [ayamir/nvimdots#1164]
### Version confirmation

- [X] Confirm

### Following prerequisites

- [X] Confirm

### Not a user config issue

- [X] Confirm

### Neovim version

NVIM v0.10.0-dev

### Operating system/version

WSL Ubuntu 24.04

### Terminal name/version

zsh

### Branch info

main (Default/Latest)

### Fetch Preferences

HTTPS (use_ssh = false)

### How to reproduce the issue

When I open any file with nvim, the following error occurs.
![image](https://github.com/ayamir/nvimdots/assets/50973632/f39899cb-0c6f-4f8e-97ef-6d57f0d812a3)

I have checked issue #1139, but if I insist on using nvim v0.10, how should I modify my configuration to eliminate this error?

### Expected behavior

no error

**Comment by ayamir** [comment]
switch to `0.10` branch.

**Comment by Penguin-SAMA** [comment]
thx

**Comment by Penguin-SAMA** [comment]
sry, i cant switch to 0.10 branch.
![image](https://github.com/ayamir/nvimdots/assets/50973632/f3d77484-6cd6-4d8a-88a1-a2acbf9d6ff3)

**Comment by CharlesChiuGit** [comment]
it's always a gd idea to learn your tools better.
![image](https://github.com/ayamir/nvimdots/assets/32497323/0be40b76-8913-4736-95fd-fbd61aa4580a)

**Comment by Penguin-SAMA** [comment]
@CharlesChiuGit 
I've tried using `git branch -r`, and the display is as follows:
![image](https://github.com/ayamir/nvimdots/assets/50973632/2289c1b6-1983-4ab7-89cc-cd3cd0b97b6a)
and then it still doesn't work
![image](https://github.com/ayamir/nvimdots/assets/50973632/64be7b74-0c98-4948-8f3b-e19a05a01cb3)

**Comment by CharlesChiuGit** [comment]
u r using a sallow clone, u need deep clone.

reclone nvimdots

**Comment by ayamir** [comment]
`git fetch --all` then `git branch -v` you will see the 0.10 branch.

**Comment by ycpss91255** [comment]
I tried switching to the 0.10 branch, but the problem still exists
