### ISSUE TITLE
When I open a file, nvim is not in the current directory

### ISSUE THREAD

**Issue by Penguin-SAMA** [ayamir/nvimdots#1166]
### Version confirmation

- [X] Confirm

### Following prerequisites

- [X] Confirm

### Not a user config issue

- [X] Confirm

### Neovim version

NVIM v0.10.0-dev

### Operating system/version

WSL Ubuntu 24.04

### Terminal name/version

zsh

### Branch info

0.10 (Nightly)

### Fetch Preferences

SSH (use_ssh = true)

### How to reproduce the issue

I am currently in the `~/test/test` directory, and when I use `nvim`, the directory is correct; but when I use `nvim` followed by any file name, it automatically jumps to the home directory. This includes all behaviors of `:cd`, `treesitter`, and the floating terminal, which are all operating under the home directory.

### Expected behavior

Operate in the currently opened directory.

**Comment by Deg2v** [comment]
I encountered a similar problem where certain directories are recognized as a project, so nvim will jump to the project directory, so I `manual_mode =true,` in `~/.config/nvim/lua/modules/configs/tool/project.lua`. `project.nvim` says `Manual mode doesn't automatically change your root directory`.I hope it will be helpful to you.

**Comment by CharlesChiuGit** [comment]
> I am currently in the ~/test/test directory, and when I use nvim, the directory is correct; but when I use nvim followed by any file name, it automatically jumps to the home directory. This includes all behaviors of :cd, treesitter, and the floating terminal, which are all operating under the home directory.

it not a bug, it's by design.

**Comment by Penguin-SAMA** [comment]
@Deg2v  Thx, its useful

**Comment by Jint-lzxy** [comment]
This seems to be a duplicate of https://github.com/ayamir/nvimdots/issues/677. Please refer to that issue for additional information.
