### ISSUE TITLE
In Inerst mode use <C-BS> mapping <C-w> not work

### ISSUE THREAD

**Issue by ycpss91255** [ayamir/nvimdots#1167]
### Version confirmation

- [X] Confirm

### Following prerequisites

- [X] Confirm

### Neovim version

NVIM v0.9.4

### Branch info

main (Default/Latest)

### Minimal (user) folder structure required to reproduce the issue

```console
lua/user/keymap/core.lua
```

### Minimal config with steps on how to reproduce the issue

This is my config('core.lua'):
```lua
return {
	["i|<C-BS>"] = map_cmd("<C-w>"):with_noremap():with_desc(""),
	["i|<C-H>"] = map_cmd("<C-w>"):with_noremap():with_desc(""),
}
```

### Expected behavior

Equivalent to <C-w> in insert mode.
I can use nvim command mode and enter `:imoremap <C-H> <C-w>` and it will be successful.

**Comment by ayamir** [comment]
Hi, it's because the `imap` of `<C-h>` is overrided by `autoclose.nvim`.
![image](https://github.com/ayamir/nvimdots/assets/61657399/9897dc13-cc97-4c99-ae31-69bb9a931706)
If you remap `imap <C-H> <C-W>` after this plugin loaded, it will works normally.

**Comment by ayamir** [comment]
`inoremap` works for me too.

**Comment by ycpss91255** [comment]
Suddenly I cam do it too, thank you
