### ISSUE TITLE
请教补全的问题

### ISSUE THREAD

**Issue by JerryAllison** [ayamir/nvimdots#117]
ayamir，你好！
我想问下，我最近使用nvim写go代码时，发现只能补全在代码内的变量、关键字补全，但是go自带的库文件的函数无法补全，这是怎么回事？
<img width="489" alt="image" src="https://user-images.githubusercontent.com/5206758/167623824-1937a438-afb0-449d-9ba9-e9c948366335.png">

**Comment by ayamir** [comment]
`LspInfo`看一下`gopls`有没有启动

**Comment by JerryAllison** [comment]
<img width="403" alt="image" src="https://user-images.githubusercontent.com/5206758/167978073-f0cde6ac-2752-4383-a913-23fc73e26ebe.png">
nvim里没有这个命令

**Comment by JerryAllison** [comment]
非常感谢，已经ok了，需要打一个go文件才能看到LSP相关的命令
