### ISSUE TITLE
Made improvement for startup time.

### ISSUE THREAD

**Issue by Cyberczy** [ayamir/nvimdots#1171]
### Feature description

Before:
![image](https://github.com/ayamir/nvimdots/assets/109653523/ae3715c8-b121-4cbc-b952-9c7795a8fe60)
Now:
![image](https://github.com/ayamir/nvimdots/assets/109653523/70bb7bae-e775-4d6c-a1de-25f6ca5dd79c)
---
I made the following changes.
```lua
require("core.options")
require("core.pack")
vim.api.nvim_create_autocmd("User", {
	pattern = "VeryLazy",
	callback = function()
		require("core.mapping")
		require("core.event")
		require("keymap")
	end,
})
```
I don't know if this affects the normal use of nvimdots, can you take a look?

**Comment by Cyberczy** [comment]
> visible issues `{ "FileType", "alpha", "set showtabline=0" },`don't work ![image](https://private-user-images.githubusercontent.com/109653523/303340053-d2ab90fa-0edc-453b-93eb-824bedbe8d16.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDczOTgxNzcsIm5iZiI6MTcwNzM5Nzg3NywicGF0aCI6Ii8xMDk2NTM1MjMvMzAzMzQwMDUzLWQyYWI5MGZhLTBlZGMtNDUzYi05M2ViLTgyNGJlZGJlOGQxNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIwOFQxMzExMTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00NjRkOGMyMjFiOGZlNGIyYmE0Yjk5NTRlMDYyMTBlY2I5MTA4ZDU5Y2IzMTg0MGVlMjVlNmVmZWM0N2JjOGU1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.eOSXYOVOKjuZYb0GYOsDEhzStUDJkmykiHovBQBkt_M)

fixed in alpha.lua
```lua
vim.api.nvim_create_autocmd("User", {
	pattern = "LazyVimStarted",
	callback = function()
		vim.o.showtabline = 0 -- this line
		dashboard.section.footer.val = footer()
		pcall(vim.cmd.AlphaRedraw)
	end,
})
```

**Comment by Mythos-404** [comment]
On my wsl2(archlinux), windows, archlinux I can only get `1~2ms` improvement after testing. This is really not necessary and can lead to some binding problems!

**Comment by Cyberczy** [comment]
Just a suggestion lol

**Comment by ayamir** [comment]
Agree with @Mythos-404, this improvement is limited. And current implementation is more readable. IMO the startup time is not the main issue now because less than 30ms is a value that is acceptable to most of humans. Thanks for your efforts.
