### ISSUE TITLE
Can I eliminate these prompts?

### ISSUE THREAD

**Issue by Penguin-SAMA** [ayamir/nvimdots#1179]
### Version confirmation

- [X] Confirm

### Following prerequisites

- [X] Confirm

### Not a user config issue

- [X] Confirm

### Neovim version

NVIM v0.10.0-dev-951+g5d8ab32f3-Homebrew

### Operating system/version

WSL Ubuntu 24.04

### Terminal name/version

zsh

### Branch info

0.10 (Nightly)

### Fetch Preferences

SSH (use_ssh = true)

### How to reproduce the issue

![image](https://github.com/ayamir/nvimdots/assets/50973632/58882937-5676-45c0-a0f6-592cec1d4829)

### Expected behavior

Can I eliminate these prompts?

**Comment by CharlesChiuGit** [comment]
seems like your custom plugin, nothing wrong on my side.
```
NVIM v0.10.0-dev-2397+ga9f578b7a
Build type: RelWithDebInfo
LuaJIT 2.1.1707061634
```
```
branch 0.10
```

**Comment by Penguin-SAMA** [comment]
However, whenever I open any editable file, this prompt pops up. How should I locate the source of the error?
``` txt
NVIM v0.10.0-dev-2397+ga9f578b7a
Build type: RelWithDebInfo
LuaJIT 2.1.1707061634
Run "nvim -V1 -v" for more info
```

**Comment by CharlesChiuGit** [comment]
have u check your custom plugin yet?

**Comment by vollowx** [comment]
aerial.nvim as the error notification says

**Comment by Penguin-SAMA** [comment]
thx, I commented out a certain line in diagnostic.lua, and now it no longer shows an error message.

**Comment by CharlesChiuGit** [comment]
https://github.com/nvimtools/none-ls.nvim/issues/58

**Comment by CharlesChiuGit** [comment]
https://github.com/nvimtools/none-ls.nvim/pull/77
