### ISSUE TITLE
输入shell命令卡顿

### ISSUE THREAD

**Issue by zzroot** [ayamir/nvimdots#118]
使用冒号进入命令行模式, 输入! shell命令,  卡顿严重

环境:  
wsl2 ubuntu20.04 lts
nvim 0.8.0-dev

**Comment by xuiv** [comment]
ripgrep反应太慢了。

**Comment by ayamir** [comment]
0.8我还没有做适配，你用0.7试试

**Comment by ayamir** [comment]
我刚刚在arch的wsl2中试了一下并没有出现你所说的问题，可能是你的文件太多了

**Comment by zzroot** [comment]
我cd到test目录(test目录有10个文件和1个子目录, 子目录中有2个文件), 然后 nvim test.txt打开, 输入
    :!man gettimeofday
还是卡顿
0.7版本我这里安装不了(可能是环境问题), 目前没有办法测试

**Comment by ayamir** [comment]
这样执行shell命令的时候会调用wilder.nvim，你可以手动把这个插件删除之后再试试
