### ISSUE TITLE
Custom User mapping

### ISSUE THREAD

**Issue by omarabid** [ayamir/nvimdots#1182]
### Version confirmation

- [X] Confirm

### Following prerequisites

- [X] Confirm

### Neovim version

NVIM v0.9.5

### Branch info

main (Default/Latest)

### Minimal (user) folder structure required to reproduce the issue

```console
I'm wondering if `mapping.lua` is also merged. I added a `/lua/user/mapping.lua` file where I made changes to `core_map`; however, these are not picked up by Neovim. Changing `settings.lua` works, and so does changing the original `mapping.lua` file.

Custom `mapping.lua` file


local core_map = {}
core_map = {
....
}
return core_map
```

### Minimal config with steps on how to reproduce the issue

I am using the fresh `main` branch. Only one file added (`/lua/user/mapping.lua`)

### Expected behavior

I am expecting `/lua/user/mapping.lua` to be merged with the default mapping file.

**Comment by ayamir** [comment]
> I'm wondering if `mapping.lua` is also merged.

No, you can add your mappings in `lua/user/keymap/core.lua`.

**Comment by gezhanling** [comment]
How to remap ESC to CapsLock?
