### ISSUE TITLE
[none-ls] Deprecating builtins with unmaintained upstream or native LSP replacement

### ISSUE THREAD

**Issue by CharlesChiuGit** [ayamir/nvimdots#1183]
![image](https://github.com/ayamir/nvimdots/assets/32497323/411690d4-5ea7-49e5-83c6-186f024cfe5f)

https://github.com/nvimtools/none-ls.nvim/discussions/81
https://github.com/nvimtools/none-ls.nvim/pull/77

That PR will lead to some changes to our format/linting mechanism, since we explicitly disable formatting ability form LSs.

I suggest doing the following:
1. Pin `none-ls`' commit 'til further decision is made.
2. Decide to use other format/ linting management plugin or change our `lua/modules/configs/completion/formatting.lua` to comply w/ `none-ls`.

**Comment by CharlesChiuGit** [comment]
https://github.com/nvimtools/none-ls.nvim/commit/f81edad87bc6c1a4e675e8e97b22a62939ad4ade

**Comment by csyJoy** [comment]
Should we pin the [previous commit](https://github.com/nvimtools/none-ls.nvim/commit/bb680d752cec37949faca7a1f509e2fe67ab418a) of this [commit](https://github.com/nvimtools/none-ls.nvim/commit/f81edad87bc6c1a4e675e8e97b22a62939ad4ade)? the warning message is just annoying

**Comment by buptlibo** [comment]
The latest commit https://github.com/nvimtools/none-ls.nvim/commit/793c6071621814c61a14c24cdb43e9badd88f0af add a way to supress the deprecation warning, I think it's better for use.

**Comment by ayamir** [comment]
I tend to just remove `rustfmt` for us and keep using `none-ls`. Users should do their own changes for upstream changes.
