### ISSUE TITLE
nvim-cmp在termux中无法显示补全窗口

### ISSUE THREAD

**Issue by xuiv** [ayamir/nvimdots#119]
有没空啊，在ubuntu20.04中一切正常。lsp.log中有大量错误。

lua require("cmp").status() 显示nvim-cmp未加载。

**Comment by ayamir** [comment]
手头没有安卓设备，不知道termux怎么debug

**Comment by xuiv** [comment]
上bluestack

**Comment by xuiv** [comment]
git@github.com真难搞，这年头谁还不会用cloudflare和heroku搞个凳子。

**Comment by ayamir** [comment]
你可以把这几行去掉：
https://github.com/ayamir/nvimdots/blob/6640174ea6786da8f32d5752c95ce4bfdeb8d557/lua/core/pack.lua#L53
https://github.com/ayamir/nvimdots/blob/6640174ea6786da8f32d5752c95ce4bfdeb8d557/lua/modules/editor/config.lua#L68-L72
然后执行`PackerSync`

**Comment by xuiv** [comment]
直接动手改成https了，我以试过了，在nvim进入输入模式后，lua require("cmp").status()能显示信息了，只是termux里是unkonwn filetype ，在ubnutu中是ready filetype

**Comment by xuiv** [comment]
我fork了一份: https://github.com/xuiv/nvim，这玩意儿支持lsp，比vim方便一点。

**Comment by xuiv** [comment]
全部是unknown source names，没有ready source names和unused source names
用 :CmpStatus

看来还是有平台选择中没有Android

**Comment by xuiv** [comment]
我用这个简单配置测试，clangd lspconfig cmp都是正常的：
`
-- set chinese wubi input
vim.cmd([[
  set fencs=utf-8,ucs-bom,shift-jis,gb18030,gbk,gb2312,cp936
  set termencoding=utf-8
  set encoding=utf-8
  set fileencodings=ucs-bom,utf-8,cp936
  set fileencoding=utf-8
  set imsearch=0
  imap <C-Space> <C-_>
  nmap <C-Space> <C-_>
  set completeopt=menu,menuone,noselect
]])

vim.g.loaded_perl_provider = 0
vim.g.loaded_ruby_provider = 0

-- setup packer
local packer_install_path = vim.fn.stdpath('data')..'/site/pack/packer/start/packer.nvim'
if vim.fn.empty(vim.fn.glob(packer_install_path)) > 0 then
  packer_bootstrap = vim.fn.system({'git', 'clone', '--depth', '1', 'https://github.com/wbthomason/packer.nvim', packer_install_path})
end

require('packer').startup(function(use)
  -- My plugins here
  use 'yianwillis/vimcdoc'
  use 'yuweijun/vim-wb'

  use {
      "williamboman/nvim-lsp-installer",
      {
          "neovim/nvim-lspconfig",
          config = function()
              require("nvim-lsp-installer").setup {}
              local lspconfig = require("lspconfig")
              lspconfig.pyright.setup {}
          end
      }
  }

  use 'hrsh7th/cmp-nvim-lsp'
  use 'hrsh7th/cmp-buffer'
  use 'hrsh7th/cmp-path'
  use 'hrsh7th/cmp-cmdline'
  use 'hrsh7th/nvim-cmp'

  -- For vsnip users.
  use 'hrsh7th/cmp-vsnip'
  use 'hrsh7th/vim-vsnip'
  -- Automatically set up your configuration after cloning packer.nvim
  -- Put this at the end after all plugins
  if packer_bootstrap then
    require('packer').sync()
  end

  require("nvim-lsp-installer").setup({
      ensure_installed = { "pyright" }, -- ensure these servers are always installed
      automatic_installation = true, -- automatically detect which servers to install (based on which servers are set up via lspconfig)
      ui = {
          icons = {
              server_installed = "✓",
              server_pending = "➜",
              server_uninstalled = "✗"
          }
      }
  })

end)

-- setup nvim-cmp completion
local function config_nvim_cmp()
  local cmp = require("cmp")

  cmp.setup({
    snippet = {
      -- REQUIRED - you must specify a snippet engine
      expand = function(args)
        vim.fn["vsnip#anonymous"](args.body) -- For `vsnip` users.
        -- require('luasnip').lsp_expand(args.body) -- For `luasnip` users.
        -- require('snippy').expand_snippet(args.body) -- For `snippy` users.
        -- vim.fn["UltiSnips#Anon"](args.body) -- For `ultisnips` users.
      end,
    },
    window = {
      -- completion = cmp.config.window.bordered(),
      -- documentation = cmp.config.window.bordered(),
    },
    mapping = cmp.mapping.preset.insert({
      ['<C-b>'] = cmp.mapping.scroll_docs(-4),
      ['<C-f>'] = cmp.mapping.scroll_docs(4),
      ['<C-Space>'] = cmp.mapping.complete(),
      ['<C-e>'] = cmp.mapping.abort(),
      ['<CR>'] = cmp.mapping.confirm({ select = true }), -- Accept currently selected item. Set `select` to `false` to only confirm explicitly selected items.
    }),
    sources = cmp.config.sources({
      { name = 'nvim_lsp' },
      { name = 'vsnip' }, -- For vsnip users.
      -- { name = 'luasnip' }, -- For luasnip users.
      -- { name = 'ultisnips' }, -- For ultisnips users.
      -- { name = 'snippy' }, -- For snippy users.
    }, {
      { name = 'buffer' },
    })
  })

  -- Set configuration for specific filetype.
  cmp.setup.filetype('gitcommit', {
    sources = cmp.config.sources({
      { name = 'cmp_git' }, -- You can specify the `cmp_git` source if you were installed it.
    }, {
      { name = 'buffer' },
    })
  })

  -- Use buffer source for `/` (if you enabled `native_menu`, this won't work anymore).
  cmp.setup.cmdline('/', {
    mapping = cmp.mapping.preset.cmdline(),
    sources = {
      { name = 'buffer' }
    }
  })

  -- Use cmdline & path source for ':' (if you enabled `native_menu`, this won't work anymore).
  cmp.setup.cmdline(':', {
    mapping = cmp.mapping.preset.cmdline(),
    sources = cmp.config.sources({
      { name = 'path' }
    }, {
      { name = 'cmdline' }
    })
  })

  -- Setup lspconfig.
  local capabilities = require('cmp_nvim_lsp').update_capabilities(vim.lsp.protocol.make_client_capabilities())
  -- Replace <YOUR_LSP_SERVER> with each lsp server you've enabled.
  require('lspconfig')['clangd'].setup {
    capabilities = capabilities
  }
  require('lspconfig')['pyright'].setup {
    capabilities = capabilities
  }
end

config_nvim_cmp()

-- mkdir -p /data/data/com.termux/files/home/.local/share/nvim/lsp_servers/clangd/bin
-- cd /data/data/com.termux/files/home/.local/share/nvim/lsp_servers/clangd/bin
-- ln -s /data/data/com.termux/files/usr/bin/clangd .
`
