### ISSUE TITLE
Error while calling lua chunk: vim/_init_packages.lua:0: module 'vim.uri' not found

### ISSUE THREAD

**Issue by Robin329** [ayamir/nvimdots#1191]
### Version confirmation

- [X] Confirm

### Following prerequisites

- [X] Confirm

### Not a user config issue

- [X] Confirm

### Neovim version

$ nvim --version NVIM v0.10.0-dev Build type: RelWithDebInfo LuaJIT 2.1.0-beta3 Run "nvim -V1 -v" for more info

### Operating system/version

$ uname -a Linux rock-5b 5.10.110-36-rockchip-gba392dc725fa #rockchip SMP Tue Jan 17 07:19:43 UTC 2023 aarch64 GNU/Linux

### Terminal name/version

Terminal

### $TERM environment variable

xterm-256color

### Branch info

main (Default/Latest)

### Fetch Preferences

HTTPS (use_ssh = false)

### How to reproduce the issue

使用README安装命令第一次启动

### Expected behavior

正常启动无报错。

### Actual behavior

![image](https://github.com/ayamir/nvimdots/assets/22770951/54db275b-f0d2-40b2-8967-7a91bf74ba72)

**Comment by ayamir** [comment]
We don't support self-built `nvim` binary, please download the binary from github release or install it by the system package manager.
