### ISSUE TITLE
lack lgrep

### ISSUE THREAD

**Issue by mjkx5** [ayamir/nvimdots#1199]
### Feature description

when I input :lgrep in command model. It's like grep. 

It's lgrep in help.

lgr[ep][!] [arguments]	Same as ":grep", except the location list for the
			current window is used instead of the quickfix list.

### Additional information

when I input grep 
!rg --hidden --vimgrep --smart-case --  2>&1| tee /tmp/
when I input lgrep 
!rg --hidden --vimgrep --smart-case --  2>&1| tee /tmp/

lgrep cannot search in local file, but in all file.

**Comment by ayamir** [comment]
Can't understand your meaning. It works fine for me: `:lgrep config.json`
![image](https://github.com/ayamir/nvimdots/assets/61657399/58f84d53-1414-4930-9cf1-02026484ba57)

**Comment by mjkx5** [comment]
I understand that. It's weird. In that case, :grep and :lgrep are the same. 
:lgrep core % == :grep core %

**Comment by mjkx5** [comment]
lgrep core == grep core

**Comment by mjkx5** [comment]
It's indeedly solve my current problem. thanks.

**Comment by Jint-lzxy** [comment]
I'm going to close this issue as not planned to avoid further confusion. The only distinction between `:lgrep` and `:grep` lies in the storage location of the results. A _location-list_ (or a window-local quickfix-list) is used for `:lgrep` while the _quickfix-list_ is used for `:grep`. The search process itself remains identical for both (with results obtained using `|grepprg|`).
