### ISSUE TITLE
修改dashboard的executive无效

### ISSUE THREAD

**Issue by tian-deng** [ayamir/nvimdots#12]
**环境**: WSL2
**问题日志** 输入,ff提示Not an editor command: Clap files ++finder=rg --ignore --hidden --files
![image](https://user-images.githubusercontent.com/66667726/129552701-957630fc-3fcc-4414-ba44-e432ebb69c71.png)
**个人尝试** 删除掉 `.local/share/nvim` 和 `.config/nvim` 的文件夹重试了好几次都是这样的问题, 最小化配置的dashboard-nvim插件是可以正常切换为telescope的. 可以请教下哪里可能有问题么?

**Comment by tian-deng** [comment]
在 `~/.config/nvim/init.lua` 添加 `vim.g.dashboard_default_executive = 'telescope'` 可以正常使用, 不清楚哪里加载出现问题了...

**Comment by ayamir** [comment]
我这两天在WSL上面测试一下，你先这样用着。

**Comment by ayamir** [comment]
fixed at https://github.com/ayamir/nvimdots/commit/937db3808cc5153f18bd3e4d4553c02779282d9b.
