### ISSUE TITLE
nvim-treesitter warning

### ISSUE THREAD

**Issue by jwangtobeno1** [ayamir/nvimdots#1200]
### Version confirmation

- [X] Confirm

### Following prerequisites

- [X] Confirm

### Not a user config issue

- [X] Confirm

### Neovim version

NVIM v0.9.5

### Operating system/version

WSL2

### Terminal name/version

WSL2

### Branch info

main (Default/Latest)

### Fetch Preferences

SSH (use_ssh = true)

### How to reproduce the issue

Whenever I open a file through nvim, it will prompt the warning shown in the figure below：

![image](https://github.com/ayamir/nvimdots/assets/69038155/32cd0adb-70cf-4721-82c8-c517415add68)

![image](https://github.com/ayamir/nvimdots/assets/69038155/c3f12bd9-478a-4a07-9048-ee27e4719d37)

### Expected behavior

no this warning. 

Looking forward to your help, thanks

**Comment by vollowx** [comment]
_READ THE WARNING MSG BEFORE OPENING A NEW ISSUE PLZ 😕_

It simply says loading treesitter-context plugin through treesitter module is no longer supported, which means we now need to update the code.

**Comment by ayamir** [comment]
Our config has already changed for upstream. Do `git pull` to update your config.
https://github.com/ayamir/nvimdots/blob/main/lua/modules/configs/editor/ts-context-commentstring.lua
