### ISSUE TITLE
why use vim-go instead of go.nvim 

### ISSUE THREAD

**Issue by kincoy** [ayamir/nvimdots#1207]
### Feature description

- `go.nvim` is **github.com/ray-x/go.nvim**
- `vim-go` is **github.com/fatih/vim-go**

go.nvim offers more modern features and configurations than vim-go, and has an active community. Therefore, it is recommended to update the development plug-in for go to "ray-x/ go.nvim ".

**Comment by ayamir** [comment]
In fact, we have already used `go.nvim` in `0.10` branch.

**Comment by ayamir** [comment]
I'm currently developing with golang, and seems current lsp-related keymaps don't work when using these two plugins.

**Comment by mjkx5** [comment]
these plugin only navigate to interface, and do not navigate to real function. I do not know why. I can use ripgrep find the function. If exist some same name function, I do not know how to do. 

I have a question, whether navigate to exactly function in goland. have anybody used that?
