### ISSUE TITLE
when you in command line mode , click  <c-p>, It is not content my expect

### ISSUE THREAD

**Issue by mjkx5** [ayamir/nvimdots#1208]
### Feature description

I do not know whether it is bug or not.

when I  click <c-p> in command line mode, I expect that it switch to coammand before this command not completion. acturally, up key can switch to comand that I expected. additionly, in the bc02854 , <c-p> is that I expected.

**Comment by ayamir** [comment]
Can't understand, if it's related with the difference between `wilder.nvim` and `cmp-cmdline`. Hope #1209 helps.
