### ISSUE TITLE
Update catppuccin version (Huge performance issue on nightly)

### ISSUE THREAD

**Issue by nullchilly** [ayamir/nvimdots#1218]
### Feature description

Recently neovim changed luajit version to sync with [master commit](https://github.com/neovim/neovim/pull/27139) which broke catppuccin's `highlight_override` function cache and [blew up the complexity](https://github.com/catppuccin/nvim/issues/664)

# Before

![image](https://github.com/ayamir/nvimdots/assets/56817415/327a217b-bf22-4556-b325-f1030cf85915)

# With https://github.com/catppuccin/nvim/commit/836de8bc1898250b69332e66cbe993058870f849

![image](https://github.com/ayamir/nvimdots/assets/56817415/969055b5-a8f1-4954-a167-3aed3b1b3e92)

**Comment by ayamir** [comment]
@Jint-lzxy maybe we could switch back `https://github.com/catppuccin/nvim` for 0.10 temprarily?

**Comment by Jint-lzxy** [comment]
Hey @nullchilly @ayamir, I feel like I mentioned earlier in https://github.com/ayamir/nvimdots/issues/1213#issue-2220820680 that I've been a bit swamped lately, so I need some time to catch up on all the updates. But I'm almost done, so I should be able to start working on my forks (and the PRs in catppuccin) soon lmao. I'll have some free time afterwards (at least until the 0.10 release) to maintain this fork and keep it up to date regularly (also planning to start actively maintaining the `nvim` port, been "slacking off" for too long lolll), so there shouldn't be too many issues. Please bear with me for a bit, thanks!

**Comment by Jint-lzxy** [comment]
My fork should be up to date with the upstream rn 🥳 https://github.com/Jint-lzxy/nvim/compare/b6f54c74f8aea460b395c4b0ede9392dbab60424...refactor/syntax-highlighting
