### ISSUE TITLE
How to modify keymap for Vim plugin

### ISSUE THREAD

**Issue by Penguin-SAMA** [ayamir/nvimdots#1220]
### Version confirmation

- [X] Confirm

### Following prerequisites

- [X] Confirm

### Neovim version

NVIM v0.9.5

### Branch info

main (Default/Latest)

### Minimal (user) folder structure required to reproduce the issue

```console
.
├── configs
│   ├── visual-multi
│   │   └── visual-multi.lua
├── keymap
│   ├── tool.lua
├── plugins
│   ├── visual-multi.lua
└── settings.lua
```

### Minimal config with steps on how to reproduce the issue

I use the vim-visual-multi plugin and originally I filled in the configuration file as instructed in #901 (shown below)

`user/plugins/visual-multi.lua`

```lua
local custom = {}

custom["mg979/vim-visual-multi"] = {
	lazy = true,
	event = "BufReadPost",
	config = require("configs.visual-multi.visual-multi"),
}

return custom
```

`user/configs/visual-multi/viusal-multi.lua`

```lua
return function()
	vim.g.VM_maps["Find Under"] = "<C-m>" -- replace C-n
	vim.g.VM_maps["Find Subword Under"] = "<C-m>" -- replace visual C-n
	vim.g.VM_mouse_mappings = 1
end
```

However, after the recent update to v3.6.0, the configuration was found to be invalid. Then I looked at #1189 and the wiki link there. I changed the configuration to the following code:
`user/plugins/visual-multi.lua`

```lua
local custom = {}

custom["mg979/vim-visual-multi"] = {
	lazy = true,
	event = "BufReadPost",
	config = require("configs.visual-multi.visual-multi"),
	cmd = {
		"Find Under",
		"Find Subword Under",
	},
}

return custom
```

`user/configs/visual-multi/visual-multi.lua`

```lua
return function() end
```

`user/keymap/tool.lua`

```lua
local bind = require("keymap.bind")
local map_cu = bind.map_cu

return {
	["n|<C-d>"] = map_cu("Find Under"):with_noremap(),
	["n|<C-d>"] = map_cu("Find Subword Under"):with_noremap(),
}
```

But this still doesn't seem to work, I think maybe it's the configuration code of the vim plugin that is different, but I don't know how I should modify my configuration.

### Expected behavior

I can use `<C-d>` for word selection normally

**Comment by ayamir** [comment]
Not `user/plugins/visual-multi.lua` but `user/plugins/editor.lua`.

**Comment by Penguin-SAMA** [comment]
Now my config is as follows, but it still doesn't work.

`user/plugins/editor.lua`

```lua
custom["mg979/vim-visual-multi"] = {
	lazy = true,
	event = "BufReadPost",
	config = require("configs.visual-multi.visual-multi"),
}
```

`user/configs/visual-multi/visual-multi.lua`

```lua
return function()
	vim.g.VM_maps["Find Under"] = "<C-d>" -- replace C-n
	vim.g.VM_maps["Find Subword Under"] = "<C-d>" -- replace visual C-n
	vim.g.VM_mouse_mappings = 1
end
```

**Comment by CharlesChiuGit** [comment]
https://github.com/ayamir/nvimdots/wiki/Usage#modify-keymaps

**Comment by Penguin-SAMA** [comment]
Sorry, I've looked at this wiki page and I've tried the following two modifications and it still doesn't work. I don't know much about the configuration method of vim plug-in, so I don't know how to fill in the keymap.

`user/configs/visual-multi/visual-multi.lua`

```lua
return function()
	vim.g.VM_maps["Find Under"] = "<C-d>" -- replace C-n
	vim.g.VM_maps["Find Subword Under"] = "<C-d>" -- replace visual C-n
	vim.g.VM_mouse_mappings = 1
end
```

`user/keymap/tool.lua`

```lua
local bind = require("keymap.bind")
local map_cu = bind.map_cu

return {
	["n|<C-d>"] = map_cu("Find Under"):with_noremap(),
	["n|<C-d>"] = map_cu("Find Subword Under"):with_noremap(),
}
```

**Comment by CharlesChiuGit** [comment]
`user/keymap/tool.lua`

```lua
local bind = require("keymap.bind")
local map_cu = bind.map_cu

return {
	["n|<C-d>"] = map_cu("Find Under"):with_noremap(),
-	["n|<C-d>"] = map_cu("Find Subword Under"):with_noremap(),
+	["v|<C-d>"] = map_cu("Find Subword Under"):with_noremap(),
}
```

**Comment by Penguin-SAMA** [comment]
Still not working. After modification, `<C-d>` will jump to the last line of the file, and the shortcut key for visual-multi is still `<C-n>`.

**Comment by CharlesChiuGit** [comment]
r u using `<C-d>` under visual mode?

**Comment by CharlesChiuGit** [comment]
oh wait, why r u use "Find Under" in the keymaps directly, that should be a function.

**Comment by CharlesChiuGit** [comment]
u should use following command instead: https://github.com/mg979/vim-visual-multi/blob/e2ff111f123da6cf97f95b96b10eb95854f953c9/doc/vm-ex-commands.txt#L8-L21

**Comment by Penguin-SAMA** [comment]
I think the key code should be the following part?
https://github.com/mg979/vim-visual-multi/blob/e2ff111f123da6cf97f95b96b10eb95854f953c9/doc/vm-mappings.txt#L23-L29

So should I change the code to the following style?(But it still doesn't work)
`user\keymap\tool.lua`
```lua
local bind = require("keymap.bind")
local map_cu = bind.map_cu

return function()
	vim.g.VM_maps["Find Under"] = "<C-d>" -- replace C-n
	vim.g.VM_maps["Find Subword Under"] = "<C-d>" -- replace visual C-n
	vim.g.VM_mouse_mappings = 1
end
```

I just want to change visual-multi's default shortcut key <C-n> to <C-d>.

**Comment by ayamir** [comment]
`lua/user/plugins/editor.lua`
```lua
local editor = {}
editor["mg979/vim-visual-multi"] = {
	lazy = true,
	event = { "CursorHold", "CursorHoldI" },
	init = require("configs.editor.visual-multi"),
}
return editor
```
`lua/user/configs/editor/visual-multi.lua`
```lua
return function()
	vim.g.VM_default_mappings = 0
	vim.g.VM_maps = {
		["Find Under"] = "<C-x>",
		["Find Subword Under"] = "<C-x>",
	}
	vim.g.VM_mouse_mappings = 1
end
```
Not recommend register this map with `<C-d>` which is usually used to pagedown and it has conflicts with `neoscroll`.

In fact, seems all of vimscript-written plugins should use `init` rather than `config` to configure.

**Comment by Penguin-SAMA** [comment]
> In fact, seems all of vimscript-written plugins should use `init` rather than `config` to configure.

Yes, you are right. thanks for your help. 

And I thought it would be more helpful to provide some content on vim plugin writing in the wiki?

**Comment by ayamir** [comment]
> And I thought it would be more helpful to provide some content on vim plugin writing in the wiki?

Done.
