### ISSUE TITLE
[Help Wanted] How configuring plugins for neovim to support Rust-DAP and smart tips for variable types  in Rust

### ISSUE THREAD

**Issue by Kanna-jiahe** [ayamir/nvimdots#1223]
### Version confirmation

- [X] Confirm

### Following prerequisites

- [X] Confirm

### Neovim version

NVIM v0.9.5

### Branch info

main (Default/Latest)

### Minimal (user) folder structure required to reproduce the issue

```console
lua/user/plugins/rustaceanvim.lua
```

### Minimal config with steps on how to reproduce the issue

Configuration files are not available at this time

### Expected behavior

I would wish to change [rustaceanvim](https://github.com/mrcjkb/rustaceanvim) or [rust-tool.nvim](https://github.com/simrat39/rust-tools.nvim) to support Rust debugging and variable type display.

like this：
<img width="1026" alt="image" src="https://github.com/ayamir/nvimdots/assets/58724756/76d77a27-8308-4a71-bcaf-2220df4f9d65">
<img width="1027" alt="image" src="https://github.com/ayamir/nvimdots/assets/58724756/afff1349-edee-47e3-baf7-429baa541c39">

### Additional information

I am a new user of neovim and like the nvimdots configuration developed by the developers, and have read the tutorials in the wiki, but there are still some things that I do not understand, I hope that the respected developers can help me.

**Comment by CharlesChiuGit** [comment]
@ClSlaid might have some tips for u

**Comment by Kanna-jiahe** [comment]
I try configure rust-tools.nvim with this code
```lua
lang["mrcjkb/rustaceanvim"] = {
	lazy = true,
	ft = "rust",
	version = "^3",
	config = require("lang.rust"),
	dependencies = { "nvim-lua/plenary.nvim" },
}
lang["simrat39/rust-tools.nvim"] = {
	lazy = true,
	local rt = require("rust-tools")

        rt.setup({
            server = {
                rust = {
                    imports = {
                        granularity = {
                            group = "module",
                        },
                        prefix = "self",
                    },
                    cargo = {
                        buildScripts = {
                            enable = true,
                        },
                    },
                    procMacro = {
                        enable = true,
                    },
                    inlayHints = {
                        bindingModeHints = {
                            enable = true,
                        },
                        chainingHints = {
                            enable = true,
                        },
                        closingBraceHints = {
                            enable = true,
                        },
                    },
                },
            },
}
```

will be support inlayHints for Rust Types.

but i don't know how to configure dap-client for rust.

**Comment by ayamir** [comment]
`cargo build` first and debug with the correct binary path.

**Comment by Kanna-jiahe** [comment]
> `cargo build` first and debug with the correct binary path.
> 
> ![image](https://private-user-images.githubusercontent.com/61657399/322269315-ad38f128-29d4-414e-b1cc-98fc0daf5a1f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMxNzE0MTIsIm5iZiI6MTcxMzE3MTExMiwicGF0aCI6Ii82MTY1NzM5OS8zMjIyNjkzMTUtYWQzOGYxMjgtMjlkNC00MTRlLWIxY2MtOThmYzBkYWY1YTFmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE1VDA4NTE1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVmMWE1OGI2YTRlNzAzNjFhMTdlNzc4OGM5YWI5MzdhOGEwNDY1ZWFmNzlhODJhYzFkNjAzOWZkMWRjYTM5NjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Z1XDI3B_8fxSil3RdG61az_AY6B1iBMjbNBNQFLcQ7I) ![image](https://private-user-images.githubusercontent.com/61657399/322269339-83f83af0-795a-47c3-8f30-2cb1599e34e5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMxNzE0MTIsIm5iZiI6MTcxMzE3MTExMiwicGF0aCI6Ii82MTY1NzM5OS8zMjIyNjkzMzktODNmODNhZjAtNzk1YS00N2MzLThmMzAtMmNiMTU5OWUzNGU1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE1VDA4NTE1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIzMTYzYjdmZDgxOWRmMGExYzk3N2I0ZTIwYjQ3NDZiOTQxN2JiOGZlZWY1MjAxZmUxNjczZGQ4NjQ5ZDIzMTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.OVBnHVggYjruCi2ovN3B0Yeb7Bh5MqOx2yRcEt1XgSY)

It turns out that I did not perform the debugging steps properly. Thanks, this helps me a lot
