### ISSUE TITLE
maybe load_extension fzf bug 

### ISSUE THREAD

**Issue by mjkx5** [ayamir/nvimdots#1224]
### Version confirmation

- [X] Confirm

### Following prerequisites

- [X] Confirm

### Not a user config issue

- [X] Confirm

### Neovim version

NVIM v0.9.5

### Operating system/version

Linux version 6.6.25-1-lts (linux-lts@archlinux)

### Terminal name/version

kitty 0.33.1-3

### Branch info

main (Default/Latest)

### Fetch Preferences

SSH (use_ssh = true)

### How to reproduce the issue

when I input <c-p> ,error occurs

### Expected behavior

disappear this error . 

### Actual behavior

![Screenshot_09-Apr_16-44-49_kitty](https://github.com/ayamir/nvimdots/assets/52132505/b868d0f8-deb6-4d46-a6a3-75274d94415c)

### Additional information

when I input <c-p> ,error occurs. 
I try to fix that error, find out because of  require("telescope").load_extension("fzf").

I comment that line, the error disappear. I do not know whether other people encounter the error and why the error occur.

**Comment by CharlesChiuGit** [comment]
try this
```bash
cd ~/.local/share/nvim/site/lazy/telescope-fzf-native.nvim
rm -rf build
make
```

**Comment by mjkx5** [comment]
@CharlesChiuGit  It works, thanks .
