### ISSUE TITLE
Can't switch open-tabs

### ISSUE THREAD

**Issue by RivTian** [ayamir/nvimdots#1227]
### Version confirmation

- [X] Confirm

### Following prerequisites

- [X] Confirm

### Not a user config issue

- [X] Confirm

### Neovim version

nvim 9.5.0

### Operating system/version

macOS 14.4.1

### Terminal name/version

Kitty 0.32.1

### Branch info

main (Default/Latest)

### Fetch Preferences

SSH (use_ssh = true)

### How to reproduce the issue

1. Open two tabs
2. try use `tk` or `tj`
 - move to other tab
 

### Expected behavior

hope push `tk` or `tj` can move to other tab

### Actual behavior

find it can't switch tab

<img width="1355" alt="image" src="https://github.com/ayamir/nvimdots/assets/62837507/be401d8f-4175-48ad-ac20-45f84014d165">

### Additional information

ps: why not use `H` and `L` achieve move tab?

**Comment by CharlesChiuGit** [comment]
it's not `tab`, it's `buffer`.
so u should use the below keymaps.
![image](https://github.com/ayamir/nvimdots/assets/32497323/1ef04b22-c8e5-4d73-9e8a-d651e124aa3f)

**Comment by CharlesChiuGit** [comment]
> ps: why not use `H` and `L` achieve move tab?

current keymaps is set this way due to generations of evolving.

of course u can set your own keymaps: https://github.com/ayamir/nvimdots/wiki/Usage#modify-keymaps
