### ISSUE TITLE
How to setup the python environment?

### ISSUE THREAD

**Issue by SimFG** [ayamir/nvimdots#1228]
### Version confirmation

- [X] Confirm

### Following prerequisites

- [X] Confirm

### Not a user config issue

- [X] Confirm

### Neovim version

v0.9.5

### Operating system/version

macOS 13.0.1

### Terminal name/version

iterm2 Build 3.4.15

### Branch info

main (Default/Latest)

### Fetch Preferences

SSH (use_ssh = true)

### How to reproduce the issue

when i open my python project, but there are many import error. what should i do to solve it?
thanks a lot for your help and precious time.
i have install the `pvnivm` for the python.
![image](https://github.com/ayamir/nvimdots/assets/21985684/a899fd80-ffe5-4ede-bd54-9b4b5063fe2c)

### Expected behavior

there is no import error

**Comment by CharlesChiuGit** [comment]
how do u set u set up your python env?
did u enter the venv before opening any file in nvim?

**Comment by ayamir** [comment]
https://github.com/ayamir/nvimdots/issues/1113#issuecomment-1868824151

**Comment by SimFG** [comment]
@CharlesChiuGit i have do it.
![image](https://github.com/ayamir/nvimdots/assets/21985684/e4c54754-e9ea-4727-9ae1-49934917cdba)
![image](https://github.com/ayamir/nvimdots/assets/21985684/7254de42-6906-421e-b361-9005b4ba5440)

**Comment by CharlesChiuGit** [comment]
did mason.log suggest anything?

**Comment by SimFG** [comment]
where is the `mason.log`

**Comment by SimFG** [comment]
@CharlesChiuGit sorry for the late reply
![image](https://github.com/ayamir/nvimdots/assets/21985684/fc0e0ff8-e966-458a-af71-0aba2643ea81)

**Comment by CharlesChiuGit** [comment]
hmmm, seems normal in mason.log

**Comment by CharlesChiuGit** [comment]
u r sure 'pynvim' is installed in current python env?

**Comment by SimFG** [comment]
@CharlesChiuGit i have install the `pynvim` in the current python env.
![image](https://github.com/ayamir/nvimdots/assets/21985684/4bb72347-4042-4de0-8cec-d5284c5fdf0b)
but in the global python, i don't.

**Comment by SimFG** [comment]
i install the `pynvim` in the global env, it doesn't take effect.

**Comment by CharlesChiuGit** [comment]
hmmm, i'm not sure why.
Mine works fine.
![image](https://github.com/ayamir/nvimdots/assets/32497323/07d09e35-b22e-4d74-8175-23ff8f2439b5)

**Comment by ayamir** [comment]
Can't repro for me too. Try using `pyright`? 
`:MasonInstall pyright` and `MasonUninstall pylsp`

**Comment by SimFG** [comment]
@ayamir I tried executing them, but it still doesn't work

**Comment by Jint-lzxy** [comment]
Not exactly a Python expert, but a skim through [the](https://github.com/python-lsp/python-lsp-server/blob/develop/CONFIGURATION.md) [docs](https://github.com/microsoft/pyright/blob/main/docs/configuration.md) seems to suggest that pyright/pylsp has a pretty robust venv detection regime. AFAIU to fix this issue, u could create a `pyrightconfig.json` in ur project's root directory and drop in this (correct me if I'm off base lol):
```json
{
  "venv": "<name-of-the-venv>"
  "venvPath": "/path/to/venv",
}
```
If that tweak does the trick (with `pyright`), it's likely because pylsp's getting mixed up about where to look for venvs (it's only checking out the dirname of [these](https://github.com/neovim/nvim-lspconfig/blob/9266dc26862d8f3556c2ca77602e811472b4c5b8/lua/lspconfig/server_configurations/pyright.lua#L3-L11) [items](https://github.com/neovim/nvim-lspconfig/blob/9266dc26862d8f3556c2ca77602e811472b4c5b8/lua/lspconfig/server_configurations/pylsp.lua#L8-L14)). So, to sort this out right, u might need to tweak its config to point straight to the files in ur project root.

**Comment by SimFG** [comment]
@CharlesChiuGit When i uninstall the pylsp, and close the nvim. and then open the nvim, it auto install the pylsp and doesn't seem to use the  pyright
![image](https://github.com/ayamir/nvimdots/assets/21985684/3b821702-83d5-4b10-a7e5-60de4c4b4396)

**Comment by CharlesChiuGit** [comment]
u also need to disable pylsp in "lua/core/settings.lua" and config pyright .

check our wiki on how to do it.

**Comment by SimFG** [comment]
No matter what I try, nothing seems to work. 😥

**Comment by CharlesChiuGit** [comment]
https://github.com/ayamir/nvimdots/wiki/Usage#modify-lsps-linters-and-formatters

**Comment by ayamir** [comment]
> https://github.com/ayamir/nvimdots/wiki/Usage#modify-lsps-linters-and-formatters

@SimFG or just remove it in `core/settings.lua` temprarily.

<img width="1014" alt="image" src="https://github.com/ayamir/nvimdots/assets/61657399/aa25ff94-d5ad-4f7a-be1d-9eb1feccd531">

**Comment by ayamir** [comment]
Actually I also want to know [basedpyright](https://github.com/DetachHead/basedpyright) whether is good enough to replace pylsp as @CharlesChiuGit mentioned in #1172.

**Comment by SimFG** [comment]
![image](https://github.com/ayamir/nvimdots/assets/21985684/aadcb4e6-0a9c-4696-b0b0-e685eed36069)
so so so so ... god 😵‍💫

**Comment by SimFG** [comment]
there are all my diff. and i use the `conda` to manage the python environment.
![image](https://github.com/ayamir/nvimdots/assets/21985684/9510a567-0e1b-4faf-aca5-86f2b2c6948d)
![image](https://github.com/ayamir/nvimdots/assets/21985684/f4004605-f1cb-442e-a266-d5daab8378b4)
![image](https://github.com/ayamir/nvimdots/assets/21985684/663f33ce-54ee-4113-9028-67600eb041d3)
![image](https://github.com/ayamir/nvimdots/assets/21985684/8551e452-5d52-4c8b-a94c-c86882fbba58)
![image](https://github.com/ayamir/nvimdots/assets/21985684/57d68d79-0721-4ba0-958e-8b65ef39c8f0)
![image](https://github.com/ayamir/nvimdots/assets/21985684/7fcdc66c-2abb-4f2a-a977-ef711f93fbc6)
![image](https://github.com/ayamir/nvimdots/assets/21985684/bb070d5d-ff21-404d-a30a-421216a33677)
![image](https://github.com/ayamir/nvimdots/assets/21985684/68d532be-086a-45bb-ae15-e0db07531df8)
![image](https://github.com/ayamir/nvimdots/assets/21985684/be3fcca3-6b9a-4023-9130-badd1b47a09c)
![image](https://github.com/ayamir/nvimdots/assets/21985684/65d4beea-fc57-4872-939f-7f49d8509b1c)

**Comment by CharlesChiuGit** [comment]
Try `:MasonUninstallAll` and open nvim again too reinstall all lsp in the config.
Also screenshot `:NullLsInfo` and check what linter you have installed.

**Comment by CharlesChiuGit** [comment]
u can also use `:Trouble` to check which lsp is generating the warnings.

**Comment by SimFG** [comment]
@CharlesChiuGit after reinstall all lsp, it seem to work fine. But it seems that `*` can't recognize it. I don't know if it's normal.
![image](https://github.com/ayamir/nvimdots/assets/21985684/1cc5f6ba-63a2-424b-afb6-0f7105cbc24c)

**Comment by CharlesChiuGit** [comment]
that's normal since it's not the pythonic way to do `import` and it's unsafe

**Comment by SimFG** [comment]
@CharlesChiuGit @ayamir Thanks a lot lot lot !!!

**Comment by SimFG** [comment]
:LspInfo
![image](https://github.com/ayamir/nvimdots/assets/21985684/625d95f0-4ed0-49b2-b32b-0d1db8137623)
:NullLsInfo
![image](https://github.com/ayamir/nvimdots/assets/21985684/f24f48c8-dc1e-43b8-b16d-f9e162bb2f09)

**Comment by CharlesChiuGit** [comment]
yeah, it looks like `jedi-lsp`'s or `null-ls` linter's issue.
