### ISSUE TITLE
How to (re)install nvimdots

### ISSUE THREAD

**Issue by qinjianwei** [ayamir/nvimdots#1232]
### Feature description

我的neovim 启动一堆Error，想要升级或者卸载重装不知道如何操作

### Additional information

我的neovim 启动一堆Error，想要升级或者卸载重装不知道如何操作

**Comment by CharlesChiuGit** [comment]
what's your OS?
how do u install nvim?
r u using the latest commit on the main branch?
do u know git?

**Comment by qinjianwei** [comment]
windows  scoop 没有在最后提交的分支 会git

**Comment by CharlesChiuGit** [comment]
https://github.com/neovim/neovim/blob/master/INSTALL.md#windows

**Comment by GaugeAndGravity** [comment]
重装就重新执行 readme 里的安装命令就行了

**Comment by ayamir** [comment]
Remove completely:
https://github.com/ayamir/nvimdots/wiki/Issues#remove-nvimdots
Install:
```pwsh
Set-ExecutionPolicy Bypass -Scope Process -Force; Invoke-Expression ((New-Object System.Net.WebClient).DownloadString('https://raw.githubusercontent.com/ayamir/nvimdots/HEAD/scripts/install.ps1'))
```
