### ISSUE TITLE
<C-V> in NvimTree can't work

### ISSUE THREAD

**Issue by Penguin-SAMA** [ayamir/nvimdots#1234]
### Version confirmation

- [X] Confirm

### Following prerequisites

- [X] Confirm

### Not a user config issue

- [X] Confirm

### Neovim version

NVIM v0.9.5

### Operating system/version

WSL Ubuntu 24.04

### Terminal name/version

Windows Terminal

### Branch info

main (Default/Latest)

### Fetch Preferences

SSH (use_ssh = true)

### How to reproduce the issue

in NvimTree, when i use `<C-v>`
![image](https://github.com/ayamir/nvimdots/assets/50973632/9142aae9-2282-494f-a394-c73d443cd6a0)

but `<C-X>` is work
![image](https://github.com/ayamir/nvimdots/assets/50973632/c316f6d2-97ee-4458-8e32-1c07016c02f9)

I think there may be a conflict with the system's paste shortcut keys? But can I make it work properly without modifying the shortcut keys?

### Expected behavior

<C-v> can work

**Comment by CharlesChiuGit** [comment]
why would u want to paste in a file tree?

**Comment by CharlesChiuGit** [comment]
ahh got it.

> I think there may be a conflict with the system's paste shortcut keys?
ys, i think it is.

> But can I make it work properly without modifying the shortcut keys?
no, u have to modify it if u want to use it.

**Comment by Penguin-SAMA** [comment]
But I think the shortcut for "paste" should be <C-v> on most machines these days. If this is a mechanism and not a bug, then this default shortcut should be unusable for most people?
Or is this just a phenomenon unique to Windows Terminal?

**Comment by CharlesChiuGit** [comment]
it's not the case on macos and linux.

u need to consider 3 levels of keymaps: system level, terminal level, nvim level
so this is really hard to balance between between OSs.

u can suggest a better keymap u think is suitable or make a pr.

**Comment by Jint-lzxy** [comment]
I think the main issue here boils down to the fact that the _terminal_ holds all the cards when it comes to what gets sent to the TUI app. It's the "gatekeeper", catching all your keystrokes and deciding what to do with them - whether to handle them itself or pass them along to the TUI app. AFAIK most terminals do let you tweak which keys they handle internally and which ones they pass on. Checking out Windows Terminal's docs might shed some light on this.

> But I think the shortcut for "paste" should be `<C-v>` on most machines these days. If this is a mechanism and not a bug, then this default shortcut should be unusable for most people
> Or is this just a phenomenon unique to Windows Terminal?

I gotta admit this one is kinda user-dependent. There are still tons of platforms or emulators that either don't use `<C-v>` for pasting or won't mess with (or hijack) your input. Frankly the best advice we can offer is to get to know your terminal better if you really want `<C-v>` to work in NvimTree, just like what @CharlesChiuGit suggested.

**Comment by Penguin-SAMA** [comment]
Oh I see, on MacOS the shortcut for pasting is `<Command-V>` instead of <control-V>.

That is indeed the influence of Windows Terminal.

I think <C-V> is a good keymap so it doesn't need to be changed, so I removed the <Ctrl+V> action in windows Terminal.

it's bad to use Windows :(
