### ISSUE TITLE
In Inerst mode use <capslock> mapping <Esc> not work

### ISSUE THREAD

**Issue by gezhanling** [ayamir/nvimdots#1241]
### Version confirmation

- [X] Confirm

### Following prerequisites

- [X] Confirm

### Neovim version

NVIM v0.9.5

### Branch info

main (Default/Latest)

### Minimal (user) folder structure required to reproduce the issue

```console
lua/user/keymap/core.lua
```

### Minimal config with steps on how to reproduce the issue

return {
    ["i|<capslock>"] = map_cmd("<Esc>"):with_noremap():with_desc(""),
}

### Expected behavior

I want to use <capslock> mapping <Esc>

### Additional information

not response

**Comment by gezhanling** [comment]
I wrote wrong, the minimal config is:

`return {
  ["i|<capslock>"] = map_cmd("<Esc>"):with_noremap():with_desc(""),
}
`

**Comment by ayamir** [comment]
You'd better remap them using your OS, this work should not be done by `nvim`.

**Comment by gezhanling** [comment]
I use ahk script is:

`#SingleInstance, Force

SetCapsLockState, AlwaysOff
CapsLock::Esc
`
But it is only no response in neovim

**Comment by gezhanling** [comment]
I use ahk script is:

`
CapsLock::Esc
`

But it is only no response in neovim

**Comment by ayamir** [comment]
Use https://github.com/microsoft/PowerToys

**Comment by gezhanling** [comment]
It is also not work, but thank you anyway for your response. 
And I found that it is Neovim's bug.
[https://github.com/neovim/neovim/pull/8187](url)

**Comment by gezhanling** [comment]
I found a useful way eventually.
And it works well!
[https://ridge.hashnode.dev/how-to-exchange-the-function-of-esc-and-capslock-in-windows-os](url)
