### ISSUE TITLE
Color scheme

### ISSUE THREAD

**Issue by sanchitsahni07** [ayamir/nvimdots#1249]
### Feature description

make a tty color scheme as which blends with terminal so no other colorscheme to be there add this

**Comment by sanchitsahni07** [comment]
you should do that its bad ui and color schemes

**Comment by CharlesChiuGit** [comment]
i have no idea what your're talking about, and u can change colorscheme using whatever u like.
https://github.com/ayamir/nvimdots/wiki/Usage
