### ISSUE TITLE
UI FIX 

### ISSUE THREAD

**Issue by sanchitsahni07** [ayamir/nvimdots#1257]
### Feature description

if you need reference will send link but this theme is not good use nord onedark any there are many other

**Comment by sanchitsahni07** [comment]
anyone if you can add onedark or github rather than catppuccin it will be great

**Comment by Cyberczy** [comment]
You can fork this repository and then add onedark or github according to the [wiki](https://github.com/ayamir/nvimdots/wiki/Usage#steps-to-add-a-new-plugin).

**Comment by ayamir** [comment]
You can add it on your own.
