### ISSUE TITLE
Allow format timeouts to be set individually

### ISSUE THREAD

**Issue by misumisumi** [ayamir/nvimdots#1273]
### Feature description

Currently, the timeout for format on save is set to a uniform 1000 ms. ([code](https://github.com/ayamir/nvimdots/blob/239df8224fc0f4f2421daa437bb6f87477bd12e3/lua/modules/configs/completion/formatting.lua#L37C1-L38C48))
Some formatters require more than 1000 ms to complete, causing a timeout error.

Can this be modified so that it can be set per formatter or inherits the timeout setting for `none-ls`?

**Comment by ayamir** [comment]
We can make it a configurable option which applies for all formatter. IMO no need to use none-ls to configure it b/c it's lsp that is used instead of the formatter from none-ls for some language.

**Comment by Jint-lzxy** [comment]
#1275
