### ISSUE TITLE
gitsigns are not compatible

### ISSUE THREAD

**Issue by yinghaoyu** [ayamir/nvimdots#1304]
### Version confirmation

- [X] Confirm

### Following prerequisites

- [X] Confirm

### Not a user config issue

- [X] Confirm

### Neovim version

Nvim0.9.5

### Operating system/version

wsl-ubuntu20.04

### Terminal name/version

windows terminal

### Branch info

main (Default/Latest)

### Fetch Preferences

SSH (use_ssh = true)

### How to reproduce the issue

After updating the plugins.

### Expected behavior

Normal to use.

### Actual behavior

Additional tips.

**Comment by yinghaoyu** [comment]
![Uploading Snipaste_2024-06-21_10-26-41.png…]()

**Comment by CharlesChiuGit** [comment]
check our recent pr first.

**Comment by CharlesChiuGit** [comment]
#1300

**Comment by yinghaoyu** [comment]
![Uploading Snipaste_2024-06-21_10-26-41.png…]()
