### ISSUE TITLE
Error when use `gr` to rename

### ISSUE THREAD

**Issue by ayamir** [ayamir/nvimdots#1306]
### Version confirmation

- [X] Confirm

### Following prerequisites

- [X] Confirm

### Not a user config issue

- [X] Confirm

### Neovim version

NVIM v0.10.0

### Operating system/version

macOS 14.5 (23F79)

### Terminal name/version

kitty

### Branch info

0.10 (Nightly)

### Fetch Preferences

SSH (use_ssh = true)

### How to reproduce the issue

Trying to rename a function that appears in different files.

### Expected behavior

No error

### Actual behavior

![image](https://github.com/ayamir/nvimdots/assets/61657399/f1b8c7a4-66d7-44af-80a4-9be61493d431)

**Comment by ayamir** [comment]
It has to do with `ghost_text` introduced in #733.

**Comment by Jint-lzxy** [comment]
@ayamir Did u mean `gr` or `gR` (uppercase)? Tho I can't seem to reproduce this using either of them on my end, maybe u could upload the document in question so that things could be easier to understand?

**Comment by ayamir** [comment]
I'm coding for my company so the files are business secrets. But I can also reproduce this error on other files.

https://github.com/ayamir/nvimdots/assets/61657399/a3aa3589-acbc-40e9-9167-c4d8e34f1d71

```go
package main

import (
	"fmt"
	"net"
	"sync"
	"time"
)

const (
	MAX_CONN = 10
)

func main() {
	var wg sync.WaitGroup
	wg.Add(1)
	for i := 0; i < MAX_CONN; i++ {
		go Conn("127.0.0.1:8089", i)
		time.Sleep(time.Millisecond * 100)
	}
	wg.Wait()
}

func Conn(addr string, id int) {
	conn, err := net.Dial("tcp", addr)
	if err != nil {
		fmt.Println(err)
		return
	}
	fmt.Println("connect ", id)
	go func() {
		buf := make([]byte, 1024)
		for {
			n, err := conn.Read(buf)
			if err != nil {
				break
			}
			fmt.Println(id, "read: ", string(buf[:n]))
		}
	}()
	time.Sleep(time.Second * 1)
	for {
		_, err := conn.Write([]byte("hello"))
		if err != nil {
			break
		}
		time.Sleep(time.Second * 10)
	}
}
```

**Comment by Jint-lzxy** [comment]
At first glance it _seems like_ there's something odd happening with `lspsaga` (not `cmp` iiuc)... I'm not entirely sure about it, but it could be a good starting point tho.

**Comment by ayamir** [comment]
This issue can be stably reproduced for the above file. Currently my workaround is disable ghost_text completely.

**Comment by ayamir** [comment]
Maybe we can use https://github.com/smjonas/inc-rename.nvim to do rename, I prefer this style.

**Comment by Jint-lzxy** [comment]
> This issue can be stably reproduced for the above file. The only method to eliminate the errors is quitting `nvim` completely. Currently my workaround is just disable ghost_text.

@ayamir I think I saw the `cmp` popup being visible in the Rename window, right? If this is true then this issue should be expected if u didn't use `<C-w>` to abort `cmp`. Shall we disable `cmp` in the Rename window, or report it upstream?

**Comment by Jint-lzxy** [comment]
I think this issue is resolved with the changes made in [this commit](https://github.com/hrsh7th/nvim-cmp/commit/82bd4b59432d44cf5e2a5ce3a40a037a575a6623).
