### ISSUE TITLE
how to disable update for a specific plugin

### ISSUE THREAD

**Issue by nicktf-developer** [ayamir/nvimdots#1308]
### Version confirmation

- [X] Confirm

### Following prerequisites

- [X] Confirm

### Not a user config issue

- [X] Confirm

### Neovim version

NVIM v0.10.0

### Operating system/version

arm64 armbian

### Terminal name/version

xterm 3.44

### Branch info

0.10 (Nightly)

### Fetch Preferences

SSH (use_ssh = true)

### How to reproduce the issue

i use arm64 to run nvim0.10.0 and nvimdots, good experience, thk to dev, but sniprun default edition is x86, it can't run in arm64 linux, so i compiled it and run ok，i hope use <leader>pr never update this plugin, only manual compiled update, what should i do,any idea ?

### Expected behavior

if i use <leader>pr , sniprun don't update

**Comment by ayamir** [comment]
add `pin = true` for `sniprun`: https://lazy.folke.io/spec#spec-versioning

**Comment by nicktf-developer** [comment]
> add `pin = true` for `sniprun`: https://lazy.folke.io/spec#spec-versioning

thk. it works
