### ISSUE TITLE
In neovim, when you press Space + ld to view error messages, you may see the message E492: Not an editor command: TroubleToggle document_diagnostics.

### ISSUE THREAD

**Issue by Aphelios2022** [ayamir/nvimdots#1320]
### Version confirmation

- [X] Confirm

### Following prerequisites

- [X] Confirm

### Not a user config issue

- [X] Confirm

### Neovim version

NVIM 0.9.6

### Operating system/version

WSL：Ubuntu 22.04.3

### Terminal name/version

powershell 7-preview

### Branch info

0.9 (Legacy)

### Fetch Preferences

SSH (use_ssh = true)

### How to reproduce the issue

When I have a syntax error in my .c file, I press Space+ld to view the error message, but the command line prompts E492: Not an editor command: TroubleToggle document_diagnostics.
![Snipaste_2024-07-06_16-33-55](https://github.com/ayamir/nvimdots/assets/96914214/4b7ea283-94e0-4900-8b48-2e816e336a49)

### Expected behavior

I hope the window of error diagnosis information can pop up normally.

**Comment by Jint-lzxy** [comment]
If u r using Neovim 0.9, only the plugins with versions specified in the [lockfile](https://github.com/ayamir/nvimdots/blob/0.9/lazy-lock.json) will work. u could either upgrade to Neovim 0.10 or use `git switch --no-create 0.9` and then `:Lazy restore` (in Neovim) to restore the plugins to versions compatible with Neovim 0.9.
