### ISSUE TITLE
omg, install vint via mason not working

### ISSUE THREAD

**Issue by jwangtobeno1** [ayamir/nvimdots#1322]
### Version confirmation

- [X] Confirm

### Following prerequisites

- [X] Confirm

### Neovim version

nvim v0.10.0

### Branch info

main (Default/Latest)

### Minimal (user) folder structure required to reproduce the issue

```lua
`~/.config/nvim/lua/user/setting.lua`


-- Please check `lua/core/settings.lua` to view the full list of configurable settings
local settings = {}

settings["use_ssh"] = false

settings["colorscheme"] = "catppuccin"

settings["lsp_deps"] = function(defaults)
	return {
		defaults[5],
		defaults[6],
		"verible",
	}
end

settings["null_ls_deps"] = function(defaults)
	return {
		defaults[5],
		defaults[6],
		defaults[7],
	}
end

settings["dap_deps"] = function(defaults)
	return {
		defaults[1],
		defaults[3],
	}
end

settings["treesitter_deps"] = function(defaults)
	return {
		defaults[1],
		defaults[2],
		defaults[3],
		defaults[9],
		defaults[10],
		defaults[12],
		defaults[13],
		defaults[14],
		defaults[15],
		defaults[16],
		defaults[17],
		defaults[19],
	}
end

return settings
```

### Minimal config with steps on how to reproduce the issue

When I open vimscript the message shown below is displayed:

<img width="946" alt="vint-error" src="https://github.com/ayamir/nvimdots/assets/69038155/ebed01b8-3099-4936-92a5-b1f990eccc92">

I try `paru -S python-setuptools`, but the problem also exist.

### Expected behavior

Don't show the error.

### Additional information

The OS is ArchWSL

**Comment by CharlesChiuGit** [comment]
report to mason

**Comment by CharlesChiuGit** [comment]
i can try install the missing package in mason's venv.
no need to install globally

**Comment by jwangtobeno1** [comment]
I try `:MasonInstall Vint`, the problem also exist.

**Comment by jwangtobeno1** [comment]
emmm....pls tell me how to do it specifically, thank u very much.

**Comment by jwangtobeno1** [comment]
> u can try install the missing package in mason's venv. no need to install globally


emmm....pls tell me how to do it specifically, thank u very much.

**Comment by CharlesChiuGit** [comment]
```sh
cd ~/.local/share/nvim/mason/packages/vint
source venv/bin/activate
pip install --upgrade setuptools
```

**Comment by jwangtobeno1** [comment]
> ```shell
> cd ~/.local/share/nvim/mason/packages/vint
> source venv/bin/activate
> pip install --upgrade setuptools
> ```

the problem was solved perfectly,  thank u!
