### ISSUE TITLE
斜体字显示问题

### ISSUE THREAD

**Issue by JerryAllison** [ayamir/nvimdots#133]
很奇怪，我在windows11下有xshell接入服务器使用nvim时就有这中情况，斜体字像是被切了一样（字体放大/缩小/更换其他字体都有这样的情况，除非consolas字体没问题），但是Mac没有问题。
如果不好解决，是否取消斜体？
![image](https://user-images.githubusercontent.com/5206758/169429549-f69666ac-85c0-49ce-9118-9af9a09589ea.png)

**Comment by ayamir** [comment]
如果你不需要斜体字可以自己移除`lua/ui/config.lua`里面`catppuccin`主题的`italic`相关设定

**Comment by ayamir** [comment]
这个应该是特定终端的问题，比如windows terminal，但是其他终端并不会出现这种问题
