### ISSUE TITLE
[NOOB]nvim-ts-autotag not working

### ISSUE THREAD

**Issue by DrLatency** [ayamir/nvimdots#134]
**Describe the bug**
`packer.nvim: Error running config for nvim-ts-autotag: [string "..."]:0: loop or previous error loading module 'nvim-ts-autotag'`

**To Reproduce**
1. Follow wiki on OSX
2. `nvim temp.html`
3. See error

**Expected behavior**
No errors

**Environment:**
 - OS: macOS
NVIM v0.7.0
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by brew@Monterey

**Additional context**
I've seen this [discussion](https://github.com/windwp/nvim-ts-autotag/issues/33), but have absolutely no idea how to apply it here...

**Comment by ayamir** [comment]
I can't reproduce this issue on my machine. You can modify config here:
https://github.com/ayamir/nvimdots/blob/main/lua/modules/editor/plugins.lua#L55-L59
to:
```lua
editor["windwp/nvim-ts-autotag"] = {
	opt = true,
	after = "nvim-treesitter",
	config = conf.autotag,
}
```

**Comment by DrLatency** [comment]
Thank you so much! Tag completion is working correctly now.
