### ISSUE TITLE
你好 请问 neovide 为啥不能记住窗口大小呢

### ISSUE THREAD

**Issue by Jinl-k** [ayamir/nvimdots#135]
<img width="606" alt="image" src="https://user-images.githubusercontent.com/39037760/169632984-38790a18-6e7e-4280-9526-d60533264c5c.png">

我已经添加了这一项但还是不行 每次重新打开， neovide的窗口大小都会恢复成默认的

**Comment by ayamir** [comment]
我这边测试是可以的，你用的什么桌面环境

**Comment by Jinl-k** [comment]
> 我这边测试是可以的，你用的什么桌面环境

我用的是Macbook air m1 Macos 12.5 beta版， 有可能是我版本 bug

**Comment by Jinl-k** [comment]
> 我这边测试是可以的，你用的什么桌面环境

现在解决啦  通过源码构建的应用
