### ISSUE TITLE
How to close the markdown preview?

### ISSUE THREAD

**Issue by shaojunjie0912** [ayamir/nvimdots#1353]
Hi, can I ask how to close the markdown preview like below?(Please note that it is not the problem of the plugin `markdown-preview` because I have closed it but the problem is still there.)

![image](https://github.com/user-attachments/assets/94d765b7-2554-4308-a0d6-f49dfcc33774)

**Comment by CharlesChiuGit** [comment]
https://github.com/MeanderingProgrammer/render-markdown.nvim#commands

**Comment by Jint-lzxy** [comment]
Just a side note: u can also toggle this plugin by pressing [`<F1>`](https://github.com/ayamir/nvimdots/blob/a22c2d5b66d3523788383490ac18427387c021ec/lua/keymap/lang.lua#L8-L12).
