### ISSUE TITLE
`transparent_background` option not works

### ISSUE THREAD

**Issue by Surinrasu** [ayamir/nvimdots#1354]
### Version confirmation

- [X] Confirm

### Following prerequisites

- [X] Confirm

### Not a user config issue

- [X] Confirm

### Neovim version

NVIM v0.10.1

### Operating system/version

macOS 14.5 (23F79)

### Terminal name/version

Terminal.app

### $TERM environment variable

screen-256color

### Branch info

main (Default/Latest)

### Fetch Preferences

SSH (use_ssh = true)

### How to reproduce the issue

1. Install with script
2. Run `nvim` and wait Lazy to finish all installation
3. Exit with `:q` and run `nvim` again

### Expected behavior

The background is not transparent (as the option is set to false in default)

### Actual behavior

![](https://github.com/user-attachments/assets/b0d64f8d-cfe8-42ec-8b6d-4607faf07a51)

**Comment by CharlesChiuGit** [comment]
so just set it to `true`

**Comment by CharlesChiuGit** [comment]
i think it's relate to your terminal seetting.
try another terminal?

**Comment by CharlesChiuGit** [comment]
nice, glad u solved it.
