### ISSUE TITLE
更改leader键后which-key无法触发

### ISSUE THREAD

**Issue by Hza2002** [ayamir/nvimdots#136]
**Describe the bug**
更改 leader 键后 which-key 无法弹出提示
由 leader 键触发的快捷键能正常运行
尝试了 leader键改为 " ", "\\", "B"，出现一样的问题

**To Reproduce**
仅更改 lua/core/init.lua 中的 vim.g.mapleader  = " "

**Environment:**
 - OS: 在两台电脑上 macOS M1pro / Manjaro 都尝试了
 - Nvim v0.7.0
 - 按照 wiki 上正常成功配置，尚未做其他配置

**Comment by ayamir** [comment]
https://github.com/ayamir/nvimdots/blob/5921fab7ca97be107dfcdc00f048724f8e3be310/lua/modules/tools/plugins.lua#L37
`,`改成`<space>`之后`PackerCompile`
