### ISSUE TITLE
neovim start  error

### ISSUE THREAD

**Issue by magiceses** [ayamir/nvimdots#1365]
### Version confirmation

- [X] Confirm

### Following prerequisites

- [X] Confirm

### Not a user config issue

- [X] Confirm

### Neovim version

NVIM v0.10.0-dev-836+g6d93bdd45-Homebrew

### Operating system/version

macOS 12.6.1

### Terminal name/version

iTerm

### Branch info

main (Default/Latest)

### Fetch Preferences

SSH (use_ssh = true)

### How to reproduce the issue

Execute： bash -c "$(curl -fsSL https://raw.githubusercontent.com/ayamir/nvimdots/HEAD/scripts/install.sh)"

Then start neovim： nvim

Then errors：
```
Error detected while processing /Users/stk/.config/nvim/init.lua:
E5113: Error while calling lua chunk: /Users/stk/.config/nvim/lua/core/options.lua:124: E474: Invalid argument
stack traceback:
        [C]: in function 'nvim_set_option_value'
        /Users/stk/.config/nvim/lua/core/options.lua:124: in function 'load_options'
        /Users/stk/.config/nvim/lua/core/options.lua:131: in main chunk
        [C]: in function 'require'
        /Users/stk/.config/nvim/lua/core/init.lua:106: in function 'load_core'
        /Users/stk/.config/nvim/lua/core/init.lua:115: in main chunk
        [C]: in function 'require'
        /Users/stk/.config/nvim/init.lua:2: in main chunk
```

### Expected behavior

Normal

**Comment by ayamir** [comment]
Try neovim latest stable version for `main` branch.
