### ISSUE TITLE
:sparkles: Automatically compile files before debugging (C++)

### ISSUE THREAD

**Issue by CodingOIer** [ayamir/nvimdots#1367]
### Feature description

Automatically compile files before debugging, which can save a lot of time

**Comment by ayamir** [comment]
Our debug functionality is impl by [nvim-dap](https://github.com/mfussenegger/nvim-dap) and when you press `<F6>` is invoke `require("dap").continue()` in fact so it will introduce unnecessary complexity for us if we want to impl it.

**Comment by CodingOIer** [comment]
thx
