### ISSUE TITLE
markdown换行

### ISSUE THREAD

**Issue by Deg2v** [ayamir/nvimdots#137]
markdown一行大概超过80字后会换行，怎么取消这个设置，在配置里没有找到相关设置，是某个插件默认的吗？

**Comment by ayamir** [comment]
https://github.com/ayamir/nvimdots/blob/d74a2ecefcdd2849e44c050fe24aa790284117dc/lua/core/event.lua#L80

**Comment by Deg2v** [comment]
`wrap`应该是显示的时候换行吧，我上面描述的缺了一点，写md文件时，超过80个字会换行，即会加入换行符。我搜了下应该和`textwidth=80`这个有关，但是只有在md文件中生效，在sh和python文件中打字不会换行。我把下面这行注释掉就可以了，请问`bw_local`是什么意思，为什么只在md中生效？https://github.com/ayamir/nvimdots/blob/d74a2ecefcdd2849e44c050fe24aa790284117dc/lua/core/options.lua#L102

**Comment by ayamir** [comment]
`bw_local`这个应该是历史遗留问题，里面的内容可以全部等价地移动到`global_local`中
至于为什么只在`markdown`中生效我也没有头绪2333

**Comment by Deg2v** [comment]
这样啊，谢谢。
