### ISSUE TITLE
Custom configure core/init.lua

### ISSUE THREAD

**Issue by Endvour** [ayamir/nvimdots#1372]
### Feature description

Hi, could you add a way to customize the contents of core/init.lua? 

The `gui_config()` inside it overrides the font configurations in neovide's `config.toml`.

**Comment by Endvour** [comment]
This will cause an error because `gui_config()` is called without any arguments.

**Comment by ayamir** [comment]
> This will cause an error because `gui_config()` is called without any arguments.
> 
> Perhaps a condition to check if the table is empty could be added to `gui_config()`, like:
> 
> ```lua
> local gui_config = function()
>     if next(settings.gui_config) then
>         vim.api.nvim_set_option_value(
>             "guifont",
>             settings.gui_config.font_name .. ":h" .. settings.gui_config.font_size,
>             {}
>         )
>     end
> end
> ```

U'r right. This code snippet can be a PR.
