### ISSUE TITLE
怎么添加插件？

### ISSUE THREAD

**Issue by xuiv** [ayamir/nvimdots#138]
我需要 'yianwillis/vimcdoc' 和 'yuweijun/vim-wb'，但是添加之后没反应，第一个是中文的手册，第二个是五笔输入法。

**Comment by ayamir** [comment]
wiki里面写了，如果你不知道如何设置lazy loading应该设置为`opt = false`

**Comment by xuiv** [comment]
搞定：
`editor["yianwillis/vimcdoc"] = {
	opt = false,
	config = function()
		vim.cmd([[
			set helplang=cn
		]])
	end,
}
editor["yuweijun/vim-wb"] = {
	opt = false,
	config = function()
		vim.cmd([[
			set imsearch=0
		]])
	end,
}`
