### ISSUE TITLE
neovide中字体渲染异常

### ISSUE THREAD

**Issue by 505007945** [ayamir/nvimdots#140]
**描述Bug**
在终端中可以正常显示，但是在neovide中字体显示异常，请问是需要一些额外的配置吗？还是neovide自身的问题？

**截图**
neovide中的截图
<img width="456" alt="image" src="https://user-images.githubusercontent.com/58020450/170862875-b651495d-7b5c-4bff-b471-796d7040b0a3.png">

neovim中的截图
<img width="451" alt="image" src="https://user-images.githubusercontent.com/58020450/170862905-17c5d19c-d2a3-4407-ae34-834c71861085.png">

**运行环境**
- 操作系统：macOS Monterey 12.4
- `nvim`版本：v0.7.0
- `nvim`安装方式： homebrew

**Comment by ayamir** [comment]
https://github.com/ayamir/nvimdots/blob/c60a965828daeeef8c4319999df439cbd258914a/lua/core/init.lua#L56
换成你要用的字体重启即可

**Comment by 505007945** [comment]
> https://github.com/ayamir/nvimdots/blob/c60a965828daeeef8c4319999df439cbd258914a/lua/core/init.lua#L56
> 
> 
> 换成你要用的字体重启即可

多谢，现在正常了
