### ISSUE TITLE
Mac M1 下，使用默认主题catppuccin 背景颜色不符合预期，其它主题则OK

### ISSUE THREAD

**Issue by Smallhi** [ayamir/nvimdots#142]
![image](https://user-images.githubusercontent.com/13210751/171357899-7f9e75bf-8775-4109-8416-26869fe59fe1.png)

**Comment by ayamir** [comment]
终端是啥？另外你的终端字体需要设置为nerd font

**Comment by Smallhi** [comment]
mac 自带的 terminal + zsh 哈

**Comment by ayamir** [comment]
换个终端试试？比如iTerm2或者kitty

**Comment by TonyWu20** [comment]
> mac 自带的 terminal + zsh 哈

自带terminal不支持真彩色
