### ISSUE TITLE
Question on dependency tree

### ISSUE THREAD

**Issue by 2403772980ygy** [ayamir/nvimdots#146]
I'd like to know why this piece of code appears in ~/.config/nvim/lua/modules/completion/plugins.lua:
(Line 42 or so)
```
		{ "hrsh7th/cmp-nvim-lsp", after = "LuaSnip" },
```
Is there a reason to set LuaSnip as a dependency? Does this affect me changing my completion engine(e.g. If I'm going to use ultisnips instead)?

**Comment by ayamir** [comment]
This setting makes lazy loading sequential. Just use `ultisnips` to replaces it.
Modify this area to `ultisnips`
https://github.com/ayamir/nvimdots/blob/main/lua/modules/completion/plugins.lua#L41

https://github.com/ayamir/nvimdots/blob/main/lua/modules/completion/plugins.lua#L57-L61

**Comment by 2403772980ygy** [comment]
Thanks, that works fine!
