### ISSUE TITLE
无法正常加载tabnine插件

### ISSUE THREAD

**Issue by yi-ge** [ayamir/nvimdots#147]
Hello, 老哥，请问之前你配置的neovim的tabnine为何注释了，被注释的部分能正常运行吗？是何原因注释呢？

我尝试安装cmp-tabnine，启动后提示`module 'cmp_tabnine.compare' not found`。

查看PackerStatus，提示`cmp-tabnine (not loaded)`。

推测`require('cmp_tabnine').setup()`没有被正常执行。请教老哥这个如何正常安装，谢谢！

**Comment by ayamir** [comment]
最新提交里面的注释已经帮你配置好了，取消注释之后`PackerSync`就行了

**Comment by yi-ge** [comment]
原来如此，感谢老哥！！
