### ISSUE TITLE
No C complier found!

### ISSUE THREAD

**Issue by Athrun-Judah** [ayamir/nvimdots#148]
1. 在终端直接输入nvim，
2. 然后运行:TSInstall 安装任何东西都会报错No C complier found! "cc", "gcc", "clang", "cl" , "zig" are not executable.

-操作系统：Windows11 wsl2 Ubuntu22.04tls
-‘nvim’版本：0.7.0
-‘nvim’安装方式：git clone neovim 0.7.0版本解压安装

另：我想安装前端的环境，比如react，但是语法不会提示react的一些函数方法，在jsx/tsx里html标签也不会提示和补全，这个该如何配置？

**Comment by ayamir** [comment]
这个问题应该是你没装`gcc`,`g++`,`make`,`cmake`这些编译工具导致的，你搜一下Ubuntu上面怎么装吧
`react`这个你要装对应的`Lsp`才能

**Comment by Athrun-Judah** [comment]
> 这个问题应该是你没装`gcc`,`g++`,`make`,`cmake`这些编译工具导致的，你搜一下Ubuntu上面怎么装吧 `react`这个你要装对应的`Lsp`才能

那我不用c这些编译工具是否可以不安装，还是说这些编译工具也是必须的？如果不安装的话在哪将这些配置取消掉？

**Comment by ayamir** [comment]
这是必要的，因为`Treesitter`的语法解析器需要这些编译工具才能正常运行

**Comment by Athrun-Judah** [comment]
好的，非常感谢解答
