### ISSUE TITLE
图标符号异常

### ISSUE THREAD

**Issue by CyshallChan** [ayamir/nvimdots#151]
<img width="211" alt="CleanShot 2022-06-29 at 22 00 46@2x" src="https://user-images.githubusercontent.com/22564041/176455845-cc66fd5b-c283-40e5-b886-e5ecc8a84956.png">
直接看图吧。
系统Mac os 12.4，用的自带终端

**Comment by ayamir** [comment]
终端字体要设置成nerd font
https://github.com/epk/SF-Mono-Nerd-Font

**Comment by LYK-love** [comment]
> 终端字体要设置成nerd font https://github.com/epk/SF-Mono-Nerd-Font

I set font to SF-Mono, some icons still present bad. 
<img width="729" alt="image-20230625212217416" src="https://github.com/ayamir/nvimdots/assets/74082944/f4169aa9-7966-4b4f-8145-28b7d4cb1eb4">

Font: [SF-Mono-Nerd-Font](https://github.com/epk/SF-Mono-Nerd-Font) v18.0d1e1.0
I've also tested with Jetbrains Mono and Fira Code,  they're worse:

Jetbrains Mono(v2.304):
<img width="1081" alt="image" src="https://github.com/ayamir/nvimdots/assets/74082944/312593ff-2568-413d-93d1-3c1263309941">

Fira Code(V6.2)
<img width="1074" alt="image" src="https://github.com/ayamir/nvimdots/assets/74082944/50b2e621-3399-4bcc-9b84-0eee7b03ddb9">

Can you explain what font should we use?

**Comment by ayamir** [comment]
> > 终端字体要设置成nerd font https://github.com/epk/SF-Mono-Nerd-Font
> 
> I set font to SF-Mono, some icons still present bad. <img alt="image-20230625212217416" width="729" src="https://user-images.githubusercontent.com/74082944/248558785-f4169aa9-7966-4b4f-8145-28b7d4cb1eb4.png">
> 
> Font: [SF-Mono-Nerd-Font](https://github.com/epk/SF-Mono-Nerd-Font) v18.0d1e1.0 I've also tested with Jetbrains Mono and Fira Code, they're worse:
> 
> Jetbrains Mono(v2.304): <img alt="image" width="1081" src="https://user-images.githubusercontent.com/74082944/248558852-312593ff-2568-413d-93d1-3c1263309941.png">
> 
> Fira Code(V6.2) <img alt="image" width="1074" src="https://user-images.githubusercontent.com/74082944/248558878-50b2e621-3399-4bcc-9b84-0eee7b03ddb9.png">
> 
> Can you explain what font should we use?

https://github.com/ayamir/nvimdots/releases/tag/v3.0.0

**Comment by LYK-love** [comment]
OK I know it:
The Nerd Font is just an extension version of original font. So "Fira Code Nerd Font" is the "Nerd Font" extension of "Fira Code". They're differend. And in order to support these small icons in terminal. We need to use the "Nerd Font" version, not the original version.
In my case, i should use "Jetbrains Mono Nerd Font', not "Jetbrains Mono"

**Comment by kang8** [comment]
> i should use "Jetbrains Mono Nerd Font', not "Jetbrains Mono"

And, you should upgrade nerd font to [v3.0.0](https://github.com/ryanoasis/nerd-fonts/releases/tag/v3.0.0) as ayamir side, to make sure the icons can be rendered properly.
