### ISSUE TITLE
permission error

### ISSUE THREAD

**Issue by mptm436** [ayamir/nvimdots#153]
https://github.com/ayamir/nvimdots/blob/f70628b7e9d0a2912aa56a28e2d8cc9a5f36c898/lua/core/pack.lua#L76

encountered permission error, I've changed it to https access

**Comment by OnlyblackTea** [comment]
The author uses ssh to accelerate download speed in mainland, China. So It's not supposed to change it.

**Comment by flaviusbuffon** [comment]
Just configure the ssh key. `git clone` via ssh is recommend.

**Comment by ayamir** [comment]
I use `ssh` by default. You can change it to `https` of course.
