### ISSUE TITLE
Error when open vim wite insert model

### ISSUE THREAD

**Issue by 2870743367** [ayamir/nvimdots#155]
**Additional context**

**Note: Any issue without any information will be closed directly, Please value our time.**

**描述Bug**

尽可能清晰简单地描述出Bug

**如何复现**

1. 以何种方式打开文件（`Telescope`或直接打开）vim
2. 执行什么命令？i

**期待的表现**

尽可能清晰简单地描述你想要的效果
error info with images
**截图**
![image](https://user-images.githubusercontent.com/48408747/178274389-d0d47561-c696-4193-bca0-db69573f3b09.png)

如果有截图的话，尽量给出截图

**运行环境**
ubuntu22
- 操作系统：
- `nvim`版本：0.6.1
- `nvim`安装方式：apt

**额外信息**

如果有额外信息，请在这里添加

**注意：没有任何信息的issue将会被直接关闭，请不要浪费双方的时间。**

**Comment by ayamir** [comment]
所以用0.7以上的版本会怎样呢

**Comment by jczhang02** [comment]
Maybe issues like this should be closed
