### ISSUE TITLE
一个再“i”模式下输入的隐藏问题（也或许不是问题）

### ISSUE THREAD

**Issue by JerryAllison** [ayamir/nvimdots#156]
一个隐藏的问题：
再nvim下在“i” 模式下，用shift+F输入大写字母后，后面用退格键删除前一个字符，会跳到上一行，经常搞得乱七八糟的，不知道是怎么回事。需要再按一次shift才能恢复正常。
以前没有出现过这种情况，最近几个版本才发现。

环境：
Windows11
xshell7
server：Ubuntu12.04

**Comment by ayamir** [comment]
nvim什么版本？
用[tabby terminal](https://tabby.sh/)换掉xshell试试？

**Comment by JerryAllison** [comment]
好了半个小时了，好像没有问题了。谢谢。
