### ISSUE TITLE
vim新手。请教一下修改主题后不生效的问题

### ISSUE THREAD

**Issue by songan** [ayamir/nvimdots#157]
选择edge主题
![image](https://user-images.githubusercontent.com/37580851/178917463-2c90ba8e-ca69-410b-ab0f-5cfd0a97fb57.png)

执行 packerCompile
![image](https://user-images.githubusercontent.com/37580851/178917617-c4d33ba3-367e-41ea-a479-bfe4fba4c5fa.png)

重启vim。设置的主题没了
![image](https://user-images.githubusercontent.com/37580851/178917846-00572f12-76f9-4c0d-8d92-bdc890d1622e.png)

**Comment by ayamir** [comment]
修改这一行之后重新打开neovim即可
https://github.com/ayamir/nvimdots/blob/d03de15cc1c3931a8a6622ea62e14e69c90a13a5/lua/core/init.lua#L111
