### ISSUE TITLE
Update catppuccin to V0.2 (latest)?

### ISSUE THREAD

**Issue by Jint-lzxy** [ayamir/nvimdots#159]
## Describe the issue
Hi! First off - I love this set of configs, thanks for the great efforts 👍

Noticed that at commit https://github.com/ayamir/nvimdots/commit/2e72ca751cc567f9bb42f4b1541c42e1247298c3, you rolled back to previous version of catppuccin (I prefer original palette too（), but recently catppuccin has been updated very frequently, many bugs have been gradually fixed, and the project structure and configuration methods have both become clearer... So do you consider updating to the newest version (v2) and then manually set the color of the palette as well as the highlight of the corresponding integration? In this way, we can not only enjoy the functions and fixes brought by the latest version & commits, but also continue to use the previous color palettes. I'm currently working on it, and there should be a draft PR very soon~

_(There are many changes taking place. For specific implementation, please see the code detail below (although it hasn't been completed yet)_

**< Another issue is that bufferline's total number of LSP prompts _(errors, warnings, infos)_ on status bar is no longer in the default config in the new version. This can be fixed by adding the following lines in the setup table. If it is meant to be displayed, I can post a pr ~>**

```lua
diagnostics_indicator = function(count, level, diagnostics_dict, context)
	return "(" .. count .. ")"
end,
```
*****

## 描述问题

Hiii作者大大，首先非常感谢您的neovim配置！很好用👍

您在 https://github.com/ayamir/nvimdots/commit/2e72ca751cc567f9bb42f4b1541c42e1247298c3 的时候回滚到了catppuccin之前的版本（不过确实我也更喜欢之前的配色w），但最近catppuccin更新的特别频繁，许多bug都已被逐步修复，项目结构与配置方法也更加清晰了。。。所以您考不考虑更新到v2然后再自行设置调色板的颜色和对应集成的高亮？这样可以既享受最新版带来的功能和修复，也能继续用之前的配色（，我这边在一点点做，应该会在最近提一个draft pr~

_（不过要改的确实多，具体实现可以看看下面的正在施工的部分233（尽管还没弄好）_

**< 还有一个是bufferline.nvim状态栏上的lsp提示总数（错误、警告、提示）在新版不再是默认内容，可以通过在setup里添加下面这几行解决，如果确实是希望显示的话我可以提一个pr～ >**

```lua
diagnostics_indicator = function(count, level, diagnostics_dict, context)
	return "(" .. count .. ")"
end,
```

### Semifinished Product's Screenshot / 半成品截图

![截屏2022-07-17 20 59 49](https://user-images.githubusercontent.com/50296129/179399553-b79fa250-d72e-4b5c-8e46-9ff15970d7f7.png)

### Implementation Detail / 实现细节（半成品）

<details>
    <summary>Palette configs / 配色调整</summary>
<p>

```lua
color_overrides = {
	mocha = {
		rosewater = "#F5E0DC",
		flamingo = "#F2CDCD",
		mauve = "#DDB6F2",
		pink = "#F5C2E7",
		red = "#F28FAD",
		maroon = "#E8A2AF",
		peach = "#F8BD96",
		yellow = "#FAE3B0",
		green = "#ABE9B3",
		blue = "#96CDFB",
		sky = "#89DCEB",
		teal = "#B5E8E0",
		lavender = "#C9CBFF",
	},
},
```

<br />
</details>

<details>
    <summary>Plugin integrations hl configs / 插件集成配色调整</summary>
<p>

```lua
custom_highlights = {
	Comment = { fg = cp.overlay1 },
	LineNr = { fg = cp.overlay1 },
	CursorLine = { bg = cp.none },
	CursorLineNr = { fg = cp.lavender },
	DiagnosticVirtualTextError = { bg = cp.none },
	DiagnosticVirtualTextWarn = { bg = cp.none },
	DiagnosticVirtualTextInfo = { bg = cp.none },
	DiagnosticVirtualTextHint = { bg = cp.none },

	TSField = { fg = cp.rosewater },
	TSProperty = { fg = cp.yellow },

	TSInclude = { fg = cp.teal },
	TSOperator = { fg = cp.sky },
	TSKeywordOperator = { fg = cp.mauve },
	TSPunctSpecial = { fg = cp.maroon },

	TSConstructor = { fg = cp.lavender },
	TSException = { fg = cp.peach },

	TSConstBuiltin = { fg = cp.lavender },
	TSVariableBuiltin = { fg = cp.red, style = { "italic" } },

	TSFuncMacro = { fg = cp.red, style = {} },
	TSParameter = { fg = cp.rosewater },
	TSKeywordFunction = { fg = cp.maroon },
	TSKeywordReturn = { fg = cp.pink, style = {} },

	TSMethod = { style = { "italic" } },
	TSNamespace = { fg = cp.rosewater },

	TSPunctDelimiter = { fg = cp.teal },
	TSPunctBracket = { fg = cp.overlay2 },

	TSType = { fg = cp.yellow },
	TSVariable = { fg = cp.white },
	TSTagAttribute = { fg = cp.mauve },
	TSTag = { fg = cp.peach },
	TSTagDelimiter = { fg = cp.maroon },
	TSText = { fg = cp.text },

	bashTSFuncBuiltin = { fg = cp.red, style = { "italic" } },
	bashTSParameter = { fg = cp.yellow, style = { "italic" } },

	luaTSField = { fg = cp.lavender },
	luaTSConstructor = { fg = cp.flamingo },

	javaTSConstant = { fg = cp.teal },

	typescriptTSProperty = { fg = cp.lavender, style = { "italic" } },

	cssTSType = { fg = cp.lavender },
	cssTSProperty = { fg = cp.yellow, style = { "italic" } },

	cppTSProperty = { fg = cp.white },
},
```

<br />
</details>

**Comment by ayamir** [comment]
哇 辛苦了 我最近一直在忙实验室的工作
配色我确实是喜欢之前那个版本，如果这样做能恢复之前的配色最好 辛苦你了
之后我会review并merge

**Comment by OnlyblackTea** [comment]
期待能看到您的pr,我最近在kitty上遇到了一个特别令人心动的主题，也想照葫芦画瓢试试看

**Comment by Jint-lzxy** [comment]
@OnlyblackTea 您可以先康康刚刚提的 draft PR(#163) 的描述和实现:) 我会尽快做完的（
