### ISSUE TITLE
What's tree-mode (shortcut "n") ?

### ISSUE THREAD

**Issue by OnlyblackTea** [ayamir/nvimdots#162]
I'm still in the process of getting familiar with this configuration.

Here I found a shortcut.

> stage hunk | \<leader\>hs ( n and v mode )

I don't know what it is, but I'm just curious about n mode, so I had a try.

After I press "n", It shows:

`E486: 找不到模式: tree`

And also I didn't find the definition of this keybinding in [wiki](https://github.com/ayamir/nvimdots/wiki/Keybindings)

So what is tree-mode? Is this a bug?

**Comment by ayamir** [comment]
`n` and `v` are abbreviations of `normal` and `visual`.
It means that `<leader>hs` will works in these two modes.

**Comment by OnlyblackTea** [comment]
> `n` and `v` are abbreviations of `normal` and `visual`. It means that `<leader>hs` will works in these two modes.

How about the E486? Is that because of I didn't use stage hunk first?

**Comment by ayamir** [comment]
when you pressed `n` in normal mode, it means that you want to search the **next** keyword in current buffer.

**Comment by OnlyblackTea** [comment]
It seems like I asked a silly question， thx😋
