### ISSUE TITLE
能否加入不配置ssh key方式安装？

### ISSUE THREAD

**Issue by MoxiuHub** [ayamir/nvimdots#168]
如图，因特殊安全问题不能配置ssh key 希望改为/加入此方式～

<sub>Sent from <a href="https://apps.apple.com/cn/app/id1314212521">PPHub</a></sub>

**Comment by ayamir** [comment]
你可以自己手动修改：
把下面这几行中的`git@github.com:`改成`https://github.com/`即可
https://github.com/ayamir/nvimdots/blob/323f1df0582d61eea1c3fe61f848f9e6035a433d/lua/core/pack.lua#L42
https://github.com/ayamir/nvimdots/blob/323f1df0582d61eea1c3fe61f848f9e6035a433d/lua/core/pack.lua#L53
https://github.com/ayamir/nvimdots/blob/323f1df0582d61eea1c3fe61f848f9e6035a433d/lua/core/pack.lua#L76

**Comment by jczhang02** [comment]
This issue can be closed.
