### ISSUE TITLE
eslist is not installed

### ISSUE THREAD

**Issue by apolionl** [ayamir/nvimdots#170]
**Describe the bug**
After switching to Maston, I get an error message saying that "eslint" is not available. 

To avoid this, it is necessary to change names "eslint" to  "eslint-lsp" at 
nvim/lua/modules/completion/config.lua 
--			"eslint",
++			"eslint-lsp",

**To Reproduce**
1. Open any file. 

**Expected behavior**
After opening any file, there should not be a error message.

**Screenshots**

**Environment (please complete the following information):**
 - OS: [ Archlinux]
 - Nvim version(output of `nvim --version`)
 NVIM v0.8.0-dev-nightly

**Comment by LuSany** [comment]
更新到最新的commit，还是会有报错：Cannot find package "eslint"
![image](https://user-images.githubusercontent.com/36779890/182053284-c133dd96-1999-4f09-8a9b-1923f2ec30f2.png)
![image](https://user-images.githubusercontent.com/36779890/182053378-72f48ea0-79b2-4630-b22c-e08058918bfd.png)

OS: Centos8
Nvim: v0.7.0

**Comment by ayamir** [comment]
> 更新到最新的commit，还是会有报错：Cannot find package "eslint" ![image](https://user-images.githubusercontent.com/36779890/182053284-c133dd96-1999-4f09-8a9b-1923f2ec30f2.png) ![image](https://user-images.githubusercontent.com/36779890/182053378-72f48ea0-79b2-4630-b22c-e08058918bfd.png)
> 
> OS: Centos8 Nvim: v0.7.0

你这个问题明显不合理，已经将`eslint`改成`eslint-lsp`之后不可能出现这样的错误。

另外，我已经将`eslint`从`mason`要安装的工具里面删除了，完全使用`efm`来完成js/ts的lint，你需要自己手动从系统安装`eslint`。

**Comment by LuSany** [comment]
我把所有的插件全删除了，然后重新安装了就好了，不清楚是哪个插件的影响
