### ISSUE TITLE
奇怪的bug

### ISSUE THREAD

**Issue by mjkx5** [ayamir/nvimdots#176]
我遇到了一个奇怪的问题，我按 \<c-i\> 会折叠， 最后定位到这个文件
lua/core/mapping.lua
["n|\<Tab\>"] = map_cr("normal zc"):with_noremap():with_silent() 

这句话的意思应该是 在 normal 下按 \<tab\> 折叠， 但是我这里按 \<tab\> 能 折叠，按 \<c-i\> 也能折叠
注释掉之后 按 \<tab\> 不能 折叠， 按 \<c-i\> 也不能折叠了

我的电脑是 5.18.16-arch1-1 ，桌面是kde

----------------------------------------------------
我不确定这个好不好复现
这个功能对我来说不重要， 只是好奇原因， 如果很麻烦就算啦

**Comment by ayamir** [comment]
没看懂你要说什么

**Comment by jczhang02** [comment]
他好像是在说，代码注释后无法折叠。这是作者只是将tab映射为zc，功能和zc是一样的。如果你有需求，只要做到让zc命令即可以折叠代码也可以折叠注释即可。
[可以看一下这里](https://vi.stackexchange.com/questions/3512/how-to-fold-comments)

**Comment by mjkx5** [comment]
> 没看懂你要说什么

没注意浏览器上 < 要加 \ 才能正确显示

**Comment by mjkx5** [comment]
> 他好像是在说，代码注释后无法折叠。这是作者只是将tab映射为zc，功能和zc是一样的。如果你有需求，只要做到让zc命令即可以折叠代码也可以折叠注释即可。 [可以看一下这里](https://vi.stackexchange.com/questions/3512/how-to-fold-comments)

我修改了提问，有一些内容没有正确显示

**Comment by jczhang02** [comment]
那似乎就是我说的样子

**Comment by mjkx5** [comment]
> 那似乎就是我说的样子

我的意思是 那一行同时 使 我的 \<c-i\> 键位 变成了 折叠功能，但是 这一行 不应该是 这样的

**Comment by ayamir** [comment]
虽然事实是这样，不过我用`verbose nmap <C-I>`检查了一下这个键位没有被映射到任何命令上面，很奇怪。

**Comment by jczhang02** [comment]
事实上，对于终端来说也不能分辨<C-i>和<Tab>键

**Comment by mjkx5** [comment]
Most terminals map both TAB and C-i to U+0009 (Character Tabulation) for historical reasons, meaning they’re recognised as the same keypress. 绝了，历史原因， 好像这个问题，大多数终端， vim, emacs ，都有，现在还没人去修复这个
