### ISSUE TITLE
怎么配置默认关闭代码右边这些virutal text 提示

### ISSUE THREAD

**Issue by zct** [ayamir/nvimdots#178]
![image](https://user-images.githubusercontent.com/4023051/183594322-c438d872-b4f3-4213-b8bc-65bb5393df8a.png)

**Comment by nullchilly** [comment]
`:h vim.diagnostic.config()`

**Comment by ayamir** [comment]
这是正常的lsp提示，如果你不需要可以执行`lua vim.diagnostic.config({virtual_text = false})`暂时关闭

**Comment by zct** [comment]
谢谢～
