### ISSUE TITLE
nvim_treesitter bug 

### ISSUE THREAD

**Issue by mjkx5** [ayamir/nvimdots#179]
/home/life/.config/nvim/lua/modules/editor/config.lua

 中的
	vim.api.nvim_command("set foldmethod=expr")
	vim.api.nvim_command("set foldexpr=nvim_treesitter#foldexpr()")

导致： 
terminal 中 出现死循环, 例如 yes , neovim会卡死，

感觉是 nvim_treesitter 出现的问题， 在这里做一个提醒。

**Comment by ayamir** [comment]
看不懂

**Comment by jczhang02** [comment]
你说得死循环是什么意思呢，能重新描述下你的问题吗 @mjkx5

**Comment by mjkx5** [comment]
打开nvim
:terminal
输入 yes

**Comment by mjkx5** [comment]
正常来说： 输入yes, 终端里会不断输出yes, 但是在这个配置下， vim 会直接卡死
