### ISSUE TITLE
[Question] 咨询下这个 CodeAction 提示是哪个插件提供的功能？

### ISSUE THREAD

**Issue by HATTER-LONG** [ayamir/nvimdots#184]
## 问题描述：

咨询下这个 CodeAction  提示是哪个插件提供的功能:
<img width="356" alt="image" src="https://user-images.githubusercontent.com/31438141/184471427-2e636e50-0cbf-4124-ad1c-4a09c6285247.png">

- 存在的问题：自动格式化换行后由于右侧   不会及时刷新导致覆盖代码显示：
<img width="486" alt="image" src="https://user-images.githubusercontent.com/31438141/184471489-d600bf13-4340-4f0b-a874-8a41d992ceef.png">

- 格式化后 遮挡了 `}`：
<img width="349" alt="image" src="https://user-images.githubusercontent.com/31438141/184471566-8a332ae4-58c0-4555-9af7-d0a878b56fd3.png">

## 尝试

删除了 lightbulb 插件依旧存在这个提示：

```lua 
-- completion["kosayoda/nvim-lightbulb"] = {
-- 	enable = false,
-- 	opt = true,
-- 	after = "nvim-lspconfig",
-- 	config = conf.lightbulb,
-- }
```

**Comment by ayamir** [comment]
除了lightbulb就是lspsaga
https://github.com/ayamir/nvimdots/blob/94f153471068c5145b2036be1f688c0f954cd973/lua/modules/completion/lsp.lua#L31

**Comment by ayamir** [comment]
更新完毕了，你可以看看现在有没有这个问题

**Comment by HATTER-LONG** [comment]
非常感谢，更新完问题还是存在，看了下应该是由于异步更新 icon 代码格式化在 icon 刷新前边了，我就先简单配置下关闭 右侧的提示了，这问题逼死强迫症，总要等 1s 左右才能看到右括号😓：

```lua
function config.lspsaga()
	local saga = require("lspsaga")
	saga.init_lsp_saga({
		code_action_lightbulb = {
			enable = true,
			sign = true,
			enable_in_insert = true,
			sign_priority = 20,
			virtual_text = false,  # close virtual text
		},
	})
end
```
