### ISSUE TITLE
Consider using nvim-navic and aerial.nvim?

### ISSUE THREAD

**Issue by Jint-lzxy** [ayamir/nvimdots#188]
- For [nvim-navic](https://github.com/SmiteshP/nvim-navic), it's because [nvim-gps](https://github.com/SmiteshP/nvim-gps) has been deprecated, and from the project description:
> nvim-navic is an improved version of nvim-gps (a version 2.0!). It accomplishes the same task as this plugin, but uses LSP instead of Treesitter. It also adds ability to have coloured icons!

- However, there's a frequently reported issue: `"x does not support documentSymbols" error popping up every time an editor is opened`. The standard recommendation is to not attach navic to problematic servers. While this is reasonable in some cases, there are a number of servers that navic would be useful with, like `htmlls` or `cssls`, that still use the `SymbolInformation` interface. **So shall we switch to nvim-navic once `SymbolInformation` is supported? There is a PR attempting to address this problem now. _(Another choice - which might be better - is to load both plugins and set gps as a fallback when navic is unavailable under current buffer)._**
******
- Given that the `SymbolInformation` API is still in use by a number of existing servers, the same applies to [lspsaga.nvim](https://github.com/glepnir/lspsaga.nvim) _(Specifically, the **outline** feature [[this line]](https://github.com/glepnir/lspsaga.nvim/blob/bd95871d67b8942a7869f8284c151b85f653027b/lua/lspsaga/outline.lua#L14))_. Whereas [aerial.nvim](https://github.com/stevearc/aerial.nvim) could automatically fetch symbols from Treesitter as a backend, with proper configuration it could offer the same experience as lspsaga **and** provide support for a wide range of languages at the same time _(Now some languages (and servers spawned by efm) cannot view it's symbol outline, lspsaga would throw an error)_. **Should we add aerial.nvim back again?**

**Comment by ayamir** [comment]
I will replace `nvim-gps` with `nvim-navic` later.
`aerial.nvim` has wider file type support, but its outline is not detailed enough.

**Comment by jczhang02** [comment]
@Jint-lzxy
Hi, i have a question that how to disable navic for some filetype (tex). I encounter the problem caused by navic when I am editing latex files.

**Comment by Jint-lzxy** [comment]
@jczhang02 What exactly IS the problem? _(e.g., navic was not being displayed in lualine, an error was reported, or lazy-loading problems.)_ When navic attempted but failed to attach to this buffer (or current server), it won't be displayed in lualine at all and no errors would be thrown _(unless you comment out this ↓ line)_.
https://github.com/ayamir/nvimdots/blob/3b9d470b41414089f2b3022232dd1a8d69ec1089/lua/modules/ui/config.lua#L604

Anyway, to disable the display in lualine, you may set the `cond` table to **conditionally** display this section, otherwise it will not be loaded and displayed. For example, to enable display whenever either `gps` or `navic` is available we may write:
```lua
local conditions = {
	check_code_context = function()
		return gps.is_available() or navic.is_available()
	end,
}
```
Then in setup:
```lua
-- Other configs...
{ --[[ This is the function that controls the display of this section --]], cond = conditions.check_code_context },
-- .......
```

However, if you would like to disable navic **COMPLETELY** on this ft, then you may want to prevent navic from attaching to this buffer _(of certain filetype)_, which might be a better option in your case.

Since `filetype` is a buffer-local option, so you can access it with:
```lua
vim.bo.filetype
```

_(From `:h lua-vim-options:`)_
```lua
From Lua you can work with editor |options| by reading and setting items in
these Lua tables:

vim.w
   ...

vim.bo                                                  *vim.bo*
       Get or set buffer-scoped |local-options|. Invalid key is an error.
       Example:
           vim.bo.buflisted = true
           print(vim.bo.comments)

vim.wo
   ...
```

We are also given the fact that `navic` gets attached to current buffer using our `custom_attach` function, then we could apply a conditional check to it. Here is a sneak peak, hope this is useful to you 👍
- Original Code:
https://github.com/ayamir/nvimdots/blob/3b9d470b41414089f2b3022232dd1a8d69ec1089/lua/modules/completion/lsp.lua#L37
- We may modify it like so:
```lua
local block_ft = { "lua", "plaintex" }
if not block_ft[vim.bo.filetype] then
	require("nvim-navic").attach(client, bufnr)
end
```
Then navic would not be attached to current buffer any more, like so: _(We now use gps as fallback)_
![res](https://user-images.githubusercontent.com/50296129/187718719-c0bd25c2-e928-4409-9c6f-7f1134c4f461.png)


- You may also create a usercmd for it to make life easier, like `FormatterToggle`, which is rather simple:
https://github.com/ayamir/nvimdots/blob/3b9d470b41414089f2b3022232dd1a8d69ec1089/lua/modules/completion/formatting.lua#L22-L64

> Above ref: [My config](https://github.com/Jint-lzxy/nvimconfig/blob/master/lua/modules/ui/config.lua) and https://github.com/nvim-lualine/lualine.nvim#general-component-options

I bet there must be a better way to fix it rather than "brutally" disable it on a specific ft. More description about the problem would be very helpful. 👍
