### ISSUE TITLE
[LspSaga] get root dir failed以及显示问题

### ISSUE THREAD

**Issue by fleongg** [ayamir/nvimdots#194]
你好，请问为什么对变量使用gh后出现这个报错？搜索之后没有发现解决方法。然后在使用gh后Find的小方块一直保留在屏幕，使用:q也无法消去，不知道时候和前面的报错有关，中英文搜索没有发现同样的现象。
![24751660850246_ pic](https://user-images.githubusercontent.com/88166834/185476944-36b0fa56-cead-450a-ac03-270246350041.jpg)
使用gh后报错

[LspSaga] get root dir failed
![24771660850464_ pic](https://user-images.githubusercontent.com/88166834/185476981-52089b9c-f011-4f15-8543-c611a7d59216.jpg)
显示问题

十分感谢

**Comment by fleongg** [comment]
系统是macOS Monterey Version 12.3, m1.
NVIM v0.7.2

**Comment by ayamir** [comment]
这个只是个lspsaga的info输出，因为你现在编辑文件是在single file mode下面，所以自然找不到root directory
<img width="497" alt="image" src="https://user-images.githubusercontent.com/61657399/185521652-dd7dbf2f-e358-40d3-8ff4-b4c5fb66e7a1.png">
至于你说的gh的退出正确的快捷键是`q`

**Comment by fleongg** [comment]
十分感谢！
