### ISSUE TITLE
mac 安装问题后不显示dashboard

### ISSUE THREAD

**Issue by xushuhui** [ayamir/nvimdots#197]
**描述Bug**

mac 安装问题后不显示dashboard

**如何复现**
安装neovim后
`git clone https://github.com/ayamir/nvimdots.git ~/.config/nvim/`

**期待的表现**

显示dashbord

**截图**

<img width="799" alt="image" src="https://user-images.githubusercontent.com/13704743/185585917-190ea72b-c0cb-4aa1-b8a8-e0cf3993d743.png">

**运行环境**

- 操作系统：
- `nvim`版本：（`nvim --version`的输出）
 NVIM v0.7.2
- `nvim`安装方式：（AppImage或包管理器名）
brew

**Comment by ayamir** [comment]
默认输入`nvim`会启动dashboard作为欢迎界面
你应该是编辑了某个目录即输入了`nvim ~/.config/nvim`，这样不会出现dashboard
