### ISSUE TITLE
hey have some method to change find file and search word,please 

### ISSUE THREAD

**Issue by 1096015776** [ayamir/nvimdots#20]

**Comment by 1096015776** [comment]
I find when I find file , in work dir ,when I jump to file ,I cannot find file in work dir, I know fzf can find in git ,so he can find in work dir ,but dashboard can not ,maybe I didn’t find correct method to let it comfortable ,if can, I do not want to add plug-in beacause dashboard should work
,and search words so so

**Comment by ayamir** [comment]
You just need to add keymap for [these methods](https://github.com/nvim-telescope/telescope.nvim#file-pickers) on your own.

**Comment by 1096015776** [comment]
Thanks
 I try it
