### ISSUE TITLE
lsp is installed every time it comes in

### ISSUE THREAD

**Issue by j2501987804** [ayamir/nvimdots#21]
![image](https://user-images.githubusercontent.com/41771911/131238748-2b9bbcfc-1cd3-4bd5-ae04-bb244bcde630.png)
How to make it take effect automatically

**Comment by ayamir** [comment]
Servers installed by `nvim-lspinstall` is permanent stored on your disk.
You can execute `ls ~/.local/share/nvim` to check if a directory called `lspinstall` exists.

**Comment by ayamir** [comment]
![lspinstall](https://user-images.githubusercontent.com/61657399/131239033-3c5b2539-11ad-40a8-b2df-eb89a7531169.png)

**Comment by j2501987804** [comment]
![image](https://user-images.githubusercontent.com/41771911/131239176-0a66ea8d-2875-41cf-b5bd-7971fd2a4c99.png)

**Comment by j2501987804** [comment]
![image](https://user-images.githubusercontent.com/41771911/131239231-bbd0d888-3159-40cc-bcf1-6ecef7a9092f.png)
I have already installed it, and it will not be loaded automatically. Every time I open vim, I have to execute it manually: lspinstall go

**Comment by ayamir** [comment]
execute `LspInfo` when you enter this buffer, correct result is like this:
![lspinstall](https://user-images.githubusercontent.com/61657399/131239430-13596d55-20c9-442a-973e-093cbe5bb20f.png)

**Comment by ayamir** [comment]
You may need to `git pull` to get my latest updates.

**Comment by j2501987804** [comment]
![image](https://user-images.githubusercontent.com/41771911/131239505-e446d54d-e0ba-48fa-8b04-6e74ab49aa32.png)

**Comment by ayamir** [comment]
Do you have `go.mod` in this directory?

**Comment by j2501987804** [comment]
https://github.com/ayamir/nvimdots/issues/21#issuecomment-907731549
Just pull is still not working, the directory has go.mod

**Comment by ayamir** [comment]
The correct sequence is this:
1. make the oackage dir.
2. touch `go.mod`.
2. touch `main.go`.
3. vim `main.go`.
![sequence](https://user-images.githubusercontent.com/61657399/131240145-9431083e-372c-4840-a757-e8d0da1c9095.png)

![success](https://user-images.githubusercontent.com/61657399/131240148-11f8e4cd-cded-4458-82a5-a2b97dc586eb.png)

**Comment by 1096015776** [comment]
hey , does your go work? i try it and it work ,just touch go.mod and main.go,it work.
i find if i not touch main.go,I just nvim main.go,the lsp is not work,may this is answer.
so you should touch main.go then nvim main.go

**Comment by 1096015776** [comment]
![截屏2021-08-29 下午6 57 28](https://user-images.githubusercontent.com/40203327/131247997-3edb1767-87ce-4989-9614-30e7cc30d2bc.png)
![截屏2021-08-29 下午6 57 11](https://user-images.githubusercontent.com/40203327/131248003-4971ecc6-657f-46fd-ac2b-f0cf0f7103e5.png)

**Comment by p1k0pan** [comment]
Mine is not work on go, but it work on python. I runned LspInstall python just like I runned LspInstall go, but python can work automatically and go failed.

**Comment by p1k0pan** [comment]
![DeepinScreenshot_select-area_20210830125613](https://user-images.githubusercontent.com/36180022/131287244-a1ff677c-db7d-4b41-9170-d1fd0630b5c4.png)
I assume that Lsp server has installed the gopls ,but the autocompletion not configure.
How to set it up?

**Comment by ayamir** [comment]
> Mine is not work on go, but it work on python. I runned LspInstall python just like I runned LspInstall go, but python can work automatically and go failed.

`golsp` need to detect your directory if a work directory or not. Please refer to [this](https://github.com/neovim/nvim-lspconfig/blob/master/CONFIG.md#gopls) and [this](https://www.reddit.com/r/neovim/comments/oapq4p/cant_get_gopls_to_work/).

**Comment by p1k0pan** [comment]
> > Mine is not work on go, but it work on python. I runned LspInstall python just like I runned LspInstall go, but python can work automatically and go failed.
> 
> `golsp` need to detect your directory if a work directory or not. Please refer to [this](https://github.com/neovim/nvim-lspconfig/blob/master/CONFIG.md#gopls) and [this](https://www.reddit.com/r/neovim/comments/oapq4p/cant_get_gopls_to_work/).

Thank you for your time for a newbee. It work well after adding go.mod . However I wonder why the autocompletion on go still not perform like on python, when I want to type Print, it does not show any code suggestion. Is there anything that I should set up?

**Comment by ayamir** [comment]
> > > Mine is not work on go, but it work on python. I runned LspInstall python just like I runned LspInstall go, but python can work automatically and go failed.
> > 
> > 
> > `golsp` need to detect your directory if a work directory or not. Please refer to [this](https://github.com/neovim/nvim-lspconfig/blob/master/CONFIG.md#gopls) and [this](https://www.reddit.com/r/neovim/comments/oapq4p/cant_get_gopls_to_work/).
> 
> Thank you for your time for a newbee. It work well after adding go.mod . However I wonder why the autocompletion on go still not perform like on python, when I want to type Print, it does not show any code suggestion. Is there anything that I should set up?

Did `gopls` attact to your buffer? You can check this via `lualine` quickly. If `gopls` starts correctly autocompletion is out of the box.

**Comment by p1k0pan** [comment]
![DeepinScreenshot_select-area_20210830143126](https://user-images.githubusercontent.com/36180022/131295410-43c6a2d4-b896-4c05-9514-5d50e16042af.png)
yes

**Comment by ayamir** [comment]
> ![DeepinScreenshot_select-area_20210830143126](https://user-images.githubusercontent.com/36180022/131295410-43c6a2d4-b896-4c05-9514-5d50e16042af.png)
> yes

Your `go.mod` need line like this: 
![gomod](https://user-images.githubusercontent.com/61657399/131295963-5dd65366-8c44-4b53-a4e8-8fb9c35755d5.png)
The module name is your `root_dir`'s name normally. Its `gopls`'s request.

**Comment by p1k0pan** [comment]
> > ![DeepinScreenshot_select-area_20210830143126](https://user-images.githubusercontent.com/36180022/131295410-43c6a2d4-b896-4c05-9514-5d50e16042af.png)
> > yes
> 
> Your `go.mod` need line like this:
> ![gomod](https://user-images.githubusercontent.com/61657399/131295963-5dd65366-8c44-4b53-a4e8-8fb9c35755d5.png)
> The module name is your `root_dir`'s name normally. Its `gopls`'s request.


Oh sorry I just run the go file and it said go.mod not set up , and I follow the default set up for go.mod and finally worked, just like your advise. I really appreciate your neovim set up. Thanks again!!

**Comment by JerryAllison** [comment]
没有lspinstall命令
<img width="403" alt="image" src="https://user-images.githubusercontent.com/5206758/167758657-db41a0fd-e6b6-4228-bc9d-9410b723d04c.png">
