### ISSUE TITLE
Docker image support?

### ISSUE THREAD

**Issue by weizhenhuan** [ayamir/nvimdots#213]
我想尝试建立一个docker镜像，这样方便在多台机器上迁移。但我写的dockerfile有点问题，不太能工作。

**Comment by ayamir** [comment]
docker的话是不是需要用https来下载插件？

**Comment by OnlyblackTea** [comment]
> docker的话是不是需要用https来下载插件？

也许配置文件可以挂载在docker外部？我乱想的x

To weizhenhuan:
你不妨细说一下什么是“不太能工作”。

**Comment by jczhang02** [comment]
我也有这种需求, 有些服务器由于安全要求无法联网, 便导致nvim无法配置, docker目前看来是最简单的办法能完成多机器迁移, 你可以把你的dockerfile分享出来, 大家一起修改一下!
@weizhenhuan

**Comment by ayamir** [comment]
Personally I don't use docker image during my workflow. It's hard for me to maintain it due to lack of enough time. PR is always welcome :)

**Comment by jczhang02** [comment]
> 
好像不用吧, 只要不是自己库里的就好
