### ISSUE TITLE
<C-W>+T进入终端以后保持在ToggleTerm状态

### ISSUE THREAD

**Issue by OnlyblackTea** [ayamir/nvimdots#217]
现在进入终端以后会保持在ToggleTerm状态，按ESC无法退出到命令状态。

可以用鼠标选择到其他的buffer,但是键盘上的快捷键好像不行。

可以用\<C-W\>+T关闭该buffer。

这是新Feature还是Bug？

**Comment by mjkx5** [comment]
Feature 

如果你不想要这个功能，

lua/modules/editor/config.lua

在 function config.toggleterm()
 		close_on_exit = true, -- close the terminal window when the process exits
		shell = vim.o.shell, -- change the default shell
++		terminal_mappings = false,
添加 terminal_mappings = false,

**Comment by ayamir** [comment]
> 现在进入终端以后会保持在ToggleTerm状态，按ESC无法退出到命令状态。
> 
> 可以用鼠标选择到其他的buffer,但是键盘上的快捷键好像不行。
> 
> 可以用<C-W>+T关闭该buffer。
> 
> 这是新Feature还是Bug？

现在所有类型的toggleterm都由[akinsho/toggleterm.nvim](https://github.com/akinsho/toggleterm.nvim)完成，不支持用<Esc>退出到整个vim的normal模式：https://github.com/akinsho/toggleterm.nvim/issues/294#issuecomment-1219520518

**Comment by ayamir** [comment]
至于toggle的快捷键在这里进行了定义：
https://github.com/ayamir/nvimdots/blob/main/lua/keymap/init.lua#L50-L61
