### ISSUE TITLE
gt 和 gT 的疑惑

### ISSUE THREAD

**Issue by zll600** [ayamir/nvimdots#222]
请问为什么要对 gt 重映射呀，感觉这个在标签页之间切换的快捷键挺有用的啊

**Comment by ayamir** [comment]
这个是`trouble.nvim`这个插件默认的快捷键，切换标签页我按照`bufferline.nvim`重新映射到了`<A-j>`和`<A-k>`以及Alt+数字上面来切换

**Comment by zll600** [comment]
> 

ok，谢谢解答
