### ISSUE TITLE
shfmt,editorconfig-checker老是安装不上

### ISSUE THREAD

**Issue by hhcwyx** [ayamir/nvimdots#223]
启动后，就提示:[mason-tool-installer] shfmt installing 
大概1分钟后，提示：[mason-tool-installer] shfmt：failed to install 
另：editorconfig-checker 也是同样的现象。
我的系统是archlinux，neovim版本是0.7.2 
刚接触neovim，不知道怎么解决，请大家帮忙。

**Comment by ayamir** [comment]
> 启动后，就提示:[mason-tool-installer] shfmt installing 大概1分钟后，提示：[mason-tool-installer] shfmt：failed to install 另：editorconfig-checker 也是同样的现象。 我的系统是archlinux，neovim版本是0.7.2 刚接触neovim，不知道怎么解决，请大家帮忙。

你如果有代理的话可以试试挂上终端代理之后再安装

**Comment by hhcwyx** [comment]
用代理也没成功，用：masoninstall shfmt  editorconfig-checker 也不行，下面是错误信息，请帮忙分析一下是不是我的机器还缺什么东西？
Failed
    ◍ editorconfig-checker
      go: github.com/editorconfig-checker/editorconfig-checker/cmd/editorconfig-checker@latest: module github.com/editorconfig-checker/editorconfig-checker/cmd/editorconfig-checker: Get "https://proxy.golang.org/github.com/editorconfig-checker/editorconfig-checker/cmd/editorconfig-checker/@v/list": dial tcp 108.177.97.141:443: i/o timeout
      spawn: go failed with exit code 1 and signal 0. 
      
    ◍ shfmt
      go: mvdan.cc/sh/v3/cmd/shfmt@latest: module mvdan.cc/sh/v3/cmd/shfmt: Get "https://proxy.golang.org/mvdan.cc/sh/v3/cmd/shfmt/@v/list": dial tcp 108.177.97.141:443: i/o timeout
      spawn: go failed with exit code 1 and signal 0.

**Comment by hhcwyx** [comment]
我用pacman 安装了这两个软件，能在机器上成功安装，但是neovim还是在启动的时候安装。我不懂这里面的逻辑，是不是手动安装没有啥用呀？

**Comment by OnlyblackTea** [comment]
pacman安装以后你没有在neovim里配置也是没用的。

**Comment by ayamir** [comment]
> 

`go env -w GOPROXY=https://proxy.golang.com.cn,direct`用这个代理再试试

**Comment by hhcwyx** [comment]
go env -w GOPROXY=https://proxy.golang.com.cn,direct用这个代理再试试

谢谢老师！！用这个成功了。
