### ISSUE TITLE
plug install failed

### ISSUE THREAD

**Issue by HQCND** [ayamir/nvimdots#229]
:!git clone git@github.com:wbthomason/packer.nvim.git /Users/huangqiang/.local/share/nvim/site/pack/packer/opt/packer.nvim
Cloning into '/Users/huangqiang/.local/share/nvim/site/pack/packer/opt/packer.nvim'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

shell returned 128

Error detected while processing /Users/huangqiang/.config/nvim/init.lua:
E5113: Error while calling lua chunk: /Users/huangqiang/.config/nvim/lua/core/pack.lua:36: Vim(packadd):E919: Directory not found in 'packpath': "pack/*/opt/packer.nvim"
stack traceback:
        [C]: in function 'nvim_command'
        /Users/huangqiang/.config/nvim/lua/core/pack.lua:36: in function 'load_packer'
        /Users/huangqiang/.config/nvim/lua/core/pack.lua:81: in function 'init_ensure_plugins'
        /Users/huangqiang/.config/nvim/lua/core/pack.lua:96: in function 'ensure_plugins'
        /Users/huangqiang/.config/nvim/lua/core/init.lua:99: in function 'load_core'
        /Users/huangqiang/.config/nvim/lua/core/init.lua:114: in main chunk
        [C]: in function 'require'
        /Users/huangqiang/.config/nvim/init.lua:2: in main chunk
Error detected while processing command line:
E492: Not an editor command: PackerSync
Press ENTER or type command to continue

**Comment by ayamir** [comment]
先配置ssh
