### ISSUE TITLE
About neovide, goneovimkeymap.config error

### ISSUE THREAD

**Issue by p1k0pan** [ayamir/nvimdots#23]
I have used ```PackerSync``` and it updated some plugins(I don't remember which). Then I reopen the file it comes out this error
![DeepinScreenshot_select-area_20210831122520](https://user-images.githubusercontent.com/36180022/131442235-f7b07dbb-d035-41a2-91b1-0b581c00192f.png)
I have tryed to comment the ```require('neovide, goneovimkeymap.config')```, but after that, all the plugins with the start ```v.lua``` in the mapping command were dead (e.g. accelerated jk, vim-eft)
![DeepinScreenshot_select-area_20210831122911](https://user-images.githubusercontent.com/36180022/131442550-514a3397-1e31-48ae-b619-9c7eeff82dea.png)

I don't use neovide or goneovim to start nvim, instead I use st(simple terminal).

**Comment by ayamir** [comment]
My local config doesn't have this error. My settings about `neovide` is this line:
![neovide](https://user-images.githubusercontent.com/61657399/131449666-38153841-0fc7-4af8-9ad2-125148d68e2a.png)
Please consider comment this line.

**Comment by p1k0pan** [comment]
> My local config doesn't have this error. My settings about `neovide` is this line:
> ![neovide](https://user-images.githubusercontent.com/61657399/131449666-38153841-0fc7-4af8-9ad2-125148d68e2a.png)
> Please consider comment this line.

It doesn't work

**Comment by ayamir** [comment]
I have never seen this bug, please show me your whole `lua/keymap/config.lua`.

**Comment by p1k0pan** [comment]
```
local vim = vim

local t = function(str)
    return vim.api.nvim_replace_termcodes(str, true, true, true)
end

_G.enhance_jk_move = function(key)
    if packer_plugins['accelerated-jk'] and
        not packer_plugins['accelerated-jk'].loaded then
        vim.cmd [[packadd accelerated-jk]]
    end
    local map = key == 'j' and '<Plug>(accelerated_jk_gj)' or
                    '<Plug>(accelerated_jk_gk)'
    return t(map)
end

_G.enhance_ft_move = function(key)
    if not packer_plugins['vim-eft'].loaded then vim.cmd [[packadd vim-eft]] end
    local map = {
        f = '<Plug>(eft-f)',
        F = '<Plug>(eft-F)',
        t = '<Plug>(eft-t)',
        T = '<Plug>(eft-T)',
        [';'] = '<Plug>(eft-repeat)'
    }
    return t(map[key])
end

_G.enhance_move = function(key)
    if not packer_plugins['vim-easymotion'].loaded then
        vim.cmd [[packadd vim-easymotion]]
    end
    local map = {
        ['lnj'] = '<Plug>(easymotion-j)',
        ['lnk'] = '<Plug>(easymotion-k)',

        ['lf'] = '<Plug>(easymotion-bd-f)',
        ['lw'] = '<Plug>(easymotion-bd-w)',

        ['lnf'] = '<Plug>(easymotion-overwin-f)',
        ['lnw'] = '<Plug>(easymotion-overwin-w)'
    }
    return t(map[key])
end

_G.enhance_align = function(key)
    if not packer_plugins['vim-easy-align'].loaded then
        vim.cmd [[packadd vim-easy-align]]
    end
    local map = {['nga'] = '<Plug>(EasyAlign)', ['xga'] = '<Plug>(EasyAlign)'}
    return t(map[key])
end
```

This file I didn't change anything since I downloaded your script

**Comment by ayamir** [comment]
> I have used `PackerSync` and it updated some plugins(I don't remember which). Then I reopen the file it comes out this error
> ![DeepinScreenshot_select-area_20210831122520](https://user-images.githubusercontent.com/36180022/131442235-f7b07dbb-d035-41a2-91b1-0b581c00192f.png)
> I have tryed to comment the `require('neovide, goneovimkeymap.config')`, but after that, all the plugins with the start `v.lua` in the mapping command were dead (e.g. accelerated jk, vim-eft)
> ![DeepinScreenshot_select-area_20210831122911](https://user-images.githubusercontent.com/36180022/131442550-514a3397-1e31-48ae-b619-9c7eeff82dea.png)
> 
> I don't use neovide or goneovim to start nvim, instead I use st(simple terminal).

where you comment this line: `require('neovide, goneovimkeymap.config')`? I have never seen this.

**Comment by p1k0pan** [comment]
That is in the file ```keymap/init.lua``` line 4. If I don't comment this line, the whole neovim can't load all the plugins and it seems to return the basic settings.
![DeepinScreenshot_select-area_20210831144336](https://user-images.githubusercontent.com/36180022/131454932-c9fda39c-6e57-4faf-b880-b83da0e2e3ab.png)

**Comment by ayamir** [comment]
https://github.com/ayamir/nvimdots/blob/d1f2e2ee752ffe80f0a925ede3c759a53e914d6d/lua/keymap/init.lua#L5

**Comment by p1k0pan** [comment]
It works again! Strange that suddenly occur this Problem, before the update everything is ok even no need to comment that line.

Thanks again!
