### ISSUE TITLE
您好请问一下查看内核的话应该使用哪个标准,Lsp clangd

### ISSUE THREAD

**Issue by fakeczg** [ayamir/nvimdots#232]
![2022-09-20](https://user-images.githubusercontent.com/54363314/191199039-6e253292-1f58-4e17-b4fd-ef6e8cf5b813.png)

**Comment by ayamir** [comment]
这可能需要你自己google

**Comment by fakeczg** [comment]
bear -- make CC=clang -std=gun11 -j64
