### ISSUE TITLE
调用gh的时候右边的代码预览可否卷动查看；

### ISSUE THREAD

**Issue by fakeczg** [ayamir/nvimdots#233]
![图片](https://user-images.githubusercontent.com/54363314/191641811-e5ec25e6-50aa-45be-9999-2dbf01e60ffe.png)

**Comment by ayamir** [comment]
`<C-u>`向上滚动，`<C-d>`向下滚动

**Comment by fakeczg** [comment]
> 

为什么我的c-u和c-d是左边的框在滚动，我的意思是右边的代码框可以滚动 - -

**Comment by ayamir** [comment]
> > 
> 
> 为什么我的c-u和c-d是左边的框在滚动，我的意思是右边的代码框可以滚动 - -

嗯是这样的，是我疏忽了，lspsaga貌似现在不支持这样滚动了

**Comment by fakeczg** [comment]
> > > 
> > 
> > 
> > 为什么我的c-u和c-d是左边的框在滚动，我的意思是右边的代码框可以滚动 - -
> 
> 嗯是这样的，是我疏忽了，lspsaga貌似现在不支持这样滚动了

应该是可以的，我周末调一下看看～

**Comment by jczhang02** [comment]
这个问题有进展了嘛 @fakeczg

**Comment by fakeczg** [comment]
> 这个问题有进展了嘛 @fakeczg

新版本不支持了；
