### ISSUE TITLE
shfmt failed to install

### ISSUE THREAD

**Issue by zll600** [ayamir/nvimdots#236]
请问打开一个有 shell 脚本的目录，报了这个错误，可以问一下吗？
![image](https://user-images.githubusercontent.com/71714656/192201724-00e3360e-e139-4f06-ac59-744b402eac7f.png)

os: ubuntu 20.04
nvim version: 
![image](https://user-images.githubusercontent.com/71714656/192202470-d65e9d06-663a-43c2-b9e6-f4a7fbe75445.png)

nvim 安装方式： deb 包

**Comment by fakeczg** [comment]
打开MasonLog看一下就知道了，:MasonLog

**Comment by fakeczg** [comment]
如果没有:MasonLog这个命令，先执行:h Mason ---> :h MasonLog

**Comment by zll600** [comment]
是 ubuntu 的 go 版本太旧导致了，用最新的二进制包重装解决了，谢谢
