### ISSUE TITLE
Several keybindings need to be refactored

### ISSUE THREAD

**Issue by ayamir** [ayamir/nvimdots#248]

**Comment by ayamir** [comment]
@Jint-lzxy  Like what?

**Comment by Jint-lzxy** [comment]
@ayamir I'm not _quite_ sure, AFAIK these conflicting keybindings may be caused by plugin updates or upstream naming/implementation changes. I found some subtle problems recently but haven't tracked down the _actual_ source in detail. I will look into them recently.

**Comment by Jint-lzxy** [comment]
It can be confirmed that these subtle problems disappear with plugin updates, so it is no longer necessary to update keybindings
