### ISSUE TITLE
Migrate `vimscript` to lua code

### ISSUE THREAD

**Issue by ayamir** [ayamir/nvimdots#250]

**Comment by ayamir** [comment]
Does `vimscript` here refer to `vim.o` or `vim.g` in lua?

**Comment by Jint-lzxy** [comment]
It refers to the `vimscript` language _itself_ _(`VimL`)_.
e.g., The command wrapped by `vim.cmd` like:
```vim
vim.cmd([[set foldexpr=nvim_treesitter#foldexpr()]])
```
May be migrated to the corresponding lua API, i.e:
```lua
vim.api.nvim_set_option_value("foldexpr", "nvim_treesitter#foldexpr()", {})
```

Another Example:

from:
```lua
vim.cmd([[autocmd User PackerComplete lua require('core.pack').back_compile()]])
```
to:
```lua
vim.api.nvim_create_autocmd("User", {
	pattern = "PackerComplete",
	callback = function()
		require('core.pack').back_compile()
	end,
})
```
In several places, the code mixes vimscript and lua, like `vim.cmd([[let g:...]])` and `vim.g...`. IMO using the same language _might_ make the code more intuitive and easier to learn/modify, avoid calling vimL first then back to lua _(`:lua <statement>`)_ to execute some commands, and may improve performance in some occasions.
