### ISSUE TITLE
New options from `Nvim core`

### ISSUE THREAD

**Issue by ayamir** [ayamir/nvimdots#251]

**Comment by Jint-lzxy** [comment]
- **TRACKING UPSTREAM**
  - [x] `insertmode`, `remap` and `terse` options are removed.
  - [x] **treesitter**: Use `@foo.bar` style highlight groups.
  - [ ] Add `replace_keycodes` to `nvim_set_keymap` <==> https://github.com/neovim/neovim/pull/19598.
  - [ ] Enable mouse by **default** `(set mouse=nvi)` <==> https://github.com/neovim/neovim/pull/19290
  - [ ] Change in `LSP` table keys and new options: `LspAttach`, `LspDetach` <==> https://github.com/neovim/neovim/issues/14090#issuecomment-1113956767.
  - [ ] New option: `cmdheight = 0 [DFLT]` (https://github.com/neovim/neovim/pull/16251), `mousescroll!` (https://github.com/neovim/neovim/pull/12355), `undo!`.
  - [ ] Default type deduction changed to filetype.lua <==> https://github.com/neovim/neovim/issues/14090#issuecomment-1177933661. **Consider removing [nathom/filetype.nvim](https://github.com/nathom/filetype.nvim)**.
  - [ ] `:Man` ported to lua <==> https://github.com/neovim/neovim/pull/19912.
  - [ ] **Indexed** vim.cmd <==> https://github.com/neovim/neovim/commit/559ef3e90393a8f02c8350a9d60f4b7849815d97.
  - [ ] Measure `require()` in `--startuptime` <==> https://github.com/neovim/neovim/commit/2c739431e8e5a2aacc39ef429401f5e4427d027a.
  - [ ] Preview for user-created function <==> https://github.com/neovim/neovim/commit/46536f53e82967dcac8d030ee3394cdb156f9603.
  - [x] Get ui events from lua <==> https://github.com/neovim/neovim/pull/16396.
  - [ ] Allow `:wincmd` to accept a count <==> https://github.com/neovim/neovim/pull/19815.
  - [ ] hl group `CurSearch` <==> https://github.com/neovim/neovim/commit/b16afe4d556af7c3e86b311cfffd1c68a5eed71f **Consider modifying Catppuccin**.
  - [ ] `:map`, `:command`, `:au` can print location in lua source (like `debug.getinfo`) <==> https://github.com/neovim/neovim/commit/3df8d9b8c56a7f0af0f7590b11831bd96ead92f1.
  - [ ] `vim.opt and vim.o` **Consider refactoring related code**.
    - https://github.com/neovim/neovim/pull/19477#issuecomment-1194040328;
    - https://github.com/neovim/neovim/pull/19982;
    - https://github.com/neovim/neovim/issues/20107.
  - [ ] Clickable statusline <==> https://github.com/neovim/neovim/pull/18650.

**Comment by nullchilly** [comment]
@CharlesChiuGit We will have to wait until neovim 0.8.1
