### ISSUE TITLE
Question about disabling distribution plugins.

### ISSUE THREAD

**Issue by CharlesChiuGit** [ayamir/nvimdots#266]
I couldn't seem to be able to find those options stated in the [**disable_distribution_plugins** function](https://github.com/ayamir/nvimdots/blob/6e8e25e4fae7ac20d3284afa84d647973f0dd7b2/lua/core/init.lua#L24-L45) in neovim's offical repo. The closest thing I could found are:
```lua
vim.g.loaded_gzip = 1
vim.g.loaded_tar = 1
vim.g.loaded_tarPlugin = 1
vim.g.loaded_zip = 1
vim.g.loaded_zipPlugin = 1
vim.g.loaded_vimball = 1
vim.g.loaded_vimballPlugin = 1
vim.g.loaded_matchit = 1
vim.g.loaded_matchparen = 1
vim.g.loaded_2html_plugin = 1
vim.g.loaded_netrw = 1
vim.g.loaded_netrwPlugin = 1
vim.g.loaded_netrwSettings = 1
vim.g.loaded_netrwFileHandlers = 1
```

Is there a reason using `vim.g.did_load_XXX` instead of `vim.g.loaded_XXX`?

Also, I couldn't find any vimscript that's related to following options:
```lua
vim.g.did_load_fzf = 1
vim.g.did_load_gtags = 1
vim.g.did_load_getscript = 1
vim.g.did_load_getscriptPlugin = 1
vim.g.did_load_logiPat = 1
vim.g.did_load_rrhelper = 1
```
Are those options shipped from other vim/neovim forks?
The only thing I could find is [this neovim commit](https://github.com/neovim/neovim/commit/5fd21b8d3e9dcb2b3dc3bdab4b58218ac908e3e8), which indicates `getscript.vim` was omitted from neovim.

Thanks for building such a great config!

**Comment by ayamir** [comment]
It should be `loaded` and I forgot why I use `did_load` to avoid loading these plugins.
