### ISSUE TITLE
如何使用lspconfig

### ISSUE THREAD

**Issue by LC0117** [ayamir/nvimdots#27]
这个配置很全面,但是目录有点复杂,不知道该在哪里加入自己的配置~
请问如何在lspconfig.lua中写入自己的配置,比如clangd.
另:在lspconfig仓库给出的配置似乎不能直接复制进入lspconfig.lua使用.

**Comment by ayamir** [comment]
lspconfig的配置需要你懂一点lua的语法：
https://github.com/ayamir/nvimdots/blob/fa7a1f1f28f86090d35e270c513ef425479d3b5b/lua/modules/completion/lspconfig.lua#L41
这个函数意思就是一个for循环，遍历了所有用lspinstall安装好的server，对其attach函数进行了重写
你要是想对clangd做额外的配置，可以参考我对lua的配置方法，用if判断单独设置clangd

**Comment by LC0117** [comment]
是的,我主要是想使用自己路径里面的clangd,这样不同的编辑器可以共享cache,但是就是到这一步不知道该怎么写下去了.
lspconfig的文档提供的模板不知道该如何加进去
<img width="897" alt="1" src="https://user-images.githubusercontent.com/77481149/132102627-77fd3a67-280f-45e8-90ce-5971fb76ae4a.png">

**Comment by 1096015776** [comment]
if you feel it is diffcult, maybe you can fork the nvim-lspinstall then change some config that you wanted,then use your origin lspinstall,may it is easy to do it.
then you can even config lang use lsp that you wanted.
so why not try it more

**Comment by ayamir** [comment]
> 是的,我主要是想使用自己路径里面的clangd,这样不同的编辑器可以共享cache,但是就是到这一步不知道该怎么写下去了.
> lspconfig的文档提供的模板不知道该如何加进去
> <img alt="1" width="897" src="https://user-images.githubusercontent.com/77481149/132102627-77fd3a67-280f-45e8-90ce-5971fb76ae4a.png">

这不是很简单吗？你只要不用lspinstall装clangd，单独把你对clangd的setup函数写在lspconfig.lua后面不就行了？
```lua


local function switch_source_header_splitcmd(bufnr, splitcmd)
    bufnr = require'lspconfig'.util.validate_bufnr(bufnr)
    local params = {uri = vim.uri_from_bufnr(bufnr)}
    vim.lsp.buf_request(bufnr, 'textDocument/switchSourceHeader', params,
                        function(err, _, result)
        if err then error(tostring(err)) end
        if not result then
            print("Corresponding file can’t be determined")
            return
        end
        vim.api.nvim_command(splitcmd .. ' ' .. vim.uri_to_fname(result))
    end)
end

nvim_lsp.clangd.setup {
    capabilities = capabilities,
    flags = {debounce_text_changes = 500},
    on_attach = custom_attach,
    commands = {
        ClangdSwitchSourceHeader = {
            function() switch_source_header_splitcmd(0, "edit") end,
            description = "Open source/header in current buffer"
        },
        ClangdSwitchSourceHeaderVSplit = {
            function() switch_source_header_splitcmd(0, "vsplit") end,
            description = "Open source/header in a new vsplit"
        },
        ClangdSwitchSourceHeaderSplit = {
            function() switch_source_header_splitcmd(0, "split") end,
            description = "Open source/header in a new split"
        }
    }
}

```

**Comment by LC0117** [comment]
成功了!原来是我对lspconfig那里的文档没有理解透,感谢作者!
