### ISSUE TITLE
[Suggest]便于自定义插件及配置的方式

### ISSUE THREAD

**Issue by rickywu** [ayamir/nvimdots#281]
现在的文件结构不便于自定义配置的同时又更新你的基线
是否可以建立一个空文件，便于用户自定义自己的配置
更新基线后覆盖这个空文件即可，不用再合并一次变更

**Comment by CharlesChiuGit** [comment]
I think u can create a "user" folder under "modules" with "plugins.lua" in it to achieve this.

**Comment by ayamir** [comment]
更新到最新的配置之后，你可以修改`lua/modules/custom`目录下的`plugins.lua`和`config.lua`来做自己的额外配置而并不会被git跟踪其变化
