### ISSUE TITLE
在书写latex的时候，lsp会自动的打出（）小括号，但是应该打出大括号{}

### ISSUE THREAD

**Issue by flaviusbuffon** [ayamir/nvimdots#29]
![image](https://user-images.githubusercontent.com/44057232/132177084-a9267fe8-9a85-424c-8265-f2159b1ff275.png)

**Comment by 1096015776** [comment]
I not write latex, i use a latex demo,I do not find this problem
first date begin is good
just makealetter is not good
then i find github's latex demo do not use () event not use {}
if you think it is bad , I try it.
I find just lsp complete,
so you can change lsp or you can find a plugin about latex.
why not try more.
if you feel it is bad just at makeatletter, you can give the lsp issue.

**Comment by 1096015776** [comment]
here you are the lsp
https://github.com/latex-lsp/texlab

**Comment by flaviusbuffon** [comment]
i am using this lsp, but it shows :
all function will auto appear "()"
![image](https://user-images.githubusercontent.com/44057232/132188366-dd673e60-3f3d-4cd9-85a9-c45640b20c37.png)

**Comment by 1096015776** [comment]
I'm sorry that I can not help you, I try it to change lsp config,like nvim lsp config example,
but not work,it complete use (),but I find the latex lsp give me example is not () {},
total,I stop the lsp , the not complete (). so I'm sure that is lsp let it use(),but I can not change, maybe somewhere i not notice.maybe you should get help from the lsp origin,
becacuse there is many people who use know why.

**Comment by flaviusbuffon** [comment]
thanks for your work!

**Comment by flaviusbuffon** [comment]
i have commit this question to texlab, hope can get a solution

**Comment by flaviusbuffon** [comment]
> I'm sorry that I can not help you, I try it to change lsp config,like nvim lsp config example,
> but not work,it complete use (),but I find the latex lsp give me example is not () {},
> total,I stop the lsp , the not complete (). so I'm sure that is lsp let it use(),but I can not change, maybe somewhere i not notice.maybe you should get help from the lsp origin,
> becacuse there is many people who use know why.

hey, texlab won't add () after functions, like "\title",
so it might be the fault of some autopair plugin,
do you have a idea?

**Comment by flaviusbuffon** [comment]
problem solved, just look up "autopair" plugin to change second config

**Comment by 1096015776** [comment]
so cool that you solve it
