### ISSUE TITLE
error when using LsoutlineToggle command

### ISSUE THREAD

**Issue by Lraxer** [ayamir/nvimdots#291]
**Describe the bug**
I got an error when using `LsoutlineToggle` command (shortcut: `<A-t>`). The error happened in c, cpp, python, go files, but not rust.
I'm not sure if this bug is from upstream, i.e., lspsaga. So I hope someone can reproduce and confirm it.

**To Reproduce**
Please check the gif.
![Peek 2022-10-17 22-54](https://user-images.githubusercontent.com/32860114/196211400-7c203320-4b11-46ad-99ec-9b7fc10a6b37.gif)

**Environment (please complete the following information):**
 - OS: Archlinux
 - neovim 0.8.0

**Comment by CharlesChiuGit** [comment]
Can confirm. It doesn't work in my python too.
I think it's lspsaga's bug.

neovim: 0.9.0-dev

**Comment by Lraxer** [comment]
> If u can't wait the plugin author to fix it, i think [simrat39/symbols-outline.nvim](https://github.com/simrat39/symbols-outline.nvim) is another great choice. At least, it works in python in my case. Check [my config's of symbols-ouline.nvim](https://github.com/CharlesChiuGit/nvimdots.lua/blob/main/lua/modules/editor/symbols-outline.lua).

Thanks for your help. I'd better wait some time. If there's no fix then I will switch to symbols-outline.nvim.

**Comment by CharlesChiuGit** [comment]
https://github.com/glepnir/lspsaga.nvim/commit/afbd5718ffd453662ada49e9c520df60efc8f444

0.2.3 is finally here!

**Comment by shelper** [comment]
i think now lspsaga has outline, maybe add a keybinding to that @Lraxer

**Comment by Lraxer** [comment]
> i think now lspsaga has outline, maybe add a keybinding to that @Lraxer

Now you can use shortcut `go` to open the outline. In wiki it is called "tagbar".
