### ISSUE TITLE
SnipRun 报错

### ISSUE THREAD

**Issue by ian-ie** [ayamir/nvimdots#292]
![image](https://user-images.githubusercontent.com/55068959/196333675-dd7b1370-0a63-415b-9169-ab19be4091f3.png)

![image](https://user-images.githubusercontent.com/55068959/196333647-c6e78ab1-73e8-4aad-9d46-0b66dd03a765.png)

**Comment by CharlesChiuGit** [comment]
Have u check the file exists and executable?

**Comment by ian-ie** [comment]
> Have u checked the file exists and is executable?
> 
> Works fine for me.

I have executed :PackerSync and passed

**Comment by CharlesChiuGit** [comment]
We can't really do anything due to lacking of info.

**Comment by ayamir** [comment]
> ![image](https://user-images.githubusercontent.com/55068959/196333675-dd7b1370-0a63-415b-9169-ab19be4091f3.png)
> 
> ![image](https://user-images.githubusercontent.com/55068959/196333647-c6e78ab1-73e8-4aad-9d46-0b66dd03a765.png)

I noticed that you are using this config for `root` user which is not recommanded. BTW, you can execuet this command to solve it:
```shell
chmod +x /root/.local/share/nvim/site/pack/packer/opt/sniprun/target/release/sniprun
```
