### ISSUE TITLE
遇到两个问题，查了issues也没解决

### ISSUE THREAD

**Issue by nkta3m** [ayamir/nvimdots#295]
第一个问题： 

OS： Debian 11

Neovim： 0.9

Black 装不上，我查了issues，检查了go在PATH里，每次打开都会有下面的提示
![shot-2022-10-20_16-25-28](https://user-images.githubusercontent.com/13484700/196897632-73973ee5-cb06-4857-8e5d-4f23b978220e.jpg)

第二个问题：

OS： Arch

Neovim： 0.9

LuaSnip报错；

![shot-2022-10-20_16-29-10](https://user-images.githubusercontent.com/13484700/196897769-3d9a56ed-901b-4e63-96b3-40c70897cd64.jpg)

**Comment by CharlesChiuGit** [comment]
1. If you're using newer python, like 3.8, 3.9, 3.10, u need to install following packages so the system can make venv, which is required by mason to install `black` if u check `:MasonLog`
`sudo apt install python3-pip python3-dev python3-setuptools python3.10-venv `

**Comment by nkta3m** [comment]
第二个问题在两个系统都出现，第一个问题h只是在debian出现，Arch是可以正常安装的

**Comment by CharlesChiuGit** [comment]
2. Lack of info, guessing u got something wrong in your luasnip config.

**Comment by nkta3m** [comment]
@CharlesChiuGit 非常感谢，black的问题解决了，我在研究一下第二个问题。

**Comment by CharlesChiuGit** [comment]
u can use :Telescope notify to show the full error meassages

**Comment by ayamir** [comment]
我也使用Arch与nvim-0.9但是并没有出现问题，所以要如何复现？

**Comment by nkta3m** [comment]
这两天忙着买菜，被封在家里了，电脑没带，可能要晚一段时间再回复，我现在也不清楚是哪里的问题。

**Comment by nkta3m** [comment]
这个问题我关掉了，因为第二个问题是我自己的错误，写错$HOME的值，现在已经好了。

**Comment by ian-sung-asus** [comment]
> 

It helps thanks a lot.

**Comment by ian-sung-asus** [comment]
> If you're using newer python, like 3.8, 3.9, 3.10, u need to install following packages so the system can make venv, which is required by mason to install black if u check :MasonLog.
sudo apt install python3-pip python3-dev python3-setuptools python3.10-venv 

This works, thank you.
