### ISSUE TITLE
What is the tool that generated the ascii art?

### ISSUE THREAD

**Issue by fleongg** [ayamir/nvimdots#297]
Sorry I do not know if this is suitable for opening an issue. I want to create an ascii art for the dashboard. After I have tried several tools to do so, I found that their style does not yield a good result in a terminal like yours. Could you kindly share your tool that does it? Thanks!

**Comment by CharlesChiuGit** [comment]
Maybe it's better to use [Discussions](https://github.com/ayamir/nvimdots/discussions).

**Comment by CharlesChiuGit** [comment]
I think [TheZoraiz/ascii-image-converter](https://github.com/TheZoraiz/ascii-image-converter) is the one you're looking for.
But it's also very important to pick a picture that's suitable for converting to ascii art. Also, u need to fine-tune tha flags and the parameters to get the best result.

**Comment by ayamir** [comment]
https://github.com/ayamir/nvimdots/wiki/Issues#change-dashboard-startup-image

**Comment by fleongg** [comment]
Thank you CharlesChiuGit for the notice, I did not notice that section. Thankyou ayamir!

**Comment by ayamir** [comment]
In fact, the terminal also influences the final effect. The terminal in my shots is `kitty`, but in `wezterm` it will have a better look.
