### ISSUE TITLE
插入模式回车换行错误

### ISSUE THREAD

**Issue by p1k0pan** [ayamir/nvimdots#298]
<img width="1418" alt="image" src="https://user-images.githubusercontent.com/36180022/197265818-78b1a5df-835c-421a-861c-a3d185fbfd95.png">

如果注释了nvim-cmp中回车键的mapping就没有错误，但是就不能确认选项了

macOS 12.3
nvim 0.8

**Comment by CharlesChiuGit** [comment]
U may want to try to replace:
`["<CR>"] = cmp.mapping.confirm({ select = true })`
with
```lua
["<CR>"] = cmp.mapping.confirm({
	-- this is the important line
	behavior = cmp.ConfirmBehavior.Replace,
	select = false,
}),
```
I use this in my [config](https://github.com/CharlesChiuGit/nvimdots.lua/blob/03ef79f8eb0fd8f8d916aebcd43852e37df48160/lua/modules/completion/cmp.lua#L83-L87).

**Comment by ayamir** [comment]
所以如何复现？

**Comment by Jint-lzxy** [comment]
That's weird, AFAIK `replace_keycodes` was added to `nvim_set_keymap` in Nvim 0.8. **What is the output of `nvim --version` then?**

If you are using Homebrew, use `brew list --pinned` to check whether nvim has been blocked for updates. In addition, you may try reinstalling neovim: `brew uninstall nvim && brew install nvim` 👍

**Comment by p1k0pan** [comment]
> 

Thanks, reinstall works!
