### ISSUE TITLE
proposal：给ssh远程开发提供一个全局剪切板能力

### ISSUE THREAD

**Issue by kevin1sMe** [ayamir/nvimdots#303]
**描述Bug**

给ssh远程开发提供一个全局剪切板能力？

**如何复现**
本地机器MacOS，远程机器为Ubuntu等linux系统，目前插件配置不了解如何可支持远程复制。

**期待的表现**

最好可以用原生复制方式拷贝到系统（全局）剪切板，本机和远程开发机共享剪切板的效果。
希望默认仓库可以支持这个能力。若有需要我可以提PR：）

**截图**

无

**运行环境**

- 操作系统：MacOS 10.15
- `nvim`版本： NVIM v0.8.0-1210-gd367ed9b2
- `nvim`安装方式：manual

**额外信息**
我尝试用了这个插件：`ojroques/vim-oscyank`能解决问题。
见这个[commit](https://github.com/kevin1sMe/nvimdots/commit/763f8ec47aa97a4cb4e84d3647ee63534d366783)

**注意：没有任何信息的issue将会被直接关闭，请不要浪费双方的时间。**

**Comment by ayamir** [comment]
I tend to use its lua rewrite version: [ojroques/nvim-osc52](https://github.com/ojroques/nvim-osc52). But there is no convenient method to detect whether it runs on a remote machine, so I have no idea to set clipboard for it like what I did for wsl and macOS [here](https://github.com/ayamir/nvimdots/blob/61fe5b7f5374beaee18c0c730441d55ad5911604/lua/core/init.lua#L92-L114)

**Comment by kevin1sMe** [comment]
> I tend to use its lua version: [ojroques/nvim-osc52](https://github.com/ojroques/nvim-osc52). But there is no convenient method to detect whether it runs on a remote machine AFAIK. I have no idea to set clipboard for it like what I did for wsl and macOS [here](https://github.com/ayamir/nvimdots/blob/61fe5b7f5374beaee18c0c730441d55ad5911604/lua/core/init.lua#L92).

I try to use nvim-osc52,  but not work. Can you show me example config? Thanks.

**Comment by CharlesChiuGit** [comment]
```lua
require("osc52").setup({
	max_length = 0, -- Maximum length of selection (0 for no limit)
	silent = true, -- Disable message on successful copy
	trim = false, -- Trim text before copy
})

--- nvim-osc52 keymap
-- In normal mode, <leader>c is an operator that will copy the given text to the clipboard.
vim.keymap.set("n", "<leader>c", require("osc52").copy_operator, { expr = true })
-- In normal mode, <leader>cc will copy the current line.
vim.keymap.set("n", "<leader>cc", "<leader>c_", { remap = true })
-- In visual mode, <leader>c will copy the current selection.
vim.keymap.set("x", "<leader>c", require("osc52").copy_visual)
```

**Comment by CharlesChiuGit** [comment]
@kevin1sMe Also, please check #275 .

**Comment by CharlesChiuGit** [comment]
There's also another option which is to mount your remote files in your local system.
Pleae check [this video](https://youtu.be/0fAygjWHpdM).

**Comment by ayamir** [comment]
> 

You can create a PR for smartyank if it support osc52 :)

**Comment by CharlesChiuGit** [comment]
@kevin1sMe That's totally fine! It's up to u.

@ayamir Sure, I'll do some tests to make sure everything works as expected before sending the PR.
