### ISSUE TITLE
疑问：cpp 项目中没有显示 build 目录

### ISSUE THREAD

**Issue by zll600** [ayamir/nvimdots#304]
使用的时候产生的疑问：
在 cpp 项目中，打开目录树后，目录树中并没有显示 build 目录，和生成的 .release 目录，但是可以正常看到 .git 目录

OS: ubuntu 20.04
neovim: 0.8

**Comment by ayamir** [comment]
It is because `nvim-tree` support `.gitignore`. You defined `build` and `.release` directory in `.gitignore` of your project so these dirs will be hidden. You can use `I` to toggle their visibility in `nvim-tree`.

**Comment by zll600** [comment]
> It is because `nvim-tree` support `.gitignore`. You defined `build` and `.release` directory in `.gitignore` of your project so these dirs will be hidden. You can use `I` to toggle their visibility in `nvim-tree`.

十分感谢
