### ISSUE TITLE
请问如何卸载？ 安装成功， 但是 语言 总是不成功，想卸载了。 

### ISSUE THREAD

**Issue by nevertoday** [ayamir/nvimdots#305]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
 - OS: [e.g. Archlinux/Ubuntu/macOS]
 - Nvim version(output of `nvim --version`)

**Additional context**

**Note: Any issue without any information will be closed directly, Please value our time.**

**描述Bug**

尽可能清晰简单地描述出Bug

**如何复现**

1. 以何种方式打开文件（`Telescope`或直接打开）
2. 执行什么命令？
3. 点击什么？
4. 使用什么快捷键？
5. ...

**期待的表现**

尽可能清晰简单地描述你想要的效果

**截图**

如果有截图的话，尽量给出截图

**运行环境**

- 操作系统：
- `nvim`版本：（`nvim --version`的输出）
- `nvim`安装方式：（AppImage或包管理器名）

**额外信息**

如果有额外信息，请在这里添加

**注意：没有任何信息的issue将会被直接关闭，请不要浪费双方的时间。**

**Comment by CharlesChiuGit** [comment]
https://github.com/ayamir/nvimdots/wiki/Issues#remove-nvimdots

**Comment by CharlesChiuGit** [comment]
Please close the issue.
