### ISSUE TITLE
Caught an error when executing nvim +PackerSync

### ISSUE THREAD

**Issue by Dusker233** [ayamir/nvimdots#307]
When I executing `nvim +PackerSync`, I got an error like this:

:!git clone https://github.com/wbthomason/packer.nvim/root/.local/share/nvim/site/pack/packer/opt/packer.nvim
Cloning into 'packer.nvim'...
remote: Not Found
fatal: repository 'https://github.com/wbthomason/packer.nvim/root/.local/share/nvim/site/pack/packer/opt/packer.nvim/' n
ot found
shell returned 128

Error detected while processing /root/.config/nvim/init.lua:
E5113: Error while calling lua chunk: /root/.config/nvim/lua/core/pack.lua:46: Vim(packadd):E919: Directory not found in
 'packpath': "pack/*/opt/packer.nvim"
stack traceback:
        [C]: in function 'nvim_command'
        /root/.config/nvim/lua/core/pack.lua:46: in function 'load_packer'
        /root/.config/nvim/lua/core/pack.lua:97: in function 'init_ensure_plugins'
        /root/.config/nvim/lua/core/pack.lua:112: in function 'ensure_plugins'
        /root/.config/nvim/lua/core/init.lua:122: in function 'load_core'
        /root/.config/nvim/lua/core/init.lua:136: in main chunk
        [C]: in function 'require'
        /root/.config/nvim/init.lua:2: in main chunk
Error detected while processing command line:
E492: Not an editor command: PackerSync

How can I solve this problem?

**Comment by Dusker233** [comment]
好像是缺少了一个空格 但我不知道怎么修复这个bug

**Comment by Dusker233** [comment]
when I didnt use root user, error also happened.

**Comment by CharlesChiuGit** [comment]
Change this line
https://github.com/ayamir/nvimdots/blob/9106ac03331414d10c7ad4b16b1783cf64844860/lua/core/pack.lua#L90

to 

```lua
or "!git clone https://github.com/wbthomason/packer.nvim "
```

**Comment by CharlesChiuGit** [comment]
it's a small bug will fix soon, thanks for reporting!

**Comment by Dusker233** [comment]
thx a lot and I'll try soon.

**Comment by CharlesChiuGit** [comment]
@Dusker233 it should be fixed now, please git pull the repo and try again. #308
