### ISSUE TITLE
How to use this project as a editor for legacy nodejs project ?

### ISSUE THREAD

**Issue by infinityhacks** [ayamir/nvimdots#309]
I'm using  NVM for nodejs version management 

As the :checkhealth shows which  version it self needs 

```
ERROR: npm: unsupported version `3.10.10`. npm version must be >= 6 
ERROR: node: unsupported version `v6.17.1`. Node version must be >= 14
```

I tried to set vim.g.node_host_prog . It still dosent work.

```
ERROR: Command error (job=18, exit code 1): `node '~/.nvm/versions/node/v16.18.0/bin/neovim-node-host' --version`
```

How can I set a node version like v16 only in neovim , and other versions in projects ?

From this article . 

[https://stackoverflow.com/questions/63281169/setting-custom-node-version-path-for-neovim](https://stackoverflow.com/questions/63281169/setting-custom-node-version-path-for-neovim)

it seems there is a way by setting $PATH in neovim to resolve my issue . but I'm not very clear to how to translate the setting in this project 

LFW for your help .thanks.

**Comment by CharlesChiuGit** [comment]
For example, my nodejs is install in `~/tools/nodejs`, so i set my `vim.g.node_host_prog` like this:
```lua
-- custom node provider
vim.g.node_host_prog = global.home .. "/tools/nodejs/lib/node_modules/neovim/bin/cli.js"
```

**Comment by ayamir** [comment]
You can set `path` in this way:
```lua
vim.opt.path = vim.opt.path + "/home/ayamir/.nvm/versions/node/v16.17.1/bin/"
```
replace the string with your node location.
Don't forget to execute `npm i -g neovim` for this node version.

**Comment by ayamir** [comment]
![image](https://user-images.githubusercontent.com/61657399/198861402-d83131dc-1eda-41ba-ab78-3b2fa1071ccc.png)
```lua
	-- custom node provider
	vim.g.node_host_prog = "/home/ayamir/.nvm/versions/node/v16.17.1/bin/neovim-node-host"
	vim.cmd([[let $PATH = "/home/ayamir/.nvm/versions/node/v16.17.1/bin:" . $PATH]])
```
replace the string on your demand.

**Comment by CharlesChiuGit** [comment]
FYI. `neovim-node-host -> ../lib/node_modules/neovim/bin/cli.js*`. So it's fine to choose either one.

**Comment by infinityhacks** [comment]
> 
```
