### ISSUE TITLE
Slow: when working with md & tex with text concealing

### ISSUE THREAD

**Issue by Aiedails** [ayamir/nvimdots#312]
**Describe the bug**
Hi! I'm really enjoying your nvim config, but recently I found when it works with md & tex, it becomes terriblely slow.
When it comes to markdown or tex file with **math formula**, nvim becomes extremely slow and one core the of CPU goes to 100%

**To Reproduce**
open a markdown file, write a few lines of math formula, scroll up and down

**Expected behavior**
no lagging, a normal fast nvim

**Environment (please complete the following information):**
 - OS: Archlinux
 - nvim version: 0.8.0

**Additional context**
I found when I turn off the `markdown_math` option, it went back to normal. It works well when no concealing symbols are in the current buffer. I've tried to use `perf record` but there's no helpful information. Other monitor dashboards such as glances just say it's nvim use a lot of CPU. I've found that vimtex may have folding issue by [this](https://github.com/lervag/vimtex/issues/372), but I don't have any idea whether this has a relationship with my condition. I've reproduced this condition in multiple terminals like alacritty and wezterm. Are there more ways to locate this issue?

**Comment by ayamir** [comment]
Have you ever encounter this problem? @jczhang02

**Comment by Aiedails** [comment]
Oh, I'm terribly sorry but it seems I've messed up my config file. So this bug should be not related to your configuration. Sorry again for the inconvenience caused by my fault and I'll be more careful next time.
