### ISSUE TITLE
不想使用git ssh key的模式

### ISSUE THREAD

**Issue by nkta3m** [ayamir/nvimdots#313]
不想使用git ssh key的模式，参考了之前#168，但是lua/module/editer/config.lua还有配置，不修改的话，一直报错没办法下载treesitter的文件，直接删了又会提示有错误，这里正确的修改方式是什么？

**Comment by ayamir** [comment]
You can use https to update plugins during installation if you follow wiki and use install.sh to install.

**Comment by CharlesChiuGit** [comment]
refer to nvim-treesitter
https://github.com/nvim-treesitter/nvim-treesitter#i-want-to-use-a-http-proxy-for-downloading-the-parsers

```lua
require("nvim-treesitter.install").command_extra_args = {
    curl = { "--proxy", "<proxy url>" },
}
```

**Comment by nkta3m** [comment]
我在windows下使用，所以没有使用install.sh。
不是proxy的问题，git@github.com这个问题，我想使用https://github.com这样

**Comment by CharlesChiuGit** [comment]
```lua
require("nvim-treesitter.install").prefer_git = true
-- local parsers = require("nvim-treesitter.parsers").get_parser_configs()
-- for _, p in pairs(parsers) do
-- 	p.install_info.url = p.install_info.url:gsub("https://github.com/", "git@github.com:")
-- end
```

**Comment by nkta3m** [comment]
谢谢，我现在去试试看

**Comment by nkta3m** [comment]
问题解决了，非常感谢
