### ISSUE TITLE
Failed to add a project 

### ISSUE THREAD

**Issue by infinityhacks** [ayamir/nvimdots#315]
I can't add some directories to project, but some directories would work.

![failed-to-add-project](https://user-images.githubusercontent.com/1070290/200525631-4aa2bb47-8679-49c4-af46-dba1ab5524ee.png)

From above screenshot, you can see there are 2 directories added to projects successfully.  And when adding a new one "docs" ,the message shows success, but it dosent show on the project lists.

Any ideas ?

**Comment by Jint-lzxy** [comment]
Cannot reproduce. Are there any special characters in the obscured pathname? In addition, is the `docs` folder in a directory containing the `.git` folder? It is not _yet_ supported to create new projects under the subdirectories of any `git` project.

The current workaround is to manually modify `${HOME}/.local/share/nvim/telescope-projects.txt`, make sure to make a backup before every change. Details: https://github.com/nvim-telescope/telescope-project.nvim/issues/65

![dem](https://user-images.githubusercontent.com/50296129/200553887-eb9f4594-b8a4-46b2-b2aa-71075b340a86.png)

**Comment by infinityhacks** [comment]
Thanks for your reply.

According to your idea, I realized the issue might cause by the directories ,like names, properties and so on. After a few tests. I find the root cause and I can reproduce the issue:

If any folder you plan to add to the project contains the words "**cache**" or under it , the issue will occure.

I'm not sure if there is way to fix this. Maybe, I should ask this in the telescope repo ?

**Comment by Jint-lzxy** [comment]
> Thanks for your reply.
> 
> According to your idea, I realized the issue might cause by the directories ,like names, properties and so on. After a few tests. I find the root cause and I can reproduce the issue:
> 
> If any folder you plan to add to the project contains the words "**cache**" or under it , the issue will occure.
> 
> I'm not sure if there is way to fix this. Maybe, I should ask this in the telescope repo ?

Ah, I see. @infinityhacks Can you provide the output of `cat ${HOME}/.local/share/nvim/telescope-projects.txt`? Looks like directories containing the word `cache` is ignored by default when we setup telescope. If the directory is _indeed_ included in `telescope-projects.txt` then we can solve this problem 👍

**Comment by infinityhacks** [comment]
Sorry ,for some reason I can't just show you the outputs .

But yes. All the folders I added from the telescopes , they are added in $HOME/.local/share/nvim/telescope-projects.txt. It looks like they just not showing up if the "path" contains "cache"

**Comment by Jint-lzxy** [comment]
@infinityhacks Just remove `".cache"` from the table below and we're all set 🎉. Do note that other folders containing the word "cache" (e.g., `.cache`) will also be displayed.
https://github.com/ayamir/nvimdots/blob/b978c29b94f36cb3a28bbf5ec50147efa5d80d46/lua/modules/tools/config.lua#L35

**Comment by infinityhacks** [comment]
Bingo, I did the same thing to fix this. Not sure if there is a better way to fix this 

Anyway, thank u all the same.

**Comment by Jint-lzxy** [comment]
There is no better alternative at present. However, if telescope updates the parsing method for ignoring directories in the future, we will also make timely adjustments 👍
