### ISSUE TITLE
请问 怎么开启对markdown 文稿的支持？？ 

### ISSUE THREAD

**Issue by nevertoday** [ayamir/nvimdots#317]
### Feature description

我有好多.md 文档， 用nvim打开后，总是提示一些警告的东西。
<img width="763" alt="image" src="https://user-images.githubusercontent.com/166048/200874159-d0312441-1e26-4e81-bc61-f42cd28ea333.png">
thks

**Comment by ayamir** [comment]
Your installation is not complete. Please follow the wiki to install efm-langserver and other components first.

**Comment by ayamir** [comment]
Your installation is not complete. Please follow the wiki to install efm-langserver and other components first.
