### ISSUE TITLE
how to add the two shortcuts config in nvim config

### ISSUE THREAD

**Issue by flaviusbuffon** [ayamir/nvimdots#32]
```
inoremap <C-f> <Esc>: silent exec '.!inkscape-figures create "'.getline('.').'" "'.b:vimtex.root.'/figures/"'<CR><CR>:w<CR>
nnoremap <C-f> : silent exec '!inkscape-figures edit "'.b:vimtex.root.'/figures/" > /dev/null 2>&1 &'<CR><CR>:redraw!<CR>
```

Hope give me a config , i am just a noob of lua nvim

**Comment by ayamir** [comment]
```lua
        [[<Esc>: silent exec '.!inkscape-figures create "'.getline('.').'" "'.b:vimtex.root.'/figures/"'<CR><CR>:w<CR>]]):with_noremap(),
    ["n|<C-f>"] = map_cmd([['!inkscape-figures edit "'.b:vimtex.root.'/figures/" > /dev/null 2>&1 &'<CR><CR>:redraw!<CR>]]):with_noremap():with_silent(),
```
Add this to `lua/keymap/init.lua`

**Comment by flaviusbuffon** [comment]
thanks for your help! also, i want to ask how to add vimscript config in lua config. I have read the guide of lua and vim, but it was useless for me.
Like code below, how to add them in your config?

```
" custom setting for clangformat
let g:neoformat_cpp_clangformat = {
    \ 'exe': 'clang-format',
    \ 'args': ['--style="{IndentWidth: 4}"']
\}
let g:neoformat_enabled_cpp = ['clangformat']
let g:neoformat_enabled_c = ['clangformat']
```

**Comment by ayamir** [comment]
> thanks for your help! also, i want to ask how to add vimscript config in lua config. I have read the guide of lua and vim, but it was useless for me.
> Like code below, how to add them in your config?
> 
> ```
> " custom setting for clangformat
> let g:neoformat_cpp_clangformat = {
>     \ 'exe': 'clang-format',
>     \ 'args': ['--style="{IndentWidth: 4}"']
> \}
> let g:neoformat_enabled_cpp = ['clangformat']
> let g:neoformat_enabled_c = ['clangformat']
> ```

refer to it: https://github.com/glepnir/nvim-lua-guide-zh

**Comment by flaviusbuffon** [comment]
i have read the guide, but i failed to add config in editor/config.lua file, so i come to seek help

**Comment by ayamir** [comment]
add this to `lua/modules/editor/config.lua`:
```lua
function config.neoformat()
    vim.g.neoformat_cpp_clangformat = {
        exe = 'clang-format',
        args = {'--style="{IndentWidth: 4}"'}
    }
    vim.g.neoformat_enabled_cpp = {'clangformat'}
    vim.g.neoformat_enabled_c = {'clangformat'}
end
```
modify `lua/modules/editor/plugins.lua`'s `neoformat` section to this:
```lua
editor['sbdchd/neoformat'] = {opt = true, cmd = 'Neoformat', config = conf.neoformat}
```

**Comment by flaviusbuffon** [comment]
Thanks For you Help!
