### ISSUE TITLE
<C-I> jump to next cursor position missing

### ISSUE THREAD

**Issue by TonyWu20** [ayamir/nvimdots#321]
### Neovim version

NVIM v0.8.0 Build type: Release LuaJIT 2.1.0-beta3 Compiled by brew@HMBRW-A-001-M1-004.local  Features: +acl +iconv +tui See ":help feature-compile"     system vimrc file: "$VIM/sysinit.vim"   fall-back for $VIM: "/opt/homebrew/Cellar/neovim/0.8.0/share/nvim"

### Operating system/version

macOS 12.6

### Terminal name/version

wezterm 20220905-102802-7d4b8249

### Branch info

main (Default/Latest)

### How to reproduce the issue

Press <C-I> in normal mode.

### Expected behavior

\<C-I\> and \<C-O\> should be equally important when used to jump between cursor positions. Currently only \<C-O\> works, however, it is extremely uncomfortable as I could not jump forward a position to go back after \<C-O\> once or multiple times.

### Actual behavior

Press \<C-I\> in normal mode will try to fold text instead of jumping to the next cursor position.

### Additional information

I cannot find any mapping related to \<C-I\> and \<C-O\> when I type `:map` and check the whole list.

**Comment by CharlesChiuGit** [comment]
currently only what works?

**Comment by ayamir** [comment]
Yes, it's a BUG. It works after `nmapclear`. I'm currently working on refactoring the set keymap process.

**Comment by ayamir** [comment]
Seems like terminals will escape <C-I> to <Tab>, so I have to remove mapping on <Tab> and <S-Tab>.
