### ISSUE TITLE
[mason-tool-installer] black:failed to install

### ISSUE THREAD

**Issue by Lonjiazeng** [ayamir/nvimdots#324]
我在每次打开nvim后在右边弹出几个信息框，上面的信息如下:

[mason-tool-installer] black:installing
[mason-tool-installer] black:installing
[mason-tool-installer] black:failed to install
[mason-tool-installer] black:failed to install

![Z7CR00NT1S{VD@4 $)8{PR](https://user-images.githubusercontent.com/76612231/202826776-73b45f50-4446-4cf0-8dc4-53c3121af436.png)

根据wiki里的教程，我使用的是ssh来安装和更新插件。  
我是第一次使用nvim，这个是在下载某个插件失败了吗，我应该如何操作来修复这个？

BTW：我想问一下如何在neovide中修改字体大小，我尝试修改了`vim.api.nvim_set_option_value("guifont", "JetBrainsMono Nerd Font:h15", {})`里面`h15`的值，但是并未成功。

**Comment by CharlesChiuGit** [comment]
for black installation error, check #295.

**Comment by Jint-lzxy** [comment]
1. Just as @CharlesChiuGit mentioned, `black` requires a series of `python` dependencies to complete the installation. Make sure you have completed dependencies installation according to #295, and the executable file is located under the `$PATH` environment variable _(i.e., can be accessed directly through typing the command name)_
If you can't accurately troubleshoot the error, try using `python -m pip --disable-pip-version-check install -U black` to install `black` yourself and if the installation fails, you may then provide the error log to us when you need any further help 👍
2. Looks like your system isn't ready to use any [Nerd Font](https://www.nerdfonts.com/), and more specifically, [JetBrainsMono Nerd Font](https://github.com/ryanoasis/nerd-fonts/blob/master/patched-fonts/JetBrainsMono/font-info.md). What is the output of `:set guifont?`? _(p.s., you need to use the "command" mode of vim to see the output. Make sure you're currently in `normal` mode. If not, pressing `ESC` quits from `insert` mode to `normal` mode, where you can press `:` to type in a command.)_ If the font(s) listed in `guifont` are not found, vim will then use the default font, **no matter** how this option is set _(including font size)_. Please install the font correctly [here](https://www.nerdfonts.com/font-downloads) first _([this link](https://github.com/ryanoasis/nerd-fonts/releases/download/v2.2.2/JetBrainsMono.zip) is for JetBrainsMono Nerd Font)_, and then modify the font size. The format is:
```lua
vim.api.nvim_set_option_value("guifont", "your_font_name(may include spaces):hsize(size is a number)", {})
```

**Comment by Lonjiazeng** [comment]
> 2\. Please follow the instructions to install your desired font correctly [here](https://www.nerdfonts.com/font-downloads) first _([this link](https://github.com/ryanoasis/nerd-fonts/releases/download/v2.2.2/JetBrainsMono.zip) is for JetBrainsMono Nerd Font)_, and then modify the font size.

我在windows中安装好链接里的字体后可以正常修改了，感谢。
后续还有一个问题，修改了字体的大小，所有的字体都会变大。是否可以通过某种方式，分别设置不同部分的字体大小（比如代码区域，弹出的提示框等）。因为我修改了字体的大小后弹出的提示框也变得很大，经常弹出的提示框会遮住代码部分，比较影响体验。

**Comment by Lonjiazeng** [comment]
> for black installation error, check #295.

fixed，thanks.

**Comment by Jint-lzxy** [comment]
> > 2. Please follow the instructions to install your desired font correctly [here](https://www.nerdfonts.com/font-downloads) first _([this link](https://github.com/ryanoasis/nerd-fonts/releases/download/v2.2.2/JetBrainsMono.zip) is for JetBrainsMono Nerd Font)_, and then modify the font size.
> 
> 我在windows中安装好链接里的字体后可以正常修改了，感谢。 后续还有一个问题，修改了字体的大小，所有的字体都会变大。是否可以通过某种方式，分别设置不同部分的字体大小（比如代码区域，弹出的提示框等）。因为我修改了字体的大小后弹出的提示框也变得很大，经常弹出的提示框会遮住代码部分，比较影响体验。

@Lonjiazeng There is no better solution at present. AFAIK `neovide` renders text properties using the global table `vim.opt.guifont`. If you change this value, all buffers will be affected. At present, there is no better way to achieve independent text rendering, since vim/neovim is built on a classic terminal model, for `TUI` _(text based user interfaces)_ based rendering, the entire screen must be completely monospaced. There's no way to control the size of the text independently in different parts of the screen. More's the pity. You may see `:h 'guifont'` for more details.

**Comment by Lonjiazeng** [comment]
> There is no better solution at present.

All right, thanks for all.
