### ISSUE TITLE
warning: multiple different client offset_encodings detected for buffer, this is note supported yet

### ISSUE THREAD

**Issue by Lonjiazeng** [ayamir/nvimdots#325]
### Neovim version

NVIM v0.9.0-dev-329+ged27f0e93

### Operating system/version

wsl Ubuntu20.04

### Terminal name/version

WezTerm

### $TERM environment variable

xterm-256color

### Branch info

main (Default/Latest)

### Affected language servers

clangd

### How to reproduce the issue

打开任意一个c文件

### Actual behavior

一直弹出警告框，如下：
![ZBA93GM `%}Q)9LGCUMI@CU](https://user-images.githubusercontent.com/76612231/202848810-dcaa715a-5b50-419e-b452-ba9cc7379ce3.png)

### Expected behavior

能够正确修复，不再弹出类似警告消息。

### Support info

![image](https://user-images.githubusercontent.com/76612231/202848859-8fd7e14c-1afa-4e66-9edd-3ad9a47a8bf9.png)
![image](https://user-images.githubusercontent.com/76612231/202848906-f1b69a5d-7942-4309-b6d5-9f89eb06de37.png)

### Logs

```console
没有在提示路径中找到log文件
```

### Additional information

这是user/config.lua中clangd部分配置：
```lua
function config.lang_c_cpp()
	vim.api.nvim_command([[packadd nvim-lspconfig]])
	vim.api.nvim_command([[packadd lsp_signature.nvim]])
	return require("clangd_extensions").setup({
		server = {
			-- options to pass to nvim-lspconfig
			-- i.e. the arguments to require("lspconfig").clangd.setup({})
			capabilities = { offsetEncoding = "utf-8" },
			cmd = { "clangd" },
			root_pattern = {
				".clangd",
				".clang-tidy",
				".clang-format",
				"compile_commands.json",
				"compile_flags.txt",
				"configure.ac",
				".git",
			},
			single_file_support = true,
		},
		extensions = {
			-- defaults:
			-- Automatically set inlay hints (type hints)
			autoSetHints = true,
			-- These apply to the default ClangdSetInlayHints command
			inlay_hints = {
				-- Only show inlay hints for the current line
				only_current_line = false,
				-- Event which triggers a refersh of the inlay hints.
				-- You can make this "CursorMoved" or "CursorMoved,CursorMovedI" but
				-- not that this may cause  higher CPU usage.
				-- This option is only respected when only_current_line and
				-- autoSetHints both are true.
				only_current_line_autocmd = "CursorHold",
				-- whether to show parameter hints with the inlay hints or not
				show_parameter_hints = true,
				-- prefix for parameter hints
				parameter_hints_prefix = "<- ",
				-- prefix for all the other hints (type, chaining)
				other_hints_prefix = "=> ",
				-- whether to align to the length of the longest line in the file
				max_len_align = false,
				-- padding from the left if max_len_align is true
				max_len_align_padding = 1,
				-- whether to align to the extreme right or not
				right_align = false,
				-- padding from the right if right_align is true
				right_align_padding = 7,
				-- The color of the hints
				highlight = "Comment",
				-- The highlight group priority for extmark
				priority = 100,
			},
			ast = {
				--[[ These are unicode, should be available in any font
                role_icons = {
                    type = "🄣",
                    declaration = "🄓",
                    expression = "🄔",
                    statement = ";",
                    specifier = "🄢",
                    ["template argument"] = "🆃",
                },
                kind_icons = {
                    Compound = "🄲",
                    Recovery = "🅁",
                    TranslationUnit = "🅄",
                    PackExpansion = "🄿",
                    TemplateTypeParm = "🅃",
                    TemplateTemplateParm = "🅃",
                    TemplateParamObject = "🅃",
                },]]
				-- These require codicons (https://github.com/microsoft/vscode-codicons)
				role_icons = {
					type = "",
					declaration = "",
					expression = "",
					specifier = "",
					statement = "",
					["template argument"] = "",
				},

				kind_icons = {
					Compound = "",
					Recovery = "",
					TranslationUnit = "",
					PackExpansion = "",
					TemplateTypeParm = "",
					TemplateTemplateParm = "",
					TemplateParamObject = "",
				},

				highlights = {
					detail = "Comment",
				},
			},
			memory_usage = {
				border = "none",
			},
			symbol_info = {
				border = "none",
			},
		},
	})
end
```

这是user/plugins.lua
```lua
lang["p00f/clangd_extensions.nvim"] = {
	opt = true,
	ft = {
		"c",
		"c++",
		"cpp",
	},
	capabilities = { offsetEncoding = "utf-8" },
	cmd = { "clangd" },
	root_pattern = {
		".clangd",
		".clang-tidy",
		".clang-format",
		"compile_commands.json",
		"compile_flags.txt",
		"configure.ac",
		".git",
	},
	single_file_support = true,
	config = conf.lang_c_cpp,
}
```

**Comment by CharlesChiuGit** [comment]
There's already a clangd setting, did u disable it?

**Comment by ayamir** [comment]
set `capabilities = { offsetEncoding = "utf-16" }` will be fine.
This have been set at here: https://github.com/ayamir/nvimdots/blob/main/lua/modules/completion/lsp.lua#L112

**Comment by Jint-lzxy** [comment]
We have _(and you probably should have)_ configured all language servers [here](https://github.com/ayamir/nvimdots/blob/4a066829f5f2caea30ed60e46ffb046604c85c12/lua/modules/completion/lsp.lua#L108). If you really _intended_ to use this plugin, please delete [these lines](https://github.com/ayamir/nvimdots/blob/4a066829f5f2caea30ed60e46ffb046604c85c12/lua/modules/completion/lsp.lua#L108-L148) and move the options you need to:
```lua
require("clangd_extensions").setup({
    server = {
        -- options to pass to nvim-lspconfig
    },
    -- ... --
})
```
 _(otherwise all the options will be set again - this is currently not allowed. See [clangd_extensions.nvim#configuration](https://github.com/p00f/clangd_extensions.nvim#configuration))_:

However, it is not recommended to use separate plugins to configure any native LSP. The built-in settings can already satisfy most of the features provided by this plugin, installing another version in parallel can cause all kinds of trouble. You might want to see [the wiki](https://github.com/ayamir/nvimdots/wiki/Keybindings).

**Comment by Lonjiazeng** [comment]
> We have _(and you should have)_ configured all language servers [here](https://github.com/ayamir/nvimdots/blob/4a066829f5f2caea30ed60e46ffb046604c85c12/lua/modules/completion/lsp.lua#L108). If you really _intended_ to use this plugin, please delete [these lines](https://github.com/ayamir/nvimdots/blob/4a066829f5f2caea30ed60e46ffb046604c85c12/lua/modules/completion/lsp.lua#L108-L148) and move the options you need to

所以只有在这个文件里没有相关的配置时我才需要新建一个user文件来配置对吗？

**Comment by CharlesChiuGit** [comment]
mostly ys.

**Comment by Lonjiazeng** [comment]
那我是应该添加在completion文件夹中，还是lang文件夹，也许是我没理解透，这两个文件夹在wiki中的描述让我有些困惑

**Comment by Lonjiazeng** [comment]
那我是应该添加在completion文件夹中，还是lang文件夹，也许是我没理解透，这两个文件夹在wiki中的描述让我有些困惑

**Comment by CharlesChiuGit** [comment]
It's fine no matter where u put it, both will work. Follow your heart.🙂

**Comment by Lonjiazeng** [comment]
好的，感谢解答

**Comment by Jint-lzxy** [comment]
> 那我是应该添加在completion文件夹中，还是lang文件夹，也许是我没理解透，这两个文件夹在wiki中的描述让我有些困惑

This is an enhancement only for `clangd`, so as described in wiki, it is recommended to put the settings for **specific languages** in the `lang` folder. But plugins can work normally wherever they are placed 👍 This is just a convention.

**Comment by Lonjiazeng** [comment]
> This is an enhancement only for `clangd`, so as described in wiki, it is recommended to put the settings for **specific languages** in the `lang` folder. But plugins can work normally wherever they are placed 👍 Just a convention.

Thank you for the detailed answer.
