### ISSUE TITLE
CentOS7 安装后 scheme 无法保存

### ISSUE THREAD

**Issue by goodpaperman** [ayamir/nvimdots#327]
### Neovim version

NVIM v0.8.1 Build type: RelWithDebInfo LuaJIT 2.1.0-beta3

### Operating system/version

CentOS Linux release 7.9.2009 (Core)

### Terminal name/version

GNU bash, version 4.2.46

### $TERM environment variable

xterm-256color

### Branch info

main (Default/Latest)

### How to reproduce the issue

see detail

### Expected behavior

see detail

### Actual behavior

selected scheme not saved:

<img width="1411" alt="图片" src="https://user-images.githubusercontent.com/8522640/204069781-37abe292-22a1-44c1-aadb-17efcdc02255.png">

### Additional information

系统已安装 sqlite3：

```
$ ls -lh /lib64/libsqlite*
lrwxrwxrwx 1 root root   19 Nov 18 11:18 /lib64/libsqlite3.so.0 -> libsqlite3.so.0.8.6
-rwxr-xr-x 1 root root 736K Jan 28  2020 /lib64/libsqlite3.so.0.8.6
```

**Comment by CharlesChiuGit** [comment]
Did u use `luarocks` to install sqlite?

**Comment by goodpaperman** [comment]
没有，头一次听说这个。安装了 luarocks 后安装 sqlite，报错：

```
$ sudo luarocks install sqlite
Installing https://luarocks.org/sqlite-v1.2.2-0.src.rock...
Using https://luarocks.org/sqlite-v1.2.2-0.src.rock... switching to 'build' mode

Error: /tmp/luarocks_sqlite-v1.2.2-0-6636/sqlite-v1.2.2-0.rockspec: Unknown field test_dependencies
```

**Comment by goodpaperman** [comment]
换 sqlite3 试试：
```
$ sudo luarocks install sqlite3
Installing https://luarocks.org/sqlite3-0.4.1.1-1.src.rock...
Using https://luarocks.org/sqlite3-0.4.1.1-1.src.rock... switching to 'build' mode

Error: Could not find header file for SQLITE
  No file sqlite3.h in /usr/local/include
  No file sqlite3.h in /usr/include
You may have to install SQLITE in your system and/or pass SQLITE_DIR or SQLITE_INCDIR to the luarocks command.
Example: luarocks install sqlite3 SQLITE_DIR=/usr/local
```

**Comment by CharlesChiuGit** [comment]
https://github.com/kkharji/sqlite.lua#linux
```sh
sudo pacman -S sqlite # Arch
sudo apt-get install sqlite3 libsqlite3-dev # Ubuntu
```
我沒用過centos 但也許也需要裝相關dev pkg?

**Comment by ayamir** [comment]
注意你`ls`列出的是`libsqlite3.so.0`，并不是`libsqlite3.so`，有两种解决办法：
1. 手动设置：`let g:sqlite_clib_path = '/lib64/libsqlite3.so.0'`
2. 创建一个`libsqlite3.so`的软链接：`sudo ln -s /lib64/libsqlite3.so.0 /lib64/libsqlite3.so`

**Comment by goodpaperman** [comment]
参考 centos7 上升级 sqlite 的[文章](https://zhuanlan.zhihu.com/p/110743704)搞定了:
sudo yum install sqlite-devel

但是选择了 scheme 后没有保存，重启 nvim 仍是原来的默认主题

**Comment by CharlesChiuGit** [comment]
@goodpaperman 建議新的問題要重新開一個issue 也把原本的標題改回來比較好 方便以後的人查詢

**Comment by CharlesChiuGit** [comment]
另外選擇了color scheme是甚麼意思 你有在 
https://github.com/ayamir/nvimdots/blob/6ceaedf561c5c4495ecb618f6ef1953dec7d5fcd/lua/core/init.lua#L133
設定後跑packercompile嗎

**Comment by ayamir** [comment]
> 参考 centos7 上升级 sqlite 的[文章](https://zhuanlan.zhihu.com/p/110743704)搞定了: sudo yum install sqlite-devel
> 
> 但是选择了 scheme 后没有保存，重启 nvim 仍是原来的默认主题

用telescope修改的主题无法保存，正确的方式是修改`lua/core/init.lua`中的这一行：
https://github.com/ayamir/nvimdots/blob/6ceaedf561c5c4495ecb618f6ef1953dec7d5fcd/lua/core/init.lua#L133

**Comment by goodpaperman** [comment]
<img width="949" alt="图片" src="https://user-images.githubusercontent.com/8522640/204123700-eef7336e-a88a-4276-9df7-46962666a203.png">

在启动界面这个地方更新了选择，再重新启动 nvim 没有生效，还是老的绿色界面

**Comment by goodpaperman** [comment]
> > 参考 centos7 上升级 sqlite 的[文章](https://zhuanlan.zhihu.com/p/110743704)搞定了: sudo yum install sqlite-devel
> > 但是选择了 scheme 后没有保存，重启 nvim 仍是原来的默认主题
> 
> 用telescope修改的主题无法保存，正确的方式是修改`lua/core/init.lua`中的这一行：
> 
> https://github.com/ayamir/nvimdots/blob/6ceaedf561c5c4495ecb618f6ef1953dec7d5fcd/lua/core/init.lua#L133

好的，我试下

**Comment by goodpaperman** [comment]
起作用了，tks
