### ISSUE TITLE
Mason没有加载出来

### ISSUE THREAD

**Issue by Lonjiazeng** [ayamir/nvimdots#329]
### Neovim version

NVIM v0.9.0-dev-329+ged27f0e93

### Operating system/version

wsl Ubuntu20.04

### Terminal name/version

WezTerm

### $TERM environment variable

xterm-256color

### Branch info

main (Default/Latest)

### How to reproduce the issue

1. 打开neovide或者nvim
2. 使用快捷键<Leader>ps
3. 输入命令`:Mason`

### Expected behavior

1. 能够更新插件
2. 能够通过`:Mason`命令查看lsp安装情况

### Actual behavior

1. 无法正确更新插件
![%@@1H4XY26)R TTVI G~RDK](https://user-images.githubusercontent.com/76612231/204076903-cf647fbf-50ff-43a0-88ac-970316532d98.png)
2. 无法使用`:Mason`命令
![} 1@WF~Q 1A8L38`3~18ITH](https://user-images.githubusercontent.com/76612231/204076943-96a144c3-d6e1-49f9-b73b-35026c9bac4c.png)

***注：在可以使用`:Mason`命令时是可以正常更新插件的，我觉得这两个应该是同一个问题***

**Comment by ayamir** [comment]
So how you install `nvimdots`? Which way do you use to update plugins? `ssh` or `http`?
If you can't bypass the GFW, please use `ssh` to update plugins.

**Comment by Lonjiazeng** [comment]
> So how you install `nvimdots`? Which way do you use to update plugins? `ssh` or `http`

yes, I installed it and used ssh for updating plugins. Command `:Mason` works sometime.

**Comment by CharlesChiuGit** [comment]
try https, it works better in my case. also remember to change ssh setting in core/settings.lua

**Comment by Lonjiazeng** [comment]
> try https

I used https, it didn't work, then I use ssh. But it seems to don't work now🤔

**Comment by ayamir** [comment]
It only requires your network condition, i.e. whether you can access github normally in your shell env.

**Comment by ayamir** [comment]
Your can also change packer config on your own, like this:
https://github.com/ayamir/nvimdots/issues/49#issue-1065953875

**Comment by Lonjiazeng** [comment]
> move your cursor the corresponding line, and hit enter

No response after pressing enter
![image](https://user-images.githubusercontent.com/76612231/204080165-2d482847-454e-43ad-9b38-5a0575706e26.png)

**Comment by Lonjiazeng** [comment]
> whether you can access github normally in your shell env

I tried `ping github.com` and `git clone <some-repo>`. It's weird that `ping` didn't work but `git clone` worked.

**Comment by ayamir** [comment]
Seems like ssh key error, follow this: https://github.com/ayamir/nvimdots/wiki/Prerequisites#ssh-key-configuration-for-github-optional

**Comment by Lonjiazeng** [comment]
> Seems like ssh key error, follow this

I had set it at first, so I think it's not the point.
![image](https://user-images.githubusercontent.com/76612231/204091256-8dd96dbb-9012-4606-aac6-b10ecebf521c.png)

**Comment by ayamir** [comment]
So it belongs to the issues of `ssh`.
check them:
+ https://stackoverflow.com/questions/67000681/kex-exchange-identification-connection-closed-by-remote-host
+ https://serverfault.com/questions/1015547/what-causes-ssh-error-kex-exchange-identification-connection-closed-by-remote
+ https://blog.51cto.com/86net/2452445

**Comment by Lonjiazeng** [comment]
> So it belongs to the issues of `ssh`.

I see, so whether the command `Mason` related to this ?

**Comment by Lonjiazeng** [comment]
> I see, so whether the command `Mason` related to this ?

I checked my shell to ssh to github.com.

![image](https://user-images.githubusercontent.com/76612231/204117323-3241f9d6-fdfa-4238-a043-0d7329ec960d.png)

Then I used command `<leader>ps` to update, it worked.

But I can't use command `:Mason`.

**Comment by ayamir** [comment]
> > So it belongs to the issues of `ssh`.
> 
> I see, so whether the command `:Mason` related to this ?

You'd better make all of plugins installed

**Comment by Lonjiazeng** [comment]
> You'd better make all of plugins installed

You mean I have not installed Mason?  I can use it before.

I use [the script](https://github.com/ayamir/nvimdots/wiki/Prerequisites#:~:text=bash%20%2Dc%20%22%24(curl%20%2DfsSL%20https%3A//raw.githubusercontent.com/ayamir/nvimdots/HEAD/install/install.sh)%22) to install this project. What should I do to install all of the plugins I'd better install and how should I know all the plugins I need have installed ?

**Comment by ayamir** [comment]
OK, did you try executing `:Mason` in the dashboard? It can't be found unless you begin to edit a file.

**Comment by Lonjiazeng** [comment]
> It can't be found unless you begin to edit a file.

I see, thx
