### ISSUE TITLE
Lua Config Error

### ISSUE THREAD

**Issue by arcthur** [ayamir/nvimdots#336]
### Neovim version

NVIM 0.8.1

### Operating system/version

macOS 13.0.1

### Terminal name/version

iTerm2 Build 3.4.18

### $TERM environment variable

xterm-256color

### Branch info

main (Default/Latest)

### Fetch Preferences

HTTPS (use_ssh = false)

### How to reproduce the issue

when i open the any file will be opened the error message

### Expected behavior

![image](https://user-images.githubusercontent.com/322331/204141252-52c444e7-5f4f-48ad-94b8-81e19579a720.png)

**Comment by ayamir** [comment]
Have you finished the installation? Show me the output of `:checkhealth` please.

**Comment by arcthur** [comment]
I solved by update libraries just now.
