### ISSUE TITLE
gd/D 不能跳转到定义

### ISSUE THREAD

**Issue by goodpaperman** [ayamir/nvimdots#337]
### Neovim version

NVIM v0.8.1 Build type: RelWithDebInfo LuaJIT 2.1.0-beta3

### Operating system/version

CentOS Linux release 7.9.2009 (Core)

### Terminal name/version

GNU bash, version 4.2.46

### $TERM environment variable

xterm-256color

### Branch info

main (Default/Latest)

### Fetch Preferences

SSH (use_ssh = true)

### How to reproduce the issue

gD on function

### Expected behavior

jump to function definition

### Actual behavior

popup an error

<img width="756" alt="图片" src="https://user-images.githubusercontent.com/8522640/204183539-9f76a231-e1a9-4115-ade5-396f819ce8b3.png">

### Additional information

efm-langserver installed already

**Comment by ayamir** [comment]
what's the type of the file? `efm` only provide format/lint function. You need to use `:Mason` to install lsp on your own.
https://github.com/ayamir/nvimdots/wiki/Prerequisites#tools-for-plugins

**Comment by goodpaperman** [comment]
mason show following errors：

<img width="804" alt="图片" src="https://user-images.githubusercontent.com/8522640/204223335-070aea2d-2515-4d21-913d-5e7f9dca7600.png">

<img width="806" alt="图片" src="https://user-images.githubusercontent.com/8522640/204221338-c3a6a4dc-dcaa-4b22-92c5-351363886274.png">

wget version:
```
$ wget --version
GNU Wget 1.14 built on linux-gnu.

+digest +https +ipv6 +iri +large-file +nls +ntlm +opie +ssl/openssl 

Wgetrc: 
    /etc/wgetrc (system)
Locale: /usr/share/locale 
Compile: gcc -DHAVE_CONFIG_H -DSYSTEM_WGETRC="/etc/wgetrc" 
    -DLOCALEDIR="/usr/share/locale" -I. -I../lib -I../lib -O2 -g -pipe 
    -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong 
    --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic 
Link: gcc -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions 
    -fstack-protector-strong --param=ssp-buffer-size=4 
    -grecord-gcc-switches -m64 -mtune=generic -lssl -lcrypto 
    /usr/lib64/libssl.so /usr/lib64/libcrypto.so /usr/lib64/libz.so 
    -ldl -lz -lz -lidn -luuid -lpcre ftp-opie.o openssl.o http-ntlm.o 
    ../lib/libgnu.a 

Copyright (C) 2011 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later
<http://www.gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Originally written by Hrvoje Niksic <hniksic@xemacs.org>.
Please send bug reports and questions to <bug-wget@gnu.org>.
```

need update?

**Comment by ayamir** [comment]
obviously you need a higher version `wget`

**Comment by goodpaperman** [comment]
upgrade wget to  1.21, lua-lang-server download & install ok, but clangd still failed:

<img width="989" alt="图片" src="https://user-images.githubusercontent.com/8522640/204424202-65d9681b-cfc0-45a1-ba25-220da288175b.png">

can I pre-download this package and putting it to the right place ?

**Comment by ayamir** [comment]
Maybe, the download destination is here.
![image](https://user-images.githubusercontent.com/61657399/204430062-3b6a667a-f066-4127-a510-e217ed1431c3.png)

**Comment by goodpaperman** [comment]
it works:

<img width="677" alt="图片" src="https://user-images.githubusercontent.com/8522640/204462286-81d59a2e-d791-4e9b-9d25-8d3bebb9257f.png">

mason now has only 1 problem: MasonInstall clang-format failed, see detail above

**Comment by CharlesChiuGit** [comment]
pip3 install wheel

**Comment by goodpaperman** [comment]
no effect:
<img width="1106" alt="图片" src="https://user-images.githubusercontent.com/8522640/204465352-a6d45fe4-82c4-4d77-9636-70a32ca19e5a.png">

<img width="1099" alt="图片" src="https://user-images.githubusercontent.com/8522640/204465368-95f6e802-8429-4825-9b12-8ff3be00559a.png">

**Comment by goodpaperman** [comment]
upgrade python 3.6.8 to 3.8，module wheel can find now， but compile still  failed:

file:///Users/yunhai01/Library/Caches/BaiduMacHi/Share/images/96e1d6995ee3ac6f5a5374c506428dff.png

**Comment by ayamir** [comment]
maybe you can install `clang-format` manually too...

**Comment by goodpaperman** [comment]
from error message:
"Host  GCC version must be at least 5.1, your version is 4.8.5"

it seems gcc need a upgrade, that is a big project, can I indicate a lower version of clang-format to walk aroud gcc upgrade ?

**Comment by ayamir** [comment]
try just download binaraies [here](https://github.com/muttleyxd/clang-tools-static-binaries/releases/tag/master-1d7ec53d)

**Comment by goodpaperman** [comment]
clang-format runs ok:
<img width="1017" alt="图片" src="https://user-images.githubusercontent.com/8522640/205019725-5ddaea42-20e3-4abd-b3fe-1ca753929137.png">

and installed ok after restart nvim:
<img width="750" alt="图片" src="https://user-images.githubusercontent.com/8522640/205050957-b4bffd52-92c1-448d-82bb-dfe149f8269e.png">
