### ISSUE TITLE
Ability to edit large files

### ISSUE THREAD

**Issue by EternalChildren** [ayamir/nvimdots#338]
### Neovim version

NVIM v0.8.0 LuaJIT 2.1.0-beta3

### Operating system/version

Centos8

### Terminal name/version

iterm2

### Branch info

main (Default/Latest)

### Fetch Preferences

SSH (use_ssh = true)

### How to reproduce the issue

当我打开一个大小为41M的日志文件的时候就会卡住很久，而且打开完成后对这个文件进行操作的时候也非常卡顿，想请教下大佬该如何解决这个问题

用--startuptime 打开日志的报告
====================================
times in msec
 clock   self+sourced   self:  sourced script
 clock   elapsed:              other lines

000.006  000.006: --- NVIM STARTING ---
000.088  000.082: event init
000.176  000.088: early init
000.327  000.151: locale set
000.358  000.031: init first window
000.605  000.247: inits 1
000.613  000.008: window checked
000.616  000.003: parsing arguments
000.981  000.055  000.055: require('vim.shared')
001.069  000.039  000.039: require('vim._meta')
001.070  000.087  000.048: require('vim._editor')
001.072  000.167  000.025: require('vim._init_packages')
001.073  000.291: init lua interpreter
001.115  000.042: expanding arguments
001.156  000.041: inits 2
001.479  000.323: init highlight
001.480  000.001: waiting for UI
002.212  000.732: done waiting for UI
002.232  000.019: init screen for UI
002.381  000.149: init default mappings
002.399  000.018: init default autocommands
002.933  000.055  000.055: sourcing /usr/share/nvim/runtime/ftplugin.vim
003.036  000.029  000.029: sourcing /usr/share/nvim/runtime/indent.vim
003.087  000.026  000.026: sourcing $VIM/sysinit.vim
003.619  000.060  000.060: require('core.global')
003.746  000.018  000.018: require('core.settings')
003.750  000.128  000.109: require('core.pack')
004.065  000.270  000.270: require('core.options')
004.182  000.062  000.062: require('keymap.bind')
004.290  000.222  000.160: require('core.mapping')
004.466  000.033  000.033: require('keymap.config')
004.892  000.601  000.568: require('keymap')
005.186  000.293  000.293: require('core.event')
006.595  000.518  000.518: require('catppuccin')
006.974  000.080  000.080: require('catppuccin.lib.hashing')
008.309  000.093  000.093: require('mason-core.functional')
008.371  000.057  000.057: require('mason-core.path')
008.448  000.076  000.076: require('mason.settings')
008.716  000.042  000.042: require('mason-core.functional.data')
008.719  000.119  000.077: require('mason-core.functional.function')
008.772  000.042  000.042: require('mason-core.functional.relation')
008.838  000.062  000.062: require('mason-core.functional.logic')
008.850  000.401  000.178: require('mason-core.platform')
008.865  000.793  000.166: require('mason-core.log')
009.129  000.152  000.152: require('mason-core.async')
009.171  000.041  000.041: require('mason-core.async.uv')
009.175  000.309  000.117: require('mason-core.fs')
009.252  000.075  000.075: require('mason-core.optional')
009.319  000.066  000.066: require('mason-core.EventEmitter')
009.471  000.151  000.151: require('mason-registry.index')
009.592  000.119  000.119: require('mason-core.functional.list')
009.597  001.617  000.104: require('mason-registry')
009.600  001.779  000.162: require('mason-tool-installer')
010.164  000.069  000.069: require('notify.util.queue')
010.166  000.201  000.133: require('notify.util')
010.315  000.147  000.147: require('notify.config.highlights')
010.318  000.480  000.131: require('notify.config')
010.369  000.049  000.049: require('notify.stages')
010.470  000.101  000.101: require('notify.service.notification')
010.870  000.084  000.084: require('notify.animate.spring')
010.872  000.143  000.059: require('notify.animate')
010.876  000.404  000.261: require('notify.windows')
011.296  000.167  000.167: require('notify.service.buffer.highlights')
011.299  000.308  000.142: require('notify.service.buffer')
011.301  000.424  000.115: require('notify.service')
011.480  000.177  000.177: require('notify.stages.util')
011.484  001.860  000.225: require('notify')
011.597  000.111  000.111: require('modules.ui.icons')
011.735  000.104  000.104: require('notify.stages.slide')
012.063  000.296  000.296: require('nvim_comment')
012.735  000.089  000.089: sourcing /home/zzz/.local/share/nvim/site/pack/packer/opt/vim-go/ftdetect/gofiletype.vim
012.795  000.017  000.017: sourcing /home/zzz/.local/share/nvim/site/pack/packer/opt/csv.vim/ftdetect/csv.vim
012.801  007.600  002.747: require('_compiled')
013.624  000.766  000.766: sourcing /home/zzz/.local/share/nvim/site/pack/packer/start/catppuccin/colors/catppuccin.vim
013.699  010.578  000.638: require('core')
013.722  010.621  000.044: sourcing /home/zzz/.config/nvim/init.lua
013.731  000.601: sourcing vimrc file(s)
014.062  000.017  000.017: sourcing /usr/share/vim/vimfiles/ftdetect/stp.vim
014.167  000.318  000.300: sourcing /usr/share/nvim/runtime/filetype.lua
014.192  000.013  000.013: sourcing /usr/share/nvim/runtime/filetype.vim
014.399  000.105  000.105: sourcing /usr/share/nvim/runtime/syntax/synload.vim
014.494  000.278  000.172: sourcing /usr/share/nvim/runtime/syntax/syntax.vim
014.979  000.013  000.013: sourcing /usr/share/nvim/runtime/plugin/gzip.vim
014.995  000.007  000.007: sourcing /usr/share/nvim/runtime/plugin/health.vim
015.012  000.009  000.009: sourcing /usr/share/nvim/runtime/plugin/matchit.vim
015.027  000.008  000.008: sourcing /usr/share/nvim/runtime/plugin/matchparen.vim
015.050  000.016  000.016: sourcing /usr/share/nvim/runtime/plugin/netrwPlugin.vim
015.187  000.007  000.007: sourcing /home/zzz/.local/share/nvim/rplugin.vim
015.193  000.135  000.128: sourcing /usr/share/nvim/runtime/plugin/rplugin.vim
015.274  000.073  000.073: sourcing /usr/share/nvim/runtime/plugin/shada.vim
015.293  000.007  000.007: sourcing /usr/share/nvim/runtime/plugin/spellfile.vim
015.318  000.013  000.013: sourcing /usr/share/nvim/runtime/plugin/tarPlugin.vim
015.336  000.008  000.008: sourcing /usr/share/nvim/runtime/plugin/tohtml.vim
015.362  000.016  000.016: sourcing /usr/share/nvim/runtime/plugin/tutor.vim
015.387  000.014  000.014: sourcing /usr/share/nvim/runtime/plugin/zipPlugin.vim
015.606  000.064  000.064: sourcing /usr/share/nvim/runtime/plugin/man.lua
015.628  000.907: loading rtp plugins
015.934  000.028  000.028: sourcing /home/zzz/.local/share/nvim/site/pack/packer/start/mason-tool-installer.nvim/plugin/mason-tool-installer.lua
016.121  000.041  000.041: sourcing /home/zzz/.local/share/nvim/site/pack/packer/start/nvim-web-devicons/plugin/nvim-web-devicons.vim
016.221  000.034  000.034: sourcing /home/zzz/.local/share/nvim/site/pack/packer/start/plenary.nvim/plugin/plenary.vim
016.307  000.575: loading packages
016.784  000.477: loading after plugins
016.796  000.013: inits 3
017.131  000.334: reading ShaDa
017.539  000.226  000.226: require('packer.load')
018.656  000.006  000.006: require('vim.F')
018.666  000.977  000.971: require('alpha')
018.773  000.105  000.105: require('alpha.themes.dashboard')
019.701  000.068  000.068: require('accelerated-jk.config')
019.706  000.684  000.616: require('accelerated-jk')
019.822  000.089  000.089: require('accelerated-jk.time_driven')
019.871  000.886  000.113: sourcing /home/zzz/.local/share/nvim/site/pack/packer/opt/accelerated-jk.nvim/plugin/accelerated-jk.vim
019.981  000.656: opening buffers
020.011  000.029: BufEnter autocommands
020.013  000.002: editing files in windows
020.199  000.063  000.063: sourcing /home/zzz/.local/share/nvim/site/pack/packer/opt/copilot.lua/plugin/copilot.lua
021.249  000.112  000.112: require('copilot_cmp.format')
021.254  000.267  000.155: require('copilot_cmp.source')
021.255  000.888  000.622: require('copilot_cmp')
021.314  000.006  000.006: require('vim.keymap')
023.357  002.387: VimEnter autocommands
024.430  000.060  000.060: require('toggleterm.lazy')
024.484  000.050  000.050: require('toggleterm.constants')
024.834  000.348  000.348: require('toggleterm.terminal')
024.840  001.313  000.856: require('toggleterm')
025.067  000.106  000.106: require('toggleterm.colors')
025.173  000.104  000.104: require('toggleterm.utils')
025.177  000.332  000.122: require('toggleterm.config')
025.375  000.143  000.143: require('toggleterm.commandline')
025.424  000.279: UIEnter autocommands
025.870  000.347  000.347: sourcing /usr/share/nvim/runtime/autoload/provider/clipboard.vim
025.876  000.104: before starting main loop
026.062  000.022  000.022: sourcing /home/zzz/.local/share/nvim/site/pack/packer/opt/specs.nvim/plugin/specs.vim
026.912  000.737  000.737: require('specs')
027.214  000.152  000.152: sourcing /home/zzz/.local/share/nvim/site/pack/packer/opt/vim-cool/plugin/cool.vim
028.761  001.975: first screen update
028.781  000.020: --- NVIM STARTED ---

### Expected behavior

即时打开，对文件操作不卡顿

**Comment by ayamir** [comment]
First of all, it's not a bug, but a enhancemen. It's a tough issue because you know large file natively requires much more time to load plugins and make them work than small file. For mainstream IDEs like [IntelliJ IDEA](https://www.jetbrains.com/idea/) or [Visual Studio](https://visualstudio.microsoft.com), they will do these jobs in the background after entering the edit interface.
I have no ideas how to solve it temprarily. A ideal solution is load plugins and their functions in the background, but I'm not the author of the plugins so my ability is limited.

**Comment by Deg2v** [comment]
Nvim itself has some options like `--clean` and `--noplugin`.
Can nvim be configured to skip loading some or all plugins when opening large files?  Some large files do not need plugins.

**Comment by EternalChildren** [comment]
> Nvim itself has some options like `--clean` and `--noplugin`. Can nvim be configured to skip loading some or all plugins when opening large files? Some large files do not need plugins.

--noplugin the command work great ,
how can i set it in config file. make it work when i open .log or no suffix file

**Comment by Jint-lzxy** [comment]
@EternalChildren At present, there is no way to disable user configs based on filetype/suffix **after** nvim has been loaded _(i.e., in the config file)_, because not all plugins support disabling itself in the current buffer through `autocmd` _(in addition, controlling how plugins are loaded based on filesize **manually** will also lead to many additional loops and unnecessary code)_. Meanwhile, it's currently not possible to _"disable"_ all user configs in a specific buffer - in this way, the entire `neovim` instance will be affected.

An alternative is to check the file size **before** entering nvim and loading user settings. We may stop loading configs when the file is too large. This is the same as passing `-u NONE` _(Note: Any file opened in this nvim instance will not share any user configs, you may use `:lua require("core")` to load the config manually **\[this is irreversible\]**)_.

Code: _(probably not the most efficient one, just for reference only)_
```lua
--- init.lua
if not vim.g.vscode then
	local max_filesize = 10 * 1024 * 1024 -- 10 MB
	local ok, stats = pcall(vim.loop.fs_stat, vim.api.nvim_buf_get_name(vim.api.nvim_get_current_buf()))
	if ok and (stats == nil or stats.size < max_filesize) then
		require("core")
	end
end
```

However, @ayamir we _may_ write `autocmd`s to disable certain plugins that would apply extensive changes on large files to achieve the same goal. After some rough investigations, the plugins known to affect performance are _(with solutions if possible)_:
```lua
vim.api.nvim_command([[
TSBufDisable highlight   " Treesitter
syntax off               " Native syntax
syntax clear             " Cache
IlluminatePauseBuf       " Illuminate
IndentBlanklineDisable   " Indent-blankline
NoMatchParen             " Matchup
]])
```
We can then solve this problem by modifying `event.lua`. IMO this should be the most appropriate solution _(but also takes some time to complete)_ 👍

**Comment by ayamir** [comment]
A clean way also can be just load options but don't load any plugins like this:
```lua
local load_core = function()
	local pack = require("core.pack")
	createdir()
	disable_distribution_plugins()
	leader_map()

	pack.ensure_plugins()
	neovide_config()
	clipboard_config()

	require("core.options")
	require("core.mapping")
	require("core.event")

	if not large_file then
            require("keymap")
	    pack.load_compile()
        end
	-- vim.api.nvim_command([[set background=light]])
	vim.api.nvim_command([[colorscheme catppuccin]])
end

load_core()
```

**Comment by ayamir** [comment]
> maybe we can have a table of "disabled plugins" to filter heavy plugins in that if statement?

It is feasible because `packer` provide the `cond` function to handle complex load logic.

**Comment by Jint-lzxy** [comment]
> maybe we can have a table of "disabled plugins" to filter heavy plugins in that if statement?

@CharlesChiuGit This might not be the _best_ solution. In this case, other files in the same `neovim` instance will not be able to use these plugins.

**Comment by CharlesChiuGit** [comment]
such mechanism could be also helpful when debugging plugin-related errors?

**Comment by CharlesChiuGit** [comment]
> @CharlesChiuGit This might not be the _best_ solution. In this case, other files in the same `neovim` instance will not be able to use these plugins.

hmm, that's true...

**Comment by CharlesChiuGit** [comment]
does neovim have some daemon mechanism like emacs?

**Comment by Jint-lzxy** [comment]
> ~~ does neovim have some daemon/rpc mechanism like emacs? ~~

Neovim could be started as a daemon with `--headless` mode.

`man nvim`:
```console
--headless  Do not start a UI.  When supplied with --embed this implies that
            the embedding application does not intend to (immediately) start
            a UI.  Also useful for "scraping" messages in a pipe.
            :help --headless
```
What's the point of this?

**Comment by ayamir** [comment]
Another problem is hot-plug plugin load when I try to open a big file after a normal file opened.

**Comment by CharlesChiuGit** [comment]
true that

**Comment by EternalChildren** [comment]
I'm trying to detect large files to prevent loading core in init.lua.  It works when I open the file directly.  but it should only be used as a temporary workaround.
hope that in the future, it will be possible to avoid time-consuming plugs when opening large files at any time.

**Comment by Jint-lzxy** [comment]
Yep this has been incorporated into our plan, and we will complete the update in the near future 👍

**Comment by ClSlaid** [comment]
This is not a likely daily workload for most IDE users. As I knew, for IDEs like IntelliJ, most features even syntax highlighting would have to be disabled when opening large files.

Bare Vim/Neovim maybe capable for such workload, but plugins used in this project may be unable to undertake such heavy workload.

I'd like to recommend the [Log Navigator](https://lnav.org/) project. It's well optimized and wrapped up with basic highlighting, searching and editing abilities.

**Comment by CharlesChiuGit** [comment]
I love use lnav as well!

**Comment by Jint-lzxy** [comment]
#394 should fix this issue 👍
