### ISSUE TITLE
Lua does not get correct HOME path on Windows 11

### ISSUE THREAD

**Issue by stdgeodesic** [ayamir/nvimdots#34]
In `lua/core/global.lua:2`:

```lua
local home = os.getenv("HOME")
```

On modern Windows (and PowerShell Core 7, I'm not sure about the exact version numbers of Windows/PowerShell that are affected by this issue), the `home` variable will get a `nil` value. This will cause the following error:

![image](https://user-images.githubusercontent.com/8758566/135089045-15d5e8ba-b205-4af4-8b33-bf3e063b8543.png)

However, we can get the home path by reading `HOMEDRIVE` `HOMEPATH` or `USERPROFILE`, e.g.:

```lua
local home = os.getenv("USERPROFILE")  -- this works for me
```

The corresponding environment variables in PoweShell are
`$env:HOMEDRIVE`, `$env:HOMEPATH` and `$env:USERPROFILE`. 

`$env:HOME` in PowerShell is an empty value by default.

**Comment by ayamir** [comment]
```lua
local home = os.getenv("USERPROFILE")  -- this works for me
```
Does it works for Window10 too? I'm sorry because I have also upgrade to Windows11 but I use neovim in WSL2 on Windows.

**Comment by stdgeodesic** [comment]
> Does it works for Window10 too? I'm sorry because I have also upgraded to Windows11 but I use neovim in WSL2 on Windows.

Yes. It also works for Windows 10. (Although not all the plugins are compatible with Windows)

When executing from PowerShell, the default behavior of the lua script

```lua
os.getenv("VAR")
```

seems to be searching in `$env:` for "VAR", i.e., `$env:VAR` **instead of** `$VAR`/`$variable:VAR`

Assuming that my home directory is `C:\Users\user_name`, the values of the mentioned variables are as follows:

```pwsh
$env:HOMEDRIVE  # C:
$env:HOMEPATH  # \Users\user_name
$env:USERPROFILE  # C:\Users\user_name
$env:HOME  # non-exist
$HOME  # C:\Users\user_name
$variable:HOME  # same as $HOME
```

As a result, `os.getenv("HOME")` will return `nil`.

**Comment by 1096015776** [comment]
it just a path var,maybe you can setting,or let home = your path string

**Comment by ayamir** [comment]
> > Does it works for Window10 too? I'm sorry because I have also upgraded to Windows11 but I use neovim in WSL2 on Windows.
> 
> Yes. It also works for Windows 10. (Although not all the plugins are compatible with Windows)
> 
> When executing from PowerShell, the default behavior of the lua script
> 
> ```lua
> os.getenv("VAR")
> ```
> 
> seems to be searching in `$env:` for "VAR", i.e., `$env:VAR` **instead of** `$VAR`/`$variable:VAR`
> 
> Assuming that my home directory is `C:\Users\user_name`, the values of the mentioned variables are as follows:
> 
> ```powershell
> $env:HOMEDRIVE  # C:
> $env:HOMEPATH  # \Users\user_name
> $env:USERPROFILE  # C:\Users\user_name
> $env:HOME  # non-exist
> $HOME  # C:\Users\user_name
> $variable:HOME  # same as $HOME
> ```
> 
> As a result, `os.getenv("HOME")` will return `nil`.

Thanks, I will fix this.
