### ISSUE TITLE
The `timeoutlen` set to 0 disables keymaps which need consecutive typing

### ISSUE THREAD

**Issue by TonyWu20** [ayamir/nvimdots#341]
### Neovim version

NVIM v0.8.1 Build type: Release LuaJIT 2.1.0-beta3 Compiled by brew@HMBRW-A-001-M1-004.local  Features: +acl +iconv +tui See ":help feature-compile"     system vimrc file: "$VIM/sysinit.vim"   fall-back for $VIM: "/opt/homebrew/Cellar/neovim/0.8.1/share/nvim"  Run :checkhealth for more info

### Operating system/version

macOS 12.6

### Terminal name/version

wezterm 20220905-102802-7d4b8249

### $TERM environment variable

xterm-256color

### Branch info

main (Default/Latest)

### Fetch Preferences

SSH (use_ssh = true)

### How to reproduce the issue

Upgrade to commit after https://github.com/ayamir/nvimdots/commit/136c6f525301c5f23d1fac8c4468b102500ea8be 

### Expected behavior

All keymaps should work normally.

### Actual behavior

After upgrading to commit after https://github.com/ayamir/nvimdots/commit/136c6f525301c5f23d1fac8c4468b102500ea8be, keymaps start with `<leader>` or other keys stop working, while keymaps like `<C-d>`, `<A-t>`, `<A-d>` still work.

### Additional information

In commit https://github.com/ayamir/nvimdots/commit/136c6f525301c5f23d1fac8c4468b102500ea8be, it seems that the `timeoutlen` is supposed to be handled by the plugin `better_escape`, and fallback to the option in `core/options.lua`. Therefore, it could be the plugin's issue.

**Comment by ayamir** [comment]
> After upgrading to commit after https://github.com/ayamir/nvimdots/commit/136c6f525301c5f23d1fac8c4468b102500ea8be, keymaps start with or other keys stop working, while keymaps like , , still work.

Such as what?

**Comment by TonyWu20** [comment]
> > After upgrading to commit after [136c6f5](https://github.com/ayamir/nvimdots/commit/136c6f525301c5f23d1fac8c4468b102500ea8be), keymaps start with or other keys stop working, while keymaps like , , still work.
> 
> Such as what?

`<A-t>` and `<C-d>`

**Comment by TonyWu20** [comment]
keymaps start with `<leader>` or character like `gD`

**Comment by ayamir** [comment]
You can pull to the latest config and everything works normally.

**Comment by ayamir** [comment]
BTW, `which-key.nvim` can handle `timeoutlen=0` normally. So please set `timeoutlen=300` if you removed `which-key.nvim` by yourself.

**Comment by TonyWu20** [comment]
I pulled to the latest config and it works. So I will close this issue
