### ISSUE TITLE
Current `catppuccin` config makes the pop-up menu selection hard to see

### ISSUE THREAD

**Issue by TonyWu20** [ayamir/nvimdots#342]
### Neovim version

NVIM v0.8.1 Build type: Release LuaJIT 2.1.0-beta3 Compiled by brew@HMBRW-A-001-M1-004.local  Features: +acl +iconv +tui See ":help feature-compile"     system vimrc file: "$VIM/sysinit.vim"   fall-back for $VIM: "/opt/homebrew/Cellar/neovim/0.8.1/share/nvim"  Run :checkhealth for more info

### Operating system/version

macOS 12.6

### Terminal name/version

wezterm 20220905-102802-7d4b8249

### $TERM environment variable

xterm-256color

### Branch info

main (Default/Latest)

### Fetch Preferences

SSH (use_ssh = true)

### How to reproduce the issue

Use the repo's `catppuccin` settings.

### Expected behavior

When the pop-up menu appears in cases such as completion invoked, we should see the current selection with proper highlight color, to be distinguished from the menu background color.

### Actual behavior

Can you tell which option is my current selection from this screenshot?
![image](https://user-images.githubusercontent.com/45414421/204703220-c9d13dcf-82ae-4fbe-bfd3-82f6e462f1b6.png)
Answer: `green`
My current solution is changing the pop-up menu background color to a deeper one: `Pmenu = { bg = cp.base, fg = cp.overlay2 }`

**Comment by ayamir** [comment]
![image](https://user-images.githubusercontent.com/61657399/204740204-8f4fb433-f312-4846-b185-6576cc180547.png)
