### ISSUE TITLE
change theme can't change status line theme

### ISSUE THREAD

**Issue by goodpaperman** [ayamir/nvimdots#345]
### Neovim version

NVIM v0.8.1 Build type: RelWithDebInfo LuaJIT 2.1.0-beta3

### Operating system/version

CentOS Linux release 7.9.2009 (Core)

### Terminal name/version

mac term

### $TERM environment variable

xterm-256color

### Branch info

main (Default/Latest)

### Fetch Preferences

SSH (use_ssh = true)

### How to reproduce the issue

switch scheme and see status bar

### Expected behavior

status bar background color changed

### Actual behavior

not change：
<img width="855" alt="图片" src="https://user-images.githubusercontent.com/8522640/205214772-e6a90d9a-0801-4170-a50e-9d4b8de95c4b.png">
<img width="843" alt="图片" src="https://user-images.githubusercontent.com/8522640/205214781-6f3589ff-4dcf-4df8-81db-cc68db5a4e2d.png">
<img width="857" alt="图片" src="https://user-images.githubusercontent.com/8522640/205214784-f9d4acf9-9d64-4a0a-a0d2-3155e9c2109f.png">
<img width="850" alt="图片" src="https://user-images.githubusercontent.com/8522640/205214798-0f161555-263f-43a7-81eb-89e63d963269.png">

### Additional information

has install Nerd Font:
<img width="667" alt="图片" src="https://user-images.githubusercontent.com/8522640/205214885-c6f59a27-f70c-422c-a767-d483c25d7cca.png">

**Comment by ayamir** [comment]
Which theme are you using? I don't know why your background is so light, it maybe related to your terminal background theme.
If you want to change the status line theme, your need to modify here:
https://github.com/ayamir/nvimdots/blob/4f4bc57bbd59686ab778739ab6e5f3557f8e6174/lua/modules/ui/config.lua#L456
And then `PackerCompile`

**Comment by goodpaperman** [comment]
I was use 'blue', and changed to many other schemes show in above picutures.
after set theme = 'blue' in ~/.config/lua/modules/ui/config.lua,  status line changed:
<img width="858" alt="图片" src="https://user-images.githubusercontent.com/8522640/205233032-af48ecb7-fc80-4759-9e7b-2497d53e37e4.png">

:LualineNotices shows
<img width="858" alt="图片" src="https://user-images.githubusercontent.com/8522640/205233107-0ba70b96-986e-4d7f-a5bf-2ad7cb3411a4.png">

anything wrong? 
I use scheme 'blue' in ~/.config/nvim/lua/core/init.lua too, and no error occurs

**Comment by ayamir** [comment]
You set lualine theme from this [list](https://github.com/nvim-lualine/lualine.nvim/blob/master/THEMES.md)

**Comment by goodpaperman** [comment]
set lualine scheme to 'onelight' and it works:

![图片](https://user-images.githubusercontent.com/8522640/205539495-be9b84ed-7a88-44dd-88c5-fc2e88367c76.png)

thks~
