### ISSUE TITLE
how to disable FormatOnSave permanently?

### ISSUE THREAD

**Issue by goodpaperman** [ayamir/nvimdots#347]
### Neovim version

NVIM v0.8.1 Build type: RelWithDebInfo LuaJIT 2.1.0-beta3

### Operating system/version

CentOS Linux release 7.9.2009 (Core)

### Terminal name/version

mac term

### $TERM environment variable

xterm-256color

### Branch info

main (Default/Latest)

### Fetch Preferences

SSH (use_ssh = true)

### Affected language servers

clang-format

### How to reproduce the issue

:w save file，code auto formatted

### Actual behavior

code formatted

### Expected behavior

not format

### Support info

:LspInfo
![图片](https://user-images.githubusercontent.com/8522640/205540261-51dee403-f5b7-4c7e-88ac-a6e74edb311c.png)

:Mason
![图片](https://user-images.githubusercontent.com/8522640/205540312-d5be2812-a875-476b-893e-2213ff3102e9.png)

### Logs

```console
no logs find in given path
```

### Additional information

using FormatToggle can disable this, but sometime forget to set this, can I disable this feature in config file?

**Comment by ayamir** [comment]
here: https://github.com/ayamir/nvimdots/blob/63113e2bb2031c335ce7ab70799dc24502fd27d3/lua/core/settings.lua#L5

**Comment by goodpaperman** [comment]
it works:

```
local settings = {}
local home = os.getenv("HOME")

settings["use_ssh"] = true
settings["format_disabled_dirs"] = {
	home .. "/format_disabled_dir_under_home",
    home .. "/code/gevent",
    "/home/ext/project/baidu/netdisk/p2p-sdk-mobile/project/src"
}

return settings
```

can I specify things like 'code/*' to do regular express match?

**Comment by ayamir** [comment]
currently can't

**Comment by goodpaperman** [comment]
can I disable clang-format on start?

**Comment by ayamir** [comment]
comment this line:
https://github.com/ayamir/nvimdots/blob/63113e2bb2031c335ce7ab70799dc24502fd27d3/lua/modules/completion/lsp.lua#L273

**Comment by goodpaperman** [comment]
lsp complains about this:

![图片](https://user-images.githubusercontent.com/8522640/205565392-1d8a1019-4841-4c71-8ccf-3b09d48c0a33.png)

**Comment by ayamir** [comment]
So what do you want to do?

**Comment by goodpaperman** [comment]
anything like do a 'FormatToggle' on startup for all files, if want format, I will toggle it mannually

**Comment by ayamir** [comment]
set `true` to `false`
https://github.com/ayamir/nvimdots/blob/5ec59914b2ef9e3e875f10ded4b199d159b2e964/lua/modules/completion/formatting.lua#L6

**Comment by goodpaperman** [comment]
it works:
![图片](https://user-images.githubusercontent.com/8522640/205584979-c91a427f-4402-4299-a346-59d02a9fd9eb.png)

for business project, this should be the default option I think, many company has it's own coding standard, format on save will make lots of modification to commit, that feels bad~
