### ISSUE TITLE
copy to register `"+` or `"*` failed

### ISSUE THREAD

**Issue by rickywu** [ayamir/nvimdots#348]
### Neovim version

NVIM 0.9.0

### Operating system/version

WSL

### Terminal name/version

MobaXterm

### Branch info

main (Default/Latest)

### Fetch Preferences

SSH (use_ssh = true)

### How to reproduce the issue

打开文件进入visual模式，按e移动到单词结尾，显示如下提示
![image](https://user-images.githubusercontent.com/442398/205567312-1e176032-fb49-4e0b-bba9-b4bacab964e6.png)

导致
vim.api.nvim_set_keymap("v", "<C-C>", '"+y', { silent = false })
这两个映射失效，无法复制，并且进入visual模式选择后执行“+y，导致+和*两个寄存器内容被”的内容覆盖

### Expected behavior

“+y应该复制visual模式选择内容到+寄存器
更新版本后加入了which-key出现的问题

**Comment by ayamir** [comment]
I resolved this conflict by modifying EasyAlign's keymap at 5ec59914b2ef9e3e875f10ded4b199d159b2e964

**Comment by rickywu** [comment]
I found and fixed mapping, But why register + overrided by " when use "+y

**Comment by ayamir** [comment]
> vim.api.nvim_set_keymap("v", "", '"+y', { silent = false })
Please use backquote pair with code snippet

**Comment by rickywu** [comment]
> > vim.api.nvim_set_keymap("v", "", '"+y', { silent = false })
> 
> Please use backquote pair with code snippet

map is OK, :map <c-c>
![image](https://user-images.githubusercontent.com/442398/205586177-e4632396-8e0d-442e-a6b2-71b3d0d68e61.png)

**Comment by ayamir** [comment]
First of all, I don't know what effect you expected finally.
On WSL, `"+` and `"*` register are configured [here](https://github.com/ayamir/nvimdots/blob/5ec59914b2ef9e3e875f10ded4b199d159b2e964/lua/core/init.lua#L92) to synchronize them with system clipboard, so their values are synced with the anonymous register `""`.

**Comment by rickywu** [comment]
I expect in visual mode after selected, use "+y should copy selected item into register +， but the actual is "+y, the reigsiter + overrided by register "

**Comment by ayamir** [comment]
comment this line:
https://github.com/ayamir/nvimdots/blob/5ec59914b2ef9e3e875f10ded4b199d159b2e964/lua/core/init.lua#L124
set this to `false`:
https://github.com/ayamir/nvimdots/blob/5ec59914b2ef9e3e875f10ded4b199d159b2e964/lua/modules/editor/config.lua#L517
then `PackerCompile`

**Comment by rickywu** [comment]
Do you have this problem:
![image](https://user-images.githubusercontent.com/442398/205614455-6495674f-cfa0-4ec6-a102-ecae83f12e37.png)
![image](https://user-images.githubusercontent.com/442398/205614520-b59908a4-9d4b-4536-ab9c-c8f1c8e3a2aa.png)

register " has content but press p in n mode got this error
I have to use ""p to paste, this only happen in WSL
