### ISSUE TITLE
How can I map C-j to C-e in lua

### ISSUE THREAD

**Issue by goodpaperman** [ayamir/nvimdots#349]
in vim, I do this by nmap:
```
" scroll screen one line down/up using ctrl+j/k instead of ctrl+e/y
nmap    <C-j> <C-e>
nmap    <C-k> <C-y>
```

how can I do this in neovim with lua, old configuration file seems not work

**Comment by CharlesChiuGit** [comment]
Please do some research before asking. 
https://neovim.io/doc/user/lua.html#lua-keymap

**Comment by ayamir** [comment]
1. Check if the keymap is mapped, for example:
`:verbose nmap <C-j>`
![image](https://user-images.githubusercontent.com/61657399/205635087-12cffab7-dacf-4042-8079-6298b5a5532e.png)

2. Remove old keymap and add your own keymap in this way:
https://github.com/ayamir/nvimdots/blob/5ec59914b2ef9e3e875f10ded4b199d159b2e964/lua/core/mapping.lua#L19

**Comment by goodpaperman** [comment]
> Please do some research before asking. https://neovim.io/doc/user/lua.html#lua-keymap

Sorry, I am a beginner of neovim with lua, and I find there is very little material about this topic..

**Comment by goodpaperman** [comment]
> 1. Check if the keymap is mapped, for example:
>        `:verbose nmap <C-j>`
>        ![image](https://user-images.githubusercontent.com/61657399/205635087-12cffab7-dacf-4042-8079-6298b5a5532e.png)
> 
>     2. Remove old keymap and add your own keymap in this way:
>        https://github.com/ayamir/nvimdots/blob/5ec59914b2ef9e3e875f10ded4b199d159b2e964/lua/core/mapping.lua#L19

perfect! it works

**Comment by goodpaperman** [comment]
I map these keys by typing in nvim
```
:nmap <C-j> <C-e>
:nmap <C-k> <C-y>
```

there is a little different setting by this way than modify code in mapping.lua, 
it can scroll 5 lines once, and see detail by verbose:
![图片](https://user-images.githubusercontent.com/8522640/205798980-e8b844a1-8206-40ca-93c6-94c65fa8603e.png)

comparing to result setting by lua code, lack a '*' at begin:
![图片](https://user-images.githubusercontent.com/8522640/205798307-ceb45478-63ef-4d4f-a684-c954c5e68c71.png)

what the difference between setting by nmap and lua code ?
how can I remove this '*' in lua code?

**Comment by ayamir** [comment]
`with_noremap()` or not

**Comment by goodpaperman** [comment]
it works，amazing！
