### ISSUE TITLE
Any command like 'Gtags -g fool' to search global symbols in LSP?

### ISSUE THREAD

**Issue by goodpaperman** [ayamir/nvimdots#350]
with gtags, I can search symbols by: Gtags -g/-d/-r fool， to do string/definition/reference search
with lsp, I can jump by gD and see definition by gd, see reference by gh, see declaration by K,
is there any command to do global symbol search ?

![图片](https://user-images.githubusercontent.com/8522640/205881160-ea2513a2-33de-4785-bab1-681c2bffc6e6.png)

**Comment by ayamir** [comment]
`:Telescope live_grep`

**Comment by goodpaperman** [comment]
great!! is there any key mapping to live_grep?

**Comment by ayamir** [comment]
`<leader>fw`

**Comment by goodpaperman** [comment]
where to set the <leader> key?

**Comment by ayamir** [comment]
https://github.com/ayamir/nvimdots/blob/81301772a302a9ea6fe50f2161a15e5787d8cf27/lua/core/init.lua#L73

**Comment by goodpaperman** [comment]
How can I specify the search range? 
I find that search in root directory, generates more results than search in a file (open one of the search result)

search in empty nvim:
![图片](https://user-images.githubusercontent.com/8522640/206342867-136be6e5-883e-4f86-9a1d-42b35f8e82b0.png)

search in one of result file:
![图片](https://user-images.githubusercontent.com/8522640/206342896-80627665-9a0e-4570-81b2-e7e3f4c505ce.png)

**Comment by ayamir** [comment]
Yes, but you can utilize `<leader>fz` to change the work directory.
Of course, you can comment this line to cancel this feature:
https://github.com/ayamir/nvimdots/blob/6dcc221f70418efbcf6e62d4ec91aca1dbe098fa/lua/core/event.lua#L37

**Comment by ayamir** [comment]
> How can I specify the search range?

Additionally, I introduced this feature at this commit: 6dcc221f70418efbcf6e62d4ec91aca1dbe098fa

**Comment by goodpaperman** [comment]
it works!
> Yes, but you can utilize `<leader>fz` to change the work directory. Of course, you can comment this line to cancel this feature:
> 
> https://github.com/ayamir/nvimdots/blob/6dcc221f70418efbcf6e62d4ec91aca1dbe098fa/lua/core/event.lua#L37


how can I apply this patch? and how to use this feature?
> > How can I specify the search range?
> 
> Additionally, I introduced this feature at this commit: [6dcc221](https://github.com/ayamir/nvimdots/commit/6dcc221f70418efbcf6e62d4ec91aca1dbe098fa)

**Comment by ayamir** [comment]
Did you install `zoxide` and init it for your shell?
https://github.com/ayamir/nvimdots/commit/6dcc221f70418efbcf6e62d4ec91aca1dbe098fa#commitcomment-92368616

**Comment by goodpaperman** [comment]
ok, I will try..
> Did you install `zoxide` and init it for your shell? [6dcc221#commitcomment-92368616](https://github.com/ayamir/nvimdots/commit/6dcc221f70418efbcf6e62d4ec91aca1dbe098fa#commitcomment-92368616) I think you can do some research before you ask me.

Sorry, I am a beginner of neovim with lua, and I find there is very little material about this topic.
Is there any cook book to introduce all these plugins in nvim?

**Comment by ayamir** [comment]
Current not, it's a good idea but it takes time.
