### ISSUE TITLE
support gruvbox-material theme

### ISSUE THREAD

**Issue by double12gzh** [ayamir/nvimdots#353]
### Feature description

support gruvbox-material theme.

update the theme per custom part cannot setup theme to gruvbox-material.

**Comment by ayamir** [comment]
![image](https://user-images.githubusercontent.com/61657399/206852913-5f7711cd-7754-40eb-88d0-6862f0f21824.png)

**Comment by double12gzh** [comment]
Great thanks for your kind help. There is still one question:

successfully setup the theme following your great advice, however, i am confused why the color for nvimtree (letft window)  is different from that used by editor (right window). 
![1](https://user-images.githubusercontent.com/2534467/206883953-b9b2b14c-f440-475c-bb7d-2f0540659d03.png)

**Comment by ayamir** [comment]
Maybe just due to the lack of support for `nvim-tree.lua`

**Comment by double12gzh** [comment]
➜  user git:(main) ✗ cat config.lua
local config = {}
local config = {}

function config.gruvbox_material()
    vim.opt.background = "dark"
    vim.g.gruvbox_material_background = "soft"
    vim.g.gruvbox_material_foreground = "material"
    vim.g.gruvbox_material_enable_italic = 1
    vim.g.gruvbox_transp_bg = 1
    vim.g.gruvbox_material_disable_italic_comment = 0
    vim.g.gruvbox_material_better_performance = 1
    vim.g.gruvbox_plugin_hi_groups = 1
    vim.g.gruvbox_filetype_hi_groups = 1
end

return config
➜  user git:(main) ✗ pwd
/root/.config/nvim/lua/modules/ui/user
➜  user git:(main) ✗

**Comment by ayamir** [comment]
![image](https://user-images.githubusercontent.com/61657399/206889051-ac736f3e-8ae3-4a5b-a095-2e3a9d2be1e7.png)
Maybe it have to do with your terminal
