### ISSUE TITLE
[Feature Request]: (New Plugin) zbirenbaum/neodim

### ISSUE THREAD

**Issue by Jint-lzxy** [ayamir/nvimdots#354]
### Feature description

This is a plugin for dimming the highlights of unused functions, variables, parameters, and more. Its behavior is similar to that of vscode:
<img width="303" alt="eg" src="https://user-images.githubusercontent.com/50296129/206829006-c6c5e769-0a59-472c-a815-8a8d192fa64c.png">

It will also disable virtual text to behave like a "silent reminder". If applicable, I will open a new PR for this 👍 

### Additional information

This is the setup that achieves the effect of the image above:
<details>
    <summary>Detail</summary>
<p>

**plugins.lua**
```lua
ui["zbirenbaum/neodim"] = {
	opt = true,
	event = "LspAttach",
	config = conf.neodim,
}
```

**config.lua**
```lua
function config.neodim()
	require("neodim").setup({
		alpha = 0.45,
		blend_color = string.format("#%06x", vim.api.nvim_get_hl_by_name("Normal", true).background),
		-- Blend with background color to make neodim more seamless
		update_in_insert = {
			enable = true,
			delay = 100,
		},
		hide = {
			virtual_text = true,
			signs = false,
			underline = false,
		},
	})
end
```
<br />
</details>

**Comment by CharlesChiuGit** [comment]
looks cool!

**Comment by ayamir** [comment]
nice feature, PR is welcome 👍
