### ISSUE TITLE
Override hi color of  nvim-notify not work

### ISSUE THREAD

**Issue by rickywu** [ayamir/nvimdots#357]
### Neovim version

nvim 0.9.0

### Operating system/version

macOS/WSL/Windows

### Terminal name/version

iTerm 2

### $TERM environment variable

xterm

### Branch info

main (Default/Latest)

### Fetch Preferences

SSH (use_ssh = true)

### How to reproduce the issue

add hi color in notify.setup()

```
	local notify = require("notify")
	local icons = {
		diagnostics = require("modules.ui.icons").get("diagnostics"),
		ui = require("modules.ui.icons").get("ui"),
	}

	notify.setup({
		---@usage Animation style one of { "fade", "slide", "fade_in_slide_out", "static" }
		stages = "slide",
		---@usage Function called when a new window is opened, use for changing win settings/config
		on_open = nil,
		---@usage Function called when a window is closed
		on_close = nil,
		---@usage timeout for notifications in ms, default 5000
		timeout = 2000,
		-- Render function for notifications. See notify-render()
		render = "default",
		---@usage highlight behind the window for stages that change opacity
		background_colour = "Normal",
		---@usage minimum width for notification windows
		minimum_width = 50,
		---@usage notifications with level lower than this would be ignored. [ERROR > WARN > INFO > DEBUG > TRACE]
		level = "TRACE",
		---@usage Icons for the different levels
		icons = {
			ERROR = icons.diagnostics.Error,
			WARN = icons.diagnostics.Warning,
			INFO = icons.diagnostics.Information,
			DEBUG = icons.ui.Bug,
			TRACE = icons.ui.Pencil,
		},
		vim.cmd([[
            hi NotifyINFOIcon guifg=#6b8e23
            hi NotifyINFOTitle guifg=#6b8e23
        ]]),
	vim.notify = notify
```

### Expected behavior

Should use hi color #6b8e23 1st startup

### Actual behavior

The 1st time use PackerCompile
![image](https://user-images.githubusercontent.com/442398/206909843-5a766f00-c6ca-42c8-a6ef-e3d429babf99.png)

2nd time seems works well
![image](https://user-images.githubusercontent.com/442398/206909856-8a452ffe-afa2-45d2-928e-9b1f3c5e72f7.png)

After restart:
![image](https://user-images.githubusercontent.com/442398/206909889-a47ccd39-65cb-4c8c-b677-162df2c7bec5.png)

### Additional information

I tested in WSL/MacOS/Windows， there is little different
WSL/MacOS change hi color immediately(in one seconds), but Windows is not
But all of them use default hi color after restart

I open an issue to nvim-notify, seems it not related about plugin.
https://github.com/rcarriga/nvim-notify/issues/162

**Comment by ayamir** [comment]
It's because your code is wrong...
You can't add `vim.cmd...` to `notify.setup({})`.
```lua
function config.notify()
	local notify = require("notify")
	local icons = {
		diagnostics = require("modules.ui.icons").get("diagnostics"),
		ui = require("modules.ui.icons").get("ui"),
	}

	notify.setup({
		---@usage Animation style one of { "fade", "slide", "fade_in_slide_out", "static" }
		stages = "slide",
		---@usage Function called when a new window is opened, use for changing win settings/config
		on_open = nil,
		---@usage Function called when a window is closed
		on_close = nil,
		---@usage timeout for notifications in ms, default 5000
		timeout = 2000,
		-- Render function for notifications. See notify-render()
		render = "default",
		---@usage highlight behind the window for stages that change opacity
		background_colour = "Normal",
		---@usage minimum width for notification windows
		minimum_width = 50,
		---@usage notifications with level lower than this would be ignored. [ERROR > WARN > INFO > DEBUG > TRACE]
		level = "TRACE",
		---@usage Icons for the different levels
		icons = {
			ERROR = icons.diagnostics.Error,
			WARN = icons.diagnostics.Warning,
			INFO = icons.diagnostics.Information,
			DEBUG = icons.ui.Bug,
			TRACE = icons.ui.Pencil,
		},
	})

	vim.cmd([[
	            hi NotifyINFOIcon guifg=#6b8e23
	            hi NotifyINFOTitle guifg=#6b8e23
	        ]])
	vim.notify = notify
end
```

**Comment by rickywu** [comment]
_compiled.lua
![image](https://user-images.githubusercontent.com/442398/206954685-6c08cd25-5354-4aa2-a475-03eabd154f95.png)

ui/config.lua
![image](https://user-images.githubusercontent.com/442398/206954814-b219cfc7-b0da-4d81-99b8-c6ec298f3818.png)

I tried PackerCompile twice and got the same
![image](https://user-images.githubusercontent.com/442398/206954744-0d192ff9-0fd3-4bd8-a18a-129810a21f25.png)

**Comment by ayamir** [comment]
<img width="1263" alt="image" src="https://user-images.githubusercontent.com/61657399/206963338-90b41dfe-cb90-4ffc-814f-e9aa54c491a3.png">
Put it to `core/init.lua` after loading colorscheme.

**Comment by rickywu** [comment]
OK, I put in colorscheme
