### ISSUE TITLE
Does language check have a different font color with the code ?

### ISSUE THREAD

**Issue by goodpaperman** [ayamir/nvimdots#358]
I open a shell script, and find many check errors, these error has the same font color with shell code, and I could NOT distinguish them easily: 
![图片](https://user-images.githubusercontent.com/8522640/206983002-c27271f1-c03c-4041-a32c-a4a91d788fd5.png)

Is there a different color setting for the check results ?

**Comment by goodpaperman** [comment]
And any switch to hide the check results ?

**Comment by ayamir** [comment]
1. Your colorscheme likes so wired. You can use `catppuccin` and check what's wrong.
2. https://github.com/ayamir/nvimdots/issues/178#issuecomment-1210538073

**Comment by goodpaperman** [comment]
Using catppuccin, it seems worse that before:
![图片](https://user-images.githubusercontent.com/8522640/207036199-c6bb3e5d-0f68-49d7-92c6-c1a85cf4b0be.png)

How can I check the reason?

**Comment by ayamir** [comment]
What terminal do you use? Does it support 256 color?

**Comment by goodpaperman** [comment]
I tried wezterm, it's good:
![图片](https://user-images.githubusercontent.com/8522640/207220621-8c1fa619-4f6b-4014-b70c-b14d1045b4a9.png)

But too few light background schemes (only catppuccin-latte / delek / morning / quiet / shine / zellner), and all of them are in low contrast, too difficult for me to see code clearly, so I give up。

To walk away this problem by changing terminal is not a good idea,  I think. As people are familiar with their own terminals, change on terminal may take a lot of time. 

So, is there any way just to change the color settings of selected scheme?

**Comment by ayamir** [comment]
> But too few light background schemes (only catppuccin-latte / delek / morning / quiet / shine / zellner), and all of them are in low contrast, too difficult for me to see code clearly, so I give up。

You can add more ligth theme on your own, like https://github.com/ayamir/nvimdots/issues/353

**Comment by goodpaperman** [comment]
Effect of using scheme 'edge' with wezterm:
![图片](https://user-images.githubusercontent.com/8522640/207243032-cb9e9bb6-9220-44db-a29e-c037b9a86051.png)

Supplement
according to this [article](https://gaomf.cn/2017/01/16/Terminal_Color/#:~:text=%E7%9B%AE%E5%89%8D%E4%B8%BB%E6%B5%81%E7%9A%84%E7%BB%88%E7%AB%AF%E4%B8%80,%E6%8C%8124%E4%BD%8D%E7%9C%9F%E5%BD%A9%E8%89%B2%E3%80%82)

I test wezterm:
![图片](https://user-images.githubusercontent.com/8522640/207243574-c1c919fa-ac68-4536-90e4-d883d7c87c7f.png)

and mac term:
![图片](https://user-images.githubusercontent.com/8522640/207243612-fefcef1a-7a53-4f1d-a626-46f1bf007edb.png)

wezterm support true color, but mac term only support 256 color, is that the key different?

**Comment by ayamir** [comment]
First of all, You must set your terminal theme to a **light** theme before using `nvim`'s **light** theme. This is also true for **dark** theme.
Secondly, as you can see, the test result of mac terminal is abnormal. I don't use mac and mac builtin terminal too, so I have no idea about it. You either need to make it works normal like `wezterm` or use a terminal which can provide correct color support such as `wezterm` or `kitty`.

**Comment by goodpaperman** [comment]
Okay，I‘ll try GNU terminal on Ubuntu, if there is no problem, this is a certain problem about mac terminal

Supplement
I use light scheme on mac term:
![图片](https://user-images.githubusercontent.com/8522640/207316734-f73c334f-e470-4333-a28d-94e622aced18.png)
