### ISSUE TITLE
I can't see the picture in the front page

### ISSUE THREAD

**Issue by Lonjiazeng** [ayamir/nvimdots#359]
### Neovim version

NVIM v0.8.1

### Operating system/version

arch

### Terminal name/version

alacritty 0.11.0 (8dbaa0bb)

### $TERM environment variable

alacritty

### Branch info

main (Default/Latest)

### Fetch Preferences

SSH (use_ssh = true)

### How to reproduce the issue

us command `neovide` or `nvim` in alacritty.

### Expected behavior

see the picture that I saw in Windows using WSL.

### Actual behavior

![image](https://user-images.githubusercontent.com/76612231/207023521-143e0ed3-6260-4823-ac7d-8128e028026c.png)

**Comment by CharlesChiuGit** [comment]
have u tried using windows terminal with arch(WSL)?
![圖片](https://user-images.githubusercontent.com/32497323/207026392-51c3cc69-3288-4e80-a67a-12b6442f2020.png)

**Comment by ayamir** [comment]
Please use `wezterm`.

**Comment by Lonjiazeng** [comment]
> Please use `wezterm`.

`wezterm` works, but neovide does not.

**Comment by Lonjiazeng** [comment]
> have u tried using windows terminal with arch(WSL)? maybe it's your alacritty theme got in the way.

I'm in arch linux now, not in Windows.

**Comment by ayamir** [comment]
Its effect up to the terminal you used, have nothing to do with the config, so close it.
