### ISSUE TITLE
插件下载有些问题

### ISSUE THREAD

**Issue by JerryAllison** [ayamir/nvimdots#364]
<img width="855" alt="image" src="https://user-images.githubusercontent.com/5206758/207556709-b5c95479-f799-4b84-9833-6901704c3478.png">
snip那个插件我一年都没有下载下来。

**Comment by ayamir** [comment]
光标定位到`Failed to update michaelb/sniprun`按下回车看一下原因

**Comment by CharlesChiuGit** [comment]
![圖片](https://user-images.githubusercontent.com/32497323/207557954-feae4e84-3505-4b5d-acd4-c6cf9ced0eb2.png)
會不會是你沒有安裝rust & cargo?

**Comment by Deg2v** [comment]
auto-session是这个原因，https://github.com/rmagatti/auto-session/issues/192， `doc/tags`没有忽略，和仓库冲突。

**Comment by JerryAllison** [comment]
<img width="1164" alt="image" src="https://user-images.githubusercontent.com/5206758/208045898-0ea456b0-9782-4eb3-8424-8698e9de7dab.png">

**Comment by CharlesChiuGit** [comment]
這是跟git 有關的問題 你是不是有去修改裡面的code?
如果你修改裡面的code是為了避免使用https 使用git proxy會是一個更穩健的做法

**Comment by ayamir** [comment]
> <img alt="image" width="1164" src="https://user-images.githubusercontent.com/5206758/208045898-0ea456b0-9782-4eb3-8424-8698e9de7dab.png">
> 
> 我基本都是使用默认的配置，对nvim不熟悉，所以没有修改任何东西。

最简单的办法就是去`~/.local/share/nvim/site/pack/packer/opt/`下把这几个插件的目录删除之后重新`PackerSync`

**Comment by JerryAllison** [comment]
`最简单的办法就是去~/.local/share/nvim/site/pack/packer/opt/下把这几个插件的目录删除之后重新PackerSync`
按这个操作搞定了，很是奇怪，我没有修改任何东西为啥会这样。
