### ISSUE TITLE
lua/vim/lsp/sync.lua throw a error `attempt to get length of local 'prev_lin e' (a nil value)` when typing in dap-repl buffer

### ISSUE THREAD

**Issue by csyJoy** [ayamir/nvimdots#365]
### Neovim version

NVIM v0.8.1

### Operating system/version

macOS 13.1

### Terminal name/version

iTerm2 build 3.4.12

### $TERM environment variable

xterm-256color

### Branch info

main (Default/Latest)

### Fetch Preferences

SSH (use_ssh = true)

### How to reproduce the issue

1. open a c++ project
2. use `<leader>db` set a break point
3. use `F6` to launch the executable
4. move to the `dap-repl` buffer and switch to insert mode
5. while switch, nvim throws an error

### Expected behavior

when switching to the `dap-repl` buffer, I can use dap command.

### Actual behavior

nvim throws am error while switching to insert mode:
  `Error executing lua callback: ...lar/neovim/0.8.1/share/nvim/runtime/lua/vim/lsp/sync.lua:177: attempt to get length of local 'prev_lin
e' (a nil value)
stack traceback:
        ...lar/neovim/0.8.1/share/nvim/runtime/lua/vim/lsp/sync.lua:177: in function 'compute_start_range'
        ...lar/neovim/0.8.1/share/nvim/runtime/lua/vim/lsp/sync.lua:408: in function 'compute_diff'
        ...w/Cellar/neovim/0.8.1/share/nvim/runtime/lua/vim/lsp.lua:442: in function 'incremental_changes'
        ...w/Cellar/neovim/0.8.1/share/nvim/runtime/lua/vim/lsp.lua:635: in function 'send_changes'
        ...w/Cellar/neovim/0.8.1/share/nvim/runtime/lua/vim/lsp.lua:1547: in function <...w/Cellar/neovim/0.8.1/share/nvim/runtime/lua/
vim/lsp.lua:1541>`

**Comment by csyJoy** [comment]
well, I add `["dap-repl"]: false` in filetypes on the first line while setting up copilot.vim and it solved.

**Comment by CharlesChiuGit** [comment]
that's a nice observation!
