### ISSUE TITLE
nvim-tree 显示问题

### ISSUE THREAD

**Issue by yjhtry** [ayamir/nvimdots#368]
## 问题
首次打开文件树是正常的, 当切换文件树的显示时,会出现如下背景覆盖问题.
将背景透明改为false问题仍然存在

首次打开显示正常
<img width="305" alt="截屏2022-12-17 下午5 58 37" src="https://user-images.githubusercontent.com/39440537/208236429-53a5965a-638b-4cab-974b-3b6555a85a88.png">

关闭  部分代码被原有的文件栏位子遮蔽
<img width="230" alt="截屏2022-12-17 下午5 58 59" src="https://user-images.githubusercontent.com/39440537/208236464-def09dd1-1cea-4749-b270-ef95d00e689f.png">

再次打开 按键仍然生效,底部也能看见文件
<img width="240" alt="截屏2022-12-17 下午5 59 12" src="https://user-images.githubusercontent.com/39440537/208236470-d780023b-1102-4893-8128-fda41b3db3e5.png">

## 环境
NVIM v0.9.0-dev-519+g2d8bbe468-dirty
Build type: Release
LuaJIT 2.1.0-beta3

<img width="517" alt="image" src="https://user-images.githubusercontent.com/39440537/208236555-c017a0a9-e9da-49ef-8ca9-f3dde7a07959.png">
<img width="937" alt="image" src="https://user-images.githubusercontent.com/39440537/208236582-749b42f1-a198-4b6c-8b34-6d359c3d19f2.png">

**Comment by ayamir** [comment]
从没遇到过的奇怪bug，你的nvim-tree是怎么开的？`C-n`吗？配置仓库以及插件是否为最新？

**Comment by yjhtry** [comment]
是通过C-n打开的, 配置也是最新的. 刚才删掉配置重装后就正常了, 在执行<leader>nr 命令后问题再次出现😂

**Comment by ayamir** [comment]
录个视频？我这边没法复现

**Comment by yjhtry** [comment]
在视频录制的过程中貌似发现了这个bug的真正原因，当左侧菜单栏高度超过终端一屏的高度时，切换菜单栏就会复现bug。 且出现bug后，点击打开的缓冲区菜单栏会出现。

https://user-images.githubusercontent.com/39440537/208245980-09384931-bab4-4156-9e41-a5f803c6c50c.mp4

**Comment by ayamir** [comment]
或许这个bug要去`nvim-tree.lua`那的仓库问一下了：https://github.com/nvim-tree/nvim-tree.lua

**Comment by yjhtry** [comment]
好的谢谢啦😁
