### ISSUE TITLE
[Feature Request]: (New Plugin) debugloop/telescope-undo.nvim

### ISSUE THREAD

**Issue by CharlesChiuGit** [ayamir/nvimdots#379]
### Feature description

Though we already have `mbbill/undotree`, but in my opinion, it's not very intuitive to use, and one can only search the undotree through their eyeballs.
This plugin leverages telescope.nvim to view undotree with following points:
1. More intuitive to use.
2. fuzzy-search through `diff`.
3. One can choose either yank the `diff` of the undo state to default register or revert to that state.

Previewer demo:
![](https://user-images.githubusercontent.com/4604331/208297854-df5a104a-2fc1-4411-9f5f-5e40454d8dac.png)
<img src="https://user-images.githubusercontent.com/32497323/208741308-24f993f1-fcf8-44c4-95a8-42ab0c00e587.png" width="300"/>

### Additional information

<details>
<summary>Details</summary>

`tools/plugins.lua`
```lua
tools["debugloop/telescope-undo.nvim"] = {
	opt = true,
	after = "telescope.nvim",
}
```

`config.lua`

```lua
require("telescope").setup({
  extensions = {
    undo = {
      side_by_side = true,
      layout_strategy = "vertical",
      layout_config = {
        preview_height = 0.7,
      },
    },
  },
})
```

</details>

**Comment by ayamir** [comment]
<img width="1279" alt="image" src="https://user-images.githubusercontent.com/61657399/208869857-72aed930-8645-4d73-934e-3bc27b8f4440.png">
So how it visualize undo history?

**Comment by CharlesChiuGit** [comment]
u mean the preview window? it should be shown once u enter this panel...
what's your setting of telescope-undo?

**Comment by ayamir** [comment]
ok, nice plugin. What's more, I found that `undotree` can't work and complain `diff is not executable` when I try to open undotree.
