### ISSUE TITLE
how to use the commands to switch light/dark theme?

### ISSUE THREAD

**Issue by CrazyGriferman** [ayamir/nvimdots#38]
I saw these commands, but I don't know how to use it. Should I just type them in terminal or add them in a config file?
Thanks

# To light
    sed -i "s/\=dark/\=light/g" ~/.config/nvim/lua/modules/ui/config.lua
    sed -i "s/onedark/onelight/g" ~/.config/nvim/lua/modules/ui/config.lua
# To Dark
    sed -i "s/\=light/\=dark/g" ~/.config/nvim/lua/modules/ui/config.lua
    sed -i "s/onelight/onedark/g" ~/.config/nvim/lua/modules/ui/config.lua

**Comment by ayamir** [comment]
These lines are shell commands. You can write a shell script to use it.

**Comment by CrazyGriferman** [comment]
thanks!
