### ISSUE TITLE
重复宏操作和预期不一致

### ISSUE THREAD

**Issue by yjhtry** [ayamir/nvimdots#381]
我不确定这是不是一个问题，求助一下大佬。

下图是vim实用脚本的教程案例

`x = "("+a+","+b+","+c+","+d+","+e+")";`

<img width="570" alt="image" src="https://user-images.githubusercontent.com/39440537/209031156-56d60b2c-5a4c-45b5-9a7a-a64471e5a2a0.png">

在使用配置的nvim中没有达到预期效果
<img width="1119" alt="image" src="https://user-images.githubusercontent.com/39440537/209030089-f5c39332-4a38-462d-bc4a-ffb6a4d38475.png">

在不使用init.lua时可以产生预期效果
<img width="699" alt="image" src="https://user-images.githubusercontent.com/39440537/209030951-d919dbf4-a56d-42ba-8131-3b888f55fac7.png">

**Comment by ayamir** [comment]
Comment the two lines:
https://github.com/ayamir/nvimdots/blob/ce0bd368edffd6f7d24e84b7b6f28f975c15253a/lua/keymap/init.lua#L93-L94

**Comment by yjhtry** [comment]
可以了, 谢谢😀
