### ISSUE TITLE
Opening lua files will cause lua-language-server to reset

### ISSUE THREAD

**Issue by Jint-lzxy** [ayamir/nvimdots#385]
### Neovim version

NVIM v0.8.1

### Operating system/version

macOS 12.6.2 (21G320) [x86_64]

### Terminal name/version

iTerm2 Build 3.4.18

### $TERM environment variable

xterm-256color

### Branch info

main (Default/Latest)

### Fetch Preferences

SSH (use_ssh = true)

### Affected language servers

lua-language-server

### How to reproduce the issue

I'm _not_ sure whether it is a local environment problem or not, but since the stable version _(3.6.4)_ of `lua-language-server` was released last month and the problem occurred _just_ recently, it can be ruled out that this is an upstream problem.

**Steps:**

1. Open a `lua` source code file.
2. Then open another `lua` source code file. _(in any way: telescope, nvim-tree...)_
3. `lua-language-server` will return several warnings that builtin functions cannot be found. _(such as `require`)_
4. However, **after modifying any opened `lua` file, the warnings disappear.**
5. If we open another `lua` source code file again, we will still run into `3.`.

### Expected behavior

No false judgment from the language server after opening the file.

### Support info

<img width="1425" alt="LspInfo" src="https://user-images.githubusercontent.com/50296129/209474807-866557e5-92ba-49b7-a901-dc2a041622da.png">

### Logs

```console
From ~/.local/share/nvim/mason/packages/lua-language-server/extension/server/log
=================================================================================

[00:05:42.334][debug][#0:script/provider/provider.lua:246]: workspace/didChangeWorkspaceFolders	{
  event = {
    added = { {
        name = "/Users/jint/.config/nvim",
        uri = "file:///Users/jint/.config/nvim"
      } },
    removed = { {} }
  }
}
-----> [00:05:42.334][info] [#0:script/workspace/workspace.lua:51]: Workspace create: 	file:///Users/jint/.config/nvim
[00:05:42.334][debug][#0:script/provider/provider.lua:267]: didOpen	file:///Users/jint/.config/nvim/lua/keymap/init.lua
[00:05:42.346][info] [#0:script/provider/provider.lua:41]: Load config from client	file:///Users/jint/.config/nvim
[00:05:42.346][info] [#0:script/provider/provider.lua:42]: {
  Lua = {
    runtime = {
      version = "LuaJIT"
    },
    telemetry = {
      enable = false
    }
  }
}
-----> [00:05:42.370][debug][#0:script/files.lua:447]: del ref	file:///Users/jint/.config/nvim/lua/modules/editor/config.lua	0
[00:05:42.371][debug][#0:script/files.lua:447]: del ref	file:///usr/local/opt/neovim/share/nvim/runtime/lua/vim/keymap.lua	0
[00:05:42.371][debug][#0:script/vm/node.lua:460]: clearNodeCache
[00:05:42.371][debug][#0:script/provider/provider.lua:1568]: close proto(ContentModified):	16	textDocument/documentSymbol
[00:05:42.371][debug][#0:script/provider/provider.lua:1568]: close proto(ContentModified):	17	textDocument/documentSymbol
[00:05:42.371][debug][#0:script/files.lua:447]: del ref	file:///usr/local/opt/neovim/share/nvim/runtime/lua/vim/lsp/log.lua	0
[00:05:42.371][debug][#0:script/vm/node.lua:460]: clearNodeCache
.......
```

**Comment by ayamir** [comment]
I can reproduce it on my wsl.

**Comment by CharlesChiuGit** [comment]
I couldn't seem to reproduce this issue on my native void linux or arch(WSL).
Which log file should I looked for?

**Comment by Jint-lzxy** [comment]
> I couldn't seem to reproduce this issue on my native void linux or arch(WSL). 

@CharlesChiuGit Are you using an unmodified clone for testing?

> Which log file should I been looking for?

`/path/to/your/lua-language-server-executable-dir/extension/server/log/`, the log file has format: `file_path(here '/' is replaced by _).log`, for example: `file_Users_jint_.config_nvim.log`. Watch out the log when performing step 2.

> Or how can I set the log level to trace?

https://github.com/ayamir/nvimdots/blob/d93d457f975d298bde60a337bf1717c479148602/lua/modules/completion/lsp.lua#L90
Append
```lua
cmd = { "lua-language-server", "--loglevel=trace" },
```
to the table, above `capabilities`.

**Comment by CharlesChiuGit** [comment]
1. ys.
2. aha! I just put those as single string. no wonder it's not working.

**Comment by CharlesChiuGit** [comment]
Not quite sure about where I should be looking for. Here's the [log file](https://docs.google.com/document/d/1J2A_HM96J3S4-hUGTvGaWSdKbfFRggTB2JmRtUck4cc/edit?usp=share_link).

**Comment by CharlesChiuGit** [comment]
https://www.reddit.com/r/neovim/comments/zvi16e/undefined_global_require_you_can_treat_require_as/
 seems relevant.

**Comment by ayamir** [comment]
It has been fixed at https://github.com/neovim/nvim-lspconfig/commit/a63d2c75c6880d45209baff596939343e8a431fd

**Comment by CharlesChiuGit** [comment]
https://github.com/neovim/nvim-lspconfig/pull/2356
seems like it's been fixed.

**Comment by Jint-lzxy** [comment]
Confirmed. This will be closed :)
