### ISSUE TITLE
打开文件显示有问题

### ISSUE THREAD

**Issue by Kotodian** [ayamir/nvimdots#388]
https://user-images.githubusercontent.com/22030659/209777145-38738ccc-62eb-4e82-951f-cb6d8502d998.mov

录了个视频 主要是第一次打开文件会有问题

**Comment by CharlesChiuGit** [comment]
你應該是很久沒有git pull這個repo了 請先嘗試更新並`:PackerSync`

**Comment by Kotodian** [comment]
<img width="1165" alt="image" src="https://user-images.githubusercontent.com/22030659/209777974-70d9e99b-e2c5-44f1-8523-4be9b2c7a2e3.png">
我今天刚开始弄的，不过我把ssh全换成https了，应该不影响吧

**Comment by CharlesChiuGit** [comment]
1. 你確定是clone目前的main branch嗎? 但我看你error log都是以前已經處理過的問題，你要不要再砍掉重clone一次
2. 使用https下載不影響

**Comment by Kotodian** [comment]
> 1. 你確定是clone目前的main branch嗎? 但我看你error log都是以前已經處理過的問題，你要不要再砍掉重clone一次
> 2. 使用https下載不影響

我看的是知乎上的，我看下
