### ISSUE TITLE
搜索过程中输入 Q 会执行 SnipRunLauncher 并导致搜索中断

### ISSUE THREAD

**Issue by goodpaperman** [ayamir/nvimdots#389]
如题，是快捷键冲突了吗

%s 替换：
![图片](https://user-images.githubusercontent.com/8522640/209900804-d8451699-5ef5-42a5-bea1-17b307aaa93a.png)

/ 直接搜索
![图片](https://user-images.githubusercontent.com/8522640/209900938-96feea16-c522-4870-944b-e6e325437b70.png)

**Comment by goodpaperman** [comment]
I do :PackerSync and update all plugins，but no effect

**Comment by CharlesChiuGit** [comment]
did u pull the latest commit?

**Comment by goodpaperman** [comment]
after git pull, this case fixed.
and I find an conflict in merging file 'lua/modules/completion/formatting.lua':
![图片](https://user-images.githubusercontent.com/8522640/210029107-27ec5f18-830d-4ab5-acc9-da0ee99ff47d.png)

Is that mean in the old version, format-on-save is an option in config file?
I want that option, but after merge, it set to false by default, how can I set it in config file?

**Comment by CharlesChiuGit** [comment]
Setting of `format_on_save` is in this line:
https://github.com/ayamir/nvimdots/blob/976d6b55c8ea73ad475735bc6e246cdfd05ef245/lua/core/settings.lua#L5

**Comment by goodpaperman** [comment]
great, that perfect solution!

**Comment by goodpaperman** [comment]
after pull I find telescope shortcuts has no effect：comma+f+w/r/..

**Comment by CharlesChiuGit** [comment]
please open another issue, also the leader key is now "space".

**Comment by goodpaperman** [comment]
space as leader key works, but the startup page still show comma+f+w/r for these commands..
![图片](https://user-images.githubusercontent.com/8522640/210032191-1463f36d-e6ab-453f-94bc-8d777258fa7e.png)

**Comment by CharlesChiuGit** [comment]
No idea why your greeter says otherwise.
https://github.com/ayamir/nvimdots/blob/main/lua/modules/ui/config.lua#L62-L71
![圖片](https://user-images.githubusercontent.com/32497323/210032351-9f00dc36-1757-4d93-9650-609969471684.png)

**Comment by goodpaperman** [comment]
my local config.lua has same content with you, I don't know why, I have restart the nvim process..
