### ISSUE TITLE
packer_compiled.vim : no such file.

### ISSUE THREAD

**Issue by flaviusbuffon** [ayamir/nvimdots#39]
![image](https://user-images.githubusercontent.com/44057232/139611955-c955f3b0-fae0-4024-a40c-ed6f61f9a393.png)
```
Error executing vim.schedule lua callback: ...are/nvim/site/pack/packer/opt/packer.nvim/lua/packer.lua:326: Vim(lua):E5108: Error executing lua /home/jczhang/.config/nvim/lua/core/pack.lua:79: bad argument #1
 to 'lines' (/home/jczhang/.local/share/nvim/site/packer_compiled.vim: No such file or directory)
```

**Comment by ayamir** [comment]
Installation period?

**Comment by flaviusbuffon** [comment]
no.
just after change some lua file and saveing

**Comment by ayamir** [comment]
try `PackerSync`

**Comment by flaviusbuffon** [comment]
but i do not want to update plugin

**Comment by ayamir** [comment]
`PackerCompile`

**Comment by flaviusbuffon** [comment]
i tried PackerCompile but not work

**Comment by ayamir** [comment]
How to recurrent it exactly?

**Comment by flaviusbuffon** [comment]
i really do not know how to recurrent it. missed the file.

**Comment by ayamir** [comment]
![image](https://user-images.githubusercontent.com/61657399/139616238-faec4339-a786-4663-a2e1-4bbbdaa03a7f.png)

**Comment by ayamir** [comment]
Maybe your wrong config's fault.

**Comment by flaviusbuffon** [comment]
config is correct,i used add twice vimsnips, then i delete one of it.




发自我的华为手机


-------- 原始邮件 --------
发件人： ayamir ***@***.***>
日期： 2021年11月1日周一 中午11:07
收件人： ayamir/nvimdots ***@***.***>
抄送： Flavius Buffon ***@***.***>, Author ***@***.***>
主 题： Re: [ayamir/nvimdots] packer_compiled.vim : no such file. (Issue #39)

Maybe your wrong config's fault.
