### ISSUE TITLE
new opened file from nvim-tree didn't replace dashboard's window

### ISSUE THREAD

**Issue by Kotodian** [ayamir/nvimdots#391]
### Neovim version

NVIM v0.8.1 Build type: Release LuaJIT 2.1.0-beta3 编译者 runner@Mac-1668417329633.local

### Operating system/version

macOS 13.0.1

### Terminal name/version

iTerm2 Build 3.4.18

### Branch info

main (Default/Latest)

### Fetch Preferences

HTTPS (use_ssh = false)

### How to reproduce the issue

1. 进入vi
2. NvimTreeOpen
3. 打开一个文件

### Expected behavior

文件显示完整,如下图所示
<img width="1918" alt="image" src="https://user-images.githubusercontent.com/22030659/210031739-04eb8da5-c6dd-4b92-9603-499422bdb6e3.png">

### Actual behavior

实际情况是只显示了一点,但是第二次打开是能够完整显示。
<img width="1888" alt="image" src="https://user-images.githubusercontent.com/22030659/210031764-57fc67fc-29cd-4ac6-843b-05c037d2c415.png">

**Comment by CharlesChiuGit** [comment]
@Kotodian can u try out if this patch fix your problem?

**Comment by Kotodian** [comment]
> @Kotodian can u try out if this patch fixes your problem?

非常感谢

**Comment by Kotodian** [comment]
> 

Thank you, but this problem still exists, but now it happens occasionally.

**Comment by ayamir** [comment]
It works for me.

**Comment by Kotodian** [comment]
> It works for me.

https://user-images.githubusercontent.com/22030659/210044528-5d12c1d4-274c-4580-9c75-c33aff9d5cb0.mov


我现在的做法是进入到~/.config/nvim文件夹下，切换成新的分支，不清楚这样的操作是否正确。

这么做了以后，第一次是能够打开文件的，但是第二次打开其他文件就是直接打不开了,

**Comment by CharlesChiuGit** [comment]
can u try other terminal emulator?

**Comment by CharlesChiuGit** [comment]
did u install any extra plugins?

**Comment by ayamir** [comment]
> > It works for me.
> 
>  Screen.Recording.2022-12-30.at.15.15.14.mov 
> 我现在的做法是进入到~/.config/nvim文件夹下，切换成新的分支，不清楚这样的操作是否正确。
> 
> 这么做了以后，第一次是能够打开文件的，但是第二次打开其他文件就是直接打不开了,

You have not `PackerSync` because it see nvim only report 89 plugins.

**Comment by Kotodian** [comment]
> > > It works for me.
> > 
> > 
> > Screen.Recording.2022-12-30.at.15.15.14.mov
> > 我现在的做法是进入到~/.config/nvim文件夹下，切换成新的分支，不清楚这样的操作是否正确。
> > 这么做了以后，第一次是能够打开文件的，但是第二次打开其他文件就是直接打不开了,
> 
> You forgot to execute `PackerSync` because I see `nvim` only report 89 plugins.

I have tried to execute `PackerSync` some times, it's still 89 plugins.
<img width="1514" alt="image" src="https://user-images.githubusercontent.com/22030659/210046078-a2a30e09-7c88-4882-9909-368722c16df5.png">
<img width="425" alt="image" src="https://user-images.githubusercontent.com/22030659/210046100-f5efc378-8fb7-4c07-a5f8-2699daee7c6f.png">

**Comment by ayamir** [comment]
`:PackerStatue` after `:NvimTreeToggle`
<img width="1280" alt="image" src="https://user-images.githubusercontent.com/61657399/210046416-98c2af87-5a67-4e6d-8241-67d733be1e7c.png">

**Comment by Kotodian** [comment]
<img width="1560" alt="image" src="https://user-images.githubusercontent.com/22030659/210046653-6043f824-f9c3-41c0-89a1-a2db011b8699.png">

**Comment by ayamir** [comment]
https://user-images.githubusercontent.com/61657399/210047015-f9fce4d7-a0a6-4bb9-ac11-735acc75a074.mp4


https://user-images.githubusercontent.com/61657399/210047035-939f1a1c-28b7-4fd3-a450-65886b33a4f2.mp4

**Comment by Kotodian** [comment]
<img width="1105" alt="image" src="https://user-images.githubusercontent.com/22030659/210048381-d99beb30-d250-49cc-b502-dc3ee81dd708.png">
Maybe is it the problem?

**Comment by CharlesChiuGit** [comment]
can u tried disable "neodim", and see will the problem fixed?

ps. neodim is in the "ui" folder

**Comment by Kotodian** [comment]
> can u tried disable "neodim", and see will the problem fixed?
> 
> ps. neodim is in the "ui" folder

I tried it and I tried to use other terminal which is from the article in zhihu, the problem is still here.

**Comment by Jint-lzxy** [comment]
@ayamir I found a possible reason: when the opened file is under git's management, this problem will not occur.

**Reproduction steps:**
1. `mkdir nvim-tree-test && cd nvim-tree-test`
2. `touch foo.txt`
3. `nvim`
4. Open `foo.txt` using nvim-tree.
5. See problem
6. `:q!`
7. `git init`
8. `nvim`
9. Open `foo.txt` using nvim-tree again.
10. Problem disappears.

**Comment by Jint-lzxy** [comment]
I will bisect recent commits of `nvim-tree` later to see if it is an upstream issue, as this problem did not exist a few days ago.

**Comment by ayamir** [comment]
> I found a possible reason: when the opened file is under git's management, this problem will not occur.

It's true.

**Comment by CharlesChiuGit** [comment]
> @ayamir I found a possible reason: when the opened file is under git's management, this problem will not occur.
> 
> **Reproduction steps:**
>     1. `mkdir nvim-tree-test && cd nvim-tree-test`
>     2. `touch foo.txt`
>     3. `nvim`
>     4. Open `foo.txt` using nvim-tree.
>     5. See problem
>     6. `:q!`
>     7. `git init`
>     8. `nvim`
>     9. Open `foo.txt` using nvim-tree again.
>     10. Problem disappears.

I somehow still can't reproduce this issue with non-git folder.

![圖片](https://user-images.githubusercontent.com/32497323/210085498-9995165f-5460-4be8-a735-69d32663e1a2.png)

**Comment by Xxh-v** [comment]
I have a similar problem.
<img width="1280" alt="截屏2022-12-31 04 42 06" src="https://user-images.githubusercontent.com/112311757/210110338-55f222c0-ff51-4f19-8f2b-00da9879dc70.png">

**Comment by ayamir** [comment]
> 

Maybe because the current work directory is recognized correctly.

**Comment by ayamir** [comment]
> 这么做了以后，第一次是能够打开文件的，但是第二次打开其他文件就是直接打不开了,

`NvimTree` will be closed after last buffer was closed, so open file then is invalid.
Note: this feature has been fixed at cf70b30e1c12f23dc4f5ee393a744a87ac9f61c3

**Comment by ayamir** [comment]
I can confirm https://github.com/ayamir/nvimdots/pull/392 has fixed this problem.

**Comment by ayamir** [comment]
> I have a similar problem. <img alt="截屏2022-12-31 04 42 06" width="1280" src="https://user-images.githubusercontent.com/112311757/210110338-55f222c0-ff51-4f19-8f2b-00da9879dc70.png">

How to reproduce it? Does it have to do with this issue? Feel free to open a new issue to solve it.

**Comment by Jint-lzxy** [comment]
I just checked the commits of `nvim-tree`, and it can be confirmed that this is not an upstream issue. I'll try to use a minimal config that only includes `nvim-tree` and `alpha` to check whether the problem is from `alpha` or the configuration.

> I can confirm #392 has fixed this problem.

If #392 can solve this problem, then one of the components in `nvim-window-picker` is effective. However, we haven't determined the reason behind this issue _yet_. Will merge this as a temporary workaround.

I will investigate this issue in detail in a few days 👍

**Comment by CharlesChiuGit** [comment]
> I just checked the commits of `nvim-tree`, and it can be confirmed that this is not an upstream issue. I'll try to use a minimal config that only includes `nvim-tree` and `alpha` to check whether the problem is from `alpha` or the configuration.
> 
> > I can confirm #392 has fixed this problem.
> 
> If #392 can solve this problem, then one of the components in `nvim-window-picker` is effective. However, we haven't determined the reason behind this issue _yet_. Will merge this as a temporary workaround.
> 
> I will investigate this issue in detail in a few days 👍

Thanks for your investigation!

**Comment by Jint-lzxy** [comment]
Update: This issue cannot be reproduced using the minimal config above. The scope of the issue has been limited to the `ui` folder - the problem occurs again when all ui-related plugins are added.

**Comment by Jint-lzxy** [comment]
Can confirm that this is an upstream issue _(a minimal config that only contains `packer`, `alpha` and `nvim-tree` also has this problem)_.

**Comment by Jint-lzxy** [comment]
**Update: The source of this issue has been located.**

Under the situation described in this issue, `nvim-tree` will open the file without any legal window id to select _(excluding itself)_. It would call [`pick_win_id()`](https://github.com/nvim-tree/nvim-tree.lua/blob/9e87ee2d6e86f37ff09cb74ec7dcf2ac984a01e9/lua/nvim-tree/actions/node/open-file.lua#L52) and get `-1`. Hence, according to [these lines](https://github.com/nvim-tree/nvim-tree.lua/blob/9e87ee2d6e86f37ff09cb74ec7dcf2ac984a01e9/lua/nvim-tree/actions/node/open-file.lua#L189-L191), `nvim-tree` will return `require("nvim-tree.lib").target_winid` instead.

In some extreme cases such as https://github.com/ayamir/nvimdots/issues/391#issuecomment-13678270050, the variable is **incorrectly set to `0`** _(which is the initial value)_. The correct value should be `1000` instead _(i.e., `nvim-tree` ignores the window where `alpha` is located)_. `nvim-window-picker` can address this issue because it always returns `1000` in this scenario.

**Comment by Jint-lzxy** [comment]
#436 should fix this issue.
