### ISSUE TITLE
Treesitter highlights broken due to `query: invalid node type`

### ISSUE THREAD

**Issue by hhcwyx** [ayamir/nvimdots#393]
### Neovim version

NVIM0.8.2

### Operating system/version

archlinux

### Terminal name/version

alacritty

### Branch info

main (Default/Latest)

### Fetch Preferences

SSH (use_ssh = true)

### How to reproduce the issue

编写python文件时,总是出现一些信息,比如:
print('hello world') treesitter/highlighter:Error executing lua:/usr/share/nvim/runtime/lua/vim/treesitter/query.lua:219 :querry: invalid node type at position 6469 for language python 

### Expected behavior

怎么把这些信息屏蔽掉呢?

**Comment by ayamir** [comment]
Perhaps it can be solved by reinstall python's parser.
`:TSInstall python` then type `y` and enter.

**Comment by Jint-lzxy** [comment]
@ayamir Some languages require _parser generator_ support from the `tree-sitter` executable _(that is, `:TSInstallFromGrammar`)_. We should explain this in the wiki _(Note: Depending on the platform, the package name can be `tree-sitter` or `tree-sitter-cli`. If installing one of them has no effect, the other should be tried. As the `tree-sitter` installation from some package managers is not globally accessible, then `nvim-treesitter` cannot locate it correctly.)_ For example:
```console
brew install tree-sitter
yarn global add tree-sitter-cli
cargo install tree-sitter-cli
```
***
@hhcwyx If installing `tree-sitter` and then recompiling the parsers does not solve the problem, this happens because,  after an update to `nvim-treesitter` or a related plugin, you have updated queries but **not** the corresponding parser _(or vice versa)_, but queries are only compatible with specific parser versions, leading to errors if they no longer match. Try the following steps:

1. Make sure that `nvim-treesitter` is updated to the latest commit and run `:TSUpdate` manually.
2. If the error persists, remove `nvim-treesitter` completely and reinstall it together with **all** parsers.
3. If the error still persists, run `:checkhealth` and note down the languages for which you see errors _(an x in the list of languages, and explicitly listed below that)._ For each language `<lang>`, repeat the following steps:
  - `:TSInstall! <lang>` and restart nvim; if the error persists, continue.
  - Run the following commands and note down the output:
```vim
:echo nvim_get_runtime_file('*/<lang>.so', v:true)
:echo nvim_get_runtime_file('queries/<lang>/*.scm', v:true)
```
  - If either of these lists contain a directory that is not a subdirectory of nvim-treesitter, remove that directory _(and, if it is another plugin, report the issue at the corresponding repository)._
****
_(Since 0.8.0, Neovim bundles parsers and queries for `c`, `lua`, `vim`, and `help`. We must make sure these parsers are installed via `nvim-treesitter` so that both parser and queries _(which are always installed)_ are taken from nvim-treesitter. Hence it's important the `nvim-treesitter` plugin directory comes before both `/usr/local/share/nvim/*` and `/usr/lib/nvim` in rtp.)_

**Comment by JerryAllison** [comment]
Error in decoration provider treesitter/highlighter.line:
Error executing lua: ...l/share/nvim/site/lazy/neodim/lua/neodim/ts_override.lua:21: attempt to call method 'get_highlight_state' (a nil value)
stack traceback:
        ...l/share/nvim/site/lazy/neodim/lua/neodim/ts_override.lua:21: in function 'fn'
        ...0/share/nvim/runtime/lua/vim/treesitter/languagetree.lua:491: in function 'for_each_tree'
        ...l/share/nvim/site/lazy/neodim/lua/neodim/ts_override.lua:15: in function 'on_line_impl'
        ...l/share/nvim/site/lazy/neodim/lua/neodim/ts_override.lua:96: in function <...l/share/nvim/site/lazy/neodim/lua/neodim/ts_override.lua:90>

今天更新的版本老是出现这样的问题，很烦人啊

**Comment by ayamir** [comment]
> Error in decoration provider treesitter/highlighter.line: Error executing lua: ...l/share/nvim/site/lazy/neodim/lua/neodim/ts_override.lua:21: attempt to call method 'get_highlight_state' (a nil value) stack traceback: ...l/share/nvim/site/lazy/neodim/lua/neodim/ts_override.lua:21: in function 'fn' ...0/share/nvim/runtime/lua/vim/treesitter/languagetree.lua:491: in function 'for_each_tree' ...l/share/nvim/site/lazy/neodim/lua/neodim/ts_override.lua:15: in function 'on_line_impl' ...l/share/nvim/site/lazy/neodim/lua/neodim/ts_override.lua:96: in function <...l/share/nvim/site/lazy/neodim/lua/neodim/ts_override.lua:90>
> 
> 最近更新的版本老是出现这样的问题，很烦人啊

`:Lazy sync`

**Comment by kagurazaka-ayano** [comment]
> > Error in decoration provider treesitter/highlighter.line: Error executing lua: ...l/share/nvim/site/lazy/neodim/lua/neodim/ts_override.lua:21: attempt to call method 'get_highlight_state' (a nil value) stack traceback: ...l/share/nvim/site/lazy/neodim/lua/neodim/ts_override.lua:21: in function 'fn' ...0/share/nvim/runtime/lua/vim/treesitter/languagetree.lua:491: in function 'for_each_tree' ...l/share/nvim/site/lazy/neodim/lua/neodim/ts_override.lua:15: in function 'on_line_impl' ...l/share/nvim/site/lazy/neodim/lua/neodim/ts_override.lua:96: in function <...l/share/nvim/site/lazy/neodim/lua/neodim/ts_override.lua:90>
> > 最近更新的版本老是出现这样的问题，很烦人啊
> 
> `:Lazy sync`

After `:Lazy sync` the error persists.

Error message:

```
Error in decoration provider treesitter/highlighter.line:
Error executing lua: ...l/share/nvim/site/lazy/neodim/lua/neodim/ts_override.lua:21: attempt to call method 'get_highlight_state' (a nil value)
stack traceback:
        ...l/share/nvim/site/lazy/neodim/lua/neodim/ts_override.lua:21: in function 'fn'
        ...0/share/nvim/runtime/lua/vim/treesitter/languagetree.lua:491: in function 'for_each_tree'
        ...l/share/nvim/site/lazy/neodim/lua/neodim/ts_override.lua:15: in function 'on_line_impl'
        ...l/share/nvim/site/lazy/neodim/lua/neodim/ts_override.lua:96: in function <...l/share/nvim/site/lazy/neodim/lua/neodim/ts_override.lua:90>
```

**Comment by kagurazaka-ayano** [comment]
> > > Error in decoration provider treesitter/highlighter.line: Error executing lua: ...l/share/nvim/site/lazy/neodim/lua/neodim/ts_override.lua:21: attempt to call method 'get_highlight_state' (a nil value) stack traceback: ...l/share/nvim/site/lazy/neodim/lua/neodim/ts_override.lua:21: in function 'fn' ...0/share/nvim/runtime/lua/vim/treesitter/languagetree.lua:491: in function 'for_each_tree' ...l/share/nvim/site/lazy/neodim/lua/neodim/ts_override.lua:15: in function 'on_line_impl' ...l/share/nvim/site/lazy/neodim/lua/neodim/ts_override.lua:96: in function <...l/share/nvim/site/lazy/neodim/lua/neodim/ts_override.lua:90>
> > > 最近更新的版本老是出现这样的问题，很烦人啊
> > 
> > 
> > `:Lazy sync`
> 
> After `:Lazy sync` the error persists.
> 
> Error message:
> 
> ```
> Error in decoration provider treesitter/highlighter.line:
> Error executing lua: ...l/share/nvim/site/lazy/neodim/lua/neodim/ts_override.lua:21: attempt to call method 'get_highlight_state' (a nil value)
> stack traceback:
>         ...l/share/nvim/site/lazy/neodim/lua/neodim/ts_override.lua:21: in function 'fn'
>         ...0/share/nvim/runtime/lua/vim/treesitter/languagetree.lua:491: in function 'for_each_tree'
>         ...l/share/nvim/site/lazy/neodim/lua/neodim/ts_override.lua:15: in function 'on_line_impl'
>         ...l/share/nvim/site/lazy/neodim/lua/neodim/ts_override.lua:96: in function <...l/share/nvim/site/lazy/neodim/lua/neodim/ts_override.lua:90>
> ```

nevermind, the problem is resolved after I reinstalled the plugin

**Comment by kagurazaka-ayano** [comment]
> > > Error in decoration provider treesitter/highlighter.line: Error executing lua: ...l/share/nvim/site/lazy/neodim/lua/neodim/ts_override.lua:21: attempt to call method 'get_highlight_state' (a nil value) stack traceback: ...l/share/nvim/site/lazy/neodim/lua/neodim/ts_override.lua:21: in function 'fn' ...0/share/nvim/runtime/lua/vim/treesitter/languagetree.lua:491: in function 'for_each_tree' ...l/share/nvim/site/lazy/neodim/lua/neodim/ts_override.lua:15: in function 'on_line_impl' ...l/share/nvim/site/lazy/neodim/lua/neodim/ts_override.lua:96: in function <...l/share/nvim/site/lazy/neodim/lua/neodim/ts_override.lua:90>
> > > 最近更新的版本老是出现这样的问题，很烦人啊
> > 
> > 
> > `:Lazy sync`
> 
> After `:Lazy sync` the error persists.
> 
> Error message:
> 
> ```
> Error in decoration provider treesitter/highlighter.line:
> Error executing lua: ...l/share/nvim/site/lazy/neodim/lua/neodim/ts_override.lua:21: attempt to call method 'get_highlight_state' (a nil value)
> stack traceback:
>         ...l/share/nvim/site/lazy/neodim/lua/neodim/ts_override.lua:21: in function 'fn'
>         ...0/share/nvim/runtime/lua/vim/treesitter/languagetree.lua:491: in function 'for_each_tree'
>         ...l/share/nvim/site/lazy/neodim/lua/neodim/ts_override.lua:15: in function 'on_line_impl'
>         ...l/share/nvim/site/lazy/neodim/lua/neodim/ts_override.lua:96: in function <...l/share/nvim/site/lazy/neodim/lua/neodim/ts_override.lua:90>
> ```

Problem is resolved by reemoving the version requirement of zbirenbaum/neodim

**Comment by stephen-nju** [comment]
> > > > Error in decoration provider treesitter/highlighter.line: Error executing lua: ...l/share/nvim/site/lazy/neodim/lua/neodim/ts_override.lua:21: attempt to call method 'get_highlight_state' (a nil value) stack traceback: ...l/share/nvim/site/lazy/neodim/lua/neodim/ts_override.lua:21: in function 'fn' ...0/share/nvim/runtime/lua/vim/treesitter/languagetree.lua:491: in function 'for_each_tree' ...l/share/nvim/site/lazy/neodim/lua/neodim/ts_override.lua:15: in function 'on_line_impl' ...l/share/nvim/site/lazy/neodim/lua/neodim/ts_override.lua:96: in function <...l/share/nvim/site/lazy/neodim/lua/neodim/ts_override.lua:90>
> > > > 最近更新的版本老是出现这样的问题，很烦人啊
> > > 
> > > 
> > > `:Lazy sync`
> > 
> > 
> > After `:Lazy sync` the error persists.
> > Error message:
> > ```
> > Error in decoration provider treesitter/highlighter.line:
> > Error executing lua: ...l/share/nvim/site/lazy/neodim/lua/neodim/ts_override.lua:21: attempt to call method 'get_highlight_state' (a nil value)
> > stack traceback:
> >         ...l/share/nvim/site/lazy/neodim/lua/neodim/ts_override.lua:21: in function 'fn'
> >         ...0/share/nvim/runtime/lua/vim/treesitter/languagetree.lua:491: in function 'for_each_tree'
> >         ...l/share/nvim/site/lazy/neodim/lua/neodim/ts_override.lua:15: in function 'on_line_impl'
> >         ...l/share/nvim/site/lazy/neodim/lua/neodim/ts_override.lua:96: in function <...l/share/nvim/site/lazy/neodim/lua/neodim/ts_override.lua:90>
> > ```
> 
> Problem is resolved by removing the version requirement of zbirenbaum/neodim

Thanks ,very helpfull. But the  version of neovim might be  NVIM v0.10.0 or later? The newest version v0.11 still has this problem

**Comment by kagurazaka-ayano** [comment]
> > > > > Error in decoration provider treesitter/highlighter.line: Error executing lua: ...l/share/nvim/site/lazy/neodim/lua/neodim/ts_override.lua:21: attempt to call method 'get_highlight_state' (a nil value) stack traceback: ...l/share/nvim/site/lazy/neodim/lua/neodim/ts_override.lua:21: in function 'fn' ...0/share/nvim/runtime/lua/vim/treesitter/languagetree.lua:491: in function 'for_each_tree' ...l/share/nvim/site/lazy/neodim/lua/neodim/ts_override.lua:15: in function 'on_line_impl' ...l/share/nvim/site/lazy/neodim/lua/neodim/ts_override.lua:96: in function <...l/share/nvim/site/lazy/neodim/lua/neodim/ts_override.lua:90>
> > > > > 最近更新的版本老是出现这样的问题，很烦人啊
> > > > 
> > > > 
> > > > `:Lazy sync`
> > > 
> > > 
> > > After `:Lazy sync` the error persists.
> > > Error message:
> > > ```
> > > Error in decoration provider treesitter/highlighter.line:
> > > Error executing lua: ...l/share/nvim/site/lazy/neodim/lua/neodim/ts_override.lua:21: attempt to call method 'get_highlight_state' (a nil value)
> > > stack traceback:
> > >         ...l/share/nvim/site/lazy/neodim/lua/neodim/ts_override.lua:21: in function 'fn'
> > >         ...0/share/nvim/runtime/lua/vim/treesitter/languagetree.lua:491: in function 'for_each_tree'
> > >         ...l/share/nvim/site/lazy/neodim/lua/neodim/ts_override.lua:15: in function 'on_line_impl'
> > >         ...l/share/nvim/site/lazy/neodim/lua/neodim/ts_override.lua:96: in function <...l/share/nvim/site/lazy/neodim/lua/neodim/ts_override.lua:90>
> > > ```
> > 
> > 
> > Problem is resolved by removing the version requirement of zbirenbaum/neodim
> 
> Thanks ,very helpfull. But the version of neovim might be NVIM v0.10.0 or later? The newest version v0.11 still has this problem

yes but this version requirement is removed in the [0.10 branch](https://github.com/ayamir/nvimdots/blob/086bb81a82ffa78812c23e68363ded7b7a305006/lua/modules/plugins/ui.lua#L39). Maybe check that branch out.
