### ISSUE TITLE
Treesitter parsers failed to install

### ISSUE THREAD

**Issue by hhcwyx** [ayamir/nvimdots#395]
### Neovim version

NVIM0.8.2

### Operating system/version

archlinux

### Terminal name/version

alacritty

### Branch info

main (Default/Latest)

### Fetch Preferences

SSH (use_ssh = true)

### How to reproduce the issue

启动nvim,创建一个新文件,点击i准备输入内容时,出现以下信息:
[nvim-treesitter] [0/17] Downloading tree-sitter-css...
nvim-treesitter[lua]: Error during download, please verify your internet connection
请按 ENTER 或其它命令继续
nvim-treesitter[go]: Error during download, please verify your internet connection
请按 ENTER 或其它命令继续
请按 ENTER 或其它命令继续
nvim-treesitter[gomod]: Error during download, please verify your internet connection
请按 ENTER 或其它命令继续
请按 ENTER 或其它命令继续
nvim-treesitter[json]: Error during download, please verify your internet connection
请按 ENTER 或其它命令继续
请按 ENTER 或其它命令继续
nvim-treesitter[latex]: Error during download, please verify your internet connection
请按 ENTER 或其它命令继续
请按 ENTER 或其它命令继续
nvim-treesitter[javascript]: Error during download, please verify your internet connection

请按 ENTER 或其它命令继续
不知道怎么回事?我的网是正常的啊,浏览器访问github也是能访问的啊.

### Expected behavior

怎么才能正常安装,消除以上信息.

**Comment by CharlesChiuGit** [comment]
Does this kind of error only happens when creating new files?

**Comment by CharlesChiuGit** [comment]
Did all the parsers install successfully when you install this repo for the first time?

**Comment by ayamir** [comment]
Have you configured the `ssh` config for accessing github? If not, please use https to update plugins and download treesitter parser.
change `true` to `false` then open file
https://github.com/ayamir/nvimdots/blob/5ccb4b6f2c843b7baa5bcb6f25a4a2088a719917/lua/core/settings.lua#L4

**Comment by hhcwyx** [comment]
> 
设置了ssh,检查了nvimdots/lua/core/settings.lua 第四行没问题.
我用:TSInstall lua 手动试了一下,成功了,但是并不是所有的都成功,比如
TSInstall yaml就没成功.

**Comment by hhcwyx** [comment]
我用:nvim +PackerSync 是正常的.

**Comment by CharlesChiuGit** [comment]
> 还有一个现象就是,使用sapce+f+n 创建新文件,会先弹出以下信息: 处理 InsertEnter 自动命令 "*" 时发生错误: Error executing lua callback: ...ite/pack/packer/opt/copilot-cmp/lua/copilot_cmp/init.lua: 44: module 'cmp' not found: ...

Can confirm, will do a PR to fix this issue.

**Comment by hhcwyx** [comment]
谢谢

**Comment by CharlesChiuGit** [comment]
@hhcwyx Can you help me verifying whether #397 fix `cmp not found` issue when opening a new file?

**Comment by hhcwyx** [comment]
@CharlesChiuGit  按照#397给出的指导,修改了相关文件,当使用space+f+n 创建新文件时:还是有以下信息输出:


packer.nvim: Error running config for neodim: ...are/nvim/site/pack/packer/opt/neodim/lua/neodim/util.lua:3: module 'nvim-treesitter.ts_utils' not found:
	no field package.preload['nvim-treesitter.ts_utils']
	no file './nvim-treesitter/ts_utils.lua'
	no file '/usr/share/luajit-2.1.0-beta3/nvim-treesitter/ts_utils.lua'
	no file '/usr/local/share/lua/5.1/nvim-treesitter/ts_utils.lua'
	no file '/usr/local/share/lua/5.1/nvim-treesitter/ts_utils/init.lua'
	no file '/usr/share/lua/5.1/nvim-treesitter/ts_utils.lua'
	no file '/usr/share/lua/5.1/nvim-treesitter/ts_utils/init.lua'
	no file '/home/hhc/.cache/nvim/packer_hererocks/2.1.0-beta3/share/lua/5.1/nvim-treesitter/ts_utils.lua'
	no file '/home/hhc/.cache/nvim/packer_hererocks/2.1.0-beta3/share/lua/5.1/nvim-treesitter/ts_utils/init.lua'
	no file '/home/hhc/.cache/nvim/packer_hererocks/2.1.0-beta3/lib/luarocks/rocks-5.1/nvim-treesitter/ts_utils.lua'
	no file '/home/hhc/.cache/nvim/packer_hererocks/2.1.0-beta3/lib/luarocks/rocks-5.1/nvim-treesitter/ts_utils/init.lua'
	no file './nvim-treesitter/ts_utils.so'
	no file '/usr/local/lib/lua/5.1/nvim-treesitter/ts_utils.so'
	no file '/usr/lib/lua/5.1/nvim-treesitter/ts_utils.so'
	no file '/usr/local/lib/lua/5.1/loadall.so'
	no file '/home/hhc/.cache/nvim/packer_hererocks/2.1.0-beta3/lib/lua/5.1/nvim-treesitter/ts_utils.so'
	no file './nvim-treesitter.so'
	no file '/usr/local/lib/lua/5.1/nvim-treesitter.so'
	no file '/usr/lib/lua/5.1/nvim-treesitter.so'
	no file '/usr/local/lib/lua/5.1/loadall.so'
	no file '/home/hhc/.cache/nvim/packer_hererocks/2.1.0-beta3/lib/lua/5.1/nvim-treesitter.so'

**Comment by CharlesChiuGit** [comment]
Ok, got it. It's another issue relate to `neodim`, I'll try to fix it as well.

**Comment by hhcwyx** [comment]
@CharlesChiuGit 谢谢!

**Comment by CharlesChiuGit** [comment]
@hhcwyx I just commited it, please try it.

**Comment by CharlesChiuGit** [comment]
@hhcwyx So does treesitter parser can be installed successfully now? Or is there still some parsers can not be installed?

**Comment by hhcwyx** [comment]
@CharlesChiuGit 一切都正常了,谢谢老师!
