### ISSUE TITLE
`nvim-ts-rainbow` is no longer maintained.

### ISSUE THREAD

**Issue by CharlesChiuGit** [ayamir/nvimdots#396]
https://github.com/p00f/nvim-ts-rainbow/commit/ef95c15a935f97c65a80e48e12fe72d49aacf9b9

From the author:
> This plugin is no longer maintained.
> I'm archiving the GitHub repo and closing the sourcehut issue tracker. Feel free to fork

It might not be a big problem in short term of time, but maybe we need to find a substitute fork/plugin after all.

other nvim configs using `nvim-ts-rainbow`: 

https://github.com/AstroNvim/AstroNvim/blob/1eb976ecc6893af46312ccc83ed6b7c01796e502/lua/core/plugins.lua#L130

**Comment by ayamir** [comment]
Maybe we can try this: https://github.com/luochen1990/rainbow

**Comment by ayamir** [comment]
> Maybe we can try this: https://github.com/luochen1990/rainbow

Tried, but no effect.

**Comment by mathjiajia** [comment]
https://github.com/HiPhish/nvim-ts-rainbow2

**Comment by CharlesChiuGit** [comment]
@mathjiajia Is this plugin a pure fork of `nvim-ts-rainbow` or it has some cool feature on it's own?

**Comment by mathjiajia** [comment]
This author takes over this work, I guess.
Note: there are some changes, such as the highlights `rainbow1` -> `TSRainbowRed` and so on.

**Comment by CharlesChiuGit** [comment]
It seems `rainbow2` has gone through a lots of refactoring, cool! 
But maybe we need to test it's stability, thanks for suggestion!

**Comment by Jint-lzxy** [comment]
FWIW We should at least wait until the mainstream colorschemes finish their update before considering using this plugin, otherwise many dependent highlight groups will not work.

**Comment by CharlesChiuGit** [comment]
https://github.com/mrjones2014/nvim-ts-rainbow
A new maintained fork, recommended by TWiN

**Comment by CharlesChiuGit** [comment]
Other forks available: https://techgaun.github.io/active-forks/index.html#https://github.com/p00f/nvim-ts-rainbow

**Comment by ayamir** [comment]
I think it's time to chore to https://github.com/mrjones2014/nvim-ts-rainbow.

**Comment by ayamir** [comment]
eb2a5b92dbedc999b0fa092766959e04d9872e32
