### ISSUE TITLE
顶层展示栏不持续占位导致光标移动时代码频繁跳动

### ISSUE THREAD

**Issue by fengxuway** [ayamir/nvimdots#398]
### Neovim version

NVIM v0.8.1

### Operating system/version

macOS 12.5.1

### Terminal name/version

iTerm2 Build 3.4.18

### Branch info

main (Default/Latest)

### Fetch Preferences

HTTPS (use_ssh = false)

### How to reproduce the issue

使用最新的配置，打开 go 代码文件，顶层的层级展示栏在空代码时不占位，在有结构的代码时占位
![demo](https://user-images.githubusercontent.com/17471078/210473349-b5173a8f-e4c0-406a-8ea5-71d52d89bcb2.gif)

### Expected behavior

预期能一直占位，防止出现图中的文件所有代码跟着抖动现象

### Actual behavior

-

### Additional information

-

**Comment by Jint-lzxy** [comment]
This _is_ the design of `lspsaga`. I'm trying to integrate it into `lualine` to avoid this problem.

**Comment by fengxuway** [comment]
大佬神速啊~ 
刚更新了配置，还有点点问题。目前的配置是将当前屏幕第一行覆盖掉用来展示层级信息，但如果展示首屏（能看到第一行）就还是一样的问题：
![demo2](https://user-images.githubusercontent.com/17471078/210475282-46b18a8e-863f-4013-91cd-450d21893714.gif)
麻烦大佬再看看有啥办法没

**Comment by ayamir** [comment]
你`git pull`之后没有`PackerCompile`过吧，现在winbar总是展示文件名，不会出现这个问题了

**Comment by CharlesChiuGit** [comment]
@fengxuway If you want to keep the current setup, you can upgrade your neovim to nightly(0.9.0) to avoid this rendering issue.
![圖片](https://user-images.githubusercontent.com/32497323/210506223-d8eb8573-fc5d-4c77-aa14-eaf767a8c0e7.png)
