### ISSUE TITLE
请教如何关闭当前已打开的文件，但不关闭当前 buffer 呢

### ISSUE THREAD

**Issue by fengxuway** [ayamir/nvimdots#399]
### Feature description

刚接触 neovim，有些快捷键不太了解。如图这样的关闭当前文件，或关闭非当前文件有快捷键吗？
<img width="758" alt="image" src="https://user-images.githubusercontent.com/17471078/210474161-9a1ec9ad-32ac-40f2-83a2-513e0bd7db40.png">

我试过执行
```
:q

:close 
```
这几个都会将当前 buffer 关闭导致 nvim 退出。

另外这套配置有快捷键参考列表嘛，对萌新更友好一些

**Comment by fengxuway** [comment]
嗯啊，多谢解答~

**Comment by Saton-anger** [comment]
I found that I could not use <A-q> to close the current buffer, it just did not have any response. However, I do can close the whole window using the key binding <A-S-q>. I was quite confused about that.

**Comment by Saton-anger** [comment]
I have tried to close the recent buffer using the keybinding `<A-q>`, but it just did not have any response. However, I can do close the whole window pressing `<A-S-q>`. I am quite confused about that.

**Comment by ayamir** [comment]
> I have tried to close the recent buffer using the keybinding <A-q>, but it just did not have any response.

https://github.com/ayamir/nvimdots/blob/d425bfdc4f4d1f36d0ac1b452a58ef83f055ce20/lua/keymap/editor.lua#L23

> However, I can do close the whole window pressing <A-S-q>.

https://github.com/ayamir/nvimdots/blob/d425bfdc4f4d1f36d0ac1b452a58ef83f055ce20/lua/core/mapping.lua#L29

**Comment by Saton-anger** [comment]
this is the current state of my key mapping settings
<img width="798" alt="截屏2023-07-23 01 15 01" src="https://github.com/ayamir/nvimdots/assets/79832629/e5826f26-545b-4a20-86bd-3190e7a4f02e">
<img width="553" alt="截屏2023-07-23 01 18 12" src="https://github.com/ayamir/nvimdots/assets/79832629/76d5c260-996d-4e02-9096-5ec4d9f28090">
Looks like there is nothing wrong with the settings.

**Comment by Jint-lzxy** [comment]
What u mean by "just did not have any response"? And what did u do before this (how to reproduce this)?

**Comment by Saton-anger** [comment]
Sorry for the vague description.

'just did not have any response' means when I pressed `<A-q>`, it did not close the current buffer as expected.

To reproduce the results, the app I use is iTerm2, and my device is M1 pro macbook pro, first of all, I type `nvim` and opened several python files, when I was trying to close one of the files (I guess it is called 'buffer', so this action can be called 'close the current buffer'?) by typing `<A-q>`, I found that the current file was not closed. I also tried other key bindings like `<A-S-q>` to test whether my `Alt` key works, and it turned out that `<A-S-q>` do close the current window, which means my `Alt` key works well.

**Comment by Jint-lzxy** [comment]
@Saton-anger Did you make any modifications to these files externally? Any move or deletion will invalidate the file handle held by the current buffer, leading to failures in closing such buffers.

Added to that, what you see when using `:BufDel!` in those buffers?

**Comment by Saton-anger** [comment]
I had modified them with vscode. But when I saved the files, quit the vscode to make sure no external modificaitons to those files and reopen those files with terminal and nvim, I still can not close the current buffer using `<A-q>`, however, I can do close them using `:BufDel!` or `BufDel`.

**Comment by Jint-lzxy** [comment]
Did you close this buffer (via `<A-q>`) in normal mode?

**Comment by Saton-anger** [comment]
seems like this is the normal mode,


<img width="1711" alt="截屏2023-07-23 14 48 33" src="https://github.com/ayamir/nvimdots/assets/79832629/9d058d77-781e-4c14-b8a1-1242112c5ce3">

 I tried to close the current buffer using `<A-q>` in this mode.

**Comment by Jint-lzxy** [comment]
Does clicking on the close button of this buffer in bufferline help?

**Comment by Saton-anger** [comment]
Actually it closed the whole window.
<img width="826" alt="截屏2023-07-23 14 52 00" src="https://github.com/ayamir/nvimdots/assets/79832629/fedfbf9f-e78b-4654-9d11-2b2df6401229">

**Comment by Saton-anger** [comment]
which means both of the two buffers were closed.

**Comment by Jint-lzxy** [comment]
Hmm this is strange... Can you provide a _complete_ repro (with detailed steps, including those corresponding files if possible)? I can't reproduce this with iTerm2.

**Comment by Jint-lzxy** [comment]
And did u follow #344 to setup ur profile correctly?

**Comment by Saton-anger** [comment]
This is the settings of my profile and I use the left option:
<img width="657" alt="截屏2023-07-23 15 02 31" src="https://github.com/ayamir/nvimdots/assets/79832629/8dcabfa0-5740-42cd-a639-414fddcaa605">
<img width="826" alt="截屏2023-07-23 14 52 00" src="https://github.com/ayamir/nvimdots/assets/79832629/fa7db0e4-d612-4905-a3a7-c3790b02e703">

**Comment by Jint-lzxy** [comment]
Thanks for the info! But a _complete_ repro is still necessary, otherwise we don't know where the problem lies.

**Comment by Saton-anger** [comment]
Ok, thanks. Should I open a new issue to proffer a complete repro?

**Comment by Jint-lzxy** [comment]
That would be appreciated, cause this sounds like a bug somewhere.

**Comment by Saton-anger** [comment]
OK, thanks again for your time.
