### ISSUE TITLE
nvim icon 乱码

### ISSUE THREAD

**Issue by MingChaoXu** [ayamir/nvimdots#4]
请问nvim乱码是什么原因呢？
![截屏2021-07-15 下午7 52 37 (2)](https://user-images.githubusercontent.com/8822286/125783708-4d99f114-bb40-4872-9af0-a60cbfa36030.png)
还有开始界面的这个warning怎么去掉呀？

**Comment by MingChaoXu** [comment]
<img width="1440" alt="截屏2021-07-15 下午7 52 37" src="https://user-images.githubusercontent.com/8822286/125783808-1825114b-9761-4fbc-b052-72a261c29337.png">
发错图了，是这张

**Comment by MingChaoXu** [comment]
这个warning我解决了，chmod修改一下相应的文件权限即可，但是这个icon怎么获得我还没懂？好像是这个插件是吧：https://github.com/kyazdani42/nvim-web-devicons
但是这个readme里面的函数用什么方式运行呢？

**Comment by ayamir** [comment]
> <img alt="截屏2021-07-15 下午7 52 37" width="1440" src="https://user-images.githubusercontent.com/8822286/125783808-1825114b-9761-4fbc-b052-72a261c29337.png">
> 
> 发错图了，是这张

已经解决

**Comment by JasenChao** [comment]
> > <img alt="截屏2021-07-15 下午7 52 37" width="1440" src="https://user-images.githubusercontent.com/8822286/125783808-1825114b-9761-4fbc-b052-72a261c29337.png">
> > 发错图了，是这张
> 
> 已经解决

能问一下怎么解决的吗。。。我貌似一样的问题

**Comment by ayamir** [comment]
终端使用nerd font

**Comment by JasenChao** [comment]
> 

牛！困扰了我一天的问题，原来是这样子。感谢！
