### ISSUE TITLE
`<leader>fw` reports an error instead of opening `live_grep` preview

### ISSUE THREAD

**Issue by goodpaperman** [ayamir/nvimdots#406]
![图片](https://user-images.githubusercontent.com/8522640/210741410-56c28cc8-3bea-495e-b112-2abec88be479.png)

:Telescope live_grep works，but short-cuts not

**Comment by CharlesChiuGit** [comment]
Can't reproduce on latest commit, please update nvim config.
Also please follow the issue template.

**Comment by ayamir** [comment]
close due to **no response** and **invalid**.

**Comment by goodpaperman** [comment]
upgrade to v1.0.0 version,  problem resolved, thanks a lot
