### ISSUE TITLE
coc 配置文件下 vue文件字体高亮和主题颜色冲突

### ISSUE THREAD

**Issue by CrazyGriferman** [ayamir/nvimdots#41]
我在coc配置的基础上安装了以下几个包
Plug 'pangloss/vim-javascript', { 'for': ['javascript', 'javascript.jsx', 'html', 'vue'] }
Plug 'leafgarland/typescript-vim'
Plug 'peitalin/vim-jsx-typescript'
Plug 'mxw/vim-jsx'
Plug 'leafOfTree/vim-vue-plugin'

然后当我进入vue文件中时，script tag下的所有字符全都是 onehalf主题的statement所定义的purple颜色。
/onehalf/vim/colors/onehalflight.vim
136 行 call s:h("Statement", s:purple, "", "")
![image](https://user-images.githubusercontent.com/51702723/140008118-2612fda7-fed2-4da4-9fdc-2eff3832a10b.png)

但是当我选中这些字符的时候，它的颜色就变为了vim-vue-plugin支持的高亮颜色:
![image](https://user-images.githubusercontent.com/51702723/140008140-41d526b2-cb00-4923-8fc4-ebcb4a5eb2aa.png)

请问这是和之前的配置文件有冲突吗？

**Comment by ayamir** [comment]
我试了一下应该是和`vue`的`treesitter`冲突了，和你装的这些包没关系，可以考虑删除`vue`的`treesitter`。
main分支试了没有问题，也可以考虑使用main分支的配置。

**Comment by ayamir** [comment]
或者你试试换个主题：https://github.com/sainnhe/edge

**Comment by CrazyGriferman** [comment]
问题解决，是treesitter的配置问题，我把disable中的 vue、javascript、tsx、typescript 放进install中就可以正常显示了，感谢
