### ISSUE TITLE
终端启动NVIM,使用space+f+r查找文件事,没有文件预览.

### ISSUE THREAD

**Issue by hhcwyx** [ayamir/nvimdots#410]
### Version confirmation

- [X] Confirm

### Neovim version

NVIM0.8.2

### Operating system/version

archlinux,dwm

### Terminal name/version

alacritty

### Branch info

main (Default/Latest)

### Fetch Preferences

SSH (use_ssh = true)

### How to reproduce the issue

在终端启动NVIM,使用space+f+r查找文件时,文件预览窗口没有出现.使用rofi起动器启动NVIM,文件预览正常,但是使用rofi启动的NVIM,字体很小.

### Expected behavior

看帮助文档里面的效果图,是有文件预览的,很漂亮.很想体验一下.

**Comment by ayamir** [comment]
If you have not openned file, `<leader>fr` won't show results.

**Comment by hhcwyx** [comment]
在文件列表里是由很多备选文件的,把光标移动到某个文件上,旁边没有此文件的内容预览.

**Comment by ayamir** [comment]
What's the window size? too small also won't show.

**Comment by hhcwyx** [comment]
我的就是一个16寸的笔记本,是屏幕太小的原因吗?

**Comment by ayamir** [comment]
It will show if you maximize the window in normal case.

**Comment by ayamir** [comment]
Any other telescope windows show the preview?

**Comment by hhcwyx** [comment]
都没有

**Comment by ayamir** [comment]
Any errors? Maybe your can try to reinstall all of plugins
```
rm -rf ~/.local/share/nvim/site/
nvim +PackerSync
```

**Comment by hhcwyx** [comment]
我试了一下另外的一个终端(st),文件预览出来了.谢谢!

**Comment by hhcwyx** [comment]
我将终端字体改小后,试了一下,文件预览出现了,一切正常了.谢谢!!
