### ISSUE TITLE
`<A-d>` can't bring up floating terminal

### ISSUE THREAD

**Issue by hhcwyx** [ayamir/nvimdots#411]
### Version confirmation

- [ ] Confirm

### Neovim version

NVIM0.8.2

### Operating system/version

archlinux,dwm

### Terminal name/version

alacritty

### Branch info

main (Default/Latest)

### Fetch Preferences

SSH (use_ssh = true)

### How to reproduce the issue

用A-d调不出浮动terminal.

### Expected behavior

看展示效果图,可以调出浮动终端,

**Comment by Jint-lzxy** [comment]
How does neovim respond when executing `:execute v:count . "ToggleTerm direction=float"` in command mode?

**Comment by CharlesChiuGit** [comment]
`<A-d>` does bring up floating terminal for me.
![圖片](https://user-images.githubusercontent.com/32497323/211152766-ff6e2457-fb48-4e66-a4ec-b641cdcd7f55.png)

**Comment by hhcwyx** [comment]
@Jint-lzxy ,刚试了一下,用 :execute v:count . "ToggleTerm direction=float" 可以调出来.

**Comment by Jint-lzxy** [comment]
> 刚试了一下,用 :execute v:count . "ToggleTerm direction=float" 可以调出来.

Then your terminal does not correctly pass the escape sequence to `neovim` instance. Looks like you are using `alacritty`. Have you set `alt_send_esc: true`?

If it's not the case then if you press `<A-d>` in `showkey -a` what do you see?

**Comment by hhcwyx** [comment]
@Jint-lzxy If it's not the case then if you press <A-d> in showkey -a what do you see?
在终端里执行showkey -a 然后<A-d> 没有输出.用别的快捷键(C-r)试了一下有输出.
另外请问:set alt_send_esc: true应该在哪里设置呢?

**Comment by CharlesChiuGit** [comment]
> 另外请问:set alt_send_esc: true应该在哪里设置呢?

normally u should find the config file in `~/.config/alacritty/alacritty.yml`

**Comment by Jint-lzxy** [comment]
> 在终端里执行showkey -a 然后 没有输出.用别的快捷键(C-r)试了一下有输出.
Then the `alt`-related sequences are not escaped correctly.

> 另外请问:set alt_send_esc: true应该在哪里设置呢?
This is a problem with your terminal, so check https://github.com/alacritty/alacritty#configuration

**Comment by hhcwyx** [comment]
我查了一下,这个是设置了的.

**Comment by CharlesChiuGit** [comment]
Actually U should try another terminal to check if it's terminal's problem or not first.

**Comment by Jint-lzxy** [comment]
Then this is an issue related to `alacritty`. Can this issue be reproduced on other terminals? If not, please open an issue in [their repo](https://github.com/alacritty/alacritty).

**Comment by hhcwyx** [comment]
好的,谢谢!
