### ISSUE TITLE
cmp-spell 插件是怎么用的

### ISSUE THREAD

**Issue by hhcwyx** [ayamir/nvimdots#414]
### Version confirmation

- [ ] Confirm

### Neovim version

NVIM0.8.2

### Operating system/version

archlinux,dwm

### Terminal name/version

alacritty

### Branch info

main (Default/Latest)

### Fetch Preferences

SSH (use_ssh = true)

### How to reproduce the issue

cmp-spell插件的作用是不是在编辑文档输入英文单词时,应该有英文单词的补全提示呢?我的没出来.

### Expected behavior

希望在输入英文单词的时候,能有单词补全提示.

**Comment by Jint-lzxy** [comment]
You need to turn on the spellcheck feature. The key is `<leader>o`. Note that this is only valid for the current buffer.

**Comment by ayamir** [comment]
> 希望在输入英文单词的时候,能有单词补全提示.

Add this plugin on your own: https://github.com/uga-rosa/cmp-dictionary

**Comment by hhcwyx** [comment]
@Jint-lzxy ,@ayamir 谢谢!
