### ISSUE TITLE
update for lspsaga

### ISSUE THREAD

**Issue by ayamir** [ayamir/nvimdots#417]
### Version confirmation

- [X] Confirm

### Neovim version

NVIM v0.8.2

### Operating system/version

Archlinux, wsl2

### Terminal name/version

wezterm

### $TERM environment variable

tmux-256color

### Branch info

main (Default/Latest)

### Fetch Preferences

SSH (use_ssh = true)

### How to reproduce the issue

Lspsaga introduced breaking change at https://github.com/glepnir/lspsaga.nvim/commit/afbd5718ffd453662ada49e9c520df60efc8f444
So tons of current configs are invalid for its new version.

### Expected behavior

- [x] `config.lspsaga` need to be refactor following its readme.
- [x] `config.lualine` need to be refactor following its readme.
- [x] `Lspsaga outline` don't provide toggle feature, so need to implement it by ourselves.

**Comment by CharlesChiuGit** [comment]
Finally!

**Comment by ayamir** [comment]
https://github.com/glepnir/lspsaga.nvim/commit/dfa4eee7f6eefff74038df416d911c21940f87fd

**Comment by Jint-lzxy** [comment]
Will refactor associated code.

**Comment by ayamir** [comment]
https://github.com/ayamir/nvimdots/pull/418
Updated, need more tests.
