### ISSUE TITLE
lua版 clangd补全头文件时，补全了多余的‘>’符号

### ISSUE THREAD

**Issue by okwellok** [ayamir/nvimdots#42]
我知道用enter键可以解决这个问题，但是处在插入状态，会有报错信息，返回norml状态才正常。
所以有无可能去除多余的'>'符号，tab键选中之后，直接esc，就能正确补全？我用coc补全的时候这样是可以的。
![2021-11-04_00-18](https://user-images.githubusercontent.com/83217712/140100217-89bf4e16-ff95-43ed-a358-f1afb96d9896.png)

**Comment by ayamir** [comment]
https://user-images.githubusercontent.com/61657399/140244097-e432755f-5b03-4dbd-be1d-bbb355b1aa5b.mp4

**Comment by ayamir** [comment]
没太懂你的需求

**Comment by okwellok** [comment]
@ayamir 
https://user-images.githubusercontent.com/83217712/140258044-8428849b-b947-4301-98f9-fbb3af24c39e.mp4

**Comment by ayamir** [comment]
你视频中的第一个问题在我这里不存在，更新一下？

https://user-images.githubusercontent.com/61657399/140286541-48e3a4a5-be05-47b4-a220-909bbc3dde8a.mp4

**Comment by okwellok** [comment]
谢谢，我把neovim换成neovim-git之后这个问题就没有了。
