### ISSUE TITLE
` require('dap').continue()` not working in C/C++ after setting breakpoints

### ISSUE THREAD

**Issue by hhcwyx** [ayamir/nvimdots#420]
### Version confirmation

- [ ] Confirm

### Neovim version

NVIM0.8.2

### Operating system/version

archlinux,dwm

### Terminal name/version

alacritty

### Branch info

main (Default/Latest)

### Fetch Preferences

SSH (use_ssh = true)

### How to reproduce the issue

调试C和C++代码,设置了断点,F6启动调试,断点没起作用,程序执行完,退出.dap-repl窗口有程序输出的结果.
用:Mason 调出以下结果(显示的都是安装上的插件),是插件没装全吗?
                            https://github.com/williamboman/mason.nvim
   (1) All   (2) LSP   (3) DAP   (4) Linter   (5) Formatter  
  
  Language Filter: press <C-f> to apply filter

  Installed
    ◍ bash-language-server
    ◍ black
    ◍ clangd
    ◍ codelldb
    ◍ efm
    ◍ gopls
    ◍ lua-language-server
    ◍ prettier
    ◍ pyright
    ◍ shellcheck
    ◍ shfmt
    ◍ stylua

### Expected behavior

python代码调试是正常的.但是C和C++出现了问题.

**Comment by Jint-lzxy** [comment]
Please change [this line](https://github.com/ayamir/nvimdots/blob/main/lua/modules/editor/config.lua#L301) to your installation path of `lldb-vscode`. If you haven't installed it yet, please use `Mason` or a package manager to install it _(usually distributed with `llvm`)_ and then set `command` to the corresponding path. In addition, please ensure that your executable file is debuggable.
```console
man clang:
        -g         Control debug information output.  Note that Clang debug information works best at -O0.
```
