### ISSUE TITLE
local buffer could not jump to the target location while using `dap.step_in()`

### ISSUE THREAD

**Issue by csyJoy** [ayamir/nvimdots#423]
### Version confirmation

- [x] Confirm

### Neovim version

NVIM v0.8.1

### Operating system/version

macOS 13.1

### Terminal name/version

Build 3.4.18

### Branch info

main (Default/Latest)

### Fetch Preferences

SSH (use_ssh = true)

### How to reproduce the issue

This problem occurred when I was using lldb to debug a c++ program
1. set a breakpoint
2. call dap.continue() start debugging
3. stop at breakpoint
4. call dap.step_into()
5. DAP throw the error: **Stop at line x but `switchbuf` setting prevented jump to location. Target buffer xx not open in any window?**

PS: I have verified that this buffer does not appear in any window.

### Expected behavior

the running cursor will jump into the function and this buffer will change

### Actual behavior

the running cursor seems to jump into the function but the buffer doesn't change.

**Comment by CharlesChiuGit** [comment]
Maybe check #420 first?

**Comment by csyJoy** [comment]
> Maybe check #420 first?

I have already changed the lldb path but It doesn't work for me. 
It seems that lldb works fine, and I can get the result, even when I use `dap.step_into()` the program is still running, only the buffer doesn't change.
I also try `dap.step_into()` in golang, The same problem also occurs.

**Comment by Jint-lzxy** [comment]
Will try to reproduce this on macOS later. Your executable consists of multiple object files, right? _(i.e., there is more than one source `.cxx` file when you compile)_

In addition, are you using `lldb` or `lldb-vscode`? They cannot be used interchangeably.

**Comment by csyJoy** [comment]
> Will try to reproduce this on macOS later. Your executable consists of multiple object files, right? _(i.e., there is more than one source `.cxx` file when you compile)_
> 
> In addition, are you using `lldb` or `lldb-vscode`? They cannot be used interchangeably.

Sorry, my explanation is not accurate, I actually use `lldb-vscode` and my executable consists of multiple object files

**Comment by Jint-lzxy** [comment]
Thank you for the information 👍 I will look into this issue after resolving https://github.com/ayamir/nvimdots/issues/422#issuecomment-1383043124.

**Comment by Jint-lzxy** [comment]
Can reproduce. Will push a fix.

**Comment by Jint-lzxy** [comment]
@csyJoy #424 should fix this problem. No issues were found in the small test I wrote.

https://user-images.githubusercontent.com/50296129/212527897-5f7420a4-de8c-4ed8-85d9-0339d1efc2ac.mp4
