### ISSUE TITLE
新建文件时不显示statusline要如何解决？

### ISSUE THREAD

**Issue by nkta3m** [ayamir/nvimdots#426]
### Version confirmation

- [ ] Confirm

### Neovim version

nvim 0.82

### Operating system/version

Windows 10

### Terminal name/version

Alacritty

### Branch info

main (Default/Latest)

### Fetch Preferences

HTTPS (use_ssh = false)

### How to reproduce the issue

1. open nvim
2. space f n
3. save to test.py

### Expected behavior

正确显示

### Actual behavior

nvim test.py 或者nvim，快捷键 space-f-n,新建一个空文件，:save test.py，statusline都不能正确显示，请教是正常的吗？

**Comment by Jint-lzxy** [comment]
This _is_ the correct _(and yet not that intuitive)_ behavior, because we haven't registered the `BufNewFile` event for `lualine` and its two dependencies. This will be resolved in #425.

**Comment by nkta3m** [comment]
明白了，谢谢

**Comment by nkta3m** [comment]
我又遇到另一个问题，新建md文件，出现如下提示：
![2023-01-16 13_08_04-Window](https://user-images.githubusercontent.com/13484700/212603054-924b7dc9-efbc-4279-be02-784d28d905a1.png)

**Comment by Jint-lzxy** [comment]
This is also related to the `BufNewFile` event _(++the language server would also stop working under certain circumstances)_. Please wait until the migration (#422) is finished.

A temporary workaround is to create such files externally using shell commands like `touch`.

**Comment by Jint-lzxy** [comment]
`:h BufNewFile`
```vimdoc
							*BufNewFile*
BufNewFile			When starting to edit a file that doesn't
				exist.  Can be used to read in a skeleton
				file.
```

**Comment by ayamir** [comment]
The correct steps to use `<leader>fn` to create a new file and use opened buffer to edit are following:
1. `<leader>fn`: create a empty buffer.
2. `:w xxx.xx`: write to a file called `xxx.xx`.
3. `:e`: reload this buffer with the saved file.

Then you will see all of them works for fine including `lsp`, `lualine` and `bufferline`.

**Comment by ayamir** [comment]
> 我又遇到另一个问题，新建md文件，进入insert后，出现如下提示：但是在test.py中不会出现
> 
> ![2023-01-16 13_08_04-Window](https://user-images.githubusercontent.com/13484700/212603054-924b7dc9-efbc-4279-be02-784d28d905a1.png)

I have removed `tabout.nvim` in https://github.com/ayamir/nvimdots/pull/425.
