### ISSUE TITLE
Use python settings in venv for debugpy

### ISSUE THREAD

**Issue by hhcwyx** [ayamir/nvimdots#428]
### Version confirmation

- [ ] Confirm

### Neovim version

NVIM0.8.2

### Operating system/version

archlinux,dwm

### Terminal name/version

alacritty

### Branch info

main (Default/Latest)

### Fetch Preferences

SSH (use_ssh = true)

### How to reproduce the issue

按F6,调试程序,出现如下信息:
Debug adapter didn't respond. Either the adapter is slow (then wait and ignore this) or there is a problem with your adapter or `python` configuration. Check the logs for errors (:help dap.set_log_level)

这是配置文件最后两次同步后出现的情况,原来是正常的.

### Expected behavior

最后两次同步配置,后出现的问题.

**Comment by Jint-lzxy** [comment]
> 最后两次同步配置,后出现的问题.

Hmm this shouldn't be introduced by recent commits - we didn't change the execution logic of DAP.

We need some further information:
1. What is the version of `/usr/bin/python` _(Please use the path to the executable AS IS, not just `python`)_?
2. What's the output of:
```vim
:echo(executable(getcwd().."/venv/bin/python") || executable(getcwd().."/.venv/bin/python"))
```
3. What do you see after running `/usr/bin/python -m debugpy.adapter`?
4. Start a debug session as normal, but before starting the adapter, run:
```lua
:lua require("dap").set_log_level("TRACE")
```
5. After the warning is issued, please provide us with the generated log from:
```lua
:lua print(vim.fn.stdpath("cache").."/dap.log")
```

**Comment by Jint-lzxy** [comment]
Don't forget to clear the logging history of dap before starting, run:
```sh
truncate --no-create --size 0 /path/to/your/dap.log
```
Where the path to your `dap.log` can be obtained from `:lua print(vim.fn.stdpath("cache").."/dap.log")` in nvim.

**Comment by hhcwyx** [comment]
@Jint-lzxy  是我自己修改了配置文件,造成的这个结果.我把自己修改的部分改回去后,就正常了.谢谢!
我还有一个问题,我有两个python版本,分别是3.10.9和3.9.14,我想用3.9.14的版本,请问应该怎么修改配置文件呢?(我自己在~/.virtualenvs目录下创建一个debugpy的虚拟环境,怎么能让系统使用这个环境呢?)

**Comment by Jint-lzxy** [comment]
I seldom use Python in daily development, so I could only provide limited help.

AFAIK if the `python` executable exists in your `~/.virtualenvs` directory, replace [pythonPath](https://github.com/ayamir/nvimdots/blob/3eb10f20881c04cc285cb1a8126d153bb7353f90/lua/modules/editor/config.lua#L409) with the following _(if you have activated venv correctly)_:
```lua
pythonPath = function()
	-- debugpy supports launching an application with a different interpreter then the one used to launch debugpy itself.
	-- The code below looks for a `venv` or `.venv` folder in the current directly and uses the python within.
	-- You could adapt this - to for example use the `VIRTUAL_ENV` environment variable.
	local cwd, venv = vim.fn.getcwd(), os.getenv("VIRTUAL_ENV")
	if vim.fn.executable(cwd .. "/venv/bin/python") == 1 then
		return cwd .. "/venv/bin/python"
	elseif vim.fn.executable(cwd .. "/.venv/bin/python") == 1 then
		return cwd .. "/.venv/bin/python"
	elseif venv and vim.fn.executable(venv .. "/bin/python") == 1 then
		return venv .. "/bin/python"
	else
		return "/usr/bin/python"
	end
end,
```

You can use the following command to check whether the path is correct.
```lua
:lua print(os.getenv("VIRTUAL_ENV") and os.getenv("VIRTUAL_ENV") .. "/bin/python" or "FAILED")
```

**Comment by Jint-lzxy** [comment]
Or if you would like to use the environment defined as `VIRTUAL_ENV` first:
```lua
pythonPath = function()
	-- debugpy supports launching an application with a different interpreter then the one used to launch debugpy itself.
	-- The code below looks for a `venv` or `.venv` folder in the current directly and uses the python within.
	-- You could adapt this - to for example use the `VIRTUAL_ENV` environment variable.
	local cwd, venv = vim.fn.getcwd(), os.getenv("VIRTUAL_ENV")
	if venv and vim.fn.executable(venv .. "/bin/python") == 1 then
		return venv .. "/bin/python"
	elseif vim.fn.executable(cwd .. "/venv/bin/python") == 1 then
		return cwd .. "/venv/bin/python"
	elseif vim.fn.executable(cwd .. "/.venv/bin/python") == 1 then
		return cwd .. "/.venv/bin/python"
	else
		return "/usr/bin/python"
	end
end,
```

**Comment by CharlesChiuGit** [comment]
Just as a reference for others using conda:

here's how u call conda env path in DAP:
``lua
		pythonPath = function()
			if not isempty(vim.env.CONDA_PREFIX) then
				return vim.env.CONDA_PREFIX .. "/bin/python"
			-- print(vim.g.python3_host_prog)
			else
				return "/usr/bin/python3"
			end
		end,
```
