### ISSUE TITLE
为什么去除了 lspsaga 插件？

### ISSUE THREAD

**Issue by HATTER-LONG** [ayamir/nvimdots#43]
请问下为什么要去除 lspsaga 插件？

虽然最近 nvim0.6 有些不兼容，但还是可以使用 0.5的分支，还是说有什么其他原因吗？

感谢分享的这份配置，非常好用 ：）

**Comment by ayamir** [comment]
主要是因为lspsaga已经好久没有更新了

**Comment by HATTER-LONG** [comment]
我切了  [tami5/lspsaga.nvim](https://github.com/tami5/lspsaga.nvim) 的分支现在还在维护，最近没发现什么问题，考虑试下吗？`vim.lsp.buf.hover` 的框实在看着有些怪和背景色区分度太低了。

**Comment by HATTER-LONG** [comment]
使用的是低于 0.6 版本的 neovim 可能需要以下的配置：

```lua
completion['tami5/lspsaga.nvim'] = {
    opt = true,
    branch = 'nvim51',
    after = 'nvim-lspconfig',
}
```
> lspsaga:
> NEOVIM NIGHTLY (+v0.6.0-dev+1865-g3beea1fe1) or use nvim51 branch use { 'tami5/lspsaga.nvim', branch = 'nvim51' }

**Comment by ayamir** [comment]
Readme中已经要求使用neovim-git了

**Comment by HATTER-LONG** [comment]
恩  我只是在这个 issue 里提一下，服务器里一般不会很新。赞！
