### ISSUE TITLE
Preview pane empty after pressing `<leader>fw`

### ISSUE THREAD

**Issue by leowucn** [ayamir/nvimdots#430]
### Version confirmation

- [X] Confirm

### Neovim version

NVIM v0.8.2 Build type: Release LuaJIT 2.1.0-beta3 Compiled by brew@Ventura-arm64.local

### Operating system/version

macos 13.1

### Terminal name/version

Item2

### Branch info

main (Default/Latest)

### Fetch Preferences

SSH (use_ssh = true)

### How to reproduce the issue

不明白为什么我这个搜索框内容为空

<img width="1476" alt="image" src="https://user-images.githubusercontent.com/16133390/213714722-744149fa-3c6e-4083-a183-fb7afe551fdd.png">

### Expected behavior

可以看到文件列表

**Comment by CharlesChiuGit** [comment]
It's suppose to be like this, start typing and your will see things.

**Comment by leowucn** [comment]
It still be empty after inputing any word or any character.

**Comment by CharlesChiuGit** [comment]
Also have u done everything in https://github.com/ayamir/nvimdots/wiki/Prerequisites?

**Comment by leowucn** [comment]
No, after installing some packages required by telescope, It worked. Thanks.
