### ISSUE TITLE
Can not use a different theme when reopen nvim.

### ISSUE THREAD

**Issue by leowucn** [ayamir/nvimdots#432]
### Version confirmation

- [ ] Confirm

### Neovim version

NVIM v0.8.2 Build type: Release LuaJIT 2.1.0-beta3 Compiled by brew@Ventura-arm64.local  Features: +acl +iconv +tui See ":help feature-compile"     system vimrc file: "$VIM/sysinit.vim"   fall-back for $VIM: "/opt/homebrew/Cellar/neovim/0.8.2/share/nvim"  Run :checkhealth for more info

### Operating system/version

macos 13.1

### Terminal name/version

iTem2

### Branch info

main (Default/Latest)

### Fetch Preferences

SSH (use_ssh = true)

### How to reproduce the issue

I select a different theme, after reopen nvim again, the theme would be reset to the default theme. How to make nvim remember my theme choice?

### Expected behavior

Make nvim remember my theme choice.

**Comment by CharlesChiuGit** [comment]
U have to set it in this line.
https://github.com/ayamir/nvimdots/blob/c761c1a7cfdbfbef6ec30a0fad15a1df083834f7/lua/core/init.lua#L133
