### ISSUE TITLE
Change default theme got error

### ISSUE THREAD

**Issue by leowucn** [ayamir/nvimdots#433]
### Version confirmation

- [ ] Confirm

### Neovim version

NVIM v0.8.2 Build type: Release LuaJIT 2.1.0-beta3 Compiled by brew@Ventura-arm64.local  Features: +acl +iconv +tui See ":help feature-compile"     system vimrc file: "$VIM/sysinit.vim"   fall-back for $VIM: "/opt/homebrew/Cellar/neovim/0.8.2/share/nvim"  Run :checkhealth for more info

### Operating system/version

macos 13.1

### Terminal name/version

iTem2

### Branch info

main (Default/Latest)

### Fetch Preferences

SSH (use_ssh = true)

### How to reproduce the issue

I add a new theme plugin which is `ellisonleao/gruvbox.nvim`.
<img width="681" alt="image" src="https://user-images.githubusercontent.com/16133390/213858324-6b1ea452-6bd8-471a-9c34-6b530a65e1af.png">

I switch new theme by `<leader>fc` and everything is ok,  after that I change default theme by add code:

<img width="848" alt="image" src="https://user-images.githubusercontent.com/16133390/213858432-8801f3e1-cf6b-486b-9081-e97ad3ea146e.png">

After running code `nvim +PackerSync`,  I got an error when open nvim.

<img width="1509" alt="image" src="https://user-images.githubusercontent.com/16133390/213858488-bd2577c6-6d6c-4802-b011-878dea81a5c2.png">
 

### Expected behavior

I can change the default theme to `gruvbox`.

**Comment by CharlesChiuGit** [comment]
Packer can't handle default colorscheme to be lazy-loaded. Here's a example of how u should set the event.
https://github.com/ayamir/nvimdots/blob/c761c1a7cfdbfbef6ec30a0fad15a1df083834f7/lua/modules/ui/plugins.lua#L7-L11
