### ISSUE TITLE
How to show current file relative path in status bar?

### ISSUE THREAD

**Issue by leowucn** [ayamir/nvimdots#434]
### Version confirmation

- [ ] Confirm

### Neovim version

NVIM v0.8.2 Build type: Release LuaJIT 2.1.0-beta3 Compiled by brew@Ventura-arm64.local  Features: +acl +iconv +tui See ":help feature-compile"     system vimrc file: "$VIM/sysinit.vim"   fall-back for $VIM: "/opt/homebrew/Cellar/neovim/0.8.2/share/nvim"  Run :checkhealth for more info

### Operating system/version

macos 13.1

### Terminal name/version

Item2

### Branch info

main (Default/Latest)

### Fetch Preferences

SSH (use_ssh = true)

### How to reproduce the issue

Is there any way to show current file's relative path in status bar?
<img width="1505" alt="image" src="https://user-images.githubusercontent.com/16133390/213858629-3d17b428-2542-454d-838e-fdc6fc7f7da7.png">

### Expected behavior

display file relative path

**Comment by CharlesChiuGit** [comment]
Here's the section u config `lualine` in this config:
https://github.com/ayamir/nvimdots/blob/c761c1a7cfdbfbef6ec30a0fad15a1df083834f7/lua/modules/ui/config.lua#L436-L599

Here's some documentation for u to reference how to config lualine:

https://github.com/nvim-lualine/lualine.nvim#default-configuration
https://github.com/nvim-lualine/lualine.nvim/wiki

**Comment by leowucn** [comment]
Thanks.

**Comment by Jint-lzxy** [comment]
@leowucn Just a reminder. You don't seem to have the required font installed correctly. Please download your desired font [here](https://www.nerdfonts.com/font-downloads) or via [Homebrew Cask Fonts](https://github.com/ryanoasis/nerd-fonts#option-4-homebrew-fonts), and then select the font ending with `Nerd Font Mono` _(e.g., JetBrainsMono Nerd Font Mono)_ in your iTerm2's custom profile.
