### ISSUE TITLE
add scheme/theme support for gruvbox

### ISSUE THREAD

**Issue by shelper** [ayamir/nvimdots#435]
### Feature description

could you add support for this scheme? https://github.com/ellisonleao/gruvbox.nvim

i searched yoru doc only found that i can only use limited sets of scheme
and no details on how i can install one to fit into your config.

**Comment by ayamir** [comment]
refer to this: https://github.com/ayamir/nvimdots/issues/353

**Comment by Jint-lzxy** [comment]
Closed as a duplicate of #353.
