### ISSUE TITLE
Update icon codepoints

### ISSUE THREAD

**Issue by Jint-lzxy** [ayamir/nvimdots#439]
[Release v2.3.3 · ryanoasis/nerd-fonts](https://github.com/ryanoasis/nerd-fonts/releases/tag/v2.3.3)
> **Material Design Icons**
>
> The Material Design Icons have to move codepoints. Historically we patch them in between `F500` - `FD46`; but part of that range is needed for Chinese and other glyphs ... Their new home will be after `F0001`. And they grow considerably.
>
> The `v2.3.x` release has both, the 'old' and the 'new' codepoints to enable you an easier transision. **Please change** already **now** your prompts and other uses to the new codepoints. Release `v3.0.0` will finally drop the old codepoints (`F500` - `FD46`).

Compatibility of all icons will be checked after implementing #394.

**Comment by CharlesChiuGit** [comment]
wow, didn't know we need to fix this.
