### ISSUE TITLE
Configuration modification does not take effect

### ISSUE THREAD

**Issue by zll600** [ayamir/nvimdots#441]
### Feature description

![image](https://user-images.githubusercontent.com/71714656/215248648-bebaa924-9381-46dc-845b-f427926dde7c.png)

I modified the `leader key`, but it doesn't seem to work.

![image](https://user-images.githubusercontent.com/71714656/215248750-85b3de1d-5bc5-443c-bebc-246dda450f7e.png)

### Additional information

![image](https://user-images.githubusercontent.com/71714656/215248815-db54351c-fe2c-4d6a-a4fe-7f33e3bc3132.png)

I use the latest code from the main branch.

**Comment by Jint-lzxy** [comment]
This is hard coded into `alpha`. Please modify these lines:
https://github.com/ayamir/nvimdots/blob/c3c0365d3dd0610d185aa610a8e6c46840e4ac03/lua/modules/ui/config.lua#L63-L71

**Comment by zll600** [comment]
> This is hard coded into `alpha`. Please modify these lines:
> 
> https://github.com/ayamir/nvimdots/blob/c3c0365d3dd0610d185aa610a8e6c46840e4ac03/lua/modules/ui/config.lua#L63-L71


But after I modify the `leader key`  to `\`, only `space key` still take effect.

**Comment by zll600** [comment]
@Jint-lzxy  I found that it seems that because I have multiple `neovim` configurations in the same directory, I modified another configuration when I used neovim to edit configuration. Thanks a lot.
