### ISSUE TITLE
lazy.nvim error after updating plugins

### ISSUE THREAD

**Issue by Lraxer** [ayamir/nvimdots#445]
### Version confirmation

- [X] Confirm

### Neovim version

NVIM v0.8.2

### Operating system/version

Archlinux

### Terminal name/version

kitty 0.26.5

### $TERM environment variable

xterm-kitty

### Branch info

main (Default/Latest)

### Fetch Preferences

SSH (use_ssh = true)

### How to reproduce the issue

I Updated to the latest configuration. When I started neovim it took some time to install lazy.nvim and other plugins (I noticed the version of lazy.nvim in `lazy-lock.json` changed to `9b208696e139a40`). Then I run `Lazy sync` in neovim.

### Expected behavior

Update all plugins as normal.

### Actual behavior

Now it keeps popping up the same error in notifications.

![2023-01-28_18-31](https://user-images.githubusercontent.com/32860114/215261959-2a4aeee1-6653-4643-95ab-153f0e93f629.png)

So I exit from neovim and restart and get this error. I reproduce the error several times, but not every time. It maybe caused by lazy.nvim updating itself, I guess?

![2023-01-28_18-33](https://user-images.githubusercontent.com/32860114/215262020-e1a3b746-e87d-4159-96fc-b017e4f94979.png)

### Additional information

The only way I can do is deleting `~/.local/share/nvim/site/lazy`.

BTW, is it not recommended to update plugins by myself since `lazy-lock.json` is uploaded to the repo? It may be changed in every commit, so I think it is unnecessary.

**Comment by Lraxer** [comment]
Ok, I think it is a network issue. My proxy does not filter ssh traffic, so I have to connect directly to Github. However, lazy.nvim still failed to update via ssh (that is weird) which causes this error.

Now I'm using http and it looks fine.

**Comment by Jint-lzxy** [comment]
@Lraxer This is _indeed_ a bug - we didn't check whether `:call system()` returned correctly. This has been fixed at https://github.com/ayamir/nvimdots/commit/b3e65fbedbcf2019467ed90be643aec903cab430.

You may reinstall this config using SSH again. Bootstrapper should report errors now 👍

> BTW, is it not recommended to update plugins by myself since `lazy-lock.json` is uploaded to the repo? It may be changed in every commit, so I think it is unnecessary.

No, you can sync plugins at any time _(same as you used to do)_. This exists only to help us better restore the status of the plugins when an issue is opened/ensure that plugin versions are the same as the versions specified in `lazy-lock.json` **at the very least** to avoid meaningless issues like https://github.com/ayamir/nvimdots/issues/388, https://github.com/ayamir/nvimdots/issues/413 and https://github.com/ayamir/nvimdots/issues/406. This file will be [updated automatically](https://github.com/ayamir/nvimdots/blob/main/.github/workflows/update_lockfile.yml).

More information: https://github.com/ayamir/nvimdots/pull/425#issuecomment-1397873355.

**Comment by Lraxer** [comment]
Thank you, now it works as expected. 

Yeah it is reasonable to add `lazy-lock.json`. I think the update process of this repo is a bit aggressive, but it becomes much better in a short term, and I've learned a lot from it. Pretty cool.

**Comment by Jint-lzxy** [comment]
> I think the update process of this repo is a bit aggressive, but it becomes much better in a short term, and I've learned a lot from it. Pretty cool.

That's true. We are beginning to use the [releases page](https://github.com/ayamir/nvimdots/releases/tag/v1.0.0-rc1) to better manage and record changes over time. Hope this can resolve some unnecessary troubles 👍
