### ISSUE TITLE
更新到最新插件后，有错误提示

### ISSUE THREAD

**Issue by nkta3m** [ayamir/nvimdots#446]
### Version confirmation

- [ ] Confirm

### Neovim version

NVIM v0.8.2

### Operating system/version

arch

### Terminal name/version

Alacritty

### Branch info

main (Default/Latest)

### Fetch Preferences

HTTPS (use_ssh = false)

### How to reproduce the issue

1. update plugins
2. open python file
![shot-2023-01-28_21-58-10](https://user-images.githubusercontent.com/13484700/215270449-f3388854-54e3-404a-9161-aa6596f0cbef.jpg)
![shot-2023-01-28_21-59-29](https://user-images.githubusercontent.com/13484700/215270457-fd1c972f-5a5a-4a88-9aa9-98a8b1601096.jpg)

### Expected behavior

fix

**Comment by Jint-lzxy** [comment]
Will support V0.2.4 later (https://github.com/glepnir/lspsaga.nvim/commit/2db894653bfbb97ce528ae15e5fb74363fa937ff). Now `lspsaga` has been pinned at v0.2.3, please run `:Lazy restore` after pulling the repository.

**Comment by ayamir** [comment]
fixed at 5223b8e2119566728acb041bf0a0a32e4027659d
