### ISSUE TITLE
Failed to run `config` for lualine.nvim

### ISSUE THREAD

**Issue by zll600** [ayamir/nvimdots#451]
### Version confirmation

- [X] Confirm

### Neovim version

NVIM v0.8.2

### Operating system/version

ArchLinux x86_64

### Terminal name/version

alacritty 0.11.0 (8dbaa0bb)

### $TERM environment variable

xterm-256color

### Branch info

main (Default/Latest)

### Fetch Preferences

SSH (use_ssh = true)

### How to reproduce the issue

1. cd ~/.config/nvim
2. git reset --hard origin/HEAD
3. nvim init.lua

### Expected behavior

Maybe it should work fine？

### Additional information

![image](https://user-images.githubusercontent.com/71714656/215336432-fb43970b-ad55-43fc-80bf-af2c7e2d2d5a.png)

**Comment by ayamir** [comment]
Do you know `git reset --hard origin/HEAD` doesn't pull the latest remote repo? The correct way is just `git pull`, this problem has been fixed at 5223b8e2119566728acb041bf0a0a32e4027659d

**Comment by zll600** [comment]
I did do `git pull` before doing `git reset`, so I had the latest commit(https://github.com/ayamir/nvimdots/commit/a32e241cb3300626cde91df2ee64af2e1bab0c64) at the time, It may be that I did lazy sync when I was using the latest commit. Now using the latest commit from the main branch works fine(I did `Lazy restore`). Thank you for  your help.
