### ISSUE TITLE
how do I get the plugins that are not loaded to load...

### ISSUE THREAD

**Issue by fakeczg** [ayamir/nvimdots#453]
### Feature description

  Total: 88 plugins
  
  Loaded (22)
     accelerated-jk.nvim 0.43ms  VeryLazy
     alpha-nvim 0.36ms  BufWinEnter
     bigfile.nvim 0.23ms  start
     catppuccin 0.98ms  start
     dressing.nvim 0.47ms  VeryLazy
     fzy-lua-native 0.13ms  wilder.nvim
     lazy.nvim 5.53ms  init.lua
     nvim-colorizer.lua 0.4ms  nvim-treesitter
     nvim-notify 2.5ms  VeryLazy
     nvim-treesitter 5.08ms  bigfile.nvim
     nvim-treesitter-textobjects 1.55ms  nvim-treesitter
     nvim-ts-autotag 0.33ms  nvim-treesitter
     nvim-ts-context-commentstring 0.15ms  nvim-treesitter
     nvim-ts-hint-textobject 0.08ms  nvim-treesitter
     nvim-ts-rainbow 0.18ms  nvim-treesitter
     specs.nvim 0.34ms  CursorMoved
     tabout.nvim 0.36ms  nvim-treesitter
     toggleterm.nvim 1.25ms  UIEnter
     vim-cool 0.15ms  CursorMoved
     vim-matchup 0.1ms  nvim-treesitter
     which-key.nvim 6.08ms  VeryLazy
     wilder.nvim 7.37ms  CmdlineEnter
  
  Not Loaded (66)
     LuaSnip  nvim-cmp
     auto-session  DeleteSession
     better-escape.nvim  BufReadPost
     bufferline.nvim  BufNewFile
     clever-f.vim  BufReadPost
     cmp-buffer  nvim-cmp
     cmp-latex-symbols  nvim-cmp
     cmp-nvim-lsp  nvim-cmp
     cmp-nvim-lua  nvim-cmp
     cmp-path  nvim-cmp
     cmp-spell  nvim-cmp
     cmp-tmux  nvim-cmp
     cmp-under-comparator  nvim-cmp
     cmp_luasnip  nvim-cmp
     copilot-cmp  copilot.lua
     copilot.lua  Copilot  InsertEnter
     csv.vim  csv
     diffview.nvim  DiffviewClose
     edge 
     efmls-configs-nvim  nvim-lspconfig
     fidget.nvim  BufReadPost
     friendly-snippets  LuaSnip
     gitsigns.nvim  BufNewFile
     hop.nvim  BufReadPost
     indent-blankline.nvim  BufReadPost
     legendary.nvim  Legendary
     lsp_signature.nvim  nvim-lspconfig
     lspkind.nvim  nvim-cmp
     lspsaga.nvim  nvim-lspconfig
     lualine.nvim  BufNewFile
     markdown-preview.nvim  markdown
     mason-lspconfig.nvim  nvim-lspconfig
     mason-tool-installer.nvim  nvim-lspconfig
     mason.nvim  nvim-lspconfig
     neodim  LspAttach
     neoscroll.nvim  BufReadPost
     nord.nvim 
     nvim-autopairs  nvim-cmp
     nvim-bufdel  BufReadPost
     nvim-cmp  InsertEnter
     nvim-comment  BufReadPre
     nvim-dap  DapTerminate
     nvim-dap-ui  nvim-dap
     nvim-lspconfig  BufNewFile
     nvim-scrollview  BufReadPost
     nvim-tree.lua  NvimTreeRefresh
     nvim-web-devicons  telescope.nvim
     plenary.nvim  telescope.nvim
     popup.nvim  telescope.nvim
     project.nvim  BufReadPost  telescope.nvim
     rust-tools.nvim  rust
     smartyank.nvim  BufReadPost
     sniprun  SnipRun
     sqlite.lua  telescope-frecency.nvim
     stabilize.nvim  BufReadPost
     telescope-frecency.nvim  telescope.nvim
     telescope-fzf-native.nvim  telescope.nvim
     telescope-live-grep-args.nvim  telescope.nvim
     telescope-undo.nvim  telescope.nvim
     telescope-zoxide  telescope.nvim
     telescope.nvim  Telescope
     trouble.nvim  TroubleRefresh
     vim-easy-align  EasyAlign
     vim-fugitive  G
     vim-go  go
     vim-illuminate  BufReadPost

### Additional information

5108: Error executing lua [string ":lua"]:1: module 'telescope' not found:
        no field package.preload['telescope']module telescope not found
        no file './telescope.lua'
        no file '/usr/share/luajit-2.1.0-beta3/telescope.lua'
        no file '/usr/local/share/lua/5.1/telescope.lua'
        no file '/usr/local/share/lua/5.1/telescope/init.lua'
        no file '/usr/share/lua/5.1/telescope.lua'
        no file '/usr/share/lua/5.1/telescope/init.lua'
        no file './telescope.so'
        no file '/usr/local/lib/lua/5.1/telescope.so'
        no file '/usr/lib/lua/5.1/telescope.so'
        no file '/usr/local/lib/lua/5.1/loadall.so'
stack traceback:
        [C]: in function 'require'
        [string ":lua"]:1: in main chunk 
 

Not Loaded (66)
Please, how do I get the plugins that are not loaded to load...

**Comment by artorias1024** [comment]
I had the same problem

**Comment by ayamir** [comment]
`Lazy load telescope.nvim`

But what the problem exactly is? And how to repo it?

**Comment by fakeczg** [comment]
> 
I don't know why I got an error using Telescope after the update，And after using leader+p+s to update, there will be no plug-ins loaded, such as the one above the figure。


E5108: Error executing lua [string ":lua"]:1: module 'telescope' not found:
        no field package.preload['telescope']module telescope not found
        no file './telescope.lua'
        no file '/usr/share/luajit-2.1.0-beta3/telescope.lua'
        no file '/usr/local/share/lua/5.1/telescope.lua'
        no file '/usr/local/share/lua/5.1/telescope/init.lua'
        no file '/usr/share/lua/5.1/telescope.lua'
        no file '/usr/share/lua/5.1/telescope/init.lua'
        no file './telescope.so'
        no file '/usr/local/lib/lua/5.1/telescope.so'
        no file '/usr/lib/lua/5.1/telescope.so'
        no file '/usr/local/lib/lua/5.1/loadall.so'
stack traceback:
        [C]: in function 'require'
        [string ":lua"]:1: in main chunk

**Comment by CharlesChiuGit** [comment]
I think telescope is not installed properly on your machine, delete the plugin folder and try reinstall again.

**Comment by fakeczg** [comment]
> I think telescope is not installed properly on your machine, delete the plugin folder and try reinstall again.

thanks，rm ~/.local/share/nvim/site and reinstall is ok；
