### ISSUE TITLE
`snippet_path` would be better to place in `global.lua`

### ISSUE THREAD

**Issue by CharlesChiuGit** [ayamir/nvimdots#456]
### Feature description

Currently, `snippet_path` is using unix style path separator. Causing `Luasnip` not being able to initialized successfully.

```lua
local snippet_path = os.getenv("HOME") .. "/.config/nvim/my-snippets/"
```

**Comment by Jint-lzxy** [comment]
emm AFAIK this has nothing to do with path separators. Are the following outputs consistent?
```lua
1. :lua print(vim.fn.stdpath("config"))
2. :lua print(os.getenv("HOME") .. "/.config/nvim/my-snippets/")
```

**Comment by CharlesChiuGit** [comment]
1. 
![圖片](https://user-images.githubusercontent.com/32497323/215732652-37d3e972-4255-40d0-a580-120b65d26bb7.png)

2.
![圖片](https://user-images.githubusercontent.com/32497323/215732770-0d5ebf53-1ff7-47a7-a334-0508870fd6de.png)
