### ISSUE TITLE
how to go to next/previous live_grep results directly

### ISSUE THREAD

**Issue by goodpaperman** [ayamir/nvimdots#460]
### Feature description

when I search a word, e.g. 'on_operation', there maybe many results, 
although I can preview them, sometimes I need goto the place to see the detail and do some edit, 
the next time I want to go to the next search result, I must reopen telescope live_grep and type in 'on_operation', and step to the destination item
![图片](https://user-images.githubusercontent.com/8522640/216034656-88d2ba12-e903-46b7-8421-7161bc7f2426.png)

Is there any short-cuts to let me browse during the results list ?
in old style I can do this by the quickfix windows:
![图片](https://user-images.githubusercontent.com/8522640/216033797-d062065e-f219-4938-ac39-6c0ad28894ed.png)
I can step up and down by simple Ctrl+N/P, and search in result, etc..
I can close quickfix by :cclose, and open it with :copen, when reopened, same content showed, 
list can be iterated again,untill I do a new search

anything to play the same role like quickfix in nvim ?

**Comment by ayamir** [comment]
https://github.com/kevinhwang91/nvim-bqf is a great plugin, maybe we can add it after https://github.com/ayamir/nvimdots/pull/458 merged.

**Comment by Jint-lzxy** [comment]
We can also take this opportunity to fully support `fzf` 👍

**Comment by Jint-lzxy** [comment]
Wait a minute, looks like I misunderstood this issue. @goodpaperman If you mean to "search the search results under current project", then I would recommend you have a look at:
1. `:h telescope.defaults.history`
2. [telescope-smart-history.nvim](https://github.com/nvim-telescope/telescope-smart-history.nvim)

@ayamir Shall we need to add this feature to the base config?

**Comment by Jint-lzxy** [comment]
Wait a minute, looks like I misunderstood this issue. @goodpaperman If you mean to "search the search results under current project", then I would recommend you have a look at:
1. `:h telescope.defaults.history`
2. [telescope-smart-history.nvim](https://github.com/nvim-telescope/telescope-smart-history.nvim)

@ayamir Shall we add this feature to the base config?

**Comment by goodpaperman** [comment]
two function on telescope live_grep is needed:
1. remember the lastest search results
2. go forth/back the result list and remember the current position

**Comment by Jint-lzxy** [comment]
@goodpaperman Yes, this is what is provided in https://github.com/ayamir/nvimdots/issues/460#issuecomment-1420195045. Did you try that?

**Comment by goodpaperman** [comment]
get it, I will try later

**Comment by ayamir** [comment]
Did you solve it?

**Comment by goodpaperman** [comment]
issue can close, I will try later and reopen it if not ok, thanks a lot~
