### ISSUE TITLE
Unable to use and initialize nvim configuration

### ISSUE THREAD

**Issue by blackpeter11** [ayamir/nvimdots#461]
### Error content
<img width="1103" alt="image" src="https://user-images.githubusercontent.com/90673507/216052359-0377764b-3504-4fd0-a4e4-acab97ba71c1.png">
After press enter:
<img width="1548" alt="image" src="https://user-images.githubusercontent.com/90673507/216052458-85df470a-e04b-4b97-8298-afc52fc7350b.png">

### Basic configuration
system:macos 13.2
package manager:homebrew
neovim version:0.8.2
lua version:5.4.4

**Comment by CharlesChiuGit** [comment]
Looks like your using a self-compiled nvim which lack of some necessary functions. Reinstall a github-compiled nvim and try it again.

**Comment by blackpeter11** [comment]
My previous neovim was installed through homebrew. Now I try to download the compiled version (compressed package) on github but still have the same problem below：
<img width="1548" alt="image" src="https://user-images.githubusercontent.com/90673507/216059061-3c0bd1ae-7260-4fca-ad35-85c7cd05335a.png">

**Comment by CharlesChiuGit** [comment]
`Vimspector unavailable: Requires vim compiled with +python3`
I think your using a apple-silicon machine. Search that error then your might found a way out.

**Comment by CharlesChiuGit** [comment]
side note: @Jint-lzxy we might need to update our issue template for apple silicon machines.

**Comment by ayamir** [comment]
> My previous neovim was installed through homebrew. Now I try to download the compiled version (compressed package) on github but still have the same problem below： <img alt="image" width="1548" src="https://user-images.githubusercontent.com/90673507/216059061-3c0bd1ae-7260-4fca-ad35-85c7cd05335a.png">

https://github.com/ayamir/nvimdots/issues/445#issuecomment-1407387208

**Comment by blackpeter11** [comment]
It seems that our problems are somewhat different, I don't have the lazy package manager.
<img width="1548" alt="image" src="https://user-images.githubusercontent.com/90673507/216064819-44c7f535-d7f1-4f53-a46d-cf3adb14ac5b.png">
And I'm using the latest version of the configuration.

**Comment by blackpeter11** [comment]
I tried some methods on the Internet but none of them solved this problem. 
**Vimspector unavailable: Requires vim compiled with +python3**
This error seems not to be the point. I used the old version of nvim configuration (packer) before, and occasionally the same error will appear after updating the plugin, but the overall use is no problem.

**Comment by CharlesChiuGit** [comment]
`lazy.nvim` haven't start it's bootstrap due to this part:
https://github.com/ayamir/nvimdots/blob/e34a73c6db055cef1693086446683a9bc4674768/init.lua#L4-L14

Which called vimspector at the very first and blocking the entire lazy bootstrap.

**Comment by CharlesChiuGit** [comment]
I guess:
1. u might have left older version of nvim uninstalled.
2. apple silicon issues.

**Comment by ayamir** [comment]
> It seems that our problems are somewhat different, I don't have the lazy package manager. <img alt="image" width="1548" src="https://user-images.githubusercontent.com/90673507/216064819-44c7f535-d7f1-4f53-a46d-cf3adb14ac5b.png"> And I'm using the latest version of the configuration.

`lazy.nvim` will bootstrap itself when you `nvim` for the first time like below picture:

<img width="1274" alt="image" src="https://user-images.githubusercontent.com/61657399/216069024-bfb633b3-56dd-4483-ad81-75f12e305375.png">

**Comment by blackpeter11** [comment]
> > It seems that our problems are somewhat different, I don't have the lazy package manager. <img alt="image" width="1548" src="https://user-images.githubusercontent.com/90673507/216064819-44c7f535-d7f1-4f53-a46d-cf3adb14ac5b.png"> And I'm using the latest version of the configuration.
> 
> `lazy.nvim` will bootstrap itself when you `nvim` for the first time like below picture:
> 
> <img alt="image" width="1274" src="https://user-images.githubusercontent.com/61657399/216069024-bfb633b3-56dd-4483-ad81-75f12e305375.png">

I didn't get the guide as shown in the picture.The problem may be that an error occurred when vimspector was called first.

**Comment by ayamir** [comment]
It's because the clone of `lazy.nvim` failed. So it showed you `Shell 已返回129`. The key problem is your `git` version maybe too old and it doesn't support `git clone --filter=blob:none --branch=stable` instruction.

**Comment by blackpeter11** [comment]
> I guess:
> 
> 1. u might have left older version of nvim uninstalled.
> 2. apple silicon issues.
> 
> If u tried anything to solve it, please state it in this issue so we can have a better idea of the problem. Otherwise we don't know how to help u.

The most common solution on the Internet is：
**pip3 install neovim**
<img width="1543" alt="image" src="https://user-images.githubusercontent.com/90673507/216071916-d4635316-255f-4724-88f1-4daa7add2578.png">
Use this command to configure the python3 environment on neovim.But it didn't work for my problem.

**Comment by blackpeter11** [comment]
> It's because the clone of `lazy.nvim` failed. So it showed you `Shell 已返回129`. The key problem is your `git` version maybe too old and it doesn't support `git clone --filter=blob:none --branch=stable` instruction.

Thanks, it's the git version problem, after I use homebrew to update the git version, the problem is solved.

**Comment by Jint-lzxy** [comment]
> side note: @Jint-lzxy we might need to update our issue template for apple silicon machines.

@CharlesChiuGit No, FWIW it has nothing to do with chips. For what I can tell `Homebrew` has almost fully supported Apple Silicon. There should be no case where source code is the same but machine code is interpreted differently :)

> `lazy.nvim` haven't start it's bootstrap due to this part:
> 
> https://github.com/ayamir/nvimdots/blob/e34a73c6db055cef1693086446683a9bc4674768/init.lua#L4-L14
>
> Which called vimspector at the very first

It has nothing to do with `vimspector`. In fact, this config does not require `vimspector` at all. I suspect that legacy plugins were still loaded _(via native package mgr)_ as the author did not completely clean up previous installation.

This warning message is issued by [vimspector itself](https://github.com/puremourning/vimspector/blob/ecf0c51b07ffedeca054581623bdda0d458e39d2/plugin/vimspector.vim#L16-L25):
```vim
if !has( 'python3' )
  augroup VimspectorNoPython
    autocmd!
    autocmd VimEnter *
          \   echohl WarningMsg
          \ | echom 'Vimspector unavailable: Requires Vim compiled with +python3'
          \ | echohl None
  augroup END
  finish
endif
```

> and blocking the entire lazy bootstrap.

Hmm but this is the exact reason for using `vim.schedule` instead of just calling the function:
```console
:h vim.schedule

vim.schedule({callback})                                      *vim.schedule()*
    Schedules {callback} to be invoked soon by the main event-loop. Useful
    to avoid |textlock| or other temporary restrictions.
```
It will wait until all resources are available before attempting to run this function 😄

**Comment by CharlesChiuGit** [comment]
I realize it now! Much thanks to the elaborate explanations!

**Comment by CharlesChiuGit** [comment]
> @CharlesChiuGit There's an [awesome video](https://www.youtube.com/watch?v=GMS0JvS7W1Y) where TJ explains `vim.schedule`. 👍

Actually I had saw that video already lol
I just blindly guessing around, sorry for the miss-leading!

**Comment by Jint-lzxy** [comment]
> > @CharlesChiuGit There's an [awesome video](https://www.youtube.com/watch?v=GMS0JvS7W1Y) where TJ explains `vim.schedule`. 👍
> 
> Actually I had saw that video already lol I just blindly guessing around, sorry for the miss-leading!


No worries, happens to the best of us 🍻

**Comment by Dennis-Zhang-SH** [comment]
I am meeting the same problem, upgrading git didn't solve it.

**Comment by Dennis-Zhang-SH** [comment]
> @Dennis-Zhang-SH r u using nvim0.9?

Yes, somehow the git in the ~/.local/share/nvim/lazy messed up, I manually delate&update the repo and then it works.
