### ISSUE TITLE
Two minor issues beyond the novice's knowledge

### ISSUE THREAD

**Issue by cyear** [ayamir/nvimdots#466]
```
We've released version v1.0.0!
It has brought about some major changes that would require a manual cleanup.

Visit https://github.com/ayamir/nvimdots/releases to see the release notes.

To silence this message, remove it from `init.lua` at root directory!
```
and
```
[mason-lspconfig.nvim] installing efm
[mason-lspconfig.nvim] installing clangd
[mason-lspconfig.nvim] installing gopls
Spawning language server with cmd: `efm-langserver` failed. The language server is either not installed, missing from PATH, or not executable.
```

**1. How to remove the version v1.0.0 error, in "init.lua"**

**2. Mason always reports an error, reinstall the same**

**Comment by ayamir** [comment]
1. Comment these lines: https://github.com/ayamir/nvimdots/blob/09b2c745d3414fdf89f6b008889e3775efa079b2/init.lua#L5-L17
2. `efm` is required for formatters so it should can be found in your `PATH`. Otherwise formatter won't work. `clangd` and `gopls` are lsp server of `c/cpp` and `go`. You can execute `MasonInstall efm` manually and show we the error log.

**Comment by cyear** [comment]
> 1. Comment these lines: https://github.com/ayamir/nvimdots/blob/09b2c745d3414fdf89f6b008889e3775efa079b2/init.lua#L5-L17
> 2. `efm` is required for formatters so it should can be found in your `PATH`. Otherwise formatter won't work. `clangd` and `gopls` are lsp server of `c/cpp` and `go`. You can execute `MasonInstall efm` manually and show we the error log.

```
  efm                                                        │
┆  11 │ │      ▼ Displaying full log                                       │
┆  12 │ │        can't load package: package github.com/mattn/efm-langserve│
┆  13 │ │        spawn: go failed with exit code 1 and signal 0.
```

**Comment by Jint-lzxy** [comment]
See https://github.com/ayamir/nvimdots/issues/306#issuecomment-1293673748. Use your favorite package manager to install `go`, currently it is either not installed, missing from PATH, or not executable.

**Comment by CharlesChiuGit** [comment]
> See https://github.com/ayamir/nvimdots/issues/306#issuecomment-1293673748. Use your favorite package manager to install `go`, currently it is either not installed, missing from PATH, or not executable.

second with this, since efm is written in golang, so u need go pkg manager to install it.

**Comment by Jint-lzxy** [comment]
You may also have a look at the latter part of https://github.com/ayamir/nvimdots/issues/370#issuecomment-1356827997. It briefly introduces `LSP` and its features.

**Comment by ayamir** [comment]
You can install them manually and add them to `PATH`. Then comment these lines: 

https://github.com/ayamir/nvimdots/blob/09b2c745d3414fdf89f6b008889e3775efa079b2/lua/modules/completion/lsp.lua#L37

https://github.com/ayamir/nvimdots/blob/09b2c745d3414fdf89f6b008889e3775efa079b2/lua/modules/completion/lsp.lua#L39-L40

**Comment by cyear** [comment]
> > > See [#306 (comment)](https://github.com/ayamir/nvimdots/issues/306#issuecomment-1293673748). Use your favorite package manager to install `go`, currently it is either not installed, missing from PATH, or not executable.
> > 
> > ```
> > go version go1.13.8 linux/amd64
> > ```
> 
> Then I/O probably timed out. Did you set `GOPATH` to an invalid path?
> 
> Also, can you yank the _complete_ error message and paste that here? Now it has been cut off.
> 
> > also
> > 
> > ```
> > Installing (1)
> > ┆   │ │      clangd                                                     │
> > ┆   │ │      ▼ Displaying full log
> > ```
> > 
> > No log！
> 
> That would be expected. As `mason` is fetching this [from `GitHub`](https://github.com/williamboman/mason.nvim/blob/24846a00941ec020c8addc7f52040a1b2fc12174/lua/mason-registry/clangd/init.lua#L20-L42):
> ```lua
>     install = function(ctx)
>         local source = github.unzip_release_file {
>             repo = "clangd/clangd",
>             asset_file = function(release)
>                 local target = coalesce(
>                     when(platform.is.mac, "clangd-mac-%s.zip"),
>                     when(platform.is.linux_x64, "clangd-linux-%s.zip"),
>                     when(platform.is.win_x64, "clangd-windows-%s.zip")
>                 )
>                 return target and target:format(release)
>             end,
>         }
>         source.with_receipt()
>         ctx.fs:rename(("clangd_%s"):format(source.release), "clangd")
>         ctx:link_bin(
>             "clangd",
>             path.concat {
>                 "clangd",
>                 "bin",
>                 platform.is.win and "clangd.exe" or "clangd",
>             }
>         )
>     end,
> ```

The latest ```GO``` solves the download error
