### ISSUE TITLE
clang-format: Use style configuration file

### ISSUE THREAD

**Issue by xiaguan** [ayamir/nvimdots#470]
### Feature description

大部分C/C++工程采用clang-format控制格式，并且都会放到根目录下，仓库的format不会读取这个文件，导致我如果开启format-on-save的话，它不能按照我预期去格式化。我想如果增加这个feature对大部分C/C++工程都是很好用的。如果不增加这个feature的话，是否可以在wiki中增加如何自定义format格式的方法？
万分感谢。

**Comment by Jint-lzxy** [comment]
That's possible. Instead of specifying the options explicitly, change this line:
https://github.com/ayamir/nvimdots/blob/87812fc44d4c375679e8a943601ac300997bfd05/lua/modules/completion/efm/formatters/clangfmt.lua#L1
to:
```lua
return { formatCommand = "clang-format -style=file", formatStdin = true } 
```

**Comment by ayamir** [comment]
Just remove all of args after `clang-format`, it will respect your project's format style defined by `.clang-format`. Like this:
```lua
return { formatCommand = "clang-format", formatStdin = true } 
```

**Comment by Jint-lzxy** [comment]
If you would like to learn more details, visit: [docs/ClangFormat#standalone-tool](https://clang.llvm.org/docs/ClangFormat.html#standalone-tool])

**Comment by xiaguan** [comment]
thanks
