### ISSUE TITLE
Move around in toggleterm

### ISSUE THREAD

**Issue by namespacebilibili** [ayamir/nvimdots#473]
### Feature description

When I try to get back to normal mode in Toggleterm, I use <C-\\> + <C-n> but failed because <C-\\> has been used to open Toggleterm. So using another keymap maybe better(I just comment all the stuff).
<img width="1269" alt="image" src="https://user-images.githubusercontent.com/91790440/216814489-955e98ac-98c7-4a9b-a983-f8ac0a09e98e.png">

**Comment by ayamir** [comment]
> When I try to get back to normal mode in Toggleterm, I tried <C-\> + but failed because <C-\> has been used to open Toggleterm.

Do you use vim mode in terminal and set `<C-\>` to escape to normal mode?

**Comment by namespacebilibili** [comment]
Emm..I don't really get you but `<C-\>` just closes the terminal.The problem is i can't get back to normal mode when in terminal mode and i don't modify the keymap configuration.

**Comment by ayamir** [comment]
> because <C-\> has been used to open Toggleterm.

`<C-\>` is configured to toggle the horizontal terminal not just open it. You can use `<C-\>` to open and hide it.

> The problem is i can't get back to normal mode when in terminal mode

So what you want is keep the terminal showing and use a keymap to jump to the opened buffer?

**Comment by ayamir** [comment]
501927194a93cca989c3ebf0adbbb8041e51494f

**Comment by namespacebilibili** [comment]
> So what you want is that keep the terminal open and use some keymaps to move cursor in and out of the terminal? If so, it can be implemented.

That's true, thanks
