### ISSUE TITLE
Installation failed for efm, gopls

### ISSUE THREAD

**Issue by darkwilldie** [ayamir/nvimdots#477]
### Version confirmation

- [X] Confirm

### Following prerequisites

- [X] Confirm

### Neovim version

NVIM v0.8.3

### Operating system/version

wsl2

### Terminal name/version

window terminal

### Branch info

main (Default/Latest)

### Fetch Preferences

SSH (use_ssh = true)

### How to reproduce the issue

There are MasonInstall's error logs:
  Failed
      gopls
      ▼ Displaying full log
        go: golang.org/x/tools/gopls@latest: module golang.org/x/tools/gopls: Get "https://proxy.golang.org/golang.org/x/tools/gopls/@v/list": dial tcp 172.217.163.49:443: i/o timeout
        spawn: go failed with exit code 1 and signal 0. 
        
      efm
      ▼ Displaying full log
        go: github.com/mattn/efm-langserver@latest: module github.com/mattn/efm-langserver: Get "https://proxy.golang.org/github.com/mattn/efm-langserver/@v/list": dial tcp 142.251.42.241:443: i/o timeout
        spawn: go failed with exit code 1 and signal 0. 

### Expected behavior

I would like to know if there are other ways to install them manually.Maybe because of the Great Firewall？

**Comment by ayamir** [comment]
execute this `go env -w GOPROXY=https://proxy.golang.com.cn,direct` then retry.
