### ISSUE TITLE
How can I traverse functions with jump list?

### ISSUE THREAD

**Issue by goodpaperman** [ayamir/nvimdots#479]
### Feature description

commonly I use  g + d/D/h jump between functions, from calling point to definition, and vice versa. 
I go back and forth by Ctrl + I/O with jump stacks, but when I do some searches between function jumps, it becomes a real mess !

so, I want to know if there any standalone jump stack for functions (and shortcuts, too), it will be useful if one just want to read code, after reading currrent function, he can go back the calling place by a simple command, no matter how many searches there are in this file.

can nvim support this feature? or tell me how if it has been supported.
thanks a lot~

### Additional information

jump stacks in vim (:ls)
![图片](https://user-images.githubusercontent.com/8522640/216959495-0ce22a24-f422-4339-a993-3a1385c6aa22.png)

**Comment by ayamir** [comment]
You want a new keymap to back and force for the jumps which are just caused by `gD`

**Comment by goodpaperman** [comment]
g + D/d/h，all jumps about function

**Comment by CharlesChiuGit** [comment]
Perhaps this one:
https://github.com/cbochs/portal.nvim

**Comment by CharlesChiuGit** [comment]
@goodpaperman The official term in nvim of jump stack is "jump list"

**Comment by Jint-lzxy** [comment]
@goodpaperman I would like to provide a vim-builtin solution. If you need a location that you can jump to that is independent of what you do later, you can use a global mark _(`m[A-Z]` to mark and `` `(or ')[A-Z] `` to goto a mark)_. This is extremely useful if your requirement is to "go back to the calling place". You may have your own marking rules so that you can mark in that order and return to the place you want. After a period of adaptation, you will find out that this feature can actually take you to anywhere you want.

`:h mark`

AFAIK Bram doesn't have a plan to implement features like "jump list modification". _(Sorry I can't find that issue for the time being)_

**Comment by goodpaperman** [comment]
> @goodpaperman P.S. The official term in nvim of jump stack is "jump list".

that's right

**Comment by goodpaperman** [comment]
> @goodpaperman I would like to provide a vim-builtin solution. If you need a location that you can jump to that is independent of what you do later, you can use a global mark _(`m[A-Z]` to mark and `` `(or ')[A-Z] `` to goto a mark)_. This is extremely useful if your requirement is to "go back to the calling place". You may have your own marking rules so that you can mark in that order and return to the place you want. After a period of adaptation, you will find out that this feature can actually take you to anywhere you want.
> 
> `:h mark`
> 
> AFAIK Bram doesn't have a plan to implement features like "jump list modification". _(Sorry I can't find that issue for the time being)_

do you meaning make the function jump list by global mark? some comstomization is needed, I think. 
Using marks directly is inconvenient in my situation.

**Comment by goodpaperman** [comment]
> Perhaps this one: https://github.com/cbochs/portal.nvim

It seems to be  a  jump list manager, not what I need

**Comment by Jint-lzxy** [comment]
> > @goodpaperman I would like to provide a vim-builtin solution. If you need a location that you can jump to that is independent of what you do later, you can use a global mark _(`m[A-Z]` to mark and `` `(or ')[A-Z] `` to goto a mark)_. This is extremely useful if your requirement is to "go back to the calling place". You may have your own marking rules so that you can mark in that order and return to the place you want. After a period of adaptation, you will find out that this feature can actually take you to anywhere you want.
> > `:h mark`
> > AFAIK Bram doesn't have a plan to implement features like "jump list modification". _(Sorry I can't find that issue for the time being)_
> 
> do you meaning make the function jump list by global mark? some comstomization is needed, I think. Using marks directly is inconvenient in my situation.

Yep, but you can go far beyond this. First you should create a mark list _(the marks in this list are not commonly used [directly])_, and then implement this feature by maintaining a stack + calling `Lspsaga goto_definition`. You can set a custom keymap to directly call this function.

**Comment by goodpaperman** [comment]
Quantitative limitation for this solution? vim has 26 global marks at most, when I browse large project, that maybe not enough..

**Comment by Jint-lzxy** [comment]
> Quantitative limitation for this solution? vim has 26 global marks at most, when I browse large project, that maybe not enough..

Then from another perspective. If you just don't want search jumps to be recorded in the jump list, you could define your own mapping like this _(just an example)_:
```lua
["n|<A-n>"] = map_cr("keepjumps normal n"):with_noremap():with_silent(), -- search forward
```
`:h :keepjumps`
***

p.s., You can also use `<leader>h` to switch between the header file and corresponding source code if it's a C-family project.

https://github.com/ayamir/nvimdots/blob/d0d63ad7f7ae3fccc123862b3e49faac144fa63d/lua/core/event.lua#L107-L111

If you don't prefer to open this in a split, you can change it to:
```lua
"nnoremap <silent> <leader>h :ClangdSwitchSourceHeader<CR>",
```

**Comment by CharlesChiuGit** [comment]
> It seems to be  a  jump list manager, not what I want

how about this?

https://github.com/asbjornhaland/telescope-send-to-harpoon.nvim

with harppon.nvim

**Comment by goodpaperman** [comment]
> > Quantitative limitation for this solution? vim has 26 global marks at most, when I browse large project, that maybe not enough..
> 
> Then from another perspective. If you just don't want search jumps to be recorded in the jump list, you could define your own mapping like this _(just an example)_:
> 
> ```lua
> ["n|<A-n>"] = map_cr("keepjumps normal n"):with_noremap():with_silent(), -- search forward
> ```
> 
> `:h :keepjumps`
> 
> p.s., You can also use `<leader>h` to switch between the header file and corresponding source code if it's a C-family project.
> 
> https://github.com/ayamir/nvimdots/blob/d0d63ad7f7ae3fccc123862b3e49faac144fa63d/lua/core/event.lua#L107-L111
> 
> If you don't prefer to open this in a split, you can change it to:
> 
> ```lua
> "nnoremap <silent> <leader>h :ClangdSwitchSourceHeader<CR>",
> ```

I know your idea: filter out other jumps to keep the jump list only record function jumps. 
that's novel, I will consider.

knowlege about switch between cpp & h is useful, I have change my configures. thanks a lot~

**Comment by goodpaperman** [comment]
> > It seems to be  a  jump list manager, not what I want
> 
> how about this?
> 
> https://github.com/asbjornhaland/telescope-send-to-harpoon.nvim
> 
> with [harpoon.nvim](https://github.com/theprimeagen/harpoon)
> 
> https://youtu.be/Qnos8aApa9g

Learn much from the demo video, harpoon focus on jumps between files, auto saves positions when switch buffer or quit, but jumps inside a large file is not supported, maybe need a little customize, I will refer to it, thanks a lot~

**Comment by CharlesChiuGit** [comment]
@goodpaperman I think maybe you'll be interested in this plugin: https://github.com/DNLHC/glance.nvim
