### ISSUE TITLE
当我删除rust.nvim这个就报错而且packer.nvim也没用了

### ISSUE THREAD

**Issue by Leiyi548** [ayamir/nvimdots#48]
![image](https://user-images.githubusercontent.com/76139422/143864288-500a3b6f-0f04-4402-88ec-1ed95c27c1bc.png)

**Comment by ayamir** [comment]
手动执行`packadd packer.nvim` 然后`PackerSync`

**Comment by Leiyi548** [comment]
@ayamir 为啥我packadd packer.nvim 添加进去还是无法执行PackerSync

**Comment by Leiyi548** [comment]
@ayamir  
![image](https://user-images.githubusercontent.com/76139422/143867306-f8b0068a-13ad-40fc-88cc-2172ef006fce.png)
添加后还是这样

**Comment by ayamir** [comment]
你现在进去之后是啥情况？

**Comment by Leiyi548** [comment]
@ayamir  老样子

**Comment by Leiyi548** [comment]
![image](https://user-images.githubusercontent.com/76139422/143869075-12eccb97-1266-4988-8f2d-91fbb40a0997.png)
@ayamir

**Comment by ayamir** [comment]
我不知道如何复现，你配置的仓库呢？

**Comment by Leiyi548** [comment]
@ayamir  https://github.com/Leiyi548/nvim

**Comment by ayamir** [comment]
我打开之后也没问题啊

**Comment by Leiyi548** [comment]
@ayamir  你用了我现在这个配置,没有问题吗..我也是把lang里面那个插件和lang的conf不要的给删除了

**Comment by ayamir** [comment]
`rm -fr ~/.local/share/nvim/site`之后再试试吧

**Comment by Leiyi548** [comment]
@ayamir 我试过了,这样会重新下载插件,然后继续一样错误

**Comment by ayamir** [comment]
我用你这个配置是一点问题都没有，你是不是没有push？

**Comment by Leiyi548** [comment]
![image](https://user-images.githubusercontent.com/76139422/143870537-ef4fcc6a-a217-4494-86e5-e5e7e345ac32.png)
push了

**Comment by ayamir** [comment]
你是打开什么文件了吗？我这里确实没问题。。

**Comment by Leiyi548** [comment]
@ayamir  ok了,我又重新运行下卸载重来解决了问题,谢谢你的帮助.
