### ISSUE TITLE
Failed to run `config` for telescope.nvim

### ISSUE THREAD

**Issue by darkwilldie** [ayamir/nvimdots#484]
### Version confirmation

- [X] Confirm

### Following prerequisites

- [X] Confirm

### Neovim version

NVIM v0.8.3

### Operating system/version

wsl2

### Terminal name/version

window terminal

### Branch info

main (Default/Latest)

### Fetch Preferences

SSH (use_ssh = true)

### How to reproduce the issue

When i run <space>ff, an error message appeared.i think every command about telescope.nvim will be the same.

### Expected behavior

i'd like to know how to fix the error.should i reinstall anything?

### Actual behavior

`Failed to run `config` for telescope.nvim

...e/lazy/telescope.nvim/lua/telescope/_extensions/init.lua:10: 'frecency' extension doesn't exist or isn't installed: module 'telescope._extensions.frecency' not found:
	no field package.preload['telescope._extensions.frecency']module telescope._extensions.frecency not found
	no file './telescope/_extensions/frecency.lua'
	no file '/__w/neovim/neovim/.deps/usr/share/luajit-2.1.0-beta3/telescope/_extensions/frecency.lua'
	no file '/usr/local/share/lua/5.1/telescope/_extensions/frecency.lua'
	no file '/usr/local/share/lua/5.1/telescope/_extensions/frecency/init.lua'
	no file '/__w/neovim/neovim/.deps/usr/share/lua/5.1/telescope/_extensions/frecency.lua'
	no file '/__w/neovim/neovim/.deps/usr/share/lua/5.1/telescope/_extensions/frecency/init.lua'
	no file './telescope/_extensions/frecency.so'
	no file '/usr/local/lib/lua/5.1/telescope/_extensions/frecency.so'
	no file '/__w/neovim/neovim/.deps/usr/lib/lua/5.1/telescope/_extensions/frecency.so'
	no file '/usr/local/lib/lua/5.1/loadall.so'
	no file './telescope.so'
	no file '/usr/local/lib/lua/5.1/telescope.so'
	no file '/__w/neovim/neovim/.deps/usr/lib/lua/5.1/telescope.so'
	no file '/usr/local/lib/lua/5.1/loadall.so'

# stacktrace:
  - /telescope.nvim/lua/telescope/_extensions/init.lua:10 _in_ **load_extension**
  - /telescope.nvim/lua/telescope/_extensions/init.lua:62 _in_ **load_extension**
  - .config/nvim/lua/modules/tools/config.lua:74 _in_ **config**
`

**Comment by CharlesChiuGit** [comment]
it seems like some plugins are not installed properly, remove the entire plugin folder and reinstall again is recommended.

**Comment by ayamir** [comment]
```
rm -fr ~/.local/share/nvim/site/lazy
```
Then reopen `nvim`.

**Comment by darkwilldie** [comment]
Thanks.after i did so, the error became something about sqlite3.so i `sudo apt install libsqlite3-dev`, now everything is fine.
