### ISSUE TITLE
override feature request

### ISSUE THREAD

**Issue by justforlxz** [ayamir/nvimdots#487]
### Feature description

Provide a directory like `lua/override` or `lua/user`, allowing users to provide their own "standard directory structure" to load plugins, avoid modifying the content of core or modules, so that they can fetch upstream without resolving conflicts.

**Comment by CharlesChiuGit** [comment]
https://github.com/ayamir/nvimdots/wiki/Usage#how-to-customize

**Comment by Jint-lzxy** [comment]
Closed as already recorded in the wiki

**Comment by justforlxz** [comment]
oh, I didn't read it properly, sorry.
