### ISSUE TITLE
How to preview the markdown file?

### ISSUE THREAD

**Issue by darkwilldie** [ayamir/nvimdots#492]
`F12`and`:MarkdownPreview`didn't work and nothing happened.

**Comment by CharlesChiuGit** [comment]
https://github.com/ayamir/nvimdots/wiki/Prerequisites

**Comment by CharlesChiuGit** [comment]
Also make sure your plugin is installed correctly. If not, remove the plugin folder and re-install again.

**Comment by Jint-lzxy** [comment]
@darkwilldie You can try installing this plugin manually:
```sh
cd ~/.local/share/nvim/site/lazy/markdown-preview.nvim
cd app && yarn install
```

**Comment by darkwilldie** [comment]
`00h00m00s 0/0: : ERROR: [Errno 2] No such file or directory: 'install'
` @Jint-lzxy I did so and there's the error.should i run some other command first?

**Comment by Jint-lzxy** [comment]
So it looks like your installation is incomplete. Let `lazy.nvim` install the plugin again. Pay special attention to `git` output. Errors are usually not captured.
```sh
rm -rf ~/.local/share/nvim/site/lazy/markdown-preview.nvim
nvim
```

**Comment by Jint-lzxy** [comment]
@darkwilldie So it looks like your installation is incomplete. Let `lazy.nvim` install this plugin again. Pay special attention to `git` output. Errors are usually not captured.
```sh
rm -rf ~/.local/share/nvim/site/lazy/markdown-preview.nvim
nvim
```

**Comment by CharlesChiuGit** [comment]
Close for no further response. feel free to reopen it.
