### ISSUE TITLE
cmp-rg will access invalid memory

### ISSUE THREAD

**Issue by lovebaihezi** [ayamir/nvimdots#50]
# cmp-rg will access invalid memory

## My Enviroment
![image](https://user-images.githubusercontent.com/55340837/143887010-feaf0afd-00cb-4af8-b98b-e8e6de2a999b.png)

## My NeoVim Config:
[github](https://github.com/lovebaihezi/nvim)

## What did I do:
```shell
touch main.py && nvim main.py
```
## What had happened:
the beneath bar will show msg  `cmp-rg/init.lua 29 in function`
![image](https://user-images.githubusercontent.com/55340837/143887266-6984924c-ef27-4144-8044-9e461dd63a30.png)

**Comment by ayamir** [comment]
`cmp-rg` just call `ripgrep` to jsonalize charactors, so you can create a `.ignore` file in your work directory. `ripgrep` will respect it. btw, refer to it: https://github.com/chinanf-boy/ripgrep-zh/blob/master/GUIDE.zh.md#%E8%87%AA%E5%8A%A8%E8%BF%87%E6%BB%A4

**Comment by lovebaihezi** [comment]
thx.
And it seems that some others have the same error, and `cmp-rg` fix this [cmp-rg issue 15](https://github.com/lukas-reineke/cmp-rg/issues/15).
