### ISSUE TITLE
migration: null-ls

### ISSUE THREAD

**Issue by aarnphm** [ayamir/nvimdots#504]
### Feature description

https://github.com/creativenull/efmls-configs-nvim hasn't seen development for a while now.

Also, I think that null-ls have better integration with mason.

**Comment by aarnphm** [comment]
If we decided to migrate to null we will probably need to update the formatted logic as well.

**Comment by CharlesChiuGit** [comment]
I'm working on it! Wait for my PR!

**Comment by CharlesChiuGit** [comment]
Also this had been discussed in #500

**Comment by aarnphm** [comment]
Got it. I will let you do it then.

**Comment by aarnphm** [comment]
This has been merged in to main and will be closing now.
