### ISSUE TITLE
Characters disappeared

### ISSUE THREAD

**Issue by huge-pancake** [ayamir/nvimdots#508]
### Version confirmation

- [X] Confirm

### Following prerequisites

- [X] Confirm

### Neovim version

NVIM v0.8.3

### Operating system/version

Archlinux with kernel version 6.1.10, x86_64

### Terminal name/version

kitty 0.27.1

### $TERM environment variable

xterm-kitty

### Branch info

main (Default/Latest)

### Fetch Preferences

SSH (use_ssh = true)

### How to reproduce the issue

```
sudo pacman -S neovim

bash

if command -v curl >/dev/null 2>&1; then
    bash -c "$(curl -fsSL https://raw.githubusercontent.com/ayamir/nvimdots/HEAD/scripts/install.sh)"
else
    bash -c "$(wget -O- https://raw.githubusercontent.com/ayamir/nvimdots/HEAD/scripts/install.sh)"
fi

nvim
```

Then open any file with indent.

### Expected behavior

Characters render normally.

### Actual behavior

Some of the characters disappear.

### Additional information

![图片](https://user-images.githubusercontent.com/73375859/218257270-4c1616c5-d868-45d3-89a9-0912749a64e8.png)

**Comment by CharlesChiuGit** [comment]
wow that's weird. Have u tried other terminal emulator? Things look fine on my end.

**Comment by huge-pancake** [comment]
Yes, I tried gnome-terminal, Alacritty and foot, nothing changed.

![图片](https://user-images.githubusercontent.com/73375859/218258885-623cd1e5-7e68-4089-8090-eae9a9c8636a.png)

**Comment by huge-pancake** [comment]
I think I know what the problem, I always use 2-spaces for tab, but I changed `tabstop` only, and I also need to change `shiftwidth` and `softtabstop` to `2` to make it work!
