### ISSUE TITLE
nvim启动报错

### ISSUE THREAD

**Issue by LuSany** [ayamir/nvimdots#51]
克隆配置到~/.config然后启动nvim，提示如下错误：

处理 /home/****/.config/nvim/init.lua 时发生错误:
E5113: Error while calling lua chunk: vim/_meta.lua:180: E474: Invalid argument
stack traceback:
        [C]: in function 'nvim_buf_set_option'
        vim/_meta.lua:180: in function '__newindex'
        /home/***/.config/nvim/lua/core/options.lua:129: in function 'load_options'
        /home/***/.config/nvim/lua/core/options.lua:133: in main chunk
        [C]: in function 'require'
        /home/***/.config/nvim/lua/core/init.lua:152: in function 'load_core'
        /home/***/.config/nvim/lua/core/init.lua:161: in main chunk
        [C]: in function 'require'
        /home/***/.config/nvim/init.lua:1: in main chunk

按任意键以后可以进入nvim，无法用PackerInstall安装插件
这个是什么原因造成的？nvim是编译安装的，系统没有安装vim

**Comment by ayamir** [comment]
`nvim +PackerSync`

**Comment by LuSany** [comment]
试了nvim +PackerSync，处理原来的错误，还增加了新的错误

处理 command line 时发生错误:
E492: 不是编辑器的命令: PackerSync

**Comment by ayamir** [comment]
`packadd packer.nvim`
`PackerSync`
还有错误的话请给我完整截图

**Comment by LuSany** [comment]
进入到nvim后输入packadd packer.nvim没有任何反应，再输入PackerSync提示不是编辑器的命令
![image](https://user-images.githubusercontent.com/36779890/144551135-316cd332-ca97-462e-bef6-ab9fdd6920ad.png)

**Comment by ayamir** [comment]
```sh
rm -fr ~/.local/share/nvim
rm -fr ~/.config/nvim
git clone https://github.com/ayamir/nvimdots ~/.config/nvim
```
另外你的nvim什么版本
```sh
nvim --version
```

**Comment by LuSany** [comment]
删除了.local/share/nvim和~/.config/nvim，再重新克隆一份配置，启动nvim后还是报原来的错误。
![image](https://user-images.githubusercontent.com/36779890/144574066-1e202acd-8ae0-49b7-9170-bbe2cf85cebd.png)

按任意键进入到nvim后下载了一些插件，退出后再打开nvim，错误如下：
![image](https://user-images.githubusercontent.com/36779890/144574663-a9c33714-52f2-44f7-bf27-2c6a1f02c12c.png)



nvim --version输出：
NVIM v0.6.0
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
Compilation: /usr/bin/cc -DNVIM_TS_HAS_SET_MATCH_LIMIT -O2 -g -Og -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=auto -DINCLUDE_GENERATED_DECLARATIONS -D_GNU_SOURCE -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/home/xxxx/Documents/neovim/build/config -I/home/10235890@zte.intra/Documents/neovim/src -I/home/xxxx/Documents/neovim/.deps/usr/include -I/usr/local/include -I/home/xxxx/Documents/neovim/build/src/nvim/auto -I/home/xxxx/Documents/neovim/build/include
编译者 xxxx@LIN-C012604185D

Features: +acl +iconv +tui
See ":help feature-compile"

     系统 vimrc 文件: "$VIM/sysinit.vim"
         $VIM 预设值: "/usr/local/share/nvim"

Run :checkhealth for more info

**Comment by ayamir** [comment]
你用release方式编译试试

**Comment by LuSany** [comment]
用release方式编译后编译安装后还是同样的错误

**Comment by ayamir** [comment]
进入nvim之后手动执行：
```sh
lua require('core.pack').sync()
```

**Comment by LuSany** [comment]
进入nvim之后手动执行：lua require('core.pack').sync()，所有插件是可以安装的，但是重新启动nvim还是有同样的错。
我用的系统是公司基于centos8上改造的，直接下载编译好的nvim使用也有同样的问题，所以我才自己编译安装，现在看来有可能是我的系统问题~，~

**Comment by ayamir** [comment]
那你大可不必在公司服务器装，直接使用neovim自带的网络文件编辑功能即可：https://neovim.io/doc/user/pi_netrw.html

**Comment by LuSany** [comment]
我用的是我们公司自己改造的centos8作为日常办公使用的linux，我用vim-plug试试吧，感谢你的及时回复！！！

**Comment by LuSany** [comment]
注释掉options.lua中spellfile = global.cache_dir .. "spell/en.uft-8.add"这行后，插件安装正常，nvim运行不报错，这个是选项是做什么用的？我在~/.cacahe/nvim底下也没有发现"spell/en.uft-8.add"这个文件。

**Comment by ayamir** [comment]
按理说这个文件有或是没有都不会有影响，只是如果有对应的spell文件的话就可以这么设置

**Comment by LuSany** [comment]
"en.uft-8.add"这个文件在哪里能下载到？有下载链接的话发一下，我手动下载这个文件试试看是否还报错。

**Comment by ayamir** [comment]
这个是根据你个人习惯设定的，这里有一个例子：https://github.com/seebi/vimrc/blob/master/spell/en.utf-8.add

**Comment by LuSany** [comment]
试了下自己手动创建的文件还是会报错，目前来看我把spellfile注释掉就可以正常使用了。

**Comment by ayamir** [comment]
我也把其他没用的目录在main分支里面注释掉了

**Comment by LuSany** [comment]
最新的修改，~/.config/nvim/lua/tools/config.lua中“local home = require('core.global').global.home”会报错找不到home，需要修改为“local home = require('core.global').home”

**Comment by ayamir** [comment]
https://github.com/ayamir/nvimdots/commit/9d86a079c4f64b41e3fdab358d1c510f838d0972
