### ISSUE TITLE
sumneko_lua is deprecated, use lua_ls instead.

### ISSUE THREAD

**Issue by Tgist1024** [ayamir/nvimdots#511]
### Version confirmation

- [X] Confirm

### Following prerequisites

- [X] Confirm

### Neovim version

NVIM  v0.8.3

### Operating system/version

Arch linux 6.1.11

### Terminal name/version

kitty 0.27.1

### Branch info

main (Default/Latest)

### Fetch Preferences

SSH (use_ssh = true)

### Affected language servers

sumneko

### How to reproduce the issue

Just use nvim to open any files, and the warning will display.

### Actual behavior

Each time I open some files, the warning message bounces first.
![image](https://user-images.githubusercontent.com/101801875/218298934-f1cf07b9-e6e9-4930-aebd-6b0ac9fbeffa.png)

### Expected behavior

Migrate to lua_ls.

### Support info

:Lspinfo
```
 Language client log: /home/liu/.local/state/nvim/lsp.log
 Detected filetype:   lua
 
 2 client(s) attached to this buffer: 
 
 Client: lua_ls (id: 1, bufnr: [1])
 	filetypes:       lua
 	autostart:       true
 	root directory:  /home/liu/.config/nvim
 	cmd:             lua-language-server
 
 Client: efm (id: 2, bufnr: [1])
 	filetypes:       markdown, javascript, typescriptreact, lua, vim, css, scss, sh, html, yaml, javascriptreact, c, cpp, python, vue, typescript
 	autostart:       true
 	root directory:  /home/liu/.config/nvim
 	cmd:             efm-langserver
 
 Configured servers list: lua_ls, html, bashls, clangd, efm, gopls, pyright

```

:Mason
```
  Installed
      bash-language-server
      black
      clangd
      efm
      gopls
      lua-language-server
      prettier
      pyright
      shellcheck
      shfmt
      stylua
  
```

### Logs

```console
[START][2023-02-12 15:24:41] LSP logging initiated
[ERROR][2023-02-12 15:24:41] .../vim/lsp/rpc.lua:733	"rpc"	"efm-langserver"	"stderr"	"2023/02/12 15:24:41 efm-langserver: no configuration file\n2023/02/12 15:24:41 efm-langserver: reading on stdin, writing on stdout\n"
[ERROR][2023-02-12 15:24:48] .../vim/lsp/rpc.lua:733	"rpc"	"efm-langserver"	"stderr"	"2023/02/12 15:24:48 jsonrpc2 handler: sending response 2: jsonrpc2: connection is closed\n2023/02/12 15:24:48 efm-langserver: connections closed\n"
[START][2023-02-12 15:29:45] LSP logging initiated
[ERROR][2023-02-12 15:29:45] .../vim/lsp/rpc.lua:733	"rpc"	"efm-langserver"	"stderr"	"2023/02/12 15:29:45 efm-langserver: no configuration file\n2023/02/12 15:29:45 efm-langserver: reading on stdin, writing on stdout\n"
[ERROR][2023-02-12 15:30:14] .../vim/lsp/rpc.lua:733	"rpc"	"efm-langserver"	"stderr"	"2023/02/12 15:30:14 jsonrpc2 handler: sending response 2: jsonrpc2: connection is closed\n2023/02/12 15:30:14 efm-langserver: connections closed\n"
[START][2023-02-12 15:32:44] LSP logging initiated
[ERROR][2023-02-12 15:32:44] .../vim/lsp/rpc.lua:733	"rpc"	"efm-langserver"	"stderr"	"2023/02/12 15:32:44 efm-langserver: no configuration file\n2023/02/12 15:32:44 efm-langserver: reading on stdin, writing on stdout\n"
[ERROR][2023-02-12 15:36:20] .../vim/lsp/rpc.lua:733	"rpc"	"efm-langserver"	"stderr"	"2023/02/12 15:36:20 jsonrpc2 handler: sending response 2: jsonrpc2: connection is closed\n2023/02/12 15:36:20 efm-langserver: connections closed\n"
```

**Comment by CharlesChiuGit** [comment]
Thanks for the report, will fix soon.

**Comment by Jint-lzxy** [comment]
We're waiting for the following issue to be merged before pushing any changes:
- [ ] https://github.com/williamboman/mason-lspconfig.nvim/pull/148

**Comment by Jint-lzxy** [comment]
We're waiting for the following PR to be merged before pushing any changes:
- [ ] https://github.com/williamboman/mason-lspconfig.nvim/pull/148

**Comment by CharlesChiuGit** [comment]
side note: other upstream plugins that had already change `sumneko_lua` to `lua_ls`
https://github.com/williamboman/mason.nvim/blob/main/lua/mason-registry/lua-language-server/init.lua
https://github.com/neovim/nvim-lspconfig/blob/master/lua/lspconfig/server_configurations/lua_ls.lua

**Comment by CharlesChiuGit** [comment]
cc @Jint-lzxy 
I'm planning to include this change in the upcoming PR for `efm->null-ls` migration, since I'm changing a lot of related stuffs.

**Comment by Jint-lzxy** [comment]
@CharlesChiuGit It's ok, but I will still push this change as those options will be invalid very soon.

**Comment by CharlesChiuGit** [comment]
> @CharlesChiuGit It's ok, but I will still push this change as those options will be invalid very soon.

Sure, but it seems there's still some place not recognize lua_ls. I'm trying to track the source.
