### ISSUE TITLE
Plugins in custom seem not in the path of keymap: "module 'haskell-tools' not found"

### ISSUE THREAD

**Issue by Tgist1024** [ayamir/nvimdots#516]
### Version confirmation

- [X] Confirm

### Following prerequisites

- [X] Confirm

### Neovim version

NVIM  v0.8.3

### Operating system/version

Arch linux 6.1.11

### Terminal name/version

kitty 0.27.1

### Branch info

main (Default/Latest)

### Fetch Preferences

SSH (use_ssh = true)

### How to reproduce the issue

1. Add plugins.
2. Modify keymap using `map_callback` with `require("new_plugin_name")` like this:
```lua
["n|<leader>rr"] = map_callback(require("haskell-tools").repl.toggle)
:with_silent()
:with_noremap()
:with_desc("Haskell: REPL for package"),
```
3. Error.

### Expected behavior

The keymap works.

### Actual behavior

![image](https://user-images.githubusercontent.com/101801875/218456960-d6b4ba40-76b1-4f03-a8d0-d3c3c13d3b9a.png)

### Additional information

Could see that my plugin is already added correctly before adding the keymap in keymap/init.lua:
![image](https://user-images.githubusercontent.com/101801875/218458049-0e9570b1-29b7-4202-affc-41947ef6d439.png)
(lazy.nvim picture)
After adding the keymap below, it just crashed:
```lua
["n|<leader>rr"] = map_callback(require("haskell-tools").repl.toggle):with_silent():with_noremap():with_desc("Haskell: REPL for package"),
```
The error message said:`E5113: Error while calling lua chunk: /home/liu/.config/nvim/lua/keymap/init.lua:21: module 'haskell-tools' not found`
Is this because of plugins in the custom folder not in the path that keymap search in?

**Comment by aarnphm** [comment]
where did you define your haskel-tools?

**Comment by CharlesChiuGit** [comment]
Try
```lua
	["n|<leader>rr"] = map_callback(function()
			require("haskell-tools").repl.toggle()
		end)
		:with_silent()
		:with_noremap()
		:with_desc("Haskell: REPL for package"),
```
?

**Comment by Tgist1024** [comment]
> where did you define your haskell-tools?

lua/modules/configs/custom/haskell-tools.lua

**Comment by Tgist1024** [comment]
> Try
> 
> ```lua
> 	["n|<leader>rr"] = map_callback(function()
> 			require("haskell-tools").repl.toggle
> 		end)
> 		:with_silent()
> 		:with_noremap()
> 		:with_desc("Haskell: REPL for package"),
> ```
> 
> ?

Find it just works after adding `()` to your second line.😄
Thanks, bro. 
Though still don't know why should wrap it in a function.

**Comment by CharlesChiuGit** [comment]
> Find it just works after adding `()` to your second line.😄

Yeah, I intuitively thought it so weird no to add `()` after `toggle`, but since in #515 don't include `()` so I didn't include it.

**Comment by aarnphm** [comment]
https://github.com/mrcjkb/haskell-tools.nvim/blob/9af20e99b32a4697946a1288e0c393d69e453581/lua/haskell-tools/repl/builtin.lua#LL197C20-L197C26 shows that toggle takes in two argument, so that it would fail to pass into callback.

If you take a look at vim.api.nvim_set_keymap, `opts` is a `:map-arguments`, that optionally takes in a Lua callback. that callback is a `fun(): bool`, which in the case of `haskell-tools` will fail.

I think that for haskell-tool you have to 
```lua
map_callback(function() require("haskell-tools").repl.toggle() end)
```
which is a bit unergonomic.

**Comment by aarnphm** [comment]
also seems like repl.toogle() is a internal API nonetheless.

**Comment by Tgist1024** [comment]
> https://github.com/mrcjkb/haskell-tools.nvim/blob/9af20e99b32a4697946a1288e0c393d69e453581/lua/haskell-tools/repl/builtin.lua#LL197C20-L197C26 shows that toggle takes in two argument, so that it would fail to pass into callback.
> 
> If you take a look at vim.api.nvim_set_keymap, `opts` is a `:map-arguments`, that optionally takes in a Lua callback. that callback is a `fun(): bool`, which in the case of `haskell-tools` will fail.
> 
> I think that for haskell-tool you have to
> 
> ```lua
> map_callback(function() require("haskell-tools").repl.toggle() end)
> ```
> 
> which is a bit unergonomic.

Thanks!
