### ISSUE TITLE
paint.nvim 

### ISSUE THREAD

**Issue by hhcwyx** [ayamir/nvimdots#519]
### Version confirmation

- [X] Confirm

### Following prerequisites

- [X] Confirm

### Neovim version

NVIM0.8.3

### Operating system/version

archlinux+dwm

### Terminal name/version

alacritty

### Branch info

main (Default/Latest)

### Fetch Preferences

SSH (use_ssh = true)

### How to reproduce the issue

在启动的时候,出现以下信息:

Failed to run `config` for paint.nvim

/home/hhc/.config/nvim/lua/modules/configs/ui/paint.lua:2: module 'paint' not found:
	no field package.preload['paint']module paint not found
	no file './paint.lua'
	no file '/usr/share/luajit-2.1.0-beta3/paint.lua'
	no file '/usr/local/share/lua/5.1/paint.lua'
	no file '/usr/local/share/lua/5.1/paint/init.lua'
	no file '/usr/share/lua/5.1/paint.lua'
	no file '/usr/share/lua/5.1/paint/init.lua'
	no file '/home/hhc/.config/nvim/lua/modules/configs/paint.lua'
	no file '/home/hhc/.config/nvim/lua/modules/configs/paint/init.lua'
	no file './paint.so'
	no file '/usr/local/lib/lua/5.1/paint.so'
	no file '/usr/lib/lua/5.1/paint.so'
	no file '/usr/local/lib/lua/5.1/loadall.so'

# stacktrace:
  - .config/nvim/lua/modules/configs/ui/paint.lua:2 _in_ **config**

### Expected behavior

好像原来没有.

**Comment by hhcwyx** [comment]
~/.local/share/nvim/site/lazy/paint.nvim文件夹下面是空的.

**Comment by CharlesChiuGit** [comment]
paint is added recently. looks like u have a nice invalid install. just remove that folder and lazy will auto-reinstall paint again.

**Comment by hhcwyx** [comment]
@CharlesChiuGit ok,谢谢!
