### ISSUE TITLE
E492: 不是编辑器的命令: NvimTreeToggle，以及安装插件问题

### ISSUE THREAD

**Issue by sailzhouk** [ayamir/nvimdots#52]
**Describe the bug**
Macos安装后出现如下问题
调用NvimTreeToggle报错
<img width="413" alt="截屏2021-12-05 下午3 13 29" src="https://user-images.githubusercontent.com/30001973/144737370-4a1a4f9e-4f7d-455b-bc67-a08b1388217f.png">

此外，有几个插件总是安装不上，环境有代理，重复调用PackerSync也无效，并且显示安装不上的插件还不一样
<img width="665" alt="截屏2021-12-05 下午3 14 06" src="https://user-images.githubusercontent.com/30001973/144737389-2177449d-1a50-4d9e-88e0-047fb6748f57.png">

<img width="864" alt="截屏2021-12-05 下午3 19 33" src="https://user-images.githubusercontent.com/30001973/144737563-1e98630d-280b-49b3-ac55-00470a2a9045.png">

**To Reproduce**
Neovim使用brew进行安装，版本是6.0
安装流程完全按照readme中说明，并且按照如下命令重新安装后也无效：
rm -fr ~/.local/share/nvim
rm -fr ~/.config/nvim
git clone https://github.com/ayamir/nvimdots ~/.config/nvim

**Environment (please complete the following information):**
 - OS: Macos
 - Nvim version(output of `nvim --version`)
NVIM v0.6.0
Build type: Release
LuaJIT 2.1.0-beta3
编译者 brew@HMBRW-A-001-M1-002.local

Features: +acl +iconv +tui
See ":help feature-compile"

     系统 vimrc 文件: "$VIM/sysinit.vim"
         $VIM 预设值: "/opt/homebrew/Cellar/neovim/0.6.0/share/nvim"

**Comment by ayamir** [comment]
建议检查网络问题，或者先使用github镜像执行PackerSync
![image](https://user-images.githubusercontent.com/61657399/144743668-53a56f78-9cbd-4c34-b1b2-325fe937a5f2.png)

**Comment by flyingchase** [comment]
这位老哥的情况我遇到过，这是由于 brew 下载的neovim构建的 luv 版本出错导致，详见https://github.com/neovim/neovim/issues/15054，在博主文件的 lua/core/pack.lua 内Packer:load_packer 函数添加 max_jobs 参数设置就行，我也正准备提个 issue 呢。![K3dEe6](https://cdn.jsdelivr.net/gh/flyingchase/Private-Img@master/uPic/K3dEe6.png)

**Comment by sailzhouk** [comment]
> 这位老哥的情况我遇到过，这是由于 brew 下载的neovim构建的 luv 版本出错导致，详见[https://github.com/neovim/neovim/issues/15054，在博主文件的](https://github.com/neovim/neovim/issues/15054%EF%BC%8C%E5%9C%A8%E5%8D%9A%E4%B8%BB%E6%96%87%E4%BB%B6%E7%9A%84) lua/core/pack.lua 内Packer:load_packer 函数添加 max_jobs 参数设置就行，我也正准备提个 issue 呢。![K3dEe6](https://camo.githubusercontent.com/13b66ba3fb6823d82fc91be8875e7f31513fd0e0ac52f6666882e7087ab33c62/68747470733a2f2f63646e2e6a7364656c6976722e6e65742f67682f666c79696e6763686173652f507269766174652d496d67406d61737465722f755069632f4b33644565362e706e67)

感谢老哥，问题已解决！
