### ISSUE TITLE
The plug-in could not find the configuration file

### ISSUE THREAD

**Issue by Yan-weihao** [ayamir/nvimdots#522]
### Version confirmation

- [X] Confirm

### Following prerequisites

- [X] Confirm

### Neovim version

The plug-in could not find the configuration file

### Operating system/version

Arch Linux 6.1.11-arch1-1

### Terminal name/version

6.1.11-arch1-1

### Branch info

main (Default/Latest)

### Fetch Preferences

SSH (use_ssh = true)

### How to reproduce the issue

1. All plug-ins have been installed
2. Enable nvim to report errors directly.

### Expected behavior

It should find the appropriate configuration file

### Actual behavior

Direct error reporting

### Additional information

![Screenshot_2023-02-15-21-09-25_1920x1080](https://user-images.githubusercontent.com/61379647/219036909-748a631e-f0db-4da2-a76e-9045b683aa17.png)
![Screenshot_2023-02-15-21-09-47_1920x1080](https://user-images.githubusercontent.com/61379647/219036928-44114cc4-b9eb-4437-9f0c-a86b09d88d64.png)
![Screenshot_2023-02-15-21-10-56_1920x1080](https://user-images.githubusercontent.com/61379647/219036933-1fd8271b-fbd7-451d-a9cb-093b0f726ef8.png)
![Screenshot_2023-02-15-20-50-29_1920x1080](https://user-images.githubusercontent.com/61379647/219036946-bf15db1d-89e9-4a33-b87e-97251928e374.png)

**Comment by nkta3m** [comment]
reinstall plugins

**Comment by Jint-lzxy** [comment]
```sh
rm -rf ~/.local/share/nvim/site/lazy
nvim
```

**Comment by Yan-weihao** [comment]
> ```shell
> rm -rf ~/.local/share/nvim/site/lazy
> nvim
> ```
I've done this many times, and it's still the same

**Comment by Yan-weihao** [comment]
> 
I re-installed the plug-in, but after a while, the problem continued to occur

**Comment by Yan-weihao** [comment]
And some plugins fail sometimes, I don't know why, for example, lualine plugin doesn't show, it seems that t's dependency stops working,

**Comment by Yan-weihao** [comment]
![Screenshot_2023-02-16-02-17-17_1920x1080](https://user-images.githubusercontent.com/61379647/219117838-6f818f85-4899-4188-a141-cda04e5ad5cd.png)

**Comment by Yan-weihao** [comment]
As of now, by reinstalling a single plugin, there is no error in opening nvim, but the message alert will still pop up the error of the appeal picture

**Comment by Yan-weihao** [comment]
I will lua/modules/configs/editor/comment in lua ts_context_commentstring. Integrations. Conmment_nvim commented, notification will not be an error

**Comment by Yan-weihao** [comment]
![Screenshot_2023-02-16-02-37-17_1920x1080](https://user-images.githubusercontent.com/61379647/219121812-80035965-ba94-41e0-8418-fc1d5710d810.png)

**Comment by aarnphm** [comment]
Did you have 
```lua
			{ "JoosepAlviste/nvim-ts-context-commentstring" },
```
under treesitter dependencies?

If you don't use ts-context-commentstring then you need to comment the pre_hook

**Comment by Yan-weihao** [comment]
> Did you have
> 
> ```lua
> 			{ "JoosepAlviste/nvim-ts-context-commentstring" },
> ```
> 
> under treesitter dependencies?
> 
> If you don't use ts-context-commentstring then you need to comment the pre_hook

I reinstalled the plugin and now it doesn't report any errors.

**Comment by Yan-weihao** [comment]
He checked to see if there would be any error after several days, because there was no error before, but when I used it the next day, it began to report errors again, and it could only be used after re-installing the plug-in

**Comment by aarnphm** [comment]
sg. I will close the issue then.
