### ISSUE TITLE
Some warning for which_key in `:checkhealth`

### ISSUE THREAD

**Issue by CharlesChiuGit** [ayamir/nvimdots#523]
I accidentally found some keymap conflicts in `:checkhealth`'s which-key part
Is this sth we need to resolve? Or it's fine to ignore?
![圖片](https://user-images.githubusercontent.com/32497323/219280175-fd9f7b24-a06f-41d2-bfa4-84e76234a36e.png)

**Comment by ayamir** [comment]
It's because `<leader>c`, `gb`, `gc` are keybindings which also are prefix of other keybindings. No problems.
