### ISSUE TITLE
Neovim-qt runtime path

### ISSUE THREAD

**Issue by nkta3m** [ayamir/nvimdots#527]
### Version confirmation

- [X] Confirm

### Following prerequisites

- [X] Confirm

### Neovim version

NVIM v0.8.3

### Operating system/version

Arch 6.1

### Terminal name/version

Alacritty

### Branch info

main (Default/Latest)

### Fetch Preferences

HTTPS (use_ssh = false)

### How to reproduce the issue

nvim-qt 的runtime 路径没有在rtp中，有些gui的命令没办法使用，这个应该在哪里添加？

### Expected behavior

add /usr/share/nvim-qt/runtime to rtp

**Comment by ayamir** [comment]
I can't understand it. `nvim-qt` will set its runtime path when you execute `nvim-qt`. Why do you want to add it to config?
<img width="671" alt="image" src="https://user-images.githubusercontent.com/61657399/219557721-1ab71ad8-92d6-4347-b4f9-5bb1b955c824.png">

**Comment by nkta3m** [comment]
实际有两个路径：
1. `scoop\apps\neovim\current\share\nvim\runtime`
2. `scoop\apps\neovim\current\share\nvim-qt\runtime`
但是第二个路径不在rtp中，Gui相关的命令就无效了。

**Comment by nkta3m** [comment]
我在`core/init.lua`最后一句加入`"set runtimepath+=" .. global.home .. "\\scoop\\apps\\neovim\\current\\share\\nvim-qt\\runtime"`
就可以正常使用了，但是我不知道在这个位置添加是否合理

**Comment by CharlesChiuGit** [comment]
What if u add `scoop\apps\neovim\current\share\nvim-qt\runtime` to windows env variable?

**Comment by nkta3m** [comment]
i set `$env:NVIM_QT_RUNTIME_PATH="~\scoop\apps\neovim\current\share\nvim-qt\runtime"`, not work

**Comment by ayamir** [comment]
... So you are using Windows why report OS is archlinux?

**Comment by nkta3m** [comment]
arch has same error

**Comment by CharlesChiuGit** [comment]
`lazy.nvim` will clear rtp for faster startup, which causing some plugin to have issues. The recent release of `lazy` v9.8.3 seen to have some workaround on this. Can u try update lazy to 9.8.3 can see if things changed?

**Comment by ayamir** [comment]
https://github.com/folke/lazy.nvim/issues/23#issuecomment-1359608717

**Comment by nkta3m** [comment]
是的，如果我把`"set runtimepath+=" .. global.home .. "\\scoop\\apps\\neovim\\current\\share\\nvim-qt\\runtime"`放在最后就没问题，如果放在这几个前面，就失效了
![2023-02-17 14_09_37-Window](https://user-images.githubusercontent.com/13484700/219563632-4ba3e01d-3c44-4b8f-a5d5-8cddc8ad6306.png)

**Comment by nkta3m** [comment]
谢谢。

**Comment by CharlesChiuGit** [comment]
I'll add this to https://github.com/ayamir/nvimdots/wiki/Issues.
