### ISSUE TITLE
Lspsaga peek_definition windows not respond to < C-c > Lspsaga shortcut keys

### ISSUE THREAD

**Issue by HATTER-LONG** [ayamir/nvimdots#533]
### Version confirmation

- [x] Confirm

### Following prerequisites

- [X] Confirm

### Neovim version

NVIM v0.9.0-dev-956+gff3d04b75-dirty

### Operating system/version

macOS 13.1

### Terminal name/version

Kitty

### Branch info

main (Default/Latest)

### Fetch Preferences

SSH (use_ssh = true)

### How to reproduce the issue

1. `<gd>` into peek windows.
2. `<C-c>v`  use Lspsaga shortcut which split windows.
3. nothing respond.

### Expected behavior

1. `<gd>` into peek windows.
2. `<C-c>v`  use Lspsaga shortcut which split windows.
3. split windows.

### Additional information

I think `which-key` Interferes with the execution of shortcut keys.
Use `<zz>` in peek window, `<C-c>v` will respond.

**Comment by ayamir** [comment]
Can repo, but don't know how to debug...

**Comment by HATTER-LONG** [comment]
I update all plugin and config, and the problem still exists.

**Comment by Jint-lzxy** [comment]
@ayamir Looks like `which-key` failed to take over keymap responses in temporary buffers with `timeoutlen = 0`. This issue cannot be reproduced when `which-key` is disabled.

**Comment by HATTER-LONG** [comment]
Yes, as I wrote in the problem description, when in temporary buffers , after use like `<zz>`  the `<C-c>` will responses. But I don't know how to continue debug.

**Comment by Jint-lzxy** [comment]
@HATTER-LONG Add the following content to `~/.config/nvim/init.lua`, reopen `neovim`, and wait for the floating window to open. Then check whether `<C-c>q` is valid in normal mode _(it'll close that window)_.
```lua
vim.defer_fn(function()
	local stats = vim.api.nvim_list_uis()[1]
	local width = stats.width
	local height = stats.height
	local winWidth = math.ceil(width * 0.8)
	local winHeight = math.ceil(height * 0.8)

	local buf = vim.api.nvim_create_buf(false, true)
	local winConfig = {
		relative = "editor",
		width = winWidth,
		height = winHeight,
		col = math.ceil((width - winWidth) / 2),
		row = math.ceil((height - winHeight) / 2) - 1,
		border = "rounded",
	}
	local winid = vim.api.nvim_open_win(buf, true, winConfig)

	vim.keymap.set("n", "<C-c>q", function()
		vim.api.nvim_win_close(winid, true)
	end, { buffer = buf, nowait = true })
end, 1000)
```

**Comment by HATTER-LONG** [comment]
Nope, it not respond.

<img width="848" alt="image" src="https://user-images.githubusercontent.com/31438141/221389091-262d0d3b-2903-4a3d-9f45-3e29a2a0a82b.png">

**Comment by Jint-lzxy** [comment]
Then we have a minimum repro 👍 IMO it would be better to open this issue in the upstream repo. We can't do much about this.

**Comment by Jint-lzxy** [comment]
@HATTER-LONG Then we have a minimum repro 👍 IMO it would be better to open this issue in the upstream repo. We can't do much about this.

**Comment by HATTER-LONG** [comment]
@Jint-lzxy  Ok. I will check it, thx.

**Comment by ayamir** [comment]
seems like it can be solved by configure `which-key.nvim` like this:
```lua
return function()
	local icons = {
		ui = require("modules.utils.icons").get("ui"),
		misc = require("modules.utils.icons").get("misc"),
	}

	require("which-key").setup({
		plugins = {
			presets = {
				operators = false,
				motions = false,
				text_objects = false,
				windows = false,
				nav = false,
				z = true,
				g = true,
			},
		},

		icons = {
			breadcrumb = icons.ui.Separator,
			separator = icons.misc.Vbar,
			group = icons.misc.Add,
		},

		window = {
			border = "none",
			position = "bottom",
			margin = { 1, 0, 1, 0 },
			padding = { 1, 1, 1, 1 },
			winblend = 0,
		},

		triggers_blacklist = {
			n = { "<C-c>" },
		},
	})
end
```
Just add `<C-c>` to `triggers_blacklist`.

**Comment by HATTER-LONG** [comment]
it does not work for me, `<C-c>` effect is the same as before.

**Comment by fecet** [comment]
Have the same problem
