### ISSUE TITLE
Lspsaga v0.2.7 floating diagnostic 

### ISSUE THREAD

**Issue by CharlesChiuGit** [ayamir/nvimdots#535]
https://github.com/ayamir/nvimdots/blob/2539b1de50b34e46d1d3a39aef804aa81cb6021a/lua/modules/configs/completion/lspsaga.lua#L71

Setting `on_insert = true` will cause a floating diagnostic on the right corner of the window. Maybe we should keep `on_insert = false` as default like before? This might confuses users quite a bit.

![圖片](https://user-images.githubusercontent.com/32497323/220043831-86b7d437-cfe7-4cb4-a2a8-5dd57debcaa4.png)

**Comment by toyuanx** [comment]
<img width="1295" alt="image" src="https://user-images.githubusercontent.com/19640938/220065032-1103dcca-c219-414e-8889-e094e6b06671.png">
Is this what you mean? I also encountered this problem.

**Comment by CharlesChiuGit** [comment]
> <img alt="image" width="1295" src="https://user-images.githubusercontent.com/19640938/220065032-1103dcca-c219-414e-8889-e094e6b06671.png">
> Is this what you mean? I also encountered this problem.

Sorry, I think it's another issue. Maybe it's a upstream issue I guess?

**Comment by Jint-lzxy** [comment]
> Setting `on_insert = true` will cause a floating diagnostic on the right corner of the window. Maybe we should keep `on_insert = false` as default like before? This might confuses users quite a bit.

This comes from an upstream "emacs-like" feature request. Sure if @ayamir also agrees with this 👍

**Comment by ayamir** [comment]
https://github.com/glepnir/lspsaga.nvim/pull/867/commits/dc7031b2d8ac0e13f3109daa54084b474faf2c64
IMO we can keep it `true`.
