### ISSUE TITLE
请问怎么修改标题

### ISSUE THREAD

**Issue by Aizaixyq** [ayamir/nvimdots#542]
### Feature description

在win终端使用时，在打开文件时，标签卡标题会固定显示C:\WINDOWS\system32\cmd.exe ，我在尝试了一些方法后无法修改，请问如何修改，谢谢

### Additional information

![image](https://user-images.githubusercontent.com/96584640/221416472-b1b6375d-4d75-480f-b93d-1dede941ee1a.png)

**Comment by CharlesChiuGit** [comment]
Not a nvim problem.
