### ISSUE TITLE
M1 mac install clang-format error

### ISSUE THREAD

**Issue by longintlong** [ayamir/nvimdots#543]
Hi, 我在 :MasonInstall clang-format ，报错可能和 pip 的版本有关，提示我要更新pip ，但是我在更新了之后还是得到了同样的错误，看 log 发现他好像在 `.local/share/nvim/package/mason/clang-format/`下也有一个pip
并且在下面截图中我的 pip 字段是 n/a
<img width="1315" alt="image" src="https://user-images.githubusercontent.com/39492651/221423527-57579ed6-eb7e-477c-b903-0754106993e2.png">

**Comment by Jint-lzxy** [comment]
@longintlong We need more information to understand this issue. What do you see if you run the following commands **in neovim**:

1.
```vim
:!which pip python
```
2.
```vim
:!python --version
```
And the following command in your **terminal**:
```sh
python -m pip install --upgrade pip && pip3 install scikit-build
```
Then in **neovim**, retry:
```vim
:MasonInstall clang-format
```

**Comment by aarnphm** [comment]
Can you try to install scikit-build outside of your editor?

**Comment by aarnphm** [comment]
I also notice that you are using system python, which is not recommended usually. Maybe you can try something like pyenv or even conda.

**Comment by CharlesChiuGit** [comment]
@longintlong u have to python installed. The `pip` is installed in python3.8. However, u also have a python 2.7 effecting your path.

**Comment by CharlesChiuGit** [comment]
> ```
> $ python -m pip install --upgrade pip && pip3 install scikit-build
> /System/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python: No module nam
> ```

If possible, I would strongly recommend u remove python2.7. This out-dated and unsupported python will caused a lot of issues.

**Comment by Jint-lzxy** [comment]
@longintlong I would recommend using `Homebrew` _(or any compatible package manager like `MacPorts`)_ to install the latest version of python and set your `$PATH` to search for those executables first.

> If possible, I would strongly recommend u remove python2.7. This out-dated and unsupported python will caused a lot of issues.
>
> An alternative is to exclude python2.7 from your path if you are familiar enough what's you're doing.

@CharlesChiuGit Hmm AFAIK it is impossible to directly modify any configs related to python on macOS if SIP has been enabled (and the OS will use `python2` by default, unfortunately). _(This is the default. Recovery OS is required to change this behavior - obviously, this might not be the best approach)_

Perhaps using a freshly installed `python3` would be a more convenient solution 😄

**Comment by CharlesChiuGit** [comment]
interesting! noted.

**Comment by longintlong** [comment]
> Can you try to install scikit-build outside of your editor?

`pip3 install scikit-build` can  work

**Comment by longintlong** [comment]
> edit: try to find the venv that mason created for clangd-format and use that python to install pip and cmake.

i can't find the `clang-format/venv` becaues directory `~/.local/share/nvim/mason/packages` does not contain clang-format

**Comment by Jint-lzxy** [comment]
> i guess that mason use python2 when it install setuptools but pip is in py3.8

Yep that would be expected. Do you have the latest version of macOS (> Monterey 12.3) installed? This version finally removed `python2` support. See [macOS Monterey 12.3 Release Notes#Deprecations](https://developer.apple.com/documentation/macos-release-notes/macos-12_3-release-notes#Deprecations). For macOS versions <12.3 they have a series of env issues for compatibility concerns. What happened is `mason` will directly call `python` in `$PATH` (which is `python2`, **not** `python3`). No matter how you modified ur venv, this will eventually point to the outdated framework with no pip support:
```console
/System/Library/Frameworks/Python.framework/Versions/Current/Resources/Python.app/Contents/MacOS/Python
```

You can choose to:
1. Upgrade macOS;
2. Install the built-in CLI tools via `xcode-select --install`, this will make `/usr/bin/python` point to:
```console
/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/Current/Resources/Python.app/Contents/MacOS/Python
```
3. Use Homebrew Python.

> (and by the way, i want to ask which version of python should be used under normal circumstances?

Any versions of python 3.x would be ok if you don't use python in ur daily development. I have:
```sh
$ python --version
Python 3.11.2
```

**Comment by Jint-lzxy** [comment]
> i guess that mason use python2 when it install setuptools but pip is in py3.8

@longintlong Yep that would be expected. Do you have the latest version of macOS (> Monterey 12.3) installed? This version finally dropped `python2` support. See [macOS Monterey 12.3 Release Notes#Deprecations](https://developer.apple.com/documentation/macos-release-notes/macos-12_3-release-notes#Deprecations). For macOS versions <12.3 they have a series of env issues for compatibility concerns. What happened is `mason` will directly call `python` in `$PATH` (which is `python2`, **not** `python3`). No matter how you modified ur venv, this will eventually point to the outdated framework with no pip support:
```console
/System/Library/Frameworks/Python.framework/Versions/Current/Resources/Python.app/Contents/MacOS/Python
```

You can choose to:
1. Upgrade macOS;
2. Install the built-in CLI tools via `xcode-select --install`, this will make `/usr/bin/python` point to:
```console
/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/Current/Resources/Python.app/Contents/MacOS/Python
```
3. Use Homebrew Python.

> (and by the way, i want to ask which version of python should be used under normal circumstances?

Any versions of python 3.x would be ok if you don't use python in ur daily development. I have:
```sh
$ python --version
Python 3.11.2
```

**Comment by aarnphm** [comment]
I found that using pyenv helps. Also having the alias for `python=python3` and `pip=pip3` always help.

**Comment by longintlong** [comment]
> > i guess that mason use python2 when it install setuptools but pip is in py3.8
> 
> @longintlong Yep that would be expected. Do you have the latest version of macOS (> Monterey 12.3) installed? This version finally dropped `python2` support. See [macOS Monterey 12.3 Release Notes#Deprecations](https://developer.apple.com/documentation/macos-release-notes/macos-12_3-release-notes#Deprecations). For macOS versions <12.3 they have a series of env issues for compatibility concerns. What happened is `mason` will directly call `python` in `$PATH` (which is `python2`, **not** `python3`). No matter how you modified ur venv, this will eventually point to the outdated framework with no pip support:
> 
> ```
> /System/Library/Frameworks/Python.framework/Versions/Current/Resources/Python.app/Contents/MacOS/Python
> ```
> 
> You can choose to:
> 
> 1. Upgrade macOS;
> 2. Install the built-in CLI tools via `xcode-select --install`, this will make `/usr/bin/python` point to:
> 
> ```
> /Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/Current/Resources/Python.app/Contents/MacOS/Python
> ```
> 
> 3. Use Homebrew Python.
> 
> > (and by the way, i want to ask which version of python should be used under normal circumstances?
> 
> Any versions of python 3.x would be ok if you don't use python in ur daily development. I have:
> 
> ```shell
> $ python --version
> Python 3.11.2
> ```

I did it! I upgrade my MacOS version  and use `xcode-select --install` can work.
Thank u again!
