### ISSUE TITLE
现在git pull总是出错

### ISSUE THREAD

**Issue by JerryAllison** [ayamir/nvimdots#544]
### Feature description

<img width="793" alt="image" src="https://user-images.githubusercontent.com/5206758/221750779-cfd44fca-5060-4b4f-b90e-88a2b2683b89.png">
最近的版本在git pull总是出问题，就算修复后，下一次git pull还是照样出问题。
看能否修复一下，虽然不算什么问题，但是总这样很烦人。

**Comment by ayamir** [comment]
execute `git restore ./lazy-lock.json` before `git pull`.
