### ISSUE TITLE
点击 gd 弹出函数定义预览子窗口，再点击 Esc 报错

### ISSUE THREAD

**Issue by fengxuway** [ayamir/nvimdots#546]
### Version confirmation

- [X] Confirm

### Following prerequisites

- [X] Confirm

### Neovim version

NVIM v0.8.1

### Operating system/version

macOS 13.2.1

### Terminal name/version

iTerm2 版本 3.4.19

### Branch info

main (Default/Latest)

### Fetch Preferences

HTTPS (use_ssh = false)

### How to reproduce the issue

在 golang 函数调用处，normal 模式点`gd` 弹出子页面，再点 <kbd>Esc</kbd> 报错：
![image](https://user-images.githubusercontent.com/17471078/222649902-82eb3ea7-c6a7-46ff-9dce-0521ed4aff7c.png)
![image](https://user-images.githubusercontent.com/17471078/222649923-577ab235-210d-4837-bf7b-dd839a7af1d7.png)

### Expected behavior

点击 <kbd>Esc</kbd>不报错，同时关闭子窗口

**Comment by fengxuway** [comment]
报错信息文本：
```
E5108: Error executing lua: ...e/nvim/site/lazy/lspsaga.nvim/lua/lspsaga/definition.lua:103: Vim(close):E488: Trailing characters: *****/go/pkg/mod/gorm.io/gorm@v1.24.5/g
orm.go: close *****/go/pkg/mod/gorm.io/gorm@v1.24.5/gorm.go
stack traceback:
        [C]: in function 'cmd'
        ...e/nvim/site/lazy/lspsaga.nvim/lua/lspsaga/definition.lua:103: in function <...e/nvim/site/lazy/lspsaga.nvim/lua/lspsaga/definition.lua:91>
```

**Comment by Jint-lzxy** [comment]
We didn't set any `<Esc>` related keymaps for this window, and it is probably used for other purposes. To close the window, please use `q`.

https://github.com/ayamir/nvimdots/blob/b4ed80f43b56a3f92b7d436098caddfa2df2280c/lua/modules/configs/completion/lspsaga.lua#L54

UPDATE: https://github.com/ayamir/nvimdots/commit/986400c8b55b786c9be09cca634ca4c59465518d should remove those outdated options.

**Comment by fengxuway** [comment]
👍🏻 works for me
