### ISSUE TITLE
pyright could not attach to the buffer

### ISSUE THREAD

**Issue by csyJoy** [ayamir/nvimdots#547]
### Version confirmation

- [X] Confirm

### Following prerequisites

- [X] Confirm

### Neovim version

NVIM 0.8.2

### Operating system/version

ubuntu 20.04

### Terminal name/version

GNOME Terminal  3.36.2

### Branch info

main (Default/Latest)

### Fetch Preferences

SSH (use_ssh = true)

### Affected language servers

pyright

### How to reproduce the issue

just open a python file and see lsp info.

### Actual behavior

pyright does not attach to the buffer

### Expected behavior

pyright does attach to the buffer

### Support info

:LspInfo
![image](https://user-images.githubusercontent.com/58020450/222668970-653b5bb6-28cc-4236-9645-9db2544c393a.png)
:Mason
![image](https://user-images.githubusercontent.com/58020450/222669055-44a3218d-9d97-480c-802c-772fbf022b02.png)

**Comment by CharlesChiuGit** [comment]
But... your `LspInfo` screenshot shows it's attached?

**Comment by csyJoy** [comment]
`LspInfo` shows that 0 client attached to this buffer, I mean. Anyway, I can't use pyright lsp in this buffer, I know little about how LSP works, maybe there is something misunderstanding with my explanation.

**Comment by CharlesChiuGit** [comment]
Aha yes, it's indeed sth wrong. 
![圖片](https://user-images.githubusercontent.com/32497323/222673042-a912687b-ab56-4c51-8b60-8ad5e2571e16.png)

**Comment by CharlesChiuGit** [comment]
Do u have modification about lsp-related stuff?

**Comment by csyJoy** [comment]
> Do u have any modification about lsp-related stuff?

no

**Comment by CharlesChiuGit** [comment]
Can u delete `~/.local/state/nvim/lsp.log`, open a python file and send the `lsp.log` to here?

**Comment by csyJoy** [comment]
This is the log info in .local/state/nvim/lsp.log 

>[START][2023-03-03 16:28:26] LSP logging initiated
>[WARN][2023-03-03 16:28:26] .../lua/vim/lsp.lua:1602	"buf_attach_client called on unloaded buffer (id: 1): "

**Comment by CharlesChiuGit** [comment]
Mine looks like this:

```log
[START][2023-03-03 16:51:52] LSP logging initiated
[WARN][2023-03-03 16:51:52] ...lsp/handlers.lua:128	"The language server pyright triggers a registerCapability handler despite dynamicRegistration set to false. Report upstream, this warning is harmless"
[WARN][2023-03-03 16:51:52] ...lsp/handlers.lua:515	"stubPath typings is not a valid directory."
```

Are u using the 100% identical nvim config from this repo, or if u have any modification?

**Comment by csyJoy** [comment]
I add some plugins and change some key bindings, but I am sure I don't change lsp-releated stuff. I test `pyright` in OSX with the same config files and It works fine, so It confuses me.

**Comment by CharlesChiuGit** [comment]
Can u try remove `~/.local/share/nvim/mason`, reinstall every lsp and see if there's any change?

**Comment by csyJoy** [comment]
I have done that, but `pyright` still does work.

**Comment by csyJoy** [comment]
I removed my config files and installed the origin config files, but it still didn't work

**Comment by Jint-lzxy** [comment]
@csyJoy Can you add the following content after [this line](https://github.com/ayamir/nvimdots/blob/986400c8b55b786c9be09cca634ca4c59465518d/lua/modules/configs/completion/lsp.lua#L110) and see if that helps?
```lua
pyright = function()
	local _opts = {
		root_dir = function(fname)
			return require("lspconfig.util").root_pattern(
				"WORKSPACE",
				".git",
				"Pipfile",
				"pyrightconfig.json",
				"setup.py",
				"setup.cfg",
				"pyproject.toml",
				"requirements.txt"
			)(fname) or require("lspconfig.util").path.dirname(fname)
		end,
	}
	local final_opts = vim.tbl_deep_extend("keep", _opts, opts)
	nvim_lsp.pyright.setup(final_opts)
end,
```

**Comment by csyJoy** [comment]
> @csyJoy Can you add the following content after [this line](https://github.com/ayamir/nvimdots/blob/986400c8b55b786c9be09cca634ca4c59465518d/lua/modules/configs/completion/lsp.lua#L110) and see if that helps?
> 
> ```lua
> pyright = function()
> 	local _opts = {
> 		root_dir = function(fname)
> 			return require("lspconfig.util").root_pattern(
> 				"WORKSPACE",
> 				".git",
> 				"Pipfile",
> 				"pyrightconfig.json",
> 				"setup.py",
> 				"setup.cfg",
> 				"pyproject.toml",
> 				"requirements.txt"
> 			)(fname) or require("lspconfig.util").path.dirname(fname)
> 		end,
> 	}
> 	local final_opts = vim.tbl_deep_extend("keep", _opts, opts)
> 	nvim_lsp.pyright.setup(final_opts)
> end,
> ```

OK, I will test it as soon as I go to the office.

**Comment by csyJoy** [comment]
> @csyJoy Can you add the following content after [this line](https://github.com/ayamir/nvimdots/blob/986400c8b55b786c9be09cca634ca4c59465518d/lua/modules/configs/completion/lsp.lua#L110) and see if that helps?
> 
> ```lua
> pyright = function()
> 	local _opts = {
> 		root_dir = function(fname)
> 			return require("lspconfig.util").root_pattern(
> 				"WORKSPACE",
> 				".git",
> 				"Pipfile",
> 				"pyrightconfig.json",
> 				"setup.py",
> 				"setup.cfg",
> 				"pyproject.toml",
> 				"requirements.txt"
> 			)(fname) or require("lspconfig.util").path.dirname(fname)
> 		end,
> 	}
> 	local final_opts = vim.tbl_deep_extend("keep", _opts, opts)
> 	nvim_lsp.pyright.setup(final_opts)
> end,
> ```

well, I test it but `pyright` still doesn't work, maybe I should switch to another python lsp.

**Comment by aarnphm** [comment]
did you have `pyproject.toml` setup in your local repository?

**Comment by csyJoy** [comment]
> did you have `pyproject.toml` setup in your local repository?

do you mean I need a `pyproject.toml` in my project? actually I have this file in my project root directory.

**Comment by aarnphm** [comment]
can you dump your pyright configuration in your pyproject.toml here?

**Comment by CharlesChiuGit** [comment]
r u using any python venv like conda or pyenv? (randomly guessing here

**Comment by aarnphm** [comment]
it works fine for me even if it is inside venv or not.

**Comment by CharlesChiuGit** [comment]
Yeah, I know pyright should also work in venv. I'm just guessing maybe @csyJoy had installed another pyright in his/her python venv?

**Comment by csyJoy** [comment]
sorry to missing the discussion, now I switch my python `lsp` to `python-language-server`, it works fine for me, but I will test all of the stuffs to find the reason, It is probably true that I installed another `pyright` somwhere.

**Comment by csyJoy** [comment]
@CharlesChiuGit I checked my python venv but didn't find any other `pyright`.
@aarnphm this is my pyright configuration, it is actually the example configuration in `pyright` repository.
```toml
[tool.pyright]
include = ["src"]
exclude = ["**/node_modules",
    "**/__pycache__",
    "src/experimental",
    "src/typestubs"
]
ignore = ["src/oldstuff"]
defineConstant = { DEBUG = true }
stubPath = "src/stubs"
venv = "env367"

reportMissingImports = true
reportMissingTypeStubs = false

pythonVersion = "3.8"
pythonPlatform = "Linux"

executionEnvironments = [
  { root = "src/web", pythonVersion = "3.5", pythonPlatform = "Windows", extraPaths = [ "src/service_libs" ] },
  { root = "src/sdk", pythonVersion = "3.0", extraPaths = [ "src/backend" ] },
  { root = "src/tests", extraPaths = ["src/tests/e2e", "src/sdk" ]},
  { root = "src" }
]
```
Is there any wrong with this configuration?

**Comment by csyJoy** [comment]
since now the default lsp for python is pylsp and it works fine to me, I think I should close this issue
