### ISSUE TITLE
Alt key for mac

### ISSUE THREAD

**Issue by dadanliu** [ayamir/nvimdots#549]
### Feature description

\<A-d\> 中的 A。对的mac里的按键是什么，options么？按了半天没找到...

**Comment by ClSlaid** [comment]
非 Macbook 用户，美式键盘应当是 `Options` 键。建议上网搜索。

**Comment by ayamir** [comment]
What's your terminal?

**Comment by dadanliu** [comment]
> 

iterm2 and option just not work;

**Comment by Jint-lzxy** [comment]
Duplicate of #344. Please search existing issues before opening a new one.
