### ISSUE TITLE
为何装饰字符矮一点，难受

### ISSUE THREAD

**Issue by xuiv** [ayamir/nvimdots#552]
![截图 2023-03-06 09-15-15](https://user-images.githubusercontent.com/2186759/223000191-1ea927c6-0dbc-44d6-bb96-4dc861b75be5.png)

**Comment by CharlesChiuGit** [comment]
Try another terminal emulator.

**Comment by xuiv** [comment]
> Try another terminal emulator.

不能设置catppunttin样式把这玩去掉吗？

**Comment by xuiv** [comment]
nvim-qt是正常的：
![截图 2023-03-06 09-21-37](https://user-images.githubusercontent.com/2186759/222999005-5c6f595a-3dfc-4493-aa70-5a43719877c0.png)

**Comment by CharlesChiuGit** [comment]
> 不能设置catppunttin样式把这玩去掉吗？

It's your terminal font setting, not the theme.

My gnome terminal looks perfectly fine:
![圖片](https://user-images.githubusercontent.com/32497323/222999142-7107fd93-94df-4734-8186-594694e874ce.png)

**Comment by xuiv** [comment]
我调过，弄不好。4k屏幕，1080P 200％放大。

**Comment by ayamir** [comment]
Another method, remove this line:
https://github.com/ayamir/nvimdots/blob/54e85577ab5252bf742c8497989cea409fe41b53/lua/modules/configs/ui/lualine.lua#L110
