### ISSUE TITLE
client quit with exit code 1 and signal 0 

### ISSUE THREAD

**Issue by CSWLeTianPai** [ayamir/nvimdots#559]
### Version confirmation

- [X] Confirm

### Following prerequisites

- [X] Confirm

### Neovim version

NVIM v0.8.2

### Operating system/version

Linux

### Terminal name/version

alacritty

### $TERM environment variable

xterm-256-color

### Branch info

main (Default/Latest)

### Fetch Preferences

SSH (use_ssh = true)

### How to reproduce the issue

不停的弹出 奇怪了

### Expected behavior

求求大大解释下

**Comment by CSWLeTianPai** [comment]
ERR 2023-03-10T23:11:23.340 nvim.47108.0 decor_provider_invoke:38: error in provider treesitter/highlighter:line: Error executing lua: /usr/share/nvim/runtime/lua/vim/treesitter/query.lua:219: query: invalid node type at position 2765 for language vim
stack traceback:
	[C]: in function '_ts_parse_query'
	/usr/share/nvim/runtime/lua/vim/treesitter/query.lua:219: in function 'get_query'
	/usr/share/nvim/runtime/lua/vim/treesitter/highlighter.lua:36: in function 'new'
	/usr/share/nvim/runtime/lua/vim/treesitter/highlighter.lua:169: in function 'get_query'
	/usr/share/nvim/runtime/lua/vim/treesitter/highlighter.lua:191: in function 'fn'
	/usr/share/nvim/runtime/lua/vim/treesitter/languagetree.lua:210: in function 'for_each_tree'
	/usr/share/nvim/runtime/lua/vim/treesitter/languagetree.lua:214: in function 'for_each_tree'
	/usr/share/nvim/runtime/lua/vim/treesitter/highlighter.lua:177: in function 'on_line_impl'
	/usr/share/nvim/runtime/lua/vim/treesitter/highlighter.lua:249: in function </usr/share/nvim/runtime/lua/vim/treesitter/highlighter.lua:243>
日志显示是这样 我是小白。。

**Comment by CSWLeTianPai** [comment]
[START][2023-03-10 22:59:59] LSP logging initiated
[ERROR][2023-03-10 22:59:59] .../vim/lsp/rpc.lua:733	"rpc"	"node"	"stderr"	"/home/csw/.local/share/nvim/site/lazy/copilot.lua/copilot/dist/agent.js:8\n

**Comment by Jint-lzxy** [comment]
They are two different issues. For **query: invalid node type at position x for language x** please refer to #393.

> [ERROR][2023-03-10 22:59:59] .../vim/lsp/rpc.lua:733 "rpc" "node" "stderr"

Looks like you haven't registered `copilot` correctly. If u are not using `copilot`, you may disable it by commenting out the following lines:
https://github.com/ayamir/nvimdots/blob/70d2a5e68899955e79001d4ad86cf5057b19b608/lua/modules/plugins/completion.lua#L58-L69
https://github.com/ayamir/nvimdots/blob/c56cd604dc3b9f7149b89f245206daf0b00b369c/lua/modules/configs/completion/cmp.lua#L132
https://github.com/ayamir/nvimdots/blob/c56cd604dc3b9f7149b89f245206daf0b00b369c/lua/modules/configs/completion/cmp.lua#L61-L62

**Comment by ayamir** [comment]
Closed due to lacking response, feel free to reopen it if problem still exists.

**Comment by listentodella** [comment]
![image](https://github.com/ayamir/nvimdots/assets/27765011/fbf33c4f-c7a5-400f-8bd7-8a99aa2f89d6)

I met this issue too. I am a new nvimer, the number of "client X" will always increase. The only way for me to solve this issuse is to disable the nvim.notify. But I don't think it right way.

**Comment by ayamir** [comment]
check `LspInfo` and put screenshot here. 

Also, provided your `~/.local/state/nvim/lsp.log` here. Of course, if it is to long to show, remove it first and reopen `nvim` to see this phenomenon then paste the content of `~/.local/state/nvim/lsp.log`.

**Comment by listentodella** [comment]
![image](https://github.com/ayamir/nvimdots/assets/27765011/443ba9a8-cfeb-4c82-bc5e-54174e2c7f23)


I use it in WSL2.

[lsp.log](https://github.com/ayamir/nvimdots/files/11597902/lsp.log)

**Comment by listentodella** [comment]
![image](https://github.com/ayamir/nvimdots/assets/27765011/d9f11bd3-4f3c-4f44-aabc-4c78754205b2)
I followed the log and run `sudo apt install python3.10-venv`, then reopen nvim, the mason can install packages correctly.

Then the error never appears.

**Comment by lzyuz** [comment]
try update nodejs > 16, I update to V19.9.0,  then everything is fine
