### ISSUE TITLE
执行 PackerSync 卡住

### ISSUE THREAD

**Issue by watsy0007** [ayamir/nvimdots#56]
![image](https://user-images.githubusercontent.com/822237/145514365-760ea217-1200-4ff9-b23d-6e86bbf4af90.png)

如图所示，会一致卡在这里。如何调试？

**Comment by ayamir** [comment]
是不是这个问题？https://github.com/ayamir/nvimdots/issues/52

**Comment by watsy0007** [comment]
是的。感谢已经解决。
