### ISSUE TITLE
我可以在bilibili 上做这个库的视频么

### ISSUE THREAD

**Issue by mjkx5** [ayamir/nvimdots#560]
### Feature description

我用了这个库一段时间了， 我觉得这个库很好用，我最近有一点时间，并且突然有一点点分享欲，想把这个库分享出去。我可以把这个库做成视频么？

视频内容大致是 ：
说一下， 每个东西在哪里，比如插件， 配置 等等，因为每个人有一些自己的配置需要改（可能），也可能顺便讲一下某几个重要的插件。我没有做过视频，只是暂时想做一个。
如果同意的话，我就开始做。

**Comment by ayamir** [comment]
可以，期待你的视频

**Comment by CharlesChiuGit** [comment]
Personally I hope u can upload an youtube video too, but that's up to u.
Thanks fore your effort!

**Comment by fioncat** [comment]
做完记得发在这里我去点赞😄

**Comment by mjkx5** [comment]
别把，我就不发了，我纯菜鸡，应该质量也不怎么好，也没人看。就是看多了其他人的分享之后，想自己整一点。我还是不发到这里了，那样压力太大了
