### ISSUE TITLE
gd to numpy break the gd function.

### ISSUE THREAD

**Issue by JoeMob** [ayamir/nvimdots#561]
### Version confirmation

- [X] Confirm

### Following prerequisites

- [X] Confirm

### Neovim version

NVIM v0.8.2

### Operating system/version

win 11

### Terminal name/version

weztrem 20221119-145034-49b9839f

### Branch info

main (Default/Latest)

### Fetch Preferences

SSH (use_ssh = true)

### Affected language servers

Pyright

### How to reproduce the issue

1.Import numpy and any other modules.
2.gd to numpy.

### Actual behavior

After gd to numpy, I can't gd to anything.
![image](https://user-images.githubusercontent.com/49267059/224471563-91ec8ffb-80f6-4a3d-8a69-462e18e742bb.png)
If I gd to numpy again it will show an analyze progress.
![image](https://user-images.githubusercontent.com/49267059/224472072-31933999-a863-489d-801b-3adda8e0fdad.png)

### Support info

![image](https://user-images.githubusercontent.com/49267059/224475161-e739ab5f-39fd-47b4-adb6-bf13b21a2bef.png)
![image](https://user-images.githubusercontent.com/49267059/224471874-a976e00d-5600-4f0e-9f23-d8b9a5cdfe0d.png)

### Logs

```console
[START][2023-03-11 15:37:04] LSP logging initiated
[WARN][2023-03-11 15:37:04] ...lsp/handlers.lua:487	"stubPath typings is not a valid directory."
[WARN][2023-03-11 15:42:01] ...lsp/handlers.lua:487	"stubPath c:\\Users\\joemob\\AppData\\Local\\Programs\\Python\\Python310\\Lib\\site-packages\\numpy\\typings is not a valid directory."
[WARN][2023-03-11 15:49:43] ...lsp/handlers.lua:113	"The language server copilot triggers a registerCapability handler despite dynamicRegistration set to false. Report upstream, this warning is harmless"
```

**Comment by ayamir** [comment]
can't repo.

**Comment by Jint-lzxy** [comment]
Communication with the language server probably timed out and the server has been forced to shutdown. Please refer to https://github.com/ayamir/nvimdots/issues/562#issuecomment-1465083112 to adjust the specifications of `pyright`.
