### ISSUE TITLE
how to install the `fzf.vim` for using the `GoDecls`

### ISSUE THREAD

**Issue by SimFG** [ayamir/nvimdots#563]
### Version confirmation

- [X] Confirm

### Following prerequisites

- [X] Confirm

### Neovim version

NVIM v0.8.1

### Operating system/version

macOS 13.0.1

### Terminal name/version

iterm2 Build 3.4.15

### Branch info

main (Default/Latest)

### Fetch Preferences

HTTPS (use_ssh = false)

### How to reproduce the issue

![image](https://user-images.githubusercontent.com/21985684/224481667-099b21a7-c2d8-422f-924c-2a72c1f92fcf.png)
![image](https://user-images.githubusercontent.com/21985684/224481674-f86c0de6-cfab-4d08-b02d-23f4325f3ad5.png)
Recently I started learning nvim, so I am not very familiar with some configurations.

### Expected behavior

can use the `GoDecls`

**Comment by ayamir** [comment]
in `lua/modules/plugins/lang.lua`
```lua
lang["fatih/vim-go"] = {
	lazy = true,
	ft = "go",
	build = ":GoInstallBinaries",
	config = require("lang.vim-go"),
	dependencies = { { "junegunn/fzf", lazy = true, build = ":call fzf#install()" } },
}
```
![Screenshot_20230311_224436](https://user-images.githubusercontent.com/61657399/224490959-0505fc7d-5477-4055-b1b6-54813e3a2871.png)

**Comment by SimFG** [comment]
Thanks!!!
