### ISSUE TITLE
 /home/work/.config/nvim/init.lua:2: module 'catppuccin' not found:

### ISSUE THREAD

**Issue by IoveRailgun** [ayamir/nvimdots#565]
### Feature description

 /home/work/.config/nvim/init.lua:2: module 'catppuccin' not found:
不知道怎么解决。。。

**Comment by CharlesChiuGit** [comment]
This is due to incomplete installation.
Remove the plugin folder and re-open nvim to let `lazy,nvim` re-intall every plugin again.
