### ISSUE TITLE
attempt to index field 'cmd' (a function value)

### ISSUE THREAD

**Issue by IoveRailgun** [ayamir/nvimdots#566]
### Feature description

Error detected while processing /home/work/.config/nvim/init.lua:
E355: Unknown option: mousescroll
E5113: Error while calling lua chunk: .../share/nvim/site/lazy/lazy.nvim/lua/lazy/core/loader.lua:68: attempt to index field 'cmd' (a function value)
stack traceback:
        .../share/nvim/site/lazy/lazy.nvim/lua/lazy/core/loader.lua:68: in function 'install_missing'
        .../share/nvim/site/lazy/lazy.nvim/lua/lazy/core/loader.lua:42: in function 'setup'
        .../.local/share/nvim/site/lazy/lazy.nvim/lua/lazy/init.lua:68: in function 'setup'
        /home/work/.config/nvim/lua/core/pack.lua:128: in function 'load_lazy'
        /home/work/.config/nvim/lua/core/pack.lua:131: in main chunk
        [C]: in function 'require'
        /home/work/.config/nvim/lua/core/init.lua:127: in function 'load_core'
        /home/work/.config/nvim/lua/core/init.lua:135: in main chunk
        [C]: in function 'require'
        /home/work/.config/nvim/init.lua:2: in main chunk

**Comment by IoveRailgun** [comment]
nvim -v                                                                                                           work@meg-megqa-hejinlong 13:33:51
NVIM v0.8.0-dev
Build type: Debug

**Comment by CharlesChiuGit** [comment]
Seems like your neovim version is too old. Install a newer version.
Also u **should** use our issue template to provide us more info to help.
