### ISSUE TITLE
nvim-treesitter[vue]: Error during compilation

### ISSUE THREAD

**Issue by IoveRailgun** [ayamir/nvimdots#567]
### Feature description

nvim-treesitter[vue]: Error during compilation
src/parser.c:4: warning: expected [error|warning|ignored] after ‘#pragma GCC diagnostic’
In file included from src/scanner.cc:3:
src/./tree_sitter_html/scanner.cc: In member function ‘unsigned int<unnamed>::Scanner::serialize(char*)’:
src/./tree_sitter_html/scanner.cc:30: error: ‘UINT16_MAX’ was not declared in this scope
src/./tree_sitter_html/scanner.cc:41: error: ‘UINT8_MAX’ was not declared in this scope

**Comment by IoveRailgun** [comment]
## The following errors have been detected:
      - ERROR: vim(highlights): ...oud/nvim/share/nvim/runtime/lua/vim/treesitter/query.lua:219: query: invalid node type at position 2765 for language vim
     vim(highlights) is concatenated from the following files:
    | [ERROR]:"/home/work/.local/share/nvim/site/lazy/nvim-treesitter/queries/vim/highlights.scm", failed to load: ...oud/nvim/share/nvim/runtime/lua/vim/treesitter/query.lua:219: query: invalid node type at position 2765 for language vim

**Comment by ayamir** [comment]
This issue doesn't belong to enhancement. Use bug report plz.
