### ISSUE TITLE
nvim-treesitter intergration requires neovim 0.8

### ISSUE THREAD

**Issue by mirroez** [ayamir/nvimdots#568]
### Feature description

你好，nvimdots 的配置非常好用。但是我由于远端服务器原因只能使用neovim 0.72 ，clone 0.7库并更新后 报出提示nvim-treesitter intergration requires neovim 0.8，我该在哪个文件中指定nvim-treesitter 支持0.72的旧版本？ 下面是一些打开lua文件时报出的错误，我该如何修复他们？

### Additional information

Error executing vim.schedule lua callback: ...pack/packer/start/mason.nvim/lua/mason-registry/init.lua:78: Cannot find package "stylua".
stack traceback:
        [C]: in function 'error'
        ...pack/packer/start/mason.nvim/lua/mason-registry/init.lua:78: in function 'get_package'
        ...on-tool-installer.nvim/lua/mason-tool-installer/init.lua:111: in function ''
        vim/_editor.lua: in function ''
        vim/_editor.lua: in function <vim/_editor.lua:0>

Error detected while processing InsertEnter Autocommands for "*":
E5108: Error executing lua ...vim/site/pack/packer/opt/packer.nvim/lua/packer/load.lua:179: Vim(echomsg):E114: Missing quote: "Error in packer_compiled: ...vim/site/pa
ck/packer/opt/packer.nvim/lua/packer/load.lua:168: Vim(lua):E5108: Error executing lua ...te/pack/packer/start/filetype.nvim/lua/filetype/init.lua:8: Vim(append):Error
 executing lua callback: ...er/opt/nvim-treesitter/lua/nvim-treesitter/highlight.lua:28: attempt to call field 'stop' (a nil value)
stack traceback:
        [C]: in function 'cmd'
        ...vim/site/pack/packer/opt/packer.nvim/lua/packer/load.lua:179: in function <...vim/site/pack/packer/opt/packer.nvim/lua/packer/load.lua:175>
        [string ":lua"]:1: in main chunk
Press ENTER or type command to continue
Error detected while processing function 4[71]..matchup#delim#get_current[1]..<SNR>58_get_delim_multi[3]..matchup#ts_engine#get_delim[3]..<SNR>50_forward:
line    1:
E5108: Error executing lua ...vim-matchup/lua/treesitter-matchup/third-party/utils.lua:116: attempt to call field 'get_node_range' (a nil value)
stack traceback:
        ...vim-matchup/lua/treesitter-matchup/third-party/utils.lua:116: in function 'is_in_node_range'
        ...cker/opt/vim-matchup/lua/treesitter-matchup/internal.lua:222: in function 'get_delim'

**Comment by ayamir** [comment]
You can cd to the directory of `nvim-treesitter` then checkout to `0.7.2` tag.
https://github.com/nvim-treesitter/nvim-treesitter/tree/v0.7.2

**Comment by mirroez** [comment]
> You can cd to the directory of `nvim-treesitter` then checkout to `0.7.2` tag. https://github.com/nvim-treesitter/nvim-treesitter/tree/v0.7.2
> 
> ```shell
> cd ~/.local/share/nvim/site/packer/opt/nvim-treesitter/
> git fetch --all --tags
> git checkout tags/0.7.2
> ```

十分感谢，这个问题解决了，但是还有个mason相关的问题：
当安装完插件重新进入nvim时会报错
 ![image](https://user-images.githubusercontent.com/96274269/225050861-f98be2ab-eeb1-453a-b74d-82fd8c75ea86.png)  
Error executing vim.schedule lua callback: ...pack/packer/start/mason.nvim/lua/mason-registry/init.lua:78: Cannot find package "stylua".
stack traceback: [C]: in function 'error' ...pack/packer/start/mason.nvim/lua/mason-registry/init.lua:78: in function 'get_package' ...on-tool-installer.nvim/lua/mason-tool-installer/init.lua:111: in function '' vim/_editor.lua: in function ''


我不能确定是什么原因引起的这个问题

**Comment by aarnphm** [comment]
can also set the version from lazy for this nvim-treesitter
```lua
plugins["nvim-treesitter/nvim-treesitter"] = {
  version = "0.7.2"
}
```

**Comment by ayamir** [comment]
You can comment this line to cancel the installation of `stylua` if you don't write `lua` file.
https://github.com/ayamir/nvimdots/blob/212217eb7b59f153f83ec1f0c56b94be8d01cbc8/lua/modules/completion/config.lua#L258
Or execute `MasonInstall stylua` then show us the log.

**Comment by CharlesChiuGit** [comment]
> Error executing vim.schedule lua callback: ...pack/packer/start/mason.nvim/lua/mason-registry/init.lua:78: Cannot find package "stylua".

It's not possible to install `stylua` now, since the github repo is now renamed to `lua_ls`. U can comment this line as ayamir stated or change it to `lua_ls`.

**Comment by CharlesChiuGit** [comment]
@Jint-lzxy @ayamir I think we better drop support for 0.7. We didn't have a lock file at that time, which will it almost impossible to maintaining it.

@mirroez sorry for that, but I think u need to fix those error yourself.

**Comment by aarnphm** [comment]
> I think we better drop support for 0.7. We didn't have a lock file at that time, which will it almost impossible to maintaining it. I'm overwhelmed by errors when I checkout to branch 0.7.

Do you know what the timeline for support on different neovim version from the neovim team? If they don't have specific EOL support then we should just drop it.

**Comment by CharlesChiuGit** [comment]
> > I think we better drop support for 0.7. We didn't have a lock file at that time, which will it almost impossible to maintaining it. I'm overwhelmed by errors when I checkout to branch 0.7.
> 
> Do you know what the timeline for support on different neovim version from the neovim team? If they don't have specific EOL support then we should just drop it.
> 
> imho neovim 0.8 should have been neovim 1.0, since the treesitter integration is relatively big.

Maybe the time of each tags could be taken as a reference?
![圖片](https://user-images.githubusercontent.com/32497323/232349783-bf804892-a6a6-4986-9677-bdd5a19c9ed2.png)

**Comment by ayamir** [comment]
> @Jint-lzxy @ayamir I think we better drop support for 0.7. We didn't have a lock file at that time, which will make it almost impossible to maintaining it. I'm overwhelmed by errors when I checkout to branch 0.7.
> 
> @mirroez sorry for that, but I think u need to fix those error yourself.

Agree.

**Comment by Jint-lzxy** [comment]
Agree. I will open a PR to deprecate the 0.7 branch later. Specifically:
- When the install script detects the version of `nvim` is less than or equal to `0.7`, it will call `_abort` and prompt the user to update their `nvim` build;
- The issue templates will mark `nvim <= 0.7` as deprecated, and users who choose this branch will be denied from submitting their issues (or closed directly).

**Comment by Jint-lzxy** [comment]
Agree. I will open a PR to deprecate the 0.7 branch later. Specifically:
- When the install script detects the version of `nvim` is less than or equal to `0.7`, it will call `_abort` and prompt the user to update their `nvim` build;
- The issue templates will mark `nvim <= 0.7` as deprecated, and users who choose this branch will be rejected from submitting their issues (or closed directly).

**Comment by Jint-lzxy** [comment]
Closing as #686 is merged. This is a wontfix.
