### ISSUE TITLE
I can't use <A-d> to open floating terminal

### ISSUE THREAD

**Issue by Penguin-SAMA** [ayamir/nvimdots#572]
### Version confirmation

- [X] Confirm

### Following prerequisites

- [X] Confirm

### Neovim version

NVIM v0.8.3 Build type: Release LuaJIT 2.1.0-beta3 编译者 brew@Ventura-arm64.local  Features: +acl +iconv +tui See ":help feature-compile"       系统 vimrc 文件: "$VIM/sysinit.vim"          $VIM 预设值: "/opt/homebrew/Cellar/neovim/0.8.3/share/nvim"  Run :checkhealth for more info

### Operating system/version

macos 13.3

### Terminal name/version

iTerm2 3.4.19

### Branch info

main (Default/Latest)

### Fetch Preferences

SSH (use_ssh = true)

### How to reproduce the issue

1. nvim MyProject.cpp
2. option + d
3. control  + d
4.command + d

### Expected behavior

open floating terminal
打开浮动终端窗口

### Actual behavior

noting happened
无论使用哪个组合按键都无法打开浮动终端

**Comment by CharlesChiuGit** [comment]
Try another terminal emulator. I think u need to change some iterm settings.

**Comment by Penguin-SAMA** [comment]
> 



> Try another terminal emulator. I think u need to change some iterm settings.

but i can use <A-\>or<C-\> to open the other terminal, only floating terminal can't open

**Comment by ayamir** [comment]
Maybe `<A-d>` has been used to bind to terminal or other program's keymap.
Try changing it to another keymap like `<A-f>`:
https://github.com/ayamir/nvimdots/blob/main/lua/keymap/tool.lua#L62-L70

**Comment by Penguin-SAMA** [comment]
> Maybe `<A-d>` has been used to bind to terminal or other program's keymap.
> Try changing it to another keymap like `<A-f>`:
> https://github.com/ayamir/nvimdots/blob/main/lua/keymap/tool.lua#L62-L70

it's useful！thx  :)
