### ISSUE TITLE
不是问题的问题

### ISSUE THREAD

**Issue by JerryAllison** [ayamir/nvimdots#573]
### Version confirmation

- [X] Confirm

### Following prerequisites

- [X] Confirm

### Neovim version

NVIM v0.8.3

### Operating system/version

13.2.1 (22D68)

### Terminal name/version

iTerm2 Build 3.4.19

### $TERM environment variable

xterm-256color

### Branch info

main (Default/Latest)

### Fetch Preferences

SSH (use_ssh = true)

### How to reproduce the issue

<img width="1427" alt="image" src="https://user-images.githubusercontent.com/5206758/225516442-81200be8-f601-48ba-b3d2-adaf62dbbc6d.png">
在多种nerd font字体下，状态栏的分割符有点错位，对于有点完美主义的人来说，有点儿别扭。
看作者状态栏对的很整齐，方便问下用的是哪款字体？或者默认是否用其他的分割符来代替呢？

### Expected behavior

状态栏对整齐一些，不随着字体的变化而变化。

**Comment by ayamir** [comment]
Use `wezterm` or https://github.com/ayamir/nvimdots/issues/552#issuecomment-1455314539

**Comment by ayamir** [comment]
Here is my config: https://github.com/ayamir/dotfiles/blob/master/catppuccin/.config/wezterm/wezterm.lua

**Comment by JerryAllison** [comment]
> Here is my config: https://github.com/ayamir/dotfiles/blob/master/catppuccin/.config/wezterm/wezterm.lua

使用了你配置，并且尝试了下fish shell，一切都在习惯中。
对了，wezterm里怎么打开tab，我用` cmd+t `毫无反应

**Comment by JerryAllison** [comment]
还有个问题，我的fish shell的prompt始终有个大i标志，这个怎么去除呢？
<img width="572" alt="image" src="https://user-images.githubusercontent.com/5206758/225816995-078a0ee0-faf6-4f6b-8a4e-3b600a74b6f8.png">

**Comment by ayamir** [comment]
> 还有个问题，我的fish shell的prompt始终有个大i标志，这个怎么去除呢？ <img alt="image" width="572" src="https://user-images.githubusercontent.com/5206758/225816995-078a0ee0-faf6-4f6b-8a4e-3b600a74b6f8.png">

`I` means `insert` mode, you can use vim keybinding in fish shell.

**Comment by ayamir** [comment]
> > Here is my config: https://github.com/ayamir/dotfiles/blob/master/catppuccin/.config/wezterm/wezterm.lua
> 
> 使用了你配置，并且尝试了下fish shell，一切都在习惯中。 对了，wezterm里怎么打开tab，我用`cmd+t`毫无反应

`<A-S-t>`

**Comment by JerryAllison** [comment]
> 
试了下，对配置文件不熟，那个字符去不掉

**Comment by ayamir** [comment]
https://stackoverflow.com/questions/41905019/how-to-disable-vi-mode-in-fish

**Comment by JerryAllison** [comment]
> https://stackoverflow.com/questions/41905019/how-to-disable-vi-mode-in-fish

thanks, its ok.
