### ISSUE TITLE
Invalid characters after opening files

### ISSUE THREAD

**Issue by ladevan** [ayamir/nvimdots#576]
### Version confirmation

- [X] Confirm

### Following prerequisites

- [X] Confirm

### Neovim version

NVIM v0.8.3

### Operating system/version

Windows Subsystem Linux - Ubuntu 22.04 LTS

### Terminal name/version

wsl terminal

### Branch info

main (Default/Latest)

### Fetch Preferences

HTTPS (use_ssh = false)

### How to reproduce the issue

正常clone repo
用nvim打开任何一个文件

### Expected behavior

没有乱码

### Actual behavior

![image](https://user-images.githubusercontent.com/815275/225719200-8fcdfb7d-0bcf-4dc2-aca2-169cfe16cb83.png)

**Comment by ayamir** [comment]
Have you used other editor open file? or use `nvim --clean`. Is this problem caused by `nvimdots`?

**Comment by ladevan** [comment]
No. I didn't use other editors to open it. Use `nvim --clean` doesn't have this issue. I also used `AstroNvim` before, no issue either.

**Comment by Jint-lzxy** [comment]
@ladevan Does "invalid characters" refer to `ggggggggggggey` on the first line?

How did you open this file _(via `telescope`/`nvim-tree` or directly via command line parameters)_? Additionally, what is your `$TERM` environment variable?

Besides that, uploading a minimal file that could reproduce this issue can help us better identify the problem :)

**Comment by ladevan** [comment]
@Jint-lzxy Yes, it's those `ggggggg` on the first line and `0000/0000/0000\` in the command line in the bottom.

I opened the file directly via command line. my `$TERM` is `xterm-256color`

I uploaded one file, but basically any file from myside will cause this issue.

[remap_win_alt.txt](https://github.com/ayamir/nvimdots/files/11006037/remap_win_alt.txt)

however, there is no issue if using AstroNvim, e.g.. I don't know what's wrong.

**Comment by ladevan** [comment]
I tried to use `Windows Terminal` app, there is no issue now.

It looks like it's related to the [wsl terminal](https://mskyaxl.github.io/wsl-terminal/) I use. Any idea what would be the root cause?
