### ISSUE TITLE
clang-format in null-ls doesn't follow .clang-format file

### ISSUE THREAD

**Issue by vollowx** [ayamir/nvimdots#581]
### Version confirmation

- [X] Confirm

### Following prerequisites

- [X] Confirm

### Neovim version

NVIM v0.9.0-dev-1193+ga7cd79349

### Operating system/version

Archlinux

### Terminal name/version

kitty 0.27.1

### $TERM environment variable

xterm-kitty

### Branch info

main (Default/Latest)

### Fetch Preferences

SSH (use_ssh = true)

### Affected language servers

clangd, null-ls

### How to reproduce the issue

`:Mason`

find clang-format

`i` to install

`q` to exit mason panel

touch a `.clang-format` file in the c++ project root dir with content

```
Language: Cpp
BasedOnStyle: Google
```

edit a c++ file

`C-s` to save and format

`A-d` to open a terminal and run `clang-format [filename]`

### Actual behavior

file content doesn't formatted with the clang-format config file, clang-format in console runs well.

### Expected behavior

file formatted with `.clang-format` file

### Support info

![image](https://user-images.githubusercontent.com/73375859/225951321-9657cfb0-1167-4a94-abed-3218b91de6c1.png)

![image](https://user-images.githubusercontent.com/73375859/225951253-ed49e1fa-6097-41b9-8cbe-e8f635e34aad.png)

**Comment by aarnphm** [comment]
I also mentioned this somewheree else, but you can do the following in null-ls

```lua
					f.clang_format.with {
						extra_args = {
							string.format(
								"--style=file:%s/.clang-format",
								require("user.utils").get_root()
							),
						},
					},
```

**Comment by huge-pancake** [comment]
thanks!

**Comment by yinghaoyu** [comment]
> Sorry about this, I think I found what the problem is
> 
> ![image](https://user-images.githubusercontent.com/73375859/225951862-9065aec3-c316-4328-969d-20eb085f1337.png)
> 
> It's defined in this file

Did you change it to `"-style=file"` ?
