### ISSUE TITLE
Vue files formatted twice if prettier(formatter) and volar(lsp) both installed

### ISSUE THREAD

**Issue by huge-pancake** [ayamir/nvimdots#582]
### Version confirmation

- [X] Confirm

### Following prerequisites

- [X] Confirm

### Neovim version

NVIM v0.9.0-dev-1193+ga7cd79349

### Operating system/version

Archlinux

### Terminal name/version

kitty 0.27.1

### $TERM environment variable

xterm-kitty

### Branch info

main (Default/Latest)

### Fetch Preferences

SSH (use_ssh = true)

### How to reproduce the issue

`:Mason` to open Mason panel

find and install `prettier` and `volar`

open a unformatted Vue file

`<C-s>` to save and format

### Expected behavior

file formatted with one formatter or lsp (choose by user?)

### Actual behavior

file changed twice (prettier formatted file => volar formatted file) quickly

### Additional information

![Recording 2023-03-18 at 09 00 08](https://user-images.githubusercontent.com/73375859/226074831-665fa96d-97c9-4280-b0b3-4de3b2398290.gif)

**Comment by Jint-lzxy** [comment]
Release v2.2.0 added this feature. Please read the [release notes](https://github.com/ayamir/nvimdots/releases/tag/v2.2.0) for more information. Specifically:
https://github.com/ayamir/nvimdots/blob/b05e62ed931011f99cf2e5e5ef4b0d4ad8a59415/lua/core/settings.lua#L41-L53

**Comment by huge-pancake** [comment]
I got it! Thanks a lot for all your works :smile:
