### ISSUE TITLE
no support  c++11, and  include my head   ERROR 

### ISSUE THREAD

**Issue by rileychc** [ayamir/nvimdots#584]
### Version confirmation

- [X] Confirm

### Following prerequisites

- [X] Confirm

### Neovim version

NVIM v0.8.3

### Operating system/version

macOS 13.2.1

### Terminal name/version

iterm2 Build 3.4.19

### $TERM environment variable

xterm-256color

### Branch info

main (Default/Latest)

### Fetch Preferences

SSH (use_ssh = true)

### Affected language servers

clangd

### How to reproduce the issue

![Uploading Pasted Graphic 2.png…]()

### Actual behavior

![Uploading Pasted Graphic 2.png…]()

### Support info

![Uploading Pasted1 Grap
<img width="1993" alt="Pasted1 Graphic3" src="https://user-images.githubusercontent.com/116857974/226231426-ad861f9f-aaa0-4309-bad8-8d4d15e55ba9.png">
hic 1.png…]()

**Comment by ayamir** [comment]
No picture uploaded, I can't see them.
You need to set the `clangd` config file on your own refer to [this](https://clangd.llvm.org/config#files).
For example, for user wide configuration:
```shell
mkdir -p ~/.config/clangd
touch ~/.config/clangd/config.yaml
nvim ~/.config/clangd/config.yaml
```
fill it with below:
```yaml
CompileFlags:
  Add: [-std=c++11]
```
For project level config, add `.clangd` file under your project root and fill it with the same content above.

**Comment by ayamir** [comment]
For include dir, it should better be managed by `cmake` and use it to generate `compile_commands.json`.
Refer to [it](https://clangd.llvm.org/installation.html#project-setup).

**Comment by rileychc** [comment]
<img width="925" alt="Pasted Graphic" src="https://user-images.githubusercontent.com/116857974/226242056-58b599f1-5995-47a4-81bb-cace7f50199f.png">
<img width="1226" alt="Pasted Graphic 1" src="https://user-images.githubusercontent.com/116857974/226242070-8273c44e-2499-4e01-b64a-b9bcfc6b0306.png">
<img width="1171" alt="Pasted Graphic 2" src="https://user-images.githubusercontent.com/116857974/226242080-5348d5e7-774b-4f1f-b8f0-eca74a50a68e.png">

**Comment by ayamir** [comment]
https://stackoverflow.com/questions/61206703/is-there-includepath-option-in-clangd

**Comment by rileychc** [comment]
> https://stackoverflow.com/questions/61206703/is-there-includepath-option-in-clangd


I solved it. Thank you very much.
