### ISSUE TITLE
Disable clang-tidy for clangd, but not effective

### ISSUE THREAD

**Issue by macrosea** [ayamir/nvimdots#585]
### Version confirmation

- [X] Confirm

### Following prerequisites

- [X] Confirm

### Neovim version

NVIM v0.8.2

### Operating system/version

macos and ubuntu

### Terminal name/version

iTerm

### Branch info

main (Default/Latest)

### Fetch Preferences

SSH (use_ssh = true)

### Affected language servers

clangd

### How to reproduce the issue

modify the file: lua/modules/configs/completion/servers/clangd.lua  as the below:

		cmd = {
			"clangd",
			"--background-index",
			"--pch-storage=memory",
			-- You MUST set this arg ↓ to your c/cpp compiler location (if not included)!
			"--query-driver=" .. get_binary_path_list({ "clang++", "clang", "gcc", "g++" }),
			"--clang-tidy=false",
			"--all-scopes-completion",
			"--completion-style=detailed",
			"--header-insertion-decorators",
			"--header-insertion=iwyu",
		},

### Actual behavior

diagnostic still not disappear;

### Support info

open a cpp file

**Comment by aarnphm** [comment]
can you send the output of `lua print(vim.inspect(vim.diagnostic.config()))`

**Comment by rileychc** [comment]
{
  ["dim/unused"] = true,
  float = true,
  severity_sort = false,
  signs = true,
  underline = true,
  update_in_insert = false,
  virtual_text = true
},,I also need to make it  disable

**Comment by aarnphm** [comment]
Might also have to disable in null-ls https://github.com/ayamir/nvimdots/blob/ed54fd687d7347168b887b8b420d42f520f8b5d6/lua/modules/configs/completion/formatters/clang_format.lua

In this case null-ls is probably getting priority here. You can see running lsp client with `LspInfo`.

**Comment by rileychc** [comment]
What should I do?

**Comment by rileychc** [comment]
<img width="1225" alt="Pasted Graphic" src="https://user-images.githubusercontent.com/116857974/226240456-6f2fcf0c-a420-4977-9514-9129f4fca7ee.png">

**Comment by CharlesChiuGit** [comment]
comment this line.
https://github.com/ayamir/nvimdots/blob/ed54fd687d7347168b887b8b420d42f520f8b5d6/lua/core/settings.lua#L76

**Comment by rileychc** [comment]
How should I specify the c++ standard of clangd in that file?

**Comment by rileychc** [comment]
> comment this line.
> 
> https://github.com/ayamir/nvimdots/blob/ed54fd687d7347168b887b8b420d42f520f8b5d6/lua/core/settings.lua#L76

After I set it up, it didn't work.

**Comment by CharlesChiuGit** [comment]
Linters still reports errors after u comment `clang_format`?

Would u mind share the screenshots? I would lieke to see the format of the diagnostics.

**Comment by ayamir** [comment]
> { ["dim/unused"] = true, float = true, severity_sort = false, signs = true, underline = true, update_in_insert = false, virtual_text = true },,I also need to make it disable

Open a new issue, don't off-topic.

**Comment by ayamir** [comment]
@macrosea You can directly remove `--clang-tidy` and see the result.

**Comment by rileychc** [comment]
> 

OK,   but ,  I also  want to achieve it ,comment "--clang-tidy" or remove it  ,no problem  been solved.

**Comment by rileychc** [comment]
> Linters still reports errors after u comment `clang_format`?
> 
> Would u mind share the screenshots? I would lieke to see the format of the diagnostics.

<img width="263" alt="Pasted Graphic 3" src="https://user-images.githubusercontent.com/116
<img width="965" alt="Pasted Graphic 4" src="https://user-images.githubusercontent.com/116857974/226242908-ba6846be-aaf7-4ad7-98a7-e535bca7a72d.png">
857974/226242901-9f273f77-cc0c-403a-93d4-26dd27d26e53.png">

**Comment by CharlesChiuGit** [comment]
Ok, so from the diagnostics, those errors are from lsp and but not `null-ls`. I don't think u need to change anything related to `null-ls` ATM.

**Comment by rileychc** [comment]
> Ok, so from the diagnostics, those errors are from lsp and but not `null-ls`. I don't think u need to change anything related to `null-ls` ATM.


Thank you very much.

**Comment by ayamir** [comment]
You can write a `.clang-tidy` file under your project root and fill it with below which will ensure disable all of the `clang-tidy`'s check. More info refer to this: https://clang.llvm.org/extra/clang-tidy/
```
Checks: '-*'
```

**Comment by Jint-lzxy** [comment]
AFAIK This is an upstream issue that might be fixed _(perhaps?)_ in the next release. Current workaround is to create a new `config.yaml` in the following directory if such file doesn't exist (this is known as a [global configuration file](https://clangd.llvm.org/config#files)):
- macOS: `~/Library/Preferences/clangd/`
- Other \*nix systems: `$XDG_CONFIG_HOME/clangd/`, if `$XDG_CONFIG_HOME` is undefined then use `~/.config/clangd/`

Then add the following content to that file:
```yml
Diagnostics:
  ClangTidy:
    Remove: ["*"]
```
***
> How should I specify the c++ standard of clangd in that file?

Append to `config.yaml`:
```yml
CompileFlags:
  Add: [-std=c++??] # or gnu++??
```

**Comment by Jint-lzxy** [comment]
AFAIK This is an upstream issue that might be fixed _(perhaps?)_ in the next release. Current workaround is to create a new `config.yaml` in the following directory if such file doesn't exist (this is known as a [global configuration file](https://clangd.llvm.org/config#files)):
- macOS: `~/Library/Preferences/clangd/`
- Other \*nix systems: `$XDG_CONFIG_HOME/clangd/`, if `$XDG_CONFIG_HOME` is undefined then use `~/.config/clangd/`

Then add the following content to that file:
```yml
Diagnostics:
  ClangTidy:
    Remove: ["*"]
```
***
> How should I specify the c++ standard of clangd in that file?

Append to `config.yaml`:
```yml
CompileFlags:
  Add: [-std=c++??] # or gnu++??
```

cc @rileychc @macrosea

**Comment by Jint-lzxy** [comment]
Closed due to inactivity.
