### ISSUE TITLE
Lack of `rustc` and `cargo` toolchain in installation script

### ISSUE THREAD

**Issue by rileychc** [ayamir/nvimdots#586]
### Version confirmation

- [X] Confirm

### Following prerequisites

- [X] Confirm

### Neovim version

NVIM v0.8.3

### Operating system/version

macOS 13.2.1

### Terminal name/version

iterm2 Build 3.4.19

### Branch info

main (Default/Latest)

### Fetch Preferences

SSH (use_ssh = true)

### How to reproduce the issue

<leader> r

### Expected behavior

Error executing lua Vim:E475: Invalid value for argument cmd: '/Users/riley/.local/share/nvim/site/lazy/sniprun/ta
rget/release/sniprun' is not executable
stack traceback:
        [C]: in function 'jobstart'
        ...iley/.local/share/nvim/site/lazy/sniprun/lua/sniprun.lua:199: in function 'start'
        ...iley/.local/share/nvim/site/lazy/sniprun/lua/sniprun.lua:203: in function 'notify'
        ...iley/.local/share/nvim/site/lazy/sniprun/lua/sniprun.lua:215: in function 'run'
        [string ":lua"]:1: in main chunk

**Comment by CharlesChiuGit** [comment]
run `:checkhealth sniprun`

**Comment by CharlesChiuGit** [comment]
> 3 - WARNING: Rust toolchain not available

So u need to install `rustc` and `cargo` first and recompile `sniprun` binary( or just re-install the plugin ).

**Comment by CharlesChiuGit** [comment]
@Jint-lzxy maybe we need to include `rustc` and `cargo` in the installation scripts?

**Comment by rileychc** [comment]
> > 3 - WARNING: Rust toolchain not available
> 
> So u need to install `rustc` and `cargo` first and recompile `sniprun` binary( or just re-install the plugin ).

Can you tell me  how to recompile it?

**Comment by CharlesChiuGit** [comment]
please make sure the rust toolchain is installed first.

**Comment by rileychc** [comment]
> please make sure the rust toolchain is installed first.
<img width="971" alt="截屏2023-03-20 18 04 35" src="https://user-images.githubusercontent.com/116857974/226308268-8aa91877-6234-4798-872d-c49814dc230a.png">
it have loaded about 2hors,my god.

**Comment by CharlesChiuGit** [comment]
I think there's sth wrong, it shouldn't take more than 3mins.
It happens to me only when I ran nvim on a 2 core cpu and super small ram VM.

**Comment by rileychc** [comment]
> I think there's sth wrong, it shouldn't take more than 3mins.
> It happens to me only when I ran nvim on a 2 core cpu and super small ram VM.

what should i do

**Comment by ayamir** [comment]
```shell
cd ~/.local/share/nvim/site/lazy/sniprun
bash ./install.sh
```

**Comment by rileychc** [comment]
> ```shell
> cd ~/.local/share/nvim/site/lazy/sniprun
> bash install.sh
> ```
<img width="977" alt="截屏2023-03-20 19 19 27" src="https://user-images.githubusercontent.com/116857974/226324927-8e3a2085-2674-4a45-8478-c67ba3b2c066.png">
It still can not solve problem.

**Comment by rileychc** [comment]
And I have reinstalled vimdot.

**Comment by rileychc** [comment]
My computer is an Apple chip.

**Comment by Jint-lzxy** [comment]
@rileychc Do you use any package manager? Manually installing `rust` on macOS can lead to a series of environmental issues, especially for Apple chips with stricter security measures.

**Comment by Jint-lzxy** [comment]
@rileychc Do you use any package manager? Manually installing `rust` on macOS can lead to a series of environment issues, especially for Apple chips with stricter security measures.

**Comment by rileychc** [comment]
> 

I use brew  manager

**Comment by rileychc** [comment]
> 

有其他方法安装吗

**Comment by rileychc** [comment]
└─[$]> cargo --version && rustc --version && which cargo && which rustc
cargo 1.68.0 (115f34552 2023-02-26)
rustc 1.68.0 (2c8cc3432 2023-03-06)
/Users/riley/.cargo/bin/cargo
/Users/riley/.cargo/bin/rustc

**Comment by Jint-lzxy** [comment]
> Is there any other way to install it?

Yes, but none is recommended on macOS because it would corrupt the rust toolchain (Different programs may call `rustc` installed at different locations, resulting in `cargo` reporting that packages have been installed but some programs still fail to find them, which can be very difficult to debug in the future). Do you have any special concerns?

**Comment by rileychc** [comment]
I can't compile sniprun through rustc.，I can't use sniprun

**Comment by Jint-lzxy** [comment]
Note that the install script (via `bash install.sh`) does not display debugging information.

**Comment by rileychc** [comment]
<img width="1273" alt="image" src="https://user-images.githubusercontent.com/116857974/226338261-83776fa9-36db-4453-9573-9eb2f99fc907.png">
it stoped

**Comment by Jint-lzxy** [comment]
Try `cargo clean && rm -rf ~/.cargo/registry/index && rm -rf ~/.cargo/.package-cache`.

Looks like multiple installation failures have blocked the current compilation of `sniprun`

**Comment by Jint-lzxy** [comment]
Then compile `sniprun` from source again via `cargo build --release`.

**Comment by Jint-lzxy** [comment]
`cd ~/.local/share/nvim/site/lazy/sniprun`

**Comment by rileychc** [comment]
<img width="1241" alt="image" src="https://user-images.githubusercontent.com/116857974/226341857-f8610af2-b484-43e9-b2b0-8f95a58e3e23.png">

**Comment by Jint-lzxy** [comment]
So the real issue is your current connection to `crates.io` is too slow.

你可以更换[镜像源](https://doc.rust-lang.org/cargo/reference/source-replacement.html)或在终端配置代理：
```shell
export https_proxy="http://<your-address>:<your-port>"
export http_proxy="http://<your-address>:<your-port>"
# <optional> export all_proxy="socks5://<your-address>:<your-port>"
```

**Comment by rileychc** [comment]
<img width="1470" alt="image" src="https://user-images.githubusercontent.com/116857974/226342723-dbef0df3-7d7d-470c-b396-0cb33b07c085.png">
I  add them  to  ~/.zshrc

**Comment by rileychc** [comment]
is it  finished? and can  i  use sniprun?

**Comment by Jint-lzxy** [comment]
Yep 🥳

**Comment by rileychc** [comment]
<img width="1386" alt="image" src="https://user-images.githubusercontent.com/116857974/226345259-dc7108f7-12ef-4913-b6a9-19a15f838081.png">
but   when i  use it ,it tip
<img width="643" alt="image" src="https://user-images.githubusercontent.com/116857974/226345426-77de00e7-c61c-4ebb-989b-275674698133.png">

**Comment by Jint-lzxy** [comment]
This has nothing to do with `sniprun`. This message simply means that the selected code block cannot be compiled.

**Comment by rileychc** [comment]
> Yep 🥳

You are really awesome. Thank you, boss.

**Comment by Jint-lzxy** [comment]
Great 👍 Gonna close this issue now.

If you have any further questions, feel free to reopen this at any time.

**Comment by rileychc** [comment]
I have another question.

**Comment by rileychc** [comment]
i  have installed llvm

**Comment by Jint-lzxy** [comment]
Then you need to change this line to your install location:
https://github.com/ayamir/nvimdots/blob/ed54fd687d7347168b887b8b420d42f520f8b5d6/lua/modules/configs/tool/dap/dap-lldb.lua#L5

**Comment by Jint-lzxy** [comment]
You need the output of `which lldb-vscode` 😄

**Comment by rileychc** [comment]
<img width="686" alt="image" src="https://user-images.githubusercontent.com/116857974/226349164-2b2faf98-5b84-4333-924a-14c2e0cfafcb.png">
haven't it

**Comment by Jint-lzxy** [comment]
You need to have `llvm` in your search path, check:
```sh
brew --prefix llvm
```

**Comment by rileychc** [comment]
<img width="746" alt="image" src="https://user-images.githubusercontent.com/116857974/226349624-a8183608-31b4-4fd7-976c-749647441283.png">

**Comment by Jint-lzxy** [comment]
```sh
export PATH="$PATH:/opt/homebrew/opt/llvm"
```
reopen your terminal.

**Comment by Jint-lzxy** [comment]
```sh
export PATH="$PATH:/opt/homebrew/opt/llvm/bin"
```
reopen your terminal.

**Comment by rileychc** [comment]
my god 
<img width="1470" alt="image" src="https://user-images.githubusercontent.com/116857974/226353687-708a6d1d-56d5-4a46-ad36-1da7a63ae59f.png">

**Comment by rileychc** [comment]
<img width="432" alt="image" src="https://user-images.githubusercontent.com/116857974/226353817-a0730c84-f9fe-4c9b-b5d4-d0def322c987.png">

**Comment by Jint-lzxy** [comment]
This is the install location of `lldb-vscode` on my intel mac. You have:
```sh
/opt/homebrew/opt/llvm/bin/lldb-vscode
```

**Comment by Jint-lzxy** [comment]
Have you generated an executable?

**Comment by Jint-lzxy** [comment]
Usually via `clang++ -g <file> -o <output>`

**Comment by Jint-lzxy** [comment]
This is not how debuggers work. You **need** to provide an executable for the debugger to attach to.

**Comment by rileychc** [comment]
Do you need the file at the end of .out?

**Comment by Jint-lzxy** [comment]
> maybe we need to include `rustc` and `cargo` in the installation scripts or the wiki?

@CharlesChiuGit IMO no need to add this. AFAIK `rust` is shipped with several operating systems, and `sniprun` will prompt users to install the rust toolchain if necessary. Actually that's not the problem with this issue 😄

**Comment by Jint-lzxy** [comment]
> Where should I put it?

You read the wrong content.
> Make sure first use `g++` or `clang++` with `-g` flag to get executable `a.out` file.

This line 😄

**Comment by CharlesChiuGit** [comment]
> @CharlesChiuGit IMO no need to add this. AFAIK `rust` is shipped with several operating systems, and `sniprun` will prompt users to install the rust toolchain if necessary. Actually that's not the problem with this issue 😄

got it. nice!

**Comment by CharlesChiuGit** [comment]
So it's the proxy, hmmm, interesting! TIL
