### ISSUE TITLE
code fold in diff mode

### ISSUE THREAD

**Issue by nkta3m** [ayamir/nvimdots#587]
### Version confirmation

- [X] Confirm

### Following prerequisites

- [X] Confirm

### Neovim version

NVIM v0.8.3 Build type: Release LuaJIT 2.1.0-beta3 Compiled by builduser

### Operating system/version

Arch 6.1

### Terminal name/version

Alacritty

### Branch info

main (Default/Latest)

### Fetch Preferences

HTTPS (use_ssh = false)

### How to reproduce the issue

nvim -d file file2

### Expected behavior

显示两个文件的不同

**Comment by ayamir** [comment]
Press `zi` can unfold all of blocks easily.

**Comment by ayamir** [comment]
Maybe can't. It's `neovim`'s feature, refer to is: https://neovim.io/doc/user/diff.html
<img width="545" alt="image" src="https://user-images.githubusercontent.com/61657399/226318105-ebdb6297-0060-499c-bef5-22a692f3b3a6.png">

**Comment by nkta3m** [comment]
我发现把treesitter中的这句注释掉，默认就不会折叠了`vim.api.nvim_set_option_value("foldexpr", "nvim_treesitter#foldexpr()", {})`

**Comment by ayamir** [comment]
Then you will lost the normal code fold function based on `treesitter`.
