### ISSUE TITLE
Insert mode press tab would navigate to a random line

### ISSUE THREAD

**Issue by Dennis-Zhang-SH** [ayamir/nvimdots#588]
### Version confirmation

- [X] Confirm

### Following prerequisites

- [X] Confirm

### Neovim version

NVIM v0.8.3

### Operating system/version

WSL2 Ubuntu22.04 5.15.90.1-microsoft-standard-WSL2

### Terminal name/version

windows terminal 1.16.10262.0

### Branch info

main (Default/Latest)

### Fetch Preferences

SSH (use_ssh = true)

### How to reproduce the issue

Insert mode press `tab`, the cursor would jump to a random line.

### Expected behavior

input a tab space into where cursor located.

**Comment by ayamir** [comment]
Does it occurs after you use snippet to complete?

**Comment by Jint-lzxy** [comment]
IMO it's related to `LuaSnip`. Pressing `<Tab>` in insert mode when cmp is hidden will jump to the position of the previous snippet (L99-100):
https://github.com/ayamir/nvimdots/blob/ed54fd687d7347168b887b8b420d42f520f8b5d6/lua/modules/configs/completion/cmp.lua#L96-L104

**Comment by ayamir** [comment]
We can restore to previous keymap `<C-l>` and `<C-h>` to navigate cursor in snippet. Seperate this function from `<Tab>`.
