### ISSUE TITLE
ERROR: vim(highlights):

### ISSUE THREAD

**Issue by rileychc** [ayamir/nvimdots#590]
### Version confirmation

- [X] Confirm

### Following prerequisites

- [X] Confirm

### Neovim version

NVIM v0.8.3

### Operating system/version

macOS 13.2.1

### Terminal name/version

iterm2 Build 3.4.19

### Branch info

main (Default/Latest)

### Fetch Preferences

SSH (use_ssh = true)

## The following errors have been detected:
  - ERROR: vim(highlights): ...im/0.8.3/share/nvim/runtime/lua/vim/treesitter/query.lua:219: query: invalid node type at position 2765 for language vim
    vim(highlights) is concatenated from the following files:
    | [ERROR]:"/Users/riley/.local/share/nvim/site/lazy/nvim-treesitter/queries/vim/highlights.scm", failed to load: ...im/0.8.3/share/nvim/runtime/lua/vim/treesitter/query.lua:219: query: invalid node type at position 2765 for language vim

### Expected behavior

<img width="1098" alt="image" src="https://user-images.githubusercontent.com/116857974/226604917-775b20ad-e09e-4568-bdfd-db4642a94f24.png">

**Comment by ayamir** [comment]
Have you tried the solution described in #393?

**Comment by rileychc** [comment]
Yesterday, because I couldn't debug, I reinstalled nvimdots, and then reported this error.

**Comment by rileychc** [comment]
<img width="982" alt="image" src="https://user-images.githubusercontent.com/116857974/226619597-69b84979-c07f-4806-8754-4c9fe3e7adb3.png">

**Comment by Jint-lzxy** [comment]
> Can nvim solve the problem of not being able to use the command key on the macOS system?

This is another issue. Please, don't go off-topic.

> <img alt="image" width="982" src="https://user-images.githubusercontent.com/116857974/226619597-69b84979-c07f-4806-8754-4c9fe3e7adb3.png">

You also need to set `ProxyCommand` for `ssh` **temporarily**.[^1] There is an appreciable probability of getting "Broken pipe" error on macOS if you only setup global proxy forwarding in System Preferences.

Append to `~/.ssh/config` _(Delete after treesitter installation is complete)_:
```sh
Host *
    IgnoreUnknown UseKeychain
    ProxyCommand nc -X 5 -x <host>:<port> %h %p
```
To get \<host\> and \<port\> see https://github.com/ayamir/nvimdots/issues/586#issuecomment-1476175402.

[^1]: Setting `ProxyCommand` for `ssh` still cannot **fully guarantee** the success of large-data transmission. But it _does_ decrease the probability of transmission failures. If the error persists, please try again.

**Comment by rileychc** [comment]
<img width="721" alt="image" src="https://user-images.githubusercontent.com/116857974/226631420-c185bbb5-6be0-47e9-b10f-69c4250c2964.png">
Is that so?

**Comment by rileychc** [comment]
<img width="184" alt="image" src="https://user-images.githubusercontent.com/116857974/226632363-23065e5d-c564-45fc-a443-cfa44290ec36.png">

**Comment by rileychc** [comment]
<img width="823" alt="image" src="https://user-images.githubusercontent.com/116857974/226633967-7b3b710c-7464-473f-ae85-e9880c3a1905.png">
<img width="704" alt="image" src="https://user-images.githubusercontent.com/116857974/226634024-63cb09cc-b612-4fbb-80a2-d702fb4a779c.png">

**Comment by rileychc** [comment]
It still reports an error.

**Comment by rileychc** [comment]
downloading tree-sitter-python  ，It has been unable to complete the download.

**Comment by Jint-lzxy** [comment]
1. `nvim ~/.ssh/config`
2. Paste the following:
```sh
Host *
    IgnoreUnknown UseKeychain
    ProxyCommand nc -X 5 -x <host>:<port> %h %p
```
3. Save the file and quit neovim.

**Delete that `host` file.**

**Comment by Jint-lzxy** [comment]
1. `nvim ~/.ssh/config` (`config` is a **file** with no extension)
2. Paste the following:
```sh
Host *
    IgnoreUnknown UseKeychain
    ProxyCommand nc -X 5 -x <host>:<port> %h %p
```
3. Save the file and quit neovim.

**Delete that `host` file and the `config` folder.**

**Comment by Jint-lzxy** [comment]
Then follow https://github.com/ayamir/nvimdots/issues/393#issuecomment-1368655491.

**Comment by rileychc** [comment]
> 然后关注[#393（评论）。](https://github.com/ayamir/nvimdots/issues/393#issuecomment-1368655491)

I have already seen it.，Still can't solve it.

**Comment by Jint-lzxy** [comment]
In a **new iTerm2 window**, enter
```sh
unset http_proxy; unset https_proxy;
```
Then `nvim`

**Comment by rileychc** [comment]
<img width="819" alt="image" src="https://user-images.githubusercontent.com/116857974/226641154-ef595b35-8f95-4a42-9c5f-9d50dd79e8f4.png">
Or report an error.

**Comment by rileychc** [comment]
:TSInstall! <lang> ， is my  lang  should be ？

**Comment by Jint-lzxy** [comment]
What _is_ the error? Everything looks fine in the screenshot.

**Comment by Jint-lzxy** [comment]
Have you ever tried reinstalling `treesitter`?
```sh
rm -rf ~/.local/share/nvim/site/lazy/nvim-treesitter/
```

**Comment by rileychc** [comment]
<img width="1003" alt="image" src="https://user-images.githubusercontent.com/116857974/226641886-f4811fb0-56f9-425a-ba53-d99fa4c0b0a2.png">
The order I execute is  TSInstall python

**Comment by rileychc** [comment]
<img width="868" alt="image" src="https://user-images.githubusercontent.com/116857974/226642455-b38d7a54-64a3-4dd8-8a12-a10c56333991.png">
I have reinstalled it once.Then I'll try again.

**Comment by rileychc** [comment]
<img width="934" alt="image" src="https://user-images.githubusercontent.com/116857974/226762345-ba60f359-5353-422e-9eb2-e1634cdacbe1.png">

it can't  still solve the problem.

**Comment by rileychc** [comment]
<img width="1112" alt="image" src="https://user-images.githubusercontent.com/116857974/226772464-7571cf0c-5909-45e3-9470-2087fd8837f6.png">

**Comment by rileychc** [comment]
I have executed   sudo nvim  and   :TSInstall! python before .

**Comment by rileychc** [comment]
Then it became like this.

**Comment by ayamir** [comment]
> <img alt="image" width="1112" src="https://user-images.githubusercontent.com/116857974/226772464-7571cf0c-5909-45e3-9470-2087fd8837f6.png">

It was caused by your network, you can't access the github repo correctly. No need to `sudo`.

**Comment by rileychc** [comment]
I downloaded vimdots again and can use the connection successfully.
It doesn't work with the original vimdots.

**Comment by ayamir** [comment]
So it's a temp problem with your network.

**Comment by JerryAllison** [comment]
这个问题已经困扰我好几月了，reinstall treesitter，不行，TSUpdate python，也不行，现在不知道怎么搞了

**Comment by CharlesChiuGit** [comment]
@JerryAllison have u update your nvim or pull the latest commits?

**Comment by JerryAllison** [comment]
> have u update your nvim or pull the latest commits?

更新了最新版

**Comment by CharlesChiuGit** [comment]
try branch 0.10

**Comment by JerryAllison** [comment]
> try branch 0.10

$ vim --version
NVIM v0.10.0
Build type: Release
LuaJIT 2.1.1716656478
Run "nvim -V1 -v" for more info

我现在用的是0.10版本

**Comment by CharlesChiuGit** [comment]
no, i not talking about nvim version now, the 0.10 branch of this repo
