### ISSUE TITLE
ERROR: Command timed out: gem list -ra '^neovim$'   - ERROR: Failed to run: gem list -ra ^neovim$

### ISSUE THREAD

**Issue by rileychc** [ayamir/nvimdots#591]
### Version confirmation

- [X] Confirm

### Following prerequisites

- [X] Confirm

### Neovim version

NVIM v0.8.3

### Operating system/version

macOS 13.2.1

### Terminal name/version

iterm2 Build 3.4.19

### Branch info

main (Default/Latest)

### Fetch Preferences

SSH (use_ssh = true)

## Ruby provider (optional)
  - INFO: Ruby: ruby 2.6.10p210 (2022-04-12 revision 67958) [universal.arm64e-darwin22]
  - INFO: Host: /usr/local/bin/neovim-ruby-host
  - ERROR: Command timed out: gem list -ra '^neovim$'
  - ERROR: Failed to run: gem list -ra ^neovim$
    - ADVICE:
      - Make sure you're connected to the internet.
      - Are you behind a firewall or proxy?

### Expected behavior

<img width="1106" alt="image" src="https://user-images.githubusercontent.com/116857974/226605228-5ca66396-7e32-4a07-87e5-2f0c62c5ab57.png">

**Comment by ayamir** [comment]
ruby is not required to use the whole function normally.

**Comment by rileychc** [comment]
I didn't report this error before.

**Comment by rileychc** [comment]
> ruby is not required to use the whole function normally.
I can't use the command key on macOS on neovim. Can this be solved?
