### ISSUE TITLE
Unable to enter variables when  debugging.

### ISSUE THREAD

**Issue by rileychc** [ayamir/nvimdots#592]
### Version confirmation

- [X] Confirm

### Following prerequisites

- [X] Confirm

### Neovim version

NVIM v0.8.3

### Operating system/version

macOS 13.2.1

### Terminal name/version

iterm2 Build 3.4.19

### Branch info

main (Default/Latest)

### Fetch Preferences

SSH (use_ssh = true)

### Affected language servers

clang

### How to reproduce the issue

<img width="2560" alt="image" src="https://user-images.githubusercontent.com/116857974/226796602-7daf9b5d-58fb-4cb0-bde8-a23123deacdc.png">

### Actual behavior

able to proceed to the next debugging

### Support info

<img width="2014" alt="image" src="https://user-images.githubusercontent.com/116857974/226796842-e7aada89-9ad9-427e-8861-e46504e86e58.png">

**Comment by Jint-lzxy** [comment]
See #440. One solution is to attach the debugger to a running executable. More info: [lldb-vscode/README.md](https://github.com/llvm/llvm-project/blob/main/lldb/tools/lldb-vscode/README.md), option **"attach"**.

Getting `dap` to handle user input currently requires appreciable user configuration as it's platform specific. If you don't want to spend time setting up all those "dirty details" then I would recommend you redirect `stdin` to a file or simply get user input from a file.

This is the minimal equivalent of your program that would get user input from a file _(to keep the code concise, I omitted several status checks)_:
```cpp
#include <fstream>
#include <iostream>

int main()
{
	std::ifstream in("dat.txt", std::ifstream::in | std::ifstream::binary); // read from ./dat.txt
	if (in.is_open()) {
		int var1 = 0;
		in >> var1;
		std::cout << var1;

		in.close();
	}
	return 0;
}
```

Using C-style [`freopen`](https://en.cppreference.com/w/cpp/io/c/freopen) to redirect `stdin` is also feasible.

**Comment by Jint-lzxy** [comment]
Closed due to inactivity.
