### ISSUE TITLE
Unable to close a single file.

### ISSUE THREAD

**Issue by johnnytim** [ayamir/nvimdots#593]
![image](https://user-images.githubusercontent.com/101324087/226814946-36cfca68-1e68-4d9c-bfba-a61e78b052fa.png)

When I want to click here to close this single file, it always closes the entire project and then returns directly to the shell.

**Comment by aarnphm** [comment]
This is closing the buffer. Please read on the difference between buffer and a tab.

**Comment by aarnphm** [comment]
you can use BufDel to remove the buffer. imo managing buffer is always better than managing tabs

**Comment by Jint-lzxy** [comment]
On a side note, you need to install a [patched font](https://www.nerdfonts.com/font-downloads) in order to render those icons correctly

**Comment by ayamir** [comment]
The close button is provided by upstream which we can't modify it to `BufDel` cmd. You can just use `<A-q>` or `:BufDel` to close current buffer. More info: https://stackoverflow.com/questions/26708822/why-do-vim-experts-prefer-buffers-over-tabs/26710166#26710166
