### ISSUE TITLE
colors.violet 没定义，参考值：#EE82EE

### ISSUE THREAD

**Issue by cvuuhk** [ayamir/nvimdots#6]
https://github.com/ayamir/nvimdots/blob/71f562be753651a55ba3f15a7336407ab85b6b87/lua/modules/ui/lightline.lua#L179

**Comment by ayamir** [comment]
fixed at [this commit](https://github.com/ayamir/nvimdots/commit/e3f1b324c3a091934d0ddde5d1112e438d86b941)
