### ISSUE TITLE
How to add custom LuaSnip?

### ISSUE THREAD

**Issue by mingsu** [ayamir/nvimdots#60]
Again, I am new to Lua configuration, one more simple question.

I want to add more custom snippets, perhaps via `LuaSnip`.

should I add snippets in `module/completion/plugin.lua` as shown below:

```
completion["L3MON4D3/LuaSnip"] = {
    after = "nvim-cmp",
    config = conf.luasnip,
    requires = "rafamadriz/friendly-snippets"
}

```

 or should I create a special folder such as `nvim/snippets/`, then write `json snippets`, like [this one](https://github.com/glepnir/nvim/blob/master/snippets/lua.json)?

**Comment by ayamir** [comment]
Please refer to this: https://github.com/L3MON4D3/LuaSnip/issues/37

**Comment by mingsu** [comment]
Thanks!

After couple hours diving, still with no success.

This new Lua based framework is a bit complex for newbies.

I tried to add code somewhere in `module/*/*.lua`

```
local ls = require("luasnip/loaders/from_vscode").load()
```

It gives me error, said `luasnip` is not found.

Then I found some code in `module/completion/config.lua`, and add the path with my custom snippets folder.

```
function config.luasnip()
    require("luasnip").config.set_config {
        history = true,
        updateevents = "TextChanged,TextChangedI"
    }
    require("luasnip/loaders/from_vscode").load(
    **{ paths = { "~/.config/nvim/snippets" } }**
    )
end

```

besides, I created the path `~/.config/nvim/snippets`, and add a file called `r.json`

```
>cat ~/.config/nvim/snippets/r.json

{
  "aaa": {
    "prefix": "aaa",
    "body": ["a1a1a1"]
  }
}
```

Still not working, please help.

**Comment by mingsu** [comment]
Is it possible to include a demo setup code in your repo? That will greatly facilitate the usage.
I suppose this is general demand.

**Comment by ayamir** [comment]
First of all, your snippets organization should follow structure like `friendly-snippets`.
Secondly, your custom snippets that is the `json` code block, should follow its example.
Thirdly, add your custom snippets to runtimepath.
So here is how I set it:
![image](https://user-images.githubusercontent.com/61657399/146198170-e75e1e7d-e279-4acf-ba37-451884f86012.png)
![image](https://user-images.githubusercontent.com/61657399/146198278-fbb270ea-a1c7-4323-b356-343e3b133497.png)
![image](https://user-images.githubusercontent.com/61657399/146198322-19e0a20c-ad82-4c05-82df-b4061951329a.png)
![image](https://user-images.githubusercontent.com/61657399/146197906-6d869626-88cb-4b3f-8a2c-a54ca7ab686c.png)
then `PackerSync`
![image](https://user-images.githubusercontent.com/61657399/146198403-b8fae94f-82f0-4826-97af-3825a4cc9ca9.png)

**Comment by ayamir** [comment]
> Is it possible to include a demo setup code in your repo? That will greatly facilitate the usage. I suppose this is general demand.

I will setup it when I have enough time, thanks for your advice.

**Comment by mingsu** [comment]
Wonderful!
