### ISSUE TITLE
Manually format file

### ISSUE THREAD

**Issue by fecet** [ayamir/nvimdots#606]
### Feature description

Since we have the option to disable the 'format_on_save' feature, is it possible to manually format a file whenever we desire to do so? 

If not, I am willing to create a pull request to add this functionality.

**Comment by ayamir** [comment]
Do you means provide a user command like `:Format` to format the file unconditionally?

**Comment by fecet** [comment]
Imporve the writting, keep the markdown format:
```
But does it worth to do so?
```
That's exactly what I want to ask:) I have been doing so since I'm more comfortable with manually formatting files when I feel like.
