### ISSUE TITLE
Treesitter can't install

### ISSUE THREAD

**Issue by Penguin-SAMA** [ayamir/nvimdots#609]
### Version confirmation

- [X] Confirm

### Following prerequisites

- [X] Confirm

### Neovim version

NVIM v0.8.3 Build type: Release LuaJIT 2.1.0-beta3 编译者 brew@Ventura-arm64.local  Features: +acl +iconv +tui See ":help feature-compile"       系统 vimrc 文件: "$VIM/sysinit.vim"          $VIM 预设值: "/opt/homebrew/Cellar/neovim/0.8.3/share/nvim"  Run :checkhealth for more info

### Operating system/version

macos 13.3

### Terminal name/version

iTerm2 3.4.19

### Branch info

main (Default/Latest)

### Fetch Preferences

SSH (use_ssh = true)

### How to reproduce the issue

在我使用打开nvim的时候就会出现如下报错
<img width="1361" alt="image" src="https://user-images.githubusercontent.com/50973632/229334436-ae77bfb1-e5d7-4ed7-ad7d-f241788f1ff6.png">
一直按回车就是这样
<img width="642" alt="image" src="https://user-images.githubusercontent.com/50973632/229334473-ec4ded50-f583-4b59-a1ba-ccb65a3ad55f.png">
但是我能正常下载其他所有插件，也能正常登陆github

### Expected behavior

希望能正常安装所有插件

**Comment by Penguin-SAMA** [comment]
刚刚把电脑里所有有关nvim的东西删了重装后又出现这个错误
<img width="718" alt="image" src="https://user-images.githubusercontent.com/50973632/229336417-911e6bc7-86cf-4005-9d53-2125575171cf.png">

**Comment by CharlesChiuGit** [comment]
check other issues first

**Comment by Penguin-SAMA** [comment]
> check other issues first

第一个问题我在卸载多次并重装后都会出现，我刚刚尝试了配置原版LazyVim也同样出现了这个问题，猜测是treesitter的问题，但是不知道怎么解决

**Comment by CharlesChiuGit** [comment]
So did u check other issues? What steps did u tried?

**Comment by Penguin-SAMA** [comment]
> So did u check other issues? What steps did u tried?

目前来看没有其他问题，全部报错都是treesitter的。
我仅仅是使用nvim打开就会出现报错，没有进行其他操作。

**Comment by CharlesChiuGit** [comment]
https://github.com/ayamir/nvimdots/issues?q=label%3Atreesitter+sort%3Aupdated-desc+is%3Aclosed

**Comment by ayamir** [comment]
> 刚刚把电脑里所有有关nvim的东西删了重装后又出现这个错误 <img alt="image" width="718" src="https://user-images.githubusercontent.com/50973632/229336417-911e6bc7-86cf-4005-9d53-2125575171cf.png">

same as #586.

**Comment by ayamir** [comment]
We can't do more about the installation of treesitter. For well-known reason about GFW, you can't access github normally without proxy. Set terminal proxy if you have it. Below commands are needed if you use `bash` or `zsh`:
```bash
export http_proxy=http://<server>:<port>
export https_proxy=http://<server>:<port>
```
replace `<server>` and `<port>` with your own proxy setting.

**Comment by Penguin-SAMA** [comment]
> We can't do more about the installation of treesitter. For well-known reason about GFW, you can't access github normally without proxy. Set terminal proxy if you have it. Below commands are needed if you use `bash` or `zsh`:We can't do more about the installation of treesitter. For well-known reason about GFW, you can't access github normally without proxy. Set terminal proxy if you have it. Below commands are needed if you use bash or zsh:
> 
> ```shell
> export http_proxy=http://<server>:<port>
> export https_proxy=http://<server>:<port>
> ```
> 
> Replace `<server>` and `<port>` with your own proxy setting then open `nvim`.Replace <server> and <port> with your own proxy setting then open nvim.


上述sniprun的问题已经解决，非常感谢。
同时我已经在zsh中配置了代理，git clone也没有出现任何问题，但是treesitter的bug依旧存在

**Comment by Jint-lzxy** [comment]
What is the output of `:checkhealth nvim_treesitter` and `:lua vim.pretty_print(require("nvim-treesitter.parsers").get_parser_configs())`?

**Comment by Jint-lzxy** [comment]
In fact, we missed one breaking change: https://github.com/nvim-treesitter/nvim-treesitter/commit/93fa5df0a3f0aeb72df50a9d2110cb90fc5a0a13.

@Penguin-SAMA Pulling the latest updates would resolve this issue.
