### ISSUE TITLE
为什么切换不了 白色主题 

### ISSUE THREAD

**Issue by ifnk** [ayamir/nvimdots#61]
**Describe the bug**

**To Reproduce**
1. 按照 readme 上面 的 `Switch light/dark theme(if you use edge theme)

# To light
    sed -i "s/\=dark/\=light/g" ~/.config/nvim/lua/modules/ui/config.lua
    sed -i "s/onedark/onelight/g" ~/.config/nvim/lua/modules/ui/config.lua`

然后退出重启 ，还是黑色的主题 ，我试着把 nvim 删除 了，重新克隆 安装 一边， 在按照文档上面做，但是结果还是一样的……

**Comment by ayamir** [comment]
You should use `edge` theme first.
This line: `catppuccin` to `edge`
https://github.com/ayamir/nvimdots/blob/cbacaca83d12a33c5467d1273ee7ab5dfba6a5b4/lua/core/init.lua#L157

**Comment by ifnk** [comment]
> You should use `edge` theme first. This line: `catppuccin` to `edge`
> 
> https://github.com/ayamir/nvimdots/blob/cbacaca83d12a33c5467d1273ee7ab5dfba6a5b4/lua/core/init.lua#L157

我按照 你说的 把 /lua/core/init.lua 里面 的 catppuccin 改成 edge ，然后 又执行  上述 `sed -i "s/\=dark/\=light/g" ~/.config/nvim/lua/modules/ui/config.lua
sed -i "s/onedark/onelight/g" ~/.config/nvim/lua/modules/ui/config.lua`命令 ，重启 nvim ,结果还是 dark 模式呀？

**Comment by lovebaihezi** [comment]
I solve this by run `nvim +PackerSync`

**Comment by ayamir** [comment]
![image](https://user-images.githubusercontent.com/61657399/146543348-013e76ad-e222-4425-a748-b87bd81a6964.png)

**Comment by ayamir** [comment]
实际上我做的事情就是用sed去修改了`ui/config.lua`：
这一行`dark`改成`light`
https://github.com/ayamir/nvimdots/blob/687b4de4384dac89b561802e5e95228c527f198e/lua/modules/ui/config.lua#L4
这一行`catppuccin`改成`onelight`
https://github.com/ayamir/nvimdots/blob/687b4de4384dac89b561802e5e95228c527f198e/lua/modules/ui/config.lua#L88
