### ISSUE TITLE
Many duplicate numbers appear when hopping in Hopline

### ISSUE THREAD

**Issue by darkwilldie** [ayamir/nvimdots#610]
### Version confirmation

- [X] Confirm

### Following prerequisites

- [X] Confirm

### Neovim version

NVIM v0.8.3

### Operating system/version

wsl2

### Terminal name/version

window terminal

### Branch info

main (Default/Latest)

### Fetch Preferences

SSH (use_ssh = true)

### How to reproduce the issue

When jumping an ordered list (number) in a markdown document using hopline, the number duplicated
![image](https://user-images.githubusercontent.com/115530319/229335026-8efb732a-5595-43da-9520-d4df07891981.png)

### Expected behavior

repair the bug

**Comment by ayamir** [comment]
Please describe this issue with more details about how to reproduce.
1. How you execute `HopLine`?
2. It appeas in which mode?
3. Does any error message displayed?

**Comment by CharlesChiuGit** [comment]
I encounter this on windows terminal too. I think it's relate to the terminal itself, not sure how to fix it tho.

**Comment by ayamir** [comment]
> I encountered this on windows terminal too. I think it's relate to the terminal itself and not only on `Hop`, not sure how to fix it tho.

Try `wezterm` if so.

**Comment by CharlesChiuGit** [comment]
Closed for no further responses. Feel free to reopen again.
