### ISSUE TITLE
Lost file history

### ISSUE THREAD

**Issue by fecet** [ayamir/nvimdots#612]
### Version confirmation

- [X] Confirm

### Following prerequisites

- [X] Confirm

### Neovim version

NVIM v0.8.3

### Operating system/version

Arch Linux

### Terminal name/version

Alacritty

### Branch info

main (Default/Latest)

### Fetch Preferences

HTTPS (use_ssh = false)

### How to reproduce the issue

Open and close some files

### Expected behavior

`Telescope oldfiles` list all files just opened

### Actual behavior

Only show the last one file

**Comment by Jint-lzxy** [comment]
Cannot reproduce.

Can u provide a _detailed_ repro? You may use a pseudonym instead of a real filename (e.g., use `A.lua` instead of `init.lua`)
***
Example:
1. Use Telescope to open `./A.lua`
2. Then use nvim-tree to open `./A/B.txt`
3. Close `./A/B.txt`
4. `Telescope oldfiles` shows only one of the files (i.e., `./A.lua`)

**Comment by fecet** [comment]
I just find it's not relevant to `telescope` since
```
:oldfiles
```
only list
```
1: /home/rok/Dashboard-1
2: /home/rok/[Wilder Float 0]
3: /home/rok/[Wilder Float 1]
```

**Comment by Jint-lzxy** [comment]
So you mean `Telescope oldfiles` didn't list the files opened in previous `nvim` instances? Then this is _exactly_ how it works - providing file access within **the current process**, which is often used to reopen _previously opened_ files by [scanning all available buffers](https://github.com/nvim-telescope/telescope.nvim/blob/942fe5faef47b21241e970551eba407bc10d9547/lua/telescope/builtin/__internal.lua#L500-L547).

But FYI, the implementation of `:oldfiles` is actually somewhat different from that of `Telescope oldfiles`:
```console
						*:o* *:ol* *:oldfiles*
:o[ldfiles]		List the files that have marks stored in the ShaDa
			file.  This list is read on startup and only changes
			afterwards with `:rshada!`.  Also see |v:oldfiles|.
			The number can be used with |c_#<|.
			The output can be filtered with |:filter|, e.g.:
				filter /\.vim/ oldfiles
			The filtering happens on the file name.
```

`:oldfiles` uses the so-called ShaDa file (usually located under `cd ~/.local/state/nvim/shada/`) to read your file history. To make your changes available, please use the `:rshada!` command **before** invoking `:oldfiles` (but that is **not** recommended.) By default we write the ShaDa file **only** when leaving `nvim` to avoid unnecessary IO overheads:
https://github.com/ayamir/nvimdots/blob/7f1b6b04e0405dd63d60c79d222613820970a1ee/lua/core/event.lua#L109-L114

Using Telescope, [`frecency`](https://github.com/nvim-telescope/telescope-frecency.nvim) may be the _actual_ command you are looking for:
https://github.com/ayamir/nvimdots/blob/7f1b6b04e0405dd63d60c79d222613820970a1ee/lua/keymap/tool.lua#L117-L122

**Comment by Jint-lzxy** [comment]
So you mean `Telescope oldfiles` didn't list the files opened in previous `nvim` instances? Then this is _exactly_ how it works - providing file access within **the current process**, which is often used to reopen _previously opened_ files by [scanning all available buffers](https://github.com/nvim-telescope/telescope.nvim/blob/942fe5faef47b21241e970551eba407bc10d9547/lua/telescope/builtin/__internal.lua#L500-L547).

But FYI, the implementation of `:oldfiles` is actually somewhat different from that of `Telescope oldfiles`:
```console
						*:o* *:ol* *:oldfiles*
:o[ldfiles]		List the files that have marks stored in the ShaDa
			file.  This list is read on startup and only changes
			afterwards with `:rshada!`.  Also see |v:oldfiles|.
			The number can be used with |c_#<|.
			The output can be filtered with |:filter|, e.g.:
				filter /\.vim/ oldfiles
			The filtering happens on the file name.
```

`:oldfiles` uses the so-called ShaDa file (usually located under `~/.local/state/nvim/shada/`) to read your file history. To make your changes available, please use the `:rshada!` command **before** invoking `:oldfiles` (but that is **not** recommended.) By default we write ShaDa file **only** when leaving `nvim` to avoid unnecessary IO overheads:
https://github.com/ayamir/nvimdots/blob/7f1b6b04e0405dd63d60c79d222613820970a1ee/lua/core/event.lua#L109-L114

Using Telescope, [`frecency`](https://github.com/nvim-telescope/telescope-frecency.nvim) may be the _actual_ command you are looking for:
https://github.com/ayamir/nvimdots/blob/7f1b6b04e0405dd63d60c79d222613820970a1ee/lua/keymap/tool.lua#L117-L122

**Comment by fecet** [comment]
Thank you! I have found the code block that was causing my issue at https://github.com/ayamir/nvimdots/blob/7f1b6b04e0405dd63d60c79d222613820970a1ee/lua/core/event.lua#L109-L114. It was actually deleting my shada everytime(why ?), which I assume is the cause of the problem. After commenting out the block, the `:oldfiles` command worked correctly.

However, I am still facing issues with Telescope e frecency, which only shows one file. Additionally, the output of Telescope oldfiles is the same as :oldfiles. I am concerned that this indicates a problem with my shada or config. Can you suggest any solutions?

**Comment by Jint-lzxy** [comment]
> I have found the code block that was causing my issue at ...

What do you see when manually executing `:wshada!`?

> ... which only shows one file

Is your filepath in the ignore list?
https://github.com/ayamir/nvimdots/blob/7f1b6b04e0405dd63d60c79d222613820970a1ee/lua/modules/configs/tool/telescope.lua#L14
https://github.com/ayamir/nvimdots/blob/7f1b6b04e0405dd63d60c79d222613820970a1ee/lua/modules/configs/tool/telescope.lua#L41

**Comment by fecet** [comment]
:wshada show nothing while :shada! ruin my `:oldfiles`...

**Comment by fecet** [comment]
As for the telescope frequency, it does not know all the files we opened since it was may or may not load when we edit a file…

Do you think we should change this behavior?

**Comment by Jint-lzxy** [comment]
> It seems that it works as expected… Is there any reason to use `!` version instead of without `!`?

That is intentional, as ShaDa file should be written _only_ on exit. Otherwise, you also need `:rshada!` to retrieve the data.
But updating any ShaDa files while `nvim` is running is **never the intended design pattern** (ShaDa files enables you to continue _where you left off_, rather than to perform some operations _while editing_):
```console
:h shada

If you exit Vim and later start it again, you would normally lose a lot of
information.  The ShaDa file can be used to remember that information, which
enables you to continue where you left off.
```
To be short, it's best **not** to use commands related to cache files (like ShaDas) while editing.

**Comment by Jint-lzxy** [comment]
So the problem should be related to `telescope`. Can you provide a minimum repro(https://github.com/ayamir/nvimdots/issues/612#issuecomment-1494367647)? I cannot reproduce this issue on macOS.

> As for the telescope frequency, it does not know all the files we opened since it was may or may not load when we edit a file…

I can't _quite_ understand this, can you clarify this a bit?

**Comment by fecet** [comment]
In order to clarify any potential misunderstandings, when utilizing the ":wsh" command to save a file, the previous shada file is first read, thus causing it to operate akin to the ">>" function in a shell. Conversely, ":wsh!" does not read the old shada file and behaves more similarly to ">" in a shell. This has the consequence that the ":oldfiles" command does not contain files previously opened in other neovim instance, which appears somewhat counterintuitive and deviates from Neovim's default behavior.

**Comment by Jint-lzxy** [comment]
Yep, but since file IO is performed during `VimLeave`, it will not have any impact on `:oldfiles`. The next time you open `nvim`, that file will be read correctly. What problem do you want to address?

**Comment by fecet** [comment]
In our setup, the telescope is lazily loaded. Therefore, if a file is opened without calling the telescope, it will not be recorded in the frequency. For example:
1. `nvim a.py`
2. Quit nvim and reopen it.
3. Call :Telescope and then use :e to open any file.
In this scenario, the later file will appear in the telescope frequency's record of opened files, while the first file will not.

**Comment by fecet** [comment]
> Yep, but since file IO is performed during `VimLeave`, it will not have any impact on `:oldfiles`. The next time you open `nvim`, that file will be read correctly. What problem do you want to address?

You mean `:oldfiles` would still list *all* the files we opened since we install it?

**Comment by Jint-lzxy** [comment]
If we use `:wsh`, then the ShaDa file will grow infinitely as we are always appending to that file. So an alternative,`Telescope frecency` was introduced to address the problem where file history cannot be recorded.

**Comment by fecet** [comment]
> If we use `:wsh`, then the ShaDa file will grow infinitely as we are always appending to that file. So an alternative,`Telescope frecency` was introduced to address the problem where file history cannot be recorded.

Okay..now I get it

**Comment by Jint-lzxy** [comment]
> In our setup, the telescope is lazily loaded. Therefore, if a file is opened without calling the telescope, it will not be recorded in the frequency. For example:
> 
> 1. `nvim a.py`
> 2. Quit nvim and reopen it.
> 3. Call :Telescope and then use :e to open any file.
>    In this scenario, the later file will appear in the telescope frequency's record of opened files, while the first file will not.

Yep, that's why:
> This is _exactly_ how it works - providing file access within **the current process**, which is often used to reopen _previously opened_ files by [scanning all available buffers](https://github.com/nvim-telescope/telescope.nvim/blob/942fe5faef47b21241e970551eba407bc10d9547/lua/telescope/builtin/__internal.lua#L500-L547).

**Comment by Jint-lzxy** [comment]
Note that `Telescope oldfiles` **only provides file access within the current process**.

**Comment by Jint-lzxy** [comment]
Yep, but this way, `main.shada` will grow _very quickly_. If your editing workload is significant, `main.shada` will increase by \~1GB in a very short period of time.

The claim "`Telescope oldfiles` only provides file access within the current process" is based entirely on this configuration, which assumes calling `:wsh!` when exiting 😄

**Comment by fecet** [comment]
And if we are expected to use `telescope frequency` as a better alternative to `:oldfiles`, wouldn't it be better to have it automatically record every time we open a file? So it won't miss any files. 

And this is a bit uncessary to me since vim already offer an option to avoid 
```
then the ShaDa file will grow infinitely
```
by
```
shada=1000,<50,s10,h
```
and we already set it?

**Comment by Jint-lzxy** [comment]
Oh, I see what you're saying. Previously, these were two separate features. `Telescope frecency` focuses on searching the dedicated database _(i.e., for files that have been opened in different `nvim` instances)_, while `Telescope oldfiles` focuses on managing files that were opened in the current session.

Yep IMO we can integrate these features before the next release. I will propose a draft PR perhaps later today 👍 This might require further discussion.
