### ISSUE TITLE
How can I clean these error for C++20

### ISSUE THREAD

**Issue by Penguin-SAMA** [ayamir/nvimdots#614]
### Version confirmation

- [X] Confirm

### Following prerequisites

- [X] Confirm

### Neovim version

NVIM v0.9.0-dev-1312+g908494889

### Operating system/version

macos 13.3

### Terminal name/version

iTerm2 3.4.19

### Branch info

main (Default/Latest)

### Fetch Preferences

SSH (use_ssh = true)

### Affected language servers

clangd

### How to reproduce the issue

编写c++20的新特性代码就会有这些报错，但是电脑自带的clangd以及lsp下载的clangd版本都是支持编译c++20的，有什么解决办法吗？

### Actual behavior

<img width="642" alt="image" src="https://user-images.githubusercontent.com/50973632/229538841-a27ceea6-64fc-4176-8397-d12a8336a3c3.png">

### Support info

<img width="1233" alt="image" src="https://user-images.githubusercontent.com/50973632/229539072-f20344a0-5b54-4d71-bdd0-a817350958cc.png">
<img width="1243" alt="image" src="https://user-images.githubusercontent.com/50973632/229539327-81a8adc0-f3d5-4278-b556-1be0a66548b6.png">

### Logs

```console
[START][2023-04-04 07:09:56] LSP logging initiated
[ERROR][2023-04-04 07:09:56] .../vim/lsp/rpc.lua:734	"rpc"	"clangd"	"stderr"	"I[07:09:56.410] clangd version 15.0.6 (https://github.com/llvm/llvm-project 088f33605d8a61ff519c580a71b1dd57d16a03f8)\nI[07:09:56.411] Features: mac+grpc+xpc\nI[07:09:56.411] PID: 26668\nI[07:09:56.411] Working directory: /Users/penguinsama/Desktop/test\nI[07:09:56.411] argv[0]: clangd\nI[07:09:56.411] argv[1]: --background-index\nI[07:09:56.411] argv[2]: --pch-storage=memory\nI[07:09:56.411] argv[3]: --query-driver=/opt/homebrew/opt/llvm/bin/clang++\nI[07:09:56.411] argv[4]: --clang-tidy\nI[07:09:56.411] argv[5]: --all-scopes-completion\nI[07:09:56.411] argv[6]: --completion-style=detailed\nI[07:09:56.411] argv[7]: --header-insertion-decorators\nI[07:09:56.411] argv[8]: --header-insertion=iwyu\nI[07:09:56.411] Starting LSP over stdin/stdout\n"
[ERROR][2023-04-04 07:09:56] .../vim/lsp/rpc.lua:734	"rpc"	"clangd"	"stderr"	"I[07:09:56.412] <-- initialize(1)\n"
[ERROR][2023-04-04 07:09:56] .../vim/lsp/rpc.lua:734	"rpc"	"clangd"	"stderr"	"I[07:09:56.431] --> reply:initialize(1) 18 ms\n"
[ERROR][2023-04-04 07:09:56] .../vim/lsp/rpc.lua:734	"rpc"	"clangd"	"stderr"	"I[07:09:56.478] <-- initialized\nI[07:09:56.478] <-- textDocument/didOpen\n"
[ERROR][2023-04-04 07:09:56] .../vim/lsp/rpc.lua:734	"rpc"	"clangd"	"stderr"	"I[07:09:56.481] --> textDocument/publishDiagnostics\nI[07:09:56.481] Failed to find compilation database for /Users/penguinsama/Desktop/test/test.cpp\nI[07:09:56.481] ASTWorker building file /Users/penguinsama/Desktop/test/test.cpp version 0 with command clangd fallback\n[/Users/penguinsama/Desktop/test]\n/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -resource-dir=/Users/penguinsama/.local/share/nvim/mason/packages/clangd/clangd_15.0.6/lib/clang/15.0.6 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk -- /Users/penguinsama/Desktop/test/test.cpp\n"
[ERROR][2023-04-04 07:09:56] .../vim/lsp/rpc.lua:734	"rpc"	"clangd"	"stderr"	"I[07:09:56.483] <-- textDocument/semanticTokens/full(2)\n"
[ERROR][2023-04-04 07:09:56] .../vim/lsp/rpc.lua:734	"rpc"	"clangd"	"stderr"	"I[07:09:56.500] --> workspace/semanticTokens/refresh(0)\n"
[ERROR][2023-04-04 07:09:56] .../vim/lsp/rpc.lua:734	"rpc"	"clangd"	"stderr"	"I[07:09:56.517] <-- $/cancelRequest\nI[07:09:56.517] <-- textDocument/semanticTokens/full(3)\n"
[ERROR][2023-04-04 07:09:56] .../vim/lsp/rpc.lua:734	"rpc"	"clangd"	"stderr"	"I[07:09:56.517] <-- reply(0)\n"
[ERROR][2023-04-04 07:09:56] .../vim/lsp/rpc.lua:734	"rpc"	"clangd"	"stderr"	"I[07:09:56.520] --> textDocument/publishDiagnostics\n"
[ERROR][2023-04-04 07:09:56] .../vim/lsp/rpc.lua:734	"rpc"	"clangd"	"stderr"	"I[07:09:56.520] --> reply:textDocument/semanticTokens/full(2) 37 ms, error: Task was cancelled.\nI[07:09:56.520] --> reply:textDocument/semanticTokens/full(3) 2 ms\n"
[ERROR][2023-04-04 07:09:56] .../vim/lsp/rpc.lua:734	"rpc"	"clangd"	"stderr"	"I[07:09:56.759] <-- textDocument/signatureHelp(4)\n"
[ERROR][2023-04-04 07:09:56] .../vim/lsp/rpc.lua:734	"rpc"	"clangd"	"stderr"	"I[07:09:56.762] --> reply:textDocument/signatureHelp(4) 2 ms\n"
[ERROR][2023-04-04 07:09:57] .../vim/lsp/rpc.lua:734	"rpc"	"clangd"	"stderr"	"I[07:09:57.344] <-- textDocument/documentSymbol(5)\nI[07:09:57.345] --> reply:textDocument/documentSymbol(5) 0 ms\n"


```

**Comment by Penguin-SAMA** [comment]
> See [#585 (comment)](https://github.com/ayamir/nvimdots/issues/585#issuecomment-1476081102). Please set `-std=c++20` or `-std=gnu++20`.

我已经设置了`-std=c++20`，但依旧是同一个错误提醒。
我猜测是我没有加`-fmodules`来提供C++20的模块支持，但我应该将这个设置添加在哪里

**Comment by Jint-lzxy** [comment]
```yaml
CompileFlags:
  Add: [-std=c++20, -fmodules]
```

**Comment by Penguin-SAMA** [comment]
还是不行，并且在一段时间后弹出下面这个错误
<img width="561" alt="image" src="https://user-images.githubusercontent.com/50973632/229567708-08d21c58-4fa3-40d8-bb2e-cd66a5a28bae.png">

**Comment by Penguin-SAMA** [comment]
我又做了一些尝试，似乎是mac自带的clang++与llvm的clang++有冲突
<img width="846" alt="image" src="https://user-images.githubusercontent.com/50973632/229569246-e8ce30cf-cc1d-48e7-85cf-27d3c462cf93.png">
不知道是否是这个原因，如果是的话我要在何处修改clang的路径

**Comment by Jint-lzxy** [comment]
Yep, Apple Clang does **not** support most of the C++20 features.

https://github.com/ayamir/nvimdots/blob/7f1b6b04e0405dd63d60c79d222613820970a1ee/lua/modules/configs/completion/servers/clangd.lua#L61

Set `--query-driver` to the output of `echo $(brew --prefix llvm)/bin/clang++`.

**Comment by Jint-lzxy** [comment]
Yep, Apple Clang does **not** support most of the C++20 features.

https://github.com/ayamir/nvimdots/blob/7f1b6b04e0405dd63d60c79d222613820970a1ee/lua/modules/configs/completion/servers/clangd.lua#L61

Assign `--query-driver` the output of `echo $(brew --prefix llvm)/bin/clang++`.

**Comment by Penguin-SAMA** [comment]
依旧不行，我尝试了两种修改方案，不知是否是我理解有误，还是其他原因
<img width="1061" alt="image" src="https://user-images.githubusercontent.com/50973632/229576839-217412b2-5f64-45c2-9922-49bff2459188.png">
打开编辑器后会显示一秒相同的错误，随后出现如下弹窗
<img width="843" alt="image" src="https://user-images.githubusercontent.com/50973632/229577164-88b9a570-1dd1-47c8-955f-6919138e2a56.png">

**Comment by Jint-lzxy** [comment]
```lua
"--query-driver=<add-your-path-here>",
```

**Comment by Jint-lzxy** [comment]
For example, on my Intel mac:
```lua
"--query-driver=/usr/local/opt/llvm/bin/clang++",
```

**Comment by Jint-lzxy** [comment]
After checking the newsletters for `Clang` and `clangd`, it turns out that [their support for modules is incomplete](https://clang.llvm.org/cxx_status.html#cxx20), especially for `clangd`:

> It would be nice if some of {C++20 modules, clang header modules} worked in clangd.
> 
> **Essentially no configurations of this work today**: occasionally things may happen to work but there are many reported problems and crashes. These are not just bugs that can be fixed, a design and new infrastructure is needed.
> 
> Because clang's module functionality can be enabled by setting driver flags, it is possible/easy for people to end up in this broken and unsupportable state, and wasting (their + our) time debugging it. We should consider failing early and explicitly instead.
> 
> **AFAIK nobody has plans/availability to work on this soon.**

I don't think this is something we can address, and after checking other IDEs (e.g., VSCode) that use open-source language server implementations _(rather than builtin servers such as CLion)_, their support for modules is also incomplete (although some have chosen to add several tweaks to cover a small fraction of regular use cases, they are still bug prone due to limitations in the compiler's underlying implementation).

It should be noted that being able to compile is not equivalent to being able to perform static analysis - only adding a new specialized parser for the existing ASTs would solve this problem.

We suggest using such features at least after full support for `C++2a`, or simply disabling these error checks _(not recommended as almost all related features will become unavailable)_.

**Comment by yinghaoyu** [comment]
In your project root path, create a file named `.clang`, then add this:
```yaml
CompileFlags:
  Add: [-std=c++20]
```
