### ISSUE TITLE
Cannot delete user defined text object 

### ISSUE THREAD

**Issue by fecet** [ayamir/nvimdots#615]
### Version confirmation

- [X] Confirm

### Following prerequisites

- [X] Confirm

### Neovim version

NVIM v0.8.3

### Operating system/version

Arch Linux

### Terminal name/version

alacritty

### Branch info

main (Default/Latest)

### Fetch Preferences

SSH (use_ssh = true)

### How to reproduce the issue

I can use `vaf` to select a function object, but `daf` cannot delete it.

text object `aw` `ap` works correctly

### Expected behavior

both `d` and `v` works

**Comment by fecet** [comment]
caused by https://github.com/ayamir/nvimdots/commit/136c6f525301c5f23d1fac8c4468b102500ea8be, is it really safe to set `timeoutlen` to 0?

**Comment by ayamir** [comment]
`timeoutlen=0` should be used with `which-key.nvim` together. Set it to `100` or other value gt than `0` will cause the input latency of `<space>` which is set to `<leader>` when you use `lazygit` in `nvim`. Of course, you can set it `100` or `300`. Maybe there are a better solutions?

**Comment by fecet** [comment]
The author of whichkey.nvim suggests that we set this value to a relatively small number. Is the delay with lazygit the only possible undesirable consequence? How about setting this value to 0 only when lazygit appears?

**Comment by Jint-lzxy** [comment]
I would suggest reverting the changes made in https://github.com/ayamir/nvimdots/commit/136c6f525301c5f23d1fac8c4468b102500ea8be. FWIW there's no reason to set keymaps with `<leader>` as prefix in terminal mode. At present, we only have the following conflicting keymap:
https://github.com/ayamir/nvimdots/blob/fc1857b3c22e1129aa891dc860f5b3319f2e8a4c/lua/keymap/tool.lua#L71-L76
IMO users can just type in the command name _(i.e. `lazygit`)_ to start lazygit _within_ the terminal, and there is no need to set an additional keymap for this.

Alternatively, changing this keymap to something that is rarely used _(for example, meta keys `<A-*>`)_ is also viable 👍

**Comment by CharlesChiuGit** [comment]
As I recall if u don't set it to 0, some keymap will not function correctly since the keymap control is taken by whichkey. So we better be careful about that.

**Comment by Jint-lzxy** [comment]
> As I recall if u don't set it to 0, some keymap will not function correctly since the keymap control is taken by whichkey. So we better be careful about that.

Hmm AFAIK after a recent commit, `which-key` would only took over user input when timeout exceeded `timeoutlen` (which is _exactly_ the purpose of adding those keymaps with `Þ` as suffix)_. Turns out that setting a non-zero value for `timeoutlen` can actually resolve #533, as some keymaps are internally set by `which-key` as `nowait`, resulting in `nvim` not parsing the input that follows.

**Comment by ayamir** [comment]
Sorry for the late reply. I am busy submitting papers and reinstalling the system to `gentoo` these two days.

First, `<leader>g` can be unmapped from `lazygit`.
Second, `set timeoutlen=300` is acceptable but it should be set to `0` when using `lazygit` becase `<Space>` is frequently used when inputing commit message.

**Comment by CharlesChiuGit** [comment]
> Second, `set timeoutlen=300` is acceptable but it should be set to `0` when using `lazygit` becase `<Space>` is frequently used when inputing commit message.

That's the reason I change my leader key from `<Space>` to `<,>` lol
Since `<Space>` is also often used will coding lol

**Comment by Jint-lzxy** [comment]
Then IMO we could unmap `t|<leader>g`. This way, there will be no keymaps starting with `<leader>` in terminal mode, and hence `nvim` would stop waiting for user input when typing `<Space>`. This can also resolve #533.

**Comment by ayamir** [comment]
> Then IMO we could unmap `t|<leader>g`. This way, there will be no keymaps starting with `<leader>` in terminal mode, and hence `nvim` would stop waiting for user input when typing `<Space>`. This can also resolve #533.

Agree.
