### ISSUE TITLE
插入模式下,使用ctrl-u不起作用

### ISSUE THREAD

**Issue by asaning** [ayamir/nvimdots#619]
### Feature description

在插入模式下,我想撤销之前的输入,举一个例子
![image](https://user-images.githubusercontent.com/99789353/230248495-c35b0e39-5edc-4a9f-8c6e-3d6a99b54b89.png)
当我写到一半的时候,我发现自己写错了,要重新写这个函数名和参数,我在插入模式下是执行回滚
![image](https://user-images.githubusercontent.com/99789353/230248638-416cd245-19d4-410c-85a2-7e2773838489.png)
变成这样了
我希望是能回滚到我刚开始写函数的部分

**Comment by CharlesChiuGit** [comment]
Fill your info with the template and re-submit the issue again.

**Comment by Jint-lzxy** [comment]
Duplicate of #616.
