### ISSUE TITLE
因为插件本身的变动导致需要修改配置

### ISSUE THREAD

**Issue by clzoc** [ayamir/nvimdots#62]
andersevenrud\compe_tmux的作者在几天前将主分支切换为cmp_tmux，而compe_tmux变为可选分支，导致PackerSync无法更新这一插件，因此需要将lua/modules/completion/plugins.lua文件中的第28行由{"andersevenrud/compe-tmux", branch = "cmp", after = "cmp-nvim-lua"},修改为{"andersevenrud/cmp-tmux", after = "cmp-nvim-lua"}

**Comment by ayamir** [comment]
pr welcome
