### ISSUE TITLE
After I press F6 to debug, I can't enter insert mode./当我按下 F6 进行调试后，无法进入插入模式

### ISSUE THREAD

**Issue by shininome** [ayamir/nvimdots#621]
Pressing either 'a' or 'i' has no effect, while other modes are working fine
无论是按下 a 还是 i，都没有任何效果，其他模式正常

**Comment by shininome** [comment]
The tested file is a Python file, while the C++ file is not yet running in debug mode/
测试的文件是python文件,c++文件bebug还没跑起来

**Comment by CharlesChiuGit** [comment]
Fill your info with the template and re-submit the issue again.
