### ISSUE TITLE
Virtual text display (and keybinding to accept it) ?

### ISSUE THREAD

**Issue by muzhancun** [ayamir/nvimdots#622]
### Feature description

Is there any way to display virtual text of copilot suggestion like [copilot-cmp](https://user-images.githubusercontent.com/32016110/173933674-9ad85a5a-5ad7-41cd-9fcc-f5a698cc88ae.png)? I can't find the config QAQ.

**Comment by CharlesChiuGit** [comment]
This should be in discussions, transferred.
