### ISSUE TITLE
Switching to `NORMAL` mode in terminals failed

### ISSUE THREAD

**Issue by huge-pancake** [ayamir/nvimdots#628]
### Version confirmation

- [X] Confirm

### Following prerequisites

- [X] Confirm

### Neovim version

NVIM v0.9.0-dev

### Operating system/version

Archlinux

### Terminal name/version

kitty 0.27.1

### $TERM environment variable

xterm-kitty

### Branch info

main (Default/Latest)

### Fetch Preferences

SSH (use_ssh = true)

### How to reproduce the issue

1. Open a terminal
2. Press `jk` or double `ESC`

### Expected behavior

NORMAL mode in terminal

### Actual behavior

Terminal will be closed and nvim-tree opened

### Additional information

![image](https://user-images.githubusercontent.com/73375859/230707623-84c4531b-a86e-4e69-aecf-14cb82b1a69f.png)

It seems that `<C-\>` closed the terminal and `<C-n>` opened nvim-tree.

And the solution is add `:with_noremap()` like following the image.

![image](https://user-images.githubusercontent.com/73375859/230707720-11478024-38fb-4648-80de-47303ef8e5ad.png)

**Comment by ayamir** [comment]
True, you can open a pr if want to contribute for `nvimdots.`

**Comment by huge-pancake** [comment]
I will :D

Also, `<Esc>` should not be used in keybindings for exiting the terminal in `TERMINAL` mode but only `INSERT` mode.
