### ISSUE TITLE
configuration change for sqlite.lua to work on windows system

### ISSUE THREAD

**Issue by clzoc** [ayamir/nvimdots#63]
**Describe the bug**
On windows system, sqlite.lua failed to load because of lack of sqlite3.dll.  To solve this problem, one can change the line locate in lua/modules/tools/config.lua: 
vim.cmd [[packadd sqlite.lua]] 
to:
vim.cmd [[
let g:sqlite_clib_path = 'path/to/sqlite3.dll' (NOTE: Users need to download precompiled sqlite from https://www.sqlite.org/download.html)
packadd sqlite.lua
]]

**Comment by clzoc** [comment]
Would you mind close my issues. They are two corner cases which are insignificant. Thank you for this awesome lua configuration, i have learned a lot.

**Comment by ayamir** [comment]
Thanks for your feedback, I will add it to wiki.
