### ISSUE TITLE
/lua/modules/configs/completion\cmp.lua:95: attempt to concatenate a nil value

### ISSUE THREAD

**Issue by Qejun** [ayamir/nvimdots#634]
### Version confirmation

- [X] Confirm

### Following prerequisites

- [X] Confirm

### Neovim version

NVIM v0.8.3 Build type: RelWithDebInfo LuaJIT 2.1.0-beta3 Compiled by runneradmin@fv-az171-224  Features: -acl +iconv +tui See ":help feature-compile"     system vimrc file: "$VIM\sysinit.vim"   fall-back for $VIM: "C:/Program Files (x86)/nvim/share/nvim"

### Operating system/version

win10 22h2

### Terminal name/version

PowerShell 7.3.3

### Branch info

main (Default/Latest)

### Fetch Preferences

SSH (use_ssh = true)

### How to reproduce the issue

I get this error every time I try to type a letter
Error executing vim.schedule lua callback: ...ppData\Local\nvim/lua/modules/configs/completion\cmp.lua:95: attempt to concatenate a nil value                                                                                                                             
stack traceback:                                                                                                                             ...ppData\Local\nvim/lua/modules/configs/completion\cmp.lua:95: in function 'format'                                                 ...ata/Local/nvim-data/site/lazy/nvim-cmp/lua/cmp/entry.lua:290: in function 'callback'                                              
...cal/nvim-data/site/lazy/nvim-cmp/lua/cmp/utils/cache.lua:38: in function 'get_vim_item'                                           ...ata/Local/nvim-data/site/lazy/nvim-cmp/lua/cmp/entry.lua:397: in function 'callback'                                              
...cal/nvim-data/site/lazy/nvim-cmp/lua/cmp/utils/cache.lua:38: in function 'match'                                                  ...ta/Local/nvim-data/site/lazy/nvim-cmp/lua/cmp/source.lua:114: in function 'get_entries'                                           ...ta/Local/nvim-data/site/lazy/nvim-cmp/lua/cmp/source.lua:352: in function 'cb'                                                    vim/_editor.lua:248: in function <vim/_editor.lua:247>   

![screen](https://user-images.githubusercontent.com/24759432/230750340-6a208615-95eb-43ab-9c64-2ba587a5afad.gif)

### Expected behavior

what should i do to solve this problem？

### Actual behavior

![screen](https://user-images.githubusercontent.com/24759432/230750325-260e3aa1-830c-4089-b401-5aeb0ff1ed8a.gif)

### Additional information

This is what "checkhealth" outputs：

gitsigns: require("gitsigns.health").check()
========================================================================
  - OK: git version 2.24.0.windows.2

lazy: require("lazy.health").check()
========================================================================
## lazy.nvim
  - OK: Git installed
  - OK: no existing packages found by other package managers
  - OK: packer_compiled.lua not found

man: require("man.health").check()
========================================================================
  - OK: plugin/man.vim not in $VIMRUNTIME
  - OK: autoload/man.vim not in $VIMRUNTIME

mason: require("mason.health").check()
========================================================================
## mason.nvim report
  - OK: neovim version >= 0.7.0
  - OK: Registry `require("mason-registry.index")` is installed.
  - OK: Registry `github.com/mason-org/mason-registry version: 2023-04-08-roman-pond` is installed.
  - OK: **unzip**: `UnZip 5.51 of 22 May 2004, by Info-ZIP.  Maintained by C. Spieler.  Send
`
  - OK: **Go**: `go version go1.20.3 windows/amd64`
  - OK: **cargo**: `cargo 1.68.2 (6feb7c9cf 2023-03-26)`
  - WARNING: **luarocks**: unsupported version `luarocks 2.0.2
`. Luarocks version must be >= 3.0.0.
  - OK: **Ruby**: `ruby 3.1.3p185 (2022-11-24 revision 1a6b16756e) [x64-mingw-ucrt]
`
  - OK: **RubyGem**: `3.3.26
`
  - WARNING: **Composer**: not available
  - WARNING: **PHP**: not available
  - OK: **npm**: `9.5.0`
  - OK: **node**: `v18.15.0
`
  - OK: **python3**: `Python 3.8.6
`
  - OK: **pip3**: `pip 23.0.1 from D:\program_file\Python38\lib\site-packages\pip (python 3.8)

`
  - WARNING: **javac**: not available
  - OK: **java**: `java version "9.0.1"
`
  - WARNING: **julia**: not available
  - OK: **wget**: `GNU Wget 1.21.3 built on mingw32.
`
  - OK: **curl**: `curl 7.83.1 (Windows) libcurl/7.83.1 Schannel
`
  - WARNING: **gzip**: not available
  - OK: **tar**: `bsdtar 3.5.2 - libarchive 3.5.2 zlib/1.2.5.f-ipp 
`
  - OK: **pwsh**: `7.3.3 Microsoft Windows 10.0.19045 Win32NT
`
  - OK: **python**: `Python 3.8.6
`
  - OK: **pip**: `pip 23.0.1 from D:\program_file\Python38\lib\site-packages\pip (python 3.8)

`
  - OK: **7z**: `7-Zip 9.10 beta  Copyright (c) 1999-2009 Igor Pavlov  2009-12-22
`
  - WARNING: **python3_host_prog**: not available
  - WARNING: **python3_host_prog pip**: not available
  - OK: GitHub API rate limit. Used: 1. Remaining: 59. Limit: 60. Reset: 2023/4/9 8:19:36.

null-ls: require("null-ls.health").check()
========================================================================
  - OK: black: the command "black" is executable.
  - OK: clang_format: the command "clang-format" is executable.
  - OK: prettier: the command "prettier" is executable.
  - OK: vint: the command "vint" is executable.
  - OK: rustfmt: the command "rustfmt" is executable.
  - OK: shfmt: the command "shfmt" is executable.
  - OK: stylua: the command "stylua" is executable.
  - OK: editorconfig_checker: the command "editorconfig-checker" is executable.

nvim: health#nvim#check
========================================================================
## Configuration
  - OK: no issues found

## Performance
  - OK: Build type: RelWithDebInfo

## Remote Plugins
  - WARNING: "wilder.nvim" is not registered. (python3 not available)
  - OK: Up to date

nvim-treesitter: require("nvim-treesitter.health").check()
========================================================================
## Installation
  - OK: `tree-sitter` found 0.20.7 (b268e412ad4848380166af153300464e5a1cf83f) (parser generator, only needed for :TSInstallFromGrammar)
  - OK: `node` found v18.15.0 (only needed for :TSInstallFromGrammar)
  - OK: `git` executable found.
  - OK: `cc` executable found. Selected from { vim.NIL, "cc", "gcc", "clang", "cl", "zig" }
    Version: cc (Rev4, Built by MSYS2 project) 12.2.0
  - OK: Neovim was compiled with tree-sitter runtime ABI version 14 (required >=13). Parsers must be compatible with runtime ABI.

## OS Info:
{
  machine = "x86_64",
  release = "10.0.19045",
  sysname = "Windows_NT",
  version = "Windows 10 Pro"
}

## Parser/Features         H L F I J
  - bash                ✓ ✓ ✓ . ✓
  - c                   ✓ ✓ ✓ ✓ ✓
  - cpp                 ✓ ✓ ✓ ✓ ✓
  - css                 ✓ . ✓ ✓ ✓
  - go                  ✓ ✓ ✓ ✓ ✓
  - gomod               ✓ . . . ✓
  - html                ✓ ✓ ✓ ✓ ✓
  - javascript          ✓ ✓ ✓ ✓ ✓
  - json                ✓ ✓ ✓ ✓ .
  - latex               ✓ . ✓ . ✓
  - lua                 ✓ ✓ ✓ ✓ ✓
  - make                ✓ . ✓ . ✓
  - markdown            ✓ . ✓ . ✓
  - markdown_inline     ✓ . . . ✓
  - python              ✓ ✓ ✓ ✓ ✓
  - rust                ✓ ✓ ✓ ✓ ✓
  - typescript          ✓ ✓ ✓ ✓ ✓
  - vimdoc              ✓ . . . ✓
  - vue                 ✓ . ✓ ✓ ✓
  - yaml                ✓ ✓ ✓ ✓ ✓

  Legend: H[ighlight], L[ocals], F[olds], I[ndents], In[j]ections
         +) multiple parsers found, only one will be used
         x) errors found in the query, try to run :TSUpdate {lang}

provider: health#provider#check
========================================================================
## Clipboard (optional)
  - OK: Clipboard tool found: win32yank

## Python 3 provider (optional)
  - INFO: Using: g:python3_host_prog = "/usr/bin/python3"
  - WARNING: No Python executable found that can `import neovim`. Using the first available executable for diagnostics.
  - INFO: Executable: Not found

## Python virtualenv
  - OK: no $VIRTUAL_ENV

## Ruby provider (optional)
  - INFO: Ruby: ruby 3.1.3p185 (2022-11-24 revision 1a6b16756e) [x64-mingw-ucrt]
  - WARNING: `neovim-ruby-host` not found.
    - ADVICE:
      - Run `gem install neovim` to ensure the neovim RubyGem is installed.
      - Run `gem environment` to ensure the gem bin directory is in $PATH.
      - If you are using rvm/rbenv/chruby, try "rehashing".
      - See :help |g:ruby_host_prog| for non-standard gem installations.
      - You may disable this provider (and warning) by adding `let g:loaded_ruby_provider = 0` to your init.vim

## Node.js provider (optional)
  - INFO: Node.js: v18.15.0
  - INFO: Nvim node.js host: C:\Users\zhang\AppData\Roaming\npm\node_modules/neovim/bin/cli.js
  - OK: Latest "neovim" npm/yarn/pnpm package is installed: 4.10.1

## Perl provider (optional)
  - WARNING: No usable perl executable found

vim.lsp: require("vim.lsp.health").check()
========================================================================
  - INFO: LSP log level : WARN
  - INFO: Log path: C:\Users\zhang\AppData\Local\nvim-data\lsp.log
  - INFO: Log size: 256 KB

vim.treesitter: require("vim.treesitter.health").check()
========================================================================
  - INFO: Runtime ABI version : 14
  - OK: Loaded parser for bash: ABI version 14
  - OK: Loaded parser for c: ABI version 13
  - OK: Loaded parser for cpp: ABI version 14
  - OK: Loaded parser for css: ABI version 13
  - OK: Loaded parser for go: ABI version 14
  - OK: Loaded parser for gomod: ABI version 13
  - OK: Loaded parser for html: ABI version 13
  - OK: Loaded parser for javascript: ABI version 14
  - OK: Loaded parser for json: ABI version 13
  - OK: Loaded parser for latex: ABI version 14
  - OK: Loaded parser for lua: ABI version 13
  - OK: Loaded parser for make: ABI version 13
  - OK: Loaded parser for markdown: ABI version 13
  - OK: Loaded parser for markdown_inline: ABI version 13
  - OK: Loaded parser for python: ABI version 14
  - OK: Loaded parser for rust: ABI version 14
  - OK: Loaded parser for typescript: ABI version 14
  - OK: Loaded parser for vimdoc: ABI version 14
  - OK: Loaded parser for vue: ABI version 13
  - OK: Loaded parser for yaml: ABI version 13
  - OK: Loaded parser for c: ABI version 13
  - OK: Loaded parser for help: ABI version 14
  - OK: Loaded parser for lua: ABI version 13
  - OK: Loaded parser for vim: ABI version 14

which_key: health#which_key#check
========================================================================
## WhichKey: checking conflicting keymaps
  - WARNING: conflicting keymap exists for mode **"n"**, lhs: **" c"**
  - INFO: rhs: `<Cmd>HopChar1<CR>`
  - WARNING: conflicting keymap exists for mode **"n"**, lhs: **"gc"**
  - INFO: rhs: `<Plug>(comment_toggle_linewise)`
  - WARNING: conflicting keymap exists for mode **"n"**, lhs: **"gb"**
  - INFO: rhs: `<Plug>(comment_toggle_blockwise)`
  - WARNING: conflicting keymap exists for mode **"v"**, lhs: **" c"**
  - INFO: rhs: `<Cmd>HopChar1<CR>`
  - WARNING: buffer-local keymap overriding global for mode **"n"**, buf: 0, lhs: **"<leader>"**
  - INFO: old rhs: ``
  - INFO: new rhs: `<cmd>lua require("which-key").show(" ", {mode = "n", auto = true})<cr>`
  - WARNING: buffer-local keymap overriding global for mode **"x"**, buf: 0, lhs: **"<leader>"**
  - INFO: old rhs: ``
  - INFO: new rhs: `<cmd>lua require("which-key").show(" ", {mode = "v", auto = true})<cr>`

**Comment by huge-pancake** [comment]
Maybe the same as #624 ?

**Comment by Qejun** [comment]
> Maybe the same as #624 ?

I think you have a point,After I commented out the relevant code, the problem disappeared along with the Nerd fonts icon.
<img width="905" alt="2023-04-09 142647" src="https://user-images.githubusercontent.com/24759432/230758434-fa5db285-ba64-448d-9cc3-a7e8b4654c7c.png">

**Comment by Jint-lzxy** [comment]
@Qejun https://github.com/ayamir/nvimdots/commit/d506a191287ef5e02de799e4340f5fc2889470a6 implemented a temporary workaround, you only need to pull the latest changes.

This is part of the v0.9 migration.

**Comment by Qejun** [comment]
> @Qejun [d506a19](https://github.com/ayamir/nvimdots/commit/d506a191287ef5e02de799e4340f5fc2889470a6)实施了临时解决方法，您只需拉取最新的更改。
> 
> 这是 v0.9 迁移的一部分。

我拉取了更新，但是没有把nvim从0.8升级到0.9，所以问题没有解决。我目前采取了[https://github.com/ayamir/nvimdots/issues/624](url)这个问题中推荐的办法。我把nvim\lua\modules\configs\completion\cmp.lua这个文件改成了下面这个样子。


return function()
	local icons = {
		kind = require("modules.utils.icons").get("kind"),
		type = require("modules.utils.icons").get("type"),
		cmp = require("modules.utils.icons").get("cmp"),
	}
	local t = function(str)
		return vim.api.nvim_replace_termcodes(str, true, true, true)
	end

	local border = function(hl)
		return {
			{ "╭", hl },
			{ "─", hl },
			{ "╮", hl },
			{ "│", hl },
			{ "╯", hl },
			{ "─", hl },
			{ "╰", hl },
			{ "│", hl },
		}
	end

	---Handling situations where LuaSnip failed to perform any jumps
	---@param r integer @Cursor position (row) before calling LuaSnip
	---@param c integer @Cursor position (col) before calling LuaSnip
	---@param fallback function @Fallback function inherited from cmp
	local luasnip_fallback = vim.schedule_wrap(function(r, c, fallback)
		local _r, _c = unpack(vim.api.nvim_win_get_cursor(0))
		if _r == r and _c == c then
			fallback()
		end
	end)

	local cmp_window = require("cmp.utils.window")

	cmp_window.info_ = cmp_window.info
	cmp_window.info = function(self)
		local info = self:info_()
		info.scrollable = false
		return info
	end

	local compare = require("cmp.config.compare")
	compare.lsp_scores = function(entry1, entry2)
		local diff
		if entry1.completion_item.score and entry2.completion_item.score then
			diff = (entry2.completion_item.score * entry2.score) - (entry1.completion_item.score * entry1.score)
		else
			diff = entry2.score - entry1.score
		end
		return (diff < 0)
	end

	local lspkind = require("lspkind")
	local cmp = require("cmp")
	local kind_icons = {
		Class = "ﴯ",
		-- Class = "",
		-- Class = "",
		Color = "",
		-- Color = "",
		Constant = "",
		-- Constant = "",
		Constructor = "",
		-- Constructor = "",
		-- Constructor = "",
		Enum = "",
		EnumMember = "",
		Event = "",
		Field = "ﰠ",
		-- Field = "",
		-- Field = "",
		-- Field = "",
		File = "",
		-- File = "",
		-- File = "",
		Folder = "",
		-- Folder = "",
		Function = "",
		Interface = "",
		Keyword = "",
		Method = "",
		Module = "",
		Operator = "",
		Property = "",
		-- Property = "ﰠ",
		Reference = "",
		-- Reference = "",
		-- Reference = "",
		Snippet = "",
		-- Snippet = "",
		Struct = "פּ",
		-- Struct = "",
		Text = "",
		-- Text = "",
		TypeParameter = "",
		-- TypeParameter = "",
		Unit = "",
		Value = "",
		Variable = "",
		-- Variable = "",
		-- Variable = "",
		-- tree-sitter
		String = "",
	}

	cmp.setup({
		window = {
			completion = {
				border = border("Normal"),
				max_width = 80,
				max_height = 20,
			},
			documentation = {
				border = border("CmpDocBorder"),
			},
		},
		sorting = {
			priority_weight = 2,
			comparators = {
				require("copilot_cmp.comparators").prioritize,
				require("copilot_cmp.comparators").score,
				-- require("cmp_tabnine.compare"),
				compare.offset,
				compare.exact,
				compare.lsp_scores,
				require("cmp-under-comparator").under,
				compare.kind,
				compare.sort_text,
				compare.length,
				compare.order,
			},
		},
		--formatting = {
		--	fields = { "kind", "abbr", "menu" },
		--	format = function(entry, vim_item)
		--		local kind = lspkind.cmp_format({
		--			mode = "symbol_text",
		--			maxwidth = 50,
		--			symbol_map = vim.tbl_deep_extend("force", icons.kind, icons.type, icons.cmp),
		--		})(entry, vim_item)
		--		local strings = vim.split(kind.kind, "%s", { trimempty = true })
		--		kind.kind = " " .. strings[1] .. " "
		--		kind.menu = "    (" .. strings[2] .. ")"
		--		return kind
		--	end,
		--},
		formatting = {
			format = function(entry, vim_item)
				local icon = kind_icons[vim_item.kind] or "default icon or text"
				vim_item.kind = icon .. " " .. vim_item.kind
				return vim_item
			end,
		},
		-- You can set mappings if you want
		mapping = cmp.mapping.preset.insert({
			["<CR>"] = cmp.mapping.confirm({ select = true, behavior = cmp.ConfirmBehavior.Replace }),
			["<C-p>"] = cmp.mapping.select_prev_item(),
			["<C-n>"] = cmp.mapping.select_next_item(),
			["<C-d>"] = cmp.mapping.scroll_docs(-4),
			["<C-f>"] = cmp.mapping.scroll_docs(4),
			["<C-w>"] = cmp.mapping.close(),
			["<Tab>"] = cmp.mapping(function(fallback)
				if cmp.visible() then
					cmp.select_next_item()
				elseif require("luasnip").expand_or_locally_jumpable() then
					local _r, _c = unpack(vim.api.nvim_win_get_cursor(0))
					vim.fn.feedkeys(t("<Plug>luasnip-expand-or-jump"))
					luasnip_fallback(_r, _c, fallback)
				else
					fallback()
				end
			end, { "i", "s" }),
			["<S-Tab>"] = cmp.mapping(function(fallback)
				if cmp.visible() then
					cmp.select_prev_item()
				elseif require("luasnip").jumpable(-1) then
					vim.fn.feedkeys(t("<Plug>luasnip-jump-prev"), "")
				else
					fallback()
				end
			end, { "i", "s" }),
		}),
		snippet = {
			expand = function(args)
				require("luasnip").lsp_expand(args.body)
			end,
		},
		-- You should specify your *installed* sources.
		sources = {
			{ name = "nvim_lsp" },
			{ name = "nvim_lua" },
			{ name = "luasnip" },
			{ name = "path" },
			{ name = "treesitter" },
			{ name = "spell" },
			{ name = "tmux" },
			{ name = "orgmode" },
			{ name = "buffer" },
			{ name = "latex_symbols" },
			{ name = "copilot" },
			-- { name = "codeium" },
			-- { name = "cmp_tabnine" },
		},
	})
end

**Comment by Qejun** [comment]
I pulled the new config file, but didn't upgrade nvim from 0.8 to 0.9, so my problem was not solved.
I took the suggestion in [https://github.com/ayamir/nvimdots/issues/624](url)
and the solution in version 0.8 is as follows:
`
return function()
	local icons = {
		kind = require("modules.utils.icons").get("kind"),
		type = require("modules.utils.icons").get("type"),
		cmp = require("modules.utils.icons").get("cmp"),
	}
	local t = function(str)
		return vim.api.nvim_replace_termcodes(str, true, true, true)
	end

	local border = function(hl)
		return {
			{ "╭", hl },
			{ "─", hl },
			{ "╮", hl },
			{ "│", hl },
			{ "╯", hl },
			{ "─", hl },
			{ "╰", hl },
			{ "│", hl },
		}
	end

	---Handling situations where LuaSnip failed to perform any jumps
	---@param r integer @Cursor position (row) before calling LuaSnip
	---@param c integer @Cursor position (col) before calling LuaSnip
	---@param fallback function @Fallback function inherited from cmp
	local luasnip_fallback = vim.schedule_wrap(function(r, c, fallback)
		local _r, _c = unpack(vim.api.nvim_win_get_cursor(0))
		if _r == r and _c == c then
			fallback()
		end
	end)

	local cmp_window = require("cmp.utils.window")

	cmp_window.info_ = cmp_window.info
	cmp_window.info = function(self)
		local info = self:info_()
		info.scrollable = false
		return info
	end

	local compare = require("cmp.config.compare")
	compare.lsp_scores = function(entry1, entry2)
		local diff
		if entry1.completion_item.score and entry2.completion_item.score then
			diff = (entry2.completion_item.score * entry2.score) - (entry1.completion_item.score * entry1.score)
		else
			diff = entry2.score - entry1.score
		end
		return (diff < 0)
	end

	local lspkind = require("lspkind")
	local cmp = require("cmp")
	local kind_icons = {
		Class = "ﴯ",
		-- Class = "",
		-- Class = "",
		Color = "",
		-- Color = "",
		Constant = "",
		-- Constant = "",
		Constructor = "",
		-- Constructor = "",
		-- Constructor = "",
		Enum = "",
		EnumMember = "",
		Event = "",
		Field = "ﰠ",
		-- Field = "",
		-- Field = "",
		-- Field = "",
		File = "",
		-- File = "",
		-- File = "",
		Folder = "",
		-- Folder = "",
		Function = "",
		Interface = "",
		Keyword = "",
		Method = "",
		Module = "",
		Operator = "",
		Property = "",
		-- Property = "ﰠ",
		Reference = "",
		-- Reference = "",
		-- Reference = "",
		Snippet = "",
		-- Snippet = "",
		Struct = "פּ",
		-- Struct = "",
		Text = "",
		-- Text = "",
		TypeParameter = "",
		-- TypeParameter = "",
		Unit = "",
		Value = "",
		Variable = "",
		-- Variable = "",
		-- Variable = "",
		-- tree-sitter
		String = "",
	}

	cmp.setup({
		window = {
			completion = {
				border = border("Normal"),
				max_width = 80,
				max_height = 20,
			},
			documentation = {
				border = border("CmpDocBorder"),
			},
		},
		sorting = {
			priority_weight = 2,
			comparators = {
				require("copilot_cmp.comparators").prioritize,
				require("copilot_cmp.comparators").score,
				-- require("cmp_tabnine.compare"),
				compare.offset,
				compare.exact,
				compare.lsp_scores,
				require("cmp-under-comparator").under,
				compare.kind,
				compare.sort_text,
				compare.length,
				compare.order,
			},
		},
		--formatting = {
		--	fields = { "kind", "abbr", "menu" },
		--	format = function(entry, vim_item)
		--		local kind = lspkind.cmp_format({
		--			mode = "symbol_text",
		--			maxwidth = 50,
		--			symbol_map = vim.tbl_deep_extend("force", icons.kind, icons.type, icons.cmp),
		--		})(entry, vim_item)
		--		local strings = vim.split(kind.kind, "%s", { trimempty = true })
		--		kind.kind = " " .. strings[1] .. " "
		--		kind.menu = "    (" .. strings[2] .. ")"
		--		return kind
		--	end,
		--},
		formatting = {
			format = function(entry, vim_item)
				local icon = kind_icons[vim_item.kind] or "default icon or text"
				vim_item.kind = icon .. " " .. vim_item.kind
				return vim_item
			end,
		},
		-- You can set mappings if you want
		mapping = cmp.mapping.preset.insert({
			["<CR>"] = cmp.mapping.confirm({ select = true, behavior = cmp.ConfirmBehavior.Replace }),
			["<C-p>"] = cmp.mapping.select_prev_item(),
			["<C-n>"] = cmp.mapping.select_next_item(),
			["<C-d>"] = cmp.mapping.scroll_docs(-4),
			["<C-f>"] = cmp.mapping.scroll_docs(4),
			["<C-w>"] = cmp.mapping.close(),
			["<Tab>"] = cmp.mapping(function(fallback)
				if cmp.visible() then
					cmp.select_next_item()
				elseif require("luasnip").expand_or_locally_jumpable() then
					local _r, _c = unpack(vim.api.nvim_win_get_cursor(0))
					vim.fn.feedkeys(t("<Plug>luasnip-expand-or-jump"))
					luasnip_fallback(_r, _c, fallback)
				else
					fallback()
				end
			end, { "i", "s" }),
			["<S-Tab>"] = cmp.mapping(function(fallback)
				if cmp.visible() then
					cmp.select_prev_item()
				elseif require("luasnip").jumpable(-1) then
					vim.fn.feedkeys(t("<Plug>luasnip-jump-prev"), "")
				else
					fallback()
				end
			end, { "i", "s" }),
		}),
		snippet = {
			expand = function(args)
				require("luasnip").lsp_expand(args.body)
			end,
		},
		-- You should specify your *installed* sources.
		sources = {
			{ name = "nvim_lsp" },
			{ name = "nvim_lua" },
			{ name = "luasnip" },
			{ name = "path" },
			{ name = "treesitter" },
			{ name = "spell" },
			{ name = "tmux" },
			{ name = "orgmode" },
			{ name = "buffer" },
			{ name = "latex_symbols" },
			{ name = "copilot" },
			-- { name = "codeium" },
			-- { name = "cmp_tabnine" },
		},
	})
end
`

**Comment by CharlesChiuGit** [comment]
#637 is trying to fix it. Hang tight!
