### ISSUE TITLE
unexpected token `??=` in windows install script

### ISSUE THREAD

**Issue by SolitaryN** [ayamir/nvimdots#636]
### Feature description

powershell报错，已使用管理员模式打开powershell，Invoke-Expression报“包含意外的标号”错误

log
==========================
(base) PS C:\Windows\system32> Set-ExecutionPolicy Bypass -Scope Process -Force; Invoke-Expression ((New-Object System.Net.WebClient).DownloadString('https://raw.githubusercontent.com/ayamir/nvimdots/HEAD/scripts/install.ps1'))
Invoke-Expression : 所在位置 行:20 字符: 22
+ $env:XDG_CONFIG_HOME ??= $env:LOCALAPPDATA
+                      ~~~
表达式或语句中包含意外的标记“??=”。
所在位置 行:21 字符: 17
+ $env:CCPACK_MGR ??= 'unknown'
+                 ~~~
表达式或语句中包含意外的标记“??=”。
所在位置 行:22 字符: 20
+ $env:CCLONE_BRANCH ??= 'main'
+                    ~~~
表达式或语句中包含意外的标记“??=”。
所在位置 行:23 字符: 18
+ $env:CCLONE_ATTR ??= 'undef'
+                  ~~~
表达式或语句中包含意外的标记“??=”。
所在位置 行:24 字符: 17
+ $env:CCDEST_DIR ??= "$env:XDG_CONFIG_HOME\nvim"
+                 ~~~
表达式或语句中包含意外的标记“??=”。
所在位置 行:1 字符: 51
+ ... ess -Force; Invoke-Expression ((New-Object System.Net.WebClient).Down ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ParserError: (:) [Invoke-Expression], ParseException
    + FullyQualifiedErrorId : UnexpectedToken,Microsoft.PowerShell.Commands.InvokeExpressionCommand

**Comment by Jint-lzxy** [comment]
What is the version of your PowerShell? This script **requires** `pwsh` > `v7.1` (the [null-coalescing assignment operator](https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_assignment_operators?view=powershell-7.3#null-coalescing-assignment-operator) was introduced in PowerShell 7.1).

To check the version:
```pwsh
Get-Host
```

**Comment by SolitaryN** [comment]
OMG, I am sorry for the stupid issue, I do not know  some features of the new powershell.
Problem solved, the powershell I used, 5.1,  is too old. I update powershell to 7. 
Thank you, it's a awesome project.
