### ISSUE TITLE
can't find "sqlite3.dll" on Windows

### ISSUE THREAD

**Issue by SolitaryN** [ayamir/nvimdots#638]
### Version confirmation

- [X] Confirm

### Following prerequisites

- [X] Confirm

### Neovim version

NVIM v0.9.0

### Operating system/version

Windows 10

### Terminal name/version

Windows terminal

### Branch info

main (Default/Latest)

### Fetch Preferences

SSH (use_ssh = true)

### How to reproduce the issue

I know the leader is space
steps
1、nvim.exe 
2、<leader>fr      
3、get the error
E5108: Error executing lua: ...Local/nvim-data/site/lazy/sqlite.lua/lua/sqlite/defs.lua:55: cannot load module 'C:\Users\Solitary/Documents/sqlite-dll-win64-x64-3400100/sqlite3.dll': 找不到指定的模块>。
stack traceback:
        [builtin#203]: at 0x7fff4a1165f0
        ...Local/nvim-data/site/lazy/sqlite.lua/lua/sqlite/defs.lua:55: in main chunk
        [C]: in function 'require'
        ...ocal/nvim-data/site/lazy/sqlite.lua/lua/sqlite/utils.lua:252: in function '__index'
        ...a/Local/nvim-data/site/lazy/sqlite.lua/lua/sqlite/db.lua:667: in main chunk
        [C]: in function 'require'
        ...Local/nvim-data/site/lazy/sqlite.lua/lua/sqlite/init.lua:66: in function '__index'
        ....nvim/lua/telescope/_extensions/frecency/sql_wrapper.lua:46: in function 'bootstrap'
        ...cy.nvim/lua/telescope/_extensions/frecency/db_client.lua:92: in function 'init'
        ...ope-frecency.nvim/lua/telescope/_extensions/frecency.lua:76: in function 'frecency'
        C:\Users\Solitary\AppData\Local\nvim/lua/keymap/tool.lua:109: in function <C:\Users\Solitary\AppData\Local\nvim/lua/keymap/tool.lua:108>

==========================================================
whether is the wrong of path, I found the path of sqlite3.dll have some wrong char like \ and / 

### Expected behavior

exectue the corresponding function of the key-binding

### Actual behavior

get error:
E5108: Error executing lua: ...Local/nvim-data/site/lazy/sqlite.lua/lua/sqlite/defs.lua:55: cannot load module 'C:\Users\Solitary/Documents/sqlite-dll-win64-x64-3400100/sqlite3.dll': 找不到指定的模块>。

stack traceback:
        [builtin#203]: at 0x7fff4a1165f0
        ...Local/nvim-data/site/lazy/sqlite.lua/lua/sqlite/defs.lua:55: in main chunk
        [C]: in function 'require'
        ...ocal/nvim-data/site/lazy/sqlite.lua/lua/sqlite/utils.lua:252: in function '__index'
        ...a/Local/nvim-data/site/lazy/sqlite.lua/lua/sqlite/db.lua:667: in main chunk
        [C]: in function 'require'
        ...Local/nvim-data/site/lazy/sqlite.lua/lua/sqlite/init.lua:66: in function '__index'
        ....nvim/lua/telescope/_extensions/frecency/sql_wrapper.lua:46: in function 'bootstrap'
        ...cy.nvim/lua/telescope/_extensions/frecency/db_client.lua:92: in function 'init'
        ...ope-frecency.nvim/lua/telescope/_extensions/frecency.lua:76: in function 'frecency'
        C:\Users\Solitary\AppData\Local\nvim/lua/keymap/tool.lua:109: in function <C:\Users\Solitary\AppData\Local\nvim/lua/keymap/tool.lua:108>

**Comment by CharlesChiuGit** [comment]
check wiki

**Comment by Jint-lzxy** [comment]
Did you follow the prompts in the install script?

https://github.com/ayamir/nvimdots/blob/508111d31c8038c152dc875b9f69643b3f0e4824/scripts/install.ps1#L383-L384

Or check the wiki: [Wiki:Issues#cannot-load-module-libsqlite3-or-similar-issues-on-windows](https://github.com/ayamir/nvimdots/wiki/Issues#cannot-load-module-libsqlite3-or-similar-issues-on-windows).
***

FYI, path separators are trivial in Lua - the interpreter understands both `/` and `\`.

**Comment by CharlesChiuGit** [comment]
can u tried update your `fzf` to 0.39.0 via scoop?

**Comment by SolitaryN** [comment]
It worked.
