### ISSUE TITLE
Parser not available for language "vimdoc"

### ISSUE THREAD

**Issue by Incipe-win** [ayamir/nvimdots#642]
As the title, when I open nvim, I get this problem.
Here is log:
````bash
Installation not possible: ...ite/lazy/nvimtreesitter/lua/nvim-treesitter/install.lua:86: Parser not abailable for language "vimdoc"
See https://github.com/nvim-treesitter/nvim-treesitter/#adding-parsers on how to add a new parser!
````
I'm not sure if this is my problem, should I slove it by [adding-parsers tutorial](https://github.com/nvim-treesitter/nvim-treesitter/#adding-parsers)?

**Comment by CharlesChiuGit** [comment]
Have u use the latest commit?

**Comment by Incipe-win** [comment]
> 

yes, when I type `git pull`, it shows **Already up to date**.

**Comment by CharlesChiuGit** [comment]
Which branch r u on?

**Comment by Incipe-win** [comment]
> Which branch r u on? Currently we have 0.7, 0.8, 0.9 and main.

main

**Comment by CharlesChiuGit** [comment]
hmmm, that shouldn't be possible... Can u remove all plugins and install them again?

**Comment by Incipe-win** [comment]
> hmmm, that shouldn't be possible... Can u remove all plugins and install them again?

ok,let me try.

**Comment by CharlesChiuGit** [comment]
Also did u done a lazy sync yet?

**Comment by Incipe-win** [comment]
> Also did u do a lazy sync yet?

I managed to solve this problem by `lazy sync`, thank u very much for your help.
