### ISSUE TITLE
`setup-handler` is deprecated for `mason-null-ls` ver 2.0

### ISSUE THREAD

**Issue by TonyWu20** [ayamir/nvimdots#651]
### Version confirmation

- [X] Confirm

### Following prerequisites

- [X] Confirm

### Neovim version

NVIM v0.9.0 Build type: Release LuaJIT 2.1.0-beta3

### Operating system/version

macOS 13.2.1

### Terminal name/version

wezterm 20230408-112425,69ae8472

### Branch info

main (Default/Latest)

### Fetch Preferences

SSH (use_ssh = true)

### How to reproduce the issue

Open any file with neovim and the error will prompt: 
```
Failed to run `config` for null-ls.nvim
.../.config/nvim/lua/modules/configs/completion/null-ls.lua:22: attempt to call field
 'setup_handlers' (a nil value)
```

### Expected behavior

No error.

### Additional information

https://github.com/jay-babu/mason-null-ls.nvim/releases/tag/v2.0.0 has the migration guide.

**Comment by CharlesChiuGit** [comment]
use branch 0.9
