### ISSUE TITLE
`nvim-cmp` invokes error messages with every key stroke

### ISSUE THREAD

**Issue by TonyWu20** [ayamir/nvimdots#653]
### Version confirmation

- [X] Confirm

### Following prerequisites

- [X] Confirm

### Neovim version

NVIM v0.9.0 Build type: Release LuaJIT 2.1.0-beta3

### Operating system/version

macOS 13.2.1

### Terminal name/version

wezterm 20230408-112425,69ae8472

### $TERM environment variable

xterm-256color

### Branch info

main (Default/Latest)

### Fetch Preferences

SSH (use_ssh = true)

### How to reproduce the issue

Press any key in a `rust` code file of mine will invoke the following messages:
```
Error executing vim.schedule lua callback: ...nywu/.config/nvim/lua/modules/configs/completion/cmp.lua:84: attempt to concatenate a nil value
```

### Expected behavior

The autocompletion window is invoked

### Actual behavior

```
Error executing vim.schedule lua callback: ...nywu/.config/nvim/lua/modules/configs/completion/cmp.lua:84: attempt to concatenate a nil value
```
with every key stroke pressed

### Additional information

@LucasTavaresA reported this issue and updates the correct settings: [get_vim_item concatenating nil value](https://github.com/hrsh7th/nvim-cmp/issues/1335#Actual-behavior)
The key modification is:
```
kind.menu = "    (" .. (strings[2] or "") .. ")"
```

**Comment by CharlesChiuGit** [comment]
use branch 0.9
