### ISSUE TITLE
How to bring word under cursor into string search popup window?

### ISSUE THREAD

**Issue by goodpaperman** [ayamir/nvimdots#656]
### Feature description

Hi, guys
I am confused with search word， in old style，I can search word under the cursor , with new leader+f+w this don't work, anyone tell me how to ?

![leader-f-w-search-under-word-5fps](https://user-images.githubusercontent.com/8522640/231710112-a41f38b9-d660-4805-b141-f69614321940.gif)

### Additional information

Kitty + neovim 0.8.1

**Comment by goodpaperman** [comment]
in another word, how can I open search popup window with word under cursor filled in ?

**Comment by Jint-lzxy** [comment]
https://github.com/ayamir/nvimdots/pull/488
