### ISSUE TITLE
Install Issue

### ISSUE THREAD

**Issue by GayStarc** [ayamir/nvimdots#663]
我在执行“if command -v curl >/dev/null 2>&1; then
    bash -c "$(curl -fsSL https://raw.githubusercontent.com/ayamir/nvimdots/HEAD/scripts/install.sh)"
else
    bash -c "$(wget -O- https://raw.githubusercontent.com/ayamir/nvimdots/HEAD/scripts/install.sh)"
fi”
这段命令时，命令行报错“curl: (7) Failed to connect to raw.githubusercontent.com port 443 after 11 ms: Connection refused”
要怎么解决呢？

**Comment by ayamir** [comment]
Use terminal proxy to bypass gfw.

**Comment by GayStarc** [comment]
I used the teriminal proxy(ALL_PROXY)
But it replied "curl: (22) The requested URL returned error: 400" 
How Can I fix it?
Thank you for your help.

发件人：ayamir ***@***.***>
发送日期：2023-04-17 09:57:37
收件人：ayamir/nvimdots ***@***.***>
抄送人：GayStarc ***@***.***>,Author ***@***.***>
主题：Re: [ayamir/nvimdots] Install Issue (Issue #663)

Use terminal proxy to bypass gfw.

**Comment by ayamir** [comment]
`ALL_PROXY` can't replace `HTTP_PROXY` and `HTTPS_PROXY`. Set all of them.
```shell
export HTTP_PROXY=<protocol>://<server>:<port>
export HTTPS_PROXY=<protocol>://<server>:<port>
export ALL_PROXY=<protocol>://<server>:<port>
```
What's more, `400` and any response number beginning with `4` meaning error from client.

**Comment by Jint-lzxy** [comment]
If you would like to check your proxy info:

Windows PowerShell:
```pwsh
Get-ItemProperty -Path 'Registry::HKCU\Software\Microsoft\Windows\CurrentVersion\Internet Settings'
```
macOS:
```sh
networksetup -getwebproxy Wi-Fi
```
Other \*nix-like systems:
```sh
env | grep -i proxy
```

**Comment by CharlesChiuGit** [comment]
Closed for no further response.
