### ISSUE TITLE
upgrade error

### ISSUE THREAD

**Issue by asaning** [ayamir/nvimdots#664]
### Feature description

the follow picture is the my environment
![image](https://user-images.githubusercontent.com/99789353/232374292-a942e82d-0a89-4ab9-a0a2-5b754afdc319.png)

1, i upgrade the nvim version to 0.9
2, when i execute the nvim cmd and then gives me error
![image](https://user-images.githubusercontent.com/99789353/232374402-daa17e0e-27e9-43d2-bc3f-9f6200c2ef4b.png)

### Additional information
i try it again

![image](https://user-images.githubusercontent.com/99789353/232374695-b8d7ba81-5173-4f84-93d9-814e51b8571d.png)

_No response_

**Comment by CharlesChiuGit** [comment]
seems like u'r installing a version without proper compile flags, try the official release

**Comment by asaning** [comment]
i download the nvim release version, the link is https://github.com/neovim/neovim/releases/tag/stable

**Comment by asaning** [comment]
i use the `brew install neovim` instead, it was resolved.
