### ISSUE TITLE
Lsps re-attach twice

### ISSUE THREAD

**Issue by CharlesChiuGit** [ayamir/nvimdots#666]
### Version confirmation

- [X] Confirm

### Following prerequisites

- [X] Confirm

### Neovim version

NVIM v0.10.0-dev-115+g240c41e1a

### Operating system/version

ubuntu 22.04

### Terminal name/version

gnome terminal

### $TERM environment variable

xterm256-color

### Branch info

main (Default/Latest)

### Fetch Preferences

SSH (use_ssh = true)

### Affected language servers

any

### How to reproduce the issue

1. Add below code to `core/event.lua`, which should clear the diagnostics for `.env`.
```lua
vim.api.nvim_create_autocmd("LspAttach", {
	pattern = ".env",
	callback = function(args)
		require("null-ls").disable({ "shellcheck" })
		local client = vim.lsp.get_client_by_id(args.data.client_id)
		if client.name == "null-ls" then
			local ns = vim.lsp.diagnostic.get_namespace(client.id)
			vim.diagnostic.disable(nil, ns)
			vim.lsp.buf_detach_client(args.buf, client.id)
		end
	end,
})
```
2. The diagnostics will be cleared at first, but soon the `null-ls` got re-attached  for some reason.

### Actual behavior

as above

### Support info

I'm recently start playing with docker and some docker projects will have an `.env` file which will be diagnosed by `shellcheck` from `null-ls`. However, `shellcheck` diagnosis is useless for `.env`, therefore I want to remove it.

Snippets of `.env`:
```env
# Mattermost settings
## Inside the container the uid and gid is 2000. The folder owner can be set with
## `sudo chown -R 2000:2000 ./volumes/app/mattermost`.
MATTERMOST_CONFIG_PATH=./volumes/app/mattermost/config
MATTERMOST_DATA_PATH=./volumes/app/mattermost/data
MATTERMOST_LOGS_PATH=./volumes/app/mattermost/logs
MATTERMOST_PLUGINS_PATH=./volumes/app/mattermost/plugins
MATTERMOST_CLIENT_PLUGINS_PATH=./volumes/app/mattermost/client/plugins
MATTERMOST_BLEVE_INDEXES_PATH=./volumes/app/mattermost/bleve-indexes
```

after applying above autocmd, the diagnosis disappeared for one second and it shows up again. 

Also it's still in the `LspInfo`
![圖片](https://user-images.githubusercontent.com/32497323/232711857-fb05fa7d-2b6a-4e6a-ab24-335c8877f32d.png)

### Logs

```console
`.local/state/nvim/lsp.log`:

[START][2023-04-18 16:03:18] LSP logging initiated
[WARN][2023-04-18 16:03:18] ...lsp/handlers.lua:137	"The language server copilot triggers a registerCapability handler despite dynamicRegistration set to false. Report upstream, this warning is harmless"
```

**Comment by CharlesChiuGit** [comment]
Side note: it seems like we can remove `neodim`, I comment out `neodim` and the dimming affect is still there.

**Comment by Jint-lzxy** [comment]
u can directly set another filetype for `*.env` to avoid this issue (based upon ur latest commit [`b372a34`](https://github.com/CharlesChiuGit/nvimdots.lua/commit/b372a34f29c26fc0d867e8da56cb40818367b197)):
```diff
diff --git a/lua/core/event.lua b/lua/core/event.lua
index be9c970..b572443 100644
--- a/lua/core/event.lua
+++ b/lua/core/event.lua
@@ -87,6 +87,8 @@ function autocmd.load_autocmds()
                        { "BufWritePre", "MERGE_MSG", "setlocal noundofile" },
                        { "BufWritePre", "*.tmp", "setlocal noundofile" },
                        { "BufWritePre", "*.bak", "setlocal noundofile" },
+                       -- disable bashls and shellcheck for *.env
+                       { "BufNewFile,BufRead", "*.env", "setlocal filetype=env" },
                        -- auto change directory
                        -- { "BufEnter", "*", "silent! lcd %:p:h" },
                },
```

> Side note: it seems like we can remove `neodim`, I comment out `neodim` and the dimming affect is still there.

This comes from LSP [semantic tokens](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#textDocument_semanticTokens) (`:Inspect` would probably give `@lsp.type.comment`). We need to keep `neodim` b/c not all servers support semantic tokens.

**Comment by CharlesChiuGit** [comment]
that's another workaround i'm considering. 

but i'm wondering if attaching lsp twice would take some performance hit?

**Comment by CharlesChiuGit** [comment]
> This comes from LSP semantic tokens (:Inspect would probably give @lsp.type.comment). We need to keep neodim b/c not all servers support semantic tokens.

got it! this make sense, or maybe we can further disable 'neodim' on some filetype to prevent rendering highlights twice?

**Comment by CharlesChiuGit** [comment]
> > ```diff
> > +  { "BufNewFile,BufRead", "*.env", "setlocal filetype=env" },
> > ```
> 
> That's another workaround I'm considering, but thanks for writing it in such a concise form!
> 
> However, the thing is that seems like a weird behavior when the LSPs got attached twice. Maybe it might cause a bit of performance hit?

I remember why I don't want to use this method, since all highlights are gone too lol.
![圖片](https://user-images.githubusercontent.com/32497323/232960622-13a28cb3-70f3-49b1-9f7d-2f10c9cc270a.png)

**Comment by CharlesChiuGit** [comment]
I think the ability to detach lsps from some files is still necessary.
For example, `docker-compose.yml` is a yaml file for sure, but `yamlls` is basically unusable when attaching to it.
But I still want it;s filetype to remain `yaml` b/c `docker_compose_language_service` need it to be `yaml`.[^1]

[^1]: https://github.com/neovim/nvim-lspconfig/blob/eddaef928c1e1dd79a96f5db45f2fd7f2efe7ea0/lua/lspconfig/server_configurations/docker_compose_language_service.lua#L13

**Comment by Jint-lzxy** [comment]
Ah, I've got it! Will check this issue after **! Refactor Treesitter highlights** (currently working on this, lots of thingy to do lol). We could have a new user command `:NullLsToggle <server>` using `null-ls`'s private API.

**Comment by Jint-lzxy** [comment]
> Perhaps we can further exclude `neodim` on some known filetypes which there's LSP has semantic tokens? In this way we can prevent rendering the highlights twice ( I know this might be too trivial to implement, totally understandable not doing it ).

This is possible, we could check if a server supports `textDocument.semanticTokens` before attaching `neodim` to that server.

**Comment by CharlesChiuGit** [comment]
> Ah, I've got it! Will check this issue after **! Refactor Treesitter highlights** (currently working on this, lots of thingy to do lol). We could have a new user command `:NullLsToggle <server>` using `null-ls`'s private API.

Understandable! Sometime I wonder how u have the knowledge to do all these lol
nvim super man! :superhero:

**Comment by CharlesChiuGit** [comment]
> > Perhaps we can further exclude `neodim` on some known filetypes which there's LSP has semantic tokens? In this way we can prevent rendering the highlights twice ( I know this might be too trivial to implement, totally understandable not doing it ).
> 
> This is possible, we could check if a server supports `textDocument.semanticTokens` before attaching `neodim` to that server.

I can work on that first.

**Comment by Jint-lzxy** [comment]
> Sometime I wonder how u have the knowledge to do all these lol

Probably b/c I read some of the fundamental documentations before lol (`:h starting`, `:h cmdline`, `:h options`, `:h events`, `:h api`, `:h lua`, `:h lsp`, and `:h quickref` as its name suggests, is a good place for concise reference).

_Help pages_ are always very _helpful_ 😆

**Comment by Jint-lzxy** [comment]
Reopening b/c I have a plan to implement this.

**Comment by CharlesChiuGit** [comment]
For those whom might interested:

After #872 got merged, I added an autocmd to Toggle those source when dealing with `.env`:

```lua
-- auto stop bashls, shellcheck and shfmt when editing docker-related files
	vim.api.nvim_create_autocmd("LspAttach", {
		pattern = {
			".env",
		},
		callback = function()
			vim.api.nvim_command([[LspStop 1 (bashls)]])
			vim.api.nvim_command([[NullLsToggle shellcheck]])
			vim.api.nvim_command([[NullLsToggle shfmt]])
		end,
	})
```
