### ISSUE TITLE
请问是否可以添加efm？

### ISSUE THREAD

**Issue by nkta3m** [ayamir/nvimdots#67]
感谢，这个用起来很快，不知是否可以添加efm？谢谢

**Comment by ayamir** [comment]
efm是啥？

**Comment by nkta3m** [comment]
efm-langserver，https://github.com/mattn/efm-langserver

可以配置自动格式化

**Comment by ayamir** [comment]
好吧，刚刚看到format.nvim已经废弃了

**Comment by ayamir** [comment]
19bbba3409b52644c376360ad5ac25de2a392470

**Comment by ayamir** [comment]
昨天和今天测试之后我发现这个并不能提供快速的异步格式化，先把main分支revert回原来版本了，之后再dev里面配置efm吧
