### ISSUE TITLE
ignore lazy-lock.json

### ISSUE THREAD

**Issue by arcthur** [ayamir/nvimdots#670]
### Version confirmation

- [X] Confirm

### Following prerequisites

- [X] Confirm

### Neovim version

NVIM 0.8

### Operating system/version

macOS

### Terminal name/version

iTerm2

### Branch info

main (Default/Latest)

### Fetch Preferences

SSH (use_ssh = true)

### How to reproduce the issue

I think the project need ignore lazy-lock.json into gitignore file. when I update the module, the lazy-lock.json file will be update too so that I cant pull the project update directly.

### Expected behavior

ignore lazy-lock.json in the project

**Comment by aarnphm** [comment]
https://github.com/ayamir/nvimdots/discussions/570

**Comment by aarnphm** [comment]
Once again, echo @ayamir it is necessary to include lazy-lock.json here. You can do `--assume-unchanged` to the lazy-lock.json to keep up to date with the main repo.

Usually I find just watching for newer commits work for things that users want to update separately.
