### ISSUE TITLE
manully open welcome page

### ISSUE THREAD

**Issue by Saafo** [ayamir/nvimdots#671]
### Feature description

When tabs are already opened, it seems there is no way to open the initial welcome page again excepting close all tabs and reopen nvim.

Maybe we can open welcome page in these ways:

* set up a key map to open the welcome page
* when close last tab by click "x" or meta+q, open the welcome page instead of open an empty editor.

**Comment by CharlesChiuGit** [comment]
`:Alpha`

u can set a keymap as u like.
