### ISSUE TITLE
Error when opening files

### ISSUE THREAD

**Issue by cknyakina** [ayamir/nvimdots#672]
### Version confirmation

- [X] Confirm

### Following prerequisites

- [X] Confirm

### Neovim version

Latest Nvim stable version with this configs purely.

### Operating system/version

Archlinux

### Terminal name/version

Alacritty/konsole latest versions

### Branch info

main (Default/Latest)

### Fetch Preferences

SSH (use_ssh = true)

### How to reproduce the issue

When I open Neovim, I get no error.

However let's say I open a file with nvim I get the error attached in the screenshot. still works but would love to get it working.
![image](https://user-images.githubusercontent.com/81164719/233442552-1e843e6e-7497-41f4-b54c-d829c74e29cf.png)

### Expected behavior

No error when opening a file via neovim

**Comment by CharlesChiuGit** [comment]
your config is not up-to-date, we add a new setting in `core/settings.lua`.
also u should use the 0.9 branch.

**Comment by cknyakina** [comment]
True, I had not updated the _.nvim configs_ but only nvim lazy plugins. Thank you. All works fine now. And yes, my version is 0.9.0-1. Thank you and I truly enjoy this setup.
