### ISSUE TITLE
Uncontrolled file searching scope while using telescope

### ISSUE THREAD

**Issue by Saton-anger** [ayamir/nvimdots#677]
### Version confirmation

- [X] Confirm

### Following prerequisites

- [X] Confirm

### Neovim version

NVIM v0.9.0

### Operating system/version

macOS 13.3.1

### Terminal name/version

iTerm2 Build 3.4.18

### Branch info

main (Default/Latest)

### Fetch Preferences

HTTPS (use_ssh = false)

### How to reproduce the issue

1. Open iTerm2
2. `cd ./Desktop/ml` (basically any folder under the home folder)
3. `nvim`: enter the neovim
4. open nvim-tree by press <C-n>
5. choose a file, and press 'o'

### Expected behavior

It should open the file under the 'ml' folder

### Actual behavior

However, it open all the folders under the home folder like the following figures
<img width="310" alt="截屏2023-04-21 22 56 33" src="https://user-images.githubusercontent.com/79832629/233668328-f91b4065-f56c-4da8-941d-70220b45d986.png">

### Additional information

In that case, when I try to find some files under the 'ml' folder, it actually search the files from the home folders, the scope is significantly large...

**Comment by Jint-lzxy** [comment]
I'm sorry but I can't _quite_ understand what you mean - is your issue related to `telescope` or `nvim-tree` _(or you reported both at the same time)_? To clarify:
- By saying "choose a file", do you mean "to place the cursor on that file"?
- You expect the behavior to be "It should open the file under the 'ml' folder" but the actual behavior is "it open all the folders under the home folder" - this shouldn't be what `api.node.open.edit` did (there's no correlation between your "expected behavior" and "actual behavior"). Was the file _itself_ opened correctly _(a new buffer was created for this)_? And by saying "open all the folders under the home folder" do you imply the file tree _was expanded_ **after** opening that file?
- Before opening that file, did the file tree _only_ focus on the current working directory?

The problem likely relates to [project.nvim](https://github.com/ahmedkhalf/project.nvim), but we need more information to determine the root cause of this issue.

**Comment by Saton-anger** [comment]
**Sorry for the confusing description, I will try to clarify it:**

- **For "By saying "choose a file", do you mean "to place the cursor on that file"?", the answer is yes.**

- **Let me clarify the detailed process:**

1. First, I just entered the target project  "machine_learning_..."

<img width="518" alt="截屏2023-04-22 01 13 19" src="https://user-images.githubusercontent.com/79832629/233698134-85257ea1-7bdc-4b77-8626-756e018e3199.png">

2. Then I just typed the `nvim` to open the IDE and typed `<C-n>` to open the nvim-tree, it worked just fine 
<img width="1241" alt="截屏2023-04-22 01 15 49" src="https://user-images.githubusercontent.com/79832629/233698748-4d1e67f0-8618-45e2-b407-7977476c9c63.png">

3.  However, when I place the cursor on the `vim_teach.py` file under the 'tech' folder, and type `o` to open it, the file tree just change to the root tree, and I guess it re-direct me to the root directory...
<img width="278" alt="截屏2023-04-22 01 16 32" src="https://user-images.githubusercontent.com/79832629/233700804-b50fa35d-08dc-4463-a617-9e6dd8fb552a.png">

<img width="257" alt="截屏2023-04-22 01 17 38" src="https://user-images.githubusercontent.com/79832629/233699473-8f208429-470b-4f7d-8ff7-8003e52519d9.png">
<img width="254" alt="截屏2023-04-22 01 18 00" src="https://user-images.githubusercontent.com/79832629/233699564-1d6ffe07-0861-4e3e-9d1a-678d8be4ac25.png">

4. What's more, in that case, when I trying to search some specific files using the keybinding `<leader>ff`, it actually did not search the files under the "current" project, the 'machine_learning_...' project, but actually search the files under the home directory 'apple', which actually contain more 900,000 files ...

- **For "Before opening that file, did the file tree only focus on the current working directory?", the answer is yes.**

**Comment by Saton-anger** [comment]
Also, the process I have just shown you is on a terminal called 'Warp', but I meet the same problem on iTerm2.

**Comment by nkta3m** [comment]
Change folder use space fz

**Comment by Jint-lzxy** [comment]
@Saton-anger Will this issue disappear after u change `manual_mode` to `true`? Looks like the root directory was not correctly recognized by [project.nvim](https://github.com/ahmedkhalf/project.nvim): _(Note: This is not a workaround, it's only for debugging purposes)_

https://github.com/ayamir/nvimdots/blob/a0dbcd9eed6f199c14c51e9e439f0d22a6b4ae41/lua/modules/configs/tool/project.lua#L3

**Comment by CharlesChiuGit** [comment]
I think this is expected. 
1. Your `machine_learning_py` is not recognized by `project.nvim`'s pattern which is used for searching for project/folder root.
2.  > However, when I place the cursor on the `vim_teach.py` file under the 'tech' folder, and type `o` to open it, the file tree just change to the root tree, and I guess it re-direct me to the root directory...

This is b/c the `nvim-tree` will refresh after u open a file, combining with the previous reason, `nvim-tree` will certainly redirect u to the project root which is your home folder.

That u can do:
1. As @Jint-lzxy said, set `manual_mode = true`.
2. Add new patterns for `project.nvim` to recognize your current folder as a "project".

**Comment by Saton-anger** [comment]
Thanks a lot for all your guys' help, set `manual_mdoe = true` just works for me, and it also help me reduce the time takes to search for files under the current project, I appreciate that.
