### ISSUE TITLE
Adapt to nvim-web-devicons API changes

### ISSUE THREAD

**Issue by Saafo** [ayamir/nvimdots#681]
### Version confirmation

- [X] Confirm

### Following prerequisites

- [X] Confirm

### Neovim version

0.9.0

### Operating system/version

macOS 13.2.1

### Terminal name/version

Warp

### $TERM environment variable

xterm-256color

### Branch info

main (Default/Latest)

### Fetch Preferences

HTTPS (use_ssh = false)

### How to reproduce the issue

1. Update all dependencies in Lazy (maybe only update `nvim-web-devicons` is enough)
2. Start nvim, Will see the warning:

```
show_buffer_default_icon is deprecated, use get_element_icon = function(buf) return require('nvim-web-devicons').get_icon(..., {de
fault = false}) instead.
This feature will be removed in bufferline version 4.0.0
```

### Expected behavior

no warning

**Comment by CharlesChiuGit** [comment]
use 0.9 branch
