### ISSUE TITLE
How to add a new colorscheme

### ISSUE THREAD

**Issue by mrdengbo** [ayamir/nvimdots#691]
### Version confirmation

- [X] Confirm

### Following prerequisites

- [X] Confirm

### Neovim version

nvim 0.9

### Operating system/version

macos 12.6.1

### Terminal name/version

tabby

### $TERM environment variable

xterm-color256

### Branch info

main (Default/Latest)

### Fetch Preferences

SSH (use_ssh = true)

### How to reproduce the issue

I configured my customize plugin according  the [wiki](https://github.com/ayamir/nvimdots/wiki/Usage);

Proceed as follows：
1. add one-nvim.lua in the `.config/nvim/lua/modules/configs/custom`,  as below：
```lua
return function()
    require("one-nvim").setup()
end
```
2. and I add custom.lua in plugins dir, as below:
```lua
local custom = {}

custom["Th3Whit3Wolf/one-nvim"] = {
	lazy = true,
	event = "BufRead",
	config = require("custom.one-nvim"), 
}

return custom
```
3. then I restart neovim, but it runs wrong, as follow:

> Failed to run `config` for one-nvim
> ...gbo/.config/nvim/lua/modules/configs/custom/one-nvim.lua:2: attempt to call field 'setup' (a nil value)
> stacktrace:
>   - ~/.config/nvim/lua/modules/configs/custom/one-nvim.lua:2 _in_ **config**
>   - ~/.config/nvim/lua/core/init.lua:164 _in_ **load_core**
>   - ~/.config/nvim/lua/core/init.lua:167
>   - ~/.config/nvim/init.lua:2
  
Can anyone help me?

### Expected behavior

neovim runs no errors

**Comment by Jint-lzxy** [comment]
This plugin does not provide the `setup()` API - in fact, it only provides one global option `one_nvim_transparent_bg`. You should do the following to use this colorscheme:
**Note: Please use the `0.9` branch before the migration (#627) is completed**.
1. `plugins/custom.lua`
```lua
local custom = {}

custom["Th3Whit3Wolf/one-nvim"] = {
	lazy = true,
	config = require("custom.one-nvim"), 
}

return custom
```
2. `configs/custom/one-nvim.lua`
```lua
return function()
	vim.g.one_nvim_transparent_bg = require("core.settings").transparent_background
end
```

Then in `core/settings.lua`, you can make changes to the following options:
1. Change `colorscheme` to `"one-nvim"`:
https://github.com/ayamir/nvimdots/blob/e15ac1cabe972e907940b76a23b7eb2c22361aab/lua/core/settings.lua#L30-L33

2. Change `transparent_background` to `true` if your terminal has transparent background.
https://github.com/ayamir/nvimdots/blob/e15ac1cabe972e907940b76a23b7eb2c22361aab/lua/core/settings.lua#L35-L37

**Comment by dengbo11** [comment]
Thank you so much!
