### ISSUE TITLE
color confusion

### ISSUE THREAD

**Issue by maobai405** [ayamir/nvimdots#694]
### Version confirmation

- [X] Confirm

### Following prerequisites

- [X] Confirm

### Neovim version

0.9

### Operating system/version

12.0.1

### Terminal name/version

alacritty/0.11

### Branch info

main (Default/Latest)

### Fetch Preferences

HTTPS (use_ssh = false)

### How to reproduce the issue

Why does CMP's window have this color? It's not just CMP. My black and # 000000 all turn orange
<img width="383" alt="image" src="https://user-images.githubusercontent.com/121467933/235277666-a1c5a6c6-e067-4911-be03-5cfbde7e5a31.png">
<img width="525" alt="image" src="https://user-images.githubusercontent.com/121467933/235277419-9198276a-8ed5-4278-b46f-b9d683e731bd.png">
<img width="1505" alt="image" src="https://user-images.githubusercontent.com/121467933/235277474-af1b44ca-f456-4754-8ba4-ce4e60045d79.png">

### Expected behavior

Black shows normal

**Comment by CharlesChiuGit** [comment]
it's probably your terminal setting, try another terminal emulator without any config.

**Comment by Jint-lzxy** [comment]
What do you see if you execute the following snippet:
```sh
#!/usr/bin/env bash

printf "|039| \033[39mDefault \033[m  |049| \033[49mDefault \033[m  |037| \033[37mLight gray \033[m     |047| \033[47mLight gray \033[m\n"
printf "|030| \033[30mBlack \033[m    |040| \033[40mBlack \033[m    |090| \033[90mDark gray \033[m      |100| \033[100mDark gray \033[m\n"
printf "|031| \033[31mRed \033[m      |041| \033[41mRed \033[m      |091| \033[91mLight red \033[m      |101| \033[101mLight red \033[m\n"
printf "|032| \033[32mGreen \033[m    |042| \033[42mGreen \033[m    |092| \033[92mLight green \033[m    |102| \033[102mLight green \033[m\n"
printf "|033| \033[33mYellow \033[m   |043| \033[43mYellow \033[m   |093| \033[93mLight yellow \033[m   |103| \033[103mLight yellow \033[m\n"
printf "|034| \033[34mBlue \033[m     |044| \033[44mBlue \033[m     |094| \033[94mLight blue \033[m     |104| \033[104mLight blue \033[m\n"
printf "|035| \033[35mMagenta \033[m  |045| \033[45mMagenta \033[m  |095| \033[95mLight magenta \033[m  |105| \033[105mLight magenta \033[m\n"
printf "|036| \033[36mCyan \033[m     |046| \033[46mCyan \033[m     |096| \033[96mLight cyan \033[m     |106| \033[106mLight cyan \033[m\n"
```

`nvim` usually uses colors within the code range `030` - `046`.

**Comment by maobai405** [comment]
![Uploading image.png…

> What do you see if you execute the following snippet:如果执行以下代码段，会看到什么：
> 
> ```shell
> #!/usr/bin/env bash
> 
> printf "|039| \033[39mDefault \033[m  |049| \033[49mDefault \033[m  |037| \033[37mLight gray \033[m     |047| \033[47mLight gray \033[m\n"
> printf "|030| \033[30mBlack \033[m    |040| \033[40mBlack \033[m    |090| \033[90mDark gray \033[m      |100| \033[100mDark gray \033[m\n"
> printf "|031| \033[31mRed \033[m      |041| \033[41mRed \033[m      |091| \033[91mLight red \033[m      |101| \033[101mLight red \033[m\n"
> printf "|032| \033[32mGreen \033[m    |042| \033[42mGreen \033[m    |092| \033[92mLight green \033[m    |102| \033[102mLight green \033[m\n"
> printf "|033| \033[33mYellow \033[m   |043| \033[43mYellow \033[m   |093| \033[93mLight yellow \033[m   |103| \033[103mLight yellow \033[m\n"
> printf "|034| \033[34mBlue \033[m     |044| \033[44mBlue \033[m     |094| \033[94mLight blue \033[m     |104| \033[104mLight blue \033[m\n"
> printf "|035| \033[35mMagenta \033[m  |045| \033[45mMagenta \033[m  |095| \033[95mLight magenta \033[m  |105| \033[105mLight magenta \033[m\n"
> printf "|036| \033[36mCyan \033[m     |046| \033[46mCyan \033[m     |096| \033[96mLight cyan \033[m     |106| \033[106mLight cyan \033[m\n"
> ```
> 
> `nvim` usually uses colors within the code range `030` - `046`。 `nvim` 通常使用代码范围 `030` - `046` 内的颜色。

<img width="1201" alt="image" src="https://user-images.githubusercontent.com/121467933/235286329-52fa7191-0a24-46a8-b654-9b77c08541e7.png">
This is my output

**Comment by maobai405** [comment]
> 

Using Alacritty, I tried switching to ITERM2 to display the colors correctly after it was run, but wasn't sure which setting was causing it

**Comment by CharlesChiuGit** [comment]
> Using Alacritty

No `$TERM` is not asking what terminal u r using. please refer to [this](https://www.gnu.org/software/gettext/manual/html_node/The-TERM-variable.html).

>  I tried switching to ITERM2 to display the colors correctly after it was run, but wasn't sure which setting was causing it

So the problem is apparently your alacritty config, which is sth u need to solve by yourself.

**Comment by Jint-lzxy** [comment]
u may follow these steps:
1. Use other [builtin colorschemes](https://github.com/alacritty/alacritty-theme) to check if this is your personal config's issue.
2. Place your cursor on the text with incorrect background _(e.g., `#000000`)_, type `:Inspect`, and remember the first highlight group `<hl>` under `Extmarks` _(it should end in `colorizer`)_. Enter `:hi <hl>` and check if `guibg` is set to `#000000` (black _literally_). If it is _indeed_ `#000000`, then this issue is specific to your terminal emulator. Please open this issue [in the upstream repo](https://github.com/alacritty/alacritty/issues/new) instead.

**Comment by maobai405** [comment]
Okay, thanks
