### ISSUE TITLE
Catppuccin theme supported alpha

### ISSUE THREAD

**Issue by huge-pancake** [ayamir/nvimdots#696]
### Version confirmation

- [X] Confirm

### Following prerequisites

- [X] Confirm

### Neovim version

NVIM v0.10.0-dev-186+g191e8b4062

### Operating system/version

Archlinux

### Terminal name/version

foot version: 1.14.0 +pgo +ime +graphemes -assertions

### $TERM environment variable

foot

### Branch info

main (Default/Latest)

### Fetch Preferences

SSH (use_ssh = true)

### How to reproduce the issue

1. `:Lazy`
2. `U` to update
3. relaunch NeoVim

### Expected behavior

alpha's color renders normally as `modules/utils/init.lua:193`

### Actual behavior

alpha's color rendered by catppuccin/nvim

### Additional information

refer to [this commit](https://github.com/catppuccin/nvim/commit/48b3c67d49b3c7f17a277ae17c5311ed4f0a2ab9)

to solve, just delete code at `modules/utils/init.lua:193`

**Comment by Jint-lzxy** [comment]
https://github.com/ayamir/nvimdots/pull/695.

**Comment by Jint-lzxy** [comment]
We are using custom highlight groups b/c not every user uses catppuccin, and we would like to keep dashboard's colors similar.

**Comment by nullchilly** [comment]
The point is your custom highlight groups got override by catppuccin 

https://github.com/ayamir/nvimdots/blob/f5198835261299ea45f494789dcd6fe7b2d2eedd/lua/modules/utils/init.lua#L193-L201

**Comment by huge-pancake** [comment]
so we should add `alpha = false` in catppuccin config right?

**Comment by Jint-lzxy** [comment]
> so we should add `alpha = false` in catppuccin config right?

That's it 😄 Just added a commit (https://github.com/ayamir/nvimdots/commit/3795d5e66a9732bdb78d37706128e916db04a1b4) to avoid further confusion.
