### ISSUE TITLE
Vim indent line

### ISSUE THREAD

**Issue by hsheikhali1** [ayamir/nvimdots#7]
How did you get your indent line to highlight the start of a code block and end at the end of a code block?

**Comment by ayamir** [comment]
https://github.com/ayamir/nvimdots/blob/71f562be753651a55ba3f15a7336407ab85b6b87/lua/modules/ui/config.lua#L170
From this line to L174.

**Comment by hsheikhali1** [comment]
I have that setting as true but it doesn't highlight anything :/

**Comment by hsheikhali1** [comment]
Here is what mine looks like with that setting turned on.

<img width="1587" alt="Screen Shot 2021-07-30 at 10 04 09 AM" src="https://user-images.githubusercontent.com/14851850/127664723-3447f9b2-437e-4726-999a-7dc20256df7c.png">

**Comment by hsheikhali1** [comment]
so it works for all file types except typescript/javascript.

**Comment by ayamir** [comment]
because this effect realized through treesitter, fixed at [this].(https://github.com/ayamir/nvimdots/commit/5f56d71718c995029e939b71166c1a2c38221331)
![image](https://user-images.githubusercontent.com/61657399/127729756-6b5b3454-0816-4a26-a32e-0ce5ed7ae740.png)
