### ISSUE TITLE
cmp.lua failed to index field 'cmp' (a nil value)

### ISSUE THREAD

**Issue by csyJoy** [ayamir/nvimdots#700]
### Version confirmation

- [x] Confirm

### Following prerequisites

- [X] Confirm

### Neovim version

NVIM v0.10.0-dev-134+gab2811746

### Operating system/version

macOS 13.3.1

### Terminal name/version

iTerms2 Build 3.4.18

### Branch info

main (Default/Latest)

### Fetch Preferences

SSH (use_ssh = true)

### How to reproduce the issue

1. switch to the insert mode and type a character
2. the error occurs
<img width="1789" alt="image" src="https://user-images.githubusercontent.com/58020450/235649424-802f0ddd-2e9a-400b-8f01-0785ea544de1.png">

### Expected behavior

this error doesn't occur

### Additional information

I find that this problem is caused by a filter callback function in `cmp.setup` added in #697.
```lua
entry_filter = function(entry)
 	local ignore_list = {
 		"Error",
 		"Comment",
 	}
 	local kind = entry:get_completion_item().cmp.kind_text
 	return not vim.tbl_contains(ignore_list, kind)
 end,
```
I changed one line code from `local kind = entry:get_completion_item().cmp.kind_text` to `local kind = entry:get_completion_item().kind` and this error disappeared.
but I still wonder whether such a change will have some other side effects since I don't find the document of the function `get_completion_item` and its return value, I would be grateful if someone could give me the location this document and tell me whether my change is correct or not.

**Comment by CharlesChiuGit** [comment]
lazy sync

**Comment by csyJoy** [comment]
sorry for the mistake, I should do lazy sync at once.
