### ISSUE TITLE
Icons not fully support Nerd Font 3.0

### ISSUE THREAD

**Issue by AngelontheRoad** [ayamir/nvimdots#711]
### Feature description

Some icons in Nerd Font 3.0 may be incompatible with old version. For example, [lualine #1035](https://github.com/nvim-lualine/lualine.nvim/pull/1035)

**Comment by Jint-lzxy** [comment]
https://github.com/ayamir/nvimdots/pull/447. Excerpt from draft release:

> This release mainly targeted [Release v3.0.0 · ryanoasis/nerd-fonts](https://github.com/ryanoasis/nerd-fonts/releases/tag/v3.0.0). 
> - Please update your installed nerd font(s) to v3.0.0 so that the icons can be rendered properly. 
> - **Starting from v3.0.0, please use the `Mono` variant (Nerd Font Mono _or_ NFM) as your GUI font.**

**Comment by Jint-lzxy** [comment]
We do not intend to maintain backward compatibility here as it's unusual to find users who can't update their installed fonts.

**Comment by AngelontheRoad** [comment]
Wow, It's incredible you have prepared a Pr for this. Thanks a lot!
