### ISSUE TITLE
error when use `K` to show hover doc

### ISSUE THREAD

**Issue by Lonjiazeng** [ayamir/nvimdots#712]
### Version confirmation

- [X] Confirm

### Following prerequisites

- [X] Confirm

### Neovim version

NVIM v0.9.0

### Operating system/version

archlinux

### Terminal name/version

WezTerm

### Branch info

main (Default/Latest)

### Fetch Preferences

SSH (use_ssh = true)

### How to reproduce the issue

press `K`

### Expected behavior

toggle hover doc

### Actual behavior

![image](https://user-images.githubusercontent.com/76612231/236592983-9cc43512-42b4-4d28-a7e6-843852556ee6.png)

**Comment by CharlesChiuGit** [comment]
what's the language u r using?

it seems like related to treesitter, so i guess maybe sth is wrong with the treesitter parser? like an invalid installation of the parser?

**Comment by Lonjiazeng** [comment]
> what's the language u r using?
> 
> it seems like related to treesitter, so i guess maybe sth is wrong with the treesitter parser? like an invalid installation of the parser?

python, so how can i fix it?
thx

**Comment by ayamir** [comment]
`:checkhealth nvim-treesitter`

**Comment by Lonjiazeng** [comment]
![image](https://user-images.githubusercontent.com/76612231/236600187-f3715572-287a-496d-9a7b-5e9f4568003a.png)
Here is the output.
Btw, I tried to use `K` to get doc after that,  there is  no error now.

**Comment by CharlesChiuGit** [comment]
so is it gd to close the issue?
