### ISSUE TITLE
`<leader>fp <C-b>` throw error

### ISSUE THREAD

**Issue by lcoder** [ayamir/nvimdots#714]
### Version confirmation

- [X] Confirm

### Following prerequisites

- [X] Confirm

### Neovim version

NVIM v0.9.0-LuaJIT 2.1.0-beta3

### Operating system/version

Mac OS13.2.1 (22D68)

### Terminal name/version

iTerm2 Build 3.4.19

### Branch info

main (Default/Latest)

### Fetch Preferences

SSH (use_ssh = true)

### How to reproduce the issue

- open nvim and the`<leader>fp`
- [inser mode] press [`<C-b>`](https://github.com/nvim-telescope/telescope-project.nvim#default-mappings-insert-mode) browse inside files within your project
- 
<img width="1287" alt="image" src="https://user-images.githubusercontent.com/5225853/236603145-cf557bf1-3718-4cd0-ad34-96290e58cb9a.png">

### Expected behavior

can browse inside files within current project

### Actual behavior

throw error

**Comment by ayamir** [comment]
Can confirm, maybe just from upstream.

**Comment by lcoder** [comment]
other question, `<C a>` also not working, keep silent
<img width="1116" alt="image" src="https://user-images.githubusercontent.com/5225853/236623683-e81c4c9f-2595-40a9-a4ec-3f7704e45c82.png">

`insert mode`，press`<C a>` the cursor jumps to front

**Comment by ayamir** [comment]
Probably because `<C-a>` has been captured by your terminal or other program.

**Comment by ayamir** [comment]
Oh, you refer to [telescope-project.nvim](https://github.com/nvim-telescope/telescope-project.nvim), but what exactly used in `nvimdots` is [project.nvim](https://github.com/ahmedkhalf/project.nvim).

**Comment by lcoder** [comment]
well, how can i create a new project with `nvimdots` seems not implemented 🤔

<img width="743" alt="image" src="https://user-images.githubusercontent.com/5225853/236624985-9d16dcb3-e9dd-4593-b386-394818bee696.png">

**Comment by CharlesChiuGit** [comment]
U can never do that. 
`add project` is not the same as `create project`. `add project` means add a project to the list, the project needs to existed first.
Check https://github.com/ahmedkhalf/project.nvim to understand what's "project".

**Comment by ayamir** [comment]
> well, how can i create a new project with `nvimdots` seems not implemented 🤔
> 
> <img alt="image" width="743" src="https://user-images.githubusercontent.com/5225853/236624985-9d16dcb3-e9dd-4593-b386-394818bee696.png">

It's time to update wiki now lol.

**Comment by ayamir** [comment]
The project is detected by `project.nvim` automatically: https://github.com/ahmedkhalf/project.nvim#pattern-matching
No need to create it manually.
