### ISSUE TITLE
Cannot render icon for "file history" and "file find" when upgrade to nerd font 3.0

### ISSUE THREAD

**Issue by Saafo** [ayamir/nvimdots#716]
### Version confirmation

- [X] Confirm

### Following prerequisites

- [X] Confirm

### Neovim version

0.9.0

### Operating system/version

macOS 13.2.1

### Terminal name/version

Warp/iTerm2

### $TERM environment variable

xterm-256color

### Branch info

main (Default/Latest)

### Fetch Preferences

SSH (use_ssh = true)

### How to reproduce the issue

1. upgrade nerd font to 3.0
2. open the alpha page

### Expected behavior

correctly render the icons

### Actual behavior

<img width="408" alt="image" src="https://user-images.githubusercontent.com/46736350/236608666-2253e61a-684c-4ad3-9185-304a1d600d7b.png">

### Additional information

maybe it's related to nerd font's [3.0 breaking change](https://github.com/ryanoasis/nerd-fonts/releases/tag/v3.0.0)

**Comment by ayamir** [comment]
WIP: https://github.com/ayamir/nvimdots/pull/447
