### ISSUE TITLE
modu le 'catppuccin.main' not found

### ISSUE THREAD

**Issue by henryyan** [ayamir/nvimdots#717]
### Version confirmation

- [X] Confirm

### Following prerequisites

- [X] Confirm

### Neovim version

v0.9.0

### Operating system/version

macOS 13.3.1 (a) 

### Terminal name/version

iTerm2 Build 3.4.19

### Branch info

main (Default/Latest)

### Fetch Preferences

HTTPS (use_ssh = false)

### How to reproduce the issue

![image](https://user-images.githubusercontent.com/1219399/236617417-76106249-7961-46d9-9a7f-f514c53e7806.png)

### Expected behavior

all will be ok

**Comment by ayamir** [comment]
Maybe just network causes it.
```
rm -rf ~/.local/share/nvim/site/lazy
```
Then `nvim`.

**Comment by henryyan** [comment]
> Does it appear on a fresh installation? Maybe poor network causes it. The simplest way is just remove all of plugins and reopen `nvim`.
> 
> ```shell
> rm -rf ~/.local/share/nvim/site/lazy/
> nvim
> ```

All right, it's ready to work.
