### ISSUE TITLE
High CPU usage and exit issue of Jedi-language-server

### ISSUE THREAD

**Issue by Tgist1024** [ayamir/nvimdots#721]
### Version confirmation

- [X] Confirm

### Following prerequisites

- [X] Confirm

### Neovim version

NVIM v0.9.0 Build type: Release LuaJIT 2.1.0-beta3     system vimrc file: "$VIM/sysinit.vim"   fall-back for $VIM: "/usr/share/nvim"

### Operating system/version

Arch Linux 6.3.1-arch1-1

### Terminal name/version

kitty 0.28.1

### Branch info

main (Default/Latest)

### Fetch Preferences

SSH (use_ssh = true)

### Affected language servers

jedi-language-server

### How to reproduce the issue

1. Open a Python file or project.
2. Wait for lsp works.
3. Exit.
4. Repeat several times.
5. Open process panel tools like `top` and the problem shows.
![image](https://user-images.githubusercontent.com/101801875/236683767-be698526-7e18-47fb-902d-748c0ed1cf67.png)

### Actual behavior

The CPU usage of Jedi language server is extremely high, and it does not automatically exit when exiting neovim. If I repeatedly open and close Python files, multiple instances of Jedi language server will appear, causing significant CPU usage. As this issue affects user experience and computer performance, it is suggested to fix it.

### Support info

:LspInfo
```
 Language client log: /home/liu/.local/state/nvim/lsp.log
 Detected filetype:   python
 
 3 client(s) attached to this buffer: 
 
 Client: pyright (id: 1, bufnr: [1])
 	filetypes:       python
 	autostart:       true
 	root directory:  Running in single file mode.
 	cmd:             pyright-langserver --stdio
 
 Client: jedi_language_server (id: 2, bufnr: [1])
 	filetypes:       python
 	autostart:       true
 	root directory:  Running in single file mode.
 	cmd:             jedi-language-server
 
 Client: null-ls (id: 3, bufnr: [1])
 	filetypes:       python, cpp, c, css, scss, sh, markdown, javascriptreact, vue, typescript, javascript, typescriptreact, html, yaml, rust, vim, lua, luau
 	autostart:       false
 	root directory:  /home/liu/Documents/code/web/mysite
 	cmd:             <function>
 
 Configured servers list: jedi_language_server, rust_analyzer, lua_ls, dartls, clangd, html, bashls, pyright, jsonls
```

**Comment by ayamir** [comment]
Does it have to do with the uninstalled `pyright`?

**Comment by Tgist1024** [comment]
> Does it have to do with the uninstalled `pyright`?

I just noticed that the project replaced pyright with jedi-language-server, but after uninstalling pyright by mason, the situation remains the same.

**Comment by ayamir** [comment]
Never encountered this, you can remove jedi for yourself and try others like `pylsp`. Need more issues about it to decide.

**Comment by Tgist1024** [comment]
Well... I found that using `:wq` to save and exit leads to the issue I mentioned while using `:q` does not. 
I think the issue might be caused by code formatting. You can try again and see if it occurs.

**Comment by ayamir** [comment]
OK, I captured this and it should be normal because `pylsp` also have this issue. 
It's reasonable that lsp need some time to stop.
<img width="1262" alt="image" src="https://user-images.githubusercontent.com/61657399/236775337-5e46c3df-c232-4335-85c8-5c2f22627d7a.png">
<img width="1266" alt="image" src="https://user-images.githubusercontent.com/61657399/236775053-e1014558-1b8f-4693-af7d-bd671edec17f.png">
But indeed jedi has abnormal high CPU load about a few seconds.
<img width="1266" alt="image" src="https://user-images.githubusercontent.com/61657399/236776611-3ad2b6e8-fc1f-4c64-9d49-6daaf8b7f48e.png">
