### ISSUE TITLE
get error when using nvim in rust

### ISSUE THREAD

**Issue by Lonjiazeng** [ayamir/nvimdots#727]
### Version confirmation

- [X] Confirm

### Following prerequisites

- [X] Confirm

### Neovim version

NVIM v0.9.0

### Operating system/version

arch

### Terminal name/version

WezTerm

### $TERM environment variable

xterm-256color

### Branch info

main (Default/Latest)

### Fetch Preferences

SSH (use_ssh = true)

### How to reproduce the issue

pops up when you type

### Expected behavior

Nothing is happening

### Actual behavior

Pop-up error：
```
Error executing vim.schedule lua callback: .../LJZ/.config/nvim/lua/modules/configs/completion/cmp.lua:158: attempt to index field 'cmp' (a nil value)
stack traceback:
        .../LJZ/.config/nvim/lua/modules/configs/completion/cmp.lua:158: in function 'entry_filter'
        .../.local/share/nvim/site/lazy/nvim-cmp/lua/cmp/source.lua:121: in function 'get_entries'
        .../.local/share/nvim/site/lazy/nvim-cmp/lua/cmp/source.lua:352: in function ''
        vim/_editor.lua: in function <vim/_editor.lua:0>
```

### Additional information

I began after I `pull` the newest repo 1h ago.

**Comment by ayamir** [comment]
`Lazy sync`
https://github.com/ayamir/nvimdots/pull/662
