### ISSUE TITLE
ssh connect  closed by remote host

### ISSUE THREAD

**Issue by jwangtobeno1** [ayamir/nvimdots#729]
### Version confirmation

- [X] Confirm

### Following prerequisites

- [X] Confirm

### Neovim version

NVIM v0.9.0

### Operating system/version

manjaro linux 5.15.109-1-manjaro

### Terminal name/version

Konsole 23.04.0

### Branch info

main (Default/Latest)

### Fetch Preferences

SSH (use_ssh = true)

### How to reproduce the issue

when I check plugins updata, prompt connection refused

![2023](https://github.com/ayamir/nvimdots/assets/69038155/a5a3448a-25cc-4cbb-9dd9-94bbc85c290a)

when I `ssh -vT git@github.com`:

`OpenSSH_9.3p1, OpenSSL 3.0.8 7 Feb 2023
debug1: Reading configuration data /etc/ssh/ssh_config
debug1: Connecting to github.com [20.205.243.166] port 22.
debug1: Connection established.
debug1: identity file /home/username/.ssh/id_rsa type 0
debug1: identity file /home/username/.ssh/id_rsa-cert type -1
debug1: identity file /home/username/.ssh/id_ecdsa type -1
debug1: identity file /home/username/.ssh/id_ecdsa-cert type -1
debug1: identity file /home/username/.ssh/id_ecdsa_sk type -1
debug1: identity file /home/username/.ssh/id_ecdsa_sk-cert type -1
debug1: identity file /home/username/.ssh/id_ed25519 type -1
debug1: identity file /home/username/.ssh/id_ed25519-cert type -1
debug1: identity file /home/username/.ssh/id_ed25519_sk type -1
debug1: identity file /home/username/.ssh/id_ed25519_sk-cert type -1
debug1: identity file /home/username/.ssh/id_xmss type -1
debug1: identity file /home/username/.ssh/id_xmss-cert type -1
debug1: identity file /home/username/.ssh/id_dsa type -1
debug1: identity file /home/username/.ssh/id_dsa-cert type -1
debug1: Local version string SSH-2.0-OpenSSH_9.3
kex_exchange_identification: Connection closed by remote host
Connection closed by 20.205.243.166 port 22`

Then I `rm -r ~/.ssh` , regenerate key and add it to github , still doesn't work！

Looking forward to your help!

### Expected behavior

check plugins updata can successful.

**Comment by ayamir** [comment]
Stop your proxy program like `clash`, unset terminal proxy then retry.

**Comment by jwangtobeno1** [comment]
Doing this has successfully resolved the issue! Greatful!

But does this mean that I will not be able to set proxy on the terminal in the future?

**Comment by ayamir** [comment]
You can use script to export or unset proxy when you needed.
