### ISSUE TITLE
WSL 2 Clipboard issue

### ISSUE THREAD

**Issue by hu3rror** [ayamir/nvimdots#731]
### Feature description

Currently win32yank is still used, but officials' wiki seem to have proposed a new method.

Ref: https://github.com/neovim/neovim/wiki/FAQ#how-to-use-the-windows-clipboard-from-wsl

**Comment by CharlesChiuGit** [comment]
looks promising! have u tried it yet?

**Comment by ayamir** [comment]
Tried it, the paste operation requires more time to be finished compared to `win32yank`.
I guess it have to do with my `powershell` need some time to load env.
