### ISSUE TITLE
Pressing `<C-p>` and `<C-n>` in insert mode calls out NeoVim native menu

### ISSUE THREAD

**Issue by huge-pancake** [ayamir/nvimdots#732]
### Version confirmation

- [X] Confirm

### Following prerequisites

- [X] Confirm

### Neovim version

NVIM v0.10.0-dev-319+g5825d2f6ca

### Operating system/version

ArchLinux

### Terminal name/version

foot version: 1.14.0 +pgo +ime +graphemes -assertions

### $TERM environment variable

foot

### Branch info

main (Default/Latest)

### Fetch Preferences

SSH (use_ssh = true)

### How to reproduce the issue

1. Open a file
2. Move to somewhere to let some text under cursor
3. Press `i` to switch to insert mode
4. Press `<C-p>` or `<C-n>`

### Expected behavior

Nothing happen

### Actual behavior

A unknown menu which doesn't follow cmp theming appeared.

![image](https://github.com/ayamir/nvimdots/assets/73375859/5104cc58-5533-48e7-84d3-d72fd3bd2cd0)

### Additional information

Normal CMP menu looks like

![image](https://github.com/ayamir/nvimdots/assets/73375859/de0ad806-1bd6-4b67-9700-fa733adda0f1)

**Comment by CharlesChiuGit** [comment]
Seems relevant to these two lines:

https://github.com/ayamir/nvimdots/blob/c6b4163407c5aae191a1235077982c245ca4221f/lua/modules/configs/completion/cmp.lua#L116-L117

Have u check if there's any related issue in the upstream repo, e.g. https://github.com/hrsh7th/nvim-cmp?

**Comment by huge-pancake** [comment]
> Seems relevant to these two lines:

No, I removed these lines and the problem still exists.

> Have u check if there's any related issue in the upstream repo, e.g. https://github.com/hrsh7th/nvim-cmp?

Not very sure about this, I also tested in NvChad, this problem is also in NvChad

**Comment by ayamir** [comment]
It's not bug. Just `nvim` built-in keyword completion.

**Comment by huge-pancake** [comment]
So is there any need/way to disable it?

**Comment by Jint-lzxy** [comment]
> So is there any need/way to disable it?

u can first check if `cmp` is available, and if not, map that to `<Nop>`. A simple `Lua` function is sufficient to handle this problem.

**Comment by huge-pancake** [comment]
![image](https://github.com/ayamir/nvimdots/assets/73375859/d439490c-9e50-4138-8eac-095a15dbfe34)

Works well.
