### ISSUE TITLE
Adapt to lazy load session_lens of auto-session

### ISSUE THREAD

**Issue by Saafo** [ayamir/nvimdots#742]
### Feature description

Currently, [auto-session](https://github.com/rmagatti/auto-session) start with configuring session_lens, so that if we start with auto-session, it will load telescope immediately and will cost about 40 ms at startup.

Now, it fixed this issue by https://github.com/rmagatti/auto-session/pull/231, and we can configure this for auto-session:

```
  session_lens = {
    load_on_setup = false,
  },
```

to avoid loading telescope at start, which will only cost about 1ms even if we load auto-session at startup.

This issue is suggesting adding the configuration above to the auto-session config. And if possible, I can create a pr for it.

Besides, I wonder whether we should call `require("auto-session").setup_session_lens()` at some point before using session-lens

**Comment by ayamir** [comment]
We have lazy loaded the `auto-session` itself with `SessionSave`, `SessionRestore` and `SessionDelete` cmds.
https://github.com/ayamir/nvimdots/blob/42e816b9d465b69110de639b1afd94b3ce1fa5c8/lua/modules/plugins/editor.lua#L10
It does't affect the startuptime.

**Comment by Saafo** [comment]
> We have lazy loaded the auto-session itself with SessionSave, SessionRestore and SessionDelete cmds.

Oh I mean, if someone (like me) enable the `auto-session` by `lazy=false`, then the configuration helps.

**Comment by ayamir** [comment]
```lua
return function()
	require("auto-session").setup({
		log_level = "info",
		auto_session_enable_last_session = true,
		auto_session_root_dir = vim.fn.stdpath("data") .. "/sessions/",
		auto_session_enabled = true,
		auto_save_enabled = true,
		auto_restore_enabled = true,
		auto_session_suppress_dirs = nil,
		session_lens = {
			-- If load_on_setup is set to false, one needs to eventually call `require("auto-session").setup_session_lens()` if they want to use session-lens.
			load_on_setup = false,
			theme_conf = { border = true },
			previewer = false,
		},
	})

	vim.api.nvim_create_user_command("SessionLenShow", function()
		require("auto-session").setup_session_lens()
		require("auto-session.session-lens").search_session()
	end, { nargs = 0 })
end

```

**Comment by Saafo** [comment]
LGTM!
