### ISSUE TITLE
Is there any way to hide the diagnose msg in editor？

### ISSUE THREAD

**Issue by PAGANSBLOOD** [ayamir/nvimdots#749]
### Feature description

![屏幕截图 2023-05-18 001159](https://github.com/ayamir/nvimdots/assets/129302474/876f2a3b-c81f-4afb-97bf-fc93ac18d5ba)
![屏幕截图 2023-05-18 001302](https://github.com/ayamir/nvimdots/assets/129302474/ef975842-c0c1-467d-bc8a-24ab595699d9)

**Comment by CharlesChiuGit** [comment]
：Lspstop

**Comment by ayamir** [comment]
https://github.com/ayamir/nvimdots/blob/fff57e1202abf01240d36bd182733937b1256959/lua/core/settings.lua#L14
