### ISSUE TITLE
请问一下，怎么样可以让catppuccin主题透明呢；

### ISSUE THREAD

**Issue by fakeczg** [ayamir/nvimdots#757]
### Feature description

请问一下，怎么样可以让catppuccin主题透明呢，就像下面这个vim一样；谢谢

![图片](https://github.com/ayamir/nvimdots/assets/54363314/5db10e28-16ef-4028-a12d-f94e7fa0df12)

**Comment by Groveer** [comment]
Modify `transparent_background` setting to `true` in `lua/core/settings.lua` file.

**Comment by fakeczg** [comment]
> Modify `transparent_background` setting to `true` in `lua/core/settings.lua` file.

thanks!

**Comment by fakeczg** [comment]
Modify transparent_background setting to true in lua/core/settings.lua file.
