### ISSUE TITLE
`transparent_background` cause `neodim` not being able the get the `bg_color`

### ISSUE THREAD

**Issue by justforlxz** [ayamir/nvimdots#758]
### Version confirmation

- [X] Confirm

### Following prerequisites

- [X] Confirm

### Neovim version

NVIM v0.9.0

### Operating system/version

deepen v23 beta

### Terminal name/version

kitty 0.28.1 created by Kovid Goyal

### Branch info

main (Default/Latest)

### Fetch Preferences

HTTPS (use_ssh = false)

### How to reproduce the issue

1. set `transparent_background` to true.
2. open some cpp file
3. add an unused variable

![image](https://github.com/ayamir/nvimdots/assets/12298476/82d1499c-dd82-41a3-ba55-7d13eff92082)

### Expected behavior

returns the correct value and the problem goes away.

### Additional information

From my analysis, the wrong color is returned.

![image](https://github.com/ayamir/nvimdots/assets/12298476/139b00af-1121-465b-b318-393cbf5187c5)

or I set blend_color to `#000000`, the error is missing.

**Comment by CharlesChiuGit** [comment]
I can't seem to reproduce that. Have u keep all the plugins and nvim config up-to-date?

**Comment by CharlesChiuGit** [comment]
ok, I got the error now. Let me look into that.
Also, could u update your original post?

**Comment by CharlesChiuGit** [comment]
@justforlxz can u test the patch?

**Comment by justforlxz** [comment]
> @justforlxz can u test the patch?

LGTM. but I'm not test light theme. : )
