### ISSUE TITLE
vim(highlights) query: invalid node type at position 2765 for language vim

### ISSUE THREAD

**Issue by kevin1sMe** [ayamir/nvimdots#761]
### Version confirmation

- [X] Confirm

### Following prerequisites

- [X] Confirm

### Neovim version

NVIM v0.8.3

### Operating system/version

ubuntu22.04TLS

### Terminal name/version

iTerm2

### $TERM environment variable

xterm

### Branch info

0.8 (Legacy)

### Fetch Preferences

SSH (use_ssh = true)

### How to reproduce the issue

After updating the version, I encountered the following error (which previously was working fine):

```
## The following errors have been detected:
  - ERROR: vim(highlights): /usr/share/nvim/runtime/lua/vim/treesitter/query.lua:219: query: invalid node type at position 2765 for language vim
    vim(highlights) is concatenated from the following files:
    | [ERROR]:"/root/.local/share/nvim/site/lazy/nvim-treesitter/queries/vim/highlights.scm", failed to load: /usr/share/nvim/runtime/lua/vim/treesitter/query.lua:219: query: invalid node type at position 2765 for language vim
```

I have tried performing a fresh installation of nvimdots and deleted the old .local/share/nvim directory, but the problem persists.

I have looked through the issues and relevant operations in [nvim-treesitter](https://github.com/nvim-treesitter/nvim-treesitter/issues/3092), but still have not found a solution.

I would appreciate any help or suggestions. Thank you!

### Expected behavior

work fine

### Actual behavior

When I open a file, the following prompt appears: 

`treesitter/highlighter: Error executing lua: ...l/share/nvim/site/lazy/neodim/lua/neodim/ts_override.lua:33: attempt to...`

**Comment by CharlesChiuGit** [comment]
try #760

**Comment by ayamir** [comment]
Use 0.9 branch is suggested.

**Comment by kevin1sMe** [comment]
> try #760

I am use 0.8 branch now, shoud I update to main(0.9)?

The PR fix my problem?

**Comment by ayamir** [comment]
> I am use 0.8 branch now, shoud I update to main(0.9)?

Yes, keep nvim version up to date will eliminate lots of bugs. Of course, it's inconvenient for us to fix problems of legacy config. Please use latest config if possible.

**Comment by AngelontheRoad** [comment]
I've encountered a similar problem before, and solved it by [here](https://github.com/nvim-treesitter/nvim-treesitter#i-get-query-error-invalid-node-type-at-position:~:text=I%20get%20query,parser%20is%20used.)

**Comment by ayamir** [comment]
> I've encountered a similar problem before, and solved it by [here](https://github.com/nvim-treesitter/nvim-treesitter#i-get-query-error-invalid-node-type-at-position:~:text=I%20get%20query,parser%20is%20used.)

@kevin1sMe check this

**Comment by Jint-lzxy** [comment]
https://github.com/ayamir/nvimdots/commit/e5e7252ff7014d795332c7e7725d98525ad110a0. Please pull the `0.8` branch and sync the plugins.

**Comment by ayamir** [comment]
Close due to long time no response, feel free to open it if needed.
