### ISSUE TITLE
All the content of the neovim register is automatically copied to the system clipboard, and the number and Chinese display is garbled

### ISSUE THREAD

**Issue by darkwilldie** [ayamir/nvimdots#762]
### Version confirmation

- [X] Confirm

### Following prerequisites

- [X] Confirm

### Neovim version

NVIM v0.10.0-dev

### Operating system/version

wsl2

### Terminal name/version

window terminal

### $TERM environment variable

xterm-256color

### Branch info

main (Default/Latest)

### Fetch Preferences

SSH (use_ssh = true)

### How to reproduce the issue

Everytime entering nvim, not only the command of "yy" will automatically connect to the system clipboard, but also "dd".The displayment of numbers can be
![image](https://github.com/ayamir/nvimdots/assets/115530319/3e1c7144-1957-412f-9c20-82a369fc1608)
and Chinese characters can be
![image](https://github.com/ayamir/nvimdots/assets/115530319/575e33a6-0099-43a2-9c5d-a3b22745467a)

### Expected behavior

I hope it can display properly.

**Comment by ayamir** [comment]
>  not only the command of "yy" will automatically connect to the system clipboard, but also "dd".

It's vim default behaviorl, not bug.

Because `clip.exe` can't recognize Chinese characters as UTF-8 string. So the better solution is revert to use `win32yank.exe`.

**Comment by CharlesChiuGit** [comment]
> > not only the command of "yy" will automatically connect to the system clipboard, but also "dd".
> 
> It's vim default behaviorl, not bug.

ys, vim is send `dd` to the register. if u want to change that, u can tune the clipboard settings, or learn how to delete things to "void" and not the register.

---

For the invalid characters part, I think it needs further investigation, cause the number shouldn't have UTF-8 encoding issues.

@darkwilldie can u try:
1. use windows terminal and win32yank
2. use wezterm and win32yank
3. use wezterm and clip.exe
4. check font settings in wsl and Windows

**Comment by CharlesChiuGit** [comment]
I found some related issues.
https://github.com/microsoft/WSL/issues/4852

**Comment by ayamir** [comment]
Temp work around for you @darkwilldie :
```
		vim.g.clipboard = {
			name = "win32yank-wsl",
			copy = {
				["+"] = "win32yank.exe -i --crlf",
				["*"] = "win32yank.exe -i --crlf",
			},
			paste = {
				["+"] = "win32yank.exe -o --lf",
				["*"] = "win32yank.exe -o --lf",
			},
			cache_enabled = 0,
		}
```

**Comment by darkwilldie** [comment]
> > > not only the command of "yy" will automatically connect to the system clipboard, but also "dd".
> > 
> > 
> > It's vim default behaviorl, not bug.
> 
> ys, vim will send things to register after `dd`, and then to `clip.exe`. if u want to change that, u can tune the clipboard settings, or learn how to delete things to "void" and not the register.
> 
> For the invalid characters part, I think it needs further investigation, cause the number shouldn't have UTF-8 encoding issues.
> 
> @darkwilldie can u try:
> 
> 1. use windows terminal and win32yank
> 2. use wezterm and win32yank
> 3. use wezterm and clip.exe
> 4. check font settings in wsl and Windows
> 
> Also please make sure everything is up-to-date, including Windows updates and wsl updates, etc.

Replaced with Wezterm, the problem remains the same, so I believe this issue is unrelated to windows terminal
![image](https://github.com/ayamir/nvimdots/assets/115530319/97ba7e99-ae1c-4a89-8fea-be32ab3852f0)
when using psyank, the mess remains(system clipboard is garbled but the registers of neovim display fine), while it solved by changing to wsl32yank(because any copied content won't be transferred to system clipboard)

**Comment by darkwilldie** [comment]
> I found a related issue. [microsoft/WSL#4852](https://github.com/microsoft/WSL/issues/4852)
![image](https://github.com/ayamir/nvimdots/assets/115530319/20806465-4d1e-45cb-b685-43860faf34b2)
well, i reproduced that issue successfully.

> I found a related issue. [microsoft/WSL#4852](https://github.com/microsoft/WSL/issues/4852)

**Comment by darkwilldie** [comment]
> I found a related issue. [microsoft/WSL#4852](https://github.com/microsoft/WSL/issues/4852)

![image](https://github.com/ayamir/nvimdots/assets/115530319/687a315d-a50b-48e8-af30-4e3c526cb77e)

**Comment by darkwilldie** [comment]
well, I reset Win32yank and now it works fine.

**Comment by ayamir** [comment]
750eef1f46ed83d4833f68f394e45909015206b1
