### ISSUE TITLE
black not working when save

### ISSUE THREAD

**Issue by nkta3m** [ayamir/nvimdots#763]
### Version confirmation

- [X] Confirm

### Following prerequisites

- [X] Confirm

### Neovim version

nvim 0.9

### Operating system/version

Arch

### Terminal name/version

Alacritty

### Branch info

main (Default/Latest)

### Fetch Preferences

HTTPS (use_ssh = false)

### Affected language servers

python

### How to reproduce the issue

好像是换到pylsp后出现的问题，保存python文件时，black不能自动format了

### Actual behavior

auto format when save

### Support info

 2 client(s) attached to this buffer: 
Client: pylsp (id: 1, bufnr: [1])     
filetypes:       python
autostart:       true

Client: null-ls (id: 2, bufnr: [1])  
filetypes:       python, markdown, markdown.mdx, sh, luau, lua, yaml 
autostart:       false 
cmd:             <function>

**Comment by ayamir** [comment]
Can't repo, check whether `black` is installed by `Mason`.

**Comment by nkta3m** [comment]
重新安装black后好了
