### ISSUE TITLE
Error executing vim.schedule lua callback: vim/_init_packages.lua:0: module 'vim.diagnostic' not found:

### ISSUE THREAD

**Issue by BitterDarker** [ayamir/nvimdots#764]
### Feature description

![2](https://github.com/ayamir/nvimdots/assets/101701191/b29fc025-bd6c-476d-8a4c-38f068cafd84)
![1](https://github.com/ayamir/nvimdots/assets/101701191/ae13181c-40ba-4dbd-b575-74f91215b8c7)

**Comment by ayamir** [comment]
Don't build neovim by yourself if you don't know how to do it.

Use nvim binary provided by neovim [here](https://github.com/neovim/neovim/releases/tag/stable) instead.

If you don't know how to install it:
1. Use the appimage is the simplest way.
```bash
wget https://github.com/neovim/neovim/releases/download/stable/nvim.appimage
mv nvim.appimage nvim
chmod +x nvim
sudo mkdir -p /usr/local/bin
sudo mv nvim /usr/local/bin
# check nvim version
nvim --version
```
2. Unzip the tar.gz then move files.
```bash
wget https://github.com/neovim/neovim/releases/download/stable/nvim-linux64.tar.gz
tar xpvf nvim-linux64.tar.gz
cd nvim-linux64
sudo mkdir -p /usr/local/bin/
sudo mkdir -p /usr/local/share/
sudo mkdir -p /usr/local/lib/
sudo cp -vr bin/* /usr/local/bin/
sudo cp -vr lib/* /usr/local/lib/
sudo cp -vr share/* /usr/local/share/
# check nvim version
nvim --version
```

**Comment by ayamir** [comment]
Close due to no response, feel free to reopen it if it still exists after applying what I suggested.
