### ISSUE TITLE
Neodim not work for pylsp

### ISSUE THREAD

**Issue by fecet** [ayamir/nvimdots#767]
### Version confirmation

- [X] Confirm

### Following prerequisites

- [X] Confirm

### Neovim version

NVIM v0.9.0

### Operating system/version

Arch

### Terminal name/version

alacritty

### Branch info

main (Default/Latest)

### Fetch Preferences

HTTPS (use_ssh = false)

### Affected language servers

pylsp, pyright

### How to reproduce the issue

open any python file, https://github.com/zbirenbaum/neodim/issues/21#issuecomment-1557531973
```python
from typing import Union, List, Any


def a(b, c) -> Any:
    return b + 1
```
And the following is how it look likes in neovim:
![image](https://github.com/zbirenbaum/neodim/assets/41792945/6fdca40a-47e4-480a-8dd0-b1440964b13d)

### Actual behavior

Neodim not dim unused variable

### Support info

 Language client log: /home/rok/.local/state/nvim/lsp.log
 Detected filetype:   python
 
 2 client(s) attached to this buffer: 
 
 Client: pylsp (id: 1, bufnr: [1])
 	filetypes:       python
 	autostart:       true
 	root directory:  /home/rok/Nutstore Files/codes/tlem
 	cmd:             /home/rok/.local/share/nvim/mason/bin/pylsp
 
 Client: null-ls (id: 2, bufnr: [1])
 	filetypes:       cpp, c, vue, typescript, javascript, typescriptreact, javascriptreact, yaml, css, html, sh, markdown, scss, vim, python, lua, luau, rust
 	autostart:       false
 	root directory:  /home/rok/Nutstore Files/codes/tlem
 	cmd:             <function>
 
 Configured servers list: html, jsonls, lua_ls, clangd, ruby_ls, pylsp, bashls

**Comment by ayamir** [comment]
Can confirm, Maybe `neodim` doesn't support `pylsp`.
