### ISSUE TITLE
clone后发生报错

### ISSUE THREAD

**Issue by lananOaO** [ayamir/nvimdots#786]
### Version confirmation

- [X] Confirm

### Following prerequisites

- [X] Confirm

### Neovim version

NVIM 0.9.1

### Operating system/version

WIN11

### Terminal name/version

Powershell

### Branch info

main (Default/Latest)

### Fetch Preferences

SSH (use_ssh = true)

### How to reproduce the issue

在clone时会失败并报出Error detected while processing C:\Users\guangkun\AppData\Local\nvim\init.lua:
E5113: Error while calling lua chunk: C:\Users\guangkun\AppData\Local\nvim/lua/core/init.lua:
164: 错误
<img width="1128" alt="image" src="https://github.com/ayamir/nvimdots/assets/103936561/4ffd2523-c1d9-4dae-8858-d74917a097c5">

### Expected behavior

<img width="1128" alt="image" src="https://github.com/ayamir/nvimdots/assets/103936561/461afa82-7a87-4d04-8a22-e1fd533ed063">

**Comment by CharlesChiuGit** [comment]
U dont just clone and use this repo, read the doc first.

**Comment by lananOaO** [comment]
我使用的是doc的命令安装，安装结束之后就显示成这样

**Comment by lananOaO** [comment]
> U dont just clone and use this repo, read the doc first.
> And don't use self-compiled nvim.

我使用的是doc的命令安装，安装结束之后就显示成这样

**Comment by CharlesChiuGit** [comment]
Do some research in the closed issues, thanks for your cooperation.
