### ISSUE TITLE
Replace path separator in the `require` function form `.` to `/`

### ISSUE THREAD

**Issue by ksksddr** [ayamir/nvimdots#787]
### Feature description

在使用`require`命令时，用`/`作为路径分隔符可能更好；否则，若用户在自定义配置文件时，若在文件名中用了`.`，可能会出现问题。理由可见于此文章：[lua require之“.““/“路径影响package.loaded[v] = nil卸载问题](https://blog.csdn.net/lanazyit/article/details/112221664)。

---

Replacing the path separator in the `require` command with `/` may be a better choice

When using the `require` command, it may be better to use `/` as the path separator; Otherwise, if the user uses `.` in the file name when customizing the configuration file, it may cause problems. The reason can be seen in this article: [lua require之“.““/“路径影响package.loaded[v] = nil卸载问题](https://blog.csdn.net/lanazyit/article/details/112221664).

**Comment by CharlesChiuGit** [comment]
Some reference:
https://luapower.com/path
https://tex.stackexchange.com/questions/48179/what-is-the-correct-way-to-delineate-directories-in-lua

**Comment by CharlesChiuGit** [comment]
The reasons looks legit to me, I think it's a gd idea.
I can draft it if other maintainers agrees.

**Comment by ksksddr** [comment]
Regarding this issue, from what I have seen, `/` is indeed a safer and more suitable path separator; Unfortunately, people in the NeoVim community seem to prefer using `.`, and even most well-known configurations are like this, such as [LunarVim](https://github.com/LunarVim/LunarVim), AstroNvim(https://github.com/AstroNvim/AstroNvim), [NvChad](https://github.com/NvChad/NvChad), [room nvim](https://github.com/doom-neovim/doom-nvim), and you can find more examples in [awesome-lua](https://github.com/uhub/awesome-lua).

— This is so strange, I don't know why.

---

关于此提议，从我所见的资料来看，“/”的确是更安全、更合适的路径分隔符；但遗憾的是，NeoVim社区中的人们似乎更偏好于使用“.”，甚至大部分知名的配置都是如此，如[LunarVim](https://github.com/LunarVim/LunarVim)、[AstroNvim](https://github.com/AstroNvim/AstroNvim)、[NvChad](https://github.com/NvChad/NvChad)、[doom-nvim](https://github.com/doom-neovim/doom-nvim)，你还可从[awesome-lua](https://github.com/uhub/awesome-lua)中找到更多例子。

——这好奇怪，我不知道这是为什么。

**Comment by CharlesChiuGit** [comment]
> Regarding this issue, from what I have seen, `/` is indeed a safer and more suitable path separator; Unfortunately, people in the NeoVim community seem to prefer using `.`, and even most well-known configurations are like this, such as [LunarVim](https://github.com/LunarVim/LunarVim), AstroNvim([AstroNvim/AstroNvim](https://github.com/AstroNvim/AstroNvim)), [NvChad](https://github.com/NvChad/NvChad), [room nvim](https://github.com/doom-neovim/doom-nvim), and you can find more examples in [awesome-lua](https://github.com/uhub/awesome-lua).
> 
> — This is so strange, I don't know why.

Indeed the Neovim community is more used to `.` than `/`. I think part of the reason is that we're not using `lua` to do our "serious job". Most of the ppl learned `lua` b/c we want to config sth, for example, Neovim, wezterm and xplr etc. Even the most famous plugins use `.` and we learn `lua` from reading their code.

But this just my personal guessing, maybe there is a legit cause for it.

**Comment by Jint-lzxy** [comment]
Hmm but AFAIU using `.` would be better b/c _the responsible `require` loader will **replace** each dot with the predefined directory separator_. Let's have a look at the corresponding implementation in [`loadlib.c`](https://github.com/lua/lua/blob/6443185167c77adcc8552a3fee7edab7895db1a9/loadlib.c#L481-L505):
```cpp
static const char *searchpath (lua_State *L, const char *name,
                                             const char *path,
                                             const char *sep,
                                             const char *dirsep) {
  // Unrelated code //

  /* separator is non-empty and appears in 'name'? */
  if (*sep != '\0' && strchr(name, *sep) != NULL)
    name = luaL_gsub(L, name, sep, dirsep);  /* replace it by 'dirsep' */

  // Unrelated code //
}
```
And corresponding [function wrapper](https://github.com/lua/lua/blob/6443185167c77adcc8552a3fee7edab7895db1a9/loadlib.c#L508C1-L519):
```cpp
static int ll_searchpath (lua_State *L) {
  const char *f = searchpath(L, luaL_checkstring(L, 1),
                                luaL_checkstring(L, 2),
                                luaL_optstring(L, 3, "."),
                                                      ^ // Note the hard-coded separator here
                                luaL_optstring(L, 4, LUA_DIRSEP));

  // Unrelated code //
}
```

Of course, users can choose to redefine `LUA_DIRSEP` when compiling Lua, but obviously this won't happen in most cases. In fact, as the [Lua Unofficial FAQ](http://www.luafaq.org/#T1.40) tell us:
> `package.config` is a string where the first 'character' is the directory separator;

This first char is, in fact, `LUA_DIRSEP` and is `/` on most platforms **using `/` as path separator.**

Hence we should avoid using `/` in require b/c it is a **platform-specific** directory separator _(in practice it will be supported by Windows though)_. In other words, using `/` is feasible, but it's **not** guaranteed to be portable (e.g., on systems that do not use `/` as path separator). Since Lua automatically normalizes strings when processing `require` paths, I cannot find a reason for using `/` as the path separator 😄

**Comment by CharlesChiuGit** [comment]
Damn, Jint-lzxy always dig deeper than me lol.

So, @ksksddr is it gd to close the issue now?

**Comment by ksksddr** [comment]
The source code in `loadlib. c` is very helpful! But there is another question: besides redefining `LUA_DIRSEP`, how to use `require` to include modules that contain `.` in the file name? It seems that using `.` in Lua file names is a bad choice.

**Comment by Jint-lzxy** [comment]
@ksksddr Using `.` is absolutely _not_ a bad choice (the article you referred to reached incorrect conclusions b/c **the author is probably unfamiliar with the package system**) - in fact, using `.` as a path separator _was_ the original design intention to prevent things from becoming _overly_ complicated. If you really want to have path(s) containing `.`, then setting `package.path` or `package.cpath` would be the correct approach (like what we did in `pack.lua`):
https://github.com/ayamir/nvimdots/blob/b60e8c24aecc409889529052f88b158e6707702d/lua/core/pack.lua#L25-L28
FYI: [Lua PIL\#8.1](https://www.lua.org/pil/8.1.html). But to keep things simple, just avoid using filenames that include `.` :)

**Comment by Jint-lzxy** [comment]
In short, Lua will (only) convert `.` to whatever defines the path separator for the target OS. Using `/` _seems_ feasible just b/c `/` happens to be the path separator on your host machine.

**Comment by ksksddr** [comment]
`Package.path` is indeed a solution!! Thank you very much!

My verification process: I created a file named `main.lua` and a folder named `sub.a` in a certain path, and created the file `a.lua` in the latter:
```
│ main.lua
│
└─sub.a
	a.lua
```
The following code in `main.lua` can run successfully:
```lua
package.path = package.path .. ";./sub.a/a.lua"
-- print(package.path)
require("sub.a.a")
require("sub.a/a")
```
But if the `a.lua` in the above code is changed to `?.lua`, an error will occur. Why did this happen? It seems that the `.` in the folder will affect the resolution of `?`.

@Jint-lzxy

**Comment by Jint-lzxy** [comment]
> But if the `a.lua` in the above code is changed to `?.lua`, an error will occur. Why did this happen? It seems that the `.` in the folder will affect the resolution of `?`.

@ksksddr I would suggest you read the relevant section(s) in [_Programming in Lua_](https://www.lua.org/pil/) as this issue is no longer related to this configuration. The following is just to tell you what actually happened:
- Before:
```lua
require("sub.a.a") -- Found b/c `./sub/a/a.lua` matches `./?.lua`, 2 replacements done.
require("sub.a/a") -- Found b/c `./sub/a/a.lua` matches `./?.lua`, 1 replacement done.
```
- After:
```lua
require("sub.a.a") -- Not found b/c the closest match is `./sub/a/sub/a/a.lua` (not a valid file);
                   -- And using package.cpath `./sub/a/a.[a/so/dll/dylib]` is also not a valid file.
                   -- 2 replacements done.
require("sub.a/a") -- Not found b/c the closest match is `./sub/a/sub/a/a.lua` (not a valid file);
                   -- And using package.cpath `./sub/a/a.[a/so/dll/dylib]` is also not a valid file.
                   -- 1 replacement done.
```

**Comment by ksksddr** [comment]
@Jint-lzxy. Thank you very much for your timely and helpful answer!
