### ISSUE TITLE
The color theme does not display properly in MobaXterm

### ISSUE THREAD

**Issue by QingYunA** [ayamir/nvimdots#789]
### Version confirmation

- [X] Confirm

### Following prerequisites

- [X] Confirm

### Neovim version

NVIM v0.9.0-dev-1158+g706bcab75

### Operating system/version

Ubuntu 20.04.6 LTS

### Terminal name/version

MobaXterm Personal Edition v21.4

### $TERM environment variable

tmux-256color

### Branch info

main (Default/Latest)

### Fetch Preferences

SSH (use_ssh = true)

### How to reproduce the issue

There seems to be an error in the color theme display.

When I use <space>fc to switch themes, there seems to be a color rendering error that causes none of the themes to display correctly, I have tried multiple color themes, including a monokai-pro theme that I added myself.

![](https://github.com/ayamir/nvimdots/assets/41177312/53fd588b-7fd2-4a93-928e-0f394b198040)
catppuccin-mocha in my nvim

![image](https://github.com/ayamir/nvimdots/assets/41177312/44fc485c-41f7-4224-8d45-56fa4a9334d8)
catppuccin-mocha in my vscode

Same problem appears on all my themes, I had thought it was a term color setting issue. I have tried switching from tmux-256color to xterm-256color, no help.

I have tried to modify "Terminal colors scheme" in Mobaxterm settings, and then the same colorscheme ("catppuchi-mocha") display different colors. like images below.
![image](https://github.com/ayamir/nvimdots/assets/41177312/bafef250-0fd2-4c6a-a2f6-5ce49c3a25f4)
![image](https://github.com/ayamir/nvimdots/assets/41177312/82ae6900-8d45-4984-9501-dbcf1a0f4419)
It seems that the problem goes from my Mobaxterm, I will then try different terminal. But I aslo want get some help from author.

### Expected behavior

All themes should show colors normally (in line with my vscode counterpart)

**Comment by Jint-lzxy** [comment]
We need more information to answer ur issue (looks like you've set _conflicting_ options in ur terminal config):
1. Are u using a non-native (not-for-Windows) Neovim distribution via SSH?
2. Are u using `tmux`? Your `$TERM` environment variable doesn't match the \<Terminal type:\> field in MobaXterm's config.
3. Does ur terminal emulator _(or ur remote emulator)_ support at least 256 colors (or true color)?
4. Does ur terminal emulator _(or ur remote emulator)_ have the corresponding up-to-date terminfo database?
5. Will your terminal emulator _(or ur remote emulator)_ block the parsing of colors emitted by `libvterm`? (Check if any given `#RRGGBB` colors are rendered correctly in Neovim)
6. If applicable, do u have ur SSH configuration(s) correctly forwarded to the remote?

***
A quick note here, the `0.9-dev` build is outdated. Please install a stable version instead.

**Comment by Jint-lzxy** [comment]
Are u using Neovim via SSH?

**Comment by QingYunA** [comment]
> Are u using Neovim via SSH?

Yes

**Comment by QingYunA** [comment]
> We need more information to answer ur issue (looks like you've set _conflicting_ options in ur terminal config):
> 
> 1. Are u using a non-native (not-for-Windows) Neovim distribution via SSH?
> 2. Are u using `tmux`? Your `$TERM` environment variable doesn't match the <Terminal type:> field in MobaXterm's config.
> 3. Does ur terminal emulator _(or ur remote emulator)_ support at least 256 colors (or true color)?
> 4. Does ur terminal emulator _(or ur remote emulator)_ have the corresponding up-to-date terminfo database?
> 5. Will your terminal emulator _(or ur remote emulator)_ block the parsing of colors emitted by `libvterm`? (Check if any given `#RRGGBB` colors are rendered correctly in Neovim)
> 6. If applicable, do u have ur SSH configuration(s) correctly forwarded to the remote?
> 7. What is `fc`? The color configs used by ur the terminal is independent of the colors used by Neovim.
> 
> A quick note here, the `0.9-dev` build is outdated. Please install a stable version instead.

Sorry for not replying to these questions in the rush to try just now.
1. Yes, I am using Nvim via SSH
2. Yes, I lanuch Nvim in Tmux plane, and `$TERM` is `tmux-256color`。
3. Yes, it support. (because the color is normal in zsh.)
4. I am not sure.
5. I think it will not block. (because the color is normal in zsh.)
6. Yes, It is correctly.
7. github swallowed my text, I mean `space`+`f`+`c`

I followed your latest suggestion and changed the Terminal type in mobaxterm from xterm to xterm-256color, and changed the $TERM on the remote server to xterm-256color.
![image](https://github.com/ayamir/nvimdots/assets/41177312/15e55e4d-9084-4634-9a30-a03e6507a587)
after done all above, nvim in tmux still have some problem,but it seem better then before alot.
![image](https://github.com/ayamir/nvimdots/assets/41177312/888c176b-ff56-47b7-862d-074bf0f8b23f)
catppuccin-mocha in nvim (open in tmux)
![image](https://github.com/ayamir/nvimdots/assets/41177312/5f24ac60-0164-43ad-878a-b0c9ef506646)
catppuccin-mocha in nvim (open directly in zsh)
