### ISSUE TITLE
Telescope's keymaps cannot work

### ISSUE THREAD

**Issue by Saafo** [ayamir/nvimdots#790]
### Version confirmation

- [X] Confirm

### Following prerequisites

- [X] Confirm

### Neovim version

0.9.1

### Operating system/version

macOS 13.4

### Terminal name/version

Warp

### $TERM environment variable

xterm-256color

### Branch info

main (Default/Latest)

### Fetch Preferences

SSH (use_ssh = true)

### How to reproduce the issue

 I rebase main branch today, the new ui do look pretty, but there's a serious bug: some keymaps don't work well:

* `<C-k>` and `<C-i>` in insert mode cannot work (https://github.com/nvim-telescope/telescope-live-grep-args.nvim)
* `?` in normal mode almost cannot work(just show the actions panel for a moment and disappeared) (Show mappings for picker actions (normal mode))

Besides, `<C-/>` in insert mode never works before and now(Show mappings for picker actions (insert mode))

### Expected behavior

Keymaps work well

**Comment by Saafo** [comment]
Also there's no divide line between result list and file preview, which is a little odd.

**Comment by ayamir** [comment]
> Also there's no divide line between result list and file preview, which is a little odd.

It's new ui.

**Comment by ayamir** [comment]
> I rebase main branch today, the new ui do look pretty, but there's a serious bug: some keymaps don't work well:
<C-k> and <C-i> in insert mode cannot work (https://github.com/nvim-telescope/telescope-live-grep-args.nvim)
? in normal mode almost cannot work(just show the actions panel for a moment and disappeared) (Show mappings for picker actions (normal mode))
Besides, <C-/> in insert mode never works before and now(Show mappings for picker actions (insert mode))

Can't repo. You should know that `<C-k>` and `<C-i>` only works for `live_grep_args`.

**Comment by Saafo** [comment]
> You should know that <C-k> and <C-i> only works for live_grep_args

Thanks for the hint! It's correct!

> ? in normal mode almost cannot work(just show the actions panel for a moment and disappeared) (Show mappings for picker actions (normal mode))

I can still reproduce this problem, the panel show and disappeared in a short time.

**Comment by Saafo** [comment]
Quite odd, I return back to my branch and everything is ok....

**Comment by CharlesChiuGit** [comment]
maybe just need to lazy sync?

**Comment by Saafo** [comment]
I find the way to repo it:

1. open nvim
2. **open any file, like `init.lua`**
3. open telescope, find file or live grep are both ok
4. press esc to return to normal mode
5. press `?`, you will see the telescope keymap panel show and hide in a second

Can repo it on the latest commit `ea166c67` with iTerm2/Warp on macOS.

**Comment by ayamir** [comment]
Can't repro on wsl2.

https://github.com/ayamir/nvimdots/assets/61657399/6a75073f-fb30-475b-9473-8e34e2c92d2d

**Comment by Saafo** [comment]
@Jint-lzxy I saw you reopened this issue, can you reproduce this on macOS?

**Comment by Jint-lzxy** [comment]
> I saw you reopened this issue, can you reproduce this on macOS?

@Saafo Ys but I haven't had time to look into this yet. Can u provide a minimum working config (single `init.lua`) that can reproduce this issue?

Template:
```lua
local root = vim.fn.fnamemodify("./.repro", ":p")
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({
    "git",
    "clone",
    "--filter=blob:none",
    "--single-branch",
    "https://github.com/folke/lazy.nvim.git",
    lazypath,
  })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  {
    "<SRC>",
    other_lazy_opts = {},
  },
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

-- add anything else here
vim.opt.termguicolors = true
```

**Comment by Saafo** [comment]
> Ys but I haven't had time to look into this yet. Can u provide a minimum working config (single init.lua) that can reproduce this issue?

@Jint-lzxy I really don't have much time recently, I tried copying almost all Telescope's dependencies and configs, but can't reproduce. I just remember this issue happens after the new ui merged.

<details>
<summary>Test Config</summary>

```lua
local root = vim.fn.fnamemodify("./.repro", ":p")
for _, name in ipairs({ "config", "data", "state", "cache" }) do
	vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
	vim.fn.system({
		"git",
		"clone",
		"--filter=blob:none",
		"--single-branch",
		"https://github.com/folke/lazy.nvim.git",
		lazypath,
	})
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
	{
		"nvim-telescope/telescope.nvim",
		dependencies = {
			{ "nvim-tree/nvim-web-devicons" },
			{ "rcarriga/nvim-notify" },
			{ "olimorris/persisted.nvim" },
			{ "nvim-lua/plenary.nvim" },
			{ "debugloop/telescope-undo.nvim" },
			{
				"ahmedkhalf/project.nvim",
				event = "BufReadPost",
				-- config = require("tool.project"),
			},
			{ "nvim-telescope/telescope-fzf-native.nvim", build = "make" },
			{ "nvim-telescope/telescope-frecency.nvim", dependencies = {
				{ "kkharji/sqlite.lua" },
			} },
			{ "jvgrootveld/telescope-zoxide" },
			{ "nvim-telescope/telescope-live-grep-args.nvim" },
		},
		config = function()
			-- local icons = { ui = require("modules.utils.icons").get("ui", true) }
			local lga_actions = require("telescope-live-grep-args.actions")

			require("telescope").setup({
				defaults = {
					vimgrep_arguments = {
						"rg",
						"--no-heading",
						"--with-filename",
						"--line-number",
						"--column",
						"--smart-case",
					},
					initial_mode = "insert",
					-- prompt_prefix = " " .. icons.ui.Telescope .. " ",
					-- selection_caret = icons.ui.ChevronRight,
					scroll_strategy = "limit",
					results_title = false,
					layout_strategy = "horizontal",
					path_display = { "absolute" },
					selection_strategy = "reset",
					sorting_strategy = "ascending",
					color_devicons = true,
					file_ignore_patterns = { ".git/", ".cache", "build/", "%.class", "%.pdf", "%.mkv", "%.mp4", "%.zip" },
					layout_config = {
						horizontal = {
							prompt_position = "top",
							preview_width = 0.55,
							results_width = 0.8,
						},
						vertical = {
							mirror = false,
						},
						width = 0.85,
						height = 0.92,
						preview_cutoff = 120,
					},
					file_previewer = require("telescope.previewers").vim_buffer_cat.new,
					grep_previewer = require("telescope.previewers").vim_buffer_vimgrep.new,
					qflist_previewer = require("telescope.previewers").vim_buffer_qflist.new,
					file_sorter = require("telescope.sorters").get_fuzzy_file,
					generic_sorter = require("telescope.sorters").get_generic_fuzzy_sorter,
					buffer_previewer_maker = require("telescope.previewers").buffer_previewer_maker,
				},
				extensions = {
					fzf = {
						fuzzy = false,
						override_generic_sorter = true,
						override_file_sorter = true,
						case_mode = "smart_case",
					},
					frecency = {
						show_scores = true,
						show_unindexed = true,
						ignore_patterns = { "*.git/*", "*/tmp/*" },
					},
					live_grep_args = {
						auto_quoting = true, -- enable/disable auto-quoting
						-- define mappings, e.g.
						mappings = { -- extend mappings
							i = {
								["<C-k>"] = lga_actions.quote_prompt(),
								["<C-i>"] = lga_actions.quote_prompt({ postfix = " --iglob " }),
							},
						},
					},
					undo = {
						side_by_side = true,
						mappings = { -- this whole table is the default
							i = {
								-- IMPORTANT: Note that telescope-undo must be available when telescope is configured if
								-- you want to use the following actions. This means installing as a dependency of
								-- telescope in it's `requirements` and loading this extension from there instead of
								-- having the separate plugin definition as outlined above. See issue #6.
								["<cr>"] = require("telescope-undo.actions").yank_additions,
								["<S-cr>"] = require("telescope-undo.actions").yank_deletions,
								["<C-cr>"] = require("telescope-undo.actions").restore,
							},
						},
					},
				},
			})

			require("telescope").load_extension("frecency")
			require("telescope").load_extension("fzf")
			require("telescope").load_extension("live_grep_args")
			require("telescope").load_extension("notify")
			require("telescope").load_extension("projects")
			require("telescope").load_extension("undo")
			require("telescope").load_extension("zoxide")
			require("telescope").load_extension("persisted")
		end,
		other_lazy_opts = {},
	},
}
require("lazy").setup(plugins, {
	root = root .. "/plugins",
})

-- add anything else here
vim.opt.termguicolors = true
```
</details>

**Comment by Jint-lzxy** [comment]
@Saafo IMO this issue should be classified as 'not-a-bug'. Excerpt from the log (generated from `nvim -V100nvim.log <...>`):
```bash
chdir(/Users/jint/.local/share/nvim/site/lazy/telescope.nvim/lua/telescope/actions/)
chdir(/Users/jint/.config/nvim)

# ^^^^^^ Pressed <Esc> to return to normal mode
# vvvvvv Another plugin registered under <event>CursorHold called one of Telescope's actions

chdir(/Users/jint/.local/share/nvim/site/lazy/telescope.nvim/lua/telescope/actions/)
chdir(/Users/jint/.config/nvim)

# -----------------------------------------------------------------------------------------

# The popup window closed automatically on action call since `close_with_action` is true
Executing User Autocommands: "*"
autocommand <Lua 972: ~/.local/share/nvim/site/lazy/telescope.nvim/lua/telescope/actions/init.lua:1326>

auto-removing autocommand: BufDelete <buffer=10>
auto-removing autocommand: BufLeave <buffer=10>
auto-removing autocommand: WinClosed <buffer=10>
```
This can be verified by any of the following approaches (cannot repro as long as _any_ of the following conditions are met):
- Open `telescope` when alpha is active - plugins won't load at this time;
- Disable `close_with_action` - one possible workaround for this;
- Wait a bit after `telescope` pops up - wait for these registered plugins to load.

**Comment by Saafo** [comment]
@Jint-lzxy Thanks for the exploration! the `Wait a bit after telescope pops up` suggestion is helpful! And I found the latest commit almost fix this issue since I've test `don't wait after telescope pops up` for 6 times, the issue appeared for 1 time.
