### ISSUE TITLE
Client <n> quit with exit code 1  and signal 0

### ISSUE THREAD

**Issue by c8libur** [ayamir/nvimdots#798]
### Version confirmation

- [X] Confirm

### Following prerequisites

- [X] Confirm

### Neovim version

NVIM v0.10.0-dev LuaJIT 2.1.0-beta3

### Operating system/version

popos22.04

### Terminal name/version

zsh

### Branch info

main (Default/Latest)

### Fetch Preferences

SSH (use_ssh = true)

### How to reproduce the issue

Just after instaing.It happened in the c++ source program after i press 'i‘ and it kept poping up.

### Expected behavior

I hope it becomes normal

### Actual behavior

![image](https://github.com/ayamir/nvimdots/assets/88889900/2f3b31e9-4150-4ac8-a87f-de0c73f41f7d)

**Comment by ayamir** [comment]
`rm ~/.local/state/nvim/lsp.log` first, then reopen this file with `nvim`.
1. Put the screenshot of `:LspInfo`.
2. Put the content of `~/.local/state/nvim/lsp.log`

**Comment by c8libur** [comment]
> `rm ~/.local/state/nvim/lsp.log` first, then reopen this file with `nvim`.
> 
>     1. Put the screenshot of `:LspInfo`.
> 
>     2. Put the content of `~/.local/state/nvim/lsp.log`

![图片](https://github.com/ayamir/nvimdots/assets/88889900/4bc66be8-6deb-4b78-b2d8-a5e22686b225)
This is my Lspinfo, and I have deleted lsp.log as your said.
I'm sorry for my late reply.

**Comment by c8libur** [comment]
> `rm ~/.local/state/nvim/lsp.log` first, then reopen this file with `nvim`.
> 
>     1. Put the screenshot of `:LspInfo`.
> 
>     2. Put the content of `~/.local/state/nvim/lsp.log`

![图片](https://github.com/ayamir/nvimdots/assets/88889900/4bc66be8-6deb-4b78-b2d8-a5e22686b225)
This is my Lspinfo, and I have deleted lsp.log as your said.
I'm sorry for my late reply.

**Comment by ayamir** [comment]
https://github.com/ayamir/nvimdots/issues/559#issuecomment-1615952538

**Comment by ayamir** [comment]
> This is my Lspinfo, and I have deleted lsp.log as your said.

remove `lsp.log` then reopen `nvim`, if this problem still exists then we can see the detail from the log.

**Comment by c8libur** [comment]
this screenshot is the result of following your steps

**Comment by Jint-lzxy** [comment]
@c8libur What we mean is "to use Neovim to open an arbitrary **file**" (e.g., `nvim init.lua`) instead of a folder (netrw); Then use:
```bash
nvim ~/.local/state/nvim/lsp.log
```
to obtain language client logs and paste ALL contents of this file here.

**Comment by CharlesChiuGit** [comment]
have u check if your nodejs version? which is used for `copilot`.
search the old issues if u need more guilds.

**Comment by DZRRRRRR** [comment]
SAME BUG

**Comment by CharlesChiuGit** [comment]
**WHAT* same bug, what exactly did u do? U haven't provide any useful info for us to debug.
U didn't done one single thing we told u to do. How on earth are we be able to help u???
Can u watch closely to what we told u to do?

**Comment by CharlesChiuGit** [comment]
From the log file, it's seem like u provide the wrong nodejs version for copilot to execute. **PLEASE** check past related issues of how to fix it. U can also find the info in the wiki.

**Comment by ayamir** [comment]
> SAME BUG! I submit the SCREENSHOTS and the LSP.LOG file ![image](https://user-images.githubusercontent.com/52708009/251701292-6f824a90-dd09-4397-9e8f-b5b05597fc66.png) ![image](https://user-images.githubusercontent.com/52708009/251701672-a935607a-d225-432e-b479-850d838baa79.png) [lsp.log](https://github.com/ayamir/nvimdots/files/11980394/lsp.log)

![1688727630852](https://github.com/ayamir/nvimdots/assets/61657399/bce98318-9c33-4740-89f8-98471b7c690a)
