### ISSUE TITLE
E5108: Error executing lua & E114: 缺少引号 & no such file or directory

### ISSUE THREAD

**Issue by WDayu** [ayamir/nvimdots#80]
**Describe the bug**

when you open some files, it will reveal some error messages like following.
```
处理 BufReadPost 自动命令 "*" 时发生错误:
E5108: Error executing lua ...vim/site/pack/packer/opt/packer.nvim/lua/packer/load.lua:165: Vim(echomsg):E114: 缺少引号: "Error in packer_compiled: ...vim/site/pack/p
acker/opt/packer.nvim/lua/packer/load.lua:155: Vim(lua):E5108: Error executing lua ...im/HEAD-2ef9d2a_1/share/nvim/runtime/lua/vim/lsp/rpc.lua:328: start `efm-langser
ver` failed: ENOENT: no such file or directory
stack traceback:
        [C]: in function 'cmd'
        ...vim/site/pack/packer/opt/packer.nvim/lua/packer/load.lua:165: in function <...vim/site/pack/packer/opt/packer.nvim/lua/packer/load.lua:161>
        [string ":lua"]:1: in main chunk
```
**To Reproduce**
Opening any file in my PC will see this error, and the message will disappear after <CR>.

**Screenshots**
<img width="740" alt="image" src="https://user-images.githubusercontent.com/43671213/150668489-d2bd3102-894e-4c47-a2f8-09a2e8fd639b.png">

**Environment (please complete the following information):**
 - OS: macOS 
 - Nvim version(output of `nvim --version`)
 
NVIM v0.6.0-dev+575-g2ef9d2a66
Build type: Release
LuaJIT 2.1.0-beta3
Features: +acl +iconv +tui

**Comment by ayamir** [comment]
![image](https://user-images.githubusercontent.com/61657399/150669004-8ff83162-3ec9-4075-847c-46955ea6124f.png)
Please install `efm-langserver` and add it to `PATH`.
