### ISSUE TITLE
Error when pressing q after typed `gd`

### ISSUE THREAD

**Issue by Lonjiazeng** [ayamir/nvimdots#805]
### Version confirmation

- [X] Confirm

### Following prerequisites

- [X] Confirm

### Neovim version

NVIM v0.9.1

### Operating system/version

archlinux

### Terminal name/version

WezTerm

### Branch info

main (Default/Latest)

### Fetch Preferences

SSH (use_ssh = true)

### How to reproduce the issue

Press `gd` at a function call, then `q`

### Expected behavior

Close the pop-up window

### Actual behavior

An error occurred：
![image](https://github.com/ayamir/nvimdots/assets/76612231/2a76a4bb-658d-4510-b7d3-6c0a63c89d87)

**Comment by Lonjiazeng** [comment]
Later I tested some other function calls, and it was a small number of functions that could trigger this error, but this function could keep triggering as long as it could trigger once

**Comment by Jint-lzxy** [comment]
We need a minimal sample & steps that can exactly reproduce this issue. u may upload such a file.

**Comment by Lonjiazeng** [comment]
I found this problem while writing a project that is currently rather large and I don't know how to shrink it down. I'll send you the address of this project.
 https://gitlab.eduxiji.net/202318123201313/compiler2023.git

**Comment by Lonjiazeng** [comment]
in src/ir/optimizer/simplify_cfg.rs, which has many function calls that can trigger errors

**Comment by Lonjiazeng** [comment]
such as `get_next_bb`

**Comment by CharlesChiuGit** [comment]
Seems like u better report this to the upstream issue?

**Comment by Lonjiazeng** [comment]
So who should I report to

**Comment by CharlesChiuGit** [comment]
> So who should I report to

https://github.com/nvimdev/lspsaga.nvim
