### ISSUE TITLE
some icons become ▯ when I upgrade to 3.0.0

### ISSUE THREAD

**Issue by Erzbir** [ayamir/nvimdots#827]
### Version confirmation

- [X] Confirm

### Following prerequisites

- [X] Confirm

### Neovim version

9.0.1

### Operating system/version

macOS ventura 13.4

### Terminal name/version

kitty 0.28.1

### $TERM environment variable

xterm-kitty

### Branch info

main (Default/Latest)

### Fetch Preferences

SSH (use_ssh = true)

### How to reproduce the issue

1. use kitty or my system terminal
2. run "nvim"

When I use old version, everything seems to normally, but I upgrade to 3.0.0 today, it occured

I forget which version I used, but I remember seeing a post written by its owner last November(?) and I used it

### Expected behavior

.

### Additional information

<img width="1680" alt="2023-06-28 17 31 35" src="https://github.com/ayamir/nvimdots/assets/100007608/8e1c03f6-b4ec-491a-92ea-55ade40130bd">

<img width="204" alt="2023-06-28 17 48 22" src="https://github.com/ayamir/nvimdots/assets/100007608/ee5c1de8-f613-41d9-bf65-8f66b51341a9">

<img width="1416" alt="2023-06-28 17 48 49" src="https://github.com/ayamir/nvimdots/assets/100007608/08857650-6e57-416d-a43c-1b783e5d76d8">

**Comment by Jint-lzxy** [comment]
Plz have a look at the [release notes](https://github.com/ayamir/nvimdots/releases/tag/v3.0.0) first:
https://github.com/ayamir/nvimdots/blob/56538b791d3354dd6a5af257be0bb3eaf52765bd/init.lua#L4-L19

**Comment by Erzbir** [comment]
I thought JetBrains Mono Nerd Font was....

> Plz have a look at the [release notes](https://github.com/ayamir/nvimdots/releases/tag/v3.0.0) first:
> 
> https://github.com/ayamir/nvimdots/blob/56538b791d3354dd6a5af257be0bb3eaf52765bd/init.lua#L4-L19

I thought JetBrains Mono Nerd Font was....

**Comment by Erzbir** [comment]
So I use which one for it?

**Comment by Jint-lzxy** [comment]
u need to have Nerd Font >`v3.0.0` installed. [Release v3.0.0 · ryanoasis/nerd-fonts](https://github.com/ryanoasis/nerd-fonts/releases/tag/v3.0.0):
> The old Material Design Icon codepoints are finally dropped. Due to an historic mistace we placed them in between some asiatic glyphs, breaking that script.
> Since v2.3.0 the (updated and expanded) Material Design Icons have new codepoints in the 5 digit region.

Restart your Mac so that it can cache correct fonts/glyphs.

btw starting from `v3.0.0`, please use the **`Mono` variant** (Nerd Font Mono _or_ NFM) as your GUI font.

**Comment by Erzbir** [comment]
> u need to have Nerd Font >`v3.0.0` installed. [Release v3.0.0 · ryanoasis/nerd-fonts](https://github.com/ryanoasis/nerd-fonts/releases/tag/v3.0.0):
> 
> > The old Material Design Icon codepoints are finally dropped. Due to an historic mistace we placed them in between some asiatic glyphs, breaking that script.
> > Since v2.3.0 the (updated and expanded) Material Design Icons have new codepoints in the 5 digit region.
> 
> Restart your Mac so that it can cache correct fonts/glyphs.
> 
> btw starting from `v3.0.0`, please use the **`Mono` variant** (Nerd Font Mono _or_ NFM) as your GUI font.

thanks ❤
