### ISSUE TITLE
`nvim-treesitter-context` not working

### ISSUE THREAD

**Issue by Saafo** [ayamir/nvimdots#828]
### Version confirmation

- [X] Confirm

### Following prerequisites

- [X] Confirm

### Neovim version

0.9.1

### Operating system/version

macOS 13.4

### Terminal name/version

Warp

### $TERM environment variable

xterm-256color

### Branch info

main (Default/Latest)

### Fetch Preferences

SSH (use_ssh = true)

### How to reproduce the issue

open a code file

### Expected behavior

show sticky header

### Actual behavior

no sticky header

### Additional information

Maybe we should call setup to make it works:

```diff
@@ -112,7 +112,12 @@ editor["nvim-treesitter/nvim-treesitter"] = {
 	config = require("editor.treesitter"),
 	dependencies = {
 		{ "nvim-treesitter/nvim-treesitter-textobjects" },
-		{ "nvim-treesitter/nvim-treesitter-context" },
+		{
+			"nvim-treesitter/nvim-treesitter-context",
+			config = function()
+				require("treesitter-context").setup()
+			end,
+		},
 		{ "mrjones2014/nvim-ts-rainbow" },
 		{ "JoosepAlviste/nvim-ts-context-commentstring" },
 		{ "mfussenegger/nvim-treehopper" },
```

**Comment by Jint-lzxy** [comment]
Can't reproduce this:
<img width="370" alt="截圖" src="https://github.com/ayamir/nvimdots/assets/50296129/8df6b37c-165e-4794-9f3d-f5e6ea55c788">

**Comment by Saafo** [comment]
> Can't reproduce this

Can reproduce on the latest commit in lua and swift files. Would you mind sync in Lazy and try again?

<img width="470" alt="image" src="https://github.com/ayamir/nvimdots/assets/46736350/7e5459f0-ab23-4a2b-b84f-7e0369269d74">

**Comment by ayamir** [comment]
@Jint-lzxy @Saafo Has repro, and add setup function will solve it 👍
