### ISSUE TITLE
packer_plugins is a nil value 

### ISSUE THREAD

**Issue by BilyZ98** [ayamir/nvimdots#83]
**Describe the bug**
There is an error prompt that the global value ```packer_plugins``` is a nil value when I press j or k  so the config file in keymap directory cannot index it.
Is anything wrong? I check the code and there is no explicit assignment to this value.

I have no problems downloading all the plugins and connecting to github.com.

**To Reproduce**
1. input ``` nvim ``` in the shell, 
2. then press any key of ``` j, k ```
3. then this error message will show up 

**Expected behavior**
No errors prompt

**Screenshots**'
![image](https://user-images.githubusercontent.com/26542149/151516702-30f29c10-4474-404d-8c8f-7bcd3c3d01b5.png)

**Environment (please complete the following information):**
 - OS: CentOS 7, kernel version 3.10
 - Nvim version 0.6.1

**Additional context**

**Comment by ayamir** [comment]
Have you installed `accelerated-jk`?
