### ISSUE TITLE
`lualine` flash with `andymass/vim-matchup`

### ISSUE THREAD

**Issue by volpan** [ayamir/nvimdots#832]
### Version confirmation

- [X] Confirm

### Following prerequisites

- [X] Confirm

### Neovim version

NVIM v0.10.0-dev-596+g7d0a23973b

### Operating system/version

Arch Linux x86_64 | 6.3.9-zen1-1-zen

### Terminal name/version

foot version: 1.14.0 +pgo +ime +graphemes -assertions

### $TERM environment variable

foot

### Branch info

main (Default/Latest)

### Fetch Preferences

SSH (use_ssh = true)

### How to reproduce the issue

1. Go to `@/lua/modules/utils/init.lua`
2. Scroll down with `j`

### Expected behavior

`lualine` work without flashing

### Actual behavior

it flashes

**Comment by Jint-lzxy** [comment]
@volpan I should have fixed this in #833 XD

**Comment by volpan** [comment]
The reason is that `vim-matchup` display the end/return of a structure in the status line, but then `lualine` 'fight back' :laughing:
