### ISSUE TITLE
Update repo's Topics?

### ISSUE THREAD

**Issue by Jint-lzxy** [ayamir/nvimdots#834]
### Feature description

IMO it would be great to add the following topics to `About`, as this would make it easier for people to find this config :)
- [vim](https://github.com/topics/vim)
- [editor](https://github.com/topics/editor)
- [dotfiles](https://github.com/topics/dotfiles)
- [vimrc](https://github.com/topics/vimrc)
- [ide](https://github.com/topics/ide)
- [nvim](https://github.com/topics/nvim)
- [neovim-dotfiles](https://github.com/topics/neovim-dotfiles)
- [neovim-configuration](https://github.com/topics/neovim-configuration)
- [neovim-lua](https://github.com/topics/neovim-lua)
- [neovim-config](https://github.com/topics/neovim-config)
- [neovim-setup](https://github.com/topics/neovim-setup)
- [nvim-configs](https://github.com/topics/nvim-configs)

### Additional information

cc @ayamir

**Comment by ayamir** [comment]
OK.
