### ISSUE TITLE
zoxide切换目录报错

### ISSUE THREAD

**Issue by nkta3m** [ayamir/nvimdots#839]
### Version confirmation

- [X] Confirm

### Following prerequisites

- [X] Confirm

### Neovim version

NVIM v0.9.1 Build type: RelWithDebInfo LuaJIT 2.1.0-beta3

### Operating system/version

Windows 10

### Terminal name/version

Alacritty

### Branch info

main (Default/Latest)

### Fetch Preferences

HTTPS (use_ssh = false)

### How to reproduce the issue

使用zoxide切换目录报错

### Expected behavior

正确显示目录

### Additional information

![2023-07-04 11_31_36-Window](https://github.com/ayamir/nvimdots/assets/13484700/527325e7-e0fd-4eda-b56a-7dc64c28daae)

**Comment by CharlesChiuGit** [comment]
Seems like either u have a very big zoxide database or your computer is too slow to finish the task?

**Comment by nkta3m** [comment]
好象是db.zo的问题，删除后没问题了
