### ISSUE TITLE
Go 使用过程中出现两个不足

### ISSUE THREAD

**Issue by jiadsii** [ayamir/nvimdots#84]
我用neovim 写了个 go

不足：
1.go代码补全严重不足 就连  fmt.Println都不能自动补全
2.quickrun 过程没有输出
当按住ctrl+c 停止后 才有输出 ，这对web项目及其不友好
3.还有为啥Mac的电脑 图标还是 Linux的
就是右下角那是个企鹅。不该是个苹果吗

**Comment by jiadsii** [comment]
建议：玩善go 语言的自动补全，
以及web项目 quickrun 后没有输出的问题

**Comment by jiadsii** [comment]
<img width="1280" alt="截屏2022-01-30 上午2 09 54" src="https://user-images.githubusercontent.com/45071541/151672364-f757e86e-8f59-473b-8c7e-af238c1ccff8.png">

**Comment by jiadsii** [comment]
<img width="1280" alt="截屏2022-01-30 上午2 13 48" src="https://user-images.githubusercontent.com/45071541/151672517-5600b4f0-80ad-458e-bb20-55ebced68511.png">

**Comment by jiadsii** [comment]
还有为啥Mac的电脑 图标还是 Linux的

**Comment by ayamir** [comment]
> <img alt="截屏2022-01-30 上午2 13 48" width="1280" src="https://user-images.githubusercontent.com/45071541/151672517-5600b4f0-80ad-458e-bb20-55ebced68511.png">

这个情况明显是因为你没有启动LSP，你执行`LspInfo`看一下

**Comment by ayamir** [comment]
至于苹果的icon这个是由lualine自动检测你的换行符得出来的。
Windows - CRLF
Linux  - LF
Macintosh (Mac OSX) - LF
Macintosh (old) - CR

**Comment by ayamir** [comment]
quickrun本就不适合这种情况，web项目建议你用toggleterm直接终端执行操作

**Comment by jiadsii** [comment]
<img width="1280" alt="截屏2022-01-30 下午5 47 41" src="https://user-images.githubusercontent.com/45071541/151694772-ca591f88-12fa-4219-bc7e-837d621d8427.png">

我是用LspInfo 它提示没有这个命令

**Comment by ayamir** [comment]
你要在打开文件之后执行，这个插件会在`BufferRead`之后才加载

**Comment by jiadsii** [comment]
的确是这样
