### ISSUE TITLE
The Error "StopHL", when I use <A-d> to open floating terminal

### ISSUE THREAD

**Issue by Penguin-SAMA** [ayamir/nvimdots#844]
### Version confirmation

- [X] Confirm

### Following prerequisites

- [X] Confirm

### Neovim version

NVIM v0.9.1

### Operating system/version

macos 14

### Terminal name/version

iTerm2 3.4.19

### Branch info

main (Default/Latest)

### Fetch Preferences

SSH (use_ssh = true)

### How to reproduce the issue

1. use <A-d> to open floating teminal

### Expected behavior

open floating terminal

### Actual behavior

<img width="1709" alt="image" src="https://github.com/ayamir/nvimdots/assets/50973632/c358c1f1-c64a-4681-97f6-7c625a35aadd">

**Comment by Jint-lzxy** [comment]
What did you do in the terminal? Or you just opened one and the error popped up?

Added to that, what is the output of the following commands:
```shell
1. echo "$0" && eval "$SHELL --version"
2. locale
```

**Comment by Penguin-SAMA** [comment]
sorry, I can't reproduce this error.
I'll let you know if it comes up again.
