### ISSUE TITLE
Several plugins maybe need to be replaced?

### ISSUE THREAD

**Issue by boomker** [ayamir/nvimdots#847]
### Discussed in https://github.com/ayamir/nvimdots/discussions/846

<div type='discussions-op-text'>

<sup>Originally posted by **boomker** July  8, 2023</sup>

[phaazon/hop.nvim](https://github.com/phaazon/hop.nvim) --> [flash.nvim](https://github.com/folke/flash.nvim)
or
[phaazon/hop.nvim](https://github.com/phaazon/hop.nvim) --> [smoka7/hop.nvim](https://github.com/smoka7/hop.nvim)

[p00f/nvim-ts-rainbow](https://github.com/p00f/nvim-ts-rainbow) --> [HiPhish/rainbow-delimiters.nvim](https://github.com/HiPhish/rainbow-delimiters.nvim)

----
`nvim-ts-rainbow` + `bufdel`  这两个插件在我这里总是出现这样的报错:
> Vim: Error executing Lua callback: Vim:E315: ml_get: invalid num: 1

我现在用 `rainbow-delimiters` + `mini-bufremove`  这两插件替换了之后就没有这样的问题</div>

**Comment by fecet** [comment]
Some of my thoughts: https://github.com/ayamir/nvimdots/discussions/773 https://github.com/folke/flash.nvim/issues/52

**Comment by ayamir** [comment]
> nvim-ts-rainbow + bufdel 这两个插件在我这里总是出现这样的报错:
> Vim: Error executing Lua callback: Vim:E315: ml_get: invalid num: 1

Open a new issue for itself.

**Comment by boomker** [comment]
> > nvim-ts-rainbow + bufdel 这两个插件在我这里总是出现这样的报错:
> > Vim: Error executing Lua callback: Vim:E315: ml_get: invalid num: 1
> 
> Open a new issue for itself.

这个问题在 `rainbow-delimiters.nvim`得到了很大程度的解决,  该插件的作者分析认为这个报错可能和 `neovim` 有关系

**Comment by boomker** [comment]
> Some of my thoughts: #773 [folke/flash.nvim#52](https://github.com/folke/flash.nvim/issues/52)

你可以看看这款插件  [mini.surround](https://github.com/echasnovski/mini.surround),  但是它没能和 `hop`、`leap` 结合, 只是在 surround operations  有更好的体验了

**Comment by fecet** [comment]
null-ls also will be archived https://github.com/jose-elias-alvarez/null-ls.nvim/issues/1621
