### ISSUE TITLE
当我用:w进行保存的时候出现 一些错误提示

### ISSUE THREAD

**Issue by jiadsii** [ayamir/nvimdots#85]
**Describe the bug**

**To Reproduce**
错误代码提示

**Expected behavior**
用neovim 编写一个hello.go
用:w想进行保存 出现如下问题

**Screenshots**
<img width="1280" alt="截屏2022-01-30 上午2 30 20" src="https://user-images.githubusercontent.com/45071541/151673058-65b6a9c7-673b-4f6a-ba29-ffb89183851d.png">

**Environment (please complete the following information):**
 - OS: [macOS]
 - Nvim version(0.7.0)

**Additional context**

**Comment by ayamir** [comment]
pull一下试试

**Comment by jiadsii** [comment]
pull之后，:w没有了错误
