### ISSUE TITLE
How to set the input method to switch automatically

### ISSUE THREAD

**Issue by fakeczg** [ayamir/nvimdots#856]
### Feature description

How to set the input method to switch automatically, for example, input Chinese in INSERT mode, this time back to normal mode, automatically switch to English mode;

**Comment by CharlesChiuGit** [comment]
we already have fcitx5.nvim configed, just kept it commented out. check it's doc.

**Comment by ayamir** [comment]
https://github.com/ayamir/nvimdots/blob/bf7f33ec6d57e5371c1b0abbee2929625782cb67/lua/modules/plugins/tool.lua#L7-L13

**Comment by fecet** [comment]
fcitx5.nvim caused serious performance problem for me

**Comment by ayamir** [comment]
> fcitx5.nvim caused serious performance problem for me

Because I rarely use this feature, you can investigate it on your own and make a pr to replace `fcitx5.nvim` if possible.

**Comment by fecet** [comment]
> Because I rarely use this feature, you can investigate it on your own and make a pr to replace `fcitx5.nvim` if possible.

Just a reminder, I also rarely use this.

**Comment by CharlesChiuGit** [comment]
Close as no further response.
