### ISSUE TITLE
Virtual text of diagnostics working strangely

### ISSUE THREAD

**Issue by Rinyaresu** [ayamir/nvimdots#858]
### Version confirmation

- [X] Confirm

### Following prerequisites

- [X] Confirm

### Neovim version

NVIM v0.9.1

### Operating system/version

Linux

### Terminal name/version

Kitty 0.28.1

### Branch info

main (Default/Latest)

### Fetch Preferences

HTTPS (use_ssh = false)

### How to reproduce the issue

1. Disable virtual_text
2. Enter on a file
3. Edit file writing something that would bring up the diagnostics

### Expected behavior

No diagnostic related virtual text should appear

### Actual behavior

The text appears anyway, and in an unusual place
![image](https://github.com/ayamir/nvimdots/assets/79602114/1e6957f5-11fe-412e-beff-9cdb21babaee)

**Comment by Rinyaresu** [comment]
Just disable this line: https://github.com/ayamir/nvimdots/blob/bf7f33ec6d57e5371c1b0abbee2929625782cb67/lua/modules/configs/completion/lspsaga.lua#L72

**Comment by CharlesChiuGit** [comment]
it's not a bug, it's lspsaga's feature.
