### ISSUE TITLE
请问下 再次打开nvim ,按u 还能 撤销 (保存已经关闭的文件的操作历史记录) 的 插件 叫什么名字 

### ISSUE THREAD

**Issue by ifnk** [ayamir/nvimdots#86]
**Describe the bug**
如题

**To Reproduce**
1. neovim 编辑 aaa.txt 
2. wq退出
3. neovim 再次编辑  aaa.txt
4. 按u 撤销 
5. 原生的 vim/nvim 这样是不行的， 应该是装了插件吧？ 不知道这个插件的名字……

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
 - OS: [e.g. Archlinux/Ubuntu/macOS]
 - Nvim version(output of `nvim --version`)

**Additional context**

**Comment by ayamir** [comment]
It's vim/neovim's feature call *Persistent Undo history*.
Refer to this: https://jovicailic.org/2017/04/vim-persistent-undo/

**Comment by ifnk** [comment]
> It's vim/neovim's feature called _Persistent Undo history_. Refer to this: https://jovicailic.org/2017/04/vim-persistent-undo/

谢谢！
