### ISSUE TITLE
the diagnostic info do not show when using copilot

### ISSUE THREAD

**Issue by zengjq666** [ayamir/nvimdots#860]
### Version confirmation

- [X] Confirm

### Following prerequisites

- [X] Confirm

### Neovim version

NVIM v0.10.0-dev

### Operating system/version

ubuntu 20.04

### Terminal name/version

wezterm

### Branch info

main (Default/Latest)

### Fetch Preferences

SSH (use_ssh = true)

### How to reproduce the issue

writing golang codes with copilot

### Expected behavior

Show the diagnostic info once use ctrl + s.
Or I can temporarily disable the copilot plugins and enable it at any time.

**Comment by Jint-lzxy** [comment]
Sorry I can't understand what you mean. What you want to report is `copilot` failed to provide completion items _(p.s., it does NOT generate any sort of diagnostic information)_; temporarily prevent `copilot` from generating completion items or something else?

**Comment by CharlesChiuGit** [comment]
I think his talking about the ghost texts?

**Comment by zengjq666** [comment]
> Sorry I can't understand what you mean. What you want to report is `copilot` failed to provide completion items _(p.s., it does NOT generate any sort of diagnostic information)_; temporarily prevent `copilot` from generating completion items or something else?

就是当我用copilot时，编辑器似乎无法给我显示代码错误的诊断信息了。

**Comment by CharlesChiuGit** [comment]
Never heard that before, how to reproduce it?

**Comment by Jint-lzxy** [comment]
Also, have you changed any [settings](https://github.com/ayamir/nvimdots/blob/main/lua/core/settings.lua)? Did u do `:Copilot auth`? and what does `:LspInfo` give you?

**Comment by zengjq666** [comment]
Sorry,I found that the problem of not displaying diagnostic information has nothing to do with copilot.
