### ISSUE TITLE
clang-format off/on doesn't work

### ISSUE THREAD

**Issue by Penguin-SAMA** [ayamir/nvimdots#862]
### Version confirmation

- [X] Confirm

### Following prerequisites

- [X] Confirm

### Neovim version

NVIM v0.9.0-dev-1312+g908494889

### Operating system/version

macos 14

### Terminal name/version

iTerm2 3.4.19

### Branch info

main (Default/Latest)

### Fetch Preferences

SSH (use_ssh = true)

### Affected language servers

clang-format

### How to reproduce the issue

//clang-format off
...code 
//clang-format on 

<img width="557" alt="image" src="https://github.com/ayamir/nvimdots/assets/50973632/7b54dcaa-0c02-4fcb-9daa-9640b0aee2b7">

: w

<img width="526" alt="image" src="https://github.com/ayamir/nvimdots/assets/50973632/9d3e7fe8-68e7-42b9-bb13-8f90a1f9fee2">

### Actual behavior

they are still modified

### Expected behavior

not modified

### Support info

<img width="2004" alt="image" src="https://github.com/ayamir/nvimdots/assets/50973632/0fcf8ac8-447e-40aa-9a25-17d3f55a95e4">
<img width="2560" alt="image" src="https://github.com/ayamir/nvimdots/assets/50973632/70090bda-475c-4e8e-9bcc-9a574441f66e">

**Comment by Jint-lzxy** [comment]
There must be a whitespace between `//` and `clang-format <....>`:
```console
// clang-format off
  ^
```

**Comment by Penguin-SAMA** [comment]
thanks!
