### ISSUE TITLE
Very slow scroll

### ISSUE THREAD

**Issue by fecet** [ayamir/nvimdots#866]
### Version confirmation

- [X] Confirm

### Following prerequisites

- [X] Confirm

### Neovim version

NVIM v0.9.1

### Operating system/version

Arch linux

### Terminal name/version

alacritty

### $TERM environment variable

xterm-256color

### Branch info

main (Default/Latest)

### Fetch Preferences

SSH (use_ssh = true)

### How to reproduce the issue

Open a relative large file (like 3000 loc) with `clangd` or `pyright`

### Expected behavior

Scroll is smooth as opened without plugin

### Additional information

![slow](https://github.com/ayamir/nvimdots/assets/41792945/e5b5f043-3056-481e-b656-ba0fe7b9b4dd)

 It appears to be due to an LSP  issue, as pylsp is significantly faster than pyright, but it may not be directly caused by pyright itself. This is because a similar phenomenon is observed on clangd as well. I suspect it is caused by a poorly supported plugin, but I haven't found the exact cause yet.

**Comment by fecet** [comment]
https://github.com/HiPhish/rainbow-delimiters.nvim/issues/12

comment this give me huge speed up

**Comment by fecet** [comment]
@HATTER-LONG do you still use this neovim config?

**Comment by HATTER-LONG** [comment]
I am still using this configuration, but after updating the configuration from upstream, I always encounter strange  problems with some overly new plugins 😭

**Comment by fecet** [comment]
I share the same feeling too. I hope there can be more testing when adding new plugins.

**Comment by ayamir** [comment]
@HATTER-LONG Seems like you has solved it, can you open a pr for it?

**Comment by HATTER-LONG** [comment]
ok, I will do this work later, I need to test how many error detections are suitable for most projects.

**Comment by HATTER-LONG** [comment]
@fecet  
Oh, I just took a closer look at your question and the file you opened did not trigger `bigfile`, did it?
I just create PR only works in the case of large files 😓
Maybe you need try this `configs/editor/rainbow_delims.lua `：

```lua
	local function check_error_and_hgive_up()
		local parser = vim.treesitter.get_parser()
		local errors = 100
		parser:for_each_tree(function(tree)
			if tree:root():has_error() and errors >= 0 then
				errors = errors - 1
			else
				return nil
			end
		end)
		if errors < 0 then
			return nil
		end
		return require("rainbow-delimiters").strategy["global"]
	end

	vim.g.rainbow_delimiters = {
		strategy = {
			[""] = check_error_and_hgive_up,
		},

```

**Comment by fecet** [comment]
much better now

**Comment by Jint-lzxy** [comment]
Hang on a bit - we haven't found the root cause of this issue yet. It's quite unusual to have so many parsing errors in a file that can be compiled correctly 🤔 I'll look into this later, but let me reopen this issue first as a reminder :)

> I hope there can be more testing when adding new plugins.

Indeed and sorry about this. We'll cover different types of large files in future plugin alternations.

**Comment by fecet** [comment]
I am still experienced slow scroll on pyright，anyone can switch from pylsp to pyright to confirm？

**Comment by Jint-lzxy** [comment]
Turns out that this is indeed related to macro expansions, as _(ever since its creation)_ `treesitter-(c|cpp)` has no gurantee on understanding macros. The issue here is errors propagate _extensively_ starting at the very first misinterpreted statement, resulting in a very high AST. Consider the following simplified example:
```c
#ifdef __cplusplus
extern "C" {
#endif

_LIBCPP_INLINE_VISIBILITY int _v1;

#ifdef __cplusplus
}
#endif
```
Would produce:
```console
translation_unit [0, 0] - [9, 0]
  preproc_ifdef [0, 0] - [8, 6]
    name: identifier [0, 7] - [0, 18]
    linkage_specification [1, 0] - [7, 1]
      value: string_literal [1, 7] - [1, 10]
      body: declaration_list [1, 11] - [7, 1]
        preproc_call [2, 0] - [4, 0]
          directive: preproc_directive [2, 0] - [2, 6]
        declaration [4, 0] - [4, 34]
          type: type_identifier [4, 0] - [4, 25] <--- Error started to propagate here
          declarator: identifier [4, 26] - [4, 29] <--- Affected node
          ERROR [4, 30] - [4, 33] <--- Affected subtree
            identifier [4, 30] - [4, 33]

<<< The remaining parts were incorrectly parsed >>>

        preproc_ifdef [6, 0] - [6, 18]
          name: identifier [6, 7] - [6, 18]
          MISSING #endif [6, 18] - [6, 18] <--- Well... What's this? (ERROR in nvim)
```

**Comment by Jint-lzxy** [comment]
> I am still experienced slow scroll on pyright，anyone can switch from pylsp to pyright to confirm？

But generally LSPs would never interfere with the UI, as they are two completely unrelated components. It is also possible that `pyright`'s index procedure caused performance degradation, indirectly affecting UI rendering. I'm writing a fix focusing on handling plugins' load orders. See if the issue would be alleviated after this PR?

**Comment by Jint-lzxy** [comment]
I want to get some feedback. Would you mind if `nvim-treesitter` is lazy-loaded? The direct impact is when the editor is opened at the very beginning, users need to wait for a few seconds before syntax highlighting gets applied, which means in the first few seconds, users will see completely white text with nothing highlighted (and then "flashes" since hls are applied).


cc @HATTER-LONG @fecet @ayamir @CharlesChiuGit

**Comment by fecet** [comment]
> I want to get some feedback. Would you mind if `nvim-treesitter` is lazy-loaded? The direct impact is when the editor is opened at the very beginning, users need to wait for a few seconds before syntax highlighting gets applied, which means in the first few seconds, users will see completely white text with nothing highlighted (and then "flashes" since hls are applied).
> 
> cc @HATTER-LONG @fecet @ayamir @CharlesChiuGit

It's okay for me if I can restrict this to only happen for python as I only face performance issue in python and pyright also need several seconds to start, at that time neovim is completely freeze

**Comment by fecet** [comment]
Using neovim 9.1 instead of the nightly build also eliminates the occurrence of stutter. So it may also relevant to https://github.com/neovim/neovim/issues/23291

**Comment by HATTER-LONG** [comment]
> I want to get some feedback. Would you mind if `nvim-treesitter` is lazy-loaded? The direct impact is when the editor is opened at the very beginning, users need to wait for a few seconds before syntax highlighting gets applied, which means in the first few seconds, users will see completely white text with nothing highlighted (and then "flashes" since hls are applied).
> 
> cc @HATTER-LONG @fecet @ayamir @CharlesChiuGit

I think this is acceptable. The performance problem affects my experience most, especially in the Header file files provided by a large number of manufacturers in embedded development will make the editor feel sluggish

**Comment by CharlesChiuGit** [comment]
> I want to get some feedback. Would you mind if `nvim-treesitter` is lazy-loaded? The direct impact is when the editor is opened at the very beginning, users need to wait for a few seconds before syntax highlighting gets applied, which means in the first few seconds, users will see completely white text with nothing highlighted (and then "flashes" since hls are applied).
> 
> cc @HATTER-LONG @fecet @ayamir @CharlesChiuGit

If it's possible to set the plugin loading order as a user config?
Personally I seldom deal with large files, I often need to jump around lots of small files very quickly. So I would prefer to open the files and everything is ready to go.

**Comment by Jint-lzxy** [comment]
> If it's possible to set the plugin loading order as a user config?

This is possible as we can dynamically determine plugins' `{ event }` key.
