### ISSUE TITLE
nvim-tree.lua doesn't open at first try

### ISSUE THREAD

**Issue by libertig** [ayamir/nvimdots#87]
**Describe the bug**
Can't open nvim-tree.

**To Reproduce**
1. Open any file to edit
2. :NvimTreeOpen or C+n
3. See error

**Expected behavior**
It should open normally, at first try.

**Screenshots**
<img width="1552" alt="Screen Shot 2022-02-09 at 08 11 36" src="https://user-images.githubusercontent.com/45043938/153188062-36da0df0-cb73-4c73-b7e8-49fadd90b71f.png">
<img width="1552" alt="Screen Shot 2022-02-09 at 08 11 55" src="https://user-images.githubusercontent.com/45043938/153188134-a4c5df9e-7b5f-4bbe-8bc7-e8db99f33a46.png">

**Environment**
 - OS: macOS
 - Nvim version: 0.6.1

**Additional context**
I noticed that if you try to open again, when the error displays and a new tab opened, it magically opens on the third tab.

**Comment by ayamir** [comment]
Thanks for your report, I just update the way to load `nvim-tree` to use `event = "BufRead"`, seems like fixed.
Please update to latest config.

**Comment by ttbug** [comment]
> Thanks for your report, I just updated the way to load `nvim-tree` to use `event = "BufRead"`, seems like fixed. Please update to latest config.

这样修改的话好像设置的快捷键就不生效了。nvim-tree新版本已经解决了这个问题

**Comment by ayamir** [comment]
> > Thanks for your report, I just updated the way to load `nvim-tree` to use `event = "BufRead"`, seems like fixed. Please update to latest config.
> 
> 这样修改的话好像设置的快捷键就不生效了。nvim-tree新版本已经解决了这个问题

没有吧，用之前cmd的方式还是会出现错误
