### ISSUE TITLE
`Lspsaga outline` got an error after try to jump to a symbol in python.

### ISSUE THREAD

**Issue by nkta3m** [ayamir/nvimdots#873]
### Version confirmation

- [X] Confirm

### Following prerequisites

- [X] Confirm

### Neovim version

NVIM0.9.1

### Operating system/version

Arch 6.1

### Terminal name/version

Alacritty

### Branch info

main (Default/Latest)

### Fetch Preferences

HTTPS (use_ssh = false)

### How to reproduce the issue

打开一个py文件
输入 go
选择一个变量或函数
回车

### Expected behavior

正常跳转

### Additional information

![shot-2023-07-18_08-38-37](https://github.com/ayamir/nvimdots/assets/13484700/b8b365a4-cb40-4913-a97a-5eb6071829a5)

**Comment by CharlesChiuGit** [comment]
Can reproduce, but it seem like a upstream issue. please report to https://github.com/nvimdev/lspsaga.nvim/issues

**Comment by CharlesChiuGit** [comment]
I'm guessing it's about which language sever too. Maybe u can try other python language server before reporting it.

**Comment by ayamir** [comment]
Seems `lspsaga` doesn't support `pylsp`. I tried `jedi` and works fine.

**Comment by nkta3m** [comment]
solved after update lspsaga.

**Comment by CharlesChiuGit** [comment]
specifically this commit: https://github.com/nvimdev/lspsaga.nvim/commit/e249a41dd2d965c9c2c50c9dc5f8019519231661
