### ISSUE TITLE
补全提示图标疑问

### ISSUE THREAD

**Issue by qianxi0410** [ayamir/nvimdots#89]
![图片](https://user-images.githubusercontent.com/55543743/154842852-a0d7e68d-8870-4caf-8fc3-ccf94d3e6390.png)

你好，请问这是什么插件吗， `coc` 能不能做到像这样的补全提示图标效果。

**Comment by ayamir** [comment]
这是`nvim-cmp`的专属配置效果：https://github.com/ayamir/nvimdots/blob/main/lua/modules/completion/config.lua#L212-L240
`coc`能否做到并不清楚

**Comment by qianxi0410** [comment]
感谢解答！

**Comment by qianxi0410** [comment]
如果有人同样使用coc想做到这种效果，可以试试 `suggest.completionItemKindLabels`。
