### ISSUE TITLE
neovim-nightly cannot convert given lua table for lsp

### ISSUE THREAD

**Issue by CharlesChiuGit** [ayamir/nvimdots#893]
### Version confirmation

- [X] Confirm

### Following prerequisites

- [X] Confirm

### Neovim version

v0.10.0-dev-709+gce56ad2ba

### Operating system/version

ubuntu 22.04

### Terminal name/version

wezterm 20230420-215610-ff153a92

### $TERM environment variable

xterm-256color

### Branch info

main (Default/Latest)

### Fetch Preferences

HTTPS (use_ssh = false)

### How to reproduce the issue

1. update nvim-nightly
2. update all plugins
3. open any lua file

### Expected behavior

fix the bug

### Actual behavior

```txt
Error executing vim.schedule lua callback: /home/charles/tools/nvim/share/nvim/runtime/lua/vim/lsp.lua:1579: Cannot convert given lua table
stack traceback:
        [C]: in function 'nvim_exec_autocmds'
        /home/charles/tools/nvim/share/nvim/runtime/lua/vim/lsp.lua:1579: in function </home/charles/tool/nvim/share/nvim/runtime/lua/vim/lsp.lua:1578>
```

![圖片](https://github.com/ayamir/nvimdots/assets/32497323/fa82567b-b6d0-414f-88e3-6b1335edfdc0)

### Additional information

I think it's just about some of our lsp's config not fitting with nvim-nightly, like `lua_ls`.
I scaned the neovim repo's issue real quick and didn't find any issue similar.
I haven't got the time to trace the issue, just put it here as a reminder.

**Comment by Jint-lzxy** [comment]
> I think it's just about some of our lsp's config not fitting with nvim-nightly, like `lua_ls`.

I suspect this is an upstream issue, as stack backtrace does not involve any user-related information.

**Comment by CharlesChiuGit** [comment]
![圖片](https://github.com/ayamir/nvimdots/assets/32497323/502a0d7d-4966-4a4b-b6b0-0639fb3dcfcf)

Looks like it's been triggered by a new event: `LspNotify` in nvim-nightly.

**Comment by CharlesChiuGit** [comment]
https://github.com/neovim/neovim/pull/24411

https://github.com/neovim/neovim/pull/24469

**Comment by CharlesChiuGit** [comment]
@Jint-lzxy do u also got this error?

**Comment by Jint-lzxy** [comment]
@CharlesChiuGit I'm usually on the latest master but haven't encountered this in the past few days... So I never knew what's going on here 😢 I have:
```console
NVIM v0.10.0-dev-735+g8fe9f41f7-Homebrew
Build type: Release
LuaJIT 2.1.0-beta3

        系統 vimrc 設定檔: "$VIM/sysinit.vim"
              $VIM 預設值: "/usr/local/Cellar/neovim/HEAD-8fe9f41/share/nvim"
                                                            ^ this commit
Run :checkhealth for more info
```

**Comment by CharlesChiuGit** [comment]
Seems like it's related to my other personal config, didn't find any error on 0.10 branch of this repo.
close it for now.

**Comment by Jint-lzxy** [comment]
@CharlesChiuGit Try debugging your `lspsaga.winbar` configs? I'm pretty sure this comes from the autocmd registered by Lspsaga:
```console
執行 LspAttach Autocommands: "*"
autocommand <Lua 1150: ~/.local/share/nvim/site/lazy/lspsaga.nvim/lua/lspsaga/symbol/head.lua:165>

Error executing vim.schedule lua callback: ...r/neovim/HEAD-8fe9f41/share/nvim/runtime/lua/vim/lsp.lua:1579: Cannot convert given lua table
stack traceback:
	[C]: in function 'nvim_exec_autocmds'
	...r/neovim/HEAD-8fe9f41/share/nvim/runtime/lua/vim/lsp.lua:1579: in function <...r/neovim/HEAD-8fe9f41/share/nvim/runtime/lua/vim/lsp.lua:1578>
````

**Comment by Jint-lzxy** [comment]
Reopening b/c I hope we could eschew this issue here as well.

**Comment by CharlesChiuGit** [comment]
seems like it's related to a **NEW** version of lspsaga config. trying to locate the issue...

**Comment by Jint-lzxy** [comment]
Hmm is this issue still present after disabling lspsaga?

**Comment by CharlesChiuGit** [comment]
> Hmm is this issue still present after disabling lspsaga?

indeed

**Comment by Jint-lzxy** [comment]
Try replacing `lsp.lua` with one that is not problematic and gradually resetting those hunks to see where the problem is?

**Comment by CharlesChiuGit** [comment]
ok I found the problem, it's about my `lua_ls` config.

My old one: https://github.com/CharlesChiuGit/nvimdots.lua/blob/df6576052e3d72f8a76e59457c0101203c634d42/lua/modules/configs/completion/servers/lua_ls.lua

The updated version:
```lua
-- https://github.com/neovim/nvim-lspconfig/blob/master/lua/lspconfig/server_configurations/lua_ls.lua

return {
	settings = {
		Lua = {
			runtime = {
				version = "LuaJIT",
			},
			diagnostics = {
				enable = true,
				globals = { "vim" },
				disable = { "different-requires" },
			},
			workspace = {
				library = {
					[vim.fn.expand("$VIMRUNTIME/lua")] = true,
					[vim.fn.expand("$VIMRUNTIME/lua/vim/lsp")] = true,
				},
				maxPreload = 2000,
				preloadFileSize = 1000,
			},
			hint = { enable = true, setType = true },
			format = { enable = false },
			telemetry = { enable = false },
			-- Do not override treesitter lua highlighting with lua_ls's highlighting
			semantic = { enable = false },
		},
	},
}
```

**Comment by CharlesChiuGit** [comment]
One possible reason the old config break might b/c I used to specify `Lua`, `luaJIT`, `Luarocks` in my shell envㄝbut now I use `asdf-vm` to manage all lang's version. 

Manually specify the `lua_runtime` might confuse nvim being confuse which lua should it listen to (I guess? I'm too tired to test now lol).

Now I remove the manually installed lua and remove specifying runtime path in `lua_ls.lua`. Things looks fine now.

**Comment by Jint-lzxy** [comment]
> P.S. `lspsaga` got nothing to do with this error, glepnir is doing a great job lol

So lspsaga is also confused lol
~~He's just doing what he should do - propagate the error~~

**Comment by CharlesChiuGit** [comment]
> So lspsaga is also confused lol
> 
> ~~He's just doing what he should do - propagate the error~~

lol indeed, i wasted so much time debugging lspsaga config.

**Comment by Jint-lzxy** [comment]
> lol indeed, i wasted so much time debugging lspsaga config.

Yeah autocmds are _always_ very difficult to debug - stack backtraces (even logs) rarely yield useful information :(
