### ISSUE TITLE
E492: Not an editor command: FormatWrite

### ISSUE THREAD

**Issue by xuzhanhh** [ayamir/nvimdots#90]
**Describe the bug**

1. 指令<C-A-l> 显示错误 E492: Not an editor command: FormatWrite
2. :w 保存时没有自动 format  （已选择FormatEnable）

**Screenshots**

**Environment (please complete the following information):**
 - OS:  macOS
 - Nvim version: 6.1

**Comment by xuzhanhh** [comment]
是我哪里配置出问题了么emmm

**Comment by ayamir** [comment]
具体是格式化什么文件？对应的formatter能不能在`PATH`中找到？

**Comment by xuzhanhh** [comment]
.ts .tsx, PATH里 prettier eslint都有的

**Comment by xuzhanhh** [comment]
<img width="720" alt="image" src="https://user-images.githubusercontent.com/20735181/154919853-d24b0b0e-f3cf-4b59-bcc1-9d1f91a4438a.png">

这里的format是生效的

**Comment by ayamir** [comment]
手动执行: `lua vim.lsp.buf.formatting_sync()`有用吗？

**Comment by xuzhanhh** [comment]
> 手动执行: `lua vim.lsp.buf.formatting_sync()`有用吗？

没效果 也没报错

**Comment by xuzhanhh** [comment]
<img width="713" alt="image" src="https://user-images.githubusercontent.com/20735181/154933251-b5c7669f-f9e5-4cd4-82e1-fedbd9b58f64.png">
缺少的应该也不是 typescript 需要的？我看 `lsp.lua` 只需要 `prettier` 和 `eslint`

**Comment by ayamir** [comment]
`efm-langserver`能在`PATH`中找到吗？

**Comment by xuzhanhh** [comment]
<img width="603" alt="image" src="https://user-images.githubusercontent.com/20735181/154937278-55e8b0fc-bbc2-45b0-a186-742efb17bb69.png">
应该是有的样子

**Comment by ayamir** [comment]
你创建配置文件看看log：
```
mkdir -p ~/.config/efm-langserver/
touch ~/.config/efm-langserver/config.yaml
```
里面输入：
```
version: 2
log-level: 1
log-file: /path/to/efm.log
```
`log-file`字段填绝对路径
之后再格式化一次退出来看一下日志里面的内容

**Comment by xuzhanhh** [comment]
<img width="507" alt="image" src="https://user-images.githubusercontent.com/20735181/154944967-7cc93d73-0c44-46eb-9022-9244fe9a12b9.png">
啊这。。。

**Comment by ayamir** [comment]
那还是`prettier`的问题吧？能手动用`prettier`格式化吗？打开这个文件之后执行`LspInfo`显示什么呢？

**Comment by xuzhanhh** [comment]
手动执行 `prettier` 是没问题的，能正确format
<img width="1101" alt="image" src="https://user-images.githubusercontent.com/20735181/154961965-21063194-54ec-4de7-9443-cdb7004daa7b.png">

`LspInfo` 需要的应该都装了
<img width="1570" alt="image" src="https://user-images.githubusercontent.com/20735181/154961599-6829544f-78c2-4e30-bacd-33556ed35410.png">

**Comment by ayamir** [comment]
我这边试着format了一下tsx文件是没有问题的，这就很奇怪了

**Comment by ayamir** [comment]
是不是你server装太多互相冲突了？我配置里面默认只禁用了`tsserver`的格式化功能：
https://github.com/ayamir/nvimdots/blob/main/lua/modules/completion/lsp.lua#L203-L209
你可以按照这个方式禁用一下其他的server，我这边测试时只有`tsserver`和`efm`

**Comment by xuzhanhh** [comment]
我排查了一下，对于 `.yaml` 文件 `prettier` 是会启动的:
```
2022/02/23 17:09:58 /usr/local/bin/prettier --stdin --stdin-filepath /Users/user/.config/efm-langserver/config.yaml: version: 2
log-level: 4
log-file: /Users/user/log/efm.log

2022/02/23 17:09:58 format succeeded
```

但是对于 `.tsx` 等 `js` 相关类型文件， `lsp` 会报这个错误：
```
[START][2022-02-23 17:23:35] LSP logging initiated
[ERROR][2022-02-23 17:23:35] .../vim/lsp/rpc.lua:420	"rpc"	"efm-langserver"	"stderr"	"2022/02/23 17:23:35 efm-langserver: reading on stdin, writing on stdout\n"
```

我猜测 `lsp` 这个 error 是由于 `efm` 的报错引起的：
```
2022/02/23 17:23:45 lint for LanguageID not supported: typescriptreact
```

但是为什么 `efm` 会报错，目前就不清楚了。。

**Comment by xuzhanhh** [comment]
另外我把这段代码反注释后，`tsserver` 是能够 `format` 代码的，但是意义不大，还是需要 `prettier` 的 `format` 才行
```
	["tsserver"] = function(opts)
		-- Disable `tsserver`'s format
		opts.on_attach = function(client)
			client.resolved_capabilities.document_formatting = false
			custom_attach(client)
		end
	end,
```

**Comment by xuzhanhh** [comment]
`lsp.lua` 这个文件变更后需要做什么操作才能更新到 `nvim` 么

**Comment by ayamir** [comment]
> `lsp.lua` 这个文件变更后需要做什么操作才能更新到 `nvim` 么
重启nvim即可

**Comment by ayamir** [comment]
> 我猜测 `lsp` 这个 error 是由于 `efm` 的报错引起的：

这error是lint的error，并不是format的error，你有照我说的那样做吗？

**Comment by xuzhanhh** [comment]
> > 我猜测 `lsp` 这个 error 是由于 `efm` 的报错引起的：
> 
> 这error是lint的error，并不是format的error，你有照我说的那样做吗？

我调整了 lsp.lua 的代码如下：
```lua
	["tsserver"] = function(opts)
		-- Disable `tsserver`'s format
		opts.on_attach = function(client)
			client.resolved_capabilities.document_formatting = false
			custom_attach(client)
		end
	end,
	["eslint"] = function(opts)
		opts.on_attach = function(client)
			client.resolved_capabilities.document_formatting = false
			custom_attach(client)
		end
	end,
	["efm"] = function(opts)
		opts.on_attach = function(client)
			client.resolved_capabilities.document_formatting = true
			custom_attach(client)
		end
```

然后 `efm.log` 中开始出现 
```
2022/02/24 15:15:50 format for LanguageID not supported: typescriptreact
```

我开始排查 `lsp` 与 `efm` 的关系，然后我找到了这个 pr https://github.com/mattn/efm-langserver/issues/24 , 从这个 pr 中可以看到，貌似 `lsp` 初始化 `efm` 的时候也会有相关的 log：

```
Tue Jan 14 14:33:52 2020:["lsp#register_server", "server registered", "solargraph"]
Tue Jan 14 14:33:52 2020:["lsp#register_server", "server registered", "efm-langserver"]
Tue Jan 14 14:33:52 2020:["lsp#register_server", "server registered", "javascript support using typescript-language-server"]
Tue Jan 14 14:33:52 2020:["lsp#register_server", "server registered", "pyls"]
Tue Jan 14 14:33:52 2020:["lsp#register_server", "server registered", "intelephense"]
Tue Jan 14 14:33:52 2020:["lsp#register_server", "server registered", "clangd"]
```

但是我的 `efm.log` 并没有这类型的 `log`, 请问大佬那边有相关的的`log` 么，如果大佬那边也有的话，那感觉上就是我这个`lsp` 启动 `efm` 的时候出问题了

**Comment by ayamir** [comment]
没有下面这种类型的bug，应该是版本迭代删掉了
```
2022/02/25 10:57:12 /usr/bin/eslint --no-color --format visualstudio --stdin: <text>(2,11): error : Parsing error: Unexpected token Nothing

1 problem

2022/02/25 10:57:12 
2022/02/25 10:57:16 /usr/bin/eslint --no-color --format visualstudio --stdin: <text>(2,11): error : Parsing error: Unexpected token Nothing

1 problem

2022/02/25 10:57:16 
2022/02/25 10:57:17 /usr/bin/prettier --stdin --stdin-filepath /home/ayamir/sample.tsx: /// <reference path='../../typings/index.d.ts' />
interface Nothing {}
class CommentBox extends React.Component<
    { url: string; pollInterval: number },
    CommentData
> {
    constructor() {
        super();
        this.state = { data: [] };
    }
    fetchComments() {
        $.ajax({
            url: this.props.url,
            dataType: "json",
            cache: false,
            success: (data) => this.setState({ data: data }),
            error: (xhr, status, err) => console.error(status, err)
        });
    }
    componentDidMount() {
        this.fetchComments();
        setInterval(this.fetchComments.bind(this), this.props.pollInterval);
    }
    render() {
        let handleCommentSubmit = (comment: {
            author: string;
            text: string;
        }) => {
            console.warn("comment submitted!", comment);
            const updated = this.state.data.slice(0);
            updated.push(comment);
            this.setState({ data: updated });
        };
        return (
            <div className="commentBox">
                <h1>Comments</h1>
                <CommentList data={this.state.data} />
                <CommentForm onCommentSubmit={handleCommentSubmit} />
            </div>
        );
    }
}

class CommentList extends React.Component<CommentData, Nothing> {
    render() {
        const nodes = this.props.data.map((comment) => (
            <Commentt author={comment.author}>{comment.text}</Commentt>
        ));
        return <div className="commentList">{nodes}</div>;
    }
}

class CommentForm extends React.Component<
    { onCommentSubmit: (t: { author: string; text: string }) => void },
    Nothing
> {
    render() {
        let handleSubmit = (e: React.FormEvent) => {
            e.preventDefault();
            const author = (
                this.refs["author"] as any as HTMLInputElement
            ).value.trim();
            const text = (
                this.refs["text"] as any as HTMLInputElement
            ).value.trim();
            if (author.length > 0 && text.length > 0) {
                this.props.onCommentSubmit({ author: author, text: text });
            }
        };

        return (
            <form className="commentForm" onSubmit={handleSubmit}>
                <input type="text" placeholder="Your name" ref="author" />
                <input type="text" placeholder="Say something..." ref="text" />
                <input type="submit" value="Post" />
            </form>
        );
    }
}

interface CommentProps {
    author: string;
    children?: string;
}

class Commentt extends React.Component<CommentProps, Nothing> {
    render() {
        return (
            <div className="comment">
                <h2 className="commentAuthor">{this.props.author}</h2>
                {this.props.children}
            </div>
        );
    }
}
interface CommentDataItem {
    author: string;
    text: string;
}
interface CommentData {
    data: Array<CommentDataItem>;
}

ReactDOM.render(
    <CommentBox url="/public/js/comments.json" pollInterval={5000} />,

    document.getElementById("content")
);

2022/02/25 10:57:17 format succeeded
```
我用的测试文件是  https://raw.githubusercontent.com/fernandezpablo85/react-typescript-tutorial/master/public/typescript/sample.tsx

**Comment by arsize** [comment]
我也遇到了一样的问题。
系统：macos m1 12.3
发现测试ts,tsx文件都无法格式化，但是lua文件可以正常格式化。
lsp.log输出：
[START][2022-03-30 04:10:36] LSP logging initiated
[ERROR][2022-03-30 04:10:36] .../vim/lsp/rpc.lua:420	"rpc"	"efm-langserver"	"stderr"	"2022/03/30 04:10:36 efm-langserver: no configuration file\n2022/03/30 04:10:36 efm-langserver: reading on stdin, writing on stdout\n"
[ERROR][2022-03-30 04:10:37] ...lsp/handlers.lua:404	"[tsserver] npm notice \nnpm notice New minor version of npm available! 8.1.2 -> 8.5.5\nnpm notice Changelog: <https://github.com/npm/cli/releases/tag/v8.5.5>\nnpm notice Run `npm install -g npm@8.5.5` to update!\nnpm notice \n"
[ERROR][2022-03-30 04:10:42] .../vim/lsp/rpc.lua:420	"rpc"	"efm-langserver"	"stderr"	"2022/03/30 04:10:42  --stdin --stdin-filepath /Users/arsize/Desktop/code/energy-storage/src/a.tsx: sh: --stdin: command not found\n\n"
[ERROR][2022-03-30 04:10:47] .../vim/lsp/rpc.lua:420	"rpc"	"efm-langserver"	"stderr"	"2022/03/30 04:10:47 jsonrpc2 handler: sending response 7: jsonrpc2: connection is closed\n2022/03/30 04:10:47 efm-langserver: connections closed\n"
[START][2022-03-30 04:10:55] LSP logging initiated
[ERROR][2022-03-30 04:10:55] .../vim/lsp/rpc.lua:420	"rpc"	"efm-langserver"	"stderr"	"2022/03/30 04:10:55 efm-langserver: no configuration file\n2022/03/30 04:10:55 efm-langserver: reading on stdin, writing on stdout\n"
[ERROR][2022-03-30 04:10:56] ...lsp/handlers.lua:404	"[tsserver] npm notice \nnpm notice New minor version of npm available! 8.1.2 -> 8.5.5\nnpm notice Changelog: <https://github.com/npm/cli/releases/tag/v8.5.5>\nnpm notice Run `npm install -g npm@8.5.5` to update!\nnpm notice \n"
[ERROR][2022-03-30 04:11:53] .../vim/lsp/rpc.lua:420	"rpc"	"efm-langserver"	"stderr"	"2022/03/30 04:11:53 jsonrpc2 handler: sending response 14: jsonrpc2: connection is closed\n2022/03/30 04:11:53 efm-langserver: connections closed\n"
[START][2022-03-30 04:12:18] LSP logging initiated

**Comment by arsize** [comment]
> 我也遇到了一样的问题。 系统：macos m1 12.3 发现测试ts,tsx文件都无法格式化，但是lua，go文件都可以正常格式化。 lsp.log输出： [START][2022-03-30 04:10:36] LSP logging initiated [ERROR][2022-03-30 04:10:36] .../vim/lsp/rpc.lua:420 "rpc" "efm-langserver" "stderr" "2022/03/30 04:10:36 efm-langserver: no configuration file\n2022/03/30 04:10:36 efm-langserver: reading on stdin, writing on stdout\n" [ERROR][2022-03-30 04:10:37] ...lsp/handlers.lua:404 "[tsserver] npm notice \nnpm notice New minor version of npm available! 8.1.2 -> 8.5.5\nnpm notice Changelog: https://github.com/npm/cli/releases/tag/v8.5.5\nnpm notice Run `npm install -g npm@8.5.5` to update!\nnpm notice \n" [ERROR][2022-03-30 04:10:42] .../vim/lsp/rpc.lua:420 "rpc" "efm-langserver" "stderr" "2022/03/30 04:10:42 --stdin --stdin-filepath /Users/arsize/Desktop/code/energy-storage/src/a.tsx: sh: --stdin: command not found\n\n" [ERROR][2022-03-30 04:10:47] .../vim/lsp/rpc.lua:420 "rpc" "efm-langserver" "stderr" "2022/03/30 04:10:47 jsonrpc2 handler: sending response 7: jsonrpc2: connection is closed\n2022/03/30 04:10:47 efm-langserver: connections closed\n" [START][2022-03-30 04:10:55] LSP logging initiated [ERROR][2022-03-30 04:10:55] .../vim/lsp/rpc.lua:420 "rpc" "efm-langserver" "stderr" "2022/03/30 04:10:55 efm-langserver: no configuration file\n2022/03/30 04:10:55 efm-langserver: reading on stdin, writing on stdout\n" [ERROR][2022-03-30 04:10:56] ...lsp/handlers.lua:404 "[tsserver] npm notice \nnpm notice New minor version of npm available! 8.1.2 -> 8.5.5\nnpm notice Changelog: https://github.com/npm/cli/releases/tag/v8.5.5\nnpm notice Run `npm install -g npm@8.5.5` to update!\nnpm notice \n" [ERROR][2022-03-30 04:11:53] .../vim/lsp/rpc.lua:420 "rpc" "efm-langserver" "stderr" "2022/03/30 04:11:53 jsonrpc2 handler: sending response 14: jsonrpc2: connection is closed\n2022/03/30 04:11:53 efm-langserver: connections closed\n" [START][2022-03-30 04:12:18] LSP logging initiated
---------------
解决了，原因是忘了安装prettier，我以为tsserver 像gopls那样自带format，原来也要依靠prettier来格式化？安装prettier之后就可以正常格式化了。
