### ISSUE TITLE
How to add vim-visual-multi?

### ISSUE THREAD

**Issue by Penguin-SAMA** [ayamir/nvimdots#901]
### Version confirmation

- [X] Confirm

### Following prerequisites

- [X] Confirm

### Neovim version

NVIM v0.9.0-dev-1312+g908494889

### Operating system/version

macos 14

### Terminal name/version

iTerm2 3.4.19

### Branch info

main (Default/Latest)

### Fetch Preferences

SSH (use_ssh = true)

### How to reproduce the issue

I have created custom file as required
but when i key `nvim *.cpp`
<img width="906" alt="image" src="https://github.com/ayamir/nvimdots/assets/50973632/31a35509-26c1-4e5e-b31f-0a36778964bd">
<img width="1775" alt="image" src="https://github.com/ayamir/nvimdots/assets/50973632/aa44eaae-2b11-4ac6-b2b7-da7565fe17f3">
But the plugin is working and available.
<img width="547" alt="image" src="https://github.com/ayamir/nvimdots/assets/50973632/e9251bd1-6779-4c09-8925-33e72714e781">

### Expected behavior

clear error

**Comment by Jint-lzxy** [comment]
Related: #691. Vim plugins typically do not have a `setup()` function, they instead use global variables to determine user configs.

**Comment by Penguin-SAMA** [comment]
Sorry, but I still don't know what should I fill in vim-visual-multi.lua

**Comment by Penguin-SAMA** [comment]
> [<img alt="@Penguin-SAMA" width="40" height="40" src="https://avatars.githubusercontent.com/u/50973632?s=80&amp;v=4">](/Penguin-SAMA)
> 
> Write Preview
> 
> 
> Attach files by dragging & dropping, selecting or pasting them.[ ](https://docs.github.com/github/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax)
>  Close with comment
> Comment
> Remember, contributions to this repository should follow our [GitHub Community Guidelines](https://docs.github.com/articles/github-community-guidelines).

Sorry, but I still don't know what should I fill in vim-visual-multi.lua

**Comment by Penguin-SAMA** [comment]
> Related: #691. Vim plugins typically do not have a `setup()` function, they instead use global variables to determine user configs.
Sorry, but I still don't know what should I fill in vim-visual-multi.lua

**Comment by Penguin-SAMA** [comment]
> Related: #691. Vim plugins typically do not have a `setup()` function, they instead use global variables to determine user configs.

Sorry, but I still don't know what should I fill in vim-visual-multi.lua

**Comment by CharlesChiuGit** [comment]
`:help visual-multi`

https://github.com/mg979/vim-visual-multi/wiki/Quick-start

**Comment by Jint-lzxy** [comment]
Example:
```lua
return function()
	vim.g.VM_maps["Find Under"] = "<C-d>" -- replace C-n
	vim.g.VM_maps["Find Subword Under"] = "<C-d>" -- replace visual C-n
	vim.g.VM_mouse_mappings = 1
end
```

**Comment by Penguin-SAMA** [comment]
Thanks!
