### ISSUE TITLE
Error while running the code

### ISSUE THREAD

**Issue by hemoumouda** [ayamir/nvimdots#904]
### Version confirmation

- [X] Confirm

### Following prerequisites

- [X] Confirm

### Neovim version

NVIM v0.9.1

### Operating system/version

Windows 10 22H2

### Terminal name/version

Windows Terminal 1.17.11461.0

### Branch info

main (Default/Latest)

### Fetch Preferences

SSH (use_ssh = true)

### How to reproduce the issue

1. Open any file.
2. Press \<leader\>r.
3. See error.

### Expected behavior

Run the code

### Actual behavior

![image](https://github.com/ayamir/nvimdots/assets/102949335/b5d1de7c-021f-44bf-9183-f464ebef48d8)

**Comment by CharlesChiuGit** [comment]
https://github.com/ayamir/nvimdots/wiki/Prerequisites#required-packages-installation-for-archlinux

u didn't follow the prerequisites, dont u?
