### ISSUE TITLE
[DAP] mason dap setup not call handle to init dap client

### ISSUE THREAD

**Issue by HATTER-LONG** [ayamir/nvimdots#910]
### Version confirmation

- [X] Confirm

### Following prerequisites

- [X] Confirm

### Neovim version

0.9.1

### Operating system/version

macos lastest

### Terminal name/version

kitty

### Branch info

main (Default/Latest)

### Fetch Preferences

SSH (use_ssh = true)

### How to reproduce the issue

1. create a demo cpp: main.cpp
2. open file directly through nvim: nvim main.cpp
3. test command: `DapContinue` or F6
4. got error message:
<img width="928" alt="image" src="https://github.com/ayamir/nvimdots/assets/31438141/c850655a-6e0e-4d24-8dce-743612ff5410">

### Expected behavior

Normally start debug process

### Additional information

I think it's because plugin loading order cause,
`mason-nvim-dap` must be after mason setup. [ref](https://github.com/jay-babu/mason-nvim-dap.nvim#setup)

I tried to modify the `dependencies`  like this, problem no longer occurs:
```lua
{ "jay-babu/mason-nvim-dap.nvim", dependencies = { { "neovim/nvim-lspconfig" } } },
```

**Comment by Jint-lzxy** [comment]
hmm this is a bit strange cause there is no connection between nvim-dap itself and Mason. Have you installed `codelldb` in Mason?

**Comment by HATTER-LONG** [comment]
Nope, They are all installed automatically

**Comment by HATTER-LONG** [comment]
> hmm this is a bit strange cause there is no connection between nvim-dap itself and Mason. Have you installed `codelldb` in Mason?

It's no connection between `nvim-dap` itself and Mason, but i think `mason-nvim-dap` depended on mason to get some info like this in `mason-nvim-dap`:

```lua
---@param handlers table<string, fun(source_name: string, methods: string[])> | nil
---@return nil
local function setup_handlers(handlers)
	handlers = handlers or {}
	local Optional = require('mason-core.optional')
	local source_mappings = require('mason-nvim-dap.mappings.source')
	local registry = require('mason-registry')
	local notify = require('mason-core.notify')

```

**Comment by Jint-lzxy** [comment]
This shouldn't be the root cause b/c for `Lazy.nvim` a plugin will be loaded once it's `require`d.

**Comment by HATTER-LONG** [comment]
No, I haven't modified these two parts. It's a bit strange. After I synced the plugin, the problem disappeared. 😓 

This situation makes me very confused.

**Comment by Jint-lzxy** [comment]
> This situation makes me very confused.

This is probably because the old cache (`luac` under `XDG_CACHE_HOME/nvim`) wasn't properly cleaned up. Since it is highly likely that `Lazy.nvim` used its cached spec, which stored your previous plugin snapshot. Then mason-nvim-dap.nvim attempted to read plugin definition from that old location and failed hard.

**Comment by Jint-lzxy** [comment]
> I wanna ask how the direct dependency relationship between mason-nvim-dap and mason is determined in this situation.

`mason-nvim-dap` depends on `mason` and `mason-nvim-dap` will properly setup `mason` if it was not initialized explicitly.
