### ISSUE TITLE
Error detected while processing BufReadPost Autocommands for "*.cpp".When i open nvim

### ISSUE THREAD

**Issue by 6FanWQ9** [ayamir/nvimdots#912]
### Version confirmation

- [X] Confirm

### Following prerequisites

- [X] Confirm

### Neovim version

NVIM v0.9.1 Build type: Release LuaJIT 2.1.0-beta3 

### Operating system/version

Ubuntu 22.04.2 LTS

### Terminal name/version

kitty 0.21.2 created by Kovid Goyal

### $TERM environment variable

xterm-kitty

### Branch info

main (Default/Latest)

### Fetch Preferences

HTTPS (use_ssh = false)

### How to reproduce the issue

1. `nvim a.cpp`
2. `enter`
3. 'enter'
4. ...'enter'

### Expected behavior

![image](https://github.com/ayamir/nvimdots/assets/99059269/5cf4f3c7-0341-4236-92a4-fc680cf103e2)
![image](https://github.com/ayamir/nvimdots/assets/99059269/7a95cfa5-5802-4aa8-b376-d477af68c1f6)
![image](https://github.com/ayamir/nvimdots/assets/99059269/2a7769cb-525c-4d3e-bee3-3c65c5360844)
![image](https://github.com/ayamir/nvimdots/assets/99059269/433156c8-d373-44bf-981a-f76176e67f99)
![image](https://github.com/ayamir/nvimdots/assets/99059269/91ca53dd-721a-4b76-bf55-931521b1f029)
![image](https://github.com/ayamir/nvimdots/assets/99059269/dbde9fa4-900b-4208-a8c7-8bc23a5113d1)
![image](https://github.com/ayamir/nvimdots/assets/99059269/5f362567-17e9-45ba-a7ba-04fa57a3d057)

### Additional information

When completing prerequisites, I can't use paru -S to install, so I can only search for them one by one on github and install it myself, not knowing if it's installed correctly.
During my installation, there was a plugin installation error, but I didn't take screenshots at the time, and I couldn't enter the plugin installation process again. Now as soon as I open NVIM, I get the error. I don't know what to do at all, and I really want to get help.

**Comment by CharlesChiuGit** [comment]
try remove the entire plugin installation folder and reopen nvim again.

**Comment by Jint-lzxy** [comment]
And to be specific:
```bash
rm -rf ~/.local/share/nvim/site/lazy/
nvim
```

**Comment by 6FanWQ9** [comment]
I just tried it and found no difference from before.
And when I tried to reinstall, I found this, it says my nvim version is 0.7 and those plugins need 0.8. but my nvim version is 0.9. and I also tried to install 0.8 and found that it still says my nvim version is 0.7.
![image](https://github.com/ayamir/nvimdots/assets/99059269/3746701d-b73f-4d53-9525-84e153752ec0)

**Comment by CharlesChiuGit** [comment]
maybe u have multiple nvim installed.

**Comment by Jint-lzxy** [comment]
Did u use our install script to bootstrap this config? It should abort if u are on Nvim 0.7.

Anyway, enter Neovim and use `CTRL-C` to stop generating further error messages (if applies), then type `:verbose version`, what u see for this?

**Comment by 6FanWQ9** [comment]
Yes!I found two neovim, one in /usr/ and one in my download .Perhaps I used to install nvim with nvim.appimage, and I got an empty nvim , so I did not think I have installed it.After I clean nvim in /usr/ and move my download nvim to /usr/, there is no error like before.Thanks for your help!
