### ISSUE TITLE
Cannot find package "go-debug-adapter"

### ISSUE THREAD

**Issue by AngelontheRoad** [ayamir/nvimdots#915]
### Version confirmation

- [X] Confirm

### Following prerequisites

- [X] Confirm

### Neovim version

NVIM v0.9.1

### Operating system/version

6.4.6-arch1-1

### Terminal name/version

kitty

### Branch info

main (Default/Latest)

### Fetch Preferences

SSH (use_ssh = true)

### How to reproduce the issue

Update configuration to newest version.
Update all plugins and Mason packages.

### Expected behavior

No error message.

### Actual behavior

Error message shows while start nvim

> ...re/nvim/site/lazy/mason.nvim/lua/mason-registry/init.lua:80: Cannot find package "go-debug-adapter" 

A lot of errors in masonlog:

> [ERROR Mon 31 Jul 2023 12:21:55 PM CST] ...re/nvim/site/lazy/mason.nvim/lua/mason-registry/init.lua:79: Cannot find package "\"delve\"".
> [ERROR Mon 31 Jul 2023 12:21:55 PM CST] ...re/nvim/site/lazy/mason.nvim/lua/mason-registry/init.lua:79: Cannot find package "\"debugpy\"".
> [ERROR Mon 31 Jul 2023 12:21:55 PM CST] ...re/nvim/site/lazy/mason.nvim/lua/mason-registry/init.lua:79: Cannot find package "\"codelldb\"".
> [ERROR Mon 31 Jul 2023 12:21:55 PM CST] ...re/nvim/site/lazy/mason.nvim/lua/mason-registry/init.lua:79: Cannot find package "\"delve\"".
> [ERROR Mon 31 Jul 2023 12:21:55 PM CST] ...re/nvim/site/lazy/mason.nvim/lua/mason-registry/init.lua:79: Cannot find package "\"debugpy\"".
> [ERROR Mon 31 Jul 2023 12:23:57 PM CST] ...re/nvim/site/lazy/mason.nvim/lua/mason-registry/init.lua:79: Cannot find package "\"bash-debug-adapter\"".
> [ERROR Mon 31 Jul 2023 12:23:57 PM CST] ...re/nvim/site/lazy/mason.nvim/lua/mason-registry/init.lua:79: Cannot find package "\"go-debug-adapter\"".
> [ERROR Mon 31 Jul 2023 12:23:57 PM CST] ...re/nvim/site/lazy/mason.nvim/lua/mason-registry/init.lua:79: Cannot find package "\"codelldb\"".
> [ERROR Mon 31 Jul 2023 12:23:57 PM CST] ...re/nvim/site/lazy/mason.nvim/lua/mason-registry/init.lua:79: Cannot find package "\"delve\"".
> [ERROR Mon 31 Jul 2023 12:23:57 PM CST] ...re/nvim/site/lazy/mason.nvim/lua/mason-registry/init.lua:79: Cannot find package "\"debugpy\"".
> 

### Additional information

It seems like therer's something wrong with `require("mason-registry").get_package("go-debug-adapter")` during init process. It works after init.

**Comment by Jint-lzxy** [comment]
Hmm I can't repro this... What does `:Mason` give u?

Can u have a look at #910 first?

**Comment by AngelontheRoad** [comment]
:Mason

![Mason](https://github.com/ayamir/nvimdots/assets/52699138/afa2168c-5109-4b47-87ad-6c5a72e35ac1)

I tried to remove `luac` under `XDG_CACHE_HOME/nvim` but it not works.

**Comment by AngelontheRoad** [comment]
Emmm... still not work. I have synced everything new.

**Comment by Jint-lzxy** [comment]
How did you open Neovim and did you instruct Neovim to open any files? What did you do inside Neovim?

**Comment by AngelontheRoad** [comment]
Thanks you for reminding me. I have added some my usual plugins. I tried to active them one by one, finally found that `overseer` has a conflict with `nvim-dap`. Remove it and everything OK.

 I never thought about a task runner could be conflicted with `dap` search. Maybe I should read its doc carefully and update my config about it. Anyway, thanks a lot!
