### ISSUE TITLE
Highlighted word is the previous candidate word when using fuzzy search

### ISSUE THREAD

**Issue by lzyuz** [ayamir/nvimdots#923]
### Version confirmation

- [X] Confirm

### Following prerequisites

- [X] Confirm

### Neovim version

NVIM v0.9.1

### Operating system/version

ubuntu22.04

### Terminal name/version

kitty0.29

### Branch info

main (Default/Latest)

### Fetch Preferences

SSH (use_ssh = true)

### How to reproduce the issue

no

### Expected behavior

Highlighted word should be candidate word

### Actual behavior

![image](https://github.com/ayamir/nvimdots/assets/127972121/eb29ba3c-d097-4081-943f-864948e0bc5c)
![image](https://github.com/ayamir/nvimdots/assets/127972121/a9135765-2c67-4bd9-a45c-e60cce472493)

**Comment by fecet** [comment]
try 
![image](https://github.com/ayamir/nvimdots/assets/41792945/41ccf603-549e-4151-a9ff-24ce8cef416b)

I fixed this long time ago and don't use wilder now

**Comment by CharlesChiuGit** [comment]
Can reproduce.

**Comment by lzyuz** [comment]
> try ![image](https://user-images.githubusercontent.com/41792945/258022494-41ccf603-549e-4151-a9ff-24ce8cef416b.png)
> 
> I fixed this long time ago (forget how) and don't use wilder now so not sure if it works

sovled, many thanks
