### ISSUE TITLE
pull最新lua配置后，打开编辑页报错：E5113: Error while calling lua chunk: /Users/xxx/.config/nvim/lua/core/options.lua:125: E474: Invalid argument

### ISSUE THREAD

**Issue by toyuanx** [ayamir/nvimdots#927]
### Version confirmation

- [x] Confirm

### Following prerequisites

- [X] Confirm

### Neovim version

NVIM v0.8.3

### Operating system/version

macOS 13.5

### Terminal name/version

Iterm2 Build 3.4.19

### Branch info

main (Default/Latest)

### Fetch Preferences

SSH (use_ssh = true)

### How to reproduce the issue

使用nvim进入文件编辑后报错：
![image](https://github.com/ayamir/nvimdots/assets/19640938/b27de94a-691b-42ae-af1a-b84476f3ef3e)

### Expected behavior

不报错

**Comment by ayamir** [comment]
update your nvim to 0.9.

**Comment by Jint-lzxy** [comment]
Or if u insist on using Nvim 0.8, checkout the `0.8` branch and do `:Lazy restore`

**Comment by toyuanx** [comment]
tks
