### ISSUE TITLE
命令模式提示错误

### ISSUE THREAD

**Issue by guanpj** [ayamir/nvimdots#93]
**Describe the bug**
vim 新手，按照知乎文章从 git clone 开始执行命令，安装完主题后执行完 nvim +PackerSync 重新打开 nvim ，命令模式出现如下错误 ：

<img width="665" alt="B58A4494-4E3D-4CD4-80EA-96BAB9B710F9" src="https://user-images.githubusercontent.com/9383680/157702046-4a33765d-3782-46ba-9d3c-9edd585e8c2b.png">

重新执行  nvim +PackerSync 后命令模式仍然报错：

<img width="665" alt="6C6D08A2-8548-406D-9206-9DE83152E0AE" src="https://user-images.githubusercontent.com/9383680/157703708-00cf19d9-910a-40db-8788-c514a94281aa.png">

**Environment**
 - OS:macOS
 - Nvim version: v0.6.1

对了，如果要删除下载的插件应该怎么操作？抱歉没看懂文档。

**Comment by ayamir** [comment]
可能需要在你的机器上手动安装`fzf`：`brew install fzf`

**Comment by ayamir** [comment]
删除插件：
1. 找到插件所在的位置，比如删除`rust-tool.nvim`，插件的安装出现在`lua/modules/lang/plugins.lua`中，配置的config出现在`lua/modules/lang/config.lua`中
2. 删除对应的代码：
https://github.com/ayamir/nvimdots/blob/main/lua/modules/lang/plugins.lua#L11-L16
https://github.com/ayamir/nvimdots/blob/main/lua/modules/lang/config.lua#L3-L74
3. 退出nvim之后执行`nvim +PackerSync`即可

**Comment by guanpj** [comment]
感谢回复，fzf 安装完之后还是一样的错误。
我想尝试重新安装 nvimdots，删除～/.config/nvim 目录后重新 clone，然后从安装主题开始走一遍，但是发现后面并没有提示主题不存在。
请问应该怎样完全移除 nvimdots？

**Comment by ayamir** [comment]
```shell
rm -rf ~/.config/nvim
rm -rf ~/.local/share/nvim
```

**Comment by guanpj** [comment]
重新安装后解决问题！
应该是我在第一步安装主题过程中没开代理，卡顿之后退出 item 造成的。感谢大佬！
