### ISSUE TITLE
How do I update to the latest version

### ISSUE THREAD

**Issue by Penguin-SAMA** [ayamir/nvimdots#932]
### Version confirmation

- [X] Confirm

### Following prerequisites

- [X] Confirm

### Neovim version

NVIM v0.9.1

### Operating system/version

macos 14

### Terminal name/version

iterm 2

### Branch info

main (Default/Latest)

### Fetch Preferences

SSH (use_ssh = true)

### How to reproduce the issue

There is a feature I like in version 3.2.0, how can I update it

### Expected behavior

thanks

**Comment by Penguin-SAMA** [comment]
i got these 
<img width="637" alt="image" src="https://github.com/ayamir/nvimdots/assets/50973632/f750a130-16b1-4fb5-b0bc-df8318dfce9d">

**Comment by ayamir** [comment]
```
git restore lazy-lock.json
```

**Comment by Penguin-SAMA** [comment]
thanks!
