### ISSUE TITLE
Better comparators for completion entries?

### ISSUE THREAD

**Issue by fengxuway** [ayamir/nvimdots#939]
### Feature description

![image](https://github.com/ayamir/nvimdots/assets/17471078/172b90b8-d4db-45b1-9bb0-e42bb2d57865)

如图，文件路径`/bin/bash`存在，但默认排序却放在第三位。当文件名有完全匹配的时候，建议完全匹配放在第一位。

**Comment by fengxuway** [comment]
或者这是哪个插件，我去对应仓库提交Issue？

**Comment by fengxuway** [comment]
同样的还有这个特殊字符`\` 在写 shell 的时候用于换行，
![image](https://github.com/ayamir/nvimdots/assets/17471078/71761a40-66ac-43d3-89f9-b3ae5df6a4e2)

当输入`\`并回车时，目前效果：
<img width="306" alt="image" src="https://github.com/ayamir/nvimdots/assets/17471078/475e6a69-da7a-447c-becf-120c2702f70e">

预期效果：
<img width="256" alt="image" src="https://github.com/ayamir/nvimdots/assets/17471078/2a1356d2-66be-4e0c-9dcb-67f91353e38f">

**Comment by CharlesChiuGit** [comment]
`:h cmp-config`

**Comment by Jint-lzxy** [comment]
> ... put exact match first

This is controlled by [`cmp.comparators`](https://github.com/ayamir/nvimdots/blob/8bfa4401801bb643a83608927e36f8fb83d86d04/lua/modules/configs/completion/cmp.lua#L54-L68). We mainly focused on the results returned by language servers while updating `cmp.comparators` in #746. Feel free to open a PR if u think u have better implementation.

> ...and this special character `\`

This is provided by [`latex_symbols`](https://github.com/ayamir/nvimdots/blob/8bfa4401801bb643a83608927e36f8fb83d86d04/lua/modules/configs/completion/cmp.lua#L173). Normally, u should press `<C-w>` first to close that pum and then press `<CR>`. Alternatively, you may disable auto-selection by commenting out this line:
https://github.com/ayamir/nvimdots/blob/8bfa4401801bb643a83608927e36f8fb83d86d04/lua/modules/configs/completion/cmp.lua#L132

**Comment by fengxuway** [comment]
The character `\` event, comment this line works for me. Thanks~
https://github.com/ayamir/nvimdots/blob/8bfa4401801bb643a83608927e36f8fb83d86d04/lua/modules/configs/completion/cmp.lua#L173
