### ISSUE TITLE
那个把==和！=合并的功能是从哪里来的呢？

### ISSUE THREAD

**Issue by hypghzy** [ayamir/nvimdots#94]
你好，我在用你这个配置的时候发现编辑器会自动把==或者！=自动显示为一个符号，想问一下这个功能是neovim自带的还是插件啊？而且这个功能在我写C++的时候起作用，但是在写lua的时候不会把~=转化为不等号呢？

**Comment by The-White-Lion** [comment]
这个是字体连字特性，一般情况下如果你的终端或者编辑器支持这个特性，而你的字体恰又好是连字字体，就会把多个符号显示为一个。
每种字体的连字字符支持不一致，达到的效果也不一样，可以使用  `JetBrainsMono Nerd Font ` 满足你的 lua 需求
更多信息可以查询 nerd fonts

**Comment by hypghzy** [comment]
> `JetBrainsMono `

好的，非常感谢
