### ISSUE TITLE
Error when using multiple files in different languages

### ISSUE THREAD

**Issue by Lonjiazeng** [ayamir/nvimdots#945]
### Version confirmation

- [X] Confirm

### Following prerequisites

- [X] Confirm

### Neovim version

NVIM v0.9.0-dev-329+ged27f0e93

### Operating system/version

archlinux

### Terminal name/version

WezTerm

### $TERM environment variable

xterm-256color

### Branch info

main (Default/Latest)

### Fetch Preferences

SSH (use_ssh = true)

### How to reproduce the issue

First create a folder, then in this new folder create two new files in different languages, e.g. a.py and b .c. Then use nvim to edit one of the files, write something like print "hello world", then use the command `:e b.c` (assuming you edited a.py first). py), and then get an error and can't move through the text at all using `hjkl`. 
![image](https://github.com/ayamir/nvimdots/assets/76612231/116c094b-2a3e-4e91-926b-5fff18f0f2df)

### Expected behavior

No errors were reported, it was able to be edited normally, and lsp was working properly

### Actual behavior

Keeps popping up errors and can't move the cursor at all, let alone edit anything!

**Comment by Jint-lzxy** [comment]
Possible duplicate of https://github.com/ayamir/nvimdots/issues/393.

**Comment by Lonjiazeng** [comment]
another error
![image](https://github.com/ayamir/nvimdots/assets/76612231/189d8ad5-aefc-4940-b09a-ea71bfa88cf3)

**Comment by Jint-lzxy** [comment]
These two are essentially the same.

**Comment by Lonjiazeng** [comment]
> Possible duplicate of #393.

After using `:TSUpdate` it works fine, thanks!
