### ISSUE TITLE
Ctrl+P显示快捷键与实际代码按键不一致

### ISSUE THREAD

**Issue by Robin329** [ayamir/nvimdots#946]
### Version confirmation

- [X] Confirm

### Following prerequisites

- [X] Confirm

### Neovim version

NVIM v0.9.1

### Operating system/version

$ nvim --version NVIM v0.9.1 Build type: Release LuaJIT 2.1.0-beta3     system vimrc file: "$VIM/sysinit.vim"   fall-back for $VIM: "/__w/neovim/neovim/build/nvim.AppDir/usr/share/nvim"  Run :checkhealth for more info

### Terminal name/version

Terminal

### Branch info

main (Default/Latest)

### Fetch Preferences

HTTPS (use_ssh = false)

### How to reproduce the issue

nvim版本如下：
$ nvim --version
NVIM v0.9.1
Build type: Release
LuaJIT 2.1.0-beta3

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/__w/neovim/neovim/build/nvim.AppDir/usr/share/nvim"

Run :checkhealth for more info

$ nvim

`Ctrl + p`进入快捷键查询面板，发现Window resize的快捷键与代码中描述不一致。
出现问题时截图：
![image](https://github.com/ayamir/nvimdots/assets/22770951/3bc3f243-6fe5-4523-bd43-3a589be84154)

而实际代码和实际操作：
![image](https://github.com/ayamir/nvimdots/assets/22770951/f2680206-191c-464c-89d4-57b7481876de)

### Expected behavior

Ctrl+p与实际按键一致

### Actual behavior

进入nvim后，使用ctrl+p显示window resize按键(alt键)跟实际不一致

**Comment by ayamir** [comment]
`M` is the same as `A`.
Additionally, you should use nerd font for your terminal.

**Comment by Robin329** [comment]
感谢解答，为什么M跟A一样？哪里有说明吗？我在代码里面没有找到。

**Comment by Jint-lzxy** [comment]
The help manual (`:h(elp) ...`) is always ur best friend - u should always consult the manual first if you're in trouble.

`:h META`:
```console
<M-…>		alt-key or meta-key		*META* *ALT* *<M-*
<A-…>		same as <M-…>			*<A-*
```

**Comment by Robin329** [comment]
Thanks for the answer, neovim is not very familiar with it at the beginning, and it has become a pleasure for me to transform and learn it.

**Comment by Jint-lzxy** [comment]
@Robin329 We also recommend you to read the user manual from start to end ([usr_01.txt](https://neovim.io/doc/user/usr_01.html#usr_01.txt)) to have a basic understanding of Neovim 😄
