### ISSUE TITLE
Support for `textDocument/callHierarchy`?

### ISSUE THREAD

**Issue by Robin329** [ayamir/nvimdots#947]
### Feature description

![image](https://github.com/ayamir/nvimdots/assets/22770951/ef5f7efe-59c6-4d67-9a5d-cff6f4e278f5)
使用新一点版本的clangd，在某个函数定义处右键有几个选项支持查看该函数的调用层次，非常好用。请问当前插件是否已有插件支持呢？

**Comment by Jint-lzxy** [comment]
These are all provided by `Lspsaga`, refer to its [manual](https://nvimdev.github.io/lspsaga/) (usage) and our command panel (keymaps) for more information.

**Comment by Jint-lzxy** [comment]
This mapping:
https://github.com/ayamir/nvimdots/blob/10e2e491402de420c38ebfa654536a2bd6ff1986/lua/core/event.lua#L140-L144

provides support for switches between Source/Header.

**Comment by Robin329** [comment]
![image](https://github.com/ayamir/nvimdots/assets/22770951/87eda984-0a28-4635-989e-abf59e49e430)
使用"Lspsaga outgoing_calls"，会卡住？同时使用"Lspsaga incoming_calls"无法显示更多层次？是否是插件支持不完善？
![image](https://github.com/ayamir/nvimdots/assets/22770951/614ba139-96ab-4ad1-9e74-f3c036086065)

对比vscode会显示更多层次：
![image](https://github.com/ayamir/nvimdots/assets/22770951/3ee2323a-729d-4463-a6f2-6f3bfdfe4a51)

**Comment by Jint-lzxy** [comment]
Did u follow [`clangd`'s documentation](https://clangd.llvm.org/design/compile-commands) to setup ur project? VSCode doesn't require such configuration b/c it has already generated the workspace for u. See https://github.com/ayamir/nvimdots/discussions/836 for details.

**Comment by Robin329** [comment]
Dear,
    我使用相同的工程，在vscode是可以正常工作的，但是nvim里面不能，当前目录下面有compile commands json文件。
![image](https://github.com/ayamir/nvimdots/assets/22770951/f7c7aa1e-2754-459a-a38f-31a990a8b709)

**Comment by Jint-lzxy** [comment]
Hmm then this looks more like a bug. Can you help fill in the [LSP Bug Report](https://github.com/ayamir/nvimdots/issues/new?assignees=&labels=bug%2Clsp&projects=&template=lsp_issue_report.yml) so that we can look into this issue?

**Comment by Robin329** [comment]
见https://github.com/ayamir/nvimdots/issues/948

**Comment by Jint-lzxy** [comment]
Closing in favor of #948.
