### ISSUE TITLE
Warnings on open nvim-tree inside config file

### ISSUE THREAD

**Issue by MKrbm** [ayamir/nvimdots#954]
### Version confirmation

- [X] Confirm

### Following prerequisites

- [X] Confirm

### Neovim version

NVIM v0.9.1

### Operating system/version

Windows10

### Terminal name/version

powershell / command prompt

### Branch info

main (Default/Latest)

### Fetch Preferences

HTTPS (use_ssh = false)

### How to reproduce the issue

1. Go to AppData\Local\nvim
2. `nvim`
3. hit `ctrl-n` 

Then below pop-up shows up

![image](https://github.com/ayamir/nvimdots/assets/57752203/aec4fec4-b609-4cbb-93da-6eb0827fc2a6)

Everything works properly tho.

### Expected behavior

I want to fix this warning

### Actual behavior

Just suspend a few second and nvim-tree start to work.

**Comment by MKrbm** [comment]
I found this happens not only under config folder but also everywhere except under `C:\Users\{UserName}`

**Comment by Jint-lzxy** [comment]
This looks more like an issue with your user profile (`C:\Users\*\Microsoft.PowerShell_profile.ps1`). A possible workaround is to check whether the underlying terminal support virtual terminal before applying ur custom config:
```ps1
function _do_support_termVT {
	$Defs = @'
[DllImport("kernel32.dll", SetLastError = true)]
public static extern IntPtr GetStdHandle(int nStdHandle);
[DllImport("kernel32.dll", SetLastError = true)]
public static extern bool GetConsoleMode(IntPtr hConsoleHandle, out uint lpMode);
'@
	$Kernel = Add-Type -MemberDefinition $Defs -Name 'Kernel32' -Namespace 'Win32' -PassThru
	$stdoutConsoleHandle = $Kernel::GetStdHandle(-11)
	$mode = 0
	$Kernel::GetConsoleMode($stdoutConsoleHandle,[ref]$mode) > $null
	if ($mode -band 0x0004) {
		return $True
	}
	return $False
}

function check_termVT_support {
	return (![System.Console]::IsOutputRedirected) -and (_do_support_termVT)
}

if (check_termVT_support) {
	# Term-VT dependent configs here...
}
```

**Comment by MKrbm** [comment]
Thank you, I will look into it. But I'm wondering why it says `Microsoft.PowerShell_profile.ps1` even if I use cmd?

**Comment by Jint-lzxy** [comment]
b/c there are a lot of tweaks that require PowerShell. So you're using cmd.exe instead of PowerShell? Then why did you fill in `powershell / command prompt` in "Terminal name/version"?

Based on this info, the solution is quite simple - just switch to PowerShell and u'll be good to go.

**Comment by MKrbm** [comment]
I mean I encountered both powershell and cmd. Sorry for confusing you.

P.S. I could suppress this popup by commenting out the following line in .ps1 file. But I think this is just a quick-fix since this setup will disable some features of my powershells. But anyways thank you for the help!



```
# Set-PSReadLineOption -PredictionSource History
# Set-PSReadLineOption -PredictionViewStyle ListView
```

**Comment by Jint-lzxy** [comment]
> P.S. I could suppress this popup by commenting out the following line in .ps1 file. But I think this is just a quick-fix since this setup will disable some features of my powershells. But anyways thank you for the help!

Just put this snippet into `if (check_termVT_support)` and everything should work fine :D Some Neovim "terminals" are actually just pseudo-terminals and lack some of the functionality.
