### ISSUE TITLE
npm is not executable

### ISSUE THREAD

**Issue by Robin329** [ayamir/nvimdots#955]
### Version confirmation

- [X] Confirm

### Following prerequisites

- [X] Confirm

### Neovim version

NVIM v0.9.1

### Operating system/version

$ uname -a Linux rock-5b 5.10.110-36-rockchip-gba392dc725fa #rockchip SMP Tue Jan 17 07:19:43 UTC 2023 aarch64 GNU/Linux

### Terminal name/version

Debian Terminal

### $TERM environment variable

xterm-256color

### Branch info

main (Default/Latest)

### Fetch Preferences

HTTPS (use_ssh = false)

### Affected language servers

clangd

### How to reproduce the issue

终端正常打开nvim，出现加载插件失败。

### Actual behavior

![image](https://github.com/ayamir/nvimdots/assets/22770951/fa760c35-4067-45ca-8c0a-6684e78d1a45)

### Support info

![image](https://github.com/ayamir/nvimdots/assets/22770951/0f35def0-b5d5-456d-8ed2-5d284c93e855)
![image](https://github.com/ayamir/nvimdots/assets/22770951/edd0659d-9338-4e65-bc61-f65705630e90)

**Comment by Jint-lzxy** [comment]
Do `:checkhealth` and resolve all errors there - u are missing necessary dependencies. Did u follow [Wiki:Prerequisites](https://github.com/ayamir/nvimdots/wiki/Prerequisites#required-packages-installation-for-archlinux) before u start?

**Comment by Robin329** [comment]
因为我在arm64服务器上部署nvim，遇到如下安装错误：
![image](https://github.com/ayamir/nvimdots/assets/22770951/ff7c5236-7437-4a24-8d4d-f3607b63ba59)
![image](https://github.com/ayamir/nvimdots/assets/22770951/68077af2-53e7-4502-9f99-1d327d34d3c2)
![image](https://github.com/ayamir/nvimdots/assets/22770951/49fa853a-e1ca-4e8e-ba8b-640582f20749)

**Comment by Jint-lzxy** [comment]
u need to have these dependencies installed (as mentioned in the fixup section):
```console
- tree-sitter
- unzip
- wget
- curl
- gzip
- tar
- bash
- cargo
- go
- node
- npm
- python (pip) 
- composer
- (optional) ruby
- (optional) luarocks
- (optional) java
- (optional) julia
- (optional) php
```
u also need to do `:TSUpdate`.

**Comment by Robin329** [comment]
> u need to have these dependencies installed (as mentioned in the fixup section):
> 
> ```
> - tree-sitter
> - unzip
> - wget
> - curl
> - gzip
> - tar
> - bash
> - cargo
> - go
> - node
> - npm
> - python (pip) 
> - composer
> - (optional) ruby
> - (optional) luarocks
> - (optional) java
> - (optional) julia
> - (optional) php
> ```
> 
> u also need to do `:TSUpdate`.

这些依赖在arch linux有提供详细的安装细节，但是类似Ubuntu/Debian这些系统没有，是否可以完善一下呢？如果换个系统这些软件都需要重新再次安装一遍比较麻烦，是否可以配置为在nvim首次启动过程将依赖安装好？

**Comment by Jint-lzxy** [comment]
> The main reason blocking us from implementing automatic dependency installation (like the Windows one) is that we have no plan to support each and every package managers for whatever distributions users would use. If we do start implementing this, at the end of the day the script will surely become extremely buggy and difficult to maintain. Feel free to open a PR if u think there's a better way to handle this

> No way cause there are too many distros and we can't maintain it.

See #938 for a detailed discussion.
