### ISSUE TITLE
Nvim gets really slow as markdown file get larger.

### ISSUE THREAD

**Issue by MKrbm** [ayamir/nvimdots#956]
### Version confirmation

- [X] Confirm

### Following prerequisites

- [X] Confirm

### Neovim version

NVIM v0.9.1

### Operating system/version

Windows10

### Terminal name/version

Powershell

### Branch info

main (Default/Latest)

### Fetch Preferences

HTTPS (use_ssh = false)

### How to reproduce the issue

1. Write `.md` file with many headers (# Title)
2. After number of headers exceeds  around 30, neovim gets slower. For example, cursor movement is really slow.

![image](https://github.com/ayamir/nvimdots/assets/57752203/932c8875-bc64-4910-8ca0-5cd98926b542)

### Expected behavior

This doesn't happen except in `.md` files so far.

**Comment by Jint-lzxy** [comment]
Yeah this has long been an issue (upstream server implementations \[e.g., letx\] are not that efficient). Try `:LspStop` to see if the problem is somehow alleviated? If so, you can exclude `markdown` from the filetypes supported by those servers as a workaround, or open a feature request upstream.

**Comment by fecet** [comment]
Have you found `nvim-cmp` also become slow? I have this problem in `quarto`

**Comment by Jint-lzxy** [comment]
> Have you found `nvim-cmp` also become slow? I have this problem in `quarto`

Ys this is more like a common issue for all markdown-like files. cause they could contain almost every possible language, highlight parsing and LSP implementations thus require a lot of effort.

**Comment by fecet** [comment]
I thought this was caused by treesitter as I dont use lsp in markdown-like. And if `nvim-cmp` become slow casued by treesitter, this nvim-cmp's own bug

**Comment by Jint-lzxy** [comment]
> I thought this was caused by treesitter as I dont use lsp in markdown-like.

Yeah I should say both caused serious delays.

> And if `nvim-cmp` become slow casued by treesitter, this is nvim-cmp's own bug

That's true because some components do rely on treesitter.

**Comment by fecet** [comment]
As for lsp, https://github.com/jmbuhr/otter.nvim from quarto team looks promising but I havn't give it a try.

**Comment by MKrbm** [comment]
> Yeah this has long been an issue (upstream server implementations [e.g., ltex] are not that efficient). Try `:LspStop` to see if the problem is somehow alleviated? If so, you can exclude `markdown` from the filetypes supported by those servers as a workaround, or open a feature request upstream.

The delay remains still after `:LspStop`.

**Comment by fecet** [comment]
Try comment event in nvim-treesitter 
```
editor["nvim-treesitter/nvim-treesitter"] = {
	lazy = true,
	build = function()
		if #vim.api.nvim_list_uis() ~= 0 then
			vim.api.nvim_command("TSUpdate")
		end
	end,
	-- event = "BufReadPost",
	config = require("editor.treesitter"),

```

**Comment by ayamir** [comment]
https://github.com/ayamir/nvimdots/assets/61657399/7f7d7bde-ce2d-450b-8c2a-1c09df589be9

Can't repro on my wsl...

**Comment by MKrbm** [comment]
I think this problem is on windows os.

**Comment by MKrbm** [comment]
> 2023-08-14-00-05-11.mp4 
> Can't repro on my wsl...

I think this happens on windows os.

**Comment by fecet** [comment]
have you tried comment event or even `lazy=true` to make it not lazy loaded?

**Comment by CharlesChiuGit** [comment]
I guess it could also effected by the antivirus. I think there's an old issue about lsp got drag down by the antivirus, but i can find it now, hmmm...

**Comment by Jint-lzxy** [comment]
> I guess it could also effected by the antivirus. I think there's an old issue about lsp got drag down by the antivirus, but i can find it now, hmmm...

+1 for me if the author did follow the instructions above. AFAIK when Windows Defender discovers some sort of (maybe) "untrusted" software spawned by another _user-controlled_ parent process, the system will continuously monitor that _parent process_ and watchers do have a non-trivial impact on performance.

**Comment by fecet** [comment]
It seems that we doesn't setup any lsp in markdown?

**Comment by Jint-lzxy** [comment]
> Didn't we not set up any LSP for markdown?

That's true. But we do register all installed servers during startup:
https://github.com/ayamir/nvimdots/blob/10e2e491402de420c38ebfa654536a2bd6ff1986/lua/modules/configs/completion/lsp.lua#L141

which involves checking if the target files are executable. Obviously, that's not possible without attempting to actually spawn the executable(s).

**Comment by MKrbm** [comment]
> have you tried comment event or even `lazy=true` to make it not lazy loaded?

Both didn't work unfortunately..

**Comment by MKrbm** [comment]
I found the problem also happens for ubuntu docker but not for archlinux docker.

**Comment by CharlesChiuGit** [comment]
Maybe it's just the limitation of that lsp?

**Comment by fecet** [comment]
Cloud you share the file that you observed slow

**Comment by MKrbm** [comment]
Also, if I uninstall markdown and markdown-inline from Treesitter, it works fine. 

The below is dockerfile and you can observe slowness with `README.md` under `~/.config/nvim`


```Dockerfile
# Start with the base Arch Linux image
FROM archlinux:base

# Update the system and install base-devel and other necessary tools
RUN pacman -Syu --noconfirm \
  && pacman -S --noconfirm base-devel git sudo

# Create a new user to build the AUR package, as building as root is not allowed
RUN useradd -m user \
  && echo 'user ALL=(ALL) NOPASSWD: ALL' > /etc/sudoers.d/user \
  && chmod 0440 /etc/sudoers.d/user

# Switch to the new user
USER user

# Clone the paru repository
RUN git clone https://aur.archlinux.org/paru.git /home/user/paru

# Navigate to the paru directory and build the package
WORKDIR /home/user/paru
RUN makepkg -si --noconfirm

RUN paru -S --noconfirm git lazygit zoxide ripgrep sqlite fd yarn ttf-jetbrains-mono-nerd lldb nvm make unzip neovim python-pynvim 

RUN source /usr/share/nvm/init-nvm.sh && nvm install 18
RUN source /usr/share/nvm/init-nvm.sh && nvm use 18


RUN sudo pacman -Rns --noconfirm rust
RUN paru -S --noconfirm rustup
RUN rustup toolchain install nightly # or stable


RUN if command -v curl >/dev/null 2>&1; then \
        bash -c "$(curl -fsSL https://raw.githubusercontent.com/ayamir/nvimdots/HEAD/scripts/install.sh)"; \
    else \
        bash -c "$(wget -O- https://raw.githubusercontent.com/ayamir/nvimdots/HEAD/scripts/install.sh)"; \
    fi


RUN echo 'source /usr/share/nvm/init-nvm.sh' >> /home/user/.bashrc


USER root


RUN pacman -Syu --noconfirm \
    && pacman -S --noconfirm xorg-apps xorg-xeyes
    
RUN pacman -S --noconfirm xclip

ENV DISPLAY host.docker.internal:0.0 

RUN echo 'user:user' | chpasswd # Set password for user
RUN echo 'root:root' | chpasswd
USER user

```

**Comment by fecet** [comment]
I can reproduce. The scroll speed become slow by `yGPPP`

**Comment by CharlesChiuGit** [comment]
> Also, if I uninstall markdown and markdown-inline from Treesitter, it works fine.

does this also works in Windows?

**Comment by Jint-lzxy** [comment]
> > Also, if I uninstall markdown and markdown-inline from Treesitter, it works fine.
> 
> does this also works in Windows?

This should work, since uninstalling Treesitter parsers is equivalent to completely disable treesitter for that filetype (including its dependencies) (or `cond = false` for Lazy.nvim). Simply "making treesitter not lazy loaded" only disables Treesitter itself, but its dependencies will still be loaded.

IMO a better approach is to disable `Treesitter highlight` for `markdown` exclusively _(if this brings significant performance penalties)_, but still keep Markdown/Markdown-Inline parsers installed (because Lspsaga needs it). In fact, there are already several [upstream issues](https://github.com/nvim-treesitter/nvim-treesitter/issues?q=is%3Aissue+is%3Aopen+markdown+performance) complaining about TS-Markdown's performance, which is the downside of grammar injection tho.

**Comment by CharlesChiuGit** [comment]
indeed, treesitter works poorly against big files or big workspaces

**Comment by MKrbm** [comment]
Yeah, it seems we need to the improvement of treesitter.  
I'm going to close since we sort of solve this.

**Comment by MKrbm** [comment]
> IMO a better approach is to disable `Treesitter highlight` for `markdown` exclusively _(if this brings significant performance penalties)_, but still keep Markdown/Markdown-Inline parsers installed (because Lspsaga needs it). In fact, there are already several [upstream issues](https://github.com/nvim-treesitter/nvim-treesitter/issues?q=is%3Aissue+is%3Aopen+markdown+performance) complaining about TS-Markdown's performance, which is the downside of grammar injection tho.

I experience poor performance speed even when I disabled highlight for `markdown` since markdown-inline is still installed as you explained above. Is there any workaround for this? I personally don't need markdown syntax highlight or anything except Lspsaga does.

**Comment by CharlesChiuGit** [comment]
maybe this could help.

https://github.com/ayamir/nvimdots/issues/666#issuecomment-1639518780

**Comment by Jint-lzxy** [comment]
> Is there any workaround for this?

You need to disable the entire Treesitter module, follow @CharlesChiuGit's suggestions and apply:
```vim
:TSBufDisable <...>
```

**Comment by metorm** [comment]
> Try comment event in nvim-treesitter
> 
> ```lua
> editor["nvim-treesitter/nvim-treesitter"] = {
> 	lazy = true,
> 	build = function()
> 		if #vim.api.nvim_list_uis() ~= 0 then
> 			vim.api.nvim_command("TSUpdate")
> 		end
> 	end,
> 	-- event = "BufReadPost",
> 	config = require("editor.treesitter"),
> ```

@fecet This saves my day. Commenting the `even = "BufReadPost"` line does sovles my problem that editing a `markdown` file is much slower than any other files.

Could you please explain that what the `even = "BufReadPost"` line  actually changed?
