### ISSUE TITLE
Cursor Navigation with <C-p> is not displayed for telescope. 

### ISSUE THREAD

**Issue by MKrbm** [ayamir/nvimdots#958]
### Version confirmation

- [X] Confirm

### Following prerequisites

- [X] Confirm

### Neovim version

NVIM v0.9.1

### Operating system/version

Arch Linux

### Terminal name/version

powershell

### Branch info

main (Default/Latest)

### Fetch Preferences

HTTPS (use_ssh = false)

### How to reproduce the issue

I'm using Docker Desktop on windows10

---

NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
VERSION_ID=20230723.0.166908
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://bugs.archlinux.org/"
PRIVACY_POLICY_URL="https://terms.archlinux.org/docs/privacy-policy/"
LOGO=archlinux-logo

---

1. `<Space>f f` to enter :telescope find_file
2. The effect of cursor movement with `<C-p>` is not displayed even though it works internally.
3. Also, after hit `<c-p>` twice, cursor moves by two. 
- `<C-n>` works fine, and somehow only for `<C-p>` not.  

### Expected behavior

Work normally.

### Actual behavior

`<C-p>` works fine internally but not visually.

### Additional information

Below is dockerfile I'm using.
```Dockerfile


FROM archlinux:base


RUN pacman -Syu --noconfirm \
  && pacman -S --noconfirm base-devel git sudo


RUN useradd -m user \
  && echo 'user ALL=(ALL) NOPASSWD: ALL' > /etc/sudoers.d/user \
  && chmod 0440 /etc/sudoers.d/user


USER user


RUN git clone https://aur.archlinux.org/paru.git /home/user/paru

# Navigate to the paru directory and build the package
WORKDIR /home/user/paru
RUN makepkg -si --noconfirm

RUN paru -S --noconfirm git lazygit zoxide ripgrep sqlite fd yarn ttf-jetbrains-mono-nerd lldb nvm make unzip neovim python-pynvim 

RUN source /usr/share/nvm/init-nvm.sh && nvm install 18
RUN source /usr/share/nvm/init-nvm.sh && nvm use 18


RUN sudo pacman -Rns --noconfirm rust
RUN paru -S --noconfirm rustup
RUN rustup toolchain install nightly # or stable


RUN if command -v curl >/dev/null 2>&1; then \
        bash -c "$(curl -fsSL https://raw.githubusercontent.com/ayamir/nvimdots/HEAD/scripts/install.sh)"; \
    else \
        bash -c "$(wget -O- https://raw.githubusercontent.com/ayamir/nvimdots/HEAD/scripts/install.sh)"; \
    fi


RUN echo 'source /usr/share/nvm/init-nvm.sh' >> /home/user/.bashrc
```

**Comment by Jint-lzxy** [comment]
> `<C-p>` works fine internally but not visually.

Which file gets opened when u press \<CR\> at that time? I suspect the keycodes emitted by your container aren't compatible with your client.

**Comment by MKrbm** [comment]
For example, if I press <C-p> at the image, it opens go.json 

![image](https://github.com/ayamir/nvimdots/assets/57752203/c2ee7897-18dd-4cc0-8355-1207933663bc)

**Comment by MKrbm** [comment]
![image](https://github.com/ayamir/nvimdots/assets/57752203/49a39b5e-10b9-4859-aef7-b99738653f16)

Your concern was completely right and I found ctrl - p was a escape sequence in docker since ctrl p ctrl q is prepared to leave from docker. 

Thank you very much.

**Comment by Jint-lzxy** [comment]
Closing as NAD.
