### ISSUE TITLE
Can't paste over SSH

### ISSUE THREAD

**Issue by Robin329** [ayamir/nvimdots#959]
### Version confirmation

- [X] Confirm

### Following prerequisites

- [X] Confirm

### Neovim version

NVIM v0.9.1

### Operating system/version

 Linux ubuntu 5.15.0-76-generic #83~20.04.1-Ubuntu SMP Wed Jun 21 20:23:31 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

### Terminal name/version

Ubuntu Terminal

### $TERM environment variable

xterm-256color

### Branch info

main (Default/Latest)

### Fetch Preferences

HTTPS (use_ssh = false)

### How to reproduce the issue

1. 使用power shell中ssh连接linux server
2. 打开neovim创建一个新文件
3. 在win下复制一段文本
4. 进入nvim插入模式，右键进行paste不能粘贴复制的内容。

### Expected behavior

支持粘贴win下面的内容

### Actual behavior

无法粘贴，vim中可以粘贴。

**Comment by ayamir** [comment]
Can't repro. I use `Ctrl-v` btw.


https://github.com/ayamir/nvimdots/assets/61657399/e42016c1-7858-42d0-b27e-84a08d43e422

**Comment by ayamir** [comment]
Can't repro for me. I use `Ctrl-v` to paste btw.
https://github.com/ayamir/nvimdots/assets/61657399/9c45219a-d123-4c43-886c-bdf57679a88c

**Comment by CharlesChiuGit** [comment]
Bro, u dont learn vim/nvim by asking others shit tons of question w/o trying to solve it by yourself first.
it's just not the why to learn anything.

**Comment by Robin329** [comment]
> Bro, u dont learn vim/nvim by asking others shit tons of question w/o trying to solve it by yourself first. it's just not the why to learn anything.

感谢你的提醒，可能你们对nvim很熟悉，所以觉得这些问题so easy，作为刚接触nvim的初学者，所以有很多问题不清楚没头绪。每一个都自己去探索解决也不现实，后面我先尝试自己先解决哈，自己不能独立解决的再提上来。

**Comment by ayamir** [comment]
Many fundamental questions you can google first. You can usually get them in stackoverflow.

**Comment by CharlesChiuGit** [comment]
> 每一个都自己去探索解决

let's exactly how i learned vim

**Comment by CharlesChiuGit** [comment]
u can use vscode to get the serious job first and learn vim at your leisure time.

check out my repo readme, there r some great resources to learn vim.

**Comment by Jint-lzxy** [comment]
I tend to close this as "NAD" (Not A Defect) b/c we can't repro this, already have both `win32yank.exe` and `smartyank.nvim` configured and it's also a "googleable" issue (there are so many places where things may go wrong if this is a remote session. Specifically, it's the user's responsibility to ensure that remote and local clipboard handlers are compatible with each other).

**Comment by Robin329** [comment]
> I tend to close this as "NAD" (Not A Defect) b/c we can't repro this, already have both `win32yank.exe` and `smartyank.nvim` configured and it's also a "googleable" issue (there are so many places where things may go wrong if this is a remote session. Specifically, it's the user's responsibility to ensure that remote and local clipboard handlers are compatible with each other).

晚点回去复现下哈，需要哪些日志？

**Comment by fecet** [comment]
I think this is actually not a simple question. Clipboard over SSH is a mess for me. For me, I can copy in remote neovim using alacritty, but I can't paste. And kitty doesn't work at all.

**Comment by ayamir** [comment]
I usually use [copyq](https://github.com/hluk/CopyQ) to manage my clipboard.
For ssh connections, I use the `paste` shortcut of the corresponding tool, such as `<C-S-v>` for [tabby terminal](https://tabby.sh/).

**Comment by Robin329** [comment]
更新powershell7可以了
