### ISSUE TITLE
退出时没有格式化

### ISSUE THREAD

**Issue by Deg2v** [ayamir/nvimdots#96]
退出nvim不格式化，这个影响倒是不大；
安装了pylsp后，保存文件一直有下面这个选项，怎么取消这个选择？

![QQ图片20220320230828](https://user-images.githubusercontent.com/49941008/159169060-1a8d4851-b227-4910-b1c7-5d761621fa8f.jpg)

**Comment by ayamir** [comment]
1. 格式化是在保存时执行的，不是在退出时执行的。
2. 默认的efm格式化用的是black，如果pylsp提供了格式化，并且你想用pylsp的格式化功能的话，注释掉这一行即可：https://github.com/ayamir/nvimdots/blob/5177255cb8d07117cd414cad08b01ca255a708c5/lua/modules/completion/lsp.lua#L315
如果你想用black提供的格式化功能，新增如下类似的代码在`enhance_server-opts`变量的代码块中即可（将`tsserver`改成`pylsp`，其余不变）：
https://github.com/ayamir/nvimdots/blob/main/lua/modules/completion/lsp.lua#L203-L216

**Comment by Deg2v** [comment]
我照着上面的方法取消了`black`的格式化，使用了`pylsp`，可以格式化，也没有出现选择了。
另外想问一下：格式化应该是只在保存时进行，保存并退出(`zz`)并不进行格式化吧？

**Comment by ayamir** [comment]
`ZZ`或者`:wq`或者`:wq!`任何要退出的操作都不会触发格式化，准确来讲格式化默认只会在`:w`时执行

**Comment by Deg2v** [comment]
非常感谢，这两天使用很正常，还有一个小问题，改了配置之后，比如改了颜色，`packerCompile`不生效，仍然需要`packerSync`，要花较长时间且会`failed to update`，我想问一下，这种情况怎么用`packerCompile`就能生效？

**Comment by ayamir** [comment]
刚刚修复了这个问题，`git pull`更新一下吧
