### ISSUE TITLE
can not use telescope to find word

### ISSUE THREAD

**Issue by magiceses** [ayamir/nvimdots#963]
### Version confirmation

- [X] Confirm

### Following prerequisites

- [X] Confirm

### Neovim version

NVIM v0.10.0-dev-836+g6d93bdd45-Homebrew

### Operating system/version

macos 12.5

### Terminal name/version

iTem2

### Branch info

main (Default/Latest)

### Fetch Preferences

SSH (use_ssh = true)

### How to reproduce the issue

install the latest version,but can not use telescope to find word in current project!

And it happen error when  <leader>fw:
<img width="1619" alt="image" src="https://github.com/ayamir/nvimdots/assets/50326171/c62c6d2e-af70-4753-9f3d-7a705813692a">

but i can find file in current project.It is a bug?

### Expected behavior

can use telescope to find word in current project

### Actual behavior

can not use telescope to find word in current project!
And it happen error 
<img width="1619" alt="image" src="https://github.com/ayamir/nvimdots/assets/50326171/c62c6d2e-af70-4753-9f3d-7a705813692a">

but i can find file in current project.It is a bug?

**Comment by ayamir** [comment]
Can't repro for me.
Try `rm -fr ~/.local/share/nvim/site/lazy/telescope.nvim` and reopen `nvim`.

**Comment by magiceses** [comment]
After reinstall, same problem. Still, i can use `<leader>ff`, but cannot use `<leader>fw`

**Comment by Groveer** [comment]
> After reinstall, same problem. Still, i can use `<leader>ff`, but cannot use `<leader>fw`

do you install ripgrep in your system?

**Comment by magiceses** [comment]
After install ripgrep, it fix.
Thanks a lot.
close
