### ISSUE TITLE
hover_doc gives error for docker desktop (windows).

### ISSUE THREAD

**Issue by MKrbm** [ayamir/nvimdots#965]
### Version confirmation

- [X] Confirm

### Following prerequisites

- [X] Confirm

### Neovim version

v0.9.1

### Operating system/version

Ubuntu 20.04 ( wsl )

### Terminal name/version

/bin/bash

### Branch info

main (Default/Latest)

### Fetch Preferences

SSH (use_ssh = true)

### How to reproduce the issue

1. Open container with 

``` Dockerfile
# Start with the base Ubuntu image
FROM ubuntu:latest

# Set environment variables to non-interactive (this prevents some prompts)
ENV DEBIAN_FRONTEND=non-interactive

ARG UID=1000
ARG GID=1000

# Update the system and install necessary tools
RUN apt-get update && \
    apt-get install -y curl git sudo make unzip wget x11-apps lldb python3-pip && \
    apt-get clean


# Create a group with GID
RUN groupadd -g $GID user

# Create a user with UID and add it to the group
RUN useradd -m -u $UID -g user user

# Switch to the new user
USER user

# Install nvm
RUN curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.38.0/install.sh | bash

# Set up environment variables for nvm
ENV NVM_DIR /home/user/.nvm
ENV NODE_VERSION 18

# Install Node.js
RUN . "$NVM_DIR/nvm.sh" \
    && nvm install $NODE_VERSION \
    && nvm alias default $NODE_VERSION \
    && nvm use default

# Install rustup and Rust
RUN curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y && \
    . $HOME/.cargo/env && rustup toolchain install nightly # or stable


# Add nvm source to bashrc
RUN echo 'source ~/.nvm/nvm.sh' >> ~/.bashrc

USER root
RUN wget https://github.com/neovim/neovim/releases/download/v0.9.1/nvim-linux64.tar.gz && \
    tar -zxvf nvim-linux64.tar.gz && \
    mv nvim-linux64/bin/nvim usr/bin/nvim && \
    mv nvim-linux64/lib/nvim usr/lib/nvim && \
    mv nvim-linux64/share/nvim/ usr/share/nvim && \
    rm -rf nvim-linux64 && \
    rm nvim-linux64.tar.gz

RUN apt-get install -y python-is-python3 python3-venv ripgrep zoxide


# Install Lazygit
RUN LAZYGIT_VERSION=$(curl -s "https://api.github.com/repos/jesseduffield/lazygit/releases/latest" | grep -Po '"tag_name": "v\K[^"]*') \
    && curl -Lo lazygit.tar.gz "https://github.com/jesseduffield/lazygit/releases/latest/download/lazygit_${LAZYGIT_VERSION}_Linux_x86_64.tar.gz" \
    && tar xf lazygit.tar.gz lazygit \
    && install lazygit /usr/local/bin \
    && rm lazygit lazygit.tar.gz


USER user

RUN pip install pynvim
RUN bash -c "$(curl -fsSL https://raw.githubusercontent.com/ayamir/nvimdots/HEAD/scripts/install.sh)"



# Switch back to root
USER root


# Set display
ENV DISPLAY host.docker.internal:0.0

RUN apt-get update -y\
    && apt-get install x11-apps xclip -y

# Set passwords for user and root
RUN echo 'user:user' | chpasswd # Set password for user
RUN echo 'root:root' | chpasswd

# # Switch back to user
USER user


```

2. Try to invoke "Lspsaga hover_doc" with <S-k> 

![image](https://github.com/ayamir/nvimdots/assets/57752203/69e817e0-1cc2-42cd-a89c-ab5b1afc8006)

### Expected behavior

Open Lspsaga hover_doc.

### Additional information

It works correctly when I run nvimdots in my windows but not in my docker.

Is this a problem of Lspsaga instead of nvimdots?

**Comment by CharlesChiuGit** [comment]
i not sure lsp in wsl with docker would work or not, since every lsp is actually a remote process that communicate with nvim itself via tcp/utp. epically when it's on Windows host, windows defender or other antivirus might have something to do with it too. 

virtualization on windows might also be another road block too.

this is a highly complex problem. im not sure if there's a solution or not.

**Comment by CharlesChiuGit** [comment]
but it could also be a very simple problem, which is invalid installation of the lspsaga plugin. 

u could try to remove it from the plugin folder and reinstall it again to see if that helps.

**Comment by MKrbm** [comment]
I found this problem is much simpler since this problem will be fixed  just by changing 
`  util.close_win(require('diagnostic').winid)` to `  util.close_win(require('lspsaga.diagnostic').winid)`.  at line 326 of `lspsaga.nvim/lua/hover.lua`. 

I don't know why I need this only when I use docker but I'm good for now ! Thank you.

**Comment by CharlesChiuGit** [comment]
maybe consider report it to upstream?

**Comment by MKrbm** [comment]
Yes. Thank you.
