### ISSUE TITLE
关于换行

### ISSUE THREAD

**Issue by JerryAllison** [ayamir/nvimdots#97]
你好，目前的默认换行缩进和tab缩进是8个字符，由于有的代码缩减比较多，能否把默认换行缩进和Tab缩减改成4个字符？

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
 - OS: [e.g. Archlinux/Ubuntu/macOS]
 - Nvim version(output of `nvim --version`)

**Additional context**

**Comment by ayamir** [comment]
看不懂你在说啥，换行和8个字符有什么关系？

**Comment by HATTER-LONG** [comment]
他这是说换行默认的缩进吧，不同文件类型自己设置调整下就行
```lua
//core/event.lua
{ "FileType", "c,cpp", "set expandtab tabstop=4 shiftwidth=4" },
```

**Comment by JerryAllison** [comment]
是的，非常感谢。

**Comment by JerryAllison** [comment]
> 他这是说换行默认的缩进吧，不同文件类型自己设置调整下就行
> 
> ```lua
> //core/event.lua
> { "FileType", "c,cpp", "set expandtab tabstop=4 shiftwidth=4" },
> ```

我没有看修改默认缩进的地方，

**Comment by ayamir** [comment]
我这边从来没有设置过宽度为8的缩进设置，不应该是编辑器的问题，请检查你的格式化器

**Comment by JerryAllison** [comment]
那很奇怪，我之前用vim编辑的代码，最近用nvim修改后，再打开，代码块全乱套了，以前的缩进4个字符，用nvim修改过的缩进8个字符。
