### ISSUE TITLE
How to add xmake.nvim?

### ISSUE THREAD

**Issue by Penguin-SAMA** [ayamir/nvimdots#971]
### Version confirmation

- [X] Confirm

### Following prerequisites

- [X] Confirm

### Neovim version

NVIM v0.9.1

### Operating system/version

macos 14

### Terminal name/version

iterm 2

### Branch info

main (Default/Latest)

### Fetch Preferences

SSH (use_ssh = true)

### How to reproduce the issue

I filled in the following information in `configs/custom/xmake.lua`
``` lua
return function() -- This file MUST return a function accepting no parameter and has no return value
	vim.g.compile_commands_dir = require(".vscode")
end
```
and filled in the following information in `plugins/custom.lua'
```lua
custom["Mythos-404/xmake.nvim"] = {
	lazy = true,
	event = "BufReadPost xmake.lua",
	config = true,
	dependencies = { "MunifTanjim/nui.nvim", "nvim-lua/plenary.nvim" },
}
```
when i type `:w` xmake doesn't work, and it displayed Error code 255
![image](https://github.com/ayamir/nvimdots/assets/50973632/716f6681-73a7-4bd4-9d23-4a74ed078fa9)

### Expected behavior

no error code, xmake.lua can work

**Comment by ayamir** [comment]
You set `config = true` so no need to add an `xmake.lua` as its config file. Remove the `config/custom/xmake.lua`. 
Switch to your work directory and `nvim` the real `xmake.lua` used to config how to build the project.

**Comment by Penguin-SAMA** [comment]
I have removed xmake.lua, but still got the error
<img width="2560" alt="image" src="https://github.com/ayamir/nvimdots/assets/50973632/e6f0ae2a-5609-4964-8378-d30a61fea3ed">

**Comment by ayamir** [comment]
did you install the `xmake` itself?

**Comment by Penguin-SAMA** [comment]
of course, The above file was generated with`$ xmake create -l c -P ./hello`

**Comment by ayamir** [comment]
It works after adding these lines to `lua/modules/plugins/custom.lua`:
```lua
local custom = {}

custom["Mythos-404/xmake.nvim"] = {
	lazy = true,
	event = "BufReadPost xmake.lua",
	config = true,
	dependencies = { "MunifTanjim/nui.nvim", "nvim-lua/plenary.nvim" },
}

return custom
```

**Comment by Penguin-SAMA** [comment]
I found that the problem seems to be that the execution directory of neovim does not match the directory I opened when I use `nvim xmake.lua`

I asked ChatGPT and it replied as follows, where should I add this code
<img width="689" alt="image" src="https://github.com/ayamir/nvimdots/assets/50973632/67b3e8f3-3a2c-41ca-82f8-71bad32ff0dd">
