### ISSUE TITLE
user setting lsp list not replaced default config, but merge with default

### ISSUE THREAD

**Issue by HATTER-LONG** [ayamir/nvimdots#972]
### Version confirmation

- [X] Confirm

### Following prerequisites

- [X] Confirm

### Neovim version

0.9.1

### Branch info

main (Default/Latest)

### Minimal (user) folder structure required to reproduce the issue

```console
user/setting.lua
```

### Minimal config with steps on how to reproduce the issue

```lua
settings["dap_deps"] = {
	"codelldb", 
	-- "delve", --  remove Go
	"python", 
}
```

### Expected behavior

Will still install delve by default, this phenomenon exists in other settings lists.

I think it's  related to the following implementations, `vim.list_extend` will merge list which default and user config.

But I didn't think of any good ways to deal it.

```lua
--- Function to recursively merge src into dst
--- Unlike vim.tbl_deep_extend(), this function extends if the original value is a list
---@paramm dst table @Table which will be modified and appended to
---@paramm src table @Table from which values will be inserted
---@return table @Modified table
local function tbl_recursive_merge(dst, src)
	for key, value in pairs(src) do
		if type(dst[key]) == "table" and type(value) == "function" then
			dst[key] = value()
		elseif type(dst[key]) == "table" and vim.tbl_islist(dst[key]) then
			vim.list_extend(dst[key], value)
		elseif type(dst[key]) == "table" and not vim.tbl_islist(dst[key]) then
			tbl_recursive_merge(dst[key], value)
		else
			dst[key] = value
		end
	end
	return dst
end

```

Add a block list setting  It seems a bit redundant. Perhaps we don't need to specify any lsp by default.

**Comment by ayamir** [comment]
You are right. IMO it's better to replace the default configuration instead of merging them.

**Comment by misumisumi** [comment]
I'm doing a merge implementation to respect the existing settings as much as possible.
If you want to replace it completely, you can set it as follows.

```lua
settings["lsp_deps"] = function()
	return {
		"jsonls",
		"nil_ls",
		"terraformls",
		"texlab",
	}
end
```

**Comment by vollowx** [comment]
Can we provide a param `default` when merging the override settings like:

```lua
settings['lsp_servers'] = function (default)
  return { 'tsserver' }
end
```

This way, users can also merge them by calling `vim....` inside the function while they can completely override them.

**Comment by misumisumi** [comment]
Yeah.
You can implement it like this:
```lua
--- Function to recursively merge src into dst
--- Unlike vim.tbl_deep_extend(), this function extends if the original value is a list
---@paramm dst table @Table which will be modified and appended to
---@paramm src table @Table from which values will be inserted
---@return table @Modified table
local function tbl_recursive_merge(dst, src)
	for key, value in pairs(src) do
		if type(dst[key]) == "table" and type(value) == "function" then
			dst[key] = value(src) -- give `src` as args
		elseif type(dst[key]) == "table" and vim.tbl_islist(dst[key]) then
			vim.list_extend(dst[key], value)
		elseif type(dst[key]) == "table" and not vim.tbl_islist(dst[key]) then
			tbl_recursive_merge(dst[key], value)
		else
			dst[key] = value
		end
	end
	return dst
end
```

**Comment by HATTER-LONG** [comment]
Using return functions is a good way to avoid it, but it's needed to improve some wiki info for it. 😊

**Comment by CharlesChiuGit** [comment]
> I'm doing a merge implementation to respect the existing settings as much as possible. If you want to replace it completely, you can set it as follows. It is easy to understand whether the default settings are maintained or completely replaced, so I think that the current state of using functions is fine.
> 
> ```lua
> settings["dap_deps"] = function()
>     return {
>         "codelldb", -- C-Family
>         "python", -- Python (debugpy)
>     }
> end
> ```

agree
