### ISSUE TITLE
怎么样设置一个shell脚本默认开头自动填充啊，谢谢

### ISSUE THREAD

**Issue by QianSong1** [ayamir/nvimdots#974]
### Version confirmation

- [X] Confirm

### Following prerequisites

- [X] Confirm

### Neovim version

0.9.1

### Branch info

main (Default/Latest)

### Minimal (user) folder structure required to reproduce the issue

```console
╰─ tree lua/user
lua/user
├── configs
│   ├── dap-clients
│   └── lsp-servers
├── event.lua
├── keymap
│   ├── completion.lua
│   ├── core.lua
│   ├── editor.lua
│   ├── init.lua
│   ├── lang.lua
│   ├── tool.lua
│   └── ui.lua
├── options.lua
├── plugins
└── settings.lua
```

### Minimal config with steps on how to reproduce the issue

不知道怎么配置，我只需要这个功能，高级的也不会玩

### Expected behavior

打开一个新的.sh脚本，自动填充默认开头信息
比如这样：
#!/bin/bash
#
#******************************************************************************************
#Author:                QianSong
#QQ:                    xxxxxxxxxx
#Date:                  2023-08-28
#FileName:              my_test_script.sh
#URL:                   https://github.com
#Description:           The test script
#Copyright (C):         QianSong 2023 All rights reserved
#******************************************************************************************

**Comment by ayamir** [comment]
FYI: https://sauravomar01.medium.com/configure-custom-header-template-in-vim-editor-6d578e440da3

**Comment by nkta3m** [comment]
https://github.com/alpertuna/vim-header
这个插件可以试试看

**Comment by CharlesChiuGit** [comment]
close for inactive

**Comment by Jint-lzxy** [comment]
u can also have a look at https://github.com/ayamir/nvimdots/discussions/879. This is the simplest approach IMO.
