### ISSUE TITLE
two issue: clipboard and mason

### ISSUE THREAD

**Issue by jwangtobeno1** [ayamir/nvimdots#978]
### Version confirmation

- [X] Confirm

### Following prerequisites

- [X] Confirm

### Not a user config issue

- [X] Confirm

### Neovim version

NVIM v0.9.1

### Operating system/version

WSL2

### Terminal name/version

WSL2

### Branch info

main (Default/Latest)

### Fetch Preferences

SSH (use_ssh = true)

### How to reproduce the issue

First issue:

when i use 'x' (cut) , then show a error:

Error detected while processing function provider#clipboard#Call[9] .. function provider# ....
E475: Invalid value for argument cmd: 'win32yank.exe' is not executable

Secend issue:

Every time I start nvim， it is show:
![image](https://github.com/ayamir/nvimdots/assets/69038155/27394aae-1fce-4906-8e32-d36309c547fb)

[mason-lspconfig.nvim] failed to xxxxxxxx

### Expected behavior

for 'x' : Realize the cutting function like vim

for mason :  Don't want these tips

**Comment by jwangtobeno1** [comment]
I found a solution for trying, but:

How to set Neovim's clipboard to unnamedplus using `set clipboard=unnamedplus` ?

**Comment by Lraxer** [comment]
1. Do you use `win32yank.exe`? Please check the doc https://github.com/ayamir/nvimdots/wiki/Issues#clipboard-for-wsl2-users .
2. Can you provide more logs by `:MasonLog`?

**Comment by jwangtobeno1** [comment]
Thank you for your answer！

Since it was my first time to use nvim and lua, I read the help and said to set the following:

`let g:clipboard = {
  \   'name': 'WslClipboard',
  \   'copy': {
  \      '+': 'clip.exe',
  \      '*': 'clip.exe',
  \    },
  \   'paste': {
  \      '+': 'powershell.exe -c [Console]::Out.Write($(Get-Clipboard -Raw).tostring().replace("`r", ""))',
  \      '*': 'powershell.exe -c [Console]::Out.Write($(Get-Clipboard -Raw).tostring().replace("`r", ""))',
  \   },
  \   'cache_enabled': 0,
  \ }`

But I don't know which file to write these to.       `init.nvim`?

**Comment by jwangtobeno1** [comment]
The following is masonlog:

[INFO  Wed 30 Aug 2023 09:55:18 PM CST] ...m/site/lazy/mason.nvim/lua/mason-core/installer/init.lua:184: Executing installer for Package(name=clang-format) {}
[INFO  Wed 30 Aug 2023 09:55:18 PM CST] ...m/site/lazy/mason.nvim/lua/mason-core/installer/init.lua:184: Executing installer for Package(name=prettier) {}
[INFO  Wed 30 Aug 2023 09:55:18 PM CST] ...m/site/lazy/mason.nvim/lua/mason-core/installer/init.lua:184: Executing installer for Package(name=shfmt) {}
[INFO  Wed 30 Aug 2023 09:55:18 PM CST] ...m/site/lazy/mason.nvim/lua/mason-core/installer/init.lua:184: Executing installer for Package(name=stylua) {}
[INFO  Wed 30 Aug 2023 09:55:18 PM CST] ...m/site/lazy/mason.nvim/lua/mason-core/installer/init.lua:184: Executing installer for Package(name=vint) {}
[ERROR Wed 30 Aug 2023 09:55:18 PM CST] ...m/site/lazy/mason.nvim/lua/mason-core/installer/init.lua:249: Installation failed for Package(name=prettier) error=spawn: npm failed with exit code - and signal -. npm is not executable
[INFO  Wed 30 Aug 2023 09:55:20 PM CST] ...m/site/lazy/mason.nvim/lua/mason-core/installer/init.lua:184: Executing installer for Package(name=bash-language-server) {}
[INFO  Wed 30 Aug 2023 09:55:20 PM CST] ...m/site/lazy/mason.nvim/lua/mason-core/installer/init.lua:245: Installation succeeded for Package(name=shfmt)
[INFO  Wed 30 Aug 2023 09:55:20 PM CST] ...m/site/lazy/mason.nvim/lua/mason-core/installer/init.lua:184: Executing installer for Package(name=clangd) {}
[ERROR Wed 30 Aug 2023 09:55:20 PM CST] ...m/site/lazy/mason.nvim/lua/mason-core/installer/init.lua:249: Installation failed for Package(name=bash-language-server) error=spawn: npm failed with exit code - and signal -. npm is not executable

**Comment by jwangtobeno1** [comment]
Thanks, First issue is sloved by add `win32yank.exe`  to my $PATH.

**Comment by CharlesChiuGit** [comment]
> Installation failed for Package(name=prettier) error=spawn: npm failed with exit code - and signal -. npm is not executable

make sure you got `npm` installed and nvim can read it from the $PATH.

**Comment by jwangtobeno1** [comment]
Thanks @CharlesChiuGit , The second issue is sloved by install npm.
