### ISSUE TITLE
how to modify markdown-preview.nvim?

### ISSUE THREAD

**Issue by Penguin-SAMA** [ayamir/nvimdots#979]
### Version confirmation

- [X] Confirm

### Following prerequisites

- [X] Confirm

### Not a user config issue

- [X] Confirm

### Neovim version

NVIM v0.9.1

### Operating system/version

macos 14

### Terminal name/version

iterm 2

### Branch info

main (Default/Latest)

### Fetch Preferences

SSH (use_ssh = true)

### How to reproduce the issue

I want to change some features about markdown-preview.nvim, such as changing the default browser to safari, how should I do it?

### Expected behavior

same

**Comment by Penguin-SAMA** [comment]
and i get a bug
when i only type 
```` markdown
```cpp and enter
````
It will automatically output the code snippet I entered earlier

like this 
<img width="626" alt="image" src="https://github.com/ayamir/nvimdots/assets/50973632/38be9073-80cd-4d0f-9753-14cef5acd1e8">

**Comment by CharlesChiuGit** [comment]
https://github.com/ayamir/nvimdots/issues/new?assignees=&labels=usage&projects=&template=custom_config.yml

dont u see there's a issue template for custom settgins?

**Comment by CharlesChiuGit** [comment]
the later it's probably copilot

**Comment by Penguin-SAMA** [comment]
sry
