### ISSUE TITLE
efm-langserver:  Error while opening a new .cc file

### ISSUE THREAD

**Issue by Shipley1105** [ayamir/nvimdots#98]
> Spawning language server with cmd: `efm-langserver` failed with error message:  EACCES:  permission denied

Could you give me some suggestiones?

After `LspInfo` it report efm-langserver unable to find executable? Should I install efm-langserver manmualy, or it will be installed automatically?

**Comment by ayamir** [comment]
I have illustrated it in here: https://github.com/ayamir/nvimdots/wiki/Prerequisites
![efm-illustration](https://user-images.githubusercontent.com/61657399/160279224-f7f4d04b-5f46-4b85-9718-34b83c81da7a.png)

**Comment by Shipley1105** [comment]
Thanks you for your fast response. I'm new to nvim, yuo did such a great job which is key for me to enter into nvim world.

**Comment by kevin-roan** [comment]
instead of using go to install that, use `yay -S efm-langserver`
