### ISSUE TITLE
Failed to install pylsp

### ISSUE THREAD

**Issue by Robin329** [ayamir/nvimdots#980]
### Version confirmation

- [X] Confirm

### Following prerequisites

- [X] Confirm

### Not a user config issue

- [X] Confirm

### Neovim version

NVIM v0.9.1

### Operating system/version

Linux 103-SOC 4.15.0-213-generic #224-Ubuntu SMP Mon Jun 19 13:30:12 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

### Terminal name/version

Terminal

### $TERM environment variable

xterm-256color

### Branch info

main (Default/Latest)

### Fetch Preferences

SSH (use_ssh = true)

### Affected language servers

clang-format

### How to reproduce the issue

正常启动nvim

### Actual behavior

报如下错误：
![image](https://github.com/ayamir/nvimdots/assets/22770951/504ccfef-2d72-465f-9e43-9b10dba89576)

### Support info

:Lspinfo
![image](https://github.com/ayamir/nvimdots/assets/22770951/5519efc0-62fc-4b11-a049-ac5c2a52edb8)

:MasonLog

![image](https://github.com/ayamir/nvimdots/assets/22770951/6dd76acc-5990-43cd-9bcd-9bb2aef84f1f)

**Comment by CharlesChiuGit** [comment]
could just delete the old `$HOME/.local/state/nvim/mason.log` and `$HOME/.local/state/nvim/lsp.log`, reopen nvim, and show us those two log again?

**Comment by ayamir** [comment]
install `python3-venv`

**Comment by Robin329** [comment]
sudo apt install python3-venv已经安装过了。

LSPinfo:
![image](https://github.com/ayamir/nvimdots/assets/22770951/b17a7dcc-ebcb-4121-b7fb-12185c65125e)
masonlog:
![image](https://github.com/ayamir/nvimdots/assets/22770951/66c2e312-1494-430a-80af-59ff5fdbdea1)

**Comment by CharlesChiuGit** [comment]
what do u think we can possibly know from a cut-off sentence which is pretty much meaningless?

I had already told u where to find the actual log files, please give me the content via
`cat $HOME/.local/state/nvim/mason.log`
and 
`cat $HOME/.local/state/nvim/lsp.log`.

tks a lot for your cooperation.

**Comment by CharlesChiuGit** [comment]
please run `:chechealth` in nvim too.

**Comment by Robin329** [comment]
![image](https://github.com/ayamir/nvimdots/assets/22770951/af36843f-68f9-4869-8773-3e1aaab77656)

**Comment by CharlesChiuGit** [comment]
after some study, it **might** related to python mirror issue.[^1][^2]

could u try manually install a earlier version of `pylsp` and see how things go?
`:MasonInstall pylsp@1.7.3` or `:MasonInstall pylsp@1.7.2`


[^1]: https://www.reddit.com/r/neovim/comments/137gy6n/mason_install_fails_for_python_server/
[^2]: https://github.com/microsoft/debugpy/issues/1345

**Comment by Robin329** [comment]
![image](https://github.com/ayamir/nvimdots/assets/22770951/59493788-3982-4545-8e0a-f06a8f111300)

**Comment by Robin329** [comment]
![image](https://github.com/ayamir/nvimdots/assets/22770951/f3ee7297-2c9d-4570-a29e-bba02771ffa0)

**Comment by CharlesChiuGit** [comment]
sorry, it should be python-lsp-server, not pylsp

https://github.com/mason-org/mason-registry/blob/main/packages/python-lsp-server/package.yaml

**Comment by ayamir** [comment]
A better way to show the log is view it in `:Mason` float window.
So we can check it failed at which step.
![图片](https://github.com/ayamir/nvimdots/assets/61657399/a0d6703a-3406-40de-935e-3f588ae089f8)

**Comment by Jint-lzxy** [comment]
I think the problem comes from this line (checkhealth):
```console
Python version: 3.6.9
```
The pip version provided by ensurepip (python3.6-venv) would then be _very very_ old. But since Mason has completely disabled version checks (by default), you should see pip fails fast with a concise message telling you that you must update it before proceeding if you have debug mode enabled:
```console
/home/renbin.jiang/.local/share/nvim/mason/packages/python-lsp-server/venv/bin/python -m pip --disable-pip-version-check install pylsp
```

**Comment by Robin329** [comment]
![image](https://github.com/ayamir/nvimdots/assets/22770951/d3a05915-fcf9-4ac4-b1bf-425140fae7f4)

**Comment by CharlesChiuGit** [comment]
try
```bash
$HOME/.local/share/nvim/mason/packages/clang-format/venv/bin/pip3 install wheel
```

**Comment by Robin329** [comment]
> try
> 
> ```shell
> $HOME/.local/share/nvim/mason/packages/clang-format/venv/bin/pip3 install wheel
> ```
> 
> if pylsp had same error, try similar command but in `python-lsp-server` folder

```sh
renbin.jiang@103-SOC:~/.local$ $HOME/.local/share/nvim/mason/packages/clang-format/venv/bin/pip3 install wheel
-bash: /home/renbin.jiang/.local/share/nvim/mason/packages/clang-format/venv/bin/pip3: No such file or directory
```

**Comment by Robin329** [comment]
可能是clang-format的版本太新而python版本太旧的原因？

**Comment by Jint-lzxy** [comment]
> 可能是clang-format的版本太新而python版本太旧的原因？

Ys I would suggest upgrading your Python distribution. Because AFAIU Mason doesn't support such ancient distribution (≤3.9).

**Comment by Robin329** [comment]
就是对于服务器没有联网的话，从另一个联网的服务器已经安装好的nvim，拷贝到没有联网的服务器会有问题。有什么离线安装更好的解决方案呢？

**Comment by Jint-lzxy** [comment]
Well u need to [build Python from source](https://devguide.python.org/getting-started/setup-building/index.html) then.

**Comment by ayamir** [comment]
> 就是对于服务器没有联网的话，从另一个联网的服务器已经安装好的nvim，拷贝到没有联网的服务器会有问题。有什么离线安装更好的解决方案呢？

```shell
cd ~/.config
tar cfJ nvim.tar.xz ./nvim
scp -P <port> nvim.tar.xz <username>@<hostname>:/home/<username>/.config/
cd ~/.local/share
tar cfJ nvim.tar.xz ./nvim
scp -P <port> nvim.tar.xz <username>@<hostname>:/home/<username>/.local/share/
```
then login to another machine and `tar xpvf` them.

**Comment by fecet** [comment]
> 就是对于服务器没有联网的话，从另一个联网的服务器已经安装好的nvim，拷贝到没有联网的服务器会有问题。有什么离线安装更好的解决方案呢？

硬件差不多就没啥问题吧, 我就是这样
```
rsync -avP stat1:~/codes/nvim/ ~/.config/nvim/ --delete
rsync -avP stat1:~/.local/share/nvim/ ~/.local/share/nvim/ --delete
rsync -avP stat1:~/.local/share/bob/ ~/.local/share/bob/ --delete
rsync -avP stat1:~/.cache/nvim/ ~/.cache/nvim/ --delete

```

**Comment by Robin329** [comment]
> > 就是对于服务器没有联网的话，从另一个联网的服务器已经安装好的nvim，拷贝到没有联网的服务器会有问题。有什么离线安装更好的解决方案呢？
> 
> 硬件差不多就没啥问题吧, 我就是这样
> 
> ```
> rsync -avP stat1:~/codes/nvim/ ~/.config/nvim/ --delete
> rsync -avP stat1:~/.local/share/nvim/ ~/.local/share/nvim/ --delete
> rsync -avP stat1:~/.local/share/bob/ ~/.local/share/bob/ --delete
> rsync -avP stat1:~/.cache/nvim/ ~/.cache/nvim/ --delete
> ```

硬件有差异，一个是WSL里面安装没问题的nvim，然后拷贝到远程服务器，远程服务器Linux版本不一样。

**Comment by Robin329** [comment]
```sh
rsync -avP stat1:~/codes/nvim/ ~/.config/nvim/ --delete
rsync -avP stat1:~/.local/share/nvim/ ~/.local/share/nvim/ --delete
rsync -avP stat1:~/.local/share/bob/ ~/.local/share/bob/ --delete
rsync -avP stat1:~/.cache/nvim/ ~/.cache/nvim/ --delete
```
可以解决
