### ISSUE TITLE
Please change the preset 'lua/user' to 'lua/user_template' or others

### ISSUE THREAD

**Issue by popjdh** [ayamir/nvimdots#984]
### Version confirmation

- [X] Confirm

### Following prerequisites

- [X] Confirm

### Not a user config issue

- [X] Confirm

### Neovim version

NVIM v0.9.1

### Operating system/version

ArchLinux 6.1.50-1-lts

### Terminal name/version

zsh 5.9-4

### Branch info

main (Default/Latest)

### Fetch Preferences

HTTPS (use_ssh = false)

### How to reproduce the issue

Although there is "lua/user" in gitignore, this directory has already been tracked by git.
Causes user's custom actions to be incorrectly tracked by git.

### Expected behavior

Please change the preset 'lua/user' to 'lua/user_template' or others.

**Comment by CharlesChiuGit** [comment]
can confirm. would u like to propose a pr and edit the wiki?
