### ISSUE TITLE
remove lua/user_template on .config/nvim?

### ISSUE THREAD

**Issue by Tunghohin** [ayamir/nvimdots#989]
### Version confirmation

- [X] Confirm

### Following prerequisites

- [X] Confirm

### Not a user config issue

- [X] Confirm

### Neovim version

NVIM v0.9.1

### Operating system/version

Ubuntu 22.04

### Terminal name/version

ubuntu terminal

### Branch info

main (Default/Latest)

### Fetch Preferences

SSH (use_ssh = true)

### How to reproduce the issue

The lua/user_template directory in .config/nvim created during install seems to be temporary.

### Expected behavior

remove it after the copy is complete

**Comment by CharlesChiuGit** [comment]
it's intended. see #984 #985 #986
