### ISSUE TITLE
是否考虑增加 YouCompleteMe 插件支持呢？

### ISSUE THREAD

**Issue by lushenle** [ayamir/nvimdots#99]
目前感觉代码补全还不是那么的完美，比如 golang 自动导入依赖包，函数完整提示还没有。
是否考虑集成 YouCompleteMe 插件来做代码补全呢？

**Comment by ayamir** [comment]
以`nvim-lspconfig`为核心的代码补全应该是原生且未来的趋势，暂没有时间新增ycm的配置

**Comment by ttbug** [comment]
> 目前感觉代码补全还不是那么的完美，比如 golang 自动导入依赖包，函数完整提示还没有。 是否考虑集成 YouCompleteMe 插件来做代码补全呢？

使用vim-go + gopls开发go应该已经能达到vscode的水平了，自动导入和函数提示也都正常，应该是你的配置或者是使用有问题

**Comment by Shipley1105** [comment]
`LspInstall c`后面选择安装clangd，请问如何goto denfiniton ?

**Comment by Shipley1105** [comment]
感谢回答。
那我打开一个工程如何自动intellisence，实现整个工程内各个模块跳转呢，比如打开webrtc？

**Comment by ayamir** [comment]
> 感谢回答。 那我打开一个工程如何自动intellisence，实现整个工程内各个模块跳转呢，比如打开webrtc？

这个要视不同lsp的支持能力
