### ISSUE TITLE
The mfussenegger/nvim-treehopper is missing from the list of plugins in the documentation.

### ISSUE THREAD

**Issue by Tunghohin** [ayamir/nvimdots#992]
### Version confirmation

- [X] Confirm

### Following prerequisites

- [X] Confirm

### Not a user config issue

- [X] Confirm

### Neovim version

NVIM v0.9.1

### Operating system/version

Ubuntu 22.04

### Terminal name/version

ubuntu terminal

### Branch info

main (Default/Latest)

### Fetch Preferences

SSH (use_ssh = true)

### How to reproduce the issue

The mfussenegger/nvim-treehopper is missing from the list of plugins in the documentation, but it is indeed installed.

### Expected behavior

fix it?

**Comment by ayamir** [comment]
Updated.
