### ISSUE TITLE
The interface of lazygit has no focus

### ISSUE THREAD

**Issue by justforlxz** [ayamir/nvimdots#995]
### Version confirmation

- [X] Confirm

### Following prerequisites

- [X] Confirm

### Not a user config issue

- [X] Confirm

### Neovim version

NVIM v0.9.1

### Operating system/version

macOS 13

### Terminal name/version

kitty 0.29.2

### $TERM environment variable

xterm-256color

### Branch info

main (Default/Latest)

### Fetch Preferences

SSH (use_ssh = true)

### How to reproduce the issue

When space+g opens lazygit, a cursor will be displayed, but lazygit cannot gain focus.

### Expected behavior

Can operate lazygit

### Additional information

https://github.com/ayamir/nvimdots/assets/12298476/dea40d84-d39e-4ba7-b1b4-90c27499fc1a

**Comment by CharlesChiuGit** [comment]
press "i" when the cursor is on the lazygit buffer

**Comment by vollowx** [comment]
But I think the terminal floating window shouldn't lost its focus anyway. I've tested on both Linux and Windows platform, sometimes the window lost its focus for some commands inside it like `pnpm install ...`, and it also lost its focus when my mouse move over the whole NeoVim window, IDK the reasons.
