### ISSUE TITLE
core/options.lua:136: E474: Invalid argument

### ISSUE THREAD

**Issue by erqiu-sj** [ayamir/nvimdots#997]
### Version confirmation

- [X] Confirm

### Following prerequisites

- [X] Confirm

### Not a user config issue

- [X] Confirm

### Neovim version

NVIM v0.9.0-dev-162+g40791f8e8 Build type: RelWithDebInfo LuaJIT 2.1.0-beta3 Compilation: /Applications/Xcode_13.2.1.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1 -DNVIM_TS_HAS_SET_MATCH_LIMIT -DNVIM_TS_HAS_SET_ALLOCATOR -O2 -g -Wall -Wextra -pedantic -Wno-unused-parameter -Wstrict-prototypes -std=gnu99 -Wshadow -Wconversion -Wdouble-promotion -Wmissing-noreturn -Wmissing-format-attribute -Wmissing-prototypes -Wimplicit-fallthrough -Wvla -fstack-protector-strong -fno-common -fdiagnostics-color=always -DINCLUDE_GENERATED_DECLARATIONS -DNVIM_MSGPACK_HAS_FLOAT32 -DNVIM_UNIBI_HAS_VAR_FROM -DMIN_LOG_LEVEL=3 -I/Users/runner/work/neovim/neovim/build/cmake.config -I/Users/runner/work/neovim/neovim/src -I/Users/runner/work/neovim/neovim/.deps/usr/include -I/Applications/Xcode_13.2.1.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.1.sdk/usr/include -I/Library/Frameworks/Mono.framework/Headers -I/Users/runner/work/neovim/neovim/build/src/nvim/auto -I/Users/runner/work/neovim/neovim/build/include 编译者 runner@Mac-1666676165240.local  Features: +acl +iconv +tui See ":help feature-compile"       系统 vimrc 文件: "$VIM/sysinit.vim"          $VIM 预设值: "/share/nvim"  Run :checkhealth for more info

### Operating system/version

macOs Sonoma beta 14.0

### Terminal name/version

iterm2 3.4.20

### Branch info

main (Default/Latest)

### Fetch Preferences

SSH (use_ssh = true)

### How to reproduce the issue

我按照wiki中 https://github.com/ayamir/nvimdots/wiki/Prerequisites#required-packages-installation-for-macos-tested-on-apple-m2 初始化
并且进入nvim 执行
lua require('core').sync() 同步插件

### Expected behavior

预计能够直接使用

### Actual behavior

报错

处理 /Users/devops/.config/nvim/init.lua 时发生错误:
E5113: Error while calling lua chunk: /Users/devops/.config/nvim/lua/core/options.lua:136: E474: Invalid argument
stack traceback:
        [C]: in function '__newindex'
        /Users/devops/.config/nvim/lua/core/options.lua:136: in function 'load_options'
        /Users/devops/.config/nvim/lua/core/options.lua:140: in main chunk
        [C]: in function 'require'
        /Users/devops/.config/nvim/lua/core/init.lua:155: in function 'load_core'
        /Users/devops/.config/nvim/lua/core/init.lua:167: in main chunk
        [C]: in function 'require'
        /Users/devops/.config/nvim/init.lua:2: in main chunk

**Comment by CharlesChiuGit** [comment]
u must have some syntax errors when u set the option table, check again.
i'm using unmodified nvim config on m2 mac mini,  no problem at all.

**Comment by erqiu-sj** [comment]
> 你设置选项表时肯定有一些语法错误，请再次检查。 我在 m2 mac mini 上使用未修改的 nvim 配置，完全没有问题。

But I pulled the repository directly down and didn't change any configuration What is the problem?

**Comment by ayamir** [comment]
Don't use self-compiled `nvim`. `brew install neovim` directly.

**Comment by ayamir** [comment]
close due to inactivity.
