### ISSUE TITLE
after executing ‘nvim’，call `space f r`,  show : "E5108: Error excuting lua: .../sqlite/init.lua: loop or previous error loading module 'sqlite.db'

### ISSUE THREAD

**Issue by Dovahkinn** [ayamir/nvimdots#998]
### Version confirmation

- [X] Confirm

### Following prerequisites

- [X] Confirm

### Not a user config issue

- [X] Confirm

### Neovim version

0.9.1

### Operating system/version

windows 11

### Terminal name/version

windows powershell

### Branch info

main (Default/Latest)

### Fetch Preferences

SSH (use_ssh = true)

### How to reproduce the issue

1. open windows powershell
2. ```nvim```
3.  ```space f r```
4. show error "E5108: Error excuting..."
    <img width="761" alt="image" src="https://github.com/ayamir/nvimdots/assets/17044194/b1507d6e-1932-407c-ba06-1056257899f0">
6.  press enter: 
    <img width="588" alt="image" src="https://github.com/ayamir/nvimdots/assets/17044194/c5d3b104-6b48-4d0e-9b0f-acf460444813">

### Expected behavior

命令正常执行，或者我自己应该如何修复

**Comment by CharlesChiuGit** [comment]
check wiki first
